/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cLH
 */
public class clh_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setAlign(frk_0.i);
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("size");
        fiy_12.setField("backgroundSize");
        fiy_12.setName("backgroundDisplay");
        fid_12.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fid_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso2.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        String string = "background";
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fsk_02);
        }
        fso2.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("visible");
        fiy_13.setField("backgroundImage");
        fiy_13.setName("backgroundDisplay");
        fsk_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        fiy_13.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fsk_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("texture");
        fiy_14.setField("backgroundImage");
        fiy_14.setName("backgroundDisplay");
        fqv2.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_03);
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso4;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso4.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        String string2 = "margin1";
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fqm_02);
        }
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fso4.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_03);
        fso4.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.i);
        fid_15.setSize(new fjf_2(100.0f, 100.0f));
        fso6.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("visible");
        fiy_15.setField("leftPage/templateLayoutId");
        fiy_15.setName("backgroundDisplay");
        fso6.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        fiy_15.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fat_2 fat_22 = new fat_2();
        fat_22.onCheckOut();
        fat_22.setElementMap(fyy_03);
        fat_22.setValue("1");
        far_23.addBasicElement(fat_22);
        fat_22.onAttributesInitialized();
        fat_22.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_15.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.b);
        fin_23.setHorizontal(false);
        fso6.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        String string3 = "text1";
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fuk_02);
        }
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(400);
        fuk_02.setMinWidth(400);
        fuk_02.setStyle("background");
        fso6.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("text");
        fiy_16.setField("leftPage/text1");
        fiy_16.setName("backgroundDisplay");
        fuk_02.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_03);
        fqg_02.setColor(new fyr_0("backgroundBookColor"));
        fqh_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso6.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso4.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_03);
        fid_16.setAlign(frk_0.i);
        fid_16.setSize(new fjf_2(100.0f, 100.0f));
        fso7.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_03);
        fiy_17.setAttribute("visible");
        fiy_17.setField("leftPage/templateLayoutId");
        fiy_17.setName("backgroundDisplay");
        fso7.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_03);
        fiy_17.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fat_2 fat_23 = new fat_2();
        fat_23.onCheckOut();
        fat_23.setElementMap(fyy_03);
        fat_23.setValue("2");
        far_24.addBasicElement(fat_23);
        fat_23.onAttributesInitialized();
        fat_23.onChildrenAdded();
        far_24.onChildrenAdded();
        fiy_17.onChildrenAdded();
        String string4 = "image1";
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_03);
        if (fyy_03 != null && string4 != null) {
            fyy_03.a(string4, fsk_03);
        }
        fso7.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_03);
        fiy_18.setAttribute("visible");
        fiy_18.setField("leftPage/imageUrl");
        fiy_18.setName("backgroundDisplay");
        fsk_03.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_03);
        fiy_18.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_03);
        far_25.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_25.onChildrenAdded();
        fiy_18.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_03);
        fsk_03.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_03);
        fiy_19.setAttribute("texture");
        fiy_19.setField("leftPage/imageUrl");
        fiy_19.setName("backgroundDisplay");
        fqv3.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        fiy_19.onChildrenAdded();
        fqv3.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fso7.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso4.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_03);
        fid_17.setAlign(frk_0.i);
        fid_17.setSize(new fjf_2(100.0f, 100.0f));
        fso8.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_03);
        fiy_110.setAttribute("visible");
        fiy_110.setField("leftPage/templateLayoutId");
        fiy_110.setName("backgroundDisplay");
        fso8.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        far_2 far_26 = new far_2();
        far_26.onCheckOut();
        far_26.setElementMap(fyy_03);
        fiy_110.addBasicElement(far_26);
        far_26.onAttributesInitialized();
        fat_2 fat_24 = new fat_2();
        fat_24.onCheckOut();
        fat_24.setElementMap(fyy_03);
        fat_24.setValue("3");
        far_26.addBasicElement(fat_24);
        fat_24.onAttributesInitialized();
        fat_24.onChildrenAdded();
        far_26.onChildrenAdded();
        fiy_110.onChildrenAdded();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.b);
        fin_24.setHorizontal(false);
        fso8.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_03);
        fso9.setExpandable(false);
        fso8.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setAlign(frs_0.d);
        fso9.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        String string5 = "image2";
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_03);
        if (fyy_03 != null && string5 != null) {
            fyy_03.a(string5, fsk_04);
        }
        fsk_04.setExpandable(false);
        fso9.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fiy_1 fiy_111 = fiy_1.checkOut();
        fiy_111.setElementMap(fyy_03);
        fiy_111.setAttribute("visible");
        fiy_111.setField("leftPage/imageUrl");
        fiy_111.setName("backgroundDisplay");
        fsk_04.addBasicElement(fiy_111);
        fiy_111.onAttributesInitialized();
        far_2 far_27 = new far_2();
        far_27.onCheckOut();
        far_27.setElementMap(fyy_03);
        fiy_111.addBasicElement(far_27);
        far_27.onAttributesInitialized();
        fab_2 fab_24 = new fab_2();
        fab_24.onCheckOut();
        fab_24.setElementMap(fyy_03);
        far_27.addBasicElement(fab_24);
        fab_24.onAttributesInitialized();
        fab_24.onChildrenAdded();
        far_27.onChildrenAdded();
        fiy_111.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_03);
        fsk_04.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fiy_1 fiy_112 = fiy_1.checkOut();
        fiy_112.setElementMap(fyy_03);
        fiy_112.setAttribute("texture");
        fiy_112.setField("leftPage/imageUrl");
        fiy_112.setName("backgroundDisplay");
        fqv4.addBasicElement(fiy_112);
        fiy_112.onAttributesInitialized();
        fiy_112.onChildrenAdded();
        fqv4.onChildrenAdded();
        fsk_04.onChildrenAdded();
        String string6 = "text2";
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_03);
        if (fyy_03 != null && string6 != null) {
            fyy_03.a(string6, fuk_04);
        }
        fuk_04.setExpandable(false);
        fuk_04.setMaxWidth(200);
        fuk_04.setMinWidth(200);
        fuk_04.setStyle("background");
        fso9.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.b);
        fuk_04.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fiy_1 fiy_113 = fiy_1.checkOut();
        fiy_113.setElementMap(fyy_03);
        fiy_113.setAttribute("text");
        fiy_113.setField("leftPage/text1");
        fiy_113.setName("backgroundDisplay");
        fuk_04.addBasicElement(fiy_113);
        fiy_113.onAttributesInitialized();
        fiy_113.onChildrenAdded();
        fuk_0 fuk_05 = fuk_04;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_05).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fuk_04.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqg_0 fqg_03 = fqg_0.checkOut();
        fqg_03.setElementMap(fyy_03);
        fqg_03.setColor(new fyr_0("backgroundBookColor"));
        fqh_03.addBasicElement(fqg_03);
        fqg_03.onAttributesInitialized();
        fqg_03.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fso9.onChildrenAdded();
        String string7 = "text3";
        fuk_0 fuk_06 = new fuk_0();
        fuk_06.onCheckOut();
        fuk_06.setElementMap(fyy_03);
        if (fyy_03 != null && string7 != null) {
            fyy_03.a(string7, fuk_06);
        }
        fuk_06.setExpandable(false);
        fuk_06.setMaxWidth(400);
        fuk_06.setMinWidth(400);
        fuk_06.setStyle("background");
        fso8.addBasicElement(fuk_06);
        fuk_06.onAttributesInitialized();
        fiy_1 fiy_114 = fiy_1.checkOut();
        fiy_114.setElementMap(fyy_03);
        fiy_114.setAttribute("text");
        fiy_114.setField("leftPage/text2");
        fiy_114.setName("backgroundDisplay");
        fuk_06.addBasicElement(fiy_114);
        fiy_114.onAttributesInitialized();
        fiy_114.onChildrenAdded();
        fuk_0 fuk_07 = fuk_06;
        fqh_0 fqh_04 = (fqh_0)((fvE)fuk_07).getAppearance();
        fqh_04.setElementMap(fyy_03);
        fuk_06.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqg_0 fqg_04 = fqg_0.checkOut();
        fqg_04.setElementMap(fyy_03);
        fqg_04.setColor(new fyr_0("backgroundBookColor"));
        fqh_04.addBasicElement(fqg_04);
        fqg_04.onAttributesInitialized();
        fqg_04.onChildrenAdded();
        fqh_04.onChildrenAdded();
        fuk_06.onChildrenAdded();
        fso8.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        fso4.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fid_1 fid_18 = new fid_1();
        fid_18.onCheckOut();
        fid_18.setElementMap(fyy_03);
        fid_18.setAlign(frk_0.i);
        fid_18.setSize(new fjf_2(100.0f, 100.0f));
        fso10.addBasicElement(fid_18);
        fid_18.onAttributesInitialized();
        fid_18.onChildrenAdded();
        fiy_1 fiy_115 = fiy_1.checkOut();
        fiy_115.setElementMap(fyy_03);
        fiy_115.setAttribute("visible");
        fiy_115.setField("leftPage/templateLayoutId");
        fiy_115.setName("backgroundDisplay");
        fso10.addBasicElement(fiy_115);
        fiy_115.onAttributesInitialized();
        far_2 far_28 = new far_2();
        far_28.onCheckOut();
        far_28.setElementMap(fyy_03);
        fiy_115.addBasicElement(far_28);
        far_28.onAttributesInitialized();
        fat_2 fat_25 = new fat_2();
        fat_25.onCheckOut();
        fat_25.setElementMap(fyy_03);
        fat_25.setValue("4");
        far_28.addBasicElement(fat_25);
        fat_25.onAttributesInitialized();
        fat_25.onChildrenAdded();
        far_28.onChildrenAdded();
        fiy_115.onChildrenAdded();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setAlign(frs_0.b);
        fin_26.setHorizontal(false);
        fso10.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        String string8 = "text4";
        fuk_0 fuk_08 = new fuk_0();
        fuk_08.onCheckOut();
        fuk_08.setElementMap(fyy_03);
        if (fyy_03 != null && string8 != null) {
            fyy_03.a(string8, fuk_08);
        }
        fuk_08.setMaxWidth(400);
        fuk_08.setMinWidth(400);
        fuk_08.setStyle("background");
        fso10.addBasicElement(fuk_08);
        fuk_08.onAttributesInitialized();
        fiy_1 fiy_116 = fiy_1.checkOut();
        fiy_116.setElementMap(fyy_03);
        fiy_116.setAttribute("text");
        fiy_116.setField("leftPage/text1");
        fiy_116.setName("backgroundDisplay");
        fuk_08.addBasicElement(fiy_116);
        fiy_116.onAttributesInitialized();
        fiy_116.onChildrenAdded();
        fuk_0 fuk_09 = fuk_08;
        fqh_0 fqh_05 = (fqh_0)((fvE)fuk_09).getAppearance();
        fqh_05.setElementMap(fyy_03);
        fuk_08.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqg_0 fqg_05 = fqg_0.checkOut();
        fqg_05.setElementMap(fyy_03);
        fqg_05.setColor(new fyr_0("backgroundBookColor"));
        fqh_05.addBasicElement(fqg_05);
        fqg_05.onAttributesInitialized();
        fqg_05.onChildrenAdded();
        fqh_05.onChildrenAdded();
        fuk_08.onChildrenAdded();
        this.a(fso10);
        fso10.onChildrenAdded();
        fso4.onChildrenAdded();
        this.b(fso3);
        fso3.onChildrenAdded();
        this.c(fso2);
        this.d(fso2);
        this.e(fso2);
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setPrefSize(new fjf_2(200, 200));
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        String string = "text5";
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fuk_02);
        }
        fuk_02.setMaxWidth(200);
        fuk_02.setMinWidth(200);
        fuk_02.setStyle("background");
        fso4.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.b);
        fuk_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("leftPage/text2");
        fiy_12.setName("backgroundDisplay");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_02);
        fqg_02.setColor(new fyr_0("backgroundBookColor"));
        fqh_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso4.onChildrenAdded();
        String string2 = "image3";
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fsk_02);
        }
        fsk_02.setExpandable(false);
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_02);
        fip_23.setAlign(frs_0.b);
        fsk_02.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("visible");
        fiy_13.setField("leftPage/imageUrl");
        fiy_13.setName("backgroundDisplay");
        fsk_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_13.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("texture");
        fiy_14.setField("leftPage/imageUrl");
        fiy_14.setName("backgroundDisplay");
        fqv2.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        String string = "margin2";
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fqm_02);
        }
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("rightPage");
        fiy_12.setName("backgroundDisplay");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso5.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("visible");
        fiy_13.setField("rightPage/templateLayoutId");
        fiy_13.setName("backgroundDisplay");
        fso5.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        fiy_13.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fat_2 fat_22 = new fat_2();
        fat_22.onCheckOut();
        fat_22.setElementMap(fyy_02);
        fat_22.setValue("1");
        far_23.addBasicElement(fat_22);
        fat_22.onAttributesInitialized();
        fat_22.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso5.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        String string2 = "text6";
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fuk_02);
        }
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(400);
        fuk_02.setMinWidth(400);
        fuk_02.setStyle("background");
        fso5.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("text");
        fiy_14.setField("rightPage/text1");
        fiy_14.setName("backgroundDisplay");
        fuk_02.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_02);
        fqg_02.setColor(new fyr_0("backgroundBookColor"));
        fqh_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso5.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso3.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso6.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("visible");
        fiy_15.setField("rightPage/templateLayoutId");
        fiy_15.setName("backgroundDisplay");
        fso6.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_02);
        fiy_15.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fat_2 fat_23 = new fat_2();
        fat_23.onCheckOut();
        fat_23.setElementMap(fyy_02);
        fat_23.setValue("2");
        far_24.addBasicElement(fat_23);
        fat_23.onAttributesInitialized();
        fat_23.onChildrenAdded();
        far_24.onChildrenAdded();
        fiy_15.onChildrenAdded();
        String string3 = "image4";
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        if (fyy_02 != null && string3 != null) {
            fyy_02.a(string3, fsk_02);
        }
        fso6.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_02);
        fiy_16.setAttribute("visible");
        fiy_16.setField("rightPage/imageUrl");
        fiy_16.setName("backgroundDisplay");
        fsk_02.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_02);
        fiy_16.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_02);
        far_25.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_25.onChildrenAdded();
        fiy_16.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_02);
        fiy_17.setAttribute("texture");
        fiy_17.setField("rightPage/imageUrl");
        fiy_17.setName("backgroundDisplay");
        fqv2.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso6.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso3.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(100.0f, 100.0f));
        fso7.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_02);
        fiy_18.setAttribute("visible");
        fiy_18.setField("rightPage/templateLayoutId");
        fiy_18.setName("backgroundDisplay");
        fso7.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        far_2 far_26 = new far_2();
        far_26.onCheckOut();
        far_26.setElementMap(fyy_02);
        fiy_18.addBasicElement(far_26);
        far_26.onAttributesInitialized();
        fat_2 fat_24 = new fat_2();
        fat_24.onCheckOut();
        fat_24.setElementMap(fyy_02);
        fat_24.setValue("3");
        far_26.addBasicElement(fat_24);
        fat_24.onAttributesInitialized();
        fat_24.onChildrenAdded();
        far_26.onChildrenAdded();
        fiy_18.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.b);
        fin_23.setHorizontal(false);
        fso7.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso8.setExpandable(false);
        fso7.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.d);
        fso8.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        String string4 = "image5";
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        if (fyy_02 != null && string4 != null) {
            fyy_02.a(string4, fsk_03);
        }
        fso8.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_02);
        fiy_19.setAttribute("visible");
        fiy_19.setField("rightPage/imageUrl");
        fiy_19.setName("backgroundDisplay");
        fsk_03.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        far_2 far_27 = new far_2();
        far_27.onCheckOut();
        far_27.setElementMap(fyy_02);
        fiy_19.addBasicElement(far_27);
        far_27.onAttributesInitialized();
        fab_2 fab_24 = new fab_2();
        fab_24.onCheckOut();
        fab_24.setElementMap(fyy_02);
        far_27.addBasicElement(fab_24);
        fab_24.onAttributesInitialized();
        fab_24.onChildrenAdded();
        far_27.onChildrenAdded();
        fiy_19.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fsk_03.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_02);
        fiy_110.setAttribute("texture");
        fiy_110.setField("rightPage/imageUrl");
        fiy_110.setName("backgroundDisplay");
        fqv3.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        fiy_110.onChildrenAdded();
        fqv3.onChildrenAdded();
        fsk_03.onChildrenAdded();
        String string5 = "text7";
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_02);
        if (fyy_02 != null && string5 != null) {
            fyy_02.a(string5, fuk_04);
        }
        fuk_04.setMaxWidth(200);
        fuk_04.setMinWidth(200);
        fuk_04.setStyle("background");
        fso8.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.b);
        fuk_04.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fiy_1 fiy_111 = fiy_1.checkOut();
        fiy_111.setElementMap(fyy_02);
        fiy_111.setAttribute("text");
        fiy_111.setField("rightPage/text1");
        fiy_111.setName("backgroundDisplay");
        fuk_04.addBasicElement(fiy_111);
        fiy_111.onAttributesInitialized();
        fiy_111.onChildrenAdded();
        fuk_0 fuk_05 = fuk_04;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_05).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fuk_04.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqg_0 fqg_03 = fqg_0.checkOut();
        fqg_03.setElementMap(fyy_02);
        fqg_03.setColor(new fyr_0("backgroundBookColor"));
        fqh_03.addBasicElement(fqg_03);
        fqg_03.onAttributesInitialized();
        fqg_03.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fso8.onChildrenAdded();
        String string6 = "text8";
        fuk_0 fuk_06 = new fuk_0();
        fuk_06.onCheckOut();
        fuk_06.setElementMap(fyy_02);
        if (fyy_02 != null && string6 != null) {
            fyy_02.a(string6, fuk_06);
        }
        fuk_06.setExpandable(false);
        fuk_06.setMaxWidth(400);
        fuk_06.setMinWidth(400);
        fuk_06.setStyle("background");
        fso7.addBasicElement(fuk_06);
        fuk_06.onAttributesInitialized();
        fiy_1 fiy_112 = fiy_1.checkOut();
        fiy_112.setElementMap(fyy_02);
        fiy_112.setAttribute("text");
        fiy_112.setField("rightPage/text2");
        fiy_112.setName("backgroundDisplay");
        fuk_06.addBasicElement(fiy_112);
        fiy_112.onAttributesInitialized();
        fiy_112.onChildrenAdded();
        fuk_0 fuk_07 = fuk_06;
        fqh_0 fqh_04 = (fqh_0)((fvE)fuk_07).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fuk_06.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqg_0 fqg_04 = fqg_0.checkOut();
        fqg_04.setElementMap(fyy_02);
        fqg_04.setColor(new fyr_0("backgroundBookColor"));
        fqh_04.addBasicElement(fqg_04);
        fqg_04.onAttributesInitialized();
        fqg_04.onChildrenAdded();
        fqh_04.onChildrenAdded();
        fuk_06.onChildrenAdded();
        fso7.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_02);
        fso3.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setAlign(frk_0.i);
        fid_15.setSize(new fjf_2(100.0f, 100.0f));
        fso9.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fiy_1 fiy_113 = fiy_1.checkOut();
        fiy_113.setElementMap(fyy_02);
        fiy_113.setAttribute("visible");
        fiy_113.setField("rightPage/templateLayoutId");
        fiy_113.setName("backgroundDisplay");
        fso9.addBasicElement(fiy_113);
        fiy_113.onAttributesInitialized();
        far_2 far_28 = new far_2();
        far_28.onCheckOut();
        far_28.setElementMap(fyy_02);
        fiy_113.addBasicElement(far_28);
        far_28.onAttributesInitialized();
        fat_2 fat_25 = new fat_2();
        fat_25.onCheckOut();
        fat_25.setElementMap(fyy_02);
        fat_25.setValue("4");
        far_28.addBasicElement(fat_25);
        fat_25.onAttributesInitialized();
        fat_25.onChildrenAdded();
        far_28.onChildrenAdded();
        fiy_113.onChildrenAdded();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setAlign(frs_0.b);
        fin_25.setHorizontal(false);
        fso9.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        String string7 = "text9";
        fuk_0 fuk_08 = new fuk_0();
        fuk_08.onCheckOut();
        fuk_08.setElementMap(fyy_02);
        if (fyy_02 != null && string7 != null) {
            fyy_02.a(string7, fuk_08);
        }
        fuk_08.setExpandable(false);
        fuk_08.setMaxWidth(400);
        fuk_08.setMinWidth(1);
        fuk_08.setStyle("background");
        fso9.addBasicElement(fuk_08);
        fuk_08.onAttributesInitialized();
        fiy_1 fiy_114 = fiy_1.checkOut();
        fiy_114.setElementMap(fyy_02);
        fiy_114.setAttribute("text");
        fiy_114.setField("rightPage/text1");
        fiy_114.setName("backgroundDisplay");
        fuk_08.addBasicElement(fiy_114);
        fiy_114.onAttributesInitialized();
        fiy_114.onChildrenAdded();
        fuk_0 fuk_09 = fuk_08;
        fqh_0 fqh_05 = (fqh_0)((fvE)fuk_09).getAppearance();
        fqh_05.setElementMap(fyy_02);
        fuk_08.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqg_0 fqg_05 = fqg_0.checkOut();
        fqg_05.setElementMap(fyy_02);
        fqg_05.setColor(new fyr_0("backgroundBookColor"));
        fqh_05.addBasicElement(fqg_05);
        fqg_05.onAttributesInitialized();
        fqg_05.onChildrenAdded();
        fqh_05.onChildrenAdded();
        fuk_08.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_02);
        fso10.setExpandable(false);
        fso9.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setAlign(frs_0.d);
        fso10.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_02);
        fso11.setPrefSize(new fjf_2(200, 200));
        fso10.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        String string8 = "text10";
        fuk_0 fuk_010 = new fuk_0();
        fuk_010.onCheckOut();
        fuk_010.setElementMap(fyy_02);
        if (fyy_02 != null && string8 != null) {
            fyy_02.a(string8, fuk_010);
        }
        fuk_010.setMaxWidth(200);
        fuk_010.setMinWidth(200);
        fuk_010.setStyle("background");
        fso11.addBasicElement(fuk_010);
        fuk_010.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_02);
        fip_23.setAlign(frs_0.b);
        fuk_010.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fiy_1 fiy_115 = fiy_1.checkOut();
        fiy_115.setElementMap(fyy_02);
        fiy_115.setAttribute("text");
        fiy_115.setField("rightPage/text2");
        fiy_115.setName("backgroundDisplay");
        fuk_010.addBasicElement(fiy_115);
        fiy_115.onAttributesInitialized();
        fiy_115.onChildrenAdded();
        fuk_0 fuk_011 = fuk_010;
        fqh_0 fqh_06 = (fqh_0)((fvE)fuk_011).getAppearance();
        fqh_06.setElementMap(fyy_02);
        fuk_010.addBasicElement(fqh_06);
        fqh_06.onAttributesInitialized();
        fqg_0 fqg_06 = fqg_0.checkOut();
        fqg_06.setElementMap(fyy_02);
        fqg_06.setColor(new fyr_0("backgroundBookColor"));
        fqh_06.addBasicElement(fqg_06);
        fqg_06.onAttributesInitialized();
        fqg_06.onChildrenAdded();
        fqh_06.onChildrenAdded();
        fuk_010.onChildrenAdded();
        fso11.onChildrenAdded();
        String string9 = "image6";
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        if (fyy_02 != null && string9 != null) {
            fyy_02.a(string9, fsk_04);
        }
        fso10.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fiy_1 fiy_116 = fiy_1.checkOut();
        fiy_116.setElementMap(fyy_02);
        fiy_116.setAttribute("visible");
        fiy_116.setField("rightPage/imageUrl");
        fiy_116.setName("backgroundDisplay");
        fsk_04.addBasicElement(fiy_116);
        fiy_116.onAttributesInitialized();
        this.a(fiy_116);
        fiy_116.onChildrenAdded();
        this.a(fsk_04);
        fsk_04.onChildrenAdded();
        fso10.onChildrenAdded();
        fso9.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo a(fiy_1 fiy_12) {
        fyy_0 fyy_02 = this.a.peek();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        return far_22;
    }

    public fyo a(fsk_0 fsk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("texture");
        fiy_12.setField("rightPage/imageUrl");
        fiy_12.setName("backgroundDisplay");
        fqv2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        String string = "previousButton";
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fru_02);
        }
        fru_02.setClickSoundId(600150);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.background:setPreviousPage");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(previousPagePopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setStyle("whiteLeftArrow");
        fso2.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.h);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_02);
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 10, 0, 0));
        fqd_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqd_02.onChildrenAdded();
        String string2 = "previousPagePopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fil_12);
        }
        fil_12.setAlign(frs_0.a);
        fil_12.setHotSpotPosition(frs_0.g);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setPrefSize(new fjf_2(10, 0));
        fso3.setStyle("popup");
        fil_12.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.e);
        fso3.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        String string3 = "%previous%";
        string3 = string3.replace("%previous%", fpm_0.b().c("previous"));
        fsM2.c(string3);
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso3.onChildrenAdded();
        fil_12.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("hasPages");
        fiy_12.setName("backgroundDisplay");
        fru_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("enabled");
        fiy_13.setField("previousExisting");
        fiy_13.setName("backgroundDisplay");
        fru_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        String string = "nextButton";
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fru_02);
        }
        fru_02.setClickSoundId(600151);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.background:setNextPage");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(nextPagePopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setStyle("whiteRightArrow");
        fso2.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.j);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_02);
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 0, 0, 10));
        fqd_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqd_02.onChildrenAdded();
        String string2 = "nextPagePopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fil_12);
        }
        fil_12.setAlign(frs_0.a);
        fil_12.setHotSpotPosition(frs_0.g);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setPrefSize(new fjf_2(10, 0));
        fso3.setStyle("popup");
        fil_12.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.e);
        fso3.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        String string3 = "%dialog.next%";
        string3 = string3.replace("%dialog.next%", fpm_0.b().c("dialog.next"));
        fsM2.c(string3);
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso3.onChildrenAdded();
        fil_12.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("hasPages");
        fiy_12.setName("backgroundDisplay");
        fru_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("enabled");
        fiy_13.setField("nextExisting");
        fiy_13.setName("backgroundDisplay");
        fru_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo e(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        String string = "closeButton";
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fru_02);
        }
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("unloadDialog");
        fru_02.setOnClick(fdt_12);
        fru_02.setStyle("backgroundDisplayClose");
        fso2.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("yOffset");
        fiy_12.setField("backgroundImage");
        fiy_12.setName("backgroundDisplay");
        fid_12.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        far_22.setElseValue("-45");
        far_22.setValue("0");
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("xOffset");
        fiy_13.setField("backgroundImage");
        fiy_13.setName("backgroundDisplay");
        fid_12.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        far_23.setElseValue("-5");
        far_23.setValue("0");
        fiy_13.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_02);
        far_23.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fid_12.onChildrenAdded();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_02);
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(10, 0, 0, 20));
        fqd_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqd_02.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }
}

