/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cLI
 */
public class cli_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fso2.setVisible(false);
        fso2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("visible");
        fiy_12.setName("isInGame");
        fso2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fan_2 fan_22 = new fan_2();
        fan_22.onCheckOut();
        fan_22.setElementMap(fyy_03);
        far_22.addBasicElement(fan_22);
        fan_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_03);
        fan_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        fai_1 fai_13 = new fai_1();
        fai_13.onCheckOut();
        fai_13.setElementMap(fyy_03);
        fan_22.addBasicElement(fai_13);
        fai_13.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("comparedValue");
        fiy_13.setName("isInBattleground");
        fai_13.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fai_13.onChildrenAdded();
        fan_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setAlign(frk_0.a);
        fid_12.setSize(new fjf_2(-2, -2));
        fid_12.setXOffset(-30);
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 0, 0, 2));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fso2.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_03);
        fso4.setExpandable(false);
        fso4.setPrefSize(new fjf_2(300, 168));
        fso2.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso4.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso4.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setAlign(frk_0.c);
        fid_13.setXOffset(-118);
        fid_13.setYOffset(-58);
        fso5.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso5.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fup_0 fup_02 = new fup_0();
        fup_02.onCheckOut();
        fup_02.setElementMap(fyy_03);
        fdi_2 fdi_22 = new fdi_2();
        fdi_22.a("wakfu:toggleBattlegroundBarDetail");
        fup_02.setOnSelectionChange(fdi_22);
        fup_02.setStyle("CharacteristicsDisplay");
        fso5.addBasicElement(fup_02);
        fup_02.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setSize(new fjf_2(100.0f, 100.0f));
        fup_02.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("selected");
        fiy_14.setName("battlegroundBarDetail");
        fup_02.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fup_02.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("DownSortArrow");
        fso5.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("visible");
        fiy_15.setName("battlegroundBarDetail");
        fsk_02.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.o);
        fid_15.setSize(new fjf_2(-2, -2));
        fid_15.setYOffset(7);
        fsk_02.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_03);
        fsk_03.setNonBlocking(true);
        fsk_03.setStyle("UpSortArrow");
        fso5.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_03);
        fid_16.setAlign(frk_0.o);
        fid_16.setSize(new fjf_2(-2, -2));
        fid_16.setYOffset(7);
        fsk_03.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("visible");
        fiy_16.setName("battlegroundBarDetail");
        fsk_03.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        fiy_16.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_03);
        far_23.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_16.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fso5.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_03);
        fso6.setExpandable(false);
        fso6.setNonBlocking(false);
        fso6.setPrefSize(new fjf_2(0, 0));
        fso6.setStyle("dungeonWindowDecoration");
        fso4.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_03);
        fid_17.setAlign(frk_0.a);
        fid_17.setXOffset(74);
        fid_17.setYOffset(-60);
        fso6.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_03);
        fiy_17.setAttribute("visible");
        fiy_17.setName("battlegroundBarDetail");
        fso6.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        String string = "battlegroundBarDetailTextId";
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fuk_02);
        }
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(200);
        fuk_02.setMinWidth(1);
        fuk_02.setMultiline(true);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("bold");
        fso6.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_03);
        fiy_18.setAttribute("text");
        fiy_18.setName("battlegroundBarDetailText");
        fuk_02.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        fiy_18.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(10, 10, 10, 10));
        fqh_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(5, 10, 15, 10));
        fqh_02.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso6.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso7.setNonBlocking(false);
        fso7.setPrefSize(new fjf_2(300, 58));
        fso7.setStyle("dungeonWindowDecoration");
        fso4.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fid_1 fid_18 = new fid_1();
        fid_18.onCheckOut();
        fid_18.setElementMap(fyy_03);
        fid_18.setAlign(frk_0.a);
        fso7.addBasicElement(fid_18);
        fid_18.onAttributesInitialized();
        fid_18.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.a);
        fso7.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso8 = fso7;
        fqj fqj3 = ((fvE)fso8).getAppearance();
        fqj3.setElementMap(fyy_03);
        fso7.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(0, 32, 12, 6));
        fqj3.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj3.onChildrenAdded();
        String string2 = "battlegroundType";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fij_12);
        }
        fso7.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_03);
        fiy_19.setAttribute("value");
        fiy_19.setField("battlegroundType");
        fiy_19.setName("battlegroundView");
        fij_12.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        fiy_19.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_03);
        fso9.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu:displayBattlegroundExplanation(battlegroundType)");
        fso9.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(bgTypeDetail)");
        fso9.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fso9.setOnPopupHide(fdf_22);
        fso9.setPrefSize(new fjf_2(46, 0));
        fso7.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fso9.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_03);
        fsk_04.setDisplaySize(new fjf_2(42, 42));
        fso9.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fid_1 fid_19 = new fid_1();
        fid_19.onCheckOut();
        fid_19.setElementMap(fyy_03);
        fid_19.setAlign(frk_0.i);
        fid_19.setSize(new fjf_2(100.0f, 100.0f));
        fsk_04.addBasicElement(fid_19);
        fid_19.onAttributesInitialized();
        fid_19.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fsk_04.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_03);
        fiy_110.setAttribute("texture");
        fiy_110.setField("battlegroundType/iconUrl");
        fiy_110.setName("battlegroundView");
        fqv2.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        fiy_110.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fsk_0 fsk_05 = new fsk_0();
        fsk_05.onCheckOut();
        fsk_05.setElementMap(fyy_03);
        fsk_05.setDisplaySize(new fjf_2(46, 46));
        fsk_05.setStyle("spellFrame");
        fso9.addBasicElement(fsk_05);
        fsk_05.onAttributesInitialized();
        fid_1 fid_110 = new fid_1();
        fid_110.onCheckOut();
        fid_110.setElementMap(fyy_03);
        fid_110.setAlign(frk_0.i);
        fid_110.setSize(new fjf_2(100.0f, 100.0f));
        fsk_05.addBasicElement(fid_110);
        fid_110.onAttributesInitialized();
        fid_110.onChildrenAdded();
        fsk_05.onChildrenAdded();
        String string3 = "bgTypeDetail";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fil_12);
        }
        fil_12.setAlign(frs_0.g);
        fil_12.setHotSpotPosition(frs_0.a);
        fso9.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        fso10.setPrefSize(new fjf_2(10, 0));
        fso10.setStyle("popup");
        fil_12.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setHorizontal(false);
        fso10.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_03);
        fuk_04.setExpandable(false);
        fuk_04.setMaxWidth(330);
        fuk_04.setMinWidth(330);
        fuk_04.setMultiline(true);
        fuk_04.setNonBlocking(true);
        fuk_04.setStyle("whiteTitle");
        fso10.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fiy_1 fiy_111 = fiy_1.checkOut();
        fiy_111.setElementMap(fyy_03);
        fiy_111.setAttribute("text");
        fiy_111.setField("battlegroundType/name");
        fiy_111.setName("battlegroundView");
        fuk_04.addBasicElement(fiy_111);
        fiy_111.onAttributesInitialized();
        fiy_111.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_03);
        fur_02.setPrefSize(new fjf_2(0, 4));
        fso10.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fuk_0 fuk_05 = new fuk_0();
        fuk_05.onCheckOut();
        fuk_05.setElementMap(fyy_03);
        fuk_05.setExpandable(false);
        fuk_05.setMaxWidth(330);
        fuk_05.setMinWidth(330);
        fuk_05.setMultiline(true);
        fuk_05.setNonBlocking(true);
        fuk_05.setStyle("white");
        fso10.addBasicElement(fuk_05);
        fuk_05.onAttributesInitialized();
        fiy_1 fiy_112 = fiy_1.checkOut();
        fiy_112.setElementMap(fyy_03);
        fiy_112.setAttribute("text");
        fiy_112.setField("battlegroundType/desc");
        fiy_112.setName("battlegroundView");
        fuk_05.addBasicElement(fiy_112);
        fiy_112.onAttributesInitialized();
        fiy_112.onChildrenAdded();
        fuk_05.onChildrenAdded();
        fso10.onChildrenAdded();
        fil_12.onChildrenAdded();
        fso9.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso11.setExpandable(false);
        fso11.setPrefSize(new fjf_2(167, 0));
        fso11.setStyle("popup");
        fso7.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fso fso12 = fso11;
        fqj fqj4 = ((fvE)fso12).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso11.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(4, 0, 12, 0));
        fqj4.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqj4.onChildrenAdded();
        fic_1 fic_15 = new fic_1();
        fic_15.onCheckOut();
        fso11.addBasicElement(fic_15);
        fic_15.onAttributesInitialized();
        fic_15.onChildrenAdded();
        fsk_0 fsk_06 = new fsk_0();
        fsk_06.onCheckOut();
        fsk_06.setElementMap(fyy_03);
        fsk_06.setDisplaySize(new fjf_2(48, 48));
        fsk_06.setNonBlocking(true);
        fsk_06.setStyle("pvpDecorator");
        fso11.addBasicElement(fsk_06);
        fsk_06.onAttributesInitialized();
        fid_1 fid_111 = new fid_1();
        fid_111.onCheckOut();
        fid_111.setElementMap(fyy_03);
        fid_111.setAlign(frk_0.i);
        fsk_06.addBasicElement(fid_111);
        fid_111.onAttributesInitialized();
        fid_111.onChildrenAdded();
        fsk_06.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_03);
        fso11.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fid_1 fid_112 = new fid_1();
        fid_112.onCheckOut();
        fid_112.setElementMap(fyy_03);
        fid_112.setAlign(frk_0.i);
        fid_112.setSize(new fjf_2(100.0f, 100.0f));
        fso13.addBasicElement(fid_112);
        fid_112.onAttributesInitialized();
        fid_112.onChildrenAdded();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setHorizontal(false);
        fso13.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_03);
        fso13.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        fuk_0 fuk_06 = new fuk_0();
        fuk_06.onCheckOut();
        fuk_06.setElementMap(fyy_03);
        fuk_06.setExpandable(false);
        fuk_06.setMaxWidth(60);
        fuk_06.setMinWidth(50);
        fuk_06.setNonBlocking(true);
        fuk_06.setStyle("whiteTitle");
        fso14.addBasicElement(fuk_06);
        fuk_06.onAttributesInitialized();
        this.a(fuk_06);
        this.b(fuk_06);
        fuk_06.onChildrenAdded();
        this.a(fso14);
        this.b(fso14);
        fso14.onChildrenAdded();
        fso13.onChildrenAdded();
        fso11.onChildrenAdded();
        fso7.onChildrenAdded();
        this.c(fso4);
        this.d(fso4);
        fso4.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo a(fuk_0 fuk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("defenseTeam/score");
        fiy_12.setName("battlegroundView");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        return fiy_12;
    }

    public fyo b(fuk_0 fuk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.e);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_02);
        fqg_02.setColor(new fyr_0("battlegroundDefenseTeamScoreColor"));
        fqh_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        return fqh_02;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_02);
        fso2.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        return fur_02;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(60);
        fuk_02.setMinWidth(50);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("whiteTitle");
        fso2.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("attackTeam/score");
        fiy_12.setName("battlegroundView");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.e);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_02);
        fqg_02.setColor(new fyr_0("battlegroundAttackTeamScoreColor"));
        fqh_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        return fuk_02;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.c);
        fid_12.setSize(new fjf_2(180, 16));
        fid_12.setXOffset(5);
        fid_12.setYOffset(-41);
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setExpandable(false);
        fso4.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso5.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(16, 16));
        fsQ2.setExpandable(false);
        fsQ2.setIdealSizeMaxRows(1);
        fsQ2.setIdealSizeMinRows(1);
        fsQ2.setNonBlocking(false);
        fso5.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("defenseTeam/nationsList");
        fiy_12.setName("battlegroundView");
        fsQ2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso6.setExpandable(false);
        fso6.setPrefSize(new fjf_2(16, 16));
        faf_22.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(14, 14));
        fsk_02.setExpandable(false);
        fsk_02.setNonBlocking(false);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(nationPopup)");
        fsk_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fsk_02.setOnPopupHide(fdf_22);
        fso6.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("texture");
        fir_12.setField("flagIconUrl");
        fqv2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fqv2.onChildrenAdded();
        String string = "nationPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fil_12);
        }
        fil_12.setAlign(frs_0.d);
        fil_12.setHotSpotPosition(frs_0.f);
        fsk_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso7.setStyle("popup");
        fil_12.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso7.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setMaxWidth(200);
        fsM2.setMinWidth(100);
        fsM2.setMultiline(true);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("whiteBold");
        fso7.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM fsM4 = fsM2;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM4).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fsM2.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(2, 0, 6, 0));
        fqh_03.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("text");
        fir_13.setField("name");
        fsM2.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso7.onChildrenAdded();
        fil_12.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso6.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso5.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_02);
        fso4.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso8.setExpandable(false);
        fso4.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.f);
        fso8.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fsQ fsQ3 = new fsQ();
        fsQ3.onCheckOut();
        fsQ3.setElementMap(fyy_02);
        fsQ3.setAutoIdealSize(true);
        fsQ3.setCellSize(new fjf_2(16, 16));
        fsQ3.setExpandable(false);
        fsQ3.setIdealSizeMaxRows(1);
        fsQ3.setIdealSizeMinRows(1);
        fsQ3.setNonBlocking(false);
        fso8.addBasicElement(fsQ3);
        fsQ3.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("content");
        fiy_13.setField("attackTeam/nationsList");
        fiy_13.setName("battlegroundView");
        fsQ3.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        faf_2 faf_23 = new faf_2();
        faf_23.onCheckOut();
        faf_23.setElementMap(fyy_02);
        fsQ3.addBasicElement(faf_23);
        faf_23.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        faf_23.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fav_1 fav_13 = new fav_1();
        fav_13.onCheckOut();
        fav_13.setElementMap(fyy_02);
        far_23.addBasicElement(fav_13);
        fav_13.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_02);
        fav_13.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        fav_13.onChildrenAdded();
        far_23.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_02);
        fso9.setExpandable(false);
        fso9.setPrefSize(new fjf_2(16, 16));
        faf_23.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        fsk_03.setDisplaySize(new fjf_2(14, 14));
        fsk_03.setExpandable(false);
        fsk_03.setNonBlocking(false);
        fde_2 fde_23 = new fde_2();
        fde_23.a("popup(nationPopup)");
        fsk_03.setOnPopupDisplay(fde_23);
        fdf_2 fdf_23 = new fdf_2();
        fdf_23.a("closePopup");
        fsk_03.setOnPopupHide(fdf_23);
        fso9.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fsk_03.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("texture");
        fir_14.setField("flagIconUrl");
        fqv3.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fqv3.onChildrenAdded();
        String string2 = "nationPopup";
        fil_1 fil_13 = new fil_1();
        fil_13.onCheckOut();
        fil_13.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fil_13);
        }
        fil_13.setAlign(frs_0.d);
        fil_13.setHotSpotPosition(frs_0.f);
        fsk_03.addBasicElement(fil_13);
        fil_13.onAttributesInitialized();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_02);
        fso10.setStyle("popup");
        fil_13.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setHorizontal(false);
        fso10.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fsM fsM5 = new fsM();
        fsM5.onCheckOut();
        fsM5.setElementMap(fyy_02);
        fsM5.setMaxWidth(200);
        fsM5.setMinWidth(100);
        fsM5.setMultiline(true);
        fsM5.setNonBlocking(true);
        fsM5.setStyle("whiteBold");
        fso10.addBasicElement(fsM5);
        fsM5.onAttributesInitialized();
        fsM fsM6 = fsM5;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM6).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fqh_04.setAlignment(frs_0.e);
        fsM5.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fsM fsM7 = fsM5;
        fqh_0 fqh_05 = (fqh_0)((fvE)fsM7).getAppearance();
        fqh_05.setElementMap(fyy_02);
        fsM5.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(2, 0, 6, 0));
        fqh_05.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_05.onChildrenAdded();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("text");
        fir_15.setField("name");
        fsM5.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fsM5.onChildrenAdded();
        fso10.onChildrenAdded();
        fil_13.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fso9.onChildrenAdded();
        faf_23.onChildrenAdded();
        fsQ3.onChildrenAdded();
        fso8.onChildrenAdded();
        fso4.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(80);
        fuk_02.setMinWidth(80);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("StyledDark12");
        fso2.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.c);
        fid_12.setSize(new fjf_2(-2, -2));
        fid_12.setXOffset(128);
        fid_12.setYOffset(-18);
        fuk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("battlegroundRemainingTime");
        fiy_12.setName("battlegroundView");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.e);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        return fuk_02;
    }
}

