/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cLu
 */
public class clu_1
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        fvk_02.setPack(true);
        fvk_02.setPrefSize(new fjf_2(500, 300));
        fvk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setAlign(frk_0.i);
        fid_12.setInitValue(true);
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fso2.setExpandable(false);
        fso2.setNonBlocking(false);
        fso2.setPrefSize(new fjf_2(18, 100));
        fso2.setStyle("itemInventoryBarBackground");
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fih_2 fih_22 = new fih_2();
        fih_22.onCheckOut();
        fso2.addBasicElement(fih_22);
        fih_22.onAttributesInitialized();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fih_22.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_03);
        fii_22.setData(frg_0.a);
        fvM2.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fih_2 fih_23 = new fih_2();
        fih_23.onCheckOut();
        fvM2.addBasicElement(fih_23);
        fih_23.onAttributesInitialized();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setNonBlocking(true);
        fsM2.setOrientation(frh_0.a);
        fsM2.setStyle("bold");
        fsM2.c("Editeur de couleur de personnage");
        fih_23.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fii_2 fii_23 = fii_2.checkOut();
        fii_23.setElementMap(fyy_03);
        fii_23.setData(frg_0.a);
        fsM2.addBasicElement(fii_23);
        fii_23.onAttributesInitialized();
        fii_23.onChildrenAdded();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 0, 20, 0));
        fqh_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_03);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("unloadDialog");
        fru_02.setOnClick(fdt_12);
        fru_02.setStyle("closeWindow");
        fih_23.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fii_2 fii_24 = fii_2.checkOut();
        fii_24.setElementMap(fyy_03);
        fii_24.setData(frg_0.b);
        fru_02.addBasicElement(fii_24);
        fii_24.onAttributesInitialized();
        fii_24.onChildrenAdded();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_03);
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(10, 0, 0, 0));
        fqd_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqd_02.onChildrenAdded();
        fru_02.onChildrenAdded();
        fih_23.onChildrenAdded();
        fvM2.onChildrenAdded();
        fih_22.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setNonBlocking(false);
        fso3.setStyle("brownInventoryBackground");
        fvk_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(15, 5, 10, 7));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setExpandable(false);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_03);
        fsM4.setExpandable(false);
        fsM4.setStyle("whiteTitle");
        fsM4.c("\u00c9dition des couleurs");
        fso5.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM4.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_03);
        fso5.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fru_0 fru_04 = new fru_0();
        fru_04.onCheckOut();
        fru_04.setElementMap(fyy_03);
        fru_04.setExpandable(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.adminCharacterEditor:openCharacterColorEditor");
        fru_04.setOnClick(fdt_13);
        fru_04.setText("\u00c9diter les caracs");
        fso5.addBasicElement(fru_04);
        fru_04.onAttributesInitialized();
        fru_0 fru_05 = fru_04;
        fqd_0 fqd_03 = (fqd_0)((fvE)fru_05).getAppearance();
        fqd_03.setElementMap(fyy_03);
        fru_04.addBasicElement(fqd_03);
        fqd_03.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(2, 10, 2, 10));
        fqd_03.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(0, 0, 0, 10));
        fqd_03.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqd_03.onChildrenAdded();
        fru_04.onChildrenAdded();
        fso5.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_03);
        fso6.setExpandable(false);
        fso3.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.d);
        fso6.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.d);
        fso6.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fsM fsM5 = new fsM();
        fsM5.onCheckOut();
        fsM5.setElementMap(fyy_03);
        fsM5.setExpandable(false);
        fsM5.setStyle("whiteBold");
        fsM5.c("Ajouter une Part \u00e0 coloriser ");
        fso6.addBasicElement(fsM5);
        fsM5.onAttributesInitialized();
        fsM5.onChildrenAdded();
        String string = "comboColor";
        fsk fsk2 = new fsk();
        fsk2.onCheckOut();
        fsk2.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fsk2);
        }
        fsk2.setExpandable(false);
        fsk2.setPrefSize(new fjf_2(150, 15));
        fso6.addBasicElement(fsk2);
        fsk2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("content");
        fiy_12.setName("adminInactiveColors");
        fsk2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        ftj_0 ftj_02 = new ftj_0();
        ftj_02.onCheckOut();
        ftj_02.setElementMap(fyy_03);
        fsk2.addBasicElement(ftj_02);
        ftj_02.onAttributesInitialized();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_03);
        ftj_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        faf_22.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.d);
        fso7.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_03);
        fsM6.setExpandable(false);
        fsM6.setNonBlocking(true);
        fso7.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_03);
        fip_23.setAlign(frs_0.e);
        fsM6.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_03);
        fir_12.setAttribute("text");
        fir_12.setField("name");
        fsM6.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fsM6.onChildrenAdded();
        fso7.onChildrenAdded();
        faf_22.onChildrenAdded();
        ftj_02.onChildrenAdded();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_03);
        fsQ2.setCellSize(new fjf_2(100.0f, 16));
        fsQ2.setHorizontal(false);
        fsk2.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        faf_2 faf_23 = new faf_2();
        faf_23.onCheckOut();
        faf_23.setElementMap(fyy_03);
        fsQ2.addBasicElement(faf_23);
        faf_23.onAttributesInitialized();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        faf_23.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj3 = ((fvE)fso9).getAppearance();
        fqj3.setElementMap(fyy_03);
        fso8.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(0, 10, 0, 0));
        fqj3.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqj3.onChildrenAdded();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setAlign(frs_0.d);
        fso8.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fsM fsM7 = new fsM();
        fsM7.onCheckOut();
        fsM7.setElementMap(fyy_03);
        fsM7.setExpandable(false);
        fsM7.setNonBlocking(true);
        fso8.addBasicElement(fsM7);
        fsM7.onAttributesInitialized();
        fip_2 fip_24 = new fip_2();
        fip_24.onCheckOut();
        fip_24.setElementMap(fyy_03);
        fip_24.setAlign(frs_0.e);
        fsM7.addBasicElement(fip_24);
        fip_24.onAttributesInitialized();
        fip_24.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_03);
        fir_13.setAttribute("text");
        fir_13.setField("name");
        fsM7.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fsM7.onChildrenAdded();
        fso8.onChildrenAdded();
        faf_23.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fsk2.onChildrenAdded();
        fru_0 fru_06 = new fru_0();
        fru_06.onCheckOut();
        fru_06.setElementMap(fyy_03);
        fru_06.setExpandable(false);
        fdt_1 fdt_14 = new fdt_1();
        fdt_14.a("wakfu.adminCharacterEditor:activateColor");
        fru_06.setOnClick(fdt_14);
        fru_06.setStyle("smallValid");
        fso6.addBasicElement(fru_06);
        fru_06.onAttributesInitialized();
        fru_06.onChildrenAdded();
        fso6.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        fso10.setExpandable(false);
        fso10.setPrefSize(new fjf_2(0, 7));
        fso10.setStyle("lineSeparator");
        fso3.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fso fso11 = fso10;
        fqj fqj4 = ((fvE)fso11).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso10.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_03);
        fqm_06.setInsets(new Insets(5, 0, 2, 0));
        fqj4.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqj4.onChildrenAdded();
        fso10.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        fso12.setExpandable(false);
        fso3.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setAlign(frs_0.d);
        fso12.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        fue_0 fue_02 = new fue_0();
        fue_02.onCheckOut();
        fue_02.setElementMap(fyy_03);
        fue_02.setExpandable(false);
        fue_02.setPrefSize(new fjf_2(350, 600));
        fso12.addBasicElement(fue_02);
        fue_02.onAttributesInitialized();
        fus_0 fus_02 = new fus_0();
        fus_02.onCheckOut();
        fus_02.setElementMap(fyy_03);
        fus_02.setHorizontal(false);
        fue_02.addBasicElement(fus_02);
        fus_02.onAttributesInitialized();
        fip_2 fip_25 = new fip_2();
        fip_25.onCheckOut();
        fip_25.setElementMap(fyy_03);
        fip_25.setAlign(frs_0.d);
        fus_02.addBasicElement(fip_25);
        fip_25.onAttributesInitialized();
        fip_25.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("content");
        fiy_13.setName("adminColors");
        fus_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fin_2 fin_27 = fin_2.checkOut();
        fin_27.setAlign(frs_0.b);
        fin_27.setHorizontal(false);
        fus_02.addBasicElement(fin_27);
        fin_27.onAttributesInitialized();
        fin_27.onChildrenAdded();
        faf_2 faf_24 = new faf_2();
        faf_24.onCheckOut();
        faf_24.setElementMap(fyy_03);
        fus_02.addBasicElement(faf_24);
        faf_24.onAttributesInitialized();
        fip_2 fip_26 = new fip_2();
        fip_26.onCheckOut();
        fip_26.setElementMap(fyy_03);
        fip_26.setAlign(frs_0.d);
        faf_24.addBasicElement(fip_26);
        fip_26.onAttributesInitialized();
        fip_26.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_03);
        fso13.setExpandable(false);
        fso13.setPrefSize(new fjf_2(290, 0));
        faf_24.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fin_2 fin_28 = fin_2.checkOut();
        fin_28.setAlign(frs_0.b);
        fin_28.setHorizontal(false);
        fso13.addBasicElement(fin_28);
        fin_28.onAttributesInitialized();
        fin_28.onChildrenAdded();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_03);
        fso14.setExpandable(false);
        fso13.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        String string2 = "color";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fij_12);
        }
        fso14.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_03);
        fir_14.setAttribute("value");
        fij_12.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fij_12.onChildrenAdded();
        fin_2 fin_29 = fin_2.checkOut();
        fin_29.setAlign(frs_0.b);
        fin_29.setHorizontal(false);
        fso14.addBasicElement(fin_29);
        fin_29.onAttributesInitialized();
        fin_29.onChildrenAdded();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_03);
        fso15.setExpandable(false);
        fso14.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fin_2 fin_210 = fin_2.checkOut();
        fin_210.setAlign(frs_0.d);
        fso15.addBasicElement(fin_210);
        fin_210.onAttributesInitialized();
        fin_210.onChildrenAdded();
        fsM fsM8 = new fsM();
        fsM8.onCheckOut();
        fsM8.setElementMap(fyy_03);
        fsM8.setExpandable(false);
        fsM8.setStyle("whiteBold");
        fso15.addBasicElement(fsM8);
        fsM8.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_03);
        fir_15.setAttribute("text");
        fir_15.setField("name");
        fsM8.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fsM8.onChildrenAdded();
        fsM fsM9 = new fsM();
        fsM9.onCheckOut();
        fsM9.setElementMap(fyy_03);
        fsM9.setExpandable(false);
        fsM9.setStyle("whiteBold");
        String string3 = "%colon%";
        string3 = string3.replace("%colon%", fpm_0.b().c("colon"));
        fsM9.c(string3);
        fso15.addBasicElement(fsM9);
        fsM9.onAttributesInitialized();
        fsM9.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setExpandable(false);
        fuk_02.setPrefSize(new fjf_2(150, 0));
        fuk_02.setSelectable(true);
        fuk_02.setStyle("whiteBold");
        fso15.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_03);
        fir_16.setAttribute("text");
        fir_16.setField("floatString");
        fuk_02.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        fir_16.onChildrenAdded();
        fuk_02.onChildrenAdded();
        this.a(fso15);
        this.b(fso15);
        fso15.onChildrenAdded();
        this.c(fso14);
        this.d(fso14);
        this.e(fso14);
        fso14.onChildrenAdded();
        this.f(fso13);
        fso13.onChildrenAdded();
        faf_24.onChildrenAdded();
        fus_02.onChildrenAdded();
        fue_02.onChildrenAdded();
        this.g(fso12);
        fso12.onChildrenAdded();
        fso3.onChildrenAdded();
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_02);
        fso2.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        return fur_02;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.adminCharacterEditor:deleteActiveColor(color)");
        fru_02.setOnClick(fdt_12);
        fru_02.setStyle("closeWindow");
        fso2.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(5, 0, 0, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setPrefSize(new fjf_2(50, 0));
        fsM2.setStyle("whiteBold");
        String string = "%red%";
        string = string.replace("%red%", fpm_0.b().c("red"));
        fsM2.c(string);
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM2.onChildrenAdded();
        fsM fsM3 = new fsM();
        fsM3.onCheckOut();
        fsM3.setElementMap(fyy_02);
        fsM3.setExpandable(false);
        fsM3.setStyle("whiteBold");
        fsM3.c("0");
        fso3.addBasicElement(fsM3);
        fsM3.onAttributesInitialized();
        fsM3.onChildrenAdded();
        fum fum2 = new fum();
        fum2.onCheckOut();
        fum2.setElementMap(fyy_02);
        fum2.setExpandable(false);
        fum2.setHorizontal(true);
        fdj_2 fdj_22 = new fdj_2();
        fdj_22.a("wakfu.adminCharacterEditor:setFilterRed(color)");
        fum2.setOnSliderMove(fdj_22);
        fum2.setPrefSize(new fjf_2(100, 0));
        fum2.setStyle("volume");
        fso3.addBasicElement(fum2);
        fum2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("value");
        fir_12.setField("red");
        fum2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fum fum3 = fum2;
        fqj fqj3 = ((fvE)fum3).getAppearance();
        fqj3.setElementMap(fyy_02);
        fum2.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 5, 0, 5));
        fqj3.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj3.onChildrenAdded();
        fum2.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setExpandable(false);
        fsM4.setStyle("whiteBold");
        fsM4.c("100%");
        fso3.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM4.onChildrenAdded();
        String string2 = "redTextEditor";
        fug_0 fug_02 = new fug_0();
        fug_02.onCheckOut();
        fug_02.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fug_02);
        }
        fug_02.setExpandable(false);
        fug_02.a(3);
        fdo_1 fdo_12 = new fdo_1();
        fdo_12.a("wakfu.adminCharacterEditor:setFilterRed(redTextEditor,color)");
        fug_02.setOnKeyType(fdo_12);
        fug_02.setPrefSize(new fjf_2(25, 15));
        fug_02.setRestrict("[0-9]+");
        fso3.addBasicElement(fug_02);
        fug_02.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("text");
        fir_13.setField("red255");
        fug_02.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fug_0 fug_03 = fug_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fug_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.f);
        fug_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fug_0 fug_04 = fug_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fug_04).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fug_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 5, 0, 0));
        fqh_03.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fug_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setPrefSize(new fjf_2(50, 0));
        fsM2.setStyle("whiteBold");
        String string = "%green%";
        string = string.replace("%green%", fpm_0.b().c("green"));
        fsM2.c(string);
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM2.onChildrenAdded();
        fsM fsM3 = new fsM();
        fsM3.onCheckOut();
        fsM3.setElementMap(fyy_02);
        fsM3.setExpandable(false);
        fsM3.setStyle("whiteBold");
        fsM3.c("0");
        fso3.addBasicElement(fsM3);
        fsM3.onAttributesInitialized();
        fsM3.onChildrenAdded();
        fum fum2 = new fum();
        fum2.onCheckOut();
        fum2.setElementMap(fyy_02);
        fum2.setExpandable(false);
        fum2.setHorizontal(true);
        fdj_2 fdj_22 = new fdj_2();
        fdj_22.a("wakfu.adminCharacterEditor:setFilterGreen(color)");
        fum2.setOnSliderMove(fdj_22);
        fum2.setPrefSize(new fjf_2(100, 0));
        fum2.setStyle("volume");
        fso3.addBasicElement(fum2);
        fum2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("value");
        fir_12.setField("green");
        fum2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fum fum3 = fum2;
        fqj fqj2 = ((fvE)fum3).getAppearance();
        fqj2.setElementMap(fyy_02);
        fum2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 5, 0, 5));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fum2.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setExpandable(false);
        fsM4.setStyle("whiteBold");
        fsM4.c("100%");
        fso3.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM4.onChildrenAdded();
        String string2 = "greenTextEditor";
        fug_0 fug_02 = new fug_0();
        fug_02.onCheckOut();
        fug_02.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fug_02);
        }
        fug_02.setExpandable(false);
        fug_02.a(3);
        fdo_1 fdo_12 = new fdo_1();
        fdo_12.a("wakfu.adminCharacterEditor:setFilterGreen(greenTextEditor,color)");
        fug_02.setOnKeyType(fdo_12);
        fug_02.setPrefSize(new fjf_2(25, 15));
        fug_02.setRestrict("[0-9]+");
        fso3.addBasicElement(fug_02);
        fug_02.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("text");
        fir_13.setField("green255");
        fug_02.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fug_0 fug_03 = fug_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fug_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.f);
        fug_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fug_0 fug_04 = fug_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fug_04).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fug_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 5, 0, 0));
        fqh_03.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fug_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo e(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setPrefSize(new fjf_2(50, 0));
        fsM2.setStyle("whiteBold");
        String string = "%blue%";
        string = string.replace("%blue%", fpm_0.b().c("blue"));
        fsM2.c(string);
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM2.onChildrenAdded();
        fsM fsM3 = new fsM();
        fsM3.onCheckOut();
        fsM3.setElementMap(fyy_02);
        fsM3.setExpandable(false);
        fsM3.setStyle("whiteBold");
        fsM3.c("0");
        fso3.addBasicElement(fsM3);
        fsM3.onAttributesInitialized();
        fsM3.onChildrenAdded();
        fum fum2 = new fum();
        fum2.onCheckOut();
        fum2.setElementMap(fyy_02);
        fum2.setExpandable(false);
        fum2.setHorizontal(true);
        fdj_2 fdj_22 = new fdj_2();
        fdj_22.a("wakfu.adminCharacterEditor:setFilterBlue(color)");
        fum2.setOnSliderMove(fdj_22);
        fum2.setPrefSize(new fjf_2(100, 0));
        fum2.setStyle("volume");
        fso3.addBasicElement(fum2);
        fum2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("value");
        fir_12.setField("blue");
        fum2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fum fum3 = fum2;
        fqj fqj2 = ((fvE)fum3).getAppearance();
        fqj2.setElementMap(fyy_02);
        fum2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 5, 0, 5));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fum2.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setExpandable(false);
        fsM4.setStyle("whiteBold");
        fsM4.c("100%");
        fso3.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM4.onChildrenAdded();
        String string2 = "blueTextEditor";
        fug_0 fug_02 = new fug_0();
        fug_02.onCheckOut();
        fug_02.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fug_02);
        }
        fug_02.setExpandable(false);
        fug_02.a(3);
        fdo_1 fdo_12 = new fdo_1();
        fdo_12.a("wakfu.adminCharacterEditor:setFilterBlue(blueTextEditor,color)");
        fug_02.setOnKeyType(fdo_12);
        fug_02.setPrefSize(new fjf_2(25, 15));
        fug_02.setRestrict("[0-9]+");
        fso3.addBasicElement(fug_02);
        fug_02.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("text");
        fir_13.setField("blue255");
        fug_02.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fug_0 fug_03 = fug_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fug_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.f);
        fug_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fug_0 fug_04 = fug_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fug_04).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fug_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 5, 0, 0));
        fqh_03.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fug_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo f(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setPrefSize(new fjf_2(0, 7));
        fso3.setStyle("lineSeparator");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(5, 0, 2, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo g(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fbh_1 fbh_12 = new fbh_1();
        fbh_12.onCheckOut();
        fbh_12.setElementMap(fyy_02);
        fbh_12.setColor(new azf_2(0.0f, 0.0f, 0.0f, 1.0f));
        fbh_12.setInsets(new Insets(0, 1, 0, 0));
        fqj2.addBasicElement(fbh_12);
        fbh_12.onAttributesInitialized();
        fbh_12.onChildrenAdded();
        fqj2.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setExpandable(false);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.d);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.adminCharacterEditor:loadAnmDebugger");
        fru_02.setOnClick(fdt_12);
        fru_02.setText("Anm Debugger");
        fso5.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_02.onChildrenAdded();
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_02);
        fru_03.setExpandable(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.adminCharacterEditor:reloadAnmimation");
        fru_03.setOnClick(fdt_13);
        fru_03.setText("Reload Anm");
        fso5.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        fru_03.onChildrenAdded();
        fso5.onChildrenAdded();
        String string = "localPlayerDisplay";
        frO frO2 = new frO();
        frO2.onCheckOut();
        frO2.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, frO2);
        }
        frO2.setExpandable(false);
        frO2.setOffsetY(-200.0f);
        frO2.setPrefSize(new fjf_2(100, 0));
        frO2.setScale(2.0f);
        fso3.addBasicElement(frO2);
        frO2.onAttributesInitialized();
        frO frO3 = frO2;
        fqb fqb2 = (fqb)((fvE)frO3).getAppearance();
        fqb2.setElementMap(fyy_02);
        frO2.addBasicElement(fqb2);
        fqb2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 30, 0, 0));
        fqb2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqb2.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("animatedElement");
        fiy_12.setField("actorDescriptorLibrary");
        fiy_12.setName("localPlayer");
        frO2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("equipment");
        fiy_13.setField("actorEquipment");
        fiy_13.setName("localPlayer");
        frO2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("direction");
        fiy_14.setName("adminAnimDirection");
        frO2.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("animName");
        fiy_15.setName("adminAnimName");
        frO2.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        frO2.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }
}

