/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cME
 */
public class cme_1
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        fvk_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvk_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqj2.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_03);
        fso4.setNonBlocking(false);
        fso4.setStyle("windowBackgroundSmallRepeated");
        fvk_02.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso4.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso4.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setExpandable(false);
        fvM2.setEnabled(false);
        fso4.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setPrefSize(new fjf_2(100.0f, 48));
        fso5.setStyle("WindowHeaderSmall");
        fvM2.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.e);
        fso5.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_03);
        fso6.setExpandable(false);
        fso6.setPrefSize(new fjf_2(44, 32));
        fso5.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fso6.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setEnableAutoZoomShrink(true);
        fsM2.setMaxWidth(270);
        fsM2.setMinWidth(100);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("windowTitle");
        String string = "%death.header%";
        string = string.replace("%death.header%", fpm_0.b().c("death.header"));
        fsM2.c(string);
        fso5.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(0, 0, 2, 0));
        fqh_02.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso7.setPrefSize(new fjf_2(44, 32));
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        fvM2.onChildrenAdded();
        String string2 = "windowContentContainer";
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fso8);
        }
        fso8.setPrefSize(new fjf_2(360, 312));
        fso4.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso8.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_03);
        fso8.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setSize(new fjf_2(100.0f, 100.0f));
        fso9.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fso9.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setSize(new fjf_2(100.0f, 100.0f));
        fso10.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fso fso11 = fso10;
        fqj fqj3 = ((fvE)fso11).getAppearance();
        fqj3.setElementMap(fyy_03);
        fso10.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(16, 16, 16, 16));
        fqj3.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso12 = fso10;
        fqj fqj4 = ((fvE)fso12).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso10.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_03);
        fqo_04.setInsets(new Insets(16, 16, 16, 16));
        fqj4.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj4.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_03);
        fso10.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.b);
        fin_23.setHorizontal(false);
        fso13.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setMaxWidth(328);
        fuk_02.setMinWidth(1);
        fuk_02.setMultiline(true);
        fuk_02.setStyle("wipLight16");
        String string3 = "%death.options.message%";
        string3 = string3.replace("%death.options.message%", fpm_0.b().c("death.options.message"));
        fuk_02.c(string3);
        fso13.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_03);
        fip_23.setAlign(frs_0.b);
        fuk_02.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_03);
        fso14.setExpandable(false);
        fso14.setNeedsScissor(true);
        fso13.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        ful ful2 = new ful();
        ful2.onCheckOut();
        ful2.setElementMap(fyy_03);
        ful2.setStyle("defaultHorizontal");
        fso14.addBasicElement(ful2);
        ful2.onAttributesInitialized();
        ful2.onChildrenAdded();
        fso fso15 = fso14;
        fqj fqj5 = ((fvE)fso15).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso14.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(8, 0, 8, 0));
        fqj5.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj5.onChildrenAdded();
        fso14.onChildrenAdded();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_03);
        fso16.setExpandable(false);
        fso13.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setHorizontal(false);
        fin_24.setUseLegacyVGapBehaviour(false);
        fin_24.setVgap((short)10);
        fso16.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fip_2 fip_24 = new fip_2();
        fip_24.onCheckOut();
        fip_24.setElementMap(fyy_03);
        fip_24.setAlign(frs_0.h);
        fso16.addBasicElement(fip_24);
        fip_24.onAttributesInitialized();
        fip_24.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_03);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("unloadDialog");
        fru_02.setOnClick(fdt_12);
        fru_02.setPrefSize(new fjf_2(308, 36));
        fru_02.setStyle("secondaryMedium");
        String string4 = "%death.waitForRaise%";
        string4 = string4.replace("%death.waitForRaise%", fpm_0.b().c("death.waitForRaise"));
        fru_02.setText(string4);
        fso16.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_02.onChildrenAdded();
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_03);
        fru_03.setExpandable(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.death:respawnToRespawnPoint");
        fru_03.setOnClick(fdt_13);
        fru_03.setPrefSize(new fjf_2(308, 36));
        fru_03.setStyle("primaryMedium");
        String string5 = "%respawn.to.respawn.point%";
        string5 = string5.replace("%respawn.to.respawn.point%", fpm_0.b().c("respawn.to.respawn.point"));
        fru_03.setText(string5);
        fso16.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        fru_03.onChildrenAdded();
        fru_0 fru_04 = new fru_0();
        fru_04.onCheckOut();
        fru_04.setElementMap(fyy_03);
        fru_04.setExpandable(false);
        fdt_1 fdt_14 = new fdt_1();
        fdt_14.a("wakfu.death:respawn");
        fru_04.setOnClick(fdt_14);
        fru_04.setPixmapAlign(frm_0.c);
        fru_04.setPrefSize(new fjf_2(308, 36));
        fru_04.setStyle("primaryMedium");
        String string6 = "%death.respawn%";
        string6 = string6.replace("%death.respawn%", fpm_0.b().c("death.respawn"));
        fru_04.setText(string6);
        fso16.addBasicElement(fru_04);
        fru_04.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("enabled");
        fiy_12.setField("haveResurrectItem");
        fiy_12.setName("deathView");
        fru_04.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setDisplaySize(new fjf_2(36, 36));
        fsk_02.setNonBlocking(true);
        fru_04.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("texture");
        fiy_13.setField("iconUrl");
        fiy_13.setName("resurrectItem");
        fqv2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fru_04.onChildrenAdded();
        fru_0 fru_05 = new fru_0();
        fru_05.onCheckOut();
        fru_05.setElementMap(fyy_03);
        fru_05.setExpandable(false);
        fdt_1 fdt_15 = new fdt_1();
        fdt_15.a("wakfu.death:respawnAdmin");
        fru_05.setOnClick(fdt_15);
        fru_05.setPixmapAlign(frm_0.c);
        fru_05.setPrefSize(new fjf_2(308, 36));
        fru_05.setStyle("primaryMedium");
        String string7 = "%death.respawn% (admin)";
        string7 = string7.replace("%death.respawn%", fpm_0.b().c("death.respawn"));
        fru_05.setText(string7);
        fso16.addBasicElement(fru_05);
        fru_05.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("visible");
        fiy_14.setName("isAdmin");
        fru_05.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fru_05.onChildrenAdded();
        fso16.onChildrenAdded();
        fso13.onChildrenAdded();
        fso10.onChildrenAdded();
        fso8.onChildrenAdded();
        fso4.onChildrenAdded();
        fso fso17 = fso.checkOut();
        fso17.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso17);
        fso17.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_03);
        fid_16.setSize(new fjf_2(100.0f, 100.0f));
        fso17.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fso17.onChildrenAdded();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_03);
        fid_17.setAlign(frk_0.i);
        fvk_02.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fvk_02.onChildrenAdded();
        return fvk_02;
    }
}

