/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cMR
 */
public class cmr_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        String string = "mapWindow";
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fso2);
        }
        fso2.setNonBlocking(false);
        fso2.onAttributesInitialized();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fbf_1 fbf_12 = new fbf_1();
        fbf_12.onCheckOut();
        fbf_12.setElementMap(fyy_03);
        fbf_12.setColor(new azf_2(0.0f, 0.0f, 0.0f, 0.7f));
        fqj2.addBasicElement(fbf_12);
        fbf_12.onAttributesInitialized();
        fbf_12.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso2.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_03);
        fso2.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso4.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(-2, -2));
        fso4.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso4.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fic_14.setAdaptToContentSize(true);
        fso5.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(-2, -2));
        fso5.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fso fso6 = fso5;
        fqj fqj3 = ((fvE)fso6).getAppearance();
        fqj3.setElementMap(fyy_03);
        fso5.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(100, 50, 100, 50));
        fqj3.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        String string2 = "map";
        fsY fsY2 = new fsY();
        fsY2.onCheckOut();
        fsY2.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fsY2);
        }
        fsY2.setExpandable(false);
        fsY2.setIsoMap(true);
        fdi_1 fdi_12 = new fdi_1();
        fdi_12.a("wakfu.dragoMap:onMapItemClick");
        fsY2.setOnItemClick(fdi_12);
        fdk_2 fdk_22 = new fdk_2();
        fdk_22.a("wakfu.dragoMap:onMapItemOut");
        fsY2.setOnItemOut(fdk_22);
        fdl_2 fdl_22 = new fdl_2();
        fdl_22.a("wakfu.dragoMap:onMapItemOver");
        fsY2.setOnItemOver(fdl_22);
        fdq_1 fdq_12 = new fdq_1();
        fdq_12.a("wakfu.dragoMap:onMapClick(map)");
        fsY2.setOnMapClick(fdq_12);
        fdr_1 fdr_12 = new fdr_1();
        fdr_12.a("wakfu.dragoMap:adminTP");
        fsY2.setOnMapDoubleClick(fdr_12);
        fds_1 fds_12 = new fds_1();
        fds_12.a("wakfu.dragoMap:onMapMove");
        fsY2.setOnMapMove(fds_12);
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.a("wakfu.dragoMap:onMouseEnter");
        fsY2.setOnMouseEnter(fdy_12);
        fdz_1 fdz_12 = new fdz_1();
        fdz_12.a("wakfu.dragoMap:onMouseExit");
        fsY2.setOnMouseExit(fdz_12);
        fdb_1 fdb_12 = new fdb_1();
        fdb_12.a("wakfu.dragoMap:onMousePress");
        fsY2.setOnMousePress(fdb_12);
        fdc_2 fdc_22 = new fdc_2();
        fdc_22.a("wakfu.dragoMap:onMouseRelease");
        fsY2.setOnMouseRelease(fdc_22);
        fsY2.setTooltipHotPoint(aiO.b);
        fso5.addBasicElement(fsY2);
        fsY2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("mapPath");
        fiy_12.setField("map");
        fiy_12.setName("map");
        fsY2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("mapId");
        fiy_13.setField("mapId");
        fiy_13.setName("map");
        fsY2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("content");
        fiy_14.setField("landmarks/points");
        fiy_14.setName("map");
        fsY2.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("compassContent");
        fiy_15.setField("landmarks/compass");
        fiy_15.setName("map");
        fsY2.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("knownMaps");
        fiy_16.setField("availableMapsCoords");
        fiy_16.setName("map");
        fsY2.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.i);
        fid_15.setSize(new fjf_2(-2, -2));
        fsY2.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fsY fsY3 = fsY2;
        fqs fqs2 = (fqs)((fvE)fsY3).getAppearance();
        fqs2.setElementMap(fyy_03);
        fqs2.setShape(fqq_0.b);
        fsY2.addBasicElement(fqs2);
        fqs2.onAttributesInitialized();
        fqs2.onChildrenAdded();
        fsY2.onChildrenAdded();
        fso5.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso4.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fso fso8 = fso7;
        fqj fqj4 = ((fvE)fso8).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso7.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqj4.onChildrenAdded();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_03);
        fid_16.setSize(new fjf_2(100.0f, 100.0f));
        fso7.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fic_1 fic_15 = new fic_1();
        fic_15.onCheckOut();
        fic_15.setAdaptToContentSize(true);
        fso7.addBasicElement(fic_15);
        fic_15.onAttributesInitialized();
        fic_15.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_03);
        fso7.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_03);
        fid_17.setSize(new fjf_2(-2, -2));
        fid_17.setXPerc(new fjv_1(80.0));
        fid_17.setYPerc(new fjv_1(80.0));
        fso9.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fic_1 fic_16 = new fic_1();
        fic_16.onCheckOut();
        fic_16.setAdaptToContentSize(true);
        fso9.addBasicElement(fic_16);
        fic_16.onAttributesInitialized();
        fic_16.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setStyle("mapButtons");
        fso9.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_03);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(5, 0, 0, 0));
        fqp2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqp2.onChildrenAdded();
        fid_1 fid_18 = new fid_1();
        fid_18.onCheckOut();
        fid_18.setElementMap(fyy_03);
        fid_18.setSize(new fjf_2(-2, -2));
        fsk_02.addBasicElement(fid_18);
        fid_18.onAttributesInitialized();
        fid_18.onChildrenAdded();
        fsk_02.onChildrenAdded();
        String string3 = "closeMapButton";
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fru_02);
        }
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("unloadDialog");
        fru_02.setOnClick(fdt_12);
        fru_02.setPrefSize(new fjf_2(35, 20));
        fru_02.setStyle("mapClose");
        fso9.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_19 = new fid_1();
        fid_19.onCheckOut();
        fid_19.setElementMap(fyy_03);
        fid_19.setAlign(frk_0.i);
        fid_19.setSize(new fjf_2(-2, -2));
        fid_19.setXOffset(44);
        fid_19.setYOffset(-15);
        fru_02.addBasicElement(fid_19);
        fid_19.onAttributesInitialized();
        fid_19.onChildrenAdded();
        fru_02.onChildrenAdded();
        fso9.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        fso7.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fid_1 fid_110 = new fid_1();
        fid_110.onCheckOut();
        fid_110.setElementMap(fyy_03);
        fid_110.setSize(new fjf_2(-2, -2));
        fid_110.setXPerc(new fjv_1(5.0));
        fid_110.setYPerc(new fjv_1(5.0));
        fso10.addBasicElement(fid_110);
        fid_110.onAttributesInitialized();
        fid_110.onChildrenAdded();
        fic_1 fic_17 = new fic_1();
        fic_17.onCheckOut();
        fic_17.setAdaptToContentSize(true);
        fso10.addBasicElement(fic_17);
        fic_17.onAttributesInitialized();
        fic_17.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_03);
        fsk_04.setDisplaySize(new fjf_2(430, 250));
        fsk_04.setKeepAspectRatio(true);
        fsk_04.setNonBlocking(true);
        fsk_04.setScaled(true);
        fsk_04.setStyle("filterBackground");
        fso10.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fsk_0 fsk_05 = fsk_04;
        fqp fqp3 = (fqp)((fvE)fsk_05).getAppearance();
        fqp3.setElementMap(fyy_03);
        fsk_04.addBasicElement(fqp3);
        fqp3.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(5, 0, 0, 0));
        fqp3.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqp3.onChildrenAdded();
        fid_1 fid_111 = new fid_1();
        fid_111.onCheckOut();
        fid_111.setElementMap(fyy_03);
        fid_111.setSize(new fjf_2(-2, -2));
        fsk_04.addBasicElement(fid_111);
        fid_111.onAttributesInitialized();
        fid_111.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_03);
        fsQ2.setCellSize(new fjf_2(58, 29));
        fsQ2.setExpandable(false);
        fsQ2.setIsoColumnCount(1);
        fsQ2.setIsoPositiveFactor(false);
        fsQ2.setListLayoutMode(fqu_0.b);
        fso10.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fid_1 fid_112 = new fid_1();
        fid_112.onCheckOut();
        fid_112.setElementMap(fyy_03);
        fid_112.setAlign(frk_0.c);
        fid_112.setSize(new fjf_2(100.0f, 100.0f));
        fid_112.setXOffset(0);
        fid_112.setYOffset(-25);
        fsQ2.addBasicElement(fid_112);
        fid_112.onAttributesInitialized();
        fid_112.onChildrenAdded();
        fsQ fsQ3 = fsQ2;
        fqr fqr2 = (fqr)((fvE)fsQ3).getAppearance();
        fqr2.setElementMap(fyy_03);
        fsQ2.addBasicElement(fqr2);
        fqr2.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(0, 35, 0, 0));
        fqr2.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqr2.onChildrenAdded();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_03);
        fiy_17.setAttribute("content");
        fiy_17.setField("typeFilterList");
        fiy_17.setName("landMark.filters");
        fsQ2.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_03);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_03);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        String string4 = "typeFilter";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_03);
        if (fyy_03 != null && string4 != null) {
            fyy_03.a(string4, fij_12);
        }
        faf_22.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_03);
        fir_12.setAttribute("value");
        fir_12.setField("id");
        fij_12.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fij_12.onChildrenAdded();
        fic_1 fic_18 = new fic_1();
        fic_18.onCheckOut();
        faf_22.addBasicElement(fic_18);
        fic_18.onAttributesInitialized();
        fic_18.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_03);
        faf_22.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        String string5 = "filter";
        fup_0 fup_02 = new fup_0();
        fup_02.onCheckOut();
        fup_02.setElementMap(fyy_03);
        if (fyy_03 != null && string5 != null) {
            fyy_03.a(string5, fup_02);
        }
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(filterDescPopup,filter)");
        fup_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fup_02.setOnPopupHide(fdf_22);
        fdi_2 fdi_22 = new fdi_2();
        fdi_22.a("wakfu.dragoMap:setTypeFilter(typeFilter)");
        fup_02.setOnSelectionChange(fdi_22);
        faf_22.addBasicElement(fup_02);
        fup_02.onAttributesInitialized();
        fid_1 fid_113 = new fid_1();
        fid_113.onCheckOut();
        fid_113.setElementMap(fyy_03);
        fid_113.setAlign(frk_0.i);
        fid_113.setSize(new fjf_2(-2, -2));
        fup_02.addBasicElement(fid_113);
        fid_113.onAttributesInitialized();
        fid_113.onChildrenAdded();
        String string6 = "filterDescPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_03);
        if (fyy_03 != null && string6 != null) {
            fyy_03.a(string6, fil_12);
        }
        fil_12.setAlign(frs_0.h);
        fil_12.setHotSpotPosition(frs_0.b);
        fup_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso11.setPrefSize(new fjf_2(10, 0));
        fso11.setStyle("popup");
        fil_12.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_03);
        fii_22.setData(frg_0.e);
        fso11.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setStyle("White11");
        fso11.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.d);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_03);
        fir_13.setAttribute("text");
        fir_13.setField("name");
        fuk_02.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso11.onChildrenAdded();
        fil_12.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_03);
        fir_14.setAttribute("style");
        fir_14.setField("style");
        fup_02.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_03);
        fir_15.setAttribute("selected");
        fir_15.setField("selected");
        fup_02.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fup_02.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        this.a(fso10);
        fso10.onChildrenAdded();
        fso7.onChildrenAdded();
        fso4.onChildrenAdded();
        this.b(fso2);
        this.c(fso2);
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        String string = "territoryFilter";
        fup_0 fup_02 = new fup_0();
        fup_02.onCheckOut();
        fup_02.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fup_02);
        }
        fup_02.setExpandable(false);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(filterDescPopup,territoryFilter)");
        fup_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fup_02.setOnPopupHide(fdf_22);
        fdi_2 fdi_22 = new fdi_2();
        fdi_22.a("wakfu.dragoMap:setDisplayTerritories");
        fup_02.setOnSelectionChange(fdi_22);
        fup_02.setStyle("filterTerritory");
        fso2.addBasicElement(fup_02);
        fup_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.q);
        fid_12.setXOffset(-45);
        fid_12.setYOffset(45);
        fup_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("selected");
        fiy_12.setField("displayTerritories");
        fiy_12.setName("map");
        fup_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        String string2 = "filterDescPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fil_12);
        }
        fil_12.setAlign(frs_0.h);
        fil_12.setHotSpotPosition(frs_0.b);
        fup_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setPrefSize(new fjf_2(10, 0));
        fso3.setStyle("popup");
        fil_12.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.e);
        fso3.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setStyle("White11");
        String string3 = "%map.territories%";
        string3 = string3.replace("%map.territories%", fpm_0.b().c("map.territories"));
        fuk_02.c(string3);
        fso3.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        fil_12.onChildrenAdded();
        fup_02.onChildrenAdded();
        return fup_02;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setPrefSize(new fjf_2(400, 66));
        fso3.setStyle("new");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(5, 15, 5, 15));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setSize(new fjf_2(-2, -2));
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(false);
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setPrefSize(new fjf_2(66, 66));
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.h);
        fso5.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso6.setPrefSize(new fjf_2(66, 66));
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(protectorDescPopup)");
        fso6.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fso6.setOnPopupHide(fdf_22);
        fso5.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso6.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso7.setNeedsScissor(true);
        fso6.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(46, 46));
        fso7.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        frO frO2 = new frO();
        frO2.onCheckOut();
        frO2.setElementMap(fyy_02);
        frO2.setAnimName("AnimStatique-Neutre");
        frO2.setDirection(1);
        frO2.setOffsetX(1.0f);
        frO2.setOffsetY(-7.0f);
        frO2.setScale(0.75f);
        fso7.addBasicElement(frO2);
        frO2.onAttributesInitialized();
        frO frO3 = frO2;
        fqb fqb2 = (fqb)((fvE)frO3).getAppearance();
        fqb2.setElementMap(fyy_02);
        frO2.addBasicElement(fqb2);
        fqb2.onAttributesInitialized();
        fbf_1 fbf_12 = new fbf_1();
        fbf_12.onCheckOut();
        fbf_12.setElementMap(fyy_02);
        fbf_12.setColor(new azf_2(0.0f, 0.0f, 0.0f, 0.5f));
        fqb2.addBasicElement(fbf_12);
        fbf_12.onAttributesInitialized();
        fbf_12.onChildrenAdded();
        fqb2.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("animatedElement");
        fiy_12.setField("animation");
        fiy_12.setName("protector");
        frO2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("animName");
        fiy_13.setField("animName");
        fiy_13.setName("protector");
        frO2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        frO2.onChildrenAdded();
        fso7.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso8.setStyle("protectorSimpleFrameOver");
        fso6.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setSize(new fjf_2(100.0f, 100.0f));
        fid_15.setXOffset(1);
        fid_15.setYOffset(-1);
        fso8.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fso8.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("visible");
        fiy_14.setField("currentProtector");
        fiy_14.setName("protector");
        fso6.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_14.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fae_2 fae_22 = new fae_2();
        fae_22.onCheckOut();
        fae_22.setElementMap(fyy_02);
        far_22.addBasicElement(fae_22);
        fae_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fae_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        fae_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("comparedValue");
        fiy_15.setField("isStatic");
        fiy_15.setName("protector");
        fai_12.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fai_12.onChildrenAdded();
        fae_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_14.onChildrenAdded();
        String string = "protectorDescPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fil_12);
        }
        fil_12.setAlign(frs_0.h);
        fil_12.setHotSpotPosition(frs_0.b);
        fso6.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_02);
        fso9.setPrefSize(new fjf_2(10, 0));
        fso9.setStyle("popup");
        fil_12.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setStyle("White11");
        fso9.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.d);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_02);
        fiy_16.setAttribute("text");
        fiy_16.setField("currentProtectorDescription");
        fiy_16.setName("map");
        fuk_02.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso9.onChildrenAdded();
        fil_12.onChildrenAdded();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_02);
        fid_16.setAlign(frk_0.a);
        fid_16.setSize(new fjf_2(81, 81));
        fid_16.setXOffset(2);
        fid_16.setYOffset(-1);
        fso6.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fso6.onChildrenAdded();
        fso5.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_02);
        fso10.setPrefSize(new fjf_2(0, 48));
        fso3.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_02);
        fid_17.setAlign(frk_0.i);
        fso10.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fso fso11 = fso10;
        fqj fqj3 = ((fvE)fso11).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso10.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(5, 3, 5, 3));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso10.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_02);
        fuk_04.setStyle("title");
        fso10.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fuk_0 fuk_05 = fuk_04;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_05).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlign(frs_0.e);
        fuk_04.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_02);
        fiy_17.setAttribute("text");
        fiy_17.setField("currentMapName");
        fiy_17.setName("map");
        fuk_04.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_02);
        fiy_18.setAttribute("visible");
        fiy_18.setField("currentMapName");
        fiy_18.setName("map");
        fuk_04.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        fiy_18.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_02);
        far_23.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_18.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fuk_0 fuk_06 = new fuk_0();
        fuk_06.onCheckOut();
        fuk_06.setElementMap(fyy_02);
        fuk_06.setStyle("title");
        fso10.addBasicElement(fuk_06);
        fuk_06.onAttributesInitialized();
        fuk_0 fuk_07 = fuk_06;
        fqh_0 fqh_04 = (fqh_0)((fvE)fuk_07).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fqh_04.setAlign(frs_0.e);
        fuk_06.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_02);
        fiy_19.setAttribute("text");
        fiy_19.setField("currentTerritoryName");
        fiy_19.setName("map");
        fuk_06.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        fiy_19.onChildrenAdded();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_02);
        fiy_110.setAttribute("visible");
        fiy_110.setField("currentTerritoryName");
        fiy_110.setName("map");
        fuk_06.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_02);
        fiy_110.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fab_2 fab_24 = new fab_2();
        fab_24.onCheckOut();
        fab_24.setElementMap(fyy_02);
        far_24.addBasicElement(fab_24);
        fab_24.onAttributesInitialized();
        fab_24.onChildrenAdded();
        far_24.onChildrenAdded();
        fiy_110.onChildrenAdded();
        fuk_06.onChildrenAdded();
        fso10.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_02);
        fso12.setPrefSize(new fjf_2(48, 48));
        fso3.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fid_1 fid_18 = new fid_1();
        fid_18.onCheckOut();
        fid_18.setElementMap(fyy_02);
        fid_18.setAlign(frk_0.j);
        fso12.addBasicElement(fid_18);
        fid_18.onAttributesInitialized();
        fid_18.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(48, 48));
        fso12.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(5, 0, 5, 5));
        fqp2.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqp2.onChildrenAdded();
        fiy_1 fiy_111 = fiy_1.checkOut();
        fiy_111.setElementMap(fyy_02);
        fiy_111.setAttribute("visible");
        fiy_111.setField("currentTerritoryIconUrl");
        fiy_111.setName("map");
        fsk_02.addBasicElement(fiy_111);
        fiy_111.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_02);
        fiy_111.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fab_2 fab_25 = new fab_2();
        fab_25.onCheckOut();
        fab_25.setElementMap(fyy_02);
        far_25.addBasicElement(fab_25);
        fab_25.onAttributesInitialized();
        fab_25.onChildrenAdded();
        far_25.onChildrenAdded();
        fiy_111.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_112 = fiy_1.checkOut();
        fiy_112.setElementMap(fyy_02);
        fiy_112.setAttribute("texture");
        fiy_112.setField("currentTerritoryIconUrl");
        fiy_112.setName("map");
        fqv2.addBasicElement(fiy_112);
        fiy_112.onAttributesInitialized();
        fiy_112.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso12.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 0, 0, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.o);
        fid_12.setSize(new fjf_2(100.0f, -2));
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setStyle("BigTitle");
        String string = "%map.position%";
        string = string.replace("%map.position%", fpm_0.b().c("map.position"));
        fsM2.c(string);
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 10, 0, 0));
        fqh_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setExpandable(false);
        fsM4.setStyle("11Light");
        fso3.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fsM4.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 3, 0, 0));
        fqh_03.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("displayedPosition");
        fiy_12.setName("map");
        fsM4.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }
}

