/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cMw
 */
public class cmw_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        fvk_02.setPack(true);
        fvk_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvk_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("windowNew");
        fvk_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(10, 5, 12, 5));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setExpandable(false);
        fso3.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fvM fvM3 = fvM2;
        fqj fqj3 = ((fvE)fvM3).getAppearance();
        fqj3.setElementMap(fyy_03);
        fvM2.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 10, 0, 10));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setStyle("titleBar");
        fvM2.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso fso6 = fso5;
        fqj fqj4 = ((fvE)fso6).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso5.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(3, 20, 3, 20));
        fqj4.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.e);
        fso7.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("StyledBold16White");
        String string = "%chat.contactList%";
        string = string.replace("%chat.contactList%", fpm_0.b().c("chat.contactList"));
        fsM2.c(string);
        fso7.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        fvM2.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso3.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj5 = ((fvE)fso9).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso8.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 12, 0, 12));
        fqj5.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj5.onChildrenAdded();
        String string2 = "windowContentContainer";
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fso10);
        }
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso10.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso11.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        fso11.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.o);
        fid_14.setSize(new fjf_2(100.0f, 100.0f));
        fso12.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.b);
        fin_24.setHorizontal(false);
        fso12.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        String string3 = "tabbedContainer";
        fut_0 fut_02 = new fut_0();
        fut_02.onCheckOut();
        fut_02.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fut_02);
        }
        fut_02.setExpandable(false);
        fut_02.setPrefSize(new fjf_2(638, 382));
        fut_02.setTabsAlignment(fro_0.d);
        fut_02.setTabsLabelAlignment(frs_0.e);
        fut_02.setTabsPosition(frm_0.a);
        fut_02.setTabsSizesEquilibrate(false);
        fut_02.setTabsXOffset(6);
        fut_02.setTabsYOffset(-6);
        fut_02.setTextOrientation(frh_0.c);
        fso12.addBasicElement(fut_02);
        fut_02.onAttributesInitialized();
        fut_0 fut_03 = fut_02;
        fqj fqj6 = ((fvE)fut_03).getAppearance();
        fqj6.setElementMap(fyy_03);
        fut_02.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(5, 5, 0, 0));
        fqj6.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqj6.onChildrenAdded();
        fin_1 fin_12 = new fin_1();
        fin_12.onCheckOut();
        fin_12.setElementMap(fyy_03);
        String string4 = "%desc.friendList%";
        string4 = string4.replace("%desc.friendList%", fpm_0.b().c("desc.friendList"));
        fin_12.setText(string4);
        fut_02.addBasicElement(fin_12);
        fin_12.onAttributesInitialized();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_03);
        fso13.setStyle("white");
        fin_12.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fso fso14 = fso13;
        fqj fqj7 = ((fvE)fso14).getAppearance();
        fqj7.setElementMap(fyy_03);
        fso13.addBasicElement(fqj7);
        fqj7.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_03);
        fqo_04.setInsets(new Insets(0, 15, 10, 15));
        fqj7.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj7.onChildrenAdded();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setHorizontal(false);
        fso13.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_03);
        fso15.setExpandable(false);
        fso13.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setAlign(frs_0.d);
        fso15.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_03);
        fso16.setExpandable(false);
        fso15.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        fso fso17 = fso16;
        fqj fqj8 = ((fvE)fso17).getAppearance();
        fqj8.setElementMap(fyy_03);
        fso16.addBasicElement(fqj8);
        fqj8.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(3, 3, 3, 0));
        fqj8.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqj8.onChildrenAdded();
        fin_2 fin_27 = fin_2.checkOut();
        fin_27.setAlign(frs_0.d);
        fso16.addBasicElement(fin_27);
        fin_27.onAttributesInitialized();
        fin_27.onChildrenAdded();
        String string5 = "customFriendName";
        fug_0 fug_02 = new fug_0();
        fug_02.onCheckOut();
        fug_02.setElementMap(fyy_03);
        if (fyy_03 != null && string5 != null) {
            fyy_03.a(string5, fug_02);
        }
        fug_02.setExpandable(false);
        String string6 = "%guild.nameToInvite%";
        string6 = string6.replace("%guild.nameToInvite%", fpm_0.b().c("guild.nameToInvite"));
        fug_02.b(string6);
        fug_02.a(64);
        fdm_2 fdm_22 = new fdm_2();
        fdm_22.a("wakfu.contactList:addFriend()");
        fug_02.setOnKeyPress(fdm_22);
        fug_02.setPrefSize(new fjf_2(175, 0));
        fug_02.setSelectOnFocus(true);
        fso16.addBasicElement(fug_02);
        fug_02.onAttributesInitialized();
        fug_02.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_03);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.contactList:addFriend()");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(addToFriendPopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setStyle("add");
        fso16.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_03);
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqo_0 fqo_05 = new fqo_0();
        fqo_05.onCheckOut();
        fqo_05.setElementMap(fyy_03);
        fqo_05.setInsets(new Insets(2, 2, 2, 2));
        fqd_02.addBasicElement(fqo_05);
        fqo_05.onAttributesInitialized();
        fqo_05.onChildrenAdded();
        fqd_02.onChildrenAdded();
        String string7 = "addToFriendPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_03);
        if (fyy_03 != null && string7 != null) {
            fyy_03.a(string7, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso18 = fso.checkOut();
        fso18.setElementMap(fyy_03);
        fso18.setPrefSize(new fjf_2(10, 0));
        fso18.setStyle("popup");
        fil_12.addBasicElement(fso18);
        fso18.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_03);
        fii_22.setData(frg_0.e);
        fso18.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_03);
        fsM4.setStyle("PopupInformation");
        String string8 = "%addToFriendList%";
        string8 = string8.replace("%addToFriendList%", fpm_0.b().c("addToFriendList"));
        fsM4.c(string8);
        fso18.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fqh_03.setAlignment(frs_0.d);
        fsM4.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso18.onChildrenAdded();
        fil_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        fso16.onChildrenAdded();
        fso15.onChildrenAdded();
        String string9 = "guildTable";
        fuc_0 fuc_02 = new fuc_0();
        fuc_02.onCheckOut();
        fuc_02.setElementMap(fyy_03);
        if (fyy_03 != null && string9 != null) {
            fyy_03.a(string9, fuc_02);
        }
        fuc_02.setCellHeight(30);
        fuc_02.setExpandable(false);
        fuc_02.setMaxRows(8);
        fuc_02.setMinRows(8);
        fso13.addBasicElement(fuc_02);
        fuc_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("content");
        fiy_12.setField("friendsList/contentList");
        fiy_12.setName("contact.list");
        fuc_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fxs_0 fxs_02 = new fxs_0();
        fxs_02.onCheckOut();
        fxs_02.setElementMap(fyy_03);
        fxs_02.setCellWidth(390);
        fxs_02.setColumnId("name");
        String string10 = "%name%";
        string10 = string10.replace("%name%", fpm_0.b().c("name"));
        fxs_02.setName(string10);
        fuc_02.addBasicElement(fxs_02);
        fxs_02.onAttributesInitialized();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_03);
        fxs_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        String string11 = "name";
        fso fso19 = fso.checkOut();
        fso19.setElementMap(fyy_03);
        if (fyy_03 != null && string11 != null) {
            fyy_03.a(string11, fso19);
        }
        fde_2 fde_23 = new fde_2();
        fde_23.a("popup(contactPopup)");
        fso19.setOnPopupDisplay(fde_23);
        fdf_2 fdf_23 = new fdf_2();
        fdf_23.a("closePopup");
        fso19.setOnPopupHide(fdf_23);
        faf_22.addBasicElement(fso19);
        fso19.onAttributesInitialized();
        String string12 = "contactPopup";
        fil_1 fil_13 = new fil_1();
        fil_13.onCheckOut();
        fil_13.setElementMap(fyy_03);
        if (fyy_03 != null && string12 != null) {
            fyy_03.a(string12, fil_13);
        }
        fil_13.setAlign(frs_0.b);
        fil_13.setHotSpotPosition(frs_0.h);
        fso19.addBasicElement(fil_13);
        fil_13.onAttributesInitialized();
        fso fso20 = fso.checkOut();
        fso20.setElementMap(fyy_03);
        fso20.setPrefSize(new fjf_2(10, 0));
        fso20.setStyle("popup");
        fil_13.addBasicElement(fso20);
        fso20.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_03);
        fir_12.setAttribute("visible");
        fir_12.setField("commentary");
        fso20.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        fir_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fir_12.onChildrenAdded();
        fii_2 fii_23 = fii_2.checkOut();
        fii_23.setElementMap(fyy_03);
        fii_23.setData(frg_0.a);
        fso20.addBasicElement(fii_23);
        fii_23.onAttributesInitialized();
        fii_23.onChildrenAdded();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_03);
        fsM6.setStyle("PopupInformation");
        fso20.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fsM fsM7 = fsM6;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM7).getAppearance();
        fqh_04.setElementMap(fyy_03);
        fqh_04.setAlignment(frs_0.d);
        fsM6.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_03);
        fir_13.setAttribute("text");
        fir_13.setField("commentary");
        fsM6.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fsM6.onChildrenAdded();
        fso20.onChildrenAdded();
        fil_13.onChildrenAdded();
        fin_2 fin_28 = fin_2.checkOut();
        fin_28.setAlign(frs_0.d);
        fso19.addBasicElement(fin_28);
        fin_28.onAttributesInitialized();
        fin_28.onChildrenAdded();
        fso fso21 = fso19;
        fqj fqj9 = ((fvE)fso21).getAppearance();
        fqj9.setElementMap(fyy_03);
        fso19.addBasicElement(fqj9);
        fqj9.onAttributesInitialized();
        fqo_0 fqo_06 = new fqo_0();
        fqo_06.onCheckOut();
        fqo_06.setElementMap(fyy_03);
        fqo_06.setInsets(new Insets(0, 1, 0, 0));
        fqj9.addBasicElement(fqo_06);
        fqo_06.onAttributesInitialized();
        fqo_06.onChildrenAdded();
        fqj9.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setExpandable(false);
        fso19.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        this.a(fsk_02);
        this.b(fsk_02);
        this.c(fsk_02);
        fsk_02.onChildrenAdded();
        this.a(fso19);
        this.b(fso19);
        fso19.onChildrenAdded();
        faf_22.onChildrenAdded();
        fxs_02.onChildrenAdded();
        this.a(fuc_02);
        this.b(fuc_02);
        fuc_02.onChildrenAdded();
        fso13.onChildrenAdded();
        fin_12.onChildrenAdded();
        this.a(fut_02);
        fut_02.onChildrenAdded();
        fso12.onChildrenAdded();
        this.h(fso11);
        fso11.onChildrenAdded();
        fso10.onChildrenAdded();
        fso8.onChildrenAdded();
        fso3.onChildrenAdded();
        this.a(fvk_02);
        this.b(fvk_02);
        this.c(fvk_02);
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fsk_0 fsk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("visible");
        fsk_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fir_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fir_12.onChildrenAdded();
        return fir_12;
    }

    public fyo b(fsk_0 fsk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("style");
        fir_12.setField("online");
        fsk_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        far_22.setElseValue("DisconnectedStatut");
        far_22.setValue("ConnectedStatut");
        fir_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fir_12.onChildrenAdded();
        return fir_12;
    }

    public fyo c(fsk_0 fsk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(2, 2, 2, 4));
        fqp2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqp2.onChildrenAdded();
        return fqp2;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setNeedsScissor(true);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setExpandable(false);
        fsk_02.setScaled(true);
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(85, 28));
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("texture");
        fir_12.setField("illustrationUrl");
        fqv2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.e);
        fso3.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setEnableAutoZoomShrink(true);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(280);
        fuk_02.setMinWidth(150);
        fuk_02.setStyle("white");
        fso3.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("text");
        fir_12.setField("name");
        fuk_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 3, 0, 0));
        fqh_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setEnableAutoZoomShrink(true);
        fsM2.setExpandable(false);
        fsM2.setMaxWidth(280);
        fsM2.setMinWidth(150);
        fsM2.setStyle("LightBlue");
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("text");
        fir_13.setField("characterNameWithLanguages");
        fsM2.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fsM fsM3 = fsM2;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fsM2.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 3, 0, 0));
        fqh_03.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo a(fuc_0 fuc_02) {
        fyy_0 fyy_02 = this.a.peek();
        fxs_0 fxs_02 = new fxs_0();
        fxs_02.onCheckOut();
        fxs_02.setElementMap(fyy_02);
        fxs_02.setCellWidth(45);
        fxs_02.setColumnId("level");
        String string = "%levelShort%";
        string = string.replace("%levelShort%", fpm_0.b().c("levelShort"));
        fxs_02.setName(string);
        fuc_02.addBasicElement(fxs_02);
        fxs_02.onAttributesInitialized();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fxs_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        String string2 = "level";
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fso2);
        }
        faf_22.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fbh_1 fbh_12 = new fbh_1();
        fbh_12.onCheckOut();
        fbh_12.setElementMap(fyy_02);
        fbh_12.setColor(new fyr_0("defaultLightColor"));
        fbh_12.setInsets(new Insets(0, 1, 0, 0));
        fqj2.addBasicElement(fbh_12);
        fbh_12.onAttributesInitialized();
        fbh_12.onChildrenAdded();
        fqj2.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setMaxSize(new fjf_2(45, 24));
        fsM2.setPrefSize(new fjf_2(45, 0));
        fsM2.setStyle("whiteBold");
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("text");
        fir_12.setField("level");
        fsM2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso3.onChildrenAdded();
        fso2.onChildrenAdded();
        faf_22.onChildrenAdded();
        faf_2 faf_23 = new faf_2();
        faf_23.onCheckOut();
        faf_23.setElementMap(fyy_02);
        fxs_02.addBasicElement(faf_23);
        faf_23.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_23.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fac_1 fac_12 = new fac_1();
        fac_12.onCheckOut();
        fac_12.setElementMap(fyy_02);
        fav_12.addBasicElement(fac_12);
        fac_12.onAttributesInitialized();
        fac_12.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setExpandable(false);
        faf_23.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso fso6 = fso5;
        fqj fqj3 = ((fvE)fso6).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso5.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fbh_1 fbh_13 = new fbh_1();
        fbh_13.onCheckOut();
        fbh_13.setElementMap(fyy_02);
        fbh_13.setColor(new fyr_0("defaultLightColor"));
        fbh_13.setInsets(new Insets(0, 1, 0, 0));
        fqj3.addBasicElement(fbh_13);
        fbh_13.onAttributesInitialized();
        fbh_13.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso5.onChildrenAdded();
        faf_23.onChildrenAdded();
        fxs_02.onChildrenAdded();
        return fxs_02;
    }

    public fyo b(fuc_0 fuc_02) {
        fyy_0 fyy_02 = this.a.peek();
        fxs_0 fxs_02 = new fxs_0();
        fxs_02.onCheckOut();
        fxs_02.setElementMap(fyy_02);
        fxs_02.setCellWidth(164);
        fxs_02.setColumnId("controls");
        fuc_02.addBasicElement(fxs_02);
        fxs_02.onAttributesInitialized();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fxs_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        String string = "primaryContact";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fij_12);
        }
        faf_22.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("value");
        fij_12.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        faf_22.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setPrefSize(new fjf_2(163, 0));
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fbh_1 fbh_12 = new fbh_1();
        fbh_12.onCheckOut();
        fbh_12.setElementMap(fyy_02);
        fbh_12.setColor(new fyr_0("defaultLightColor"));
        fbh_12.setInsets(new Insets(0, 1, 0, 0));
        fqj2.addBasicElement(fbh_12);
        fbh_12.onAttributesInitialized();
        fbh_12.onChildrenAdded();
        fqj2.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setExpandable(false);
        fso5.setMaxSize(new fjf_2(143, 24));
        fso5.setPrefSize(new fjf_2(143, 0));
        fso5.setShrinkable(true);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("visible");
        fso5.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        fir_13.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_02);
        far_23.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_23.onChildrenAdded();
        fir_13.onChildrenAdded();
        fso fso6 = fso5;
        fqj fqj3 = ((fvE)fso6).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso5.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 2, 0, 0));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso5.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("visible");
        fir_14.setField("commentaryEdition");
        fso7.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_02);
        fir_14.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        far_24.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_24.onChildrenAdded();
        fir_14.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso7.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.d);
        fso7.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso8.setExpandable(false);
        fso8.setPrefSize(new fjf_2(30, 25));
        fso7.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fso8.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.contactList:addCommentary(primaryContact)");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(addCommentaryPopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setStyle("yellow");
        fso8.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("enabled");
        fir_15.setField("online");
        fru_02.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fru_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_02);
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(2, 2, 2, 0));
        fqd_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqd_02.onChildrenAdded();
        String string2 = "addCommentaryPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fil_12);
        }
        fil_12.setAlign(frs_0.c);
        fil_12.setHotSpotPosition(frs_0.g);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_02);
        fso9.setPrefSize(new fjf_2(10, 0));
        fso9.setStyle("popup");
        fil_12.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.a);
        fso9.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        String string3 = "%desc.addCommentary%";
        string3 = string3.replace("%desc.addCommentary%", fpm_0.b().c("desc.addCommentary"));
        fsM2.c(string3);
        fso9.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso9.onChildrenAdded();
        fil_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setNonBlocking(true);
        fsk_02.setScaled(true);
        fsk_02.setStyle("Commentary");
        fso8.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.i);
        fid_14.setXOffset(1);
        fsk_02.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_02);
        fir_16.setAttribute("modulationColor");
        fir_16.setField("online");
        fqp2.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_02);
        far_25.setElseValue("1,1,1,0.5");
        far_25.setValue("1,1,1");
        fir_16.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_25.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_25.onChildrenAdded();
        fir_16.onChildrenAdded();
        fqp2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso8.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_02);
        fso10.setExpandable(false);
        fso10.setPrefSize(new fjf_2(30, 25));
        fso7.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fso10.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        fru_0 fru_04 = new fru_0();
        fru_04.onCheckOut();
        fru_04.setElementMap(fyy_02);
        fru_04.setExpandable(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.contactList:addFriendToGroup(primaryContact)");
        fru_04.setOnClick(fdt_13);
        fde_2 fde_23 = new fde_2();
        fde_23.a("popup(addToGroupPopup)");
        fru_04.setOnPopupDisplay(fde_23);
        fdf_2 fdf_23 = new fdf_2();
        fdf_23.a("closePopup");
        fru_04.setOnPopupHide(fdf_23);
        fru_04.setStyle("yellow");
        fso10.addBasicElement(fru_04);
        fru_04.onAttributesInitialized();
        fir_1 fir_17 = new fir_1();
        fir_17.onCheckOut();
        fir_17.setElementMap(fyy_02);
        fir_17.setAttribute("enabled");
        fir_17.setField("online");
        fru_04.addBasicElement(fir_17);
        fir_17.onAttributesInitialized();
        fir_17.onChildrenAdded();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setAlign(frk_0.i);
        fid_15.setSize(new fjf_2(100.0f, 100.0f));
        fru_04.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fru_0 fru_05 = fru_04;
        fqd_0 fqd_03 = (fqd_0)((fvE)fru_05).getAppearance();
        fqd_03.setElementMap(fyy_02);
        fru_04.addBasicElement(fqd_03);
        fqd_03.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(2, 2, 2, 0));
        fqd_03.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqd_03.onChildrenAdded();
        String string4 = "addToGroupPopup";
        fil_1 fil_13 = new fil_1();
        fil_13.onCheckOut();
        fil_13.setElementMap(fyy_02);
        if (fyy_02 != null && string4 != null) {
            fyy_02.a(string4, fil_13);
        }
        fil_13.setAlign(frs_0.c);
        fil_13.setHotSpotPosition(frs_0.g);
        fru_04.addBasicElement(fil_13);
        fil_13.onAttributesInitialized();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_02);
        fso11.setPrefSize(new fjf_2(10, 0));
        fso11.setStyle("popup");
        fil_13.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fii_2 fii_23 = fii_2.checkOut();
        fii_23.setElementMap(fyy_02);
        fii_23.setData(frg_0.a);
        fso11.addBasicElement(fii_23);
        fii_23.onAttributesInitialized();
        fii_23.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setStyle("PopupInformation");
        String string5 = "%invitToJoinGroup%";
        string5 = string5.replace("%invitToJoinGroup%", fpm_0.b().c("invitToJoinGroup"));
        fsM4.c(string5);
        fso11.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlignment(frs_0.d);
        fsM4.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso11.onChildrenAdded();
        fil_13.onChildrenAdded();
        fru_04.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        fsk_04.setNonBlocking(true);
        fsk_04.setStyle("contactsIcon");
        fso10.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_02);
        fid_16.setAlign(frk_0.i);
        fid_16.setSize(new fjf_2(30, 30));
        fid_16.setXOffset(1);
        fid_16.setYOffset(-1);
        fsk_04.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fsk_0 fsk_05 = fsk_04;
        fqp fqp3 = (fqp)((fvE)fsk_05).getAppearance();
        fqp3.setElementMap(fyy_02);
        fsk_04.addBasicElement(fqp3);
        fqp3.onAttributesInitialized();
        fir_1 fir_18 = new fir_1();
        fir_18.onCheckOut();
        fir_18.setElementMap(fyy_02);
        fir_18.setAttribute("modulationColor");
        fir_18.setField("online");
        fqp3.addBasicElement(fir_18);
        fir_18.onAttributesInitialized();
        far_2 far_26 = new far_2();
        far_26.onCheckOut();
        far_26.setElementMap(fyy_02);
        far_26.setElseValue("1,1,1,0.5");
        far_26.setValue("1,1,1");
        fir_18.addBasicElement(far_26);
        far_26.onAttributesInitialized();
        fai_1 fai_13 = new fai_1();
        fai_13.onCheckOut();
        fai_13.setElementMap(fyy_02);
        far_26.addBasicElement(fai_13);
        fai_13.onAttributesInitialized();
        fai_13.onChildrenAdded();
        far_26.onChildrenAdded();
        fir_18.onChildrenAdded();
        fqp3.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fso10.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_02);
        fso12.setExpandable(false);
        fso12.setPrefSize(new fjf_2(30, 25));
        fso7.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fir_1 fir_19 = new fir_1();
        fir_19.onCheckOut();
        fir_19.setElementMap(fyy_02);
        fir_19.setAttribute("visible");
        fir_19.setField("canInviteToGuild");
        fso12.addBasicElement(fir_19);
        fir_19.onAttributesInitialized();
        fir_19.onChildrenAdded();
        fic_1 fic_15 = new fic_1();
        fic_15.onCheckOut();
        fso12.addBasicElement(fic_15);
        fic_15.onAttributesInitialized();
        fic_15.onChildrenAdded();
        fru_0 fru_06 = new fru_0();
        fru_06.onCheckOut();
        fru_06.setElementMap(fyy_02);
        fru_06.setExpandable(false);
        fdt_1 fdt_14 = new fdt_1();
        fdt_14.a("wakfu.contactList:addFriendToGuild(primaryContact)");
        fru_06.setOnClick(fdt_14);
        fde_2 fde_24 = new fde_2();
        fde_24.a("popup(addToGuildPopup)");
        fru_06.setOnPopupDisplay(fde_24);
        fdf_2 fdf_24 = new fdf_2();
        fdf_24.a("closePopup");
        fru_06.setOnPopupHide(fdf_24);
        fru_06.setStyle("yellow");
        fso12.addBasicElement(fru_06);
        fru_06.onAttributesInitialized();
        fir_1 fir_110 = new fir_1();
        fir_110.onCheckOut();
        fir_110.setElementMap(fyy_02);
        fir_110.setAttribute("enabled");
        fir_110.setField("canInviteToGuild");
        fru_06.addBasicElement(fir_110);
        fir_110.onAttributesInitialized();
        fir_110.onChildrenAdded();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_02);
        fid_17.setAlign(frk_0.i);
        fid_17.setSize(new fjf_2(100.0f, 100.0f));
        fru_06.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fru_0 fru_07 = fru_06;
        fqd_0 fqd_04 = (fqd_0)((fvE)fru_07).getAppearance();
        fqd_04.setElementMap(fyy_02);
        fru_06.addBasicElement(fqd_04);
        fqd_04.onAttributesInitialized();
        this.a(fqd_04);
        fqd_04.onChildrenAdded();
        this.a(fru_06);
        fru_06.onChildrenAdded();
        this.c(fso12);
        fso12.onChildrenAdded();
        this.d(fso7);
        this.e(fso7);
        fso7.onChildrenAdded();
        this.f(fso5);
        fso5.onChildrenAdded();
        fso3.onChildrenAdded();
        fso2.onChildrenAdded();
        faf_22.onChildrenAdded();
        this.a(fxs_02);
        fxs_02.onChildrenAdded();
        return fxs_02;
    }

    public fyo a(fqd_0 fqd_02) {
        fyy_0 fyy_02 = this.a.peek();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(2, 2, 2, 0));
        fqd_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        return fqm_02;
    }

    public fyo a(fru_0 fru_02) {
        fyy_0 fyy_02 = this.a.peek();
        String string = "addToGuildPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fil_12);
        }
        fil_12.setAlign(frs_0.c);
        fil_12.setHotSpotPosition(frs_0.g);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fso2.setPrefSize(new fjf_2(10, 0));
        fso2.setStyle("popup");
        fil_12.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.a);
        fso2.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        String string2 = "%inviteToJoinGuild%";
        string2 = string2.replace("%inviteToJoinGuild%", fpm_0.b().c("inviteToJoinGuild"));
        fsM2.c(string2);
        fso2.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso2.onChildrenAdded();
        fil_12.onChildrenAdded();
        return fil_12;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("guild");
        fso2.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(30, 30));
        fid_12.setXOffset(1);
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("modulationColor");
        fir_12.setField("canInviteToGuild");
        fqp2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        far_22.setElseValue("1,1,1,0.5");
        far_22.setValue("1,1,1");
        fir_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fir_12.onChildrenAdded();
        fqp2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        return fsk_02;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setPrefSize(new fjf_2(30, 25));
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.chat:addPrivatePipe(primaryContact)");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(privateChatPopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setPrefSize(new fjf_2(19, 19));
        fru_02.setStyle("yellow");
        fso3.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("enabled");
        fir_12.setField("online");
        fru_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_02);
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(2, 2, 2, 0));
        fqd_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqd_02.onChildrenAdded();
        String string = "privateChatPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fil_12);
        }
        fil_12.setAlign(frs_0.c);
        fil_12.setHotSpotPosition(frs_0.g);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setPrefSize(new fjf_2(10, 0));
        fso4.setStyle("popup");
        fil_12.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.a);
        fso4.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        String string2 = "%createPrivateChat%";
        string2 = string2.replace("%createPrivateChat%", fpm_0.b().c("createPrivateChat"));
        fsM2.c(string2);
        fso4.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso4.onChildrenAdded();
        fil_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(20, 20));
        fsk_02.setNonBlocking(true);
        fsk_02.setScaled(true);
        fsk_02.setStyle("privateChat");
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setXOffset(2);
        fsk_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("modulationColor");
        fir_13.setField("online");
        fqp2.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        far_22.setElseValue("1,1,1,0.5");
        far_22.setValue("1,1,1");
        fir_13.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fir_13.onChildrenAdded();
        fqp2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo e(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setPrefSize(new fjf_2(35, 0));
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.contactList:removeFriend(primaryContact)");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(descRemoveFromContactsPopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setStyle("smallCancel");
        fso3.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        String string = "descRemoveFromContactsPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fil_12);
        }
        fil_12.setAlign(frs_0.c);
        fil_12.setHotSpotPosition(frs_0.g);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setPrefSize(new fjf_2(10, 0));
        fso4.setStyle("popup");
        fil_12.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.a);
        fso4.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        String string2 = "%chat.removeFromContactList%";
        string2 = string2.replace("%chat.removeFromContactList%", fpm_0.b().c("chat.removeFromContactList"));
        fsM2.c(string2);
        fso4.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso4.onChildrenAdded();
        fil_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo f(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setVisible(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("visible");
        fir_12.setField("commentaryEdition");
        fso3.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fir_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fir_12.onChildrenAdded();
        String string = "customCommentary";
        fug_0 fug_02 = new fug_0();
        fug_02.onCheckOut();
        fug_02.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fug_02);
        }
        fug_02.setAutoHorizontalScrolled(true);
        fug_02.setExpandable(false);
        fug_02.a(64);
        fdm_2 fdm_22 = new fdm_2();
        fdm_22.a("wakfu.contactList:validCommentary(primaryContact,customCommentary)");
        fug_02.setOnKeyPress(fdm_22);
        fug_02.setPrefSize(new fjf_2(93, 0));
        fso3.addBasicElement(fug_02);
        fug_02.onAttributesInitialized();
        fug_0 fug_03 = fug_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fug_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fug_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(5, 0, 5, 5));
        fqh_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("text");
        fir_13.setField("commentary");
        fug_02.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fug_02.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setAlign(frs_0.d);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.contactList:validCommentary(primaryContact,customCommentary)");
        fru_02.setOnClick(fdt_12);
        fru_02.setStyle("smallValid");
        fso3.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo a(fxs_0 fxs_02) {
        fyy_0 fyy_02 = this.a.peek();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fxs_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fac_1 fac_12 = new fac_1();
        fac_12.onCheckOut();
        fac_12.setElementMap(fyy_02);
        fav_12.addBasicElement(fac_12);
        fac_12.onAttributesInitialized();
        fac_12.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fso2.setExpandable(false);
        fso2.setPrefSize(new fjf_2(163, 0));
        faf_22.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fbh_1 fbh_12 = new fbh_1();
        fbh_12.onCheckOut();
        fbh_12.setElementMap(fyy_02);
        fbh_12.setColor(new fyr_0("defaultLightColor"));
        fbh_12.setInsets(new Insets(0, 1, 0, 0));
        fqj2.addBasicElement(fbh_12);
        fbh_12.onAttributesInitialized();
        fbh_12.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso2.onChildrenAdded();
        faf_22.onChildrenAdded();
        return faf_22;
    }

    public fyo a(fut_0 fut_02) {
        fyy_0 fyy_02 = this.a.peek();
        fin_1 fin_12 = new fin_1();
        fin_12.onCheckOut();
        fin_12.setElementMap(fyy_02);
        String string = "%desc.ignoreList%";
        string = string.replace("%desc.ignoreList%", fpm_0.b().c("desc.ignoreList"));
        fin_12.setText(string);
        fut_02.addBasicElement(fin_12);
        fin_12.onAttributesInitialized();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fso2.setStyle("white");
        fin_12.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(0, 15, 10, 15));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso2.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setExpandable(false);
        fso2.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.d);
        fso4.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setExpandable(false);
        fso4.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso fso6 = fso5;
        fqj fqj3 = ((fvE)fso6).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso5.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(3, 3, 3, 0));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.d);
        fso5.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        String string2 = "customIgnoreName";
        fug_0 fug_02 = new fug_0();
        fug_02.onCheckOut();
        fug_02.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fug_02);
        }
        fug_02.setExpandable(false);
        String string3 = "%nameToIgnore%";
        string3 = string3.replace("%nameToIgnore%", fpm_0.b().c("nameToIgnore"));
        fug_02.b(string3);
        fug_02.a(64);
        fdm_2 fdm_22 = new fdm_2();
        fdm_22.a("wakfu.contactList:addIgnore()");
        fug_02.setOnKeyPress(fdm_22);
        fug_02.setPrefSize(new fjf_2(175, 0));
        fug_02.setSelectOnFocus(true);
        fso5.addBasicElement(fug_02);
        fug_02.onAttributesInitialized();
        fug_02.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.contactList:addIgnore()");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(addToIgnorePopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setStyle("add");
        fso5.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_02);
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_02);
        fqo_03.setInsets(new Insets(2, 2, 2, 2));
        fqd_02.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqd_02.onChildrenAdded();
        String string4 = "addToIgnorePopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string4 != null) {
            fyy_02.a(string4, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso7.setPrefSize(new fjf_2(10, 0));
        fso7.setStyle("popup");
        fil_12.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.e);
        fso7.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        String string5 = "%chat.addToIgnoreList%";
        string5 = string5.replace("%chat.addToIgnoreList%", fpm_0.b().c("chat.addToIgnoreList"));
        fsM2.c(string5);
        fso7.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso7.onChildrenAdded();
        fil_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        fso5.onChildrenAdded();
        fso4.onChildrenAdded();
        fuc_0 fuc_02 = new fuc_0();
        fuc_02.onCheckOut();
        fuc_02.setElementMap(fyy_02);
        fuc_02.setCellHeight(30);
        fuc_02.setExpandable(false);
        fuc_02.setMaxRows(8);
        fuc_02.setMinRows(8);
        fso2.addBasicElement(fuc_02);
        fuc_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("ignoreList/contentList");
        fiy_12.setName("contact.list");
        fuc_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fxs_0 fxs_02 = new fxs_0();
        fxs_02.onCheckOut();
        fxs_02.setElementMap(fyy_02);
        fxs_02.setCellWidth(539);
        fxs_02.setColumnId("name");
        String string6 = "%name%";
        string6 = string6.replace("%name%", fpm_0.b().c("name"));
        fxs_02.setName(string6);
        fuc_02.addBasicElement(fxs_02);
        fxs_02.onAttributesInitialized();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fxs_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        faf_22.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setAlign(frs_0.d);
        fso8.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fso fso9 = fso8;
        fqj fqj4 = ((fvE)fso9).getAppearance();
        fqj4.setElementMap(fyy_02);
        fso8.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_02);
        fqo_04.setInsets(new Insets(0, 1, 0, 0));
        fqj4.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj4.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setExpandable(false);
        fso8.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("style");
        fir_12.setField("online");
        fsk_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        far_23.setElseValue("DisconnectedStatut");
        far_23.setValue("ConnectedStatut");
        fir_12.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_23.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_23.onChildrenAdded();
        fir_12.onChildrenAdded();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(2, 2, 2, 4));
        fqp2.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqp2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_02);
        fso10.setExpandable(false);
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setAlign(frs_0.b);
        fin_26.setHorizontal(false);
        fso10.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setEnableAutoZoomShrink(true);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(280);
        fuk_02.setMinWidth(280);
        fuk_02.setStyle("white");
        fso10.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("text");
        fir_13.setField("name");
        fuk_02.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fuk_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(3, 3, 0, 0));
        fqh_03.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setEnableAutoZoomShrink(true);
        fsM4.setExpandable(false);
        fsM4.setMaxWidth(280);
        fsM4.setMinWidth(280);
        fsM4.setStyle("LightBlue");
        fso10.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("text");
        fir_14.setField("characterName");
        fsM4.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fsM fsM5 = fsM4;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fsM4.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_02);
        fqm_05.setInsets(new Insets(0, 3, 0, 0));
        fqh_04.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqh_04.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso10.onChildrenAdded();
        fso8.onChildrenAdded();
        faf_22.onChildrenAdded();
        fxs_02.onChildrenAdded();
        fxs_0 fxs_03 = new fxs_0();
        fxs_03.onCheckOut();
        fxs_03.setElementMap(fyy_02);
        fxs_03.setCellWidth(60);
        fxs_03.setColumnId("controls");
        fuc_02.addBasicElement(fxs_03);
        fxs_03.onAttributesInitialized();
        faf_2 faf_23 = new faf_2();
        faf_23.onCheckOut();
        faf_23.setElementMap(fyy_02);
        fxs_03.addBasicElement(faf_23);
        faf_23.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_02);
        faf_23.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fav_1 fav_13 = new fav_1();
        fav_13.onCheckOut();
        fav_13.setElementMap(fyy_02);
        far_24.addBasicElement(fav_13);
        fav_13.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_02);
        fav_13.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        fav_13.onChildrenAdded();
        far_24.onChildrenAdded();
        String string7 = "primaryContact";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_02);
        if (fyy_02 != null && string7 != null) {
            fyy_02.a(string7, fij_12);
        }
        faf_23.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("value");
        fij_12.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_02);
        faf_23.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_02);
        fso12.setExpandable(false);
        fso12.setPrefSize(new fjf_2(60, 0));
        fso11.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fso fso13 = fso12;
        fqj fqj5 = ((fvE)fso13).getAppearance();
        fqj5.setElementMap(fyy_02);
        fso12.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fbh_1 fbh_12 = new fbh_1();
        fbh_12.onCheckOut();
        fbh_12.setElementMap(fyy_02);
        fbh_12.setColor(new fyr_0("defaultLightColor"));
        fbh_12.setInsets(new Insets(0, 1, 0, 0));
        fqj5.addBasicElement(fbh_12);
        fbh_12.onAttributesInitialized();
        fbh_12.onChildrenAdded();
        fqj5.onChildrenAdded();
        fin_2 fin_27 = fin_2.checkOut();
        fin_27.setAlign(frs_0.e);
        fso12.addBasicElement(fin_27);
        fin_27.onAttributesInitialized();
        fin_27.onChildrenAdded();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_02);
        fso14.setExpandable(false);
        fso12.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_02);
        fir_16.setAttribute("visible");
        fso14.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_02);
        fir_16.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fab_2 fab_24 = new fab_2();
        fab_24.onCheckOut();
        fab_24.setElementMap(fyy_02);
        far_25.addBasicElement(fab_24);
        fab_24.onAttributesInitialized();
        fab_24.onChildrenAdded();
        far_25.onChildrenAdded();
        fir_16.onChildrenAdded();
        fso fso15 = fso14;
        fqj fqj6 = ((fvE)fso15).getAppearance();
        fqj6.setElementMap(fyy_02);
        fso14.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_02);
        fqm_06.setInsets(new Insets(0, 2, 0, 0));
        fqj6.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqj6.onChildrenAdded();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_02);
        fso16.setExpandable(false);
        fso16.setPrefSize(new fjf_2(35, 0));
        fso14.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        fru_0 fru_04 = new fru_0();
        fru_04.onCheckOut();
        fru_04.setElementMap(fyy_02);
        fru_04.setExpandable(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.contactList:removeIgnore(primaryContact)");
        fru_04.setOnClick(fdt_13);
        fde_2 fde_23 = new fde_2();
        fde_23.a("popup(descRemoveFromContactsPopup)");
        fru_04.setOnPopupDisplay(fde_23);
        fdf_2 fdf_23 = new fdf_2();
        fdf_23.a("closePopup");
        fru_04.setOnPopupHide(fdf_23);
        fru_04.setStyle("smallCancel");
        fso16.addBasicElement(fru_04);
        fru_04.onAttributesInitialized();
        String string8 = "descRemoveFromContactsPopup";
        fil_1 fil_13 = new fil_1();
        fil_13.onCheckOut();
        fil_13.setElementMap(fyy_02);
        if (fyy_02 != null && string8 != null) {
            fyy_02.a(string8, fil_13);
        }
        fil_13.setAlign(frs_0.c);
        fil_13.setHotSpotPosition(frs_0.g);
        fru_04.addBasicElement(fil_13);
        fil_13.onAttributesInitialized();
        fso fso17 = fso.checkOut();
        fso17.setElementMap(fyy_02);
        fso17.setPrefSize(new fjf_2(10, 0));
        fso17.setStyle("popup");
        fil_13.addBasicElement(fso17);
        fso17.onAttributesInitialized();
        fii_2 fii_23 = fii_2.checkOut();
        fii_23.setElementMap(fyy_02);
        fii_23.setData(frg_0.a);
        fso17.addBasicElement(fii_23);
        fii_23.onAttributesInitialized();
        fii_23.onChildrenAdded();
        this.g(fso17);
        fso17.onChildrenAdded();
        fil_13.onChildrenAdded();
        fru_04.onChildrenAdded();
        fso16.onChildrenAdded();
        fso14.onChildrenAdded();
        fso12.onChildrenAdded();
        fso11.onChildrenAdded();
        faf_23.onChildrenAdded();
        this.b(fxs_03);
        fxs_03.onChildrenAdded();
        fuc_02.onChildrenAdded();
        fso2.onChildrenAdded();
        fin_12.onChildrenAdded();
        return fin_12;
    }

    public fyo g(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        String string = "%chat.removeFromContactList%";
        string = string.replace("%chat.removeFromContactList%", fpm_0.b().c("chat.removeFromContactList"));
        fsM2.c(string);
        fso2.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        return fsM2;
    }

    public fyo b(fxs_0 fxs_02) {
        fyy_0 fyy_02 = this.a.peek();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fxs_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fac_1 fac_12 = new fac_1();
        fac_12.onCheckOut();
        fac_12.setElementMap(fyy_02);
        fav_12.addBasicElement(fac_12);
        fac_12.onAttributesInitialized();
        fac_12.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fso2.setExpandable(false);
        fso2.setPrefSize(new fjf_2(60, 0));
        faf_22.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fbh_1 fbh_12 = new fbh_1();
        fbh_12.onCheckOut();
        fbh_12.setElementMap(fyy_02);
        fbh_12.setColor(new fyr_0("defaultLightColor"));
        fbh_12.setInsets(new Insets(0, 1, 0, 0));
        fqj2.addBasicElement(fbh_12);
        fbh_12.onAttributesInitialized();
        fbh_12.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso2.onChildrenAdded();
        faf_22.onChildrenAdded();
        return faf_22;
    }

    public fyo h(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fup_0 fup_02 = new fup_0();
        fup_02.onCheckOut();
        fup_02.setElementMap(fyy_02);
        fup_02.setExpandable(false);
        fdi_2 fdi_22 = new fdi_2();
        fdi_22.a("wakfu.contactList:displayDisconnectedPlayers");
        fup_02.setOnSelectionChange(fdi_22);
        fup_02.setSelected(true);
        String string = "%guild.displayDisconnectedMembers%";
        string = string.replace("%guild.displayDisconnectedMembers%", fpm_0.b().c("guild.displayDisconnectedMembers"));
        fup_02.setText(string);
        fso2.addBasicElement(fup_02);
        fup_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fup_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fup_0 fup_03 = fup_02;
        fqj_0 fqj_02 = (fqj_0)((fvE)fup_03).getAppearance();
        fqj_02.setElementMap(fyy_02);
        fup_02.addBasicElement(fqj_02);
        fqj_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(20, 0, 0, 10));
        fqj_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj_02.onChildrenAdded();
        fup_02.onChildrenAdded();
        return fup_02;
    }

    public fyo a(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo b(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fru_02.setStyle("close");
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("unloadDialog");
        fru_02.setOnClick(fdt_12);
        fvk_02.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setSize(new fjf_2(-2, -2));
        fid_12.setXOffset(-18);
        fid_12.setYOffset(-12);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo c(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.j);
        fid_12.setResizeOnce(true);
        fid_12.setSize(new fjf_2(-2, -2));
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }
}

