/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cNA
 */
public class cna_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        String string = "guideList";
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fvk_02);
        }
        fvk_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvk_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("BLUEWINDOW");
        fvk_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setExpandable(false);
        fvM2.setPrefSize(new fjf_2(100.0f, 50));
        fso3.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fvM fvM3 = fvM2;
        fqj fqj2 = ((fvE)fvM3).getAppearance();
        fqj2.setElementMap(fyy_03);
        fvM2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(-4, -30, 0, -30));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqk_0 fqk_02 = new fqk_0();
        fqk_02.onCheckOut();
        fqk_02.setElementMap(fyy_03);
        fqk_02.setInsets(new Insets(0, 15, 0, 15));
        fqj2.addBasicElement(fqk_02);
        fqk_02.onAttributesInitialized();
        fqk_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_03);
        fso4.setPrefSize(new fjf_2(100.0f, 50));
        fso4.setStyle("BLUEWINDOWHEADER");
        fvM2.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(false);
        fso4.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso4.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.c);
        fid_14.setSize(new fjf_2(100.0f, 42));
        fso5.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fso5.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_03);
        fso6.setExpandable(false);
        fso5.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.h);
        fid_15.setXOffset(20);
        fso6.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fso6.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso7.setPrefSize(new fjf_2(100, 37));
        fso7.setStyle("BLUEWINDOWTITLEBACKGROUND");
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fso fso8 = fso7;
        fqj fqj3 = ((fvE)fso8).getAppearance();
        fqj3.setElementMap(fyy_03);
        fso7.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(0, 20, 0, 20));
        fqj3.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_03);
        fid_16.setAlign(frk_0.i);
        fso7.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setStyle("STYLEDBOLD16WHITE");
        String string2 = "%unlock.guide.title%";
        string2 = string2.replace("%unlock.guide.title%", fpm_0.b().c("unlock.guide.title"));
        fsM2.c(string2);
        fso7.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlign(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso7.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_03);
        fso9.setExpandable(false);
        fso5.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_03);
        fid_17.setAlign(frk_0.j);
        fso9.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fso9.onChildrenAdded();
        fso5.onChildrenAdded();
        fso4.onChildrenAdded();
        fvM2.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        fso3.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fso fso11 = fso10;
        fqj fqj4 = ((fvE)fso11).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso10.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqj4.onChildrenAdded();
        String string3 = "windowContentContainer";
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fso12);
        }
        fso10.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_03);
        fso13.setExpandable(false);
        fso13.setPrefSize(new fjf_2(265, 100.0f));
        fso12.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fso fso14 = fso13;
        fqj fqj5 = ((fvE)fso14).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso13.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 3, 0, 0));
        fqj5.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj5.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.b);
        fin_23.setHorizontal(false);
        fso13.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fuh_0 fuh_02 = new fuh_0();
        fuh_02.onCheckOut();
        fuh_02.setElementMap(fyy_03);
        fuh_02.setExpandable(false);
        String string4 = "%search%";
        string4 = string4.replace("%search%", fpm_0.b().c("search"));
        fuh_02.b(string4);
        fuh_02.a(30);
        fuh_02.setPrefSize(new fjf_2(100.0f, 30));
        fuh_02.setStyle("blueWindow");
        fuh_02.setWithClearButton(true);
        fuh_02.setWithSearchButton(true);
        fso13.addBasicElement(fuh_02);
        fuh_02.onAttributesInitialized();
        fuh_0 fuh_03 = fuh_02;
        fqG fqG2 = (fqG)((fvE)fuh_03).getAppearance();
        fqG2.setElementMap(fyy_03);
        fqG2.setAlign(frs_0.d);
        fuh_02.addBasicElement(fqG2);
        fqG2.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(8, 0, 6, 0));
        fqG2.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(0, 5, 0, 5));
        fqG2.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqG2.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("listFilter");
        fiy_12.setName("guideListFilter");
        fuh_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fuh_02.onChildrenAdded();
        fue_0 fue_02 = new fue_0();
        fue_02.onCheckOut();
        fue_02.setElementMap(fyy_03);
        fue_02.setExpandable(false);
        fue_02.setHorizontalScrollBarBehaviour(fra_0.c);
        fue_02.setInnerWidgetAlign(frs_0.b);
        fue_02.setPrefSize(new fjf_2(258, 459));
        fue_02.setStyle("GuideListContainer");
        fue_02.setVerticalScrollBarBehaviour(fra_0.b);
        fso13.addBasicElement(fue_02);
        fue_02.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.a);
        fue_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fue_0 fue_03 = fue_02;
        fqj fqj6 = ((fvE)fue_03).getAppearance();
        fqj6.setElementMap(fyy_03);
        fue_02.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_03);
        fqo_04.setInsets(new Insets(4, 4, 4, 4));
        fqj6.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj6.onChildrenAdded();
        fus_0 fus_02 = new fus_0();
        fus_02.onCheckOut();
        fus_02.setElementMap(fyy_03);
        fus_02.setExpandable(false);
        fus_02.setHorizontal(false);
        fus_02.setInnerExpandable(false);
        fue_02.addBasicElement(fus_02);
        fus_02.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("content");
        fiy_13.setName("guideCategories");
        fus_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_03);
        fus_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_03);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_03);
        fso15.setPrefSize(new fjf_2(248, 0));
        faf_22.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fso fso16 = fso15;
        fqj fqj7 = ((fvE)fso16).getAppearance();
        fqj7.setElementMap(fyy_03);
        fso15.addBasicElement(fqj7);
        fqj7.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(0, 0, 0, 0));
        fqj7.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqj7.onChildrenAdded();
        fic_1 fic_15 = new fic_1();
        fic_15.onCheckOut();
        fic_15.setAdaptToContentSize(true);
        fso15.addBasicElement(fic_15);
        fic_15.onAttributesInitialized();
        fic_15.onChildrenAdded();
        String string5 = "guideCategoryView";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_03);
        if (fyy_03 != null && string5 != null) {
            fyy_03.a(string5, fij_12);
        }
        fso15.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_03);
        fir_12.setAttribute("value");
        fij_12.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fij_12.onChildrenAdded();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_03);
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(100.0f, 35));
        fsQ2.setEnableFilterCache(true);
        fsQ2.setHorizontal(false);
        fsQ2.setIdealSizeMaxColumns(1);
        fsQ2.setIdealSizeMinColumns(1);
        fso15.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fid_1 fid_18 = new fid_1();
        fid_18.onCheckOut();
        fid_18.setElementMap(fyy_03);
        fid_18.setAlignment(frk_0.o);
        fid_18.setSize(new fjf_2(100.0f, 100.0f));
        fsQ2.addBasicElement(fid_18);
        fid_18.onAttributesInitialized();
        fid_18.onChildrenAdded();
        fsQ fsQ3 = fsQ2;
        fqr fqr2 = (fqr)((fvE)fsQ3).getAppearance();
        fqr2.setElementMap(fyy_03);
        fsQ2.addBasicElement(fqr2);
        fqr2.onAttributesInitialized();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_03);
        fqm_06.setInsets(new Insets(44, 0, 0, 0));
        fqr2.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqr2.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("listFilter");
        fiy_14.setName("guideListFilter");
        fsQ2.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_03);
        fir_13.setAttribute("content");
        fir_13.setField("guides");
        fsQ2.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_03);
        fir_14.setAttribute("visible");
        fir_14.setField("collapsed");
        fsQ2.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        fir_14.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_03);
        far_23.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_23.onChildrenAdded();
        fir_14.onChildrenAdded();
        faf_2 faf_23 = new faf_2();
        faf_23.onCheckOut();
        faf_23.setElementMap(fyy_03);
        fsQ2.addBasicElement(faf_23);
        faf_23.onAttributesInitialized();
        fso fso17 = fso.checkOut();
        fso17.setElementMap(fyy_03);
        faf_23.addBasicElement(fso17);
        fso17.onAttributesInitialized();
        fso fso18 = fso17;
        fqj fqj8 = ((fvE)fso18).getAppearance();
        fqj8.setElementMap(fyy_03);
        fso17.addBasicElement(fqj8);
        fqj8.onAttributesInitialized();
        fqm_0 fqm_07 = fqm_0.checkOut();
        fqm_07.setElementMap(fyy_03);
        fqm_07.setInsets(new Insets(0, 15, 0, 2));
        fqj8.addBasicElement(fqm_07);
        fqm_07.onAttributesInitialized();
        fqm_07.onChildrenAdded();
        fqj8.onChildrenAdded();
        String string6 = "guideView";
        fij_1 fij_13 = new fij_1();
        fij_13.onCheckOut();
        fij_13.setElementMap(fyy_03);
        if (fyy_03 != null && string6 != null) {
            fyy_03.a(string6, fij_13);
        }
        fso17.addBasicElement(fij_13);
        fij_13.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_03);
        fir_15.setAttribute("value");
        fij_13.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fij_13.onChildrenAdded();
        fso fso19 = fso.checkOut();
        fso19.setElementMap(fyy_03);
        fso17.addBasicElement(fso19);
        fso19.onAttributesInitialized();
        fso fso20 = fso19;
        fqj fqj9 = ((fvE)fso20).getAppearance();
        fqj9.setElementMap(fyy_03);
        fso19.addBasicElement(fqj9);
        fqj9.onAttributesInitialized();
        fqo_0 fqo_05 = new fqo_0();
        fqo_05.onCheckOut();
        fqo_05.setElementMap(fyy_03);
        fqo_05.setInsets(new Insets(1, 1, 1, 1));
        fqj9.addBasicElement(fqo_05);
        fqo_05.onAttributesInitialized();
        fqo_05.onChildrenAdded();
        fqj9.onChildrenAdded();
        fic_1 fic_16 = new fic_1();
        fic_16.onCheckOut();
        fso19.addBasicElement(fic_16);
        fic_16.onAttributesInitialized();
        fic_16.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_03);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.guideList:selectGuide(guideView)");
        fru_02.setOnClick(fdt_12);
        fso19.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        this.a(fru_02);
        this.b(fru_02);
        fru_02.onChildrenAdded();
        this.a(fso19);
        this.b(fso19);
        fso19.onChildrenAdded();
        fso17.onChildrenAdded();
        faf_23.onChildrenAdded();
        fsQ2.onChildrenAdded();
        this.c(fso15);
        fso15.onChildrenAdded();
        faf_22.onChildrenAdded();
        fus_02.onChildrenAdded();
        fue_02.onChildrenAdded();
        fso13.onChildrenAdded();
        this.d(fso12);
        this.e(fso12);
        fso12.onChildrenAdded();
        fso10.onChildrenAdded();
        fso3.onChildrenAdded();
        this.a(fvk_02);
        this.b(fvk_02);
        this.c(fvk_02);
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fru_0 fru_02) {
        fyy_0 fyy_02 = this.a.peek();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("style");
        fir_12.setField("selected");
        fru_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        far_22.setElseValue("GuideElement");
        far_22.setValue("GuideElementSelected");
        fir_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fir_12.onChildrenAdded();
        return fir_12;
    }

    public fyo b(fru_0 fru_02) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setEnableAutoZoomShrink(true);
        fsM2.setMaxWidth(100);
        fsM2.setMinWidth(1);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("defaultBold14White");
        fso2.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("modulationColor");
        fir_12.setField("selected");
        fqh_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        far_22.setElseValue("defaultLightColor");
        far_22.setValue("importantTextColor");
        fir_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fir_12.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(90.0f, 40));
        fsM2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("text");
        fir_13.setField("title");
        fsM2.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fsM2.onChildrenAdded();
        return fsM2;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setNonBlocking(true);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setSize(new fjf_2(14, 14));
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(8, 8));
        fsk_02.setExpandable(false);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("newNotificationBig");
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("visible");
        fir_12.setField("unread");
        fsk_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setPrefSize(new fjf_2(100.0f, 40));
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlignment(frk_0.c);
        fid_12.setSize(new fjf_2(100.0f, 45));
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(false);
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 0, 3, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.guideList:clickCategory(guideCategoryView)");
        fru_02.setOnClick(fdt_12);
        fru_02.setStyle("GuideCategory");
        fso3.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fru_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fru_02.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setExpandable(false);
        fso5.setNonBlocking(true);
        fso5.setPrefSize(new fjf_2(40, 40));
        fso5.setStyle("BLUEWINDOWTITLEBACKGROUND");
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.h);
        fid_14.setSize(new fjf_2(40, 40));
        fid_14.setXOffset(2);
        fid_14.setYOffset(-1);
        fso5.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(30, 30));
        fso5.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("texture");
        fir_12.setField("icon");
        fqv2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso5.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        fsk_03.setDisplaySize(new fjf_2(24, 24));
        fsk_03.setNonBlocking(true);
        fsk_03.setStyle("BlueWindowArrowRight");
        fso3.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setAlign(frk_0.h);
        fid_15.setSize(new fjf_2(30, 24));
        fid_15.setXOffset(40);
        fsk_03.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("style");
        fir_13.setField("collapsed");
        fsk_03.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        far_22.setElseValue("BlueWindowArrowDown");
        far_22.setValue("BlueWindowArrowRight");
        fir_13.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fir_13.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("STYLEDBOLD16WHITE");
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_02);
        fid_16.setAlign(frk_0.h);
        fid_16.setSize(new fjf_2(200, 100.0f));
        fid_16.setXOffset(40);
        fsM2.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("text");
        fir_14.setField("title");
        fsM2.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso6.setExpandable(false);
        fso6.setNonBlocking(true);
        fso3.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_02);
        fid_17.setAlign(frk_0.e);
        fid_17.setSize(new fjf_2(14, 14));
        fso6.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        fsk_04.setDisplaySize(new fjf_2(8, 8));
        fsk_04.setExpandable(false);
        fsk_04.setNonBlocking(true);
        fsk_04.setStyle("newNotificationBig");
        fso6.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("visible");
        fir_15.setField("unread");
        fsk_04.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fso6.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setPrefSize(new fjf_2(2, 100.0f));
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 2, 0, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setPrefSize(new fjf_2(2, 40));
        fso5.setStyle("BlueWindowVerticalSeparator");
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.h);
        fso5.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fso5.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo e(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.e);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        String string = "guideView";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fij_12);
        }
        fso3.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("value");
        fiy_12.setLocal(true);
        fiy_12.setName("guideViewPopup");
        fij_12.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso4;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso4.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(5, 5, 5, 5));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso4.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso6.setStyle("BLUEWINDOWCONTENT");
        fso4.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(642, 517));
        fso6.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fso6.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(588, 340));
        fsk_02.setExpandable(false);
        fsk_02.setKeepAspectRatio(true);
        fso6.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.c);
        fid_13.setSize(new fjf_2(594, 346));
        fsk_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("texture");
        fiy_13.setField("illustration");
        fiy_13.setLocal(true);
        fiy_13.setName("guideViewPopup");
        fqv2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso6.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.c);
        fid_14.setSize(new fjf_2(594, 346));
        fso7.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso8.setNonBlocking(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.guidePopup:previousPage(guideView)");
        fso8.setOnClick(fdt_12);
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.a("wakfu.guidePopup:setLeftArrowVisible(guideView,leftGuideArrow)");
        fso8.setOnMouseEnter(fdy_12);
        fdz_1 fdz_12 = new fdz_1();
        fdz_12.a("wakfu.guidePopup:setLeftArrowInvisible(guideView,leftGuideArrow)");
        fso8.setOnMouseExit(fdz_12);
        fso8.setPrefSize(new fjf_2(250, 100.0f));
        fso7.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj3 = ((fvE)fso9).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso8.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(4, 4, 4, 4));
        fqj3.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        String string2 = "leftGuideArrow";
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fso10);
        }
        fso10.setExpandable(false);
        fso10.setNonBlocking(true);
        fso10.setPrefSize(new fjf_2(36, 100.0f));
        fso10.setVisible(false);
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso10.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_02);
        fso11.setStyle("LeftShadowBorder");
        fso10.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fso11.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        fsk_03.setDisplaySize(new fjf_2(36, 36));
        fsk_03.setExpandable(false);
        fsk_03.setStyle("LeftShadowBorderArrow");
        fso10.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fsk_03.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_02);
        fso12.setStyle("LeftShadowBorder");
        fso10.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fso12.onChildrenAdded();
        fso10.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_02);
        fso8.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fso8.onChildrenAdded();
        fur_0 fur_03 = new fur_0();
        fur_03.onCheckOut();
        fur_03.setElementMap(fyy_02);
        fso7.addBasicElement(fur_03);
        fur_03.onAttributesInitialized();
        fur_03.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_02);
        fso13.setNonBlocking(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.guidePopup:nextPage(guideView)");
        fso13.setOnClick(fdt_13);
        fdy_1 fdy_13 = new fdy_1();
        fdy_13.a("wakfu.guidePopup:setRightArrowVisible(guideView,rightGuideArrow)");
        fso13.setOnMouseEnter(fdy_13);
        fdz_1 fdz_13 = new fdz_1();
        fdz_13.a("wakfu.guidePopup:setRightArrowInvisible(guideView,rightGuideArrow)");
        fso13.setOnMouseExit(fdz_13);
        fso13.setPrefSize(new fjf_2(250, 100.0f));
        fso7.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fso fso14 = fso13;
        fqj fqj4 = ((fvE)fso14).getAppearance();
        fqj4.setElementMap(fyy_02);
        fso13.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_02);
        fqo_03.setInsets(new Insets(4, 4, 4, 4));
        fqj4.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fur_0 fur_04 = new fur_0();
        fur_04.onCheckOut();
        fur_04.setElementMap(fyy_02);
        fso13.addBasicElement(fur_04);
        fur_04.onAttributesInitialized();
        fur_04.onChildrenAdded();
        String string3 = "rightGuideArrow";
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_02);
        if (fyy_02 != null && string3 != null) {
            fyy_02.a(string3, fso15);
        }
        fso15.setExpandable(false);
        fso15.setNonBlocking(true);
        fso15.setPrefSize(new fjf_2(36, 100.0f));
        fso15.setVisible(false);
        fso13.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setHorizontal(false);
        fso15.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_02);
        fso16.setStyle("RightShadowBorder");
        fso15.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        fso16.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        fsk_04.setDisplaySize(new fjf_2(36, 36));
        fsk_04.setExpandable(false);
        fsk_04.setStyle("RightShadowBorderArrow");
        fso15.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fsk_04.onChildrenAdded();
        fso fso17 = fso.checkOut();
        fso17.setElementMap(fyy_02);
        fso17.setStyle("RightShadowBorder");
        fso15.addBasicElement(fso17);
        fso17.onAttributesInitialized();
        fso17.onChildrenAdded();
        fso15.onChildrenAdded();
        fso13.onChildrenAdded();
        fso7.onChildrenAdded();
        fso fso18 = fso.checkOut();
        fso18.setElementMap(fyy_02);
        fso18.setStyle("BLUEWINDOWIMAGEFRAME");
        fso6.addBasicElement(fso18);
        fso18.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setAlign(frk_0.c);
        fid_15.setSize(new fjf_2(594, 346));
        fso18.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fso18.onChildrenAdded();
        fso fso19 = fso.checkOut();
        fso19.setElementMap(fyy_02);
        fso19.setStyle("BLUEWINDOWTEXTFRAME");
        fso6.addBasicElement(fso19);
        fso19.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_02);
        fid_16.setAlign(frk_0.o);
        fid_16.setSize(new fjf_2(598, 120));
        fso19.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fso fso20 = fso19;
        fqj fqj5 = ((fvE)fso20).getAppearance();
        fqj5.setElementMap(fyy_02);
        fso19.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_02);
        fqo_04.setInsets(new Insets(10, 10, 10, 10));
        fqj5.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj5.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setMaxWidth(400);
        fuk_02.setMinWidth(1);
        fuk_02.setMultiline(true);
        fuk_02.setStyle("DefaultBold12White");
        fso19.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.a);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("text");
        fiy_14.setField("description");
        fiy_14.setLocal(true);
        fiy_14.setName("guideViewPopup");
        fuk_02.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso19.onChildrenAdded();
        fso6.onChildrenAdded();
        fso4.onChildrenAdded();
        fso fso21 = fso.checkOut();
        fso21.setElementMap(fyy_02);
        fso21.setExpandable(false);
        fso21.setPrefSize(new fjf_2(100.0f, 28));
        fso3.addBasicElement(fso21);
        fso21.onAttributesInitialized();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setAlign(frs_0.b);
        fso21.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fso fso22 = fso21;
        fqj fqj6 = ((fvE)fso22).getAppearance();
        fqj6.setElementMap(fyy_02);
        fso21.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqo_0 fqo_05 = new fqo_0();
        fqo_05.onCheckOut();
        fqo_05.setElementMap(fyy_02);
        fqo_05.setInsets(new Insets(0, 0, 4, 0));
        fqj6.addBasicElement(fqo_05);
        fqo_05.onAttributesInitialized();
        fqo_05.onChildrenAdded();
        fqj6.onChildrenAdded();
        fur_0 fur_05 = new fur_0();
        fur_05.onCheckOut();
        fur_05.setElementMap(fyy_02);
        fso21.addBasicElement(fur_05);
        fur_05.onAttributesInitialized();
        fur_05.onChildrenAdded();
        fso fso23 = fso.checkOut();
        fso23.setElementMap(fyy_02);
        fso23.setExpandable(false);
        fso23.setPrefSize(new fjf_2(200, 31));
        fso21.addBasicElement(fso23);
        fso23.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("visible");
        fiy_15.setField("hasManyPages");
        fiy_15.setLocal(true);
        fiy_15.setName("guideViewPopup");
        fso23.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fso fso24 = fso23;
        fqj fqj7 = ((fvE)fso24).getAppearance();
        fqj7.setElementMap(fyy_02);
        fso23.addBasicElement(fqj7);
        fqj7.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(-3, 0, 0, 0));
        fqj7.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj7.onChildrenAdded();
        fso fso25 = fso.checkOut();
        fso25.setElementMap(fyy_02);
        fso23.addBasicElement(fso25);
        fso25.onAttributesInitialized();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_02);
        fiy_16.setAttribute("visible");
        fiy_16.setField("hasPreviousPage");
        fiy_16.setLocal(true);
        fiy_16.setName("guideViewPopup");
        fso25.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fso25.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fdt_1 fdt_14 = new fdt_1();
        fdt_14.a("wakfu.guidePopup:previousPage(guideView)");
        fru_02.setOnClick(fdt_14);
        fru_02.setStyle("BlueWindowLeftArrowButton");
        String string4 = "%desc.mru.previous%";
        string4 = string4.replace("%desc.mru.previous%", fpm_0.b().c("desc.mru.previous"));
        fru_02.setText(string4);
        fso25.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_02);
        fiy_17.setAttribute("enabled");
        fiy_17.setField("hasPreviousPage");
        fiy_17.setLocal(true);
        fiy_17.setName("guideViewPopup");
        fru_02.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_02);
        fid_17.setAlign(frk_0.i);
        fid_17.setSize(new fjf_2(150, 31));
        fru_02.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fru_02.onChildrenAdded();
        fso25.onChildrenAdded();
        fso23.onChildrenAdded();
        fur_0 fur_06 = new fur_0();
        fur_06.onCheckOut();
        fur_06.setElementMap(fyy_02);
        fso21.addBasicElement(fur_06);
        fur_06.onAttributesInitialized();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_02);
        fiy_18.setAttribute("visible");
        fiy_18.setField("hasManyPages");
        fiy_18.setLocal(true);
        fiy_18.setName("guideViewPopup");
        fur_06.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        fiy_18.onChildrenAdded();
        fur_06.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setStyle("defaultBold14White");
        fso21.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlign(frs_0.e);
        fsM2.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 20, 0, 20));
        fqh_03.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_02);
        fiy_19.setAttribute("visible");
        fiy_19.setField("hasManyPages");
        fiy_19.setLocal(true);
        fiy_19.setName("guideViewPopup");
        fsM2.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        fiy_19.onChildrenAdded();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_02);
        fiy_110.setAttribute("text");
        fiy_110.setField("pageNumber");
        fiy_110.setLocal(true);
        fiy_110.setName("guideViewPopup");
        fsM2.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        fiy_110.onChildrenAdded();
        fsM2.onChildrenAdded();
        fur_0 fur_07 = new fur_0();
        fur_07.onCheckOut();
        fur_07.setElementMap(fyy_02);
        fso21.addBasicElement(fur_07);
        fur_07.onAttributesInitialized();
        fiy_1 fiy_111 = fiy_1.checkOut();
        fiy_111.setElementMap(fyy_02);
        fiy_111.setAttribute("visible");
        fiy_111.setField("hasManyPages");
        fiy_111.setLocal(true);
        fiy_111.setName("guideViewPopup");
        fur_07.addBasicElement(fiy_111);
        fiy_111.onAttributesInitialized();
        fiy_111.onChildrenAdded();
        fur_07.onChildrenAdded();
        this.f(fso21);
        this.g(fso21);
        fso21.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo f(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setPrefSize(new fjf_2(200, 31));
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(-3, 0, 0, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("hasNextPage");
        fiy_12.setLocal(true);
        fiy_12.setName("guideViewPopup");
        fso5.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso5.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.guidePopup:nextPage(guideView)");
        fru_02.setOnClick(fdt_12);
        fru_02.setStyle("BlueWindowRightArrowButton");
        String string = "%desc.mru.next%";
        string = string.replace("%desc.mru.next%", fpm_0.b().c("desc.mru.next"));
        fru_02.setText(string);
        fso5.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("enabled");
        fiy_13.setField("hasNextPage");
        fiy_13.setLocal(true);
        fiy_13.setName("guideViewPopup");
        fru_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(150, 31));
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        fso5.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo g(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_02);
        fso2.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        return fur_02;
    }

    public fyo a(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo b(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fru_02.setStyle("BLUEWINDOWCLOSE");
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("unloadDialog");
        fru_02.setOnClick(fdt_12);
        fvk_02.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setXOffset(-7);
        fid_12.setYOffset(-7);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo c(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setInitValue(true);
        fid_12.setSize(new fjf_2(930, 614));
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }
}

