/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cNB
 */
public class cnb_1
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        String string = "guidePopup";
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fvk_02);
        }
        fvk_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvk_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("BLUEWINDOW");
        fvk_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setExpandable(false);
        fvM2.setPrefSize(new fjf_2(100.0f, 50));
        fvM2.setEnabled(false);
        fso3.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fvM fvM3 = fvM2;
        fqj fqj2 = ((fvE)fvM3).getAppearance();
        fqj2.setElementMap(fyy_03);
        fvM2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(-4, -30, 0, -30));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqk_0 fqk_02 = new fqk_0();
        fqk_02.onCheckOut();
        fqk_02.setElementMap(fyy_03);
        fqk_02.setInsets(new Insets(0, 15, 0, 15));
        fqj2.addBasicElement(fqk_02);
        fqk_02.onAttributesInitialized();
        fqk_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_03);
        fso4.setPrefSize(new fjf_2(100.0f, 50));
        fso4.setStyle("BLUEWINDOWHEADER");
        fvM2.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(false);
        fso4.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso4.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.c);
        fid_14.setSize(new fjf_2(100.0f, 42));
        fso5.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fso5.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_03);
        fso6.setExpandable(false);
        fso6.setPrefSize(new fjf_2(40, 40));
        fso6.setStyle("BLUEWINDOWTITLEBACKGROUND");
        fso5.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.h);
        fid_15.setXOffset(20);
        fso6.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fso fso7 = fso6;
        fqj fqj3 = ((fvE)fso7).getAppearance();
        fqj3.setElementMap(fyy_03);
        fso6.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(2, 2, 2, 2));
        fqj3.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setDisplaySize(new fjf_2(26, 26));
        fso6.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("texture");
        fiy_12.setField("icon");
        fiy_12.setLocal(true);
        fiy_12.setName("guideViewPopup");
        fqv2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso6.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso8.setExpandable(false);
        fso8.setPrefSize(new fjf_2(100, 37));
        fso8.setStyle("BLUEWINDOWTITLEBACKGROUND");
        fso5.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj4 = ((fvE)fso9).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso8.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(0, 20, 0, 20));
        fqj4.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_03);
        fid_16.setAlign(frk_0.i);
        fso8.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setNonBlocking(false);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(adminGuidePopup)");
        fsM2.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fsM2.setOnPopupHide(fdf_22);
        fsM2.setStyle("STYLEDBOLD16WHITE");
        fso8.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlign(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("text");
        fiy_13.setField("title");
        fiy_13.setLocal(true);
        fiy_13.setName("guideViewPopup");
        fsM2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        String string2 = "adminGuidePopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fil_12);
        }
        fil_12.setAlign(frs_0.h);
        fil_12.setHotSpotPosition(frs_0.b);
        fsM2.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        fso10.setPrefSize(new fjf_2(10, 0));
        fso10.setStyle("popup");
        fil_12.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("visible");
        fiy_14.setName("isAdmin");
        fso10.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setMaxWidth(200);
        fuk_02.setMinWidth(1);
        fuk_02.setMultiline(true);
        fuk_02.setStyle("11");
        fso10.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("text");
        fiy_15.setField("adminGuideInfo");
        fiy_15.setLocal(true);
        fiy_15.setName("guideViewPopup");
        fuk_02.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fqh_03.setAlign(frs_0.d);
        fuk_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_03);
        fqg_02.setColor(new fyr_0("defaultLightColor"));
        fqh_03.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso10.onChildrenAdded();
        fil_12.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso8.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso11.setExpandable(false);
        fso5.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_03);
        fid_17.setAlign(frk_0.j);
        fso11.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fso11.onChildrenAdded();
        fso5.onChildrenAdded();
        fso4.onChildrenAdded();
        fvM2.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        fso3.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fso fso13 = fso12;
        fqj fqj5 = ((fvE)fso13).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso12.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqj5.onChildrenAdded();
        String string3 = "windowContentContainer";
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fso14);
        }
        fso12.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_03);
        fso14.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.e);
        fin_23.setHorizontal(false);
        fso15.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        String string4 = "guideView";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_03);
        if (fyy_03 != null && string4 != null) {
            fyy_03.a(string4, fij_12);
        }
        fso15.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("value");
        fiy_16.setLocal(true);
        fiy_16.setName("guideViewPopup");
        fij_12.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_03);
        fso15.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        fso fso17 = fso16;
        fqj fqj6 = ((fvE)fso17).getAppearance();
        fqj6.setElementMap(fyy_03);
        fso16.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(5, 5, 5, 5));
        fqj6.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj6.onChildrenAdded();
        fic_1 fic_15 = new fic_1();
        fic_15.onCheckOut();
        fso16.addBasicElement(fic_15);
        fic_15.onAttributesInitialized();
        fic_15.onChildrenAdded();
        fso fso18 = fso.checkOut();
        fso18.setElementMap(fyy_03);
        fso18.setStyle("BLUEWINDOWCONTENT");
        fso16.addBasicElement(fso18);
        fso18.onAttributesInitialized();
        fid_1 fid_18 = new fid_1();
        fid_18.onCheckOut();
        fid_18.setElementMap(fyy_03);
        fid_18.setAlign(frk_0.i);
        fid_18.setSize(new fjf_2(642, 517));
        fso18.addBasicElement(fid_18);
        fid_18.onAttributesInitialized();
        fid_18.onChildrenAdded();
        fic_1 fic_16 = new fic_1();
        fic_16.onCheckOut();
        fso18.addBasicElement(fic_16);
        fic_16.onAttributesInitialized();
        fic_16.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_03);
        fsk_03.setDisplaySize(new fjf_2(588, 340));
        fsk_03.setExpandable(false);
        fsk_03.setKeepAspectRatio(true);
        fso18.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_19 = new fid_1();
        fid_19.onCheckOut();
        fid_19.setElementMap(fyy_03);
        fid_19.setAlign(frk_0.c);
        fid_19.setSize(new fjf_2(594, 346));
        fsk_03.addBasicElement(fid_19);
        fid_19.onAttributesInitialized();
        fid_19.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_03);
        fsk_03.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_03);
        fiy_17.setAttribute("texture");
        fiy_17.setField("illustration");
        fiy_17.setLocal(true);
        fiy_17.setName("guideViewPopup");
        fqv3.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        fqv3.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fso fso19 = fso.checkOut();
        fso19.setElementMap(fyy_03);
        fso18.addBasicElement(fso19);
        fso19.onAttributesInitialized();
        fid_1 fid_110 = new fid_1();
        fid_110.onCheckOut();
        fid_110.setElementMap(fyy_03);
        fid_110.setAlign(frk_0.c);
        fid_110.setSize(new fjf_2(594, 346));
        fso19.addBasicElement(fid_110);
        fid_110.onAttributesInitialized();
        fid_110.onChildrenAdded();
        fso fso20 = fso.checkOut();
        fso20.setElementMap(fyy_03);
        fso20.setNonBlocking(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.guidePopup:previousPage(guideView)");
        fso20.setOnClick(fdt_12);
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.a("wakfu.guidePopup:setLeftArrowVisible(guideView,leftGuideArrow)");
        fso20.setOnMouseEnter(fdy_12);
        fdz_1 fdz_12 = new fdz_1();
        fdz_12.a("wakfu.guidePopup:setLeftArrowInvisible(guideView,leftGuideArrow)");
        fso20.setOnMouseExit(fdz_12);
        fso20.setPrefSize(new fjf_2(250, 100.0f));
        fso19.addBasicElement(fso20);
        fso20.onAttributesInitialized();
        fso fso21 = fso20;
        fqj fqj7 = ((fvE)fso21).getAppearance();
        fqj7.setElementMap(fyy_03);
        fso20.addBasicElement(fqj7);
        fqj7.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_03);
        fqo_04.setInsets(new Insets(4, 4, 4, 4));
        fqj7.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj7.onChildrenAdded();
        String string5 = "leftGuideArrow";
        fso fso22 = fso.checkOut();
        fso22.setElementMap(fyy_03);
        if (fyy_03 != null && string5 != null) {
            fyy_03.a(string5, fso22);
        }
        fso22.setExpandable(false);
        fso22.setNonBlocking(true);
        fso22.setPrefSize(new fjf_2(36, 100.0f));
        fso22.setVisible(false);
        fso20.addBasicElement(fso22);
        fso22.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setHorizontal(false);
        fso22.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fso fso23 = fso.checkOut();
        fso23.setElementMap(fyy_03);
        fso23.setStyle("LeftShadowBorder");
        fso22.addBasicElement(fso23);
        fso23.onAttributesInitialized();
        fso23.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_03);
        fsk_04.setDisplaySize(new fjf_2(36, 36));
        fsk_04.setExpandable(false);
        fsk_04.setStyle("LeftShadowBorderArrow");
        fso22.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fsk_04.onChildrenAdded();
        fso fso24 = fso.checkOut();
        fso24.setElementMap(fyy_03);
        fso24.setStyle("LeftShadowBorder");
        fso22.addBasicElement(fso24);
        fso24.onAttributesInitialized();
        fso24.onChildrenAdded();
        fso22.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_03);
        fso20.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fso20.onChildrenAdded();
        fur_0 fur_03 = new fur_0();
        fur_03.onCheckOut();
        fur_03.setElementMap(fyy_03);
        fso19.addBasicElement(fur_03);
        fur_03.onAttributesInitialized();
        fur_03.onChildrenAdded();
        fso fso25 = fso.checkOut();
        fso25.setElementMap(fyy_03);
        fso25.setNonBlocking(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.guidePopup:nextPage(guideView)");
        fso25.setOnClick(fdt_13);
        fdy_1 fdy_13 = new fdy_1();
        fdy_13.a("wakfu.guidePopup:setRightArrowVisible(guideView,rightGuideArrow)");
        fso25.setOnMouseEnter(fdy_13);
        fdz_1 fdz_13 = new fdz_1();
        fdz_13.a("wakfu.guidePopup:setRightArrowInvisible(guideView,rightGuideArrow)");
        fso25.setOnMouseExit(fdz_13);
        fso25.setPrefSize(new fjf_2(250, 100.0f));
        fso19.addBasicElement(fso25);
        fso25.onAttributesInitialized();
        this.a(fso25);
        this.b(fso25);
        this.c(fso25);
        fso25.onChildrenAdded();
        fso19.onChildrenAdded();
        this.d(fso18);
        this.e(fso18);
        fso18.onChildrenAdded();
        fso16.onChildrenAdded();
        this.f(fso15);
        fso15.onChildrenAdded();
        fso14.onChildrenAdded();
        fso12.onChildrenAdded();
        fso3.onChildrenAdded();
        this.a(fvk_02);
        this.b(fvk_02);
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(4, 4, 4, 4));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        return fqj2;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_02);
        fso2.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        return fur_02;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        String string = "rightGuideArrow";
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fso3);
        }
        fso3.setExpandable(false);
        fso3.setNonBlocking(true);
        fso3.setPrefSize(new fjf_2(36, 100.0f));
        fso3.setVisible(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setStyle("RightShadowBorder");
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso4.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(36, 36));
        fsk_02.setExpandable(false);
        fsk_02.setStyle("RightShadowBorderArrow");
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_02.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setStyle("RightShadowBorder");
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso5.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setStyle("BLUEWINDOWIMAGEFRAME");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.c);
        fid_12.setSize(new fjf_2(594, 346));
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo e(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setStyle("BLUEWINDOWTEXTFRAME");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.o);
        fid_12.setSize(new fjf_2(598, 120));
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(10, 10, 10, 10));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setMaxWidth(400);
        fuk_02.setMinWidth(1);
        fuk_02.setMultiline(true);
        fuk_02.setStyle("DefaultBold12White");
        fso3.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.a);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("description");
        fiy_12.setLocal(true);
        fiy_12.setName("guideViewPopup");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo f(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setPrefSize(new fjf_2(100.0f, 28));
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(0, 0, 4, 0));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_02);
        fso3.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setExpandable(false);
        fso5.setPrefSize(new fjf_2(200, 31));
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("hasManyPages");
        fiy_12.setLocal(true);
        fiy_12.setName("guideViewPopup");
        fso5.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fso fso6 = fso5;
        fqj fqj3 = ((fvE)fso6).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso5.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(-3, 0, 0, 0));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("visible");
        fiy_13.setField("hasPreviousPage");
        fiy_13.setLocal(true);
        fiy_13.setName("guideViewPopup");
        fso7.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso7.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.guidePopup:previousPage(guideView)");
        fru_02.setOnClick(fdt_12);
        fru_02.setStyle("BlueWindowLeftArrowButton");
        String string = "%desc.mru.previous%";
        string = string.replace("%desc.mru.previous%", fpm_0.b().c("desc.mru.previous"));
        fru_02.setText(string);
        fso7.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("enabled");
        fiy_14.setField("hasPreviousPage");
        fiy_14.setLocal(true);
        fiy_14.setName("guideViewPopup");
        fru_02.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(150, 31));
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        fur_0 fur_03 = new fur_0();
        fur_03.onCheckOut();
        fur_03.setElementMap(fyy_02);
        fso3.addBasicElement(fur_03);
        fur_03.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("visible");
        fiy_15.setField("hasManyPages");
        fiy_15.setLocal(true);
        fiy_15.setName("guideViewPopup");
        fur_03.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fur_03.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setStyle("defaultBold14White");
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 20, 0, 20));
        fqh_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_02);
        fiy_16.setAttribute("visible");
        fiy_16.setField("hasManyPages");
        fiy_16.setLocal(true);
        fiy_16.setName("guideViewPopup");
        fsM2.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_02);
        fiy_17.setAttribute("text");
        fiy_17.setField("pageNumber");
        fiy_17.setLocal(true);
        fiy_17.setName("guideViewPopup");
        fsM2.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        fsM2.onChildrenAdded();
        fur_0 fur_04 = new fur_0();
        fur_04.onCheckOut();
        fur_04.setElementMap(fyy_02);
        fso3.addBasicElement(fur_04);
        fur_04.onAttributesInitialized();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_02);
        fiy_18.setAttribute("visible");
        fiy_18.setField("hasManyPages");
        fiy_18.setLocal(true);
        fiy_18.setName("guideViewPopup");
        fur_04.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        fiy_18.onChildrenAdded();
        fur_04.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso8.setExpandable(false);
        fso8.setPrefSize(new fjf_2(200, 31));
        fso3.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj4 = ((fvE)fso9).getAppearance();
        fqj4.setElementMap(fyy_02);
        fso8.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(-3, 0, 0, 0));
        fqj4.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqj4.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_02);
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_02);
        fiy_19.setAttribute("visible");
        fiy_19.setField("hasNextPage");
        fiy_19.setLocal(true);
        fiy_19.setName("guideViewPopup");
        fso10.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        fiy_19.onChildrenAdded();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fso10.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_02);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.guidePopup:nextPage(guideView)");
        fru_03.setOnClick(fdt_13);
        fru_03.setStyle("BlueWindowRightArrowButton");
        String string2 = "%desc.mru.next%";
        string2 = string2.replace("%desc.mru.next%", fpm_0.b().c("desc.mru.next"));
        fru_03.setText(string2);
        fso10.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_02);
        fiy_110.setAttribute("enabled");
        fiy_110.setField("hasNextPage");
        fiy_110.setLocal(true);
        fiy_110.setName("guideViewPopup");
        fru_03.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        fiy_110.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(150, 31));
        fru_03.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fru_03.onChildrenAdded();
        fso10.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_02);
        fso8.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fiy_1 fiy_111 = fiy_1.checkOut();
        fiy_111.setElementMap(fyy_02);
        fiy_111.setAttribute("visible");
        fiy_111.setField("hasNextPage");
        fiy_111.setLocal(true);
        fiy_111.setName("guideViewPopup");
        fso11.addBasicElement(fiy_111);
        fiy_111.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_111.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        far_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_111.onChildrenAdded();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fso11.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        fru_0 fru_04 = new fru_0();
        fru_04.onCheckOut();
        fru_04.setElementMap(fyy_02);
        fdt_1 fdt_14 = new fdt_1();
        fdt_14.a("wakfu.guidePopup:close");
        fru_04.setOnClick(fdt_14);
        fru_04.setStyle("BlueWindowNoArrowButton");
        String string3 = "%close%";
        string3 = string3.replace("%close%", fpm_0.b().c("close"));
        fru_04.setText(string3);
        fso11.addBasicElement(fru_04);
        fru_04.onAttributesInitialized();
        fiy_1 fiy_112 = fiy_1.checkOut();
        fiy_112.setElementMap(fyy_02);
        fiy_112.setAttribute("enabled");
        fiy_112.setLocal(true);
        fiy_112.setName("guidePopupIsClosable");
        fru_04.addBasicElement(fiy_112);
        fiy_112.onAttributesInitialized();
        fiy_112.onChildrenAdded();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(150, 31));
        fru_04.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fru_04.onChildrenAdded();
        fso11.onChildrenAdded();
        fso8.onChildrenAdded();
        fur_0 fur_05 = new fur_0();
        fur_05.onCheckOut();
        fur_05.setElementMap(fyy_02);
        fso3.addBasicElement(fur_05);
        fur_05.onAttributesInitialized();
        fur_05.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo a(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo b(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setInitValue(true);
        fid_12.setSize(new fjf_2(664, 612));
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }
}

