/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cNg
 */
public class cng_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        fvk_02.setPack(true);
        fvk_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvk_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("windowNew");
        fvk_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(10, 5, 12, 5));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setExpandable(false);
        fso3.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fvM fvM3 = fvM2;
        fqj fqj3 = ((fvE)fvM3).getAppearance();
        fqj3.setElementMap(fyy_03);
        fvM2.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 10, 0, 10));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setStyle("titleBar");
        fvM2.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso fso6 = fso5;
        fqj fqj4 = ((fvE)fso6).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso5.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(3, 20, 3, 20));
        fqj4.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.e);
        fso7.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("StyledBold16White");
        String string = "%eventsCalendar.display.title%";
        string = string.replace("%eventsCalendar.display.title%", fpm_0.b().c("eventsCalendar.display.title"));
        fsM2.c(string);
        fso7.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlign(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        fvM2.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso3.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj5 = ((fvE)fso9).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso8.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 12, 0, 12));
        fqj5.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj5.onChildrenAdded();
        String string2 = "windowContentContainer";
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fso10);
        }
        fso10.setPrefSize(new fjf_2(450, 0));
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setHorizontal(false);
        fin_24.setVgap((short)3);
        fso10.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso11.setExpandable(false);
        fso10.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setHorizontal(false);
        fso11.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_03);
        fsM4.setExpandable(false);
        fsM4.setStyle("bold");
        String string3 = "%eventsCalendar.eventTitle%";
        string3 = string3.replace("%eventsCalendar.eventTitle%", fpm_0.b().c("eventsCalendar.eventTitle"));
        fsM4.c(string3);
        fso11.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM4.onChildrenAdded();
        String string4 = "title";
        fug_0 fug_02 = new fug_0();
        fug_02.onCheckOut();
        fug_02.setElementMap(fyy_03);
        if (fyy_03 != null && string4 != null) {
            fyy_03.a(string4, fug_02);
        }
        fug_02.a(50);
        fug_02.setSelectable(true);
        fso11.addBasicElement(fug_02);
        fug_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("text");
        fiy_12.setField("title");
        fiy_12.setName("calendar.event.editable");
        fug_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("editable");
        fiy_13.setName("calendar.event.editable.isOwner");
        fug_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fug_02.onChildrenAdded();
        fso11.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        fso12.setExpandable(false);
        fso10.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setHorizontal(false);
        fso12.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        fsM fsM5 = new fsM();
        fsM5.onCheckOut();
        fsM5.setElementMap(fyy_03);
        fsM5.setExpandable(false);
        fsM5.setStyle("bold");
        String string5 = "%description%";
        string5 = string5.replace("%description%", fpm_0.b().c("description"));
        fsM5.c(string5);
        fso12.addBasicElement(fsM5);
        fsM5.onAttributesInitialized();
        fsM5.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_03);
        fso13.setStyle("textEditor");
        fso12.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fue_0 fue_02 = new fue_0();
        fue_02.onCheckOut();
        fue_02.setElementMap(fyy_03);
        fue_02.setHorizontalScrollBarBehaviour(fra_0.c);
        fue_02.setPrefSize(new fjf_2(180, 55));
        fue_02.setVerticalScrollBarBehaviour(fra_0.b);
        fso13.addBasicElement(fue_02);
        fue_02.onAttributesInitialized();
        String string6 = "description";
        fug_0 fug_03 = new fug_0();
        fug_03.onCheckOut();
        fug_03.setElementMap(fyy_03);
        if (fyy_03 != null && string6 != null) {
            fyy_03.a(string6, fug_03);
        }
        fug_03.setEnableShrinking(false);
        fug_03.setExpandable(false);
        fug_03.setMultiline(true);
        fug_03.setStyle("withoutBorder");
        fue_02.addBasicElement(fug_03);
        fug_03.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("text");
        fiy_14.setField("description");
        fiy_14.setName("calendar.event.editable");
        fug_03.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("editable");
        fiy_15.setName("calendar.event.editable.isOwner");
        fug_03.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("maxChars");
        fiy_16.setName("calendar.event.desc.maxChars");
        fug_03.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fug_03.onChildrenAdded();
        fue_02.onChildrenAdded();
        fso13.onChildrenAdded();
        fso12.onChildrenAdded();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_03);
        fso10.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        fin_2 fin_27 = fin_2.checkOut();
        fin_27.setAlign(frs_0.d);
        fso14.addBasicElement(fin_27);
        fin_27.onAttributesInitialized();
        fin_27.onChildrenAdded();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_03);
        fsM6.setExpandable(false);
        fsM6.setStyle("bold");
        String string7 = "%eventsCalendar.startDate%";
        string7 = string7.replace("%eventsCalendar.startDate%", fpm_0.b().c("eventsCalendar.startDate"));
        fsM6.c(string7);
        fso14.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_03);
        fip_23.setAlign(frs_0.e);
        fsM6.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fsM fsM7 = fsM6;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM7).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fsM6.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(0, 0, 0, 10));
        fqh_03.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fsM6.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setExpandable(false);
        fso14.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fip_2 fip_24 = new fip_2();
        fip_24.onCheckOut();
        fip_24.setElementMap(fyy_03);
        fip_24.setAlign(frs_0.e);
        fuk_02.addBasicElement(fip_24);
        fip_24.onAttributesInitialized();
        fip_24.onChildrenAdded();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_03);
        fiy_17.setAttribute("text");
        fiy_17.setField("startDateDesc");
        fiy_17.setName("calendar.event.editable");
        fuk_02.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_03);
        fso15.setExpandable(false);
        fso14.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_03);
        fiy_18.setAttribute("visible");
        fiy_18.setName("calendar.event.editable.isOwner");
        fso15.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        fiy_18.onChildrenAdded();
        fso fso16 = fso15;
        fqj fqj6 = ((fvE)fso16).getAppearance();
        fqj6.setElementMap(fyy_03);
        fso15.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(0, 3, 0, 0));
        fqj6.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqj6.onChildrenAdded();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso15.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        String string8 = "start";
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_03);
        if (fyy_03 != null && string8 != null) {
            fyy_03.a(string8, fru_02);
        }
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.eventsCalendar:selectStartDate");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(descSelectStartDatePopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setStyle("flat");
        fso15.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        String string9 = "descSelectStartDatePopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_03);
        if (fyy_03 != null && string9 != null) {
            fyy_03.a(string9, fil_12);
        }
        fil_12.setAlign(frs_0.f);
        fil_12.setHotSpotPosition(frs_0.d);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso17 = fso.checkOut();
        fso17.setElementMap(fyy_03);
        fso17.setPrefSize(new fjf_2(10, 0));
        fso17.setStyle("popup");
        fil_12.addBasicElement(fso17);
        fso17.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_03);
        fii_22.setData(frg_0.a);
        fso17.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM8 = new fsM();
        fsM8.onCheckOut();
        fsM8.setElementMap(fyy_03);
        fsM8.setStyle("PopupInformation");
        String string10 = "%eventsCalendar.selectStartDate%";
        string10 = string10.replace("%eventsCalendar.selectStartDate%", fpm_0.b().c("eventsCalendar.selectStartDate"));
        fsM8.c(string10);
        fso17.addBasicElement(fsM8);
        fsM8.onAttributesInitialized();
        fsM fsM9 = fsM8;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM9).getAppearance();
        fqh_04.setElementMap(fyy_03);
        fqh_04.setAlignment(frs_0.d);
        fsM8.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fsM8.onChildrenAdded();
        fso17.onChildrenAdded();
        fil_12.onChildrenAdded();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setSize(new fjf_2(100.0f, 100.0f));
        fru_02.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fru_02.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("calendarIcon");
        fso15.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.i);
        fid_15.setSize(new fjf_2(-2, -2));
        fsk_02.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_03);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_03);
        fqm_06.setInsets(new Insets(5, 5, 5, 5));
        fqp2.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqp2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso15.onChildrenAdded();
        fso14.onChildrenAdded();
        fso fso18 = fso.checkOut();
        fso18.setElementMap(fyy_03);
        fso10.addBasicElement(fso18);
        fso18.onAttributesInitialized();
        fin_2 fin_28 = fin_2.checkOut();
        fin_28.setAlign(frs_0.d);
        fso18.addBasicElement(fin_28);
        fin_28.onAttributesInitialized();
        fin_28.onChildrenAdded();
        fsM fsM10 = new fsM();
        fsM10.onCheckOut();
        fsM10.setElementMap(fyy_03);
        fsM10.setExpandable(false);
        fsM10.setStyle("bold");
        String string11 = "%eventsCalendar.endDate%";
        string11 = string11.replace("%eventsCalendar.endDate%", fpm_0.b().c("eventsCalendar.endDate"));
        fsM10.c(string11);
        fso18.addBasicElement(fsM10);
        fsM10.onAttributesInitialized();
        fip_2 fip_25 = new fip_2();
        fip_25.onCheckOut();
        fip_25.setElementMap(fyy_03);
        fip_25.setAlign(frs_0.e);
        fsM10.addBasicElement(fip_25);
        fip_25.onAttributesInitialized();
        fip_25.onChildrenAdded();
        fsM fsM11 = fsM10;
        fqh_0 fqh_05 = (fqh_0)((fvE)fsM11).getAppearance();
        fqh_05.setElementMap(fyy_03);
        fsM10.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        this.a(fqh_05);
        fqh_05.onChildrenAdded();
        fsM10.onChildrenAdded();
        this.a(fso18);
        this.b(fso18);
        fso18.onChildrenAdded();
        this.c(fso10);
        this.d(fso10);
        this.e(fso10);
        this.i(fso10);
        this.j(fso10);
        fso10.onChildrenAdded();
        fso8.onChildrenAdded();
        fso3.onChildrenAdded();
        this.a(fvk_02);
        this.b(fvk_02);
        this.c(fvk_02);
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fqh_0 fqh_02) {
        fyy_0 fyy_02 = this.a.peek();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 0, 0, 10));
        fqh_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        return fqm_02;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fso2.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.e);
        fuk_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("endDateDesc");
        fiy_12.setName("calendar.event.editable");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fuk_02.onChildrenAdded();
        return fuk_02;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setName("calendar.event.editable.isOwner");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 3, 0, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        String string = "end";
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fru_02);
        }
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.eventsCalendar:selectEndDate");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(descSelectStartEndPopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setStyle("flat");
        fso3.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        String string2 = "descSelectStartEndPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fil_12);
        }
        fil_12.setAlign(frs_0.f);
        fil_12.setHotSpotPosition(frs_0.d);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setPrefSize(new fjf_2(10, 0));
        fso5.setStyle("popup");
        fil_12.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.a);
        fso5.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        String string3 = "%eventsCalendar.selectEndDate%";
        string3 = string3.replace("%eventsCalendar.selectEndDate%", fpm_0.b().c("eventsCalendar.selectEndDate"));
        fsM2.c(string3);
        fso5.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso5.onChildrenAdded();
        fil_12.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("calendarIcon");
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(-2, -2));
        fsk_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(5, 5, 5, 5));
        fqp2.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqp2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setPrefSize(new fjf_2(50, 1));
        fso3.setStyle("lineSeparator2");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(5, 20, 5, 20));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        String string = "eventType";
        fim_1 fim_12 = new fim_1();
        fim_12.onCheckOut();
        fim_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, (fyb_0)fim_12);
        }
        fso3.addBasicElement(fim_12);
        fim_12.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("value");
        fiy_12.setField("selectedType/value");
        fiy_12.setName("calendar.event.editable");
        fim_12.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fim_12.onChildrenAdded();
        ftI ftI2 = new ftI();
        ftI2.onCheckOut();
        ftI2.setElementMap(fyy_02);
        ftI2.setEnabled(false);
        ftI2.setGroupId("eventType");
        fdi_2 fdi_22 = new fdi_2();
        fdi_22.a("wakfu.eventsCalendar:setEventType");
        ftI2.setOnSelectionChange(fdi_22);
        String string2 = "%calendar.event.type.1%";
        string2 = string2.replace("%calendar.event.type.1%", fpm_0.b().c("calendar.event.type.1"));
        ftI2.setText(string2);
        ftI2.setValue("1");
        fso3.addBasicElement(ftI2);
        ftI2.onAttributesInitialized();
        ftI2.onChildrenAdded();
        ftI ftI3 = new ftI();
        ftI3.onCheckOut();
        ftI3.setElementMap(fyy_02);
        ftI3.setEnabled(false);
        ftI3.setGroupId("eventType");
        fdi_2 fdi_23 = new fdi_2();
        fdi_23.a("wakfu.eventsCalendar:setEventType");
        ftI3.setOnSelectionChange(fdi_23);
        String string3 = "%calendar.event.type.2%";
        string3 = string3.replace("%calendar.event.type.2%", fpm_0.b().c("calendar.event.type.2"));
        ftI3.setText(string3);
        ftI3.setValue("2");
        fso3.addBasicElement(ftI3);
        ftI3.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("visible");
        fiy_13.setField("hasGuild");
        fiy_13.setName("localPlayer");
        ftI3.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        ftI3.onChildrenAdded();
        ftI ftI4 = new ftI();
        ftI4.onCheckOut();
        ftI4.setElementMap(fyy_02);
        ftI4.setEnabled(false);
        ftI4.setGroupId("eventType");
        fdi_2 fdi_24 = new fdi_2();
        fdi_24.a("wakfu.eventsCalendar:setEventType");
        ftI4.setOnSelectionChange(fdi_24);
        String string4 = "%calendar.event.type.3%";
        string4 = string4.replace("%calendar.event.type.3%", fpm_0.b().c("calendar.event.type.3"));
        ftI4.setText(string4);
        ftI4.setValue("3");
        fso3.addBasicElement(ftI4);
        ftI4.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("visible");
        fiy_14.setName("isAdmin");
        ftI4.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        ftI4.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo e(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fup_0 fup_02 = new fup_0();
        fup_02.onCheckOut();
        fup_02.setElementMap(fyy_02);
        fdi_2 fdi_22 = new fdi_2();
        fdi_22.a("wakfu.eventsCalendar:setParticipantsLimited");
        fup_02.setOnSelectionChange(fdi_22);
        String string = "%eventsCalendar.limitParticipants%";
        string = string.replace("%eventsCalendar.limitParticipants%", fpm_0.b().c("eventsCalendar.limitParticipants"));
        fup_02.setText(string);
        fso3.addBasicElement(fup_02);
        fup_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("selected");
        fiy_12.setField("areParticipantsLimited");
        fiy_12.setName("calendar.event.editable");
        fup_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("enabled");
        fiy_13.setField("canEditParticipantsLimit");
        fiy_13.setName("calendar.event.editable");
        fup_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fup_02.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso4;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso4.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(2, 0, 0, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso4.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("visible");
        fiy_14.setField("areParticipantsLimited");
        fiy_14.setName("calendar.event.editable");
        fso4.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        String string2 = "numRegisteredContainer";
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fso6);
        }
        fso6.setExpandable(false);
        fso4.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.d);
        fso6.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setStyle("bold");
        String string3 = "%eventsCalendar.eventMaxRegistered%";
        string3 = string3.replace("%eventsCalendar.eventMaxRegistered%", fpm_0.b().c("eventsCalendar.eventMaxRegistered"));
        fsM2.c(string3);
        fso6.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 0, 0, 10));
        fqh_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        String string4 = "maxRegistrations";
        fug_0 fug_02 = new fug_0();
        fug_02.onCheckOut();
        fug_02.setElementMap(fyy_02);
        if (fyy_02 != null && string4 != null) {
            fyy_02.a(string4, fug_02);
        }
        fug_02.setExpandable(false);
        fug_02.a(2);
        fdo_1 fdo_12 = new fdo_1();
        fdo_12.a("wakfu.eventsCalendar:changeMaxRegistrations");
        fug_02.setOnKeyType(fdo_12);
        fug_02.setPrefSize(new fjf_2(15, 0));
        fug_02.setRestrict("[0-9]");
        fug_02.setSelectOnFocus(true);
        fso6.addBasicElement(fug_02);
        fug_02.onAttributesInitialized();
        fug_0 fug_03 = fug_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fug_03).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlign(frs_0.f);
        fug_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.d);
        fug_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("text");
        fiy_15.setField("maxRegistrations");
        fiy_15.setName("calendar.event.editable");
        fug_02.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_02);
        fiy_16.setAttribute("editable");
        fiy_16.setName("calendar.event.editable.isOwner");
        fug_02.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fug_02.onChildrenAdded();
        fso6.onChildrenAdded();
        String string5 = "numParticipantsContainer";
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        if (fyy_02 != null && string5 != null) {
            fyy_02.a(string5, fso7);
        }
        fso7.setExpandable(false);
        fso4.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setAlign(frs_0.d);
        fso7.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setExpandable(false);
        fsM4.setStyle("bold");
        String string6 = "%eventsCalendar.eventMaxParticipants%";
        string6 = string6.replace("%eventsCalendar.eventMaxParticipants%", fpm_0.b().c("eventsCalendar.eventMaxParticipants"));
        fsM4.c(string6);
        fso7.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fsM4.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 0, 0, 10));
        fqh_04.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_04.onChildrenAdded();
        fsM4.onChildrenAdded();
        String string7 = "maxParticipants";
        fug_0 fug_04 = new fug_0();
        fug_04.onCheckOut();
        fug_04.setElementMap(fyy_02);
        if (fyy_02 != null && string7 != null) {
            fyy_02.a(string7, fug_04);
        }
        fug_04.setExpandable(false);
        fug_04.a(2);
        fdo_1 fdo_13 = new fdo_1();
        fdo_13.a("wakfu.eventsCalendar:changeMaxParticipants");
        fug_04.setOnKeyType(fdo_13);
        fug_04.setPrefSize(new fjf_2(15, 0));
        fug_04.setRestrict("[0-9]");
        fug_04.setSelectOnFocus(true);
        fso7.addBasicElement(fug_04);
        fug_04.onAttributesInitialized();
        fug_0 fug_05 = fug_04;
        fqh_0 fqh_05 = (fqh_0)((fvE)fug_05).getAppearance();
        fqh_05.setElementMap(fyy_02);
        fqh_05.setAlign(frs_0.f);
        fug_04.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqh_05.onChildrenAdded();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_02);
        fip_23.setAlign(frs_0.d);
        fug_04.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_02);
        fiy_17.setAttribute("text");
        fiy_17.setField("maxParticipants");
        fiy_17.setName("calendar.event.editable");
        fug_04.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_02);
        fiy_18.setAttribute("editable");
        fiy_18.setName("calendar.event.editable.isOwner");
        fug_04.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        fiy_18.onChildrenAdded();
        fug_04.onChildrenAdded();
        fso7.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso4.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj3 = ((fvE)fso9).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso8.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_02);
        fqm_05.setInsets(new Insets(3, 0, 0, 0));
        fqj3.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_02);
        fso10.setPrefSize(new fjf_2(200, 0));
        fso10.setStyle("caracs");
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setAlign(frs_0.b);
        fin_26.setHorizontal(false);
        fso10.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_02);
        fso11.setExpandable(false);
        fso10.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_02);
        fsM6.setExpandable(false);
        fsM6.setStyle("11Bold");
        String string8 = "%eventsCalendar.edit.registeredList%%colon%";
        string8 = string8.replace("%eventsCalendar.edit.registeredList%", fpm_0.b().c("eventsCalendar.edit.registeredList"));
        string8 = string8.replace("%colon%", fpm_0.b().c("colon"));
        fsM6.c(string8);
        fso11.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fsM fsM7 = fsM6;
        fqh_0 fqh_06 = (fqh_0)((fvE)fsM7).getAppearance();
        fqh_06.setElementMap(fyy_02);
        fqh_06.setAlign(frs_0.e);
        fsM6.addBasicElement(fqh_06);
        fqh_06.onAttributesInitialized();
        fqh_06.onChildrenAdded();
        fsM6.onChildrenAdded();
        fsM fsM8 = new fsM();
        fsM8.onCheckOut();
        fsM8.setElementMap(fyy_02);
        fsM8.setExpandable(false);
        fsM8.setStyle("11Bold");
        fso11.addBasicElement(fsM8);
        fsM8.onAttributesInitialized();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_02);
        fiy_19.setAttribute("text");
        fiy_19.setField("numRegistrationsDesc");
        fiy_19.setName("calendar.event.editable");
        fsM8.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        fiy_19.onChildrenAdded();
        fsM8.onChildrenAdded();
        fso11.onChildrenAdded();
        String string9 = "registered";
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        if (fyy_02 != null && string9 != null) {
            fyy_02.a(string9, fsQ2);
        }
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(180, 20));
        fsQ2.setExpandable(false);
        fsQ2.setIdealSizeMaxColumns(1);
        fsQ2.setIdealSizeMaxRows(10);
        fsQ2.setIdealSizeMinColumns(1);
        fsQ2.setIdealSizeMinRows(0);
        fso10.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fsQ fsQ3 = fsQ2;
        fqr fqr2 = (fqr)((fvE)fsQ3).getAppearance();
        fqr2.setElementMap(fyy_02);
        fsQ2.addBasicElement(fqr2);
        fqr2.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_02);
        fqg_02.setColor(new azf_2(0.0f, 0.0f, 0.0f, 0.3f));
        fqr2.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqr2.onChildrenAdded();
        fip_2 fip_24 = new fip_2();
        fip_24.onCheckOut();
        fip_24.setElementMap(fyy_02);
        fip_24.setAlign(frs_0.e);
        fsQ2.addBasicElement(fip_24);
        fip_24.onAttributesInitialized();
        fip_24.onChildrenAdded();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_02);
        fiy_110.setAttribute("content");
        fiy_110.setField("registeredList");
        fiy_110.setName("calendar.event.editable");
        fsQ2.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        fiy_110.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        faw_2 faw_22 = new faw_2();
        faw_22.onCheckOut();
        faw_22.setElementMap(fyy_02);
        faw_22.setKey("selected");
        far_22.addBasicElement(faw_22);
        faw_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        faw_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_02);
        faf_22.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fsM fsM9 = new fsM();
        fsM9.onCheckOut();
        fsM9.setElementMap(fyy_02);
        fsM9.setStyle("bold");
        fso12.addBasicElement(fsM9);
        fsM9.onAttributesInitialized();
        fsM fsM10 = fsM9;
        fqh_0 fqh_07 = (fqh_0)((fvE)fsM10).getAppearance();
        fqh_07.setElementMap(fyy_02);
        fqh_07.setAlign(frs_0.e);
        fsM9.addBasicElement(fqh_07);
        fqh_07.onAttributesInitialized();
        fqh_07.onChildrenAdded();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("text");
        fir_12.setField("name");
        fsM9.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fsM9.onChildrenAdded();
        String string10 = "participantId";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_02);
        if (fyy_02 != null && string10 != null) {
            fyy_02.a(string10, fij_12);
        }
        fso12.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("value");
        fir_13.setField("id");
        fij_12.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso12.onChildrenAdded();
        faf_22.onChildrenAdded();
        faf_2 faf_23 = new faf_2();
        faf_23.onCheckOut();
        faf_23.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_23);
        faf_23.onAttributesInitialized();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_02);
        faf_23.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fsM fsM11 = new fsM();
        fsM11.onCheckOut();
        fsM11.setElementMap(fyy_02);
        fsM11.setStyle("");
        fso13.addBasicElement(fsM11);
        fsM11.onAttributesInitialized();
        fsM fsM12 = fsM11;
        fqh_0 fqh_08 = (fqh_0)((fvE)fsM12).getAppearance();
        fqh_08.setElementMap(fyy_02);
        fqh_08.setAlign(frs_0.e);
        fsM11.addBasicElement(fqh_08);
        fqh_08.onAttributesInitialized();
        fqh_08.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("text");
        fir_14.setField("name");
        fsM11.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fsM11.onChildrenAdded();
        String string11 = "participantId";
        fij_1 fij_13 = new fij_1();
        fij_13.onCheckOut();
        fij_13.setElementMap(fyy_02);
        if (fyy_02 != null && string11 != null) {
            fyy_02.a(string11, fij_13);
        }
        fso13.addBasicElement(fij_13);
        fij_13.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("value");
        fir_15.setField("id");
        fij_13.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fij_13.onChildrenAdded();
        fso13.onChildrenAdded();
        faf_23.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso10.onChildrenAdded();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_02);
        fso8.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        fiy_1 fiy_111 = fiy_1.checkOut();
        fiy_111.setElementMap(fyy_02);
        fiy_111.setAttribute("visible");
        fiy_111.setName("calendar.event.editable.isOwner");
        fso14.addBasicElement(fiy_111);
        fiy_111.onAttributesInitialized();
        fiy_111.onChildrenAdded();
        fin_2 fin_27 = fin_2.checkOut();
        fin_27.setAlign(frs_0.e);
        fin_27.setHorizontal(false);
        fso14.addBasicElement(fin_27);
        fin_27.onAttributesInitialized();
        fin_27.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.eventsCalendar:unvalidate(validated)");
        fru_02.setOnClick(fdt_12);
        fru_02.setStyle("whiteLeftArrow");
        fru_02.setText("{");
        fso14.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_02.onChildrenAdded();
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_02);
        fru_03.setExpandable(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.eventsCalendar:validate(registered)");
        fru_03.setOnClick(fdt_13);
        fru_03.setStyle("whiteRightArrow");
        fru_03.setText("}");
        fso14.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        fru_03.onChildrenAdded();
        fso14.onChildrenAdded();
        this.f(fso8);
        fso8.onChildrenAdded();
        this.g(fso4);
        this.h(fso4);
        fso4.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo f(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setPrefSize(new fjf_2(200, 0));
        fso3.setStyle("caracs");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setExpandable(false);
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setStyle("11Bold");
        String string = "%eventsCalendar.edit.validatedList%%colon%";
        string = string.replace("%eventsCalendar.edit.validatedList%", fpm_0.b().c("eventsCalendar.edit.validatedList"));
        string = string.replace("%colon%", fpm_0.b().c("colon"));
        fsM2.c(string);
        fso4.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setExpandable(false);
        fsM4.setStyle("11Bold");
        fso4.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("numParticipantsDesc");
        fiy_12.setName("calendar.event.editable");
        fsM4.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso4.onChildrenAdded();
        String string2 = "validated";
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fsQ2);
        }
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(180, 20));
        fsQ2.setExpandable(false);
        fsQ2.setIdealSizeMaxColumns(1);
        fsQ2.setIdealSizeMaxRows(10);
        fsQ2.setIdealSizeMinColumns(1);
        fsQ2.setIdealSizeMinRows(1);
        fso3.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fsQ fsQ3 = fsQ2;
        fqr fqr2 = (fqr)((fvE)fsQ3).getAppearance();
        fqr2.setElementMap(fyy_02);
        fsQ2.addBasicElement(fqr2);
        fqr2.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_02);
        fqg_02.setColor(new azf_2(0.0f, 0.0f, 0.0f, 0.3f));
        fqr2.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqr2.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.e);
        fsQ2.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("content");
        fiy_13.setField("validatedList");
        fiy_13.setName("calendar.event.editable");
        fsQ2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        faf_22.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fsM fsM5 = new fsM();
        fsM5.onCheckOut();
        fsM5.setElementMap(fyy_02);
        fsM5.setStyle("");
        fso5.addBasicElement(fsM5);
        fsM5.onAttributesInitialized();
        fsM fsM6 = fsM5;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM6).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlign(frs_0.e);
        fsM5.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("text");
        fir_12.setField("name");
        fsM5.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fsM5.onChildrenAdded();
        String string3 = "participantId";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_02);
        if (fyy_02 != null && string3 != null) {
            fyy_02.a(string3, fij_12);
        }
        fso5.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("value");
        fir_13.setField("id");
        fij_12.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso5.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo g(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setName("calendar.event.editable.isOwner");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(3, 0, 0, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        String string = "inviteToEvent";
        fug_0 fug_02 = new fug_0();
        fug_02.onCheckOut();
        fug_02.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fug_02);
        }
        fso3.addBasicElement(fug_02);
        fug_02.onAttributesInitialized();
        fug_02.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.eventsCalendar:inviteToEvent(inviteToEvent)");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(descInviteToEventPopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setStyle("add");
        fso3.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        String string2 = "descInviteToEventPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fil_12);
        }
        fil_12.setAlign(frs_0.f);
        fil_12.setHotSpotPosition(frs_0.d);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setPrefSize(new fjf_2(10, 0));
        fso5.setStyle("popup");
        fil_12.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.a);
        fso5.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        String string3 = "%eventsCalendar.edit.inviteToEvent%";
        string3 = string3.replace("%eventsCalendar.edit.inviteToEvent%", fpm_0.b().c("eventsCalendar.edit.inviteToEvent"));
        fsM2.c(string3);
        fso5.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso5.onChildrenAdded();
        fil_12.onChildrenAdded();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(0, 3, 0, 3));
        fru_02.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fru_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo h(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.eventsCalendar:inviteAllParticipants");
        fru_02.setOnClick(fdt_12);
        fru_02.setStyle("flat");
        String string = "%eventsCalendar.edit.inviteAllParticipants%";
        string = string.replace("%eventsCalendar.edit.inviteAllParticipants%", fpm_0.b().c("eventsCalendar.edit.inviteAllParticipants"));
        fru_02.setText(string);
        fso2.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_02);
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(3, 0, 0, 0));
        fqd_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(3, 10, 3, 10));
        fqd_02.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqd_02.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo i(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setPrefSize(new fjf_2(50, 1));
        fso3.setStyle("lineSeparator2");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(5, 20, 5, 20));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo j(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso4.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.f);
        fso4.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.eventsCalendar:registerEvent");
        fru_02.setOnClick(fdt_12);
        fru_02.setStyle("flat");
        String string = "%eventsCalendar.edit.register%";
        string = string.replace("%eventsCalendar.edit.register%", fpm_0.b().c("eventsCalendar.edit.register"));
        fru_02.setText(string);
        fso4.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("areParticipantsLimited");
        fiy_12.setName("calendar.event.editable");
        fru_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("enabled");
        fiy_13.setField("isRegistered");
        fiy_13.setName("calendar.event.editable");
        fru_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_13.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fan_2 fan_22 = new fan_2();
        fan_22.onCheckOut();
        fan_22.setElementMap(fyy_02);
        far_22.addBasicElement(fan_22);
        fan_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        fan_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        fau_1 fau_13 = new fau_1();
        fau_13.onCheckOut();
        fau_13.setElementMap(fyy_02);
        fan_22.addBasicElement(fau_13);
        fau_13.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("comparedValue");
        fiy_14.setField("isValidated");
        fiy_14.setName("calendar.event.editable");
        fau_13.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fau_13.onChildrenAdded();
        fan_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_02);
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(3, 0, 0, 0));
        fqd_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(3, 10, 3, 10));
        fqd_02.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqd_02.onChildrenAdded();
        fru_02.onChildrenAdded();
        fru_0 fru_04 = new fru_0();
        fru_04.onCheckOut();
        fru_04.setElementMap(fyy_02);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.eventsCalendar:editEvent(title,description,maxParticipants,maxRegistrations)");
        fru_04.setOnClick(fdt_13);
        fru_04.setStyle("flat");
        String string2 = "%eventsCalendar.edit.action%";
        string2 = string2.replace("%eventsCalendar.edit.action%", fpm_0.b().c("eventsCalendar.edit.action"));
        fru_04.setText(string2);
        fso4.addBasicElement(fru_04);
        fru_04.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("visible");
        fiy_15.setName("calendar.event.editable.isOwner");
        fru_04.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fru_0 fru_05 = fru_04;
        fqd_0 fqd_03 = (fqd_0)((fvE)fru_05).getAppearance();
        fqd_03.setElementMap(fyy_02);
        fru_04.addBasicElement(fqd_03);
        fqd_03.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(3, 0, 0, 0));
        fqd_03.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_02);
        fqo_03.setInsets(new Insets(3, 10, 3, 10));
        fqd_03.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqd_03.onChildrenAdded();
        fru_04.onChildrenAdded();
        fso4.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_02);
        fip_23.setAlign(frs_0.d);
        fso5.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fru_0 fru_06 = new fru_0();
        fru_06.onCheckOut();
        fru_06.setElementMap(fyy_02);
        fdt_1 fdt_14 = new fdt_1();
        fdt_14.a("wakfu.eventsCalendar:unregisterEvent");
        fru_06.setOnClick(fdt_14);
        fru_06.setStyle("flat");
        String string3 = "%eventsCalendar.edit.unregister%";
        string3 = string3.replace("%eventsCalendar.edit.unregister%", fpm_0.b().c("eventsCalendar.edit.unregister"));
        fru_06.setText(string3);
        fso5.addBasicElement(fru_06);
        fru_06.onAttributesInitialized();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_02);
        fiy_16.setAttribute("visible");
        fiy_16.setField("areParticipantsLimited");
        fiy_16.setName("calendar.event.editable");
        fru_06.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_02);
        fiy_17.setAttribute("enabled");
        fiy_17.setField("isRegistered");
        fiy_17.setName("calendar.event.editable");
        fru_06.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        fiy_17.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fae_2 fae_22 = new fae_2();
        fae_22.onCheckOut();
        fae_22.setElementMap(fyy_02);
        far_23.addBasicElement(fae_22);
        fae_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        fae_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        fai_1 fai_13 = new fai_1();
        fai_13.onCheckOut();
        fai_13.setElementMap(fyy_02);
        fae_22.addBasicElement(fai_13);
        fai_13.onAttributesInitialized();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_02);
        fiy_18.setAttribute("comparedValue");
        fiy_18.setField("isValidated");
        fiy_18.setName("calendar.event.editable");
        fai_13.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        fiy_18.onChildrenAdded();
        fai_13.onChildrenAdded();
        fae_22.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_17.onChildrenAdded();
        fru_0 fru_07 = fru_06;
        fqd_0 fqd_04 = (fqd_0)((fvE)fru_07).getAppearance();
        fqd_04.setElementMap(fyy_02);
        fru_06.addBasicElement(fqd_04);
        fqd_04.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(3, 0, 0, 0));
        fqd_04.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_02);
        fqo_04.setInsets(new Insets(3, 10, 3, 10));
        fqd_04.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqd_04.onChildrenAdded();
        fru_06.onChildrenAdded();
        fru_0 fru_08 = new fru_0();
        fru_08.onCheckOut();
        fru_08.setElementMap(fyy_02);
        fdt_1 fdt_15 = new fdt_1();
        fdt_15.a("wakfu.eventsCalendar:deleteEvent");
        fru_08.setOnClick(fdt_15);
        fru_08.setStyle("flat");
        String string4 = "%eventsCalendar.edit.delete%";
        string4 = string4.replace("%eventsCalendar.edit.delete%", fpm_0.b().c("eventsCalendar.edit.delete"));
        fru_08.setText(string4);
        fso5.addBasicElement(fru_08);
        fru_08.onAttributesInitialized();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_02);
        fiy_19.setAttribute("visible");
        fiy_19.setName("calendar.event.editable.isOwner");
        fru_08.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        fiy_19.onChildrenAdded();
        fru_0 fru_09 = fru_08;
        fqd_0 fqd_05 = (fqd_0)((fvE)fru_09).getAppearance();
        fqd_05.setElementMap(fyy_02);
        fru_08.addBasicElement(fqd_05);
        fqd_05.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_02);
        fqm_05.setInsets(new Insets(3, 0, 0, 0));
        fqd_05.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqo_0 fqo_05 = new fqo_0();
        fqo_05.onCheckOut();
        fqo_05.setElementMap(fyy_02);
        fqo_05.setInsets(new Insets(3, 10, 3, 10));
        fqd_05.addBasicElement(fqo_05);
        fqo_05.onAttributesInitialized();
        fqo_05.onChildrenAdded();
        fqd_05.onChildrenAdded();
        fru_08.onChildrenAdded();
        fso5.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo a(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo b(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fru_02.setStyle("close");
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.eventsCalendar:closeEditEventDialog");
        fru_02.setOnClick(fdt_12);
        fvk_02.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setSize(new fjf_2(-2, -2));
        fid_12.setXOffset(-18);
        fid_12.setYOffset(-12);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo c(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setInitValue(true);
        fid_12.setSize(new fjf_2(-2, -2));
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }
}

