/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cNI
 */
public class cni_1
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        fvk_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvk_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("windowNew");
        fvk_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(10, 5, 12, 5));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setExpandable(false);
        fso3.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fvM fvM3 = fvM2;
        fqj fqj3 = ((fvE)fvM3).getAppearance();
        fqj3.setElementMap(fyy_03);
        fvM2.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 10, 0, 10));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setStyle("titleBar");
        fvM2.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso fso6 = fso5;
        fqj fqj4 = ((fvE)fso6).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso5.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(3, 20, 3, 20));
        fqj4.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.e);
        fso7.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("StyledBold16White");
        String string = "%haven.world.entrance.title%";
        string = string.replace("%haven.world.entrance.title%", fpm_0.b().c("haven.world.entrance.title"));
        fsM2.c(string);
        fso7.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 0, 0, 5));
        fqh_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        fvM2.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso3.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj5 = ((fvE)fso9).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso8.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(0, 12, 0, 12));
        fqj5.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqj5.onChildrenAdded();
        String string2 = "windowContentContainer";
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fso10);
        }
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(false);
        fso10.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso10.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.h);
        fid_14.setSize(new fjf_2(300, 100.0f));
        fso11.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fso11.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        fso11.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.c);
        fid_15.setSize(new fjf_2(100.0f, 70));
        fso12.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.e);
        fin_24.setHorizontal(false);
        fso12.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_03);
        fso13.setExpandable(false);
        fso12.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_03);
        fip_23.setAlign(frs_0.b);
        fso13.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fso fso14 = fso13;
        fqj fqj6 = ((fvE)fso14).getAppearance();
        fqj6.setElementMap(fyy_03);
        fso13.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_03);
        fqo_04.setInsets(new Insets(5, 0, 0, 0));
        fqj6.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj6.onChildrenAdded();
        String string3 = "customNameFilter";
        fug_0 fug_02 = new fug_0();
        fug_02.onCheckOut();
        fug_02.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fug_02);
        }
        fug_02.setAutoHorizontalScrolled(true);
        String string4 = "%guild.name%";
        string4 = string4.replace("%guild.name%", fpm_0.b().c("guild.name"));
        fug_02.b(string4);
        fug_02.a(30);
        fug_02.setMinWidth(240);
        fdo_1 fdo_12 = new fdo_1();
        fdo_12.a("wakfu.havenWorldEntrance:validNameFilter(customNameFilter)");
        fug_02.setOnKeyType(fdo_12);
        fug_02.setSelectOnFocus(true);
        fso13.addBasicElement(fug_02);
        fug_02.onAttributesInitialized();
        fug_0 fug_03 = fug_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fug_03).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fug_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(5, 5, 5, 5));
        fqh_03.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fug_02.onChildrenAdded();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_03);
        fso15.setExpandable(false);
        fso13.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setHorizontal(false);
        fso15.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_03);
        fso16.setExpandable(false);
        fso15.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setDisplaySize(new fjf_2(20, 20));
        fsk_02.setExpandable(false);
        fsk_02.setNonBlocking(false);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(openFilterPopup)");
        fsk_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fsk_02.setOnPopupHide(fdf_22);
        fsk_02.setStyle("LOCK");
        fso16.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        String string5 = "openFilterPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_03);
        if (fyy_03 != null && string5 != null) {
            fyy_03.a(string5, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fsk_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso17 = fso.checkOut();
        fso17.setElementMap(fyy_03);
        fso17.setPrefSize(new fjf_2(10, 0));
        fso17.setStyle("popup");
        fil_12.addBasicElement(fso17);
        fso17.onAttributesInitialized();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_03);
        fsM4.setStyle("PopupInformation");
        String string6 = "%desc.havenWorld.openedFilter%";
        string6 = string6.replace("%desc.havenWorld.openedFilter%", fpm_0.b().c("desc.havenWorld.openedFilter"));
        fsM4.c(string6);
        fso17.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_04.setElementMap(fyy_03);
        fqh_04.setAlignment(frs_0.d);
        fsM4.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso17.onChildrenAdded();
        fil_12.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fup_0 fup_02 = new fup_0();
        fup_02.onCheckOut();
        fup_02.setElementMap(fyy_03);
        fup_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.havenWorldEntrance:checkOpenedFilter");
        fup_02.setOnClick(fdt_12);
        fup_02.setSelected(true);
        fup_02.setStyle("filter");
        fso16.addBasicElement(fup_02);
        fup_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("selected");
        fiy_12.setField("isOpenedFilter");
        fiy_12.setLocal(true);
        fiy_12.setName("havenWorldListView");
        fup_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fup_02.onChildrenAdded();
        fso16.onChildrenAdded();
        fso fso18 = fso.checkOut();
        fso18.setElementMap(fyy_03);
        fso18.setExpandable(false);
        fso15.addBasicElement(fso18);
        fso18.onAttributesInitialized();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_03);
        fsk_03.setDisplaySize(new fjf_2(20, 20));
        fsk_03.setExpandable(false);
        fsk_03.setNonBlocking(false);
        fde_2 fde_23 = new fde_2();
        fde_23.a("popup(guildFilterPopup)");
        fsk_03.setOnPopupDisplay(fde_23);
        fdf_2 fdf_23 = new fdf_2();
        fdf_23.a("closePopup");
        fsk_03.setOnPopupHide(fdf_23);
        fsk_03.setStyle("NEWGUILD");
        fso18.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        String string7 = "guildFilterPopup";
        fil_1 fil_13 = new fil_1();
        fil_13.onCheckOut();
        fil_13.setElementMap(fyy_03);
        if (fyy_03 != null && string7 != null) {
            fyy_03.a(string7, fil_13);
        }
        fil_13.setAlign(frs_0.b);
        fil_13.setHotSpotPosition(frs_0.h);
        fsk_03.addBasicElement(fil_13);
        fil_13.onAttributesInitialized();
        fso fso19 = fso.checkOut();
        fso19.setElementMap(fyy_03);
        fso19.setPrefSize(new fjf_2(10, 0));
        fso19.setStyle("popup");
        fil_13.addBasicElement(fso19);
        fso19.onAttributesInitialized();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_03);
        fsM6.setStyle("PopupInformation");
        String string8 = "%desc.havenWorld.guildFilter%";
        string8 = string8.replace("%desc.havenWorld.guildFilter%", fpm_0.b().c("desc.havenWorld.guildFilter"));
        fsM6.c(string8);
        fso19.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fsM fsM7 = fsM6;
        fqh_0 fqh_05 = (fqh_0)((fvE)fsM7).getAppearance();
        fqh_05.setElementMap(fyy_03);
        fqh_05.setAlignment(frs_0.d);
        fsM6.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqh_05.onChildrenAdded();
        fsM6.onChildrenAdded();
        fso19.onChildrenAdded();
        fil_13.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fup_0 fup_03 = new fup_0();
        fup_03.onCheckOut();
        fup_03.setElementMap(fyy_03);
        fup_03.setExpandable(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.havenWorldEntrance:checkGuildFilter");
        fup_03.setOnClick(fdt_13);
        fup_03.setSelected(true);
        fup_03.setStyle("filter");
        fso18.addBasicElement(fup_03);
        fup_03.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("selected");
        fiy_13.setField("isGuildFilter");
        fiy_13.setLocal(true);
        fiy_13.setName("havenWorldListView");
        fup_03.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fup_03.onChildrenAdded();
        fso18.onChildrenAdded();
        fso15.onChildrenAdded();
        fso13.onChildrenAdded();
        fso fso20 = fso.checkOut();
        fso20.setElementMap(fyy_03);
        fso20.setNonBlocking(true);
        fso12.addBasicElement(fso20);
        fso20.onAttributesInitialized();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setAlign(frs_0.e);
        fso20.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_03);
        fru_02.setEnabled(false);
        fru_02.setExpandable(false);
        fdt_1 fdt_14 = new fdt_1();
        fdt_14.a("wakfu.havenWorldEntrance:firstPage()");
        fru_02.setOnClick(fdt_14);
        fru_02.setStyle("pagingAllLeft");
        fso20.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("enabled");
        fiy_14.setField("hasPreviousPage");
        fiy_14.setName("havenWorldViewList");
        fru_02.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fru_02.onChildrenAdded();
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_03);
        fru_03.setEnabled(false);
        fru_03.setExpandable(false);
        fdt_1 fdt_15 = new fdt_1();
        fdt_15.a("wakfu.havenWorldEntrance:previousPage()");
        fru_03.setOnClick(fdt_15);
        fru_03.setStyle("pagingOneLeft");
        fso20.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("enabled");
        fiy_15.setField("hasPreviousPage");
        fiy_15.setName("havenWorldViewList");
        fru_03.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fru_03.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setExpandable(false);
        fuk_02.setPrefSize(new fjf_2(120, 0));
        fuk_02.setStyle("titleNameBold12");
        String string9 = "%marketBoard.noResults%";
        string9 = string9.replace("%marketBoard.noResults%", fpm_0.b().c("marketBoard.noResults"));
        fuk_02.c(string9);
        fso20.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("text");
        fiy_16.setField("currentPageText");
        fiy_16.setName("havenWorldViewList");
        fuk_02.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_06 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_06.setElementMap(fyy_03);
        fqh_06.setAlign(frs_0.e);
        fuk_02.addBasicElement(fqh_06);
        fqh_06.onAttributesInitialized();
        fqh_06.onChildrenAdded();
        fuk_02.onChildrenAdded();
        this.a(fso20);
        this.b(fso20);
        fso20.onChildrenAdded();
        fso12.onChildrenAdded();
        this.c(fso11);
        this.d(fso11);
        fso11.onChildrenAdded();
        fso10.onChildrenAdded();
        fso8.onChildrenAdded();
        fso3.onChildrenAdded();
        this.a(fvk_02);
        this.b(fvk_02);
        this.c(fvk_02);
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setEnabled(false);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.havenWorldEntrance:nextPage()");
        fru_02.setOnClick(fdt_12);
        fru_02.setStyle("pagingOneRight");
        fso2.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("enabled");
        fiy_12.setField("hasNextPage");
        fiy_12.setName("havenWorldViewList");
        fru_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setEnabled(false);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.havenWorldEntrance:lastPage()");
        fru_02.setOnClick(fdt_12);
        fru_02.setStyle("pagingAllRight");
        fso2.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("enabled");
        fir_12.setField("hasNextPage");
        fru_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("enabled");
        fiy_12.setField("hasNextPage");
        fiy_12.setName("havenWorldViewList");
        fru_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.o);
        fid_12.setSize(new fjf_2(100.0f, 460));
        fid_12.setYOffset(40);
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(0, 8, 0, 5));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(285, 50));
        fsQ2.setIdealSizeMaxColumns(1);
        fsQ2.setIdealSizeMinColumns(1);
        fsQ2.setScrollBarBehaviour(fra_0.c);
        fso3.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("filteredList");
        fiy_12.setName("havenWorldViewList");
        fsQ2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fdi_1 fdi_12 = new fdi_1();
        fdi_12.a("wakfu.havenWorldEntrance:selectHavenWorld");
        faf_22.setOnItemClick(fdi_12);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setStyle("caracs");
        faf_22.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("style");
        fiy_13.setLocal(true);
        fiy_13.setName("selectedHavenWorld");
        fso5.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        far_23.setElseValue("caracs");
        far_23.setValue("caracsBlue");
        fiy_13.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fat_2 fat_22 = new fat_2();
        fat_22.onCheckOut();
        fat_22.setElementMap(fyy_02);
        far_23.addBasicElement(fat_22);
        fat_22.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("value");
        fat_22.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fat_22.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso5.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fin_22.setHorizontal(true);
        fso5.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso6.setExpandable(false);
        fso6.setPrefSize(new fjf_2(32, 32));
        fso5.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(32, 32));
        fso6.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("texture");
        fir_13.setField("guildBlazon");
        fqv2.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso6.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso7.setNonBlocking(false);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fso fso8 = fso7;
        fqj fqj3 = ((fvE)fso8).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso7.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 10, 0, 3));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(200);
        fuk_02.setMinWidth(1);
        fuk_02.setMultiline(true);
        fuk_02.setNonBlocking(false);
        fuk_02.setStyle("titleNameBold10");
        fso7.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("text");
        fir_14.setField("name");
        fuk_02.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.d);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_02);
        fso7.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        fsk_03.setDisplaySize(new fjf_2(20, 20));
        fsk_03.setExpandable(false);
        fsk_03.setNonBlocking(true);
        fsk_03.setStyle("NEWGUILD");
        fso7.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("visible");
        fir_15.setField("isGuildOnly");
        fsk_03.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_02);
        fso9.setExpandable(false);
        fso9.setPrefSize(new fjf_2(20, 20));
        fso7.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        fsk_04.setDisplaySize(new fjf_2(20, 20));
        fsk_04.setExpandable(false);
        fsk_04.setNonBlocking(true);
        fsk_04.setStyle("LOCK");
        fso9.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_02);
        fir_16.setAttribute("visible");
        fir_16.setField("isOpen");
        fsk_04.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_02);
        fir_16.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        far_24.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_24.onChildrenAdded();
        fir_16.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fso9.onChildrenAdded();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.o);
        fid_12.setSize(new fjf_2(100.0f, 30));
        fid_12.setYOffset(10);
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setPrefSize(new fjf_2(110, 30));
        fso4.setVisible(false);
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("canEnter");
        fiy_12.setName("basicHavenWorld");
        fso4.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso4.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.havenWorldEntrance:enterHavenWorld");
        fru_02.setOnClick(fdt_12);
        fso4.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(110, 30));
        fru_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fru_02.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("titleNameBold12");
        String string = "%door.enter%";
        string = string.replace("%door.enter%", fpm_0.b().c("door.enter"));
        fuk_02.c(string);
        fso4.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(110, 30));
        fuk_02.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.e);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso4.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setPrefSize(new fjf_2(110, 30));
        fso5.setVisible(false);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("visible");
        fiy_13.setField("canOpen");
        fiy_13.setName("basicHavenWorld");
        fso5.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fso5.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_02);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.havenWorldEntrance:openHavenWorld");
        fru_03.setOnClick(fdt_13);
        fso5.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setAlign(frk_0.i);
        fid_15.setSize(new fjf_2(110, 30));
        fru_03.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fru_03.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_02);
        fuk_04.setNonBlocking(true);
        fuk_04.setStyle("titleNameBold12");
        String string2 = "%havenWorld.open%";
        string2 = string2.replace("%havenWorld.open%", fpm_0.b().c("havenWorld.open"));
        fuk_04.c(string2);
        fso5.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_02);
        fid_16.setAlign(frk_0.i);
        fid_16.setSize(new fjf_2(110, 30));
        fuk_04.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fuk_0 fuk_05 = fuk_04;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_05).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlign(frs_0.e);
        fuk_04.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fso5.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo a(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo b(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fru_02.setStyle("close");
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("unloadDialog");
        fru_02.setOnClick(fdt_12);
        fvk_02.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setSize(new fjf_2(-2, -2));
        fid_12.setXOffset(-18);
        fid_12.setYOffset(-12);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo c(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setResizeOnce(true);
        fid_12.setSize(new fjf_2(340, 620));
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }
}

