/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cNJ
 */
public class cnj_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        fvk_02.setPack(true);
        fvk_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvk_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("windowNew");
        fvk_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(10, 5, 12, 5));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setExpandable(false);
        fso3.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fvM fvM3 = fvM2;
        fqj fqj3 = ((fvE)fvM3).getAppearance();
        fqj3.setElementMap(fyy_03);
        fvM2.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 10, 0, 10));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setStyle("titleBar");
        fvM2.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso fso6 = fso5;
        fqj fqj4 = ((fvE)fso6).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso5.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(3, 20, 3, 20));
        fqj4.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.e);
        fso7.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("StyledBold16White");
        String string = "%havenWorld%";
        string = string.replace("%havenWorld%", fpm_0.b().c("havenWorld"));
        fsM2.c(string);
        fso7.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 0, 0, 5));
        fqh_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        fvM2.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso3.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj5 = ((fvE)fso9).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso8.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(0, 12, 0, 12));
        fqj5.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqj5.onChildrenAdded();
        String string2 = "windowContentContainer";
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fso10);
        }
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso10.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso11 = fso10;
        fqj fqj6 = ((fvE)fso11).getAppearance();
        fqj6.setElementMap(fyy_03);
        fso10.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_03);
        fqo_04.setInsets(new Insets(10, 0, 0, 0));
        fqj6.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj6.onChildrenAdded();
        String string3 = "elementDetailPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fil_12);
        }
        fil_12.setAlign(frs_0.c);
        fil_12.setHotSpotPosition(frs_0.a);
        fso10.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fyy_0 fyy_04 = fyy_03;
        fyy_03 = this.b.a((fyy_03 != null ? fyy_03.c() : "") + ".elementDetailPopupInc");
        fyy_03.a(fyy_04);
        this.a.push(fyy_03);
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        fso12.setPrefSize(new fjf_2(240, 0));
        fso12.setStyle("popup");
        fil_12.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.b);
        fin_24.setHorizontal(false);
        fso12.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_03);
        fso13.setExpandable(false);
        fso12.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setHorizontal(false);
        fso13.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_03);
        fso13.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setAlign(frs_0.b);
        fin_26.setHorizontal(false);
        fso14.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_03);
        fso15.setExpandable(false);
        fso14.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fin_2 fin_27 = fin_2.checkOut();
        fin_27.setAlign(frs_0.d);
        fso15.addBasicElement(fin_27);
        fin_27.onAttributesInitialized();
        fin_27.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(250);
        fuk_02.setMinWidth(1);
        fuk_02.setStyle("DefaultBold14White");
        fso15.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_03);
        fip_23.setAlign(frs_0.b);
        fuk_02.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fqh_03.setAlign(frs_0.a);
        fuk_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(0, 5, 0, 0));
        fqh_03.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("text");
        fiy_12.setField("name");
        fiy_12.setName("havenWorldOverCatalogEntry");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso15.onChildrenAdded();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_03);
        fso16.setExpandable(false);
        fso14.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        fin_2 fin_28 = fin_2.checkOut();
        fin_28.setAlign(frs_0.d);
        fso16.addBasicElement(fin_28);
        fin_28.onAttributesInitialized();
        fin_28.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setDisplaySize(new fjf_2(128, 128));
        fsk_02.setExpandable(false);
        fsk_02.setKeepAspectRatio(true);
        fso16.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("texture");
        fiy_13.setField("iconUrl");
        fiy_13.setName("havenWorldOverCatalogEntry");
        fqv2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_03);
        fso16.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fso fso17 = fso.checkOut();
        fso17.setElementMap(fyy_03);
        fso17.setExpandable(false);
        fso16.addBasicElement(fso17);
        fso17.onAttributesInitialized();
        fin_2 fin_29 = fin_2.checkOut();
        fin_29.setAlign(frs_0.b);
        fin_29.setHorizontal(false);
        fso17.addBasicElement(fin_29);
        fin_29.onAttributesInitialized();
        fin_29.onChildrenAdded();
        fso fso18 = fso17;
        fqj fqj7 = ((fvE)fso18).getAppearance();
        fqj7.setElementMap(fyy_03);
        fso17.addBasicElement(fqj7);
        fqj7.onAttributesInitialized();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_03);
        fqm_06.setInsets(new Insets(0, 3, 0, 0));
        fqj7.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqj7.onChildrenAdded();
        fso fso19 = fso.checkOut();
        fso19.setElementMap(fyy_03);
        fso19.setExpandable(false);
        fso17.addBasicElement(fso19);
        fso19.onAttributesInitialized();
        fso fso20 = fso19;
        fqj fqj8 = ((fvE)fso20).getAppearance();
        fqj8.setElementMap(fyy_03);
        fso19.addBasicElement(fqj8);
        fqj8.onAttributesInitialized();
        fqm_0 fqm_07 = fqm_0.checkOut();
        fqm_07.setElementMap(fyy_03);
        fqm_07.setInsets(new Insets(0, 0, 2, 0));
        fqj8.addBasicElement(fqm_07);
        fqm_07.onAttributesInitialized();
        fqm_07.onChildrenAdded();
        fqj8.onChildrenAdded();
        fin_2 fin_210 = fin_2.checkOut();
        fin_210.setAlign(frs_0.f);
        fin_210.setHgap((short)2);
        fso19.addBasicElement(fin_210);
        fin_210.onAttributesInitialized();
        fin_210.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_03);
        fuk_04.setExpandable(false);
        fuk_04.setStyle("whiteBold");
        fso19.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fip_2 fip_24 = new fip_2();
        fip_24.onCheckOut();
        fip_24.setElementMap(fyy_03);
        fip_24.setAlign(frs_0.e);
        fuk_04.addBasicElement(fip_24);
        fip_24.onAttributesInitialized();
        fip_24.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("text");
        fiy_14.setField("kamasCost");
        fiy_14.setName("havenWorldOverCatalogEntry");
        fuk_04.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_03);
        fsk_03.setExpandable(false);
        fsk_03.setStyle("KamaIcon");
        fso19.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fsk_03.onChildrenAdded();
        fso19.onChildrenAdded();
        fso fso21 = fso.checkOut();
        fso21.setElementMap(fyy_03);
        fso21.setExpandable(false);
        fso17.addBasicElement(fso21);
        fso21.onAttributesInitialized();
        fin_2 fin_211 = fin_2.checkOut();
        fin_211.setAlign(frs_0.f);
        fin_211.setHgap((short)2);
        fso21.addBasicElement(fin_211);
        fin_211.onAttributesInitialized();
        fin_211.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("visible");
        fiy_15.setField("ressourcesCost");
        fiy_15.setName("havenWorldOverCatalogEntry");
        fso21.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        fiy_15.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_15.onChildrenAdded();
        fuk_0 fuk_05 = new fuk_0();
        fuk_05.onCheckOut();
        fuk_05.setElementMap(fyy_03);
        fuk_05.setExpandable(false);
        fuk_05.setStyle("whiteBold");
        fso21.addBasicElement(fuk_05);
        fuk_05.onAttributesInitialized();
        fip_2 fip_25 = new fip_2();
        fip_25.onCheckOut();
        fip_25.setElementMap(fyy_03);
        fip_25.setAlign(frs_0.e);
        fuk_05.addBasicElement(fip_25);
        fip_25.onAttributesInitialized();
        fip_25.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("text");
        fiy_16.setField("ressourcesCost");
        fiy_16.setName("havenWorldOverCatalogEntry");
        fuk_05.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fuk_05.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_03);
        fsk_04.setExpandable(false);
        fsk_04.setStyle("HavenWorldResourcesPoints");
        fso21.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fsk_04.onChildrenAdded();
        fso21.onChildrenAdded();
        fso fso22 = fso.checkOut();
        fso22.setElementMap(fyy_03);
        fso22.setExpandable(false);
        fso17.addBasicElement(fso22);
        fso22.onAttributesInitialized();
        fin_2 fin_212 = fin_2.checkOut();
        fin_212.setAlign(frs_0.f);
        fin_212.setHgap((short)2);
        fso22.addBasicElement(fin_212);
        fin_212.onAttributesInitialized();
        fin_212.onChildrenAdded();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_03);
        fiy_17.setAttribute("visible");
        fiy_17.setField("sidoaNeed");
        fiy_17.setName("havenWorldOverCatalogEntry");
        fso22.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        fiy_17.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_03);
        far_23.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_17.onChildrenAdded();
        fuk_0 fuk_06 = new fuk_0();
        fuk_06.onCheckOut();
        fuk_06.setElementMap(fyy_03);
        fuk_06.setExpandable(false);
        fuk_06.setStyle("whiteBold");
        fso22.addBasicElement(fuk_06);
        fuk_06.onAttributesInitialized();
        fip_2 fip_26 = new fip_2();
        fip_26.onCheckOut();
        fip_26.setElementMap(fyy_03);
        fip_26.setAlign(frs_0.e);
        fuk_06.addBasicElement(fip_26);
        fip_26.onAttributesInitialized();
        fip_26.onChildrenAdded();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_03);
        fiy_18.setAttribute("text");
        fiy_18.setField("sidoaNeed");
        fiy_18.setName("havenWorldOverCatalogEntry");
        fuk_06.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        fiy_18.onChildrenAdded();
        fuk_06.onChildrenAdded();
        this.a(fso22);
        fso22.onChildrenAdded();
        this.b(fso17);
        this.c(fso17);
        fso17.onChildrenAdded();
        fso16.onChildrenAdded();
        fso14.onChildrenAdded();
        this.d(fso13);
        fso13.onChildrenAdded();
        this.e(fso12);
        this.f(fso12);
        this.g(fso12);
        this.h(fso12);
        fso12.onChildrenAdded();
        this.a.pop();
        fyy_03 = this.a.peek();
        fil_12.onChildrenAdded();
        this.i(fso10);
        this.j(fso10);
        this.p(fso10);
        fso10.onChildrenAdded();
        fso8.onChildrenAdded();
        fso3.onChildrenAdded();
        this.a(fvk_02);
        this.b(fvk_02);
        this.c(fvk_02);
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setExpandable(false);
        fsk_02.setStyle("Sidoa");
        fso2.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_02.onChildrenAdded();
        return fsk_02;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setVisible(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("buildDelay");
        fiy_12.setName("havenWorldOverCatalogEntry");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.f);
        fso3.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHgap((short)2);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setStyle("11Light");
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("text");
        fiy_13.setField("buildDelay");
        fiy_13.setName("havenWorldOverCatalogEntry");
        fsM2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fsM2.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setExpandable(false);
        fsk_02.setStyle("SmallTimer");
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("surface");
        fiy_12.setName("havenWorldOverCatalogEntry");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.f);
        fso3.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHgap((short)2);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("11Light");
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("text");
        fiy_13.setField("surface");
        fiy_13.setName("havenWorldOverCatalogEntry");
        fsM2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fsM2.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setExpandable(false);
        fsk_02.setStyle("IconSurface");
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 0, 0, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.f);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo e(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setExpandable(false);
        fso4.setPrefSize(new fjf_2(50, 1));
        fso4.setStyle("lineSeparator2");
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso4;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso4.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(5, 20, 5, 20));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso4.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(230);
        fuk_02.setMinWidth(1);
        fuk_02.setStyle("narrow12");
        fso3.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.d);
        fuk_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 0, 0, 0));
        fqh_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_02);
        fqg_02.setColor(new fyr_0("descriptionPopupColor"));
        fqh_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("description");
        fiy_12.setName("havenWorldOverCatalogEntry");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo f(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("effects");
        fiy_12.setName("havenWorldOverCatalogEntry");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setExpandable(false);
        fso4.setPrefSize(new fjf_2(50, 1));
        fso4.setStyle("lineSeparator2");
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso4;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso4.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(5, 20, 5, 20));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso4.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso6.setExpandable(false);
        fso3.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.d);
        fso6.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.d);
        fso6.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setStyle("11BoldLight");
        String string = "%effects%";
        string = string.replace("%effects%", fpm_0.b().c("effects"));
        fsM2.c(string);
        fso6.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 5, 5, 0));
        fqh_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setExpandable(false);
        fsM4.setStyle("11BoldLight");
        String string2 = "%effects.guildMembers%";
        string2 = string2.replace("%effects.guildMembers%", fpm_0.b().c("effects.guildMembers"));
        fsM4.c(string2);
        fso6.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM4.onChildrenAdded();
        fso6.onChildrenAdded();
        fus_0 fus_02 = new fus_0();
        fus_02.onCheckOut();
        fus_02.setElementMap(fyy_02);
        fus_02.setHorizontal(false);
        fso3.addBasicElement(fus_02);
        fus_02.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_02);
        fip_23.setAlign(frs_0.d);
        fus_02.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("content");
        fiy_13.setField("effects");
        fiy_13.setName("havenWorldOverCatalogEntry");
        fus_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fus_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        faf_22.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_23.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_23.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        faf_22.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(250);
        fuk_02.setMinWidth(250);
        fuk_02.setMultiline(true);
        fuk_02.setStyle("white11");
        fso7.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fuk_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 5, 0, 0));
        fqh_03.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("text");
        fuk_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso7.onChildrenAdded();
        faf_22.onChildrenAdded();
        fus_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo g(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("evolutionName");
        fiy_12.setName("havenWorldOverCatalogEntry");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setExpandable(false);
        fso4.setPrefSize(new fjf_2(50, 1));
        fso4.setStyle("lineSeparator2");
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso4;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso4.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(5, 20, 5, 20));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso4.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setStyle("11BoldLight");
        String string = "%desc.buildingEvolution%";
        string = string.replace("%desc.buildingEvolution%", fpm_0.b().c("desc.buildingEvolution"));
        fsM2.c(string);
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 5, 5, 0));
        fqh_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(225);
        fuk_02.setMinWidth(1);
        fuk_02.setStyle("white11");
        fso3.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.d);
        fuk_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fuk_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 10, 5, 0));
        fqh_03.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("text");
        fiy_13.setField("evolutionName");
        fiy_13.setName("havenWorldOverCatalogEntry");
        fuk_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo h(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("conditions");
        fiy_12.setName("havenWorldOverCatalogEntry");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setExpandable(false);
        fso4.setPrefSize(new fjf_2(50, 1));
        fso4.setStyle("lineSeparator2");
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso4;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso4.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(5, 20, 5, 20));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso4.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setStyle("11BoldLight");
        String string = "%requirements%";
        string = string.replace("%requirements%", fpm_0.b().c("requirements"));
        fsM2.c(string);
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 5, 5, 0));
        fqh_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(225);
        fuk_02.setMinWidth(1);
        fuk_02.setStyle("white11");
        fso3.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.d);
        fuk_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fuk_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 10, 5, 0));
        fqh_03.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("text");
        fiy_13.setField("conditions");
        fiy_13.setName("havenWorldOverCatalogEntry");
        fuk_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo i(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setStyle("ScrollString");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.j);
        fid_12.setSize(new fjf_2(10, 100.0f));
        fid_12.setXOffset(-5);
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(30, 0, 35, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo j(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setStyle("Encyclopedia");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(0, 10, 0, 0));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(17, 3, 20, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setPrefSize(new fjf_2(0, 500));
        fso5.setStyle("tiledScroll");
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso5.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fso fso6 = fso5;
        fqj fqj3 = ((fvE)fso6).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso5.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_02);
        fqo_03.setInsets(new Insets(5, 10, 0, 0));
        fqj3.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 10, 0, 20));
        fqj3.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj3.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso5.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso7.setExpandable(false);
        fso7.setPrefSize(new fjf_2(0, 130));
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso7.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso8.setExpandable(false);
        fso8.setPrefSize(new fjf_2(0, 30));
        fso8.setStyle("EncyclopediaSplashTitle");
        fso7.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.c);
        fid_14.setSize(new fjf_2(100.0f, -2));
        fso8.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fso fso9 = fso8;
        fqj fqj4 = ((fvE)fso9).getAppearance();
        fqj4.setElementMap(fyy_02);
        fso8.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_02);
        fqo_04.setInsets(new Insets(0, 0, 3, 0));
        fqj4.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj4.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.e);
        fso8.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(83, 39));
        fsk_02.setExpandable(false);
        fsk_02.setStyle("NationLeftDecorator");
        fso8.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_02.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(250);
        fuk_02.setMinWidth(1);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("StyledBold16White");
        fso8.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("havenWorldName");
        fiy_12.setName("havenWorld");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        fsk_03.setDisplaySize(new fjf_2(83, 39));
        fsk_03.setExpandable(false);
        fsk_03.setStyle("NationRightDecorator");
        fso8.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fsk_03.onChildrenAdded();
        fso8.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_02);
        fso7.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setAlign(frk_0.o);
        fso10.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.b);
        fin_24.setHorizontal(false);
        fin_24.setVgap((short)8);
        fso10.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fso fso11 = fso10;
        fqj fqj5 = ((fvE)fso11).getAppearance();
        fqj5.setElementMap(fyy_02);
        fso10.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqo_0 fqo_05 = new fqo_0();
        fqo_05.onCheckOut();
        fqo_05.setElementMap(fyy_02);
        fqo_05.setInsets(new Insets(0, 5, 0, 10));
        fqj5.addBasicElement(fqo_05);
        fqo_05.onAttributesInitialized();
        fqo_05.onChildrenAdded();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 150, 0, 0));
        fqj5.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqj5.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_02);
        fso12.setExpandable(false);
        fso10.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fic_14.setAdaptToContentSize(true);
        fso12.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_02);
        fso13.setPrefSize(new fjf_2(0, 20));
        fso13.setStyle("TiledScrollCenter");
        fso12.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_02);
        fid_16.setAlign(frk_0.h);
        fid_16.setSize(new fjf_2(100.0f, -2));
        fso13.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fso13.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        fsk_04.setDisplaySize(new fjf_2(260, 4));
        fsk_04.setStyle("TiledScrollTop");
        fso12.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_02);
        fid_17.setAlign(frk_0.a);
        fsk_04.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fsk_0 fsk_05 = new fsk_0();
        fsk_05.onCheckOut();
        fsk_05.setElementMap(fyy_02);
        fsk_05.setDisplaySize(new fjf_2(260, 4));
        fsk_05.setStyle("TiledScrollBottom");
        fso12.addBasicElement(fsk_05);
        fsk_05.onAttributesInitialized();
        fid_1 fid_18 = new fid_1();
        fid_18.onCheckOut();
        fid_18.setElementMap(fyy_02);
        fid_18.setAlign(frk_0.m);
        fsk_05.addBasicElement(fid_18);
        fid_18.onAttributesInitialized();
        fid_18.onChildrenAdded();
        fsk_05.onChildrenAdded();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_02);
        fso12.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        fid_1 fid_19 = new fid_1();
        fid_19.onCheckOut();
        fid_19.setElementMap(fyy_02);
        fid_19.setAlign(frk_0.i);
        fid_19.setSize(new fjf_2(100.0f, -2));
        fso14.addBasicElement(fid_19);
        fid_19.onAttributesInitialized();
        fid_19.onChildrenAdded();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setAlign(frs_0.d);
        fso14.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setStyle("darkBold");
        String string = "%ownerWithComas%";
        string = string.replace("%ownerWithComas%", fpm_0.b().c("ownerWithComas"));
        fsM2.c(string);
        fso14.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM2.onChildrenAdded();
        fuk_0 fuk_03 = new fuk_0();
        fuk_03.onCheckOut();
        fuk_03.setElementMap(fyy_02);
        fuk_03.setExpandable(false);
        fuk_03.setStyle("darkTitle");
        fso14.addBasicElement(fuk_03);
        fuk_03.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("text");
        fiy_13.setField("guildName");
        fiy_13.setName("havenWorld");
        fuk_03.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fuk_03.onChildrenAdded();
        fso14.onChildrenAdded();
        fso12.onChildrenAdded();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_02);
        fso15.setExpandable(false);
        fso10.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fic_1 fic_15 = new fic_1();
        fic_15.onCheckOut();
        fic_15.setAdaptToContentSize(true);
        fso15.addBasicElement(fic_15);
        fic_15.onAttributesInitialized();
        fic_15.onChildrenAdded();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_02);
        fso16.setPrefSize(new fjf_2(0, 20));
        fso16.setStyle("TiledScrollCenter");
        fso15.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        fid_1 fid_110 = new fid_1();
        fid_110.onCheckOut();
        fid_110.setElementMap(fyy_02);
        fid_110.setAlign(frk_0.h);
        fid_110.setSize(new fjf_2(100.0f, -2));
        fso16.addBasicElement(fid_110);
        fid_110.onAttributesInitialized();
        fid_110.onChildrenAdded();
        fso16.onChildrenAdded();
        fsk_0 fsk_06 = new fsk_0();
        fsk_06.onCheckOut();
        fsk_06.setElementMap(fyy_02);
        fsk_06.setDisplaySize(new fjf_2(260, 4));
        fsk_06.setStyle("TiledScrollTop");
        fso15.addBasicElement(fsk_06);
        fsk_06.onAttributesInitialized();
        fid_1 fid_111 = new fid_1();
        fid_111.onCheckOut();
        fid_111.setElementMap(fyy_02);
        fid_111.setAlign(frk_0.a);
        fsk_06.addBasicElement(fid_111);
        fid_111.onAttributesInitialized();
        fid_111.onChildrenAdded();
        fsk_06.onChildrenAdded();
        fsk_0 fsk_07 = new fsk_0();
        fsk_07.onCheckOut();
        fsk_07.setElementMap(fyy_02);
        fsk_07.setDisplaySize(new fjf_2(260, 4));
        fsk_07.setStyle("TiledScrollBottom");
        fso15.addBasicElement(fsk_07);
        fsk_07.onAttributesInitialized();
        fid_1 fid_112 = new fid_1();
        fid_112.onCheckOut();
        fid_112.setElementMap(fyy_02);
        fid_112.setAlign(frk_0.m);
        fsk_07.addBasicElement(fid_112);
        fid_112.onAttributesInitialized();
        fid_112.onChildrenAdded();
        fsk_07.onChildrenAdded();
        fso fso17 = fso.checkOut();
        fso17.setElementMap(fyy_02);
        fso15.addBasicElement(fso17);
        fso17.onAttributesInitialized();
        fid_1 fid_113 = new fid_1();
        fid_113.onCheckOut();
        fid_113.setElementMap(fyy_02);
        fid_113.setAlign(frk_0.i);
        fid_113.setSize(new fjf_2(100.0f, -2));
        fso17.addBasicElement(fid_113);
        fid_113.onAttributesInitialized();
        fid_113.onChildrenAdded();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setAlign(frs_0.d);
        fso17.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        fsM fsM3 = new fsM();
        fsM3.onCheckOut();
        fsM3.setElementMap(fyy_02);
        fsM3.setExpandable(false);
        fsM3.setStyle("darkBold");
        String string2 = "%actualRank%";
        string2 = string2.replace("%actualRank%", fpm_0.b().c("actualRank"));
        fsM3.c(string2);
        fso17.addBasicElement(fsM3);
        fsM3.onAttributesInitialized();
        fsM3.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_02);
        fuk_04.setExpandable(false);
        fuk_04.setStyle("darkTitle");
        fso17.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("text");
        fiy_14.setField("guildRank");
        fiy_14.setName("havenWorld");
        fuk_04.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fso17.onChildrenAdded();
        fso15.onChildrenAdded();
        fso fso18 = fso.checkOut();
        fso18.setElementMap(fyy_02);
        fso18.setExpandable(false);
        fso10.addBasicElement(fso18);
        fso18.onAttributesInitialized();
        fic_1 fic_16 = new fic_1();
        fic_16.onCheckOut();
        fic_16.setAdaptToContentSize(true);
        fso18.addBasicElement(fic_16);
        fic_16.onAttributesInitialized();
        fic_16.onChildrenAdded();
        fso fso19 = fso.checkOut();
        fso19.setElementMap(fyy_02);
        fso19.setPrefSize(new fjf_2(0, 20));
        fso19.setStyle("TiledScrollCenter");
        fso18.addBasicElement(fso19);
        fso19.onAttributesInitialized();
        fid_1 fid_114 = new fid_1();
        fid_114.onCheckOut();
        fid_114.setElementMap(fyy_02);
        fid_114.setAlign(frk_0.h);
        fid_114.setSize(new fjf_2(100.0f, -2));
        fso19.addBasicElement(fid_114);
        fid_114.onAttributesInitialized();
        fid_114.onChildrenAdded();
        fso19.onChildrenAdded();
        fsk_0 fsk_08 = new fsk_0();
        fsk_08.onCheckOut();
        fsk_08.setElementMap(fyy_02);
        fsk_08.setDisplaySize(new fjf_2(260, 4));
        fsk_08.setStyle("TiledScrollTop");
        fso18.addBasicElement(fsk_08);
        fsk_08.onAttributesInitialized();
        fid_1 fid_115 = new fid_1();
        fid_115.onCheckOut();
        fid_115.setElementMap(fyy_02);
        fid_115.setAlign(frk_0.a);
        fsk_08.addBasicElement(fid_115);
        fid_115.onAttributesInitialized();
        fid_115.onChildrenAdded();
        fsk_08.onChildrenAdded();
        fsk_0 fsk_09 = new fsk_0();
        fsk_09.onCheckOut();
        fsk_09.setElementMap(fyy_02);
        fsk_09.setDisplaySize(new fjf_2(260, 4));
        fsk_09.setStyle("TiledScrollBottom");
        fso18.addBasicElement(fsk_09);
        fsk_09.onAttributesInitialized();
        fid_1 fid_116 = new fid_1();
        fid_116.onCheckOut();
        fid_116.setElementMap(fyy_02);
        fid_116.setAlign(frk_0.m);
        fsk_09.addBasicElement(fid_116);
        fid_116.onAttributesInitialized();
        fid_116.onChildrenAdded();
        fsk_09.onChildrenAdded();
        fso fso20 = fso.checkOut();
        fso20.setElementMap(fyy_02);
        fso18.addBasicElement(fso20);
        fso20.onAttributesInitialized();
        fid_1 fid_117 = new fid_1();
        fid_117.onCheckOut();
        fid_117.setElementMap(fyy_02);
        fid_117.setAlign(frk_0.i);
        fid_117.setSize(new fjf_2(100.0f, -2));
        fso20.addBasicElement(fid_117);
        fid_117.onAttributesInitialized();
        fid_117.onChildrenAdded();
        fin_2 fin_27 = fin_2.checkOut();
        fin_27.setAlign(frs_0.d);
        fso20.addBasicElement(fin_27);
        fin_27.onAttributesInitialized();
        fin_27.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setExpandable(false);
        fsM4.setStyle("darkBold");
        String string3 = "%actualConquestRank%";
        string3 = string3.replace("%actualConquestRank%", fpm_0.b().c("actualConquestRank"));
        fsM4.c(string3);
        fso20.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM4.onChildrenAdded();
        fuk_0 fuk_05 = new fuk_0();
        fuk_05.onCheckOut();
        fuk_05.setElementMap(fyy_02);
        fuk_05.setExpandable(false);
        fuk_05.setStyle("darkTitle");
        fso20.addBasicElement(fuk_05);
        fuk_05.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("text");
        fiy_15.setField("conquestRank");
        fiy_15.setName("havenWorld");
        fuk_05.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fuk_05.onChildrenAdded();
        fso20.onChildrenAdded();
        fso18.onChildrenAdded();
        fso10.onChildrenAdded();
        this.k(fso7);
        fso7.onChildrenAdded();
        this.l(fso5);
        this.m(fso5);
        this.n(fso5);
        this.o(fso5);
        fso5.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo k(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setStyle("HavenWorldMini");
        fso2.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.a);
        fid_12.setYOffset(-10);
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fsk_02.onChildrenAdded();
        return fsk_02;
    }

    public fyo l(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setNonBlocking(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.havenWorldPanel:toggleOpenBuildingList");
        fso3.setOnClick(fdt_12);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(15, 0, 0, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setStyle("scrollTitleBar");
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        ((fqj)fqp2).setModulationColor(new azf_2(1.0f, 1.0f, 1.0f, 0.8f));
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqp2.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setExpandable(false);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso5.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso5.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setEnableShrinking(false);
        fsM2.setExpandable(false);
        fsM2.setStyle("WhiteTitle");
        String string = "%buildingsBuiltList%";
        string = string.replace("%buildingsBuiltList%", fpm_0.b().c("buildingsBuiltList"));
        fsM2.c(string);
        fso5.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM fsM4 = fsM2;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM4).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fsM2.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 30, 0, 0));
        fqh_03.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fsM2.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        fsk_04.setExpandable(false);
        fso5.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fsk_0 fsk_05 = fsk_04;
        fqp fqp3 = (fqp)((fvE)fsk_05).getAppearance();
        fqp3.setElementMap(fyy_02);
        fsk_04.addBasicElement(fqp3);
        fqp3.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 10, 0, 0));
        fqp3.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqp3.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("style");
        fiy_12.setField("buildingsOpenned");
        fiy_12.setName("havenWorld");
        fsk_04.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        far_22.setElseValue("RightArrowMarket");
        far_22.setValue("DownArrowMarket");
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fso5.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo m(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(64, 64));
        fsQ2.setExpandable(false);
        fsQ2.setIdealSizeMaxColumns(6);
        fsQ2.setIdealSizeMaxRows(30);
        fsQ2.setIdealSizeMinColumns(1);
        fsQ2.setIdealSizeMinRows(1);
        fsQ2.setVisible(false);
        fso2.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.d);
        fsQ2.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("buildingList");
        fiy_12.setName("havenWorld");
        fsQ2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("visible");
        fiy_13.setField("buildingsOpenned");
        fiy_13.setName("havenWorld");
        fsQ2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        faf_22.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        String string = "element";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fij_12);
        }
        fso3.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("value");
        fij_12.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setExpandable(false);
        fso4.setNonBlocking(false);
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.a("wakfu.havenWorldPanel:onMouseOverElement(element,elementDetailPopup)");
        fso4.setOnMouseEnter(fdy_12);
        fdz_1 fdz_12 = new fdz_1();
        fdz_12.a("wakfu.havenWorldPanel:onMouseOutElement(element,elementDetailPopup)");
        fso4.setOnMouseExit(fdz_12);
        fso4.setPrefSize(new fjf_2(50, 50));
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(50, 50));
        fsk_02.setNonBlocking(true);
        fso4.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("texture");
        fir_13.setField("iconUrl");
        fqv2.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso4.onChildrenAdded();
        fso3.onChildrenAdded();
        faf_22.onChildrenAdded();
        faf_2 faf_23 = new faf_2();
        faf_23.onCheckOut();
        faf_23.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_23);
        faf_23.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        faf_23.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fav_1 fav_13 = new fav_1();
        fav_13.onCheckOut();
        fav_13.setElementMap(fyy_02);
        far_23.addBasicElement(fav_13);
        fav_13.onAttributesInitialized();
        fac_1 fac_12 = new fac_1();
        fac_12.onCheckOut();
        fac_12.setElementMap(fyy_02);
        fav_13.addBasicElement(fac_12);
        fac_12.onAttributesInitialized();
        fac_12.onChildrenAdded();
        fav_13.onChildrenAdded();
        far_23.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        faf_23.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso5.onChildrenAdded();
        faf_23.onChildrenAdded();
        fsQ2.onChildrenAdded();
        return fsQ2;
    }

    public fyo n(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setNonBlocking(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.havenWorldPanel:toggleOpenEvolutingBuildingList");
        fso3.setOnClick(fdt_12);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(15, 0, 0, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setStyle("scrollTitleBar");
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        ((fqj)fqp2).setModulationColor(new azf_2(1.0f, 1.0f, 1.0f, 0.8f));
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqp2.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setExpandable(false);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso5.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso5.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setEnableShrinking(false);
        fsM2.setExpandable(false);
        fsM2.setStyle("WhiteTitle");
        String string = "%evolutingBuildingsList%";
        string = string.replace("%evolutingBuildingsList%", fpm_0.b().c("evolutingBuildingsList"));
        fsM2.c(string);
        fso5.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM fsM4 = fsM2;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM4).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fsM2.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 30, 0, 0));
        fqh_03.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fsM2.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        fsk_04.setExpandable(false);
        fso5.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fsk_0 fsk_05 = fsk_04;
        fqp fqp3 = (fqp)((fvE)fsk_05).getAppearance();
        fqp3.setElementMap(fyy_02);
        fsk_04.addBasicElement(fqp3);
        fqp3.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 10, 0, 0));
        fqp3.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqp3.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("style");
        fiy_12.setField("evolutingBuildingsOpenned");
        fiy_12.setName("havenWorld");
        fsk_04.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        far_22.setElseValue("RightArrowMarket");
        far_22.setValue("DownArrowMarket");
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fso5.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo o(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(64, 64));
        fsQ2.setExpandable(false);
        fsQ2.setIdealSizeMaxColumns(6);
        fsQ2.setIdealSizeMaxRows(30);
        fsQ2.setIdealSizeMinColumns(1);
        fsQ2.setIdealSizeMinRows(1);
        fsQ2.setVisible(false);
        fso2.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.d);
        fsQ2.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("evolutingBuildingList");
        fiy_12.setName("havenWorld");
        fsQ2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("visible");
        fiy_13.setField("evolutingBuildingsOpenned");
        fiy_13.setName("havenWorld");
        fsQ2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        faf_22.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        String string = "element";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fij_12);
        }
        fso3.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("value");
        fij_12.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setExpandable(false);
        fso4.setNonBlocking(false);
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.a("wakfu.havenWorldPanel:onMouseOverElement(element,elementDetailPopup)");
        fso4.setOnMouseEnter(fdy_12);
        fdz_1 fdz_12 = new fdz_1();
        fdz_12.a("wakfu.havenWorldPanel:onMouseOutElement(element,elementDetailPopup)");
        fso4.setOnMouseExit(fdz_12);
        fso4.setPrefSize(new fjf_2(50, 50));
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(50, 50));
        fsk_02.setNonBlocking(true);
        fso4.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("texture");
        fir_13.setField("iconUrl");
        fqv2.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso4.onChildrenAdded();
        fso3.onChildrenAdded();
        faf_22.onChildrenAdded();
        faf_2 faf_23 = new faf_2();
        faf_23.onCheckOut();
        faf_23.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_23);
        faf_23.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        faf_23.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fav_1 fav_13 = new fav_1();
        fav_13.onCheckOut();
        fav_13.setElementMap(fyy_02);
        far_23.addBasicElement(fav_13);
        fav_13.onAttributesInitialized();
        fac_1 fac_12 = new fac_1();
        fac_12.onCheckOut();
        fac_12.setElementMap(fyy_02);
        fav_13.addBasicElement(fac_12);
        fac_12.onAttributesInitialized();
        fac_12.onChildrenAdded();
        fav_13.onChildrenAdded();
        far_23.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        faf_23.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso5.onChildrenAdded();
        faf_23.onChildrenAdded();
        fsQ2.onChildrenAdded();
        return fsQ2;
    }

    public fyo p(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setNonBlocking(true);
        fso3.setStyle("EncyclopediaPane");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.c);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fid_12.setYOffset(1);
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo a(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo b(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fru_02.setStyle("close");
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("unloadDialog");
        fru_02.setOnClick(fdt_12);
        fvk_02.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setSize(new fjf_2(-2, -2));
        fid_12.setXOffset(-18);
        fid_12.setYOffset(-12);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo c(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setResizeOnce(true);
        fid_12.setSize(new fjf_2(-2, -2));
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }
}

