/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cNj
 */
public class cnj_1
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        String string = "fightBar";
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fvk_02);
        }
        fdm_1 fdm_12 = new fdm_1();
        fdm_12.a("wakfu.windowStick:stickWindow");
        fvk_02.setOnStick(fdm_12);
        fvk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setAlign(frk_0.o);
        fid_12.setInitValue(true);
        fid_12.setXOffset(-200);
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fso2.setNonBlocking(false);
        fso2.setStyle("MainBackground");
        fvM2.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        String string2 = "giveUpButton";
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fru_02);
        }
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.fightAction:giveUpFight");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(descGiveUpFightPopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setPrefSize(new fjf_2(33, 35));
        fru_02.setStyle("fightBar2");
        fso2.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        String string3 = "descGiveUpFightPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setPrefSize(new fjf_2(10, 0));
        fso3.setStyle("popup");
        fil_12.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_03);
        fii_22.setData(frg_0.a);
        fso3.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setStyle("PopupInformation");
        String string4 = "%desc.giveUpFight% (";
        string4 = string4.replace("%desc.giveUpFight%", fpm_0.b().c("desc.giveUpFight"));
        fsM2.c(string4);
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_03);
        fsM4.setStyle("PopupInformation");
        fso3.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fqh_03.setAlignment(frs_0.d);
        fsM4.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("text");
        fiy_12.setField("giveUp/key");
        fiy_12.setName("shortcutsList");
        fsM4.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fsM4.onChildrenAdded();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_03);
        fsM6.setStyle("PopupInformation");
        fsM6.c(")");
        fso3.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fsM fsM7 = fsM6;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM7).getAppearance();
        fqh_04.setElementMap(fyy_03);
        fqh_04.setAlignment(frs_0.d);
        fsM6.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fsM6.onChildrenAdded();
        fso3.onChildrenAdded();
        fil_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("enabled");
        fiy_13.setName("canGiveUpFight");
        fru_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        fiy_13.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fan_2 fan_22 = new fan_2();
        fan_22.onCheckOut();
        fan_22.setElementMap(fyy_03);
        far_22.addBasicElement(fan_22);
        fan_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_03);
        fan_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_03);
        fan_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("comparedValue");
        fiy_14.setName("giveUpDisabled");
        fau_12.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fau_12.onChildrenAdded();
        fan_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("giveUpFlag");
        fru_02.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("modulationColor");
        fiy_15.setName("canGiveUpFight");
        fsk_02.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        far_23.setElseValue("1,1,1,0.5");
        far_23.setValue("1,1,1");
        fiy_15.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fan_2 fan_23 = new fan_2();
        fan_23.onCheckOut();
        fan_23.setElementMap(fyy_03);
        far_23.addBasicElement(fan_23);
        fan_23.onAttributesInitialized();
        fai_1 fai_13 = new fai_1();
        fai_13.onCheckOut();
        fai_13.setElementMap(fyy_03);
        fan_23.addBasicElement(fai_13);
        fai_13.onAttributesInitialized();
        fai_13.onChildrenAdded();
        fau_1 fau_13 = new fau_1();
        fau_13.onCheckOut();
        fau_13.setElementMap(fyy_03);
        fan_23.addBasicElement(fau_13);
        fau_13.onAttributesInitialized();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("comparedValue");
        fiy_16.setName("giveUpDisabled");
        fau_13.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fau_13.onChildrenAdded();
        fan_23.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_15.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fru_02.onChildrenAdded();
        String string5 = "hideFightersButton";
        fup_0 fup_02 = new fup_0();
        fup_02.onCheckOut();
        fup_02.setElementMap(fyy_03);
        if (fyy_03 != null && string5 != null) {
            fyy_03.a(string5, fup_02);
        }
        fup_02.setExpandable(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.fightAction:hideFighters");
        fup_02.setOnClick(fdt_13);
        fde_2 fde_23 = new fde_2();
        fde_23.a("popup(descHideFightersPopup)");
        fup_02.setOnPopupDisplay(fde_23);
        fdf_2 fdf_23 = new fdf_2();
        fdf_23.a("closePopup");
        fup_02.setOnPopupHide(fdf_23);
        fup_02.setPrefSize(new fjf_2(33, 35));
        fup_02.setStyle("fightBar2");
        fso2.addBasicElement(fup_02);
        fup_02.onAttributesInitialized();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_03);
        fiy_17.setAttribute("selected");
        fiy_17.setField("enableFightersTransparency");
        fiy_17.setName("gamePreferences");
        fup_02.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_03);
        fiy_18.setAttribute("enabled");
        fiy_18.setName("hideFightersDisabled");
        fup_02.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_03);
        fiy_18.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fau_1 fau_14 = new fau_1();
        fau_14.onCheckOut();
        fau_14.setElementMap(fyy_03);
        far_24.addBasicElement(fau_14);
        fau_14.onAttributesInitialized();
        fau_14.onChildrenAdded();
        far_24.onChildrenAdded();
        fiy_18.onChildrenAdded();
        String string6 = "descHideFightersPopup";
        fil_1 fil_13 = new fil_1();
        fil_13.onCheckOut();
        fil_13.setElementMap(fyy_03);
        if (fyy_03 != null && string6 != null) {
            fyy_03.a(string6, fil_13);
        }
        fil_13.setAlign(frs_0.b);
        fil_13.setHotSpotPosition(frs_0.h);
        fup_02.addBasicElement(fil_13);
        fil_13.onAttributesInitialized();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_03);
        fso4.setPrefSize(new fjf_2(10, 0));
        fso4.setStyle("popup");
        fil_13.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fii_2 fii_23 = fii_2.checkOut();
        fii_23.setElementMap(fyy_03);
        fii_23.setData(frg_0.a);
        fso4.addBasicElement(fii_23);
        fii_23.onAttributesInitialized();
        fii_23.onChildrenAdded();
        fsM fsM8 = new fsM();
        fsM8.onCheckOut();
        fsM8.setElementMap(fyy_03);
        fsM8.setStyle("PopupInformation");
        String string7 = "%desc.hideFighters% (";
        string7 = string7.replace("%desc.hideFighters%", fpm_0.b().c("desc.hideFighters"));
        fsM8.c(string7);
        fso4.addBasicElement(fsM8);
        fsM8.onAttributesInitialized();
        fsM fsM9 = fsM8;
        fqh_0 fqh_05 = (fqh_0)((fvE)fsM9).getAppearance();
        fqh_05.setElementMap(fyy_03);
        fqh_05.setAlignment(frs_0.d);
        fsM8.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqh_05.onChildrenAdded();
        fsM8.onChildrenAdded();
        fsM fsM10 = new fsM();
        fsM10.onCheckOut();
        fsM10.setElementMap(fyy_03);
        fsM10.setStyle("PopupInformation");
        fso4.addBasicElement(fsM10);
        fsM10.onAttributesInitialized();
        fsM fsM11 = fsM10;
        fqh_0 fqh_06 = (fqh_0)((fvE)fsM11).getAppearance();
        fqh_06.setElementMap(fyy_03);
        fqh_06.setAlignment(frs_0.d);
        fsM10.addBasicElement(fqh_06);
        fqh_06.onAttributesInitialized();
        fqh_06.onChildrenAdded();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_03);
        fiy_19.setAttribute("text");
        fiy_19.setField("fighterTransparency/key");
        fiy_19.setName("shortcutsList");
        fsM10.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        fiy_19.onChildrenAdded();
        fsM10.onChildrenAdded();
        fsM fsM12 = new fsM();
        fsM12.onCheckOut();
        fsM12.setElementMap(fyy_03);
        fsM12.setStyle("PopupInformation");
        fsM12.c(")");
        fso4.addBasicElement(fsM12);
        fsM12.onAttributesInitialized();
        fsM fsM13 = fsM12;
        fqh_0 fqh_07 = (fqh_0)((fvE)fsM13).getAppearance();
        fqh_07.setElementMap(fyy_03);
        fqh_07.setAlignment(frs_0.d);
        fsM12.addBasicElement(fqh_07);
        fqh_07.onAttributesInitialized();
        fqh_07.onChildrenAdded();
        fsM12.onChildrenAdded();
        fso4.onChildrenAdded();
        fil_13.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_03);
        fsk_03.setNonBlocking(true);
        fsk_03.setStyle("invisibleGuy");
        fup_02.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_03);
        fiy_110.setAttribute("modulationColor");
        fiy_110.setName("hideFightersDisabled");
        fsk_03.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_03);
        far_25.setElseValue("1,1,1,0.5");
        far_25.setValue("1,1,1");
        fiy_110.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fau_1 fau_15 = new fau_1();
        fau_15.onCheckOut();
        fau_15.setElementMap(fyy_03);
        far_25.addBasicElement(fau_15);
        fau_15.onAttributesInitialized();
        fau_15.onChildrenAdded();
        far_25.onChildrenAdded();
        fiy_110.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fup_02.onChildrenAdded();
        String string8 = "tacticalModeBtn";
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_03);
        if (fyy_03 != null && string8 != null) {
            fyy_03.a(string8, fru_03);
        }
        fru_03.setExpandable(false);
        fdt_1 fdt_14 = new fdt_1();
        fdt_14.a("wakfu.fightAction:tacticalViewNextMode()");
        fru_03.setOnClick(fdt_14);
        fde_2 fde_24 = new fde_2();
        fde_24.a("popup(descTacticalModePopup)");
        fru_03.setOnPopupDisplay(fde_24);
        fdf_2 fdf_24 = new fdf_2();
        fdf_24.a("closePopup");
        fru_03.setOnPopupHide(fdf_24);
        fru_03.setPrefSize(new fjf_2(33, 35));
        fru_03.setStyle("fightBar2");
        fso2.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        String string9 = "descTacticalModePopup";
        fil_1 fil_14 = new fil_1();
        fil_14.onCheckOut();
        fil_14.setElementMap(fyy_03);
        if (fyy_03 != null && string9 != null) {
            fyy_03.a(string9, fil_14);
        }
        fil_14.setAlign(frs_0.b);
        fil_14.setHotSpotPosition(frs_0.h);
        fru_03.addBasicElement(fil_14);
        fil_14.onAttributesInitialized();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setPrefSize(new fjf_2(10, 0));
        fso5.setStyle("popup");
        fil_14.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fii_2 fii_24 = fii_2.checkOut();
        fii_24.setElementMap(fyy_03);
        fii_24.setData(frg_0.a);
        fso5.addBasicElement(fii_24);
        fii_24.onAttributesInitialized();
        fii_24.onChildrenAdded();
        fsM fsM14 = new fsM();
        fsM14.onCheckOut();
        fsM14.setElementMap(fyy_03);
        fsM14.setStyle("PopupInformation");
        String string10 = "%desc.switchTacticalView% (";
        string10 = string10.replace("%desc.switchTacticalView%", fpm_0.b().c("desc.switchTacticalView"));
        fsM14.c(string10);
        fso5.addBasicElement(fsM14);
        fsM14.onAttributesInitialized();
        fsM fsM15 = fsM14;
        fqh_0 fqh_08 = (fqh_0)((fvE)fsM15).getAppearance();
        fqh_08.setElementMap(fyy_03);
        fqh_08.setAlignment(frs_0.d);
        fsM14.addBasicElement(fqh_08);
        fqh_08.onAttributesInitialized();
        fqh_08.onChildrenAdded();
        fsM14.onChildrenAdded();
        fsM fsM16 = new fsM();
        fsM16.onCheckOut();
        fsM16.setElementMap(fyy_03);
        fsM16.setStyle("PopupInformation");
        fso5.addBasicElement(fsM16);
        fsM16.onAttributesInitialized();
        fsM fsM17 = fsM16;
        fqh_0 fqh_09 = (fqh_0)((fvE)fsM17).getAppearance();
        fqh_09.setElementMap(fyy_03);
        fqh_09.setAlignment(frs_0.d);
        fsM16.addBasicElement(fqh_09);
        fqh_09.onAttributesInitialized();
        fqh_09.onChildrenAdded();
        fiy_1 fiy_111 = fiy_1.checkOut();
        fiy_111.setElementMap(fyy_03);
        fiy_111.setAttribute("text");
        fiy_111.setField("switchTacticalView/key");
        fiy_111.setName("shortcutsList");
        fsM16.addBasicElement(fiy_111);
        fiy_111.onAttributesInitialized();
        fiy_111.onChildrenAdded();
        fsM16.onChildrenAdded();
        fsM fsM18 = new fsM();
        fsM18.onCheckOut();
        fsM18.setElementMap(fyy_03);
        fsM18.setStyle("PopupInformation");
        fsM18.c(")");
        fso5.addBasicElement(fsM18);
        fsM18.onAttributesInitialized();
        fsM fsM19 = fsM18;
        fqh_0 fqh_010 = (fqh_0)((fvE)fsM19).getAppearance();
        fqh_010.setElementMap(fyy_03);
        fqh_010.setAlignment(frs_0.d);
        fsM18.addBasicElement(fqh_010);
        fqh_010.onAttributesInitialized();
        fqh_010.onChildrenAdded();
        fsM18.onChildrenAdded();
        fso5.onChildrenAdded();
        fil_14.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_03);
        fsk_04.setNonBlocking(true);
        fsk_04.setStyle("ICONSURFACE");
        fru_03.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fsk_04.onChildrenAdded();
        fru_03.onChildrenAdded();
        String string11 = "reportCellBtn";
        fru_0 fru_04 = new fru_0();
        fru_04.onCheckOut();
        fru_04.setElementMap(fyy_03);
        if (fyy_03 != null && string11 != null) {
            fyy_03.a(string11, fru_04);
        }
        fru_04.setExpandable(false);
        fdt_1 fdt_15 = new fdt_1();
        fdt_15.a("wakfu.fightAction:reportCell(reportCellBtn)");
        fru_04.setOnClick(fdt_15);
        fde_2 fde_25 = new fde_2();
        fde_25.a("popup(descReportCellPopup)");
        fru_04.setOnPopupDisplay(fde_25);
        fdf_2 fdf_25 = new fdf_2();
        fdf_25.a("closePopup");
        fru_04.setOnPopupHide(fdf_25);
        fru_04.setPrefSize(new fjf_2(33, 35));
        fru_04.setStyle("fightBar2");
        fso2.addBasicElement(fru_04);
        fru_04.onAttributesInitialized();
        this.a(fru_04);
        this.b(fru_04);
        this.c(fru_04);
        fru_04.onChildrenAdded();
        this.a(fso2);
        this.b(fso2);
        this.c(fso2);
        this.d(fso2);
        fso2.onChildrenAdded();
        fvM2.onChildrenAdded();
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fru_0 fru_02) {
        fyy_0 fyy_02 = this.a.peek();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("enabled");
        fiy_12.setName("cellReportDisabled");
        fru_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        far_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        return fiy_12;
    }

    public fyo b(fru_0 fru_02) {
        fyy_0 fyy_02 = this.a.peek();
        String string = "descReportCellPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fso2.setPrefSize(new fjf_2(10, 0));
        fso2.setStyle("popup");
        fil_12.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.a);
        fso2.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        String string2 = "%desc.reportCell% (";
        string2 = string2.replace("%desc.reportCell%", fpm_0.b().c("desc.reportCell"));
        fsM2.c(string2);
        fso2.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setStyle("PopupInformation");
        fso2.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlignment(frs_0.d);
        fsM4.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("reportCell/key");
        fiy_12.setName("shortcutsList");
        fsM4.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fsM4.onChildrenAdded();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_02);
        fsM6.setStyle("PopupInformation");
        fsM6.c(")");
        fso2.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fsM fsM7 = fsM6;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM7).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fqh_04.setAlignment(frs_0.d);
        fsM6.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fsM6.onChildrenAdded();
        fso2.onChildrenAdded();
        fil_12.onChildrenAdded();
        return fil_12;
    }

    public fyo c(fru_0 fru_02) {
        fyy_0 fyy_02 = this.a.peek();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("showTile");
        fru_02.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("modulationColor");
        fiy_12.setName("cellReportDisabled");
        fsk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        far_22.setElseValue("1,1,1,0.5");
        far_22.setValue("1,1,1");
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        far_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fsk_02.onChildrenAdded();
        return fsk_02;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        String string = "fightMarkerBtn";
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fru_02);
        }
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.fightAction:addFightMarker(fightMarkerBtn)");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(descFightMarkerPopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setPrefSize(new fjf_2(33, 35));
        fru_02.setStyle("fightBar2");
        fso2.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("enabled");
        fiy_12.setName("cellReportDisabled");
        fru_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        far_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        String string2 = "descFightMarkerPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setPrefSize(new fjf_2(10, 0));
        fso3.setStyle("popup");
        fil_12.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.a);
        fso3.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        String string3 = "%desc.addFightMarker% (";
        string3 = string3.replace("%desc.addFightMarker%", fpm_0.b().c("desc.addFightMarker"));
        fsM2.c(string3);
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setStyle("PopupInformation");
        fso3.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlignment(frs_0.d);
        fsM4.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("text");
        fiy_13.setField("reportCell/key");
        fiy_13.setName("shortcutsList");
        fsM4.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fsM4.onChildrenAdded();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_02);
        fsM6.setStyle("PopupInformation");
        fsM6.c(" ");
        fso3.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fsM6.onChildrenAdded();
        fsM fsM7 = new fsM();
        fsM7.onCheckOut();
        fsM7.setElementMap(fyy_02);
        fsM7.setStyle("PopupInformation");
        fso3.addBasicElement(fsM7);
        fsM7.onAttributesInitialized();
        fsM fsM8 = fsM7;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM8).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fqh_04.setAlignment(frs_0.d);
        fsM7.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("text");
        fiy_14.setField("reportCell/key");
        fiy_14.setName("shortcutsList");
        fsM7.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fsM7.onChildrenAdded();
        fsM fsM9 = new fsM();
        fsM9.onCheckOut();
        fsM9.setElementMap(fyy_02);
        fsM9.setStyle("PopupInformation");
        fsM9.c(")");
        fso3.addBasicElement(fsM9);
        fsM9.onAttributesInitialized();
        fsM fsM10 = fsM9;
        fqh_0 fqh_05 = (fqh_0)((fvE)fsM10).getAppearance();
        fqh_05.setElementMap(fyy_02);
        fqh_05.setAlignment(frs_0.d);
        fsM9.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqh_05.onChildrenAdded();
        fsM9.onChildrenAdded();
        fso3.onChildrenAdded();
        fil_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("AddFightMarker");
        fru_02.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(0, 0, 2, 0));
        fqp2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqp2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        String string = "lockFightBtn";
        fup_0 fup_02 = new fup_0();
        fup_02.onCheckOut();
        fup_02.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fup_02);
        }
        fup_02.setExpandable(false);
        fdc_2 fdc_22 = new fdc_2();
        fdc_22.a("wakfu.fightCreationOrPlacement:lockFight(lockFightBtn)");
        fup_02.setOnMouseRelease(fdc_22);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(descPadLocksPopup)");
        fup_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fup_02.setOnPopupHide(fdf_22);
        fup_02.setPrefSize(new fjf_2(33, 35));
        fup_02.setStyle("fightBar2");
        fso2.addBasicElement(fup_02);
        fup_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("selected");
        fiy_12.setName("currentFightLocked");
        fup_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("enabled");
        fiy_13.setName("isInFightCreationOrPlacement");
        fup_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_13.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fan_2 fan_22 = new fan_2();
        fan_22.onCheckOut();
        fan_22.setElementMap(fyy_02);
        far_22.addBasicElement(fan_22);
        fan_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        fan_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        fan_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("comparedValue");
        fiy_14.setName("lockFightDisabled");
        fau_12.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fau_12.onChildrenAdded();
        fan_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_13.onChildrenAdded();
        String string2 = "descPadLocksPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fup_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setPrefSize(new fjf_2(10, 0));
        fso3.setStyle("popup");
        fil_12.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.a);
        fso3.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("text");
        fiy_15.setName("currentFightLocked");
        fsM2.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        String string3 = "%desc.lockFight% (";
        string3 = string3.replace("%desc.lockFight%", fpm_0.b().c("desc.lockFight"));
        far_23.setElseValue(string3);
        String string4 = "%desc.unlockFight% (";
        string4 = string4.replace("%desc.unlockFight%", fpm_0.b().c("desc.unlockFight"));
        far_23.setValue(string4);
        fiy_15.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fai_1 fai_13 = new fai_1();
        fai_13.onCheckOut();
        fai_13.setElementMap(fyy_02);
        far_23.addBasicElement(fai_13);
        fai_13.onAttributesInitialized();
        fai_13.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_15.onChildrenAdded();
        fsM2.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setStyle("PopupInformation");
        fso3.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlignment(frs_0.d);
        fsM4.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_02);
        fiy_16.setAttribute("text");
        fiy_16.setField("lockFight/key");
        fiy_16.setName("shortcutsList");
        fsM4.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fsM4.onChildrenAdded();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_02);
        fsM6.setStyle("PopupInformation");
        fsM6.c(")");
        fso3.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fsM fsM7 = fsM6;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM7).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fqh_04.setAlignment(frs_0.d);
        fsM6.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fsM6.onChildrenAdded();
        fso3.onChildrenAdded();
        fil_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("lock");
        fup_02.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_02);
        fiy_17.setAttribute("modulationColor");
        fiy_17.setName("isInFightCreationOrPlacement");
        fsk_02.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_02);
        far_24.setElseValue("1,1,1,0.5");
        far_24.setValue("1,1,1");
        fiy_17.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fan_2 fan_23 = new fan_2();
        fan_23.onCheckOut();
        fan_23.setElementMap(fyy_02);
        far_24.addBasicElement(fan_23);
        fan_23.onAttributesInitialized();
        fai_1 fai_14 = new fai_1();
        fai_14.onCheckOut();
        fai_14.setElementMap(fyy_02);
        fan_23.addBasicElement(fai_14);
        fai_14.onAttributesInitialized();
        fai_14.onChildrenAdded();
        fau_1 fau_13 = new fau_1();
        fau_13.onCheckOut();
        fau_13.setElementMap(fyy_02);
        fan_23.addBasicElement(fau_13);
        fau_13.onAttributesInitialized();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_02);
        fiy_18.setAttribute("comparedValue");
        fiy_18.setName("lockFightDisabled");
        fau_13.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        fiy_18.onChildrenAdded();
        fau_13.onChildrenAdded();
        fan_23.onChildrenAdded();
        far_24.onChildrenAdded();
        fiy_17.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fup_02.onChildrenAdded();
        return fup_02;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(7, 10, 7, 10));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        return fqj2;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso2.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        return null;
    }
}

