/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cNk
 */
public class cnk_1
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        String string = "fightDialog";
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fvk_02);
        }
        fvk_02.setNonBlocking(true);
        fvk_02.setStyle("chat");
        fvk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setAlign(frk_0.j);
        fid_12.setInitValue(true);
        fid_12.setXOffset(-10);
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fso2.setNonBlocking(true);
        fso2.setPrefSize(new fjf_2(180, 100));
        fso2.setStyle("popup");
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso2.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_03);
        fqj2.setModulationColor(new azf_2(1.0f, 1.0f, 1.0f, 0.5f));
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqj2.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setNonBlocking(true);
        fso2.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fvM2.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fue_0 fue_02 = new fue_0();
        fue_02.onCheckOut();
        fue_02.setElementMap(fyy_03);
        fue_02.setNonBlocking(true);
        fue_02.setPrefSize(new fjf_2(150, 100));
        fvM2.addBasicElement(fue_02);
        fue_02.onAttributesInitialized();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setEnableOnlySelectablePartInteraction(true);
        fuk_02.setNonBlocking(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.chat:processLinkAction(fightDialog,chatView)");
        fuk_02.setOnClick(fdt_12);
        fdz_1 fdz_12 = new fdz_1();
        fdz_12.a("wakfu.chat:onMouseExitSelectableText(fightDialog)");
        fuk_02.setOnMouseExit(fdz_12);
        fda_1 fda_12 = new fda_1();
        fda_12.a("wakfu.chat:processLinkAction(fightDialog,chatView)");
        fuk_02.setOnMouseMove(fda_12);
        fuk_02.setPrefSize(new fjf_2(0, 100));
        fuk_02.setStyle("white14Bordered");
        fuk_02.setVerticalAlignment(fro_0.b);
        fue_02.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("text");
        fiy_12.setField("currentView/history");
        fiy_12.setLocal(true);
        fiy_12.setName("chat");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fue_02.onChildrenAdded();
        fvM2.onChildrenAdded();
        fvp_0 fvp_02 = new fvp_0();
        fvp_02.onCheckOut();
        fvp_02.setElementMap(fyy_03);
        fvp_02.setPointAlign(frs_0.b);
        fvp_02.setPrefSize(new fjf_2(0, 15));
        fso2.addBasicElement(fvp_02);
        fvp_02.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.c);
        fid_14.setSize(new fjf_2(100.0f, -2));
        fid_14.setYOffset(5);
        fvp_02.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fvp_0 fvp_03 = fvp_02;
        fqj fqj3 = ((fvE)fvp_03).getAppearance();
        fqj3.setElementMap(fyy_03);
        fvp_02.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 15, 0, 15));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fvp_02.onChildrenAdded();
        fvp_0 fvp_04 = new fvp_0();
        fvp_04.onCheckOut();
        fvp_04.setElementMap(fyy_03);
        fvp_04.setPointAlign(frs_0.h);
        fvp_04.setPrefSize(new fjf_2(0, 15));
        fso2.addBasicElement(fvp_04);
        fvp_04.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.o);
        fid_15.setSize(new fjf_2(100.0f, -2));
        fid_15.setYOffset(-5);
        fvp_04.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fvp_0 fvp_05 = fvp_04;
        fqj fqj4 = ((fvE)fvp_05).getAppearance();
        fqj4.setElementMap(fyy_03);
        fvp_04.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 15, 0, 15));
        fqj4.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fvp_04.onChildrenAdded();
        fvp_0 fvp_06 = new fvp_0();
        fvp_06.onCheckOut();
        fvp_06.setElementMap(fyy_03);
        fvp_06.setPointAlign(frs_0.f);
        fvp_06.setPrefSize(new fjf_2(10, 0));
        fso2.addBasicElement(fvp_06);
        fvp_06.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_03);
        fid_16.setAlign(frk_0.j);
        fid_16.setSize(new fjf_2(-2, 100.0f));
        fid_16.setXOffset(10);
        fvp_06.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fvp_06.onChildrenAdded();
        fvp_0 fvp_07 = new fvp_0();
        fvp_07.onCheckOut();
        fvp_07.setElementMap(fyy_03);
        fvp_07.setPointAlign(frs_0.d);
        fvp_07.setPrefSize(new fjf_2(15, 0));
        fso2.addBasicElement(fvp_07);
        fvp_07.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_03);
        fid_17.setAlign(frk_0.h);
        fid_17.setSize(new fjf_2(-2, 100.0f));
        fid_17.setXOffset(-5);
        fvp_07.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fvp_07.onChildrenAdded();
        fvp_0 fvp_08 = new fvp_0();
        fvp_08.onCheckOut();
        fvp_08.setElementMap(fyy_03);
        fvp_08.setPointAlign(frs_0.c);
        fvp_08.setPrefSize(new fjf_2(15, 15));
        fso2.addBasicElement(fvp_08);
        fvp_08.onAttributesInitialized();
        fid_1 fid_18 = new fid_1();
        fid_18.onCheckOut();
        fid_18.setElementMap(fyy_03);
        fid_18.setAlign(frk_0.e);
        fid_18.setSize(new fjf_2(-2, -2));
        fid_18.setXOffset(5);
        fid_18.setYOffset(5);
        fvp_08.addBasicElement(fid_18);
        fid_18.onAttributesInitialized();
        fid_18.onChildrenAdded();
        fvp_08.onChildrenAdded();
        fvp_0 fvp_09 = new fvp_0();
        fvp_09.onCheckOut();
        fvp_09.setElementMap(fyy_03);
        fvp_09.setPointAlign(frs_0.a);
        fvp_09.setPrefSize(new fjf_2(15, 15));
        fso2.addBasicElement(fvp_09);
        fvp_09.onAttributesInitialized();
        fid_1 fid_19 = new fid_1();
        fid_19.onCheckOut();
        fid_19.setElementMap(fyy_03);
        fid_19.setAlign(frk_0.a);
        fid_19.setSize(new fjf_2(-2, -2));
        fid_19.setXOffset(-5);
        fid_19.setYOffset(5);
        fvp_09.addBasicElement(fid_19);
        fid_19.onAttributesInitialized();
        fid_19.onChildrenAdded();
        fvp_09.onChildrenAdded();
        fvp_0 fvp_010 = new fvp_0();
        fvp_010.onCheckOut();
        fvp_010.setElementMap(fyy_03);
        fvp_010.setPointAlign(frs_0.i);
        fvp_010.setPrefSize(new fjf_2(15, 15));
        fso2.addBasicElement(fvp_010);
        fvp_010.onAttributesInitialized();
        fid_1 fid_110 = new fid_1();
        fid_110.onCheckOut();
        fid_110.setElementMap(fyy_03);
        fid_110.setAlign(frk_0.q);
        fid_110.setSize(new fjf_2(-2, -2));
        fid_110.setXOffset(5);
        fid_110.setYOffset(-5);
        fvp_010.addBasicElement(fid_110);
        fid_110.onAttributesInitialized();
        fid_110.onChildrenAdded();
        fvp_010.onChildrenAdded();
        fvp_0 fvp_011 = new fvp_0();
        fvp_011.onCheckOut();
        fvp_011.setElementMap(fyy_03);
        fvp_011.setPointAlign(frs_0.g);
        fvp_011.setPrefSize(new fjf_2(15, 15));
        fso2.addBasicElement(fvp_011);
        fvp_011.onAttributesInitialized();
        fid_1 fid_111 = new fid_1();
        fid_111.onCheckOut();
        fid_111.setElementMap(fyy_03);
        fid_111.setAlign(frk_0.m);
        fid_111.setSize(new fjf_2(-2, -2));
        fid_111.setXOffset(-5);
        fid_111.setYOffset(-5);
        fvp_011.addBasicElement(fid_111);
        fid_111.onAttributesInitialized();
        fid_111.onChildrenAdded();
        fvp_011.onChildrenAdded();
        fso2.onChildrenAdded();
        fvk_02.onChildrenAdded();
        return fvk_02;
    }
}

