/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cNK
 */
public class cnk_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        String string = "resourcesCollectorWindow";
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fvk_02);
        }
        fvk_02.setPack(true);
        fvk_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvk_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("windowNew");
        fvk_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(10, 5, 12, 5));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setExpandable(false);
        fso3.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fvM fvM3 = fvM2;
        fqj fqj3 = ((fvE)fvM3).getAppearance();
        fqj3.setElementMap(fyy_03);
        fvM2.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 10, 0, 10));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setStyle("titleBar");
        fvM2.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso fso6 = fso5;
        fqj fqj4 = ((fvE)fso6).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso5.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(3, 20, 3, 20));
        fqj4.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.e);
        fso7.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("StyledBold16White");
        String string2 = "%havenWorld.resourcesCollector%";
        string2 = string2.replace("%havenWorld.resourcesCollector%", fpm_0.b().c("havenWorld.resourcesCollector"));
        fsM2.c(string2);
        fso7.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        fvM2.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso3.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj5 = ((fvE)fso9).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso8.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 12, 0, 12));
        fqj5.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj5.onChildrenAdded();
        String string3 = "windowContentContainer";
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fso10);
        }
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso10.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.b);
        fin_24.setHorizontal(false);
        fso11.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        fso11.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso12.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso13 = fso12;
        fqj fqj6 = ((fvE)fso13).getAppearance();
        fqj6.setElementMap(fyy_03);
        fso12.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_03);
        fqo_04.setInsets(new Insets(5, 0, 0, 0));
        fqj6.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj6.onChildrenAdded();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_03);
        fso14.setExpandable(false);
        fso12.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(100.0f, 100.0f));
        fso14.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fso fso15 = fso14;
        fqj fqj7 = ((fvE)fso15).getAppearance();
        fqj7.setElementMap(fyy_03);
        fso14.addBasicElement(fqj7);
        fqj7.onAttributesInitialized();
        fqo_0 fqo_05 = new fqo_0();
        fqo_05.onCheckOut();
        fqo_05.setElementMap(fyy_03);
        fqo_05.setInsets(new Insets(20, 0, 20, 0));
        fqj7.addBasicElement(fqo_05);
        fqo_05.onAttributesInitialized();
        fqo_05.onChildrenAdded();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(0, 20, 0, 20));
        fqj7.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqj7.onChildrenAdded();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_03);
        fso16.setExpandable(false);
        fso16.setStyle("tiledScroll");
        fso14.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        fso fso17 = fso16;
        fqj fqj8 = ((fvE)fso17).getAppearance();
        fqj8.setElementMap(fyy_03);
        fso16.addBasicElement(fqj8);
        fqj8.onAttributesInitialized();
        fqo_0 fqo_06 = new fqo_0();
        fqo_06.onCheckOut();
        fqo_06.setElementMap(fyy_03);
        fqo_06.setInsets(new Insets(5, 20, 10, 20));
        fqj8.addBasicElement(fqo_06);
        fqo_06.onAttributesInitialized();
        fqo_06.onChildrenAdded();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(0, 0, 0, 0));
        fqj8.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqj8.onChildrenAdded();
        fso fso18 = fso.checkOut();
        fso18.setElementMap(fyy_03);
        fso16.addBasicElement(fso18);
        fso18.onAttributesInitialized();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setAlign(frs_0.b);
        fin_25.setHorizontal(false);
        fso18.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fso fso19 = fso.checkOut();
        fso19.setElementMap(fyy_03);
        fso19.setExpandable(false);
        fso19.setPrefSize(new fjf_2(0, 30));
        fso19.setStyle("EncyclopediaSplashTitle");
        fso18.addBasicElement(fso19);
        fso19.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_03);
        fip_23.setAlign(frs_0.e);
        fso19.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fso fso20 = fso19;
        fqj fqj9 = ((fvE)fso20).getAppearance();
        fqj9.setElementMap(fyy_03);
        fso19.addBasicElement(fqj9);
        fqj9.onAttributesInitialized();
        fqo_0 fqo_07 = new fqo_0();
        fqo_07.onCheckOut();
        fqo_07.setElementMap(fyy_03);
        fqo_07.setInsets(new Insets(0, 0, 3, 0));
        fqj9.addBasicElement(fqo_07);
        fqo_07.onAttributesInitialized();
        fqo_07.onChildrenAdded();
        fqj9.onChildrenAdded();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setAlign(frs_0.e);
        fso19.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setDisplaySize(new fjf_2(83, 39));
        fsk_02.setExpandable(false);
        fsk_02.setStyle("NationLeftDecorator");
        fso19.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_02.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(250);
        fuk_02.setMinWidth(1);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("StyledBold16White");
        String string4 = "%desc.howDoesItWorks%";
        string4 = string4.replace("%desc.howDoesItWorks%", fpm_0.b().c("desc.howDoesItWorks"));
        fuk_02.c(string4);
        fso19.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_02.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_03);
        fsk_03.setDisplaySize(new fjf_2(83, 39));
        fsk_03.setExpandable(false);
        fsk_03.setStyle("NationRightDecorator");
        fso19.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fsk_03.onChildrenAdded();
        fso19.onChildrenAdded();
        fso fso21 = fso.checkOut();
        fso21.setElementMap(fyy_03);
        fso21.setExpandable(false);
        fso18.addBasicElement(fso21);
        fso21.onAttributesInitialized();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_03);
        fsk_04.setExpandable(false);
        fsk_04.setStyle("ResourcesCollectorIllu");
        fso21.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fsk_04.onChildrenAdded();
        fuk_0 fuk_03 = new fuk_0();
        fuk_03.onCheckOut();
        fuk_03.setElementMap(fyy_03);
        fuk_03.setExpandable(false);
        fuk_03.setMaxWidth(283);
        fuk_03.setMinWidth(1);
        fuk_03.setMultiline(true);
        fuk_03.setStyle("darkBold");
        String string5 = "%desc.resourcesCollectorHowTo%";
        string5 = string5.replace("%desc.resourcesCollectorHowTo%", fpm_0.b().c("desc.resourcesCollectorHowTo"));
        fuk_03.c(string5);
        fso21.addBasicElement(fuk_03);
        fuk_03.onAttributesInitialized();
        fuk_03.onChildrenAdded();
        fso21.onChildrenAdded();
        fso18.onChildrenAdded();
        fso16.onChildrenAdded();
        fso14.onChildrenAdded();
        fso fso22 = fso.checkOut();
        fso22.setElementMap(fyy_03);
        fso22.setNonBlocking(true);
        fso22.setStyle("EncyclopediaPane");
        fso12.addBasicElement(fso22);
        fso22.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.c);
        fid_15.setSize(new fjf_2(100.0f, 100.0f));
        fso22.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fso22.onChildrenAdded();
        fso12.onChildrenAdded();
        fso fso23 = fso.checkOut();
        fso23.setElementMap(fyy_03);
        fso23.setStyle("titleBar");
        fso11.addBasicElement(fso23);
        fso23.onAttributesInitialized();
        fso fso24 = fso23;
        fqj fqj10 = ((fvE)fso24).getAppearance();
        fqj10.setElementMap(fyy_03);
        fso23.addBasicElement(fqj10);
        fqj10.onAttributesInitialized();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_03);
        fqm_06.setInsets(new Insets(0, 10, 0, 10));
        fqj10.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqo_0 fqo_08 = new fqo_0();
        fqo_08.onCheckOut();
        fqo_08.setElementMap(fyy_03);
        fqo_08.setInsets(new Insets(2, 20, 0, 20));
        fqj10.addBasicElement(fqo_08);
        fqo_08.onAttributesInitialized();
        fqo_08.onChildrenAdded();
        fqj10.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_03);
        fsM4.setExpandable(false);
        fsM4.setNonBlocking(true);
        fsM4.setStyle("StyledBold16White");
        String string6 = "%desc.storageZone%";
        string6 = string6.replace("%desc.storageZone%", fpm_0.b().c("desc.storageZone"));
        fsM4.c(string6);
        fso23.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fqh_03.setAlign(frs_0.e);
        fsM4.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso23.onChildrenAdded();
        fso fso25 = fso.checkOut();
        fso25.setElementMap(fyy_03);
        fso11.addBasicElement(fso25);
        fso25.onAttributesInitialized();
        fso fso26 = fso25;
        fqj fqj11 = ((fvE)fso26).getAppearance();
        fqj11.setElementMap(fyy_03);
        fso25.addBasicElement(fqj11);
        fqj11.onAttributesInitialized();
        fqm_0 fqm_07 = fqm_0.checkOut();
        fqm_07.setElementMap(fyy_03);
        fqm_07.setInsets(new Insets(0, 10, 0, 10));
        fqj11.addBasicElement(fqm_07);
        fqm_07.onAttributesInitialized();
        fqm_07.onChildrenAdded();
        fqj11.onChildrenAdded();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fic_14.setAdaptToContentSize(true);
        fso25.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        fso fso27 = fso.checkOut();
        fso27.setElementMap(fyy_03);
        fso27.setStyle("caracs");
        fso25.addBasicElement(fso27);
        fso27.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_03);
        fid_16.setAlign(frk_0.i);
        fid_16.setSize(new fjf_2(100.0f, 100.0f));
        fso27.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fso fso28 = fso27;
        fqj fqj12 = ((fvE)fso28).getAppearance();
        fqj12.setElementMap(fyy_03);
        fqj12.setModulationColor(new azf_2(0.9f, 0.9f, 0.9f, 1.0f));
        fso27.addBasicElement(fqj12);
        fqj12.onAttributesInitialized();
        fqm_0 fqm_08 = fqm_0.checkOut();
        fqm_08.setElementMap(fyy_03);
        fqm_08.setInsets(new Insets(0, 0, 0, 0));
        fqj12.addBasicElement(fqm_08);
        fqm_08.onAttributesInitialized();
        fqm_08.onChildrenAdded();
        fqj12.onChildrenAdded();
        fso27.onChildrenAdded();
        fso fso29 = fso.checkOut();
        fso29.setElementMap(fyy_03);
        fso29.setExpandable(false);
        fso25.addBasicElement(fso29);
        fso29.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_03);
        fid_17.setAlign(frk_0.i);
        fid_17.setSize(new fjf_2(100.0f, 100.0f));
        fid_17.setXOffset(3);
        fso29.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fso fso30 = fso29;
        fqj fqj13 = ((fvE)fso30).getAppearance();
        fqj13.setElementMap(fyy_03);
        fso29.addBasicElement(fqj13);
        fqj13.onAttributesInitialized();
        fqm_0 fqm_09 = fqm_0.checkOut();
        fqm_09.setElementMap(fyy_03);
        fqm_09.setInsets(new Insets(7, 1, 5, 0));
        fqj13.addBasicElement(fqm_09);
        fqm_09.onAttributesInitialized();
        fqm_09.onChildrenAdded();
        fqj13.onChildrenAdded();
        String string7 = "itemList";
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_03);
        if (fyy_03 != null && string7 != null) {
            fyy_03.a(string7, fsQ2);
        }
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(40, 40));
        fsQ2.setHorizontal(false);
        fsQ2.setIdealSizeMaxColumns(11);
        fsQ2.setIdealSizeMaxRows(4);
        fsQ2.setIdealSizeMinColumns(11);
        fsQ2.setIdealSizeMinRows(4);
        fsQ2.setScrollBarBehaviour(fra_0.c);
        fsQ2.setSelectionTogglable(false);
        fso29.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        this.a(fsQ2);
        this.b(fsQ2);
        this.c(fsQ2);
        this.d(fsQ2);
        fsQ2.onChildrenAdded();
        fso29.onChildrenAdded();
        fso25.onChildrenAdded();
        this.a(fso11);
        fso11.onChildrenAdded();
        fso10.onChildrenAdded();
        fso8.onChildrenAdded();
        fso3.onChildrenAdded();
        this.a(fvk_02);
        this.b(fvk_02);
        this.c(fvk_02);
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fsQ fsQ2) {
        fyy_0 fyy_02 = this.a.peek();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.d);
        fsQ2.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        return fip_22;
    }

    public fyo b(fsQ fsQ2) {
        fyy_0 fyy_02 = this.a.peek();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("itemList");
        fiy_12.setName("havenWorldResourcesCollector");
        fsQ2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        return fiy_12;
    }

    public fyo c(fsQ fsQ2) {
        fyy_0 fyy_02 = this.a.peek();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fdb_2 fdb_22 = new fdb_2();
        fdb_22.a("wakfu.havenWorldResourcesCollector:dragItem");
        faf_22.setOnDrag(fdb_22);
        fde_1 fde_12 = new fde_1();
        fde_12.a("wakfu.havenWorldResourcesCollector:dropItem");
        faf_22.setOnDrop(fde_12);
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.a("wakfu.havenWorldResourcesCollector:removeItem");
        faf_22.setOnDropOut(fdf_12);
        fdi_1 fdi_12 = new fdi_1();
        fdi_12.a("wakfu.equipment:openItemDetailWindow(resourcesCollectorWindow)");
        faf_22.setOnItemClick(fdi_12);
        fdj_1 fdj_12 = new fdj_1();
        fdj_12.a("wakfu.havenWorldResourcesCollector:onItemDoubleClick");
        faf_22.setOnItemDoubleClick(fdj_12);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        String string = "currentItem";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fij_12);
        }
        faf_22.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("value");
        fij_12.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        faf_22.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso2.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        String string2 = "itemContainer";
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fso3);
        }
        fso3.setNonBlocking(false);
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.a("wakfu.havenWorldResourcesCollector:changeItemBackground(currentItem,itemPopup)");
        fso3.setOnMouseEnter(fdy_12);
        fdz_1 fdz_12 = new fdz_1();
        fdz_12.a("wakfu.havenWorldResourcesCollector:changeItemBackground(currentItem,itemPopup)");
        fso3.setOnMouseExit(fdz_12);
        fso3.setStyle("itemBackground");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(43, 43));
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        String string3 = "itemPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string3 != null) {
            fyy_02.a(string3, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fso3.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setPrefSize(new fjf_2(10, 0));
        fso4.setStyle("popup");
        fil_12.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.a);
        fso4.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("visible");
        fir_13.setField("name");
        fso4.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        fir_13.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fay_1 fay_12 = new fay_1();
        fay_12.onCheckOut();
        fay_12.setElementMap(fyy_02);
        far_23.addBasicElement(fay_12);
        fay_12.onAttributesInitialized();
        fat_2 fat_22 = new fat_2();
        fat_22.onCheckOut();
        fat_22.setElementMap(fyy_02);
        fat_22.setValue("");
        fay_12.addBasicElement(fat_22);
        fat_22.onAttributesInitialized();
        fat_22.onChildrenAdded();
        fay_12.onChildrenAdded();
        far_23.onChildrenAdded();
        fir_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso4.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setStyle("PopupInformation");
        fso4.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("text");
        fir_14.setField("name");
        fsM2.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso4.onChildrenAdded();
        fil_12.onChildrenAdded();
        fsv_0 fsv_02 = new fsv_0();
        fsv_02.onCheckOut();
        fsv_02.setElementMap(fyy_02);
        fde_1 fde_13 = new fde_1();
        fde_13.a("wakfu.havenWorldResourcesCollector:removeItem");
        fsv_02.setOnDrop(fde_13);
        fso3.addBasicElement(fsv_02);
        fsv_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("dragEnabled");
        fiy_12.setName("recycleRunning");
        fsv_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        far_24.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_24.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fsv_02.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(38, 38));
        fsk_02.setNonBlocking(true);
        fsv_02.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fsk_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("texture");
        fir_15.setField("iconUrl");
        fqv2.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setNonBlocking(true);
        fsM4.setStyle("White10Bordered");
        fsv_02.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_02);
        fir_16.setAttribute("visible");
        fir_16.setField("quantity");
        fsM4.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_02);
        fir_16.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fam_1 fam_12 = new fam_1();
        fam_12.onCheckOut();
        fam_12.setElementMap(fyy_02);
        fam_12.setValue("1");
        far_25.addBasicElement(fam_12);
        fam_12.onAttributesInitialized();
        fam_12.onChildrenAdded();
        far_25.onChildrenAdded();
        fir_16.onChildrenAdded();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.m);
        fsM4.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fsM fsM5 = fsM4;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fsM4.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 6, 6, 0));
        fqh_03.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fir_1 fir_17 = new fir_1();
        fir_17.onCheckOut();
        fir_17.setElementMap(fyy_02);
        fir_17.setAttribute("text");
        fir_17.setField("quantity");
        fsM4.addBasicElement(fir_17);
        fir_17.onAttributesInitialized();
        fir_17.onChildrenAdded();
        fsM4.onChildrenAdded();
        fsv_02.onChildrenAdded();
        fso3.onChildrenAdded();
        fso2.onChildrenAdded();
        faf_22.onChildrenAdded();
        return faf_22;
    }

    public fyo d(fsQ fsQ2) {
        fyy_0 fyy_02 = this.a.peek();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fde_1 fde_12 = new fde_1();
        fde_12.a("wakfu.havenWorldResourcesCollector:dropItem");
        faf_22.setOnDrop(fde_12);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fac_1 fac_12 = new fac_1();
        fac_12.onCheckOut();
        fac_12.setElementMap(fyy_02);
        fav_12.addBasicElement(fac_12);
        fac_12.onAttributesInitialized();
        fac_12.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        faf_22.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fsv_0 fsv_02 = new fsv_0();
        fsv_02.onCheckOut();
        fsv_02.setElementMap(fyy_02);
        fsv_02.setDragEnabled(false);
        fde_1 fde_13 = new fde_1();
        fde_13.a("wakfu.havenWorldResourcesCollector:removeItem");
        fsv_02.setOnDrop(fde_13);
        fso2.addBasicElement(fsv_02);
        fsv_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fsv_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        String string = "itemBackgroundContainer";
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fso3);
        }
        fso3.setStyle("itemBackground");
        fsv_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(43, 43));
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso3.onChildrenAdded();
        fsv_02.onChildrenAdded();
        fso2.onChildrenAdded();
        faf_22.onChildrenAdded();
        return faf_22;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setStyle("darkBackgrounded");
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso4;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso4.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 10, 0, 30));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(0, 0, 2, 0));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, -2));
        fso4.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso4.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setExpandable(false);
        fsk_02.setStyle("HavenWorldResourcesPoints");
        fso4.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.h);
        fsk_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 0, 0, 5));
        fqp2.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqp2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso6.setExpandable(false);
        fso6.setPrefSize(new fjf_2(367, 0));
        fso4.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.b);
        fin_23.setHorizontal(false);
        fso6.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setExpandable(false);
        fsM2.setStyle("whiteBold");
        String string = "%havenWorldResourcesCollector.resourcesQuantity%";
        string = string.replace("%havenWorldResourcesCollector.resourcesQuantity%", fpm_0.b().c("havenWorldResourcesCollector.resourcesQuantity"));
        fsM2.c(string);
        fso6.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(2, 0, 5, 0));
        fqh_02.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso7.setExpandable(false);
        fso6.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso7.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso8 = fso7;
        fqj fqj3 = ((fvE)fso8).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso7.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fbf_1 fbf_12 = new fbf_1();
        fbf_12.onCheckOut();
        fbf_12.setElementMap(fyy_02);
        fbf_12.setColor(new azf_2(0.0f, 0.0f, 0.0f, 1.0f));
        fqj3.addBasicElement(fbf_12);
        fbf_12.onAttributesInitialized();
        fbf_12.onChildrenAdded();
        fqj3.onChildrenAdded();
        ftv ftv2 = new ftv();
        ftv2.onCheckOut();
        ftv2.setElementMap(fyy_02);
        ftv2.setNonBlocking(false);
        ftv2.setStyle("XP2Wakfu");
        ftv2.setTweenDuration(1000L);
        ftv2.setUseDecreaseProgressTween(false);
        fso7.addBasicElement(ftv2);
        ftv2.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(100.0f, 20));
        fid_13.setXOffset(1);
        ftv2.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("value");
        fiy_12.setField("resourcesQuantityValue");
        fiy_12.setName("havenWorldResourcesCollector");
        ftv2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        ftv2.onChildrenAdded();
        ftv ftv3 = new ftv();
        ftv3.onCheckOut();
        ftv3.setElementMap(fyy_02);
        ftv3.setNonBlocking(true);
        ftv3.setStyle("XP2");
        ftv3.setTweenDuration(1000L);
        ftv3.setUseDecreaseProgressTween(false);
        fso7.addBasicElement(ftv3);
        ftv3.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(100.0f, 20));
        fid_14.setXOffset(1);
        ftv3.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("value");
        fiy_13.setField("baseResourcesQuantityValue");
        fiy_13.setName("havenWorldResourcesCollector");
        ftv3.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        ftv3.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_02);
        fso9.setPrefSize(new fjf_2(0, 11));
        fso9.setStyle("ProgressBar");
        fso7.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setAlign(frk_0.i);
        fid_15.setSize(new fjf_2(100.0f, 20));
        fso9.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fso9.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setStyle("White10Bordered");
        fso7.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_02);
        fid_16.setAlign(frk_0.i);
        fid_16.setSize(new fjf_2(100.0f, 20));
        fuk_02.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlignment(frs_0.e);
        fuk_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("text");
        fiy_14.setField("resourcesQuantityText");
        fiy_14.setName("havenWorldResourcesCollector");
        fuk_02.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso7.onChildrenAdded();
        fso6.onChildrenAdded();
        fso4.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_02);
        fso3.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_02);
        fid_17.setAlign(frk_0.q);
        fso10.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fic_14.setAdaptToContentSize(true);
        fso10.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        String string2 = "startButton";
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fru_02);
        }
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.havenWorldResourcesCollector:validCollect");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(startButtonPopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setStyle("StartCraft");
        fso10.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_18 = new fid_1();
        fid_18.onCheckOut();
        fid_18.setElementMap(fyy_02);
        fid_18.setAlign(frk_0.i);
        fru_02.addBasicElement(fid_18);
        fid_18.onAttributesInitialized();
        fid_18.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("enabled");
        fiy_15.setField("validEnabled");
        fiy_15.setName("havenWorldResourcesCollector");
        fru_02.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        String string3 = "startButtonPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string3 != null) {
            fyy_02.a(string3, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_02);
        fso11.setPrefSize(new fjf_2(10, 0));
        fso11.setStyle("popup");
        fil_12.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.d);
        fso11.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_02);
        fuk_04.setExpandable(false);
        fuk_04.setStyle("White11");
        String string4 = "%desc.collect%";
        string4 = string4.replace("%desc.collect%", fpm_0.b().c("desc.collect"));
        fuk_04.c(string4);
        fso11.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fuk_0 fuk_05 = fuk_04;
        fqh_0 fqh_04 = (fqh_0)((fvE)fuk_05).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fqh_04.setAlignment(frs_0.d);
        fuk_04.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fso11.onChildrenAdded();
        fil_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        fsk_04.setNonBlocking(true);
        fsk_04.setStyle("recycle");
        fso10.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fid_1 fid_19 = new fid_1();
        fid_19.onCheckOut();
        fid_19.setElementMap(fyy_02);
        fid_19.setAlign(frk_0.i);
        fid_19.setSize(new fjf_2(-2, -2));
        fid_19.setXOffset(-2);
        fsk_04.addBasicElement(fid_19);
        fid_19.onAttributesInitialized();
        fid_19.onChildrenAdded();
        fsk_0 fsk_05 = fsk_04;
        fqp fqp3 = (fqp)((fvE)fsk_05).getAppearance();
        fqp3.setElementMap(fyy_02);
        fsk_04.addBasicElement(fqp3);
        fqp3.onAttributesInitialized();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_02);
        fiy_16.setAttribute("modulationColor");
        fiy_16.setField("validEnabled");
        fiy_16.setName("havenWorldResourcesCollector");
        fqp3.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        far_22.setElseValue("1,1,1,0.5");
        far_22.setValue("1,1,1,1");
        fiy_16.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_16.onChildrenAdded();
        fqp3.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fso10.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo a(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo b(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fru_02.setStyle("close");
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.havenWorldResourcesCollector:closeWindow");
        fru_02.setOnClick(fdt_12);
        fvk_02.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setSize(new fjf_2(-2, -2));
        fid_12.setXOffset(-18);
        fid_12.setYOffset(-12);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo c(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.h);
        fid_12.setInitValue(true);
        fid_12.setSize(new fjf_2(-2, -2));
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }
}

