/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cOm
 */
public class com_1
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fso2.setVisible(false);
        fso2.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fso2.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("visible");
        fiy_12.setName("itemPopupDetail");
        fso2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setExpandable(false);
        fso3.setPrefSize(new fjf_2(250, 0));
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(6, 6, 6, 6));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fbf_1 fbf_12 = new fbf_1();
        fbf_12.onCheckOut();
        fbf_12.setElementMap(fyy_03);
        fbf_12.setColor(new azf_2(0.0f, 0.0f, 0.0f, 0.9f));
        fqj2.addBasicElement(fbf_12);
        fbf_12.onAttributesInitialized();
        fbf_12.onChildrenAdded();
        fqj2.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.b);
        fin_23.setHorizontal(false);
        fso3.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setExpandable(false);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fso5.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_03);
        fso5.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setAlign(frs_0.b);
        fin_25.setHorizontal(false);
        fso6.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setExpandable(false);
        fsM2.setStyle("bigTitle");
        fso6.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("text");
        fiy_13.setField("name");
        fiy_13.setName("itemPopupDetail");
        fsM2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso6.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.d);
        fso7.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setMultiline(false);
        fuk_02.setStyle("white11");
        fso7.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("text");
        fiy_14.setField("type");
        fiy_14.setName("itemPopupDetail");
        fuk_02.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso7.onChildrenAdded();
        fso6.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso8.setExpandable(false);
        fso5.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj3 = ((fvE)fso9).getAppearance();
        fqj3.setElementMap(fyy_03);
        fso8.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(3, 0, 0, 0));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setAlign(frs_0.b);
        fin_26.setHorizontal(false);
        fso8.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        fuk_0 fuk_03 = new fuk_0();
        fuk_03.onCheckOut();
        fuk_03.setElementMap(fyy_03);
        fuk_03.setExpandable(false);
        fuk_03.setStyle("white11");
        fso8.addBasicElement(fuk_03);
        fuk_03.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_03);
        fip_23.setAlign(frs_0.f);
        fuk_03.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("text");
        fiy_15.setField("levelDescription");
        fiy_15.setName("itemPopupDetail");
        fuk_03.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fuk_03.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        fso10.setExpandable(false);
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fip_2 fip_24 = new fip_2();
        fip_24.onCheckOut();
        fip_24.setElementMap(fyy_03);
        fip_24.setAlign(frs_0.f);
        fso10.addBasicElement(fip_24);
        fip_24.onAttributesInitialized();
        fip_24.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("visible");
        fiy_16.setField("ap");
        fiy_16.setName("itemPopupDetail");
        fso10.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        fiy_16.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        faa_2 faa_22 = new faa_2();
        faa_22.onCheckOut();
        faa_22.setElementMap(fyy_03);
        faa_22.setValue("0");
        far_23.addBasicElement(faa_22);
        faa_22.onAttributesInitialized();
        faa_22.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_16.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setExpandable(false);
        fsk_02.setStyle("iconAP");
        fso10.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_02.onChildrenAdded();
        fsM fsM3 = new fsM();
        fsM3.onCheckOut();
        fsM3.setElementMap(fyy_03);
        fsM3.setStyle("11Light");
        fso10.addBasicElement(fsM3);
        fsM3.onAttributesInitialized();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_03);
        fiy_17.setAttribute("text");
        fiy_17.setField("ap");
        fiy_17.setName("itemPopupDetail");
        fsM3.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        fsM3.onChildrenAdded();
        fso10.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso11.setExpandable(false);
        fso8.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fip_2 fip_25 = new fip_2();
        fip_25.onCheckOut();
        fip_25.setElementMap(fyy_03);
        fip_25.setAlign(frs_0.f);
        fso11.addBasicElement(fip_25);
        fip_25.onAttributesInitialized();
        fip_25.onChildrenAdded();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_03);
        fiy_18.setAttribute("visible");
        fiy_18.setField("range");
        fiy_18.setName("itemPopupDetail");
        fso11.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_03);
        fiy_18.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_03);
        far_24.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_24.onChildrenAdded();
        fiy_18.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_03);
        fsk_03.setExpandable(false);
        fsk_03.setStyle("smallSword");
        fso11.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fsk_03.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_03);
        fsM4.setStyle("11Light");
        fso11.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_03);
        fiy_19.setAttribute("text");
        fiy_19.setField("range");
        fiy_19.setName("itemPopupDetail");
        fsM4.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        fiy_19.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso11.onChildrenAdded();
        fso8.onChildrenAdded();
        fso5.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        fso12.setExpandable(false);
        fso3.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_03);
        fiy_110.setAttribute("visible");
        fiy_110.setField("effect");
        fiy_110.setName("itemPopupDetail");
        fso12.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_03);
        far_25.setElseValue("true");
        far_25.setValue("false");
        fiy_110.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fat_2 fat_22 = new fat_2();
        fat_22.onCheckOut();
        fat_22.setElementMap(fyy_03);
        fat_22.setValue("");
        far_25.addBasicElement(fat_22);
        fat_22.onAttributesInitialized();
        fat_22.onChildrenAdded();
        far_25.onChildrenAdded();
        fiy_110.onChildrenAdded();
        fin_2 fin_27 = fin_2.checkOut();
        fin_27.setHorizontal(false);
        fso12.addBasicElement(fin_27);
        fin_27.onAttributesInitialized();
        fin_27.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_03);
        fso13.setExpandable(false);
        fso13.setPrefSize(new fjf_2(0, 7));
        fso13.setStyle("lineSeparator");
        fso12.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fso fso14 = fso13;
        fqj fqj4 = ((fvE)fso14).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso13.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(5, 0, 2, 0));
        fqj4.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fso13.onChildrenAdded();
        fsM fsM5 = new fsM();
        fsM5.onCheckOut();
        fsM5.setElementMap(fyy_03);
        fsM5.setExpandable(false);
        fsM5.setStyle("11");
        String string = "%effects.characteristics%";
        string = string.replace("%effects.characteristics%", fpm_0.b().c("effects.characteristics"));
        fsM5.c(string);
        fso12.addBasicElement(fsM5);
        fsM5.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_03);
        fii_22.setData(frg_0.a);
        fsM5.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM6 = fsM5;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM6).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fsM5.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_03);
        fqg_02.setColor(new azf_2(1.0f, 1.0f, 1.0f, 1.0f));
        fqh_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(0, 5, 5, 0));
        fqh_02.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fsM5.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_03);
        fuk_04.setMinWidth(230);
        fuk_04.setStyle("white11");
        fso12.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fiy_1 fiy_111 = fiy_1.checkOut();
        fiy_111.setElementMap(fyy_03);
        fiy_111.setAttribute("visible");
        fiy_111.setField("effectDetails");
        fiy_111.setName("itemPopupDetail");
        fuk_04.addBasicElement(fiy_111);
        fiy_111.onAttributesInitialized();
        far_2 far_26 = new far_2();
        far_26.onCheckOut();
        far_26.setElementMap(fyy_03);
        far_26.setElseValue("true");
        far_26.setValue("false");
        fiy_111.addBasicElement(far_26);
        far_26.onAttributesInitialized();
        fae_2 fae_22 = new fae_2();
        fae_22.onCheckOut();
        fae_22.setElementMap(fyy_03);
        far_26.addBasicElement(fae_22);
        fae_22.onAttributesInitialized();
        fat_2 fat_23 = new fat_2();
        fat_23.onCheckOut();
        fat_23.setElementMap(fyy_03);
        fat_23.setValue("");
        fae_22.addBasicElement(fat_23);
        fat_23.onAttributesInitialized();
        fat_23.onChildrenAdded();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_03);
        fae_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fiy_1 fiy_112 = fiy_1.checkOut();
        fiy_112.setElementMap(fyy_03);
        fiy_112.setAttribute("comparedValue");
        fiy_112.setName("isFromEquipedShortcut");
        fai_12.addBasicElement(fiy_112);
        fiy_112.onAttributesInitialized();
        fiy_112.onChildrenAdded();
        fai_12.onChildrenAdded();
        fai_1 fai_13 = new fai_1();
        fai_13.onCheckOut();
        fai_13.setElementMap(fyy_03);
        fae_22.addBasicElement(fai_13);
        fai_13.onAttributesInitialized();
        fiy_1 fiy_113 = fiy_1.checkOut();
        fiy_113.setElementMap(fyy_03);
        fiy_113.setAttribute("comparedValue");
        fiy_113.setName("isFromShortcut");
        fai_13.addBasicElement(fiy_113);
        fiy_113.onAttributesInitialized();
        fiy_113.onChildrenAdded();
        fai_13.onChildrenAdded();
        fae_22.onChildrenAdded();
        far_26.onChildrenAdded();
        fiy_111.onChildrenAdded();
        fuk_0 fuk_05 = fuk_04;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_05).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fuk_04.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(0, 20, 0, 0));
        fqh_03.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_114 = fiy_1.checkOut();
        fiy_114.setElementMap(fyy_03);
        fiy_114.setAttribute("text");
        fiy_114.setField("effectDetails");
        fiy_114.setName("itemPopupDetail");
        fuk_04.addBasicElement(fiy_114);
        fiy_114.onAttributesInitialized();
        fiy_114.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fuk_0 fuk_06 = new fuk_0();
        fuk_06.onCheckOut();
        fuk_06.setElementMap(fyy_03);
        fuk_06.setMinWidth(230);
        fuk_06.setStyle("white11");
        fuk_06.setVisible(false);
        fso12.addBasicElement(fuk_06);
        fuk_06.onAttributesInitialized();
        fiy_1 fiy_115 = fiy_1.checkOut();
        fiy_115.setElementMap(fyy_03);
        fiy_115.setAttribute("visible");
        fiy_115.setName("isFromEquipedShortcut");
        fuk_06.addBasicElement(fiy_115);
        fiy_115.onAttributesInitialized();
        far_2 far_27 = new far_2();
        far_27.onCheckOut();
        far_27.setElementMap(fyy_03);
        far_27.setElseValue("true");
        far_27.setValue("false");
        fiy_115.addBasicElement(far_27);
        far_27.onAttributesInitialized();
        fae_2 fae_23 = new fae_2();
        fae_23.onCheckOut();
        fae_23.setElementMap(fyy_03);
        far_27.addBasicElement(fae_23);
        fae_23.onAttributesInitialized();
        fan_2 fan_22 = new fan_2();
        fan_22.onCheckOut();
        fan_22.setElementMap(fyy_03);
        fae_23.addBasicElement(fan_22);
        fan_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_03);
        fan_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        fau_1 fau_13 = new fau_1();
        fau_13.onCheckOut();
        fau_13.setElementMap(fyy_03);
        fan_22.addBasicElement(fau_13);
        fau_13.onAttributesInitialized();
        this.a(fau_13);
        fau_13.onChildrenAdded();
        fan_22.onChildrenAdded();
        this.a(fae_23);
        fae_23.onChildrenAdded();
        far_27.onChildrenAdded();
        fiy_115.onChildrenAdded();
        this.a(fuk_06);
        this.b(fuk_06);
        fuk_06.onChildrenAdded();
        fso12.onChildrenAdded();
        fso3.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo a(fau_1 fau_12) {
        fyy_0 fyy_02 = this.a.peek();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("comparedValue");
        fiy_12.setName("isFromShortcut");
        fau_12.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        return fiy_12;
    }

    public fyo a(fae_2 fae_22) {
        fyy_0 fyy_02 = this.a.peek();
        fat_2 fat_22 = new fat_2();
        fat_22.onCheckOut();
        fat_22.setElementMap(fyy_02);
        fat_22.setValue("");
        fae_22.addBasicElement(fat_22);
        fat_22.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("comparedValue");
        fiy_12.setField("effect");
        fiy_12.setName("itemPopupDetail");
        fat_22.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fat_22.onChildrenAdded();
        return fat_22;
    }

    public fyo a(fuk_0 fuk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 20, 0, 0));
        fqh_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        return fqh_02;
    }

    public fyo b(fuk_0 fuk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("effectDetails");
        fiy_12.setName("itemPopupDetail");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        return fiy_12;
    }
}

