/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cOo
 */
public class coo_1
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        fvk_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvk_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("windowNew");
        fvk_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(10, 5, 12, 5));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setExpandable(false);
        fso3.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fvM fvM3 = fvM2;
        fqj fqj3 = ((fvE)fvM3).getAppearance();
        fqj3.setElementMap(fyy_03);
        fvM2.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 10, 0, 10));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setStyle("titleBar");
        fvM2.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso fso6 = fso5;
        fqj fqj4 = ((fvE)fso6).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso5.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(3, 20, 3, 20));
        fqj4.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.e);
        fso7.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("StyledBold16White");
        String string = "%jukebox.title%";
        string = string.replace("%jukebox.title%", fpm_0.b().c("jukebox.title"));
        fsM2.c(string);
        fso7.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        fvM2.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso3.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj5 = ((fvE)fso9).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso8.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 12, 0, 12));
        fqj5.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj5.onChildrenAdded();
        String string2 = "windowContentContainer";
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fso10);
        }
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setHorizontal(false);
        fso10.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso11.setExpandable(false);
        fso11.setPrefSize(new fjf_2(-2, 30));
        fso11.setStyle("caracs");
        fso10.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fso11.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        fso11.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.h);
        fid_14.setSize(new fjf_2(-2, -2));
        fso12.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_03);
        fsM4.setStyle("bold");
        String string3 = "%jukebox.currentMusic%";
        string3 = string3.replace("%jukebox.currentMusic%", fpm_0.b().c("jukebox.currentMusic"));
        fsM4.c(string3);
        fso12.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM4.onChildrenAdded();
        fsM fsM5 = new fsM();
        fsM5.onCheckOut();
        fsM5.setElementMap(fyy_03);
        fso12.addBasicElement(fsM5);
        fsM5.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("text");
        fiy_12.setField("currentMusicName");
        fiy_12.setLocal(true);
        fiy_12.setName("jukebox");
        fsM5.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fsM5.onChildrenAdded();
        fso12.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_03);
        fso11.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.j);
        fid_15.setSize(new fjf_2(-2, -2));
        fso13.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_03);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.jukebox:dropMusic");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(dropMusicPopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setPrefSize(new fjf_2(20, 20));
        fso13.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fru_02.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setDisplaySize(new fjf_2(20, 20));
        fsk_02.setExpandable(false);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("cancel");
        fru_02.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_03);
        fid_16.setAlign(frk_0.i);
        fid_16.setSize(new fjf_2(20, 20));
        fid_16.setYOffset(-1);
        fsk_02.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fsk_02.onChildrenAdded();
        String string4 = "dropMusicPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_03);
        if (fyy_03 != null && string4 != null) {
            fyy_03.a(string4, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_03);
        fso14.setPrefSize(new fjf_2(10, 0));
        fso14.setStyle("popup");
        fil_12.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_03);
        fii_22.setData(frg_0.e);
        fso14.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_03);
        fsM6.setStyle("PopupInformation");
        String string5 = "%jukebox.dropMusic%";
        string5 = string5.replace("%jukebox.dropMusic%", fpm_0.b().c("jukebox.dropMusic"));
        fsM6.c(string5);
        fso14.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fsM fsM7 = fsM6;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM7).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fqh_03.setAlign(frs_0.d);
        fsM6.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fsM6.onChildrenAdded();
        fso14.onChildrenAdded();
        fil_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_03);
        fru_03.setExpandable(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.jukebox:randomMusic");
        fru_03.setOnClick(fdt_13);
        fde_2 fde_23 = new fde_2();
        fde_23.a("popup(randomMusicPopup)");
        fru_03.setOnPopupDisplay(fde_23);
        fdf_2 fdf_23 = new fdf_2();
        fdf_23.a("closePopup");
        fru_03.setOnPopupHide(fdf_23);
        fru_03.setPrefSize(new fjf_2(20, 20));
        fso13.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        fic_1 fic_15 = new fic_1();
        fic_15.onCheckOut();
        fru_03.addBasicElement(fic_15);
        fic_15.onAttributesInitialized();
        fic_15.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_03);
        fsk_03.setExpandable(false);
        fsk_03.setNonBlocking(true);
        fsk_03.setStyle("RandomSquare");
        fru_03.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_03);
        fid_17.setAlign(frk_0.i);
        fid_17.setYOffset(-1);
        fsk_03.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fsk_03.onChildrenAdded();
        String string6 = "randomMusicPopup";
        fil_1 fil_13 = new fil_1();
        fil_13.onCheckOut();
        fil_13.setElementMap(fyy_03);
        if (fyy_03 != null && string6 != null) {
            fyy_03.a(string6, fil_13);
        }
        fil_13.setAlign(frs_0.b);
        fil_13.setHotSpotPosition(frs_0.h);
        fru_03.addBasicElement(fil_13);
        fil_13.onAttributesInitialized();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_03);
        fso15.setPrefSize(new fjf_2(10, 0));
        fso15.setStyle("popup");
        fil_13.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fii_2 fii_23 = fii_2.checkOut();
        fii_23.setElementMap(fyy_03);
        fii_23.setData(frg_0.e);
        fso15.addBasicElement(fii_23);
        fii_23.onAttributesInitialized();
        fii_23.onChildrenAdded();
        fsM fsM8 = new fsM();
        fsM8.onCheckOut();
        fsM8.setElementMap(fyy_03);
        fsM8.setStyle("PopupInformation");
        String string7 = "%jukebox.randomMusic%";
        string7 = string7.replace("%jukebox.randomMusic%", fpm_0.b().c("jukebox.randomMusic"));
        fsM8.c(string7);
        fso15.addBasicElement(fsM8);
        fsM8.onAttributesInitialized();
        fsM fsM9 = fsM8;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM9).getAppearance();
        fqh_04.setElementMap(fyy_03);
        fqh_04.setAlign(frs_0.d);
        fsM8.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fsM8.onChildrenAdded();
        fso15.onChildrenAdded();
        fil_13.onChildrenAdded();
        fru_03.onChildrenAdded();
        fso13.onChildrenAdded();
        fso11.onChildrenAdded();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_03);
        fso10.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        fso fso17 = fso.checkOut();
        fso17.setElementMap(fyy_03);
        fso17.setExpandable(false);
        fso17.setNonBlocking(false);
        fso17.setPrefSize(new fjf_2(280, 330));
        fso17.setStyle("caracs");
        fso16.addBasicElement(fso17);
        fso17.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_03);
        fip_23.setAlign(frs_0.a);
        fso17.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setHorizontal(false);
        fso17.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fug_0 fug_02 = new fug_0();
        fug_02.onCheckOut();
        fug_02.setElementMap(fyy_03);
        fug_02.setExpandable(false);
        fug_02.setFocused(true);
        String string8 = "%search%";
        string8 = string8.replace("%search%", fpm_0.b().c("search"));
        fug_02.b(string8);
        fdo_1 fdo_12 = new fdo_1();
        fdo_12.a("wakfu.jukebox:onInstanceSearch");
        fug_02.setOnKeyType(fdo_12);
        fug_02.setPrefSize(new fjf_2(100.0f, 20));
        fug_02.setStyle("TITLEDTEXTBLUE");
        fso17.addBasicElement(fug_02);
        fug_02.onAttributesInitialized();
        fug_02.onChildrenAdded();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_03);
        fsQ2.setCellSize(new fjf_2(100.0f, 24));
        fsQ2.setExpandable(false);
        fsQ2.setIdealSizeMaxColumns(1);
        fsQ2.setIdealSizeMaxRows(10);
        fsQ2.setIdealSizeMinColumns(1);
        fsQ2.setIdealSizeMinRows(10);
        fsQ2.setPrefSize(new fjf_2(100.0f, 300));
        fsQ2.setScrollBarBehaviour(fra_0.b);
        fso17.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("content");
        fiy_13.setField("instances");
        fiy_13.setLocal(true);
        fiy_13.setName("jukebox");
        fsQ2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("selectedValue");
        fiy_14.setField("instance");
        fiy_14.setLocal(true);
        fiy_14.setName("jukebox");
        fsQ2.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_03);
        fdi_1 fdi_12 = new fdi_1();
        fdi_12.a("wakfu.jukebox:pickInstance");
        faf_22.setOnItemClick(fdi_12);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_03);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso18 = fso.checkOut();
        fso18.setElementMap(fyy_03);
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.a("wakfu.jukebox:overList(overContainer)");
        fso18.setOnMouseEnter(fdy_12);
        fdz_1 fdz_12 = new fdz_1();
        fdz_12.a("wakfu.jukebox:outList(overContainer)");
        fso18.setOnMouseExit(fdz_12);
        faf_22.addBasicElement(fso18);
        fso18.onAttributesInitialized();
        fic_1 fic_16 = new fic_1();
        fic_16.onCheckOut();
        fso18.addBasicElement(fic_16);
        fic_16.onAttributesInitialized();
        fic_16.onChildrenAdded();
        fso fso19 = fso.checkOut();
        fso19.setElementMap(fyy_03);
        fso18.addBasicElement(fso19);
        fso19.onAttributesInitialized();
        this.a(fso19);
        this.b(fso19);
        this.c(fso19);
        fso19.onChildrenAdded();
        this.d(fso18);
        fso18.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso17.onChildrenAdded();
        this.e(fso16);
        this.f(fso16);
        this.i(fso16);
        fso16.onChildrenAdded();
        fso10.onChildrenAdded();
        fso8.onChildrenAdded();
        fso3.onChildrenAdded();
        this.a(fvk_02);
        this.b(fvk_02);
        this.c(fvk_02);
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fbf_1 fbf_12 = new fbf_1();
        fbf_12.onCheckOut();
        fbf_12.setElementMap(fyy_02);
        fqj2.addBasicElement(fbf_12);
        fbf_12.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("color");
        fbf_12.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        far_22.setElseValue("oddCellColor");
        far_22.setValue("evenCellColor");
        fir_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        faw_2 faw_22 = new faw_2();
        faw_22.onCheckOut();
        faw_22.setElementMap(fyy_02);
        faw_22.setKey("evenIndex");
        far_22.addBasicElement(faw_22);
        faw_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        faw_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fir_12.onChildrenAdded();
        fbf_12.onChildrenAdded();
        fqj2.onChildrenAdded();
        return fqj2;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fso2.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("style");
        fiy_12.setField("instance");
        fiy_12.setLocal(true);
        fiy_12.setName("jukebox");
        fsM2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        far_22.setElseValue("white");
        far_22.setValue("whiteBold");
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fat_2 fat_22 = new fat_2();
        fat_22.onCheckOut();
        fat_22.setElementMap(fyy_02);
        far_22.addBasicElement(fat_22);
        fat_22.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("value");
        fat_22.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fat_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 5, 0, 0));
        fqh_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("text");
        fir_13.setField("instance");
        fsM2.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fsM2.onChildrenAdded();
        return fsM2;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        String string = "overContainer";
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fso3);
        }
        fso3.setVisible(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fbf_1 fbf_12 = new fbf_1();
        fbf_12.onCheckOut();
        fbf_12.setElementMap(fyy_02);
        fbf_12.setColor(new azf_2(1.0f, 1.0f, 1.0f, 0.05f));
        fqj2.addBasicElement(fbf_12);
        fbf_12.onAttributesInitialized();
        fbf_12.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo e(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_02);
        fso2.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        return fur_02;
    }

    public fyo f(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setNonBlocking(false);
        fso3.setPrefSize(new fjf_2(320, 342));
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("instance");
        fiy_12.setLocal(true);
        fiy_12.setName("jukebox");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.c);
        fso3.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setExpandable(false);
        fso4.setPrefSize(new fjf_2(300, 100));
        fso4.setStyle("caracs");
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_02);
        fip_23.setAlign(frs_0.b);
        fso4.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        fsQ2.setCellSize(new fjf_2(300, 24));
        fsQ2.setIdealSizeMaxColumns(1);
        fsQ2.setIdealSizeMinColumns(1);
        fsQ2.setScrollBarBehaviour(fra_0.b);
        fsQ2.setSelectionTogglable(false);
        fso4.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("content");
        fiy_13.setField("instance/zones");
        fiy_13.setLocal(true);
        fiy_13.setName("jukebox");
        fsQ2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("selectedValue");
        fiy_14.setField("playlist");
        fiy_14.setLocal(true);
        fiy_14.setName("jukebox");
        fsQ2.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fdi_1 fdi_12 = new fdi_1();
        fdi_12.a("wakfu.jukebox:pickAmbienceZone");
        faf_22.setOnItemClick(fdi_12);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        faf_22.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_23.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_23.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.a("wakfu.jukebox:overList(overContainer)");
        fso5.setOnMouseEnter(fdy_12);
        fdz_1 fdz_12 = new fdz_1();
        fdz_12.a("wakfu.jukebox:outList(overContainer)");
        fso5.setOnMouseExit(fdz_12);
        faf_22.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso5.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso5.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso6.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso7 = fso6;
        fqj fqj2 = ((fvE)fso7).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso6.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fbf_1 fbf_12 = new fbf_1();
        fbf_12.onCheckOut();
        fbf_12.setElementMap(fyy_02);
        fqj2.addBasicElement(fbf_12);
        fbf_12.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("color");
        fbf_12.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_02);
        far_24.setElseValue("oddCellColor");
        far_24.setValue("evenCellColor");
        fir_12.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        faw_2 faw_22 = new faw_2();
        faw_22.onCheckOut();
        faw_22.setElementMap(fyy_02);
        faw_22.setKey("evenIndex");
        far_24.addBasicElement(faw_22);
        faw_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        faw_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        far_24.onChildrenAdded();
        fir_12.onChildrenAdded();
        fbf_12.onChildrenAdded();
        fqj2.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fso6.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("style");
        fiy_15.setField("playlist");
        fiy_15.setLocal(true);
        fiy_15.setName("jukebox");
        fsM2.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_02);
        far_25.setElseValue("white");
        far_25.setValue("whiteBold");
        fiy_15.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fat_2 fat_22 = new fat_2();
        fat_22.onCheckOut();
        fat_22.setElementMap(fyy_02);
        far_25.addBasicElement(fat_22);
        fat_22.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("value");
        fat_22.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fat_22.onChildrenAdded();
        far_25.onChildrenAdded();
        fiy_15.onChildrenAdded();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 5, 0, 0));
        fqh_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("text");
        fir_14.setField("ambienceZoneName");
        fsM2.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso6.onChildrenAdded();
        String string = "overContainer";
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fso8);
        }
        fso8.setVisible(false);
        fso5.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso8.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fso fso9 = fso8;
        fqj fqj3 = ((fvE)fso9).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso8.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fbf_1 fbf_13 = new fbf_1();
        fbf_13.onCheckOut();
        fbf_13.setElementMap(fyy_02);
        fbf_13.setColor(new azf_2(1.0f, 1.0f, 1.0f, 0.05f));
        fqj3.addBasicElement(fbf_13);
        fbf_13.onAttributesInitialized();
        fbf_13.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso8.onChildrenAdded();
        fso5.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso4.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_02);
        fso10.setStyle("caracs");
        fso3.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso10.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso11 = fso10;
        fqj fqj4 = ((fvE)fso11).getAppearance();
        fqj4.setElementMap(fyy_02);
        fso10.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(0, 5, 0, 0));
        fqj4.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj4.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_02);
        fso10.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fso12.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setStyle("titleNameBold");
        String string2 = "%jukebox.dayMusic%";
        string2 = string2.replace("%jukebox.dayMusic%", fpm_0.b().c("jukebox.dayMusic"));
        fsM4.c(string2);
        fso12.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.h);
        fid_14.setSize(new fjf_2(180, 20));
        fsM4.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_02);
        fso12.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setAlign(frk_0.h);
        fid_15.setSize(new fjf_2(140, 20));
        fid_15.setXOffset(180);
        fso13.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fsQ fsQ3 = new fsQ();
        fsQ3.onCheckOut();
        fsQ3.setElementMap(fyy_02);
        fsQ3.setCellSize(new fjf_2(20, 20));
        fsQ3.setHorizontal(true);
        fsQ3.setIdealSizeMaxRows(1);
        fsQ3.setIdealSizeMinRows(1);
        fsQ3.setScrollBarBehaviour(fra_0.c);
        fsQ3.setSelectionTogglable(false);
        fso13.addBasicElement(fsQ3);
        fsQ3.onAttributesInitialized();
        faf_2 faf_23 = new faf_2();
        faf_23.onCheckOut();
        faf_23.setElementMap(fyy_02);
        fdi_1 fdi_13 = new fdi_1();
        fdi_13.a("wakfu.jukebox:pickMusic");
        faf_23.setOnItemClick(fdi_13);
        fsQ3.addBasicElement(faf_23);
        faf_23.onAttributesInitialized();
        far_2 far_26 = new far_2();
        far_26.onCheckOut();
        far_26.setElementMap(fyy_02);
        faf_23.addBasicElement(far_26);
        far_26.onAttributesInitialized();
        fav_1 fav_13 = new fav_1();
        fav_13.onCheckOut();
        fav_13.setElementMap(fyy_02);
        far_26.addBasicElement(fav_13);
        fav_13.onAttributesInitialized();
        fab_2 fab_24 = new fab_2();
        fab_24.onCheckOut();
        fab_24.setElementMap(fyy_02);
        fav_13.addBasicElement(fab_24);
        fab_24.onAttributesInitialized();
        fab_24.onChildrenAdded();
        fav_13.onChildrenAdded();
        far_26.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setDisplaySize(new fjf_2(20, 20));
        fru_02.setStyle("BIGPLAYVIDEO");
        faf_23.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_02.onChildrenAdded();
        faf_23.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_02);
        fiy_16.setAttribute("content");
        fiy_16.setField("playlist/dayMusics");
        fiy_16.setLocal(true);
        fiy_16.setName("jukebox");
        fsQ3.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fsQ3.onChildrenAdded();
        fso13.onChildrenAdded();
        fso12.onChildrenAdded();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_02);
        fso10.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fso14.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        fsM fsM5 = new fsM();
        fsM5.onCheckOut();
        fsM5.setElementMap(fyy_02);
        fsM5.setStyle("titleNameBold");
        String string3 = "%jukebox.nightMusic%";
        string3 = string3.replace("%jukebox.nightMusic%", fpm_0.b().c("jukebox.nightMusic"));
        fsM5.c(string3);
        fso14.addBasicElement(fsM5);
        fsM5.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_02);
        fid_16.setAlign(frk_0.h);
        fid_16.setSize(new fjf_2(180, 20));
        fsM5.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fsM5.onChildrenAdded();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_02);
        fso14.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_02);
        fid_17.setAlign(frk_0.h);
        fid_17.setSize(new fjf_2(140, 20));
        fid_17.setXOffset(180);
        fso15.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fsQ fsQ4 = new fsQ();
        fsQ4.onCheckOut();
        fsQ4.setElementMap(fyy_02);
        fsQ4.setCellSize(new fjf_2(20, 20));
        fsQ4.setHorizontal(true);
        fsQ4.setIdealSizeMaxRows(1);
        fsQ4.setIdealSizeMinRows(1);
        fsQ4.setScrollBarBehaviour(fra_0.c);
        fsQ4.setSelectionTogglable(false);
        fso15.addBasicElement(fsQ4);
        fsQ4.onAttributesInitialized();
        faf_2 faf_24 = new faf_2();
        faf_24.onCheckOut();
        faf_24.setElementMap(fyy_02);
        fdi_1 fdi_14 = new fdi_1();
        fdi_14.a("wakfu.jukebox:pickMusic");
        faf_24.setOnItemClick(fdi_14);
        fsQ4.addBasicElement(faf_24);
        faf_24.onAttributesInitialized();
        far_2 far_27 = new far_2();
        far_27.onCheckOut();
        far_27.setElementMap(fyy_02);
        faf_24.addBasicElement(far_27);
        far_27.onAttributesInitialized();
        fav_1 fav_14 = new fav_1();
        fav_14.onCheckOut();
        fav_14.setElementMap(fyy_02);
        far_27.addBasicElement(fav_14);
        fav_14.onAttributesInitialized();
        fab_2 fab_25 = new fab_2();
        fab_25.onCheckOut();
        fab_25.setElementMap(fyy_02);
        fav_14.addBasicElement(fab_25);
        fab_25.onAttributesInitialized();
        fab_25.onChildrenAdded();
        fav_14.onChildrenAdded();
        far_27.onChildrenAdded();
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_02);
        fru_03.setDisplaySize(new fjf_2(20, 20));
        fru_03.setStyle("BIGPLAYVIDEO");
        faf_24.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        fru_03.onChildrenAdded();
        faf_24.onChildrenAdded();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_02);
        fiy_17.setAttribute("content");
        fiy_17.setField("playlist/nightMusics");
        fiy_17.setLocal(true);
        fiy_17.setName("jukebox");
        fsQ4.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        fsQ4.onChildrenAdded();
        fso15.onChildrenAdded();
        fso14.onChildrenAdded();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_02);
        fso10.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        fic_1 fic_15 = new fic_1();
        fic_15.onCheckOut();
        fso16.addBasicElement(fic_15);
        fic_15.onAttributesInitialized();
        fic_15.onChildrenAdded();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_02);
        fsM6.setStyle("titleNameBold");
        String string4 = "%jukebox.fightMusic%";
        string4 = string4.replace("%jukebox.fightMusic%", fpm_0.b().c("jukebox.fightMusic"));
        fsM6.c(string4);
        fso16.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        this.a(fsM6);
        fsM6.onChildrenAdded();
        this.g(fso16);
        fso16.onChildrenAdded();
        this.h(fso10);
        fso10.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo a(fsM fsM2) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.h);
        fid_12.setSize(new fjf_2(180, 20));
        fsM2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }

    public fyo g(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.h);
        fid_12.setSize(new fjf_2(140, 20));
        fid_12.setXOffset(180);
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        fsQ2.setCellSize(new fjf_2(20, 20));
        fsQ2.setHorizontal(true);
        fsQ2.setIdealSizeMaxRows(1);
        fsQ2.setIdealSizeMinRows(1);
        fsQ2.setScrollBarBehaviour(fra_0.c);
        fsQ2.setSelectionTogglable(false);
        fso3.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fdi_1 fdi_12 = new fdi_1();
        fdi_12.a("wakfu.jukebox:pickMusic");
        faf_22.setOnItemClick(fdi_12);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setDisplaySize(new fjf_2(20, 20));
        fru_02.setStyle("BIGPLAYVIDEO");
        faf_22.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_02.onChildrenAdded();
        faf_22.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("playlist/fightMusics");
        fiy_12.setLocal(true);
        fiy_12.setName("jukebox");
        fsQ2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo h(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("titleNameBold");
        String string = "%jukebox.bossMusic%";
        string = string.replace("%jukebox.bossMusic%", fpm_0.b().c("jukebox.bossMusic"));
        fsM2.c(string);
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.h);
        fid_12.setSize(new fjf_2(180, 20));
        fsM2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.h);
        fid_13.setSize(new fjf_2(140, 20));
        fid_13.setXOffset(180);
        fso4.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        fsQ2.setCellSize(new fjf_2(20, 20));
        fsQ2.setHorizontal(true);
        fsQ2.setIdealSizeMaxRows(1);
        fsQ2.setIdealSizeMinRows(1);
        fsQ2.setScrollBarBehaviour(fra_0.c);
        fsQ2.setSelectionTogglable(false);
        fso4.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fdi_1 fdi_12 = new fdi_1();
        fdi_12.a("wakfu.jukebox:pickMusic");
        faf_22.setOnItemClick(fdi_12);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setDisplaySize(new fjf_2(20, 20));
        fru_02.setStyle("BIGPLAYVIDEO");
        faf_22.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_02.onChildrenAdded();
        faf_22.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("playlist/bossMusics");
        fiy_12.setLocal(true);
        fiy_12.setName("jukebox");
        fsQ2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso4.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo i(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setPrefSize(new fjf_2(320, 0));
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("instance");
        fiy_12.setLocal(true);
        fiy_12.setName("jukebox");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fac_1 fac_12 = new fac_1();
        fac_12.onCheckOut();
        fac_12.setElementMap(fyy_02);
        far_22.addBasicElement(fac_12);
        fac_12.onAttributesInitialized();
        fac_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo a(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso2.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(11, 15));
        fsk_02.setExpandable(false);
        fsk_02.setNonBlocking(false);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(tutoJukebox)");
        fsk_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fsk_02.setOnPopupHide(fdf_22);
        fsk_02.setStyle("questionMark");
        fso2.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.e);
        fid_13.setSize(new fjf_2(-2, -2));
        fid_13.setXOffset(-40);
        fid_13.setYOffset(-15);
        fsk_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        String string = "tutoJukebox";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fsk_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setPrefSize(new fjf_2(10, 0));
        fso3.setStyle("popup");
        fil_12.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setEnableShrinking(false);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(250);
        fuk_02.setMinWidth(1);
        fuk_02.setStyle("white");
        String string2 = "%jukebox.tuto%";
        string2 = string2.replace("%jukebox.tuto%", fpm_0.b().c("jukebox.tuto"));
        fuk_02.c(string2);
        fso3.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.e);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        fil_12.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo b(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fru_02.setStyle("close");
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("unloadDialog");
        fru_02.setOnClick(fdt_12);
        fvk_02.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setSize(new fjf_2(-2, -2));
        fid_12.setXOffset(-18);
        fid_12.setYOffset(-12);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.e);
        fid_13.setSize(new fjf_2(-2, -2));
        fid_13.setXOffset(-20);
        fid_13.setYOffset(-13);
        fru_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo c(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setResizeOnce(true);
        fid_12.setSize(new fjf_2(660, 430));
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }
}

