/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cPi
 */
public class cpi_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fso2.setNonBlocking(false);
        fso2.setPrefSize(new fjf_2(360, 50));
        fso2.setStyle("MainBackground");
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setAlign(frk_0.i);
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fih_2 fih_22 = new fih_2();
        fih_22.onCheckOut();
        fso2.addBasicElement(fih_22);
        fih_22.onAttributesInitialized();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("topWindow");
        fih_22.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_03);
        fii_22.setData(frg_0.b);
        fso3.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setStyle("title");
        String string = "%menu%";
        string = string.replace("%menu%", fpm_0.b().c("menu"));
        fsM2.c(string);
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setAlign(frk_0.i);
        fsM2.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(5, 0, 0, 0));
        fqh_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_03);
        fso3.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_03);
        fsM4.setExpandable(false);
        fso3.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.j);
        fsM4.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("text");
        fiy_12.setName("buildVersion");
        fsM4.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fsM fsM5 = fsM4;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fsM4.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 0, 0, 15));
        fqh_03.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso3.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_03);
        fih_22.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso4;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso4.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(10, 10, 10, 10));
        fqj2.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqj2.onChildrenAdded();
        fii_2 fii_23 = fii_2.checkOut();
        fii_23.setElementMap(fyy_03);
        fii_23.setData(frg_0.a);
        fso4.addBasicElement(fii_23);
        fii_23.onAttributesInitialized();
        fii_23.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso4.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_03);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.menu:openOptionsDialog");
        fru_02.setOnClick(fdt_12);
        String string2 = "%options%";
        string2 = string2.replace("%options%", fpm_0.b().c("options"));
        fru_02.setText(string2);
        fin_22.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_03);
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(0, 0, 5, 0));
        fqd_02.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqd_02.onChildrenAdded();
        fru_02.onChildrenAdded();
        fru_0 fru_04 = new fru_0();
        fru_04.onCheckOut();
        fru_04.setElementMap(fyy_03);
        fru_04.setExpandable(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu:checkAntiAddictionAccount");
        fru_04.setOnClick(fdt_13);
        String string3 = "%antiAddictionAccountCheck%";
        string3 = string3.replace("%antiAddictionAccountCheck%", fpm_0.b().c("antiAddictionAccountCheck"));
        fru_04.setText(string3);
        fin_22.addBasicElement(fru_04);
        fru_04.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("visible");
        fiy_13.setName("antiAddictionEnabled");
        fru_04.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        fiy_13.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_03);
        far_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fru_0 fru_05 = fru_04;
        fqd_0 fqd_03 = (fqd_0)((fvE)fru_05).getAppearance();
        fqd_03.setElementMap(fyy_03);
        fru_04.addBasicElement(fqd_03);
        fqd_03.onAttributesInitialized();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_03);
        fqm_06.setInsets(new Insets(0, 0, 5, 0));
        fqd_03.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqd_03.onChildrenAdded();
        fru_04.onChildrenAdded();
        fru_0 fru_06 = new fru_0();
        fru_06.onCheckOut();
        fru_06.setElementMap(fyy_03);
        fru_06.setExpandable(false);
        fdt_1 fdt_14 = new fdt_1();
        fdt_14.a("wakfu.menu:goToWorldChoiceDialog");
        fru_06.setOnClick(fdt_14);
        String string4 = "%changeCharacter%";
        string4 = string4.replace("%changeCharacter%", fpm_0.b().c("changeCharacter"));
        fru_06.setText(string4);
        fin_22.addBasicElement(fru_06);
        fru_06.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("visible");
        fiy_14.setName("isInGame");
        fru_06.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        fiy_14.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fan_2 fan_22 = new fan_2();
        fan_22.onCheckOut();
        fan_22.setElementMap(fyy_03);
        far_23.addBasicElement(fan_22);
        fan_22.onAttributesInitialized();
        fai_1 fai_13 = new fai_1();
        fai_13.onCheckOut();
        fai_13.setElementMap(fyy_03);
        fan_22.addBasicElement(fai_13);
        fai_13.onAttributesInitialized();
        fai_13.onChildrenAdded();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_03);
        fan_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("comparedValue");
        fiy_15.setField("character.change.disabled");
        fiy_15.setName("systemConfiguration");
        fau_12.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fau_12.onChildrenAdded();
        fan_22.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_14.onChildrenAdded();
        fru_0 fru_07 = fru_06;
        fqd_0 fqd_04 = (fqd_0)((fvE)fru_07).getAppearance();
        fqd_04.setElementMap(fyy_03);
        fru_06.addBasicElement(fqd_04);
        fqd_04.onAttributesInitialized();
        fqm_0 fqm_07 = fqm_0.checkOut();
        fqm_07.setElementMap(fyy_03);
        fqm_07.setInsets(new Insets(0, 0, 5, 0));
        fqd_04.addBasicElement(fqm_07);
        fqm_07.onAttributesInitialized();
        fqm_07.onChildrenAdded();
        fqd_04.onChildrenAdded();
        fru_06.onChildrenAdded();
        fru_0 fru_08 = new fru_0();
        fru_08.onCheckOut();
        fru_08.setElementMap(fyy_03);
        fru_08.setExpandable(false);
        fdt_1 fdt_15 = new fdt_1();
        fdt_15.a("wakfu.menu:contactModerator");
        fru_08.setOnClick(fdt_15);
        String string5 = "%contactModerator%";
        string5 = string5.replace("%contactModerator%", fpm_0.b().c("contactModerator"));
        fru_08.setText(string5);
        fin_22.addBasicElement(fru_08);
        fru_08.onAttributesInitialized();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("enabled");
        fiy_16.setName("hasModeratorChatRequest");
        fru_08.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_03);
        fiy_17.setAttribute("visible");
        fiy_17.setName("isInGame");
        fru_08.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_03);
        fiy_17.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fan_2 fan_23 = new fan_2();
        fan_23.onCheckOut();
        fan_23.setElementMap(fyy_03);
        far_24.addBasicElement(fan_23);
        fan_23.onAttributesInitialized();
        fai_1 fai_14 = new fai_1();
        fai_14.onCheckOut();
        fai_14.setElementMap(fyy_03);
        fan_23.addBasicElement(fai_14);
        fai_14.onAttributesInitialized();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_03);
        fiy_18.setAttribute("comparedValue");
        fiy_18.setField("contactModerator.enable");
        fiy_18.setName("systemConfiguration");
        fai_14.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        fiy_18.onChildrenAdded();
        fai_14.onChildrenAdded();
        fai_1 fai_15 = new fai_1();
        fai_15.onCheckOut();
        fai_15.setElementMap(fyy_03);
        fan_23.addBasicElement(fai_15);
        fai_15.onAttributesInitialized();
        fai_15.onChildrenAdded();
        fan_23.onChildrenAdded();
        far_24.onChildrenAdded();
        fiy_17.onChildrenAdded();
        fru_0 fru_09 = fru_08;
        fqd_0 fqd_05 = (fqd_0)((fvE)fru_09).getAppearance();
        fqd_05.setElementMap(fyy_03);
        fru_08.addBasicElement(fqd_05);
        fqd_05.onAttributesInitialized();
        fqm_0 fqm_08 = fqm_0.checkOut();
        fqm_08.setElementMap(fyy_03);
        fqm_08.setInsets(new Insets(0, 0, 5, 0));
        fqd_05.addBasicElement(fqm_08);
        fqm_08.onAttributesInitialized();
        fqm_08.onChildrenAdded();
        fqd_05.onChildrenAdded();
        fru_08.onChildrenAdded();
        fru_0 fru_010 = new fru_0();
        fru_010.onCheckOut();
        fru_010.setElementMap(fyy_03);
        fru_010.setExpandable(false);
        fdt_1 fdt_16 = new fdt_1();
        fdt_16.a("wakfu.menu:loggoff");
        fru_010.setOnClick(fdt_16);
        String string6 = "%disconnect%";
        string6 = string6.replace("%disconnect%", fpm_0.b().c("disconnect"));
        fru_010.setText(string6);
        fin_22.addBasicElement(fru_010);
        fru_010.onAttributesInitialized();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_03);
        fiy_19.setAttribute("visible");
        fiy_19.setName("isConnected");
        fru_010.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_03);
        fiy_19.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fai_1 fai_16 = new fai_1();
        fai_16.onCheckOut();
        fai_16.setElementMap(fyy_03);
        far_25.addBasicElement(fai_16);
        fai_16.onAttributesInitialized();
        fai_16.onChildrenAdded();
        far_25.onChildrenAdded();
        fiy_19.onChildrenAdded();
        fru_0 fru_011 = fru_010;
        fqd_0 fqd_06 = (fqd_0)((fvE)fru_011).getAppearance();
        fqd_06.setElementMap(fyy_03);
        fru_010.addBasicElement(fqd_06);
        fqd_06.onAttributesInitialized();
        fqm_0 fqm_09 = fqm_0.checkOut();
        fqm_09.setElementMap(fyy_03);
        fqm_09.setInsets(new Insets(0, 0, 5, 0));
        fqd_06.addBasicElement(fqm_09);
        fqm_09.onAttributesInitialized();
        fqm_09.onChildrenAdded();
        fqd_06.onChildrenAdded();
        fru_010.onChildrenAdded();
        fru_0 fru_012 = new fru_0();
        fru_012.onCheckOut();
        fru_012.setElementMap(fyy_03);
        fru_012.setExpandable(false);
        fdt_1 fdt_17 = new fdt_1();
        fdt_17.a("wakfu:quit");
        fru_012.setOnClick(fdt_17);
        String string7 = "%quit%";
        string7 = string7.replace("%quit%", fpm_0.b().c("quit"));
        fru_012.setText(string7);
        fin_22.addBasicElement(fru_012);
        fru_012.onAttributesInitialized();
        fru_0 fru_013 = fru_012;
        fqd_0 fqd_07 = (fqd_0)((fvE)fru_013).getAppearance();
        fqd_07.setElementMap(fyy_03);
        fru_012.addBasicElement(fqd_07);
        fqd_07.onAttributesInitialized();
        fqm_0 fqm_010 = fqm_0.checkOut();
        fqm_010.setElementMap(fyy_03);
        fqm_010.setInsets(new Insets(0, 0, 5, 0));
        fqd_07.addBasicElement(fqm_010);
        fqm_010.onAttributesInitialized();
        fqm_010.onChildrenAdded();
        fqd_07.onChildrenAdded();
        fru_012.onChildrenAdded();
        fru_0 fru_014 = new fru_0();
        fru_014.onCheckOut();
        fru_014.setElementMap(fyy_03);
        fru_014.setExpandable(false);
        fdt_1 fdt_18 = new fdt_1();
        fdt_18.a("wakfu:openReportBugDialog");
        fru_014.setOnClick(fdt_18);
        String string8 = "%desc.bugReport%";
        string8 = string8.replace("%desc.bugReport%", fpm_0.b().c("desc.bugReport"));
        fru_014.setText(string8);
        fin_22.addBasicElement(fru_014);
        fru_014.onAttributesInitialized();
        fru_0 fru_015 = fru_014;
        fqd_0 fqd_08 = (fqd_0)((fvE)fru_015).getAppearance();
        fqd_08.setElementMap(fyy_03);
        fru_014.addBasicElement(fqd_08);
        fqd_08.onAttributesInitialized();
        fqm_0 fqm_011 = fqm_0.checkOut();
        fqm_011.setElementMap(fyy_03);
        fqm_011.setInsets(new Insets(0, 0, 5, 0));
        fqd_08.addBasicElement(fqm_011);
        fqm_011.onAttributesInitialized();
        fqm_011.onChildrenAdded();
        fqd_08.onChildrenAdded();
        fru_014.onChildrenAdded();
        fru_0 fru_016 = new fru_0();
        fru_016.onCheckOut();
        fru_016.setElementMap(fyy_03);
        fru_016.setExpandable(false);
        fdt_1 fdt_19 = new fdt_1();
        fdt_19.a("wakfu.menu:closeMenuDialog");
        fru_016.setOnClick(fdt_19);
        String string9 = "%backToGame%";
        string9 = string9.replace("%backToGame%", fpm_0.b().c("backToGame"));
        fru_016.setText(string9);
        fin_22.addBasicElement(fru_016);
        fru_016.onAttributesInitialized();
        fru_0 fru_017 = fru_016;
        fqd_0 fqd_09 = (fqd_0)((fvE)fru_017).getAppearance();
        fqd_09.setElementMap(fyy_03);
        fru_016.addBasicElement(fqd_09);
        fqd_09.onAttributesInitialized();
        fqm_0 fqm_012 = fqm_0.checkOut();
        fqm_012.setElementMap(fyy_03);
        fqm_012.setInsets(new Insets(5, 0, 0, 0));
        fqd_09.addBasicElement(fqm_012);
        fqm_012.onAttributesInitialized();
        fqm_012.onChildrenAdded();
        fqd_09.onChildrenAdded();
        fru_016.onChildrenAdded();
        fin_22.onChildrenAdded();
        fso4.onChildrenAdded();
        fih_22.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }
}

