/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cPJ
 */
public class cpj_1
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        fvk_02.setPack(true);
        fvk_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvk_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("windowNew");
        fvk_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(10, 5, 12, 5));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setExpandable(false);
        fso3.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fvM fvM3 = fvM2;
        fqj fqj3 = ((fvE)fvM3).getAppearance();
        fqj3.setElementMap(fyy_03);
        fvM2.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 10, 0, 10));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setStyle("titleBar");
        fvM2.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso fso6 = fso5;
        fqj fqj4 = ((fvE)fso6).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso5.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(3, 20, 3, 20));
        fqj4.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.e);
        fso7.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("StyledBold16White");
        String string = "%nationSelection.title%";
        string = string.replace("%nationSelection.title%", fpm_0.b().c("nationSelection.title"));
        fsM2.c(string);
        fso7.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        fvM2.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso3.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj5 = ((fvE)fso9).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso8.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 12, 0, 12));
        fqj5.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj5.onChildrenAdded();
        String string2 = "windowContentContainer";
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fso10);
        }
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        String string3 = "list";
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fsQ2);
        }
        fsQ2.setCellSize(new fjf_2(240, 475));
        fsQ2.setPrefSize(new fjf_2(960, 460));
        fso10.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("content");
        fiy_12.setName("nationSelectionList");
        fsQ2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_03);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_03);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        String string4 = "nationSelection";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_03);
        if (fyy_03 != null && string4 != null) {
            fyy_03.a(string4, fij_12);
        }
        faf_22.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_03);
        fir_12.setAttribute("value");
        fij_12.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso11.setNonBlocking(false);
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.a("wakfu.nationSelectionPanel:onMouseOverElement(nationSelection)");
        fso11.setOnMouseEnter(fdy_12);
        fdz_1 fdz_12 = new fdz_1();
        fdz_12.a("wakfu.nationSelectionPanel:onMouseOutElement");
        fso11.setOnMouseExit(fdz_12);
        faf_22.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso11.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        fso12.setExpandable(false);
        fso12.setPrefSize(new fjf_2(220, 60));
        fso11.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.o);
        fid_14.setXOffset(-10);
        fso12.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fso fso13 = fso12;
        fqj fqj6 = ((fvE)fso13).getAppearance();
        fqj6.setElementMap(fyy_03);
        fso12.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(20, 0, 0, 0));
        fqj6.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqj6.onChildrenAdded();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fic_14.setAdaptToContentSize(true);
        fso12.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setDisplaySize(new fjf_2(57, 36));
        fsk_02.setNonBlocking(false);
        fsk_02.setStyle("TimelineTimerBackgroundVerticalFlip");
        fso12.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.h);
        fsk_02.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_03);
        ((fqj)fqp2).setModulationColor(new azf_2(1.0f, 1.0f, 1.0f, 0.3f));
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqp2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_03);
        fsk_04.setDisplaySize(new fjf_2(57, 36));
        fsk_04.setNonBlocking(false);
        fsk_04.setStyle("TimelineTimerBackgroundVerticalHorizontalFlip");
        fso12.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_03);
        fid_16.setAlign(frk_0.j);
        fsk_04.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fsk_0 fsk_05 = fsk_04;
        fqp fqp3 = (fqp)((fvE)fsk_05).getAppearance();
        fqp3.setElementMap(fyy_03);
        ((fqj)fqp3).setModulationColor(new azf_2(1.0f, 1.0f, 1.0f, 0.3f));
        fsk_04.addBasicElement(fqp3);
        fqp3.onAttributesInitialized();
        fqp3.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_03);
        fso12.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_03);
        fid_17.setAlign(frk_0.i);
        fso14.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fic_1 fic_15 = new fic_1();
        fic_15.onCheckOut();
        fic_15.setAdaptToContentSize(true);
        fso14.addBasicElement(fic_15);
        fic_15.onAttributesInitialized();
        fic_15.onChildrenAdded();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_03);
        fso14.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fid_1 fid_18 = new fid_1();
        fid_18.onCheckOut();
        fid_18.setElementMap(fyy_03);
        fid_18.setAlign(frk_0.c);
        fid_18.setSize(new fjf_2(100.0f, -2));
        fso15.addBasicElement(fid_18);
        fid_18.onAttributesInitialized();
        fid_18.onChildrenAdded();
        fsk_0 fsk_06 = new fsk_0();
        fsk_06.onCheckOut();
        fsk_06.setElementMap(fyy_03);
        fsk_06.setExpandable(false);
        fsk_06.setNonBlocking(true);
        fsk_06.setStyle("SundialLeftButtonContainer");
        fso15.addBasicElement(fsk_06);
        fsk_06.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_03);
        fip_23.setAlign(frs_0.b);
        fsk_06.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fsk_06.onChildrenAdded();
        fsk_0 fsk_07 = new fsk_0();
        fsk_07.onCheckOut();
        fsk_07.setElementMap(fyy_03);
        fsk_07.setNonBlocking(true);
        fsk_07.setStyle("SundialCenterButtonContainer");
        fso15.addBasicElement(fsk_07);
        fsk_07.onAttributesInitialized();
        fip_2 fip_24 = new fip_2();
        fip_24.onCheckOut();
        fip_24.setElementMap(fyy_03);
        fip_24.setAlign(frs_0.b);
        fsk_07.addBasicElement(fip_24);
        fip_24.onAttributesInitialized();
        fip_24.onChildrenAdded();
        fsk_07.onChildrenAdded();
        fsk_0 fsk_08 = new fsk_0();
        fsk_08.onCheckOut();
        fsk_08.setElementMap(fyy_03);
        fsk_08.setExpandable(false);
        fsk_08.setNonBlocking(true);
        fsk_08.setStyle("SundialRightButtonContainer");
        fso15.addBasicElement(fsk_08);
        fsk_08.onAttributesInitialized();
        fip_2 fip_25 = new fip_2();
        fip_25.onCheckOut();
        fip_25.setElementMap(fyy_03);
        fip_25.setAlign(frs_0.b);
        fsk_08.addBasicElement(fip_25);
        fip_25.onAttributesInitialized();
        fip_25.onChildrenAdded();
        fsk_08.onChildrenAdded();
        fso15.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_03);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.nationSelectionPanel:chooseNation(nationSelection)");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(choosePopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setStyle("big");
        String string5 = "%choose%";
        string5 = string5.replace("%choose%", fpm_0.b().c("choose"));
        fru_02.setText(string5);
        fso14.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_19 = new fid_1();
        fid_19.onCheckOut();
        fid_19.setElementMap(fyy_03);
        fid_19.setAlign(frk_0.i);
        fru_02.addBasicElement(fid_19);
        fid_19.onAttributesInitialized();
        fid_19.onChildrenAdded();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_03);
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(0, 20, 0, 20));
        fqd_02.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_03);
        fqo_04.setInsets(new Insets(2, 15, 2, 15));
        fqd_02.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("modulationColor");
        fiy_13.setName("selectedNation");
        fqd_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        far_23.setElseValue("1,1,1");
        far_23.setValue("0.28,0.86,0.83,1");
        fiy_13.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fat_2 fat_22 = new fat_2();
        fat_22.onCheckOut();
        fat_22.setElementMap(fyy_03);
        far_23.addBasicElement(fat_22);
        fat_22.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_03);
        fir_13.setAttribute("value");
        fat_22.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fat_22.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fqd_02.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("enabled");
        fiy_14.setName("nationSelectionDisabledMessage");
        fru_02.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_03);
        fiy_14.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fac_1 fac_12 = new fac_1();
        fac_12.onCheckOut();
        fac_12.setElementMap(fyy_03);
        far_24.addBasicElement(fac_12);
        fac_12.onAttributesInitialized();
        fac_12.onChildrenAdded();
        far_24.onChildrenAdded();
        fiy_14.onChildrenAdded();
        String string6 = "choosePopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_03);
        if (fyy_03 != null && string6 != null) {
            fyy_03.a(string6, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_03);
        fso16.setPrefSize(new fjf_2(10, 0));
        fso16.setStyle("popup");
        fil_12.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_03);
        fii_22.setData(frg_0.a);
        fso16.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.b);
        fin_24.setHorizontal(false);
        fso16.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        this.a(fso16);
        this.b(fso16);
        fso16.onChildrenAdded();
        fil_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        fso14.onChildrenAdded();
        fso12.onChildrenAdded();
        this.c(fso11);
        this.i(fso11);
        this.j(fso11);
        fso11.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso10.onChildrenAdded();
        fso8.onChildrenAdded();
        fso3.onChildrenAdded();
        this.a(fvk_02);
        this.b(fvk_02);
        this.c(fvk_02);
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        String string = "%choose%";
        string = string.replace("%choose%", fpm_0.b().c("choose"));
        fsM2.c(string);
        fso2.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        return fsM2;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setStyle("PopupInformation");
        fso2.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_02);
        fqg_02.setColor(new fyr_0("errorColor"));
        fqh_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setName("nationSelectionDisabledMessage");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("visible");
        fiy_13.setName("nationSelectionDisabledMessage");
        fuk_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_13.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fuk_02.onChildrenAdded();
        return fuk_02;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setNonBlocking(false);
        fso3.setStyle("tiledScroll");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(0, 0, 0, 0));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(17, 12, 55, 30));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso5.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso5.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso6.setExpandable(false);
        fso6.setPrefSize(new fjf_2(0, 30));
        fso6.setStyle("EncyclopediaSplashTitle");
        fso5.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.e);
        fso6.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fso fso7 = fso6;
        fqj fqj3 = ((fvE)fso7).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso6.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_02);
        fqo_03.setInsets(new Insets(0, 10, 3, 10));
        fqj3.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(5, 0, 0, 0));
        fqj3.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj3.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.e);
        fso6.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("StyledBold16White");
        fso6.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("text");
        fir_12.setField("nation/name");
        fuk_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso6.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso8.setExpandable(false);
        fso5.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso8.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_02);
        fso9.setExpandable(false);
        fso9.setStyle("lineSeparator");
        fso8.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.o);
        fid_14.setSize(new fjf_2(100.0f, 7));
        fso9.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fso9.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setExpandable(false);
        fsk_02.setStyle("KamaPoi");
        fso8.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setAlign(frk_0.h);
        fsk_02.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fuk_0 fuk_03 = new fuk_0();
        fuk_03.onCheckOut();
        fuk_03.setElementMap(fyy_02);
        fuk_03.setStyle("StyledBoldDark12");
        String string = "%richness%";
        string = string.replace("%richness%", fpm_0.b().c("richness"));
        fuk_03.c(string);
        fso8.addBasicElement(fuk_03);
        fuk_03.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_02);
        fid_16.setAlign(frk_0.h);
        fuk_03.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fuk_0 fuk_04 = fuk_03;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_04).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fuk_03.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_02);
        fqo_04.setInsets(new Insets(0, 32, 0, 0));
        fqh_02.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fuk_03.onChildrenAdded();
        fso8.onChildrenAdded();
        fuk_0 fuk_05 = new fuk_0();
        fuk_05.onCheckOut();
        fuk_05.setElementMap(fyy_02);
        fuk_05.setExpandable(false);
        fuk_05.setStyle("titleName12");
        fso5.addBasicElement(fuk_05);
        fuk_05.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_02);
        fip_23.setAlign(frs_0.e);
        fuk_05.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("text");
        fir_13.setField("totalCash");
        fuk_05.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fuk_05.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_02);
        fso10.setExpandable(false);
        fso5.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fic_14.setAdaptToContentSize(true);
        fso10.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_02);
        fso11.setExpandable(false);
        fso11.setStyle("lineSeparator");
        fso10.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_02);
        fid_17.setAlign(frk_0.o);
        fid_17.setSize(new fjf_2(100.0f, 7));
        fso11.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fso11.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        fsk_03.setExpandable(false);
        fsk_03.setStyle("ChestPoi");
        fso10.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_18 = new fid_1();
        fid_18.onCheckOut();
        fid_18.setElementMap(fyy_02);
        fid_18.setAlign(frk_0.h);
        fsk_03.addBasicElement(fid_18);
        fid_18.onAttributesInitialized();
        fid_18.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fuk_0 fuk_06 = new fuk_0();
        fuk_06.onCheckOut();
        fuk_06.setElementMap(fyy_02);
        fuk_06.setStyle("StyledBoldDark12");
        String string2 = "%inhabitantCount%";
        string2 = string2.replace("%inhabitantCount%", fpm_0.b().c("inhabitantCount"));
        fuk_06.c(string2);
        fso10.addBasicElement(fuk_06);
        fuk_06.onAttributesInitialized();
        fid_1 fid_19 = new fid_1();
        fid_19.onCheckOut();
        fid_19.setElementMap(fyy_02);
        fid_19.setAlign(frk_0.h);
        fuk_06.addBasicElement(fid_19);
        fid_19.onAttributesInitialized();
        fid_19.onChildrenAdded();
        fuk_0 fuk_07 = fuk_06;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_07).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fuk_06.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqo_0 fqo_05 = new fqo_0();
        fqo_05.onCheckOut();
        fqo_05.setElementMap(fyy_02);
        fqo_05.setInsets(new Insets(0, 32, 0, 0));
        fqh_03.addBasicElement(fqo_05);
        fqo_05.onAttributesInitialized();
        fqo_05.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fuk_06.onChildrenAdded();
        fso10.onChildrenAdded();
        fuk_0 fuk_08 = new fuk_0();
        fuk_08.onCheckOut();
        fuk_08.setElementMap(fyy_02);
        fuk_08.setExpandable(false);
        fuk_08.setStyle("titleName12");
        fso5.addBasicElement(fuk_08);
        fuk_08.onAttributesInitialized();
        fip_2 fip_24 = new fip_2();
        fip_24.onCheckOut();
        fip_24.setElementMap(fyy_02);
        fip_24.setAlign(frs_0.e);
        fuk_08.addBasicElement(fip_24);
        fip_24.onAttributesInitialized();
        fip_24.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("text");
        fir_14.setField("populationSize");
        fuk_08.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fuk_08.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_02);
        fso12.setExpandable(false);
        fso5.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fic_1 fic_15 = new fic_1();
        fic_15.onCheckOut();
        fic_15.setAdaptToContentSize(true);
        fso12.addBasicElement(fic_15);
        fic_15.onAttributesInitialized();
        fic_15.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_02);
        fso13.setExpandable(false);
        fso13.setStyle("lineSeparator");
        fso12.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fid_1 fid_110 = new fid_1();
        fid_110.onCheckOut();
        fid_110.setElementMap(fyy_02);
        fid_110.setAlign(frk_0.o);
        fid_110.setSize(new fjf_2(100.0f, 7));
        fso13.addBasicElement(fid_110);
        fid_110.onAttributesInitialized();
        fid_110.onChildrenAdded();
        fso13.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        fsk_04.setExpandable(false);
        fsk_04.setStyle("swordPoi");
        fso12.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fid_1 fid_111 = new fid_1();
        fid_111.onCheckOut();
        fid_111.setElementMap(fyy_02);
        fid_111.setAlign(frk_0.h);
        fsk_04.addBasicElement(fid_111);
        fid_111.onAttributesInitialized();
        fid_111.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fuk_0 fuk_09 = new fuk_0();
        fuk_09.onCheckOut();
        fuk_09.setElementMap(fyy_02);
        fuk_09.setStyle("StyledBoldDark12");
        String string3 = "%nation.governor%";
        string3 = string3.replace("%nation.governor%", fpm_0.b().c("nation.governor"));
        fuk_09.c(string3);
        fso12.addBasicElement(fuk_09);
        fuk_09.onAttributesInitialized();
        fid_1 fid_112 = new fid_1();
        fid_112.onCheckOut();
        fid_112.setElementMap(fyy_02);
        fid_112.setAlign(frk_0.h);
        fuk_09.addBasicElement(fid_112);
        fid_112.onAttributesInitialized();
        fid_112.onChildrenAdded();
        fuk_0 fuk_010 = fuk_09;
        fqh_0 fqh_04 = (fqh_0)((fvE)fuk_010).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fuk_09.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqo_0 fqo_06 = new fqo_0();
        fqo_06.onCheckOut();
        fqo_06.setElementMap(fyy_02);
        fqo_06.setInsets(new Insets(0, 32, 0, 0));
        fqh_04.addBasicElement(fqo_06);
        fqo_06.onAttributesInitialized();
        fqo_06.onChildrenAdded();
        fqh_04.onChildrenAdded();
        fuk_09.onChildrenAdded();
        fso12.onChildrenAdded();
        fuk_0 fuk_011 = new fuk_0();
        fuk_011.onCheckOut();
        fuk_011.setElementMap(fyy_02);
        fuk_011.setExpandable(false);
        fuk_011.setStyle("titleName12");
        fso5.addBasicElement(fuk_011);
        fuk_011.onAttributesInitialized();
        fip_2 fip_25 = new fip_2();
        fip_25.onCheckOut();
        fip_25.setElementMap(fyy_02);
        fip_25.setAlign(frs_0.e);
        fuk_011.addBasicElement(fip_25);
        fip_25.onAttributesInitialized();
        fip_25.onChildrenAdded();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("text");
        fir_15.setField("governorName");
        fuk_011.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fuk_011.onChildrenAdded();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_02);
        fso14.setExpandable(false);
        fso5.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        fic_1 fic_16 = new fic_1();
        fic_16.onCheckOut();
        fic_16.setAdaptToContentSize(true);
        fso14.addBasicElement(fic_16);
        fic_16.onAttributesInitialized();
        fic_16.onChildrenAdded();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_02);
        fso15.setExpandable(false);
        fso15.setStyle("lineSeparator");
        fso14.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fid_1 fid_113 = new fid_1();
        fid_113.onCheckOut();
        fid_113.setElementMap(fyy_02);
        fid_113.setAlign(frk_0.o);
        fid_113.setSize(new fjf_2(100.0f, 7));
        fso15.addBasicElement(fid_113);
        fid_113.onAttributesInitialized();
        fid_113.onChildrenAdded();
        fso15.onChildrenAdded();
        fsk_0 fsk_05 = new fsk_0();
        fsk_05.onCheckOut();
        fsk_05.setElementMap(fyy_02);
        fsk_05.setExpandable(false);
        fsk_05.setStyle("flagPoi");
        fso14.addBasicElement(fsk_05);
        fsk_05.onAttributesInitialized();
        fid_1 fid_114 = new fid_1();
        fid_114.onCheckOut();
        fid_114.setElementMap(fyy_02);
        fid_114.setAlign(frk_0.h);
        fid_114.setXOffset(5);
        fsk_05.addBasicElement(fid_114);
        fid_114.onAttributesInitialized();
        fid_114.onChildrenAdded();
        fsk_05.onChildrenAdded();
        fuk_0 fuk_012 = new fuk_0();
        fuk_012.onCheckOut();
        fuk_012.setElementMap(fyy_02);
        fuk_012.setStyle("StyledBoldDark12");
        String string4 = "%territoriesCount%";
        string4 = string4.replace("%territoriesCount%", fpm_0.b().c("territoriesCount"));
        fuk_012.c(string4);
        fso14.addBasicElement(fuk_012);
        fuk_012.onAttributesInitialized();
        fid_1 fid_115 = new fid_1();
        fid_115.onCheckOut();
        fid_115.setElementMap(fyy_02);
        fid_115.setAlign(frk_0.h);
        fuk_012.addBasicElement(fid_115);
        fid_115.onAttributesInitialized();
        fid_115.onChildrenAdded();
        fuk_0 fuk_013 = fuk_012;
        fqh_0 fqh_05 = (fqh_0)((fvE)fuk_013).getAppearance();
        fqh_05.setElementMap(fyy_02);
        fuk_012.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqo_0 fqo_07 = new fqo_0();
        fqo_07.onCheckOut();
        fqo_07.setElementMap(fyy_02);
        fqo_07.setInsets(new Insets(0, 32, 0, 0));
        fqh_05.addBasicElement(fqo_07);
        fqo_07.onAttributesInitialized();
        fqo_07.onChildrenAdded();
        fqh_05.onChildrenAdded();
        fuk_012.onChildrenAdded();
        fso14.onChildrenAdded();
        fuk_0 fuk_014 = new fuk_0();
        fuk_014.onCheckOut();
        fuk_014.setElementMap(fyy_02);
        fuk_014.setExpandable(false);
        fuk_014.setStyle("titleName12");
        fso5.addBasicElement(fuk_014);
        fuk_014.onAttributesInitialized();
        fip_2 fip_26 = new fip_2();
        fip_26.onCheckOut();
        fip_26.setElementMap(fyy_02);
        fip_26.setAlign(frs_0.e);
        fuk_014.addBasicElement(fip_26);
        fip_26.onAttributesInitialized();
        fip_26.onChildrenAdded();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_02);
        fir_16.setAttribute("text");
        fir_16.setField("territoriesCount");
        fuk_014.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        fir_16.onChildrenAdded();
        fuk_014.onChildrenAdded();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_02);
        fso16.setExpandable(false);
        fso5.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        this.d(fso16);
        this.e(fso16);
        this.f(fso16);
        this.g(fso16);
        fso16.onChildrenAdded();
        this.h(fso5);
        fso5.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso2.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        return null;
    }

    public fyo e(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setStyle("lineSeparator");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.o);
        fid_12.setSize(new fjf_2(100.0f, 7));
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo f(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setExpandable(false);
        fsk_02.setStyle("questionPoi");
        fso2.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.h);
        fid_12.setXOffset(5);
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fsk_02.onChildrenAdded();
        return fsk_02;
    }

    public fyo g(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setStyle("StyledBoldDark12");
        String string = "%nationAlignments%";
        string = string.replace("%nationAlignments%", fpm_0.b().c("nationAlignments"));
        fuk_02.c(string);
        fso2.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.h);
        fuk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(0, 32, 0, 0));
        fqh_02.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        return fuk_02;
    }

    public fyo h(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setStyle("titleName12");
        fso2.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.e);
        fuk_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("text");
        fir_12.setField("nationAlignments");
        fuk_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fuk_02.onChildrenAdded();
        return fuk_02;
    }

    public fyo i(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.o);
        fid_12.setSize(new fjf_2(215, -2));
        fid_12.setXOffset(-5);
        fid_12.setYOffset(50);
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(80, 80));
        fsk_02.setExpandable(false);
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.h);
        fsk_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("texture");
        fir_12.setField("nation/passportStampIconUrl");
        fqv2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        fsk_03.setDisplaySize(new fjf_2(140, 100));
        fsk_03.setExpandable(false);
        fso3.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.j);
        fsk_03.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fsk_03.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("texture");
        fir_13.setField("selectionIcon");
        fqv3.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fqv3.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo j(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setNonBlocking(true);
        fso3.setStyle("EncyclopediaPane");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.c);
        fid_12.setSize(new fjf_2(260, 100.0f));
        fid_12.setXOffset(-9);
        fid_12.setYOffset(1);
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 0, 35, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo a(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo b(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fru_02.setStyle("close");
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("unloadDialog");
        fru_02.setOnClick(fdt_12);
        fvk_02.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setSize(new fjf_2(-2, -2));
        fid_12.setXOffset(-18);
        fid_12.setYOffset(-12);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo c(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setInitValue(true);
        fid_12.setSize(new fjf_2(-2, -2));
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }
}

