/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cPU
 */
public class cpu_1
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fvc_0 fvc_02 = new fvc_0();
        fvc_02.onCheckOut();
        fvc_02.setElementMap(fyy_03);
        fvc_02.setAlign(frs_0.b);
        fvc_02.setYOffset(20);
        fvc_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(-2, -2));
        fvc_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fso2.setStyle("popup");
        fvc_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso2.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_03);
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso4.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("visible");
        fiy_12.setField("isFightSwordElement");
        fiy_12.setName("overHead");
        fso4.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_03);
        far_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setEnableShrinking(false);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(300);
        fuk_02.setMinWidth(1);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("DefaultWhite");
        fso4.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("text");
        fiy_13.setField("title");
        fiy_13.setName("overHead");
        fuk_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("visible");
        fiy_14.setField("title");
        fiy_14.setName("overHead");
        fuk_02.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        fiy_14.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        far_23.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_14.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(5, 0, 5, 0));
        fqh_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso4.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        String string = "overheadDialogStackList";
        fus_0 fus_02 = new fus_0();
        fus_02.onCheckOut();
        fus_02.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fus_02);
        }
        fus_02.setCursorType(frb_0.e);
        fus_02.setExpandable(false);
        fus_02.setHorizontal(false);
        fus_02.setInnerExpandable(false);
        fus_02.setNonBlocking(true);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu:transferClickEventToWorldInteractionFrame");
        fus_02.setOnClick(fdt_12);
        fus_02.setSelectionable(false);
        fso5.addBasicElement(fus_02);
        fus_02.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.f);
        fus_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fus_0 fus_03 = fus_02;
        fqr fqr2 = (fqr)((fvE)fus_03).getAppearance();
        fqr2.setElementMap(fyy_03);
        fus_02.addBasicElement(fqr2);
        fqr2.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 0, 0, 3));
        fqr2.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqr2.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("content");
        fiy_15.setField("overHeadInfos");
        fiy_15.setName("overHead");
        fus_02.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("visible");
        fiy_16.setField("overHeadInfos");
        fiy_16.setName("overHead");
        fus_02.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_03);
        fiy_16.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_03);
        far_24.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_24.onChildrenAdded();
        fiy_16.onChildrenAdded();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_03);
        fiy_17.setAttribute("visible");
        fiy_17.setName("bagOverHead");
        fus_02.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        String string2 = "overheadDialogItemRenderer";
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, faf_22);
        }
        fus_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_03);
        faf_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_03);
        fav_12.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fab_2 fab_24 = new fab_2();
        fab_24.onCheckOut();
        fab_24.setElementMap(fyy_03);
        far_25.addBasicElement(fab_24);
        fab_24.onAttributesInitialized();
        fab_24.onChildrenAdded();
        far_25.onChildrenAdded();
        fav_12.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_03);
        fso6.setNonBlocking(true);
        faf_22.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.d);
        fso6.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setDisplaySize(new fjf_2(32, 32));
        fsk_02.setExpandable(false);
        fsk_02.setNonBlocking(true);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu:transferClickEventToWorldInteractionFrame");
        fsk_02.setOnClick(fdt_13);
        fso6.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_03);
        fir_12.setAttribute("visible");
        fir_12.setField("iconUrl");
        fsk_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        far_2 far_26 = new far_2();
        far_26.onCheckOut();
        far_26.setElementMap(fyy_03);
        fir_12.addBasicElement(far_26);
        far_26.onAttributesInitialized();
        fab_2 fab_25 = new fab_2();
        fab_25.onCheckOut();
        fab_25.setElementMap(fyy_03);
        far_26.addBasicElement(fab_25);
        fab_25.onAttributesInitialized();
        fab_25.onChildrenAdded();
        far_26.onChildrenAdded();
        fir_12.onChildrenAdded();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_03);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(0, 0, 0, 3));
        fqp2.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqp2.onChildrenAdded();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setSize(new fjf_2(100.0f, 100.0f));
        fsk_02.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_03);
        fir_13.setAttribute("texture");
        fir_13.setField("iconUrl");
        fqv2.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_03);
        fuk_04.setEnableShrinking(false);
        fuk_04.setMaxWidth(300);
        fuk_04.setMinWidth(1);
        fuk_04.setNonBlocking(true);
        fdt_1 fdt_14 = new fdt_1();
        fdt_14.a("wakfu:transferClickEventToWorldInteractionFrame");
        fuk_04.setOnClick(fdt_14);
        fuk_04.setStyle("DefaultWhite");
        fso6.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_03);
        fip_23.setAlign(frs_0.e);
        fuk_04.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_03);
        fir_14.setAttribute("text");
        fir_14.setField("text");
        fuk_04.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_03);
        fso6.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fus_0 fus_04 = new fus_0();
        fus_04.onCheckOut();
        fus_04.setElementMap(fyy_03);
        fus_04.setNonBlocking(true);
        fdt_1 fdt_15 = new fdt_1();
        fdt_15.a("wakfu:transferClickEventToWorldInteractionFrame");
        fus_04.setOnClick(fdt_15);
        fso6.addBasicElement(fus_04);
        fus_04.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_03);
        fir_15.setAttribute("visible");
        fir_15.setField("overIconsUrl");
        fus_04.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        far_2 far_27 = new far_2();
        far_27.onCheckOut();
        far_27.setElementMap(fyy_03);
        fir_15.addBasicElement(far_27);
        far_27.onAttributesInitialized();
        fab_2 fab_26 = new fab_2();
        fab_26.onCheckOut();
        fab_26.setElementMap(fyy_03);
        far_27.addBasicElement(fab_26);
        fab_26.onAttributesInitialized();
        fab_26.onChildrenAdded();
        far_27.onChildrenAdded();
        fir_15.onChildrenAdded();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_03);
        fir_16.setAttribute("content");
        fir_16.setField("overIconsUrl");
        fus_04.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        fir_16.onChildrenAdded();
        faf_2 faf_23 = new faf_2();
        faf_23.onCheckOut();
        faf_23.setElementMap(fyy_03);
        fus_04.addBasicElement(faf_23);
        faf_23.onAttributesInitialized();
        fav_1 fav_13 = new fav_1();
        fav_13.onCheckOut();
        fav_13.setElementMap(fyy_03);
        faf_23.addBasicElement(fav_13);
        fav_13.onAttributesInitialized();
        far_2 far_28 = new far_2();
        far_28.onCheckOut();
        far_28.setElementMap(fyy_03);
        fav_13.addBasicElement(far_28);
        far_28.onAttributesInitialized();
        fab_2 fab_27 = new fab_2();
        fab_27.onCheckOut();
        fab_27.setElementMap(fyy_03);
        far_28.addBasicElement(fab_27);
        fab_27.onAttributesInitialized();
        fab_27.onChildrenAdded();
        far_28.onChildrenAdded();
        fav_13.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_03);
        fsk_04.setDisplaySize(new fjf_2(32, 32));
        fsk_04.setExpandable(false);
        fsk_04.setNonBlocking(true);
        faf_23.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_03);
        fsk_04.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fir_1 fir_17 = new fir_1();
        fir_17.onCheckOut();
        fir_17.setElementMap(fyy_03);
        fir_17.setAttribute("texture");
        fqv3.addBasicElement(fir_17);
        fir_17.onAttributesInitialized();
        fir_17.onChildrenAdded();
        fqv3.onChildrenAdded();
        fsk_04.onChildrenAdded();
        faf_23.onChildrenAdded();
        fus_04.onChildrenAdded();
        fso6.onChildrenAdded();
        faf_22.onChildrenAdded();
        fus_02.onChildrenAdded();
        fsk_0 fsk_05 = new fsk_0();
        fsk_05.onCheckOut();
        fsk_05.setElementMap(fyy_03);
        fsk_05.setStyle("connectedStatut");
        fso5.addBasicElement(fsk_05);
        fsk_05.onAttributesInitialized();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_03);
        fiy_18.setAttribute("visible");
        fiy_18.setField("ownerStatus");
        fiy_18.setName("overHead");
        fsk_05.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        fiy_18.onChildrenAdded();
        fsk_05.onChildrenAdded();
        fso5.onChildrenAdded();
        fso4.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso3.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setHorizontal(false);
        fso7.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_03);
        fiy_19.setAttribute("visible");
        fiy_19.setField("isFightSwordElement");
        fiy_19.setName("overHead");
        fso7.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        far_2 far_29 = new far_2();
        far_29.onCheckOut();
        far_29.setElementMap(fyy_03);
        fiy_19.addBasicElement(far_29);
        far_29.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_03);
        far_29.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_29.onChildrenAdded();
        fiy_19.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso7.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_03);
        fso9.setPrefSize(new fjf_2(250, 0));
        fso8.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fuk_0 fuk_05 = new fuk_0();
        fuk_05.onCheckOut();
        fuk_05.setElementMap(fyy_03);
        fuk_05.setEnableShrinking(false);
        fuk_05.setExpandable(false);
        fuk_05.setMaxWidth(250);
        fuk_05.setNonBlocking(true);
        fuk_05.setStyle("StyledBold16White");
        fso9.addBasicElement(fuk_05);
        fuk_05.onAttributesInitialized();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_03);
        fiy_110.setAttribute("text");
        fiy_110.setField("fightStatus");
        fiy_110.setName("overHead");
        fuk_05.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        fiy_110.onChildrenAdded();
        fiy_1 fiy_111 = fiy_1.checkOut();
        fiy_111.setElementMap(fyy_03);
        fiy_111.setAttribute("visible");
        fiy_111.setField("fightStatus");
        fiy_111.setName("overHead");
        fuk_05.addBasicElement(fiy_111);
        fiy_111.onAttributesInitialized();
        this.a(fiy_111);
        fiy_111.onChildrenAdded();
        fuk_05.onChildrenAdded();
        fso9.onChildrenAdded();
        this.a(fso8);
        this.b(fso8);
        fso8.onChildrenAdded();
        this.c(fso7);
        this.d(fso7);
        fso7.onChildrenAdded();
        fso3.onChildrenAdded();
        this.f(fso2);
        this.g(fso2);
        this.h(fso2);
        fso2.onChildrenAdded();
        fvc_02.onChildrenAdded();
        return fvc_02;
    }

    public fyo a(fiy_1 fiy_12) {
        fyy_0 fyy_02 = this.a.peek();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        return far_22;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setExpandable(false);
        fsk_02.setStyle("verticalSeparator2");
        fso2.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 5, 0, 5));
        fqp2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqp2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        return fsk_02;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setPrefSize(new fjf_2(250, 0));
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setEnableShrinking(false);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(250);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("StyledBold16White");
        fso3.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("fightInfos");
        fiy_12.setName("overHead");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("visible");
        fiy_13.setField("fightInfos");
        fiy_13.setName("overHead");
        fuk_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_13.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(10, 0, 10, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setPrefSize(new fjf_2(60, 0));
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso5.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setEnableShrinking(false);
        fuk_02.setExpandable(false);
        fuk_02.setStyle("WhiteTitle");
        fso5.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("attackerTeamTotalLevel");
        fiy_12.setName("overHead");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso5.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso3.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fus_0 fus_02 = new fus_0();
        fus_02.onCheckOut();
        fus_02.setElementMap(fyy_02);
        fus_02.setExpandable(false);
        fus_02.setHorizontal(false);
        fus_02.setInnerExpandable(false);
        fus_02.setNonBlocking(true);
        fus_02.setSelectionable(false);
        fso6.addBasicElement(fus_02);
        fus_02.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("content");
        fiy_13.setField("overHeadInfos");
        fiy_13.setName("overHead");
        fus_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("visible");
        fiy_14.setField("overHeadInfos");
        fiy_14.setName("overHead");
        fus_02.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_14.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_14.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fus_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        faf_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        fav_12.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_02);
        far_23.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_23.onChildrenAdded();
        fav_12.onChildrenAdded();
        fuk_0 fuk_03 = new fuk_0();
        fuk_03.onCheckOut();
        fuk_03.setElementMap(fyy_02);
        fuk_03.setEnableShrinking(false);
        fuk_03.setMaxWidth(300);
        fuk_03.setNonBlocking(true);
        fuk_03.setStyle("WhiteTitle");
        faf_22.addBasicElement(fuk_03);
        fuk_03.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("text");
        fir_12.setField("text");
        fuk_03.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fuk_03.onChildrenAdded();
        faf_22.onChildrenAdded();
        fus_02.onChildrenAdded();
        fso6.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso7.setPrefSize(new fjf_2(60, 0));
        fso3.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.f);
        fso7.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_02);
        fuk_04.setEnableShrinking(false);
        fuk_04.setExpandable(false);
        fuk_04.setStyle("WhiteTitle");
        fso7.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("text");
        fiy_15.setField("defenderTeamTotalLevel");
        fiy_15.setName("overHead");
        fuk_04.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fso7.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setExpandable(false);
        fso4.setPrefSize(new fjf_2(250, 0));
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fus_0 fus_02 = new fus_0();
        fus_02.onCheckOut();
        fus_02.setElementMap(fyy_02);
        fus_02.setCursorType(frb_0.e);
        fus_02.setHorizontal(false);
        fus_02.setInnerExpandable(false);
        fus_02.setNonBlocking(true);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu:transferClickEventToWorldInteractionFrame");
        fus_02.setOnClick(fdt_12);
        fus_02.setSelectionable(false);
        fso4.addBasicElement(fus_02);
        fus_02.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.b);
        fus_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fus_0 fus_03 = fus_02;
        fqr fqr2 = (fqr)((fvE)fus_03).getAppearance();
        fqr2.setElementMap(fyy_02);
        fus_02.addBasicElement(fqr2);
        fqr2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 0, 0, 3));
        fqr2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqr2.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("attackerOverHeadInfos");
        fiy_12.setName("overHead");
        fus_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("visible");
        fiy_13.setField("attackerOverHeadInfos");
        fiy_13.setName("overHead");
        fus_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_13.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_13.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fus_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        faf_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        fav_12.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_02);
        far_23.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_23.onChildrenAdded();
        fav_12.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        faf_22.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso fso6 = fso5;
        fqj fqj2 = ((fvE)fso6).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso5.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 0, 5, 0));
        fqj2.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj2.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(32, 32));
        fsk_02.setExpandable(false);
        fsk_02.setNonBlocking(true);
        fsk_02.setPrefSize(new fjf_2(32, 32));
        fso5.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("visible");
        fiy_14.setField("isAttackerPlayerCharacter");
        fiy_14.setName("overHead");
        fsk_02.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_02);
        fiy_14.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_24.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_24.onChildrenAdded();
        fiy_14.onChildrenAdded();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 0, 0, 3));
        fqp2.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqp2.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("texture");
        fir_12.setField("guildIconUrl");
        fqv2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        fsk_04.setDisplaySize(new fjf_2(32, 32));
        fsk_04.setExpandable(false);
        fsk_04.setNonBlocking(true);
        fsk_04.setPrefSize(new fjf_2(32, 32));
        fso5.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fsk_0 fsk_05 = fsk_04;
        fqp fqp3 = (fqp)((fvE)fsk_05).getAppearance();
        fqp3.setElementMap(fyy_02);
        fsk_04.addBasicElement(fqp3);
        fqp3.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_02);
        fqm_05.setInsets(new Insets(0, 0, 0, 3));
        fqp3.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqp3.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fsk_04.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("texture");
        fir_13.setField("iconUrl");
        fqv3.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fqv3.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setEnableShrinking(false);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(150);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("DefaultWhite");
        fso5.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_02);
        fqm_06.setInsets(new Insets(0, 0, 0, 15));
        fqh_02.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("text");
        fir_14.setField("text");
        fuk_02.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_02);
        fso5.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso7.setExpandable(false);
        fso7.setPrefSize(new fjf_2(32, 32));
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fsk_0 fsk_06 = new fsk_0();
        fsk_06.onCheckOut();
        fsk_06.setElementMap(fyy_02);
        fsk_06.setDisplaySize(new fjf_2(32, 24));
        fsk_06.setStyle("characterSkull");
        fso7.addBasicElement(fsk_06);
        fsk_06.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("visible");
        fir_15.setField("isDead");
        fsk_06.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_02);
        fir_15.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fai_1 fai_13 = new fai_1();
        fai_13.onCheckOut();
        fai_13.setElementMap(fyy_02);
        far_25.addBasicElement(fai_13);
        fai_13.onAttributesInitialized();
        fai_13.onChildrenAdded();
        far_25.onChildrenAdded();
        fir_15.onChildrenAdded();
        fsk_06.onChildrenAdded();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        faf_22.onChildrenAdded();
        fus_02.onChildrenAdded();
        fso4.onChildrenAdded();
        fsk_0 fsk_07 = new fsk_0();
        fsk_07.onCheckOut();
        fsk_07.setElementMap(fyy_02);
        fsk_07.setExpandable(false);
        fsk_07.setStyle("verticalSeparator2");
        fso3.addBasicElement(fsk_07);
        fsk_07.onAttributesInitialized();
        fsk_0 fsk_08 = fsk_07;
        fqp fqp4 = (fqp)((fvE)fsk_08).getAppearance();
        fqp4.setElementMap(fyy_02);
        fsk_07.addBasicElement(fqp4);
        fqp4.onAttributesInitialized();
        fqm_0 fqm_07 = fqm_0.checkOut();
        fqm_07.setElementMap(fyy_02);
        fqm_07.setInsets(new Insets(0, 5, 0, 5));
        fqp4.addBasicElement(fqm_07);
        fqm_07.onAttributesInitialized();
        fqm_07.onChildrenAdded();
        fqp4.onChildrenAdded();
        fsk_07.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso8.setExpandable(false);
        fso8.setNonBlocking(true);
        fso8.setPrefSize(new fjf_2(250, 0));
        fso3.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fus_0 fus_04 = new fus_0();
        fus_04.onCheckOut();
        fus_04.setElementMap(fyy_02);
        fus_04.setCursorType(frb_0.e);
        fus_04.setHorizontal(false);
        fus_04.setInnerExpandable(false);
        fus_04.setNonBlocking(true);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu:transferClickEventToWorldInteractionFrame");
        fus_04.setOnClick(fdt_13);
        fus_04.setSelectionable(false);
        fso8.addBasicElement(fus_04);
        fus_04.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_02);
        fip_23.setAlign(frs_0.b);
        fus_04.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fus_0 fus_05 = fus_04;
        fqr fqr3 = (fqr)((fvE)fus_05).getAppearance();
        fqr3.setElementMap(fyy_02);
        fus_04.addBasicElement(fqr3);
        fqr3.onAttributesInitialized();
        fqm_0 fqm_08 = fqm_0.checkOut();
        fqm_08.setElementMap(fyy_02);
        fqm_08.setInsets(new Insets(0, 3, 0, 0));
        fqr3.addBasicElement(fqm_08);
        fqm_08.onAttributesInitialized();
        fqm_08.onChildrenAdded();
        fqr3.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("content");
        fiy_15.setField("defenderOverHeadInfos");
        fiy_15.setName("overHead");
        fus_04.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_02);
        fiy_16.setAttribute("visible");
        fiy_16.setField("defenderOverHeadInfos");
        fiy_16.setName("overHead");
        fus_04.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        far_2 far_26 = new far_2();
        far_26.onCheckOut();
        far_26.setElementMap(fyy_02);
        fiy_16.addBasicElement(far_26);
        far_26.onAttributesInitialized();
        fab_2 fab_24 = new fab_2();
        fab_24.onCheckOut();
        fab_24.setElementMap(fyy_02);
        far_26.addBasicElement(fab_24);
        fab_24.onAttributesInitialized();
        fab_24.onChildrenAdded();
        far_26.onChildrenAdded();
        fiy_16.onChildrenAdded();
        faf_2 faf_23 = new faf_2();
        faf_23.onCheckOut();
        faf_23.setElementMap(fyy_02);
        fus_04.addBasicElement(faf_23);
        faf_23.onAttributesInitialized();
        fav_1 fav_13 = new fav_1();
        fav_13.onCheckOut();
        fav_13.setElementMap(fyy_02);
        faf_23.addBasicElement(fav_13);
        fav_13.onAttributesInitialized();
        far_2 far_27 = new far_2();
        far_27.onCheckOut();
        far_27.setElementMap(fyy_02);
        fav_13.addBasicElement(far_27);
        far_27.onAttributesInitialized();
        fab_2 fab_25 = new fab_2();
        fab_25.onCheckOut();
        fab_25.setElementMap(fyy_02);
        far_27.addBasicElement(fab_25);
        fab_25.onAttributesInitialized();
        fab_25.onChildrenAdded();
        far_27.onChildrenAdded();
        fav_13.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_02);
        faf_23.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fso fso10 = fso9;
        fqj fqj3 = ((fvE)fso10).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso9.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_09 = fqm_0.checkOut();
        fqm_09.setElementMap(fyy_02);
        fqm_09.setInsets(new Insets(0, 0, 5, 0));
        fqj3.addBasicElement(fqm_09);
        fqm_09.onAttributesInitialized();
        fqm_09.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_02);
        fso11.setExpandable(false);
        fso11.setPrefSize(new fjf_2(32, 32));
        fso9.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fsk_0 fsk_09 = new fsk_0();
        fsk_09.onCheckOut();
        fsk_09.setElementMap(fyy_02);
        fsk_09.setDisplaySize(new fjf_2(32, 24));
        fsk_09.setStyle("characterSkull");
        fso11.addBasicElement(fsk_09);
        fsk_09.onAttributesInitialized();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_02);
        fir_16.setAttribute("visible");
        fir_16.setField("isDead");
        fsk_09.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        far_2 far_28 = new far_2();
        far_28.onCheckOut();
        far_28.setElementMap(fyy_02);
        fir_16.addBasicElement(far_28);
        far_28.onAttributesInitialized();
        fai_1 fai_14 = new fai_1();
        fai_14.onCheckOut();
        fai_14.setElementMap(fyy_02);
        far_28.addBasicElement(fai_14);
        fai_14.onAttributesInitialized();
        fai_14.onChildrenAdded();
        far_28.onChildrenAdded();
        fir_16.onChildrenAdded();
        fsk_09.onChildrenAdded();
        fso11.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_02);
        fuk_04.setEnableShrinking(false);
        fuk_04.setExpandable(true);
        fuk_04.setMaxWidth(150);
        fuk_04.setNonBlocking(true);
        fuk_04.setStyle("DefaultWhite");
        fso9.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fuk_0 fuk_05 = fuk_04;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_05).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fuk_04.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_010 = fqm_0.checkOut();
        fqm_010.setElementMap(fyy_02);
        fqm_010.setInsets(new Insets(0, 15, 0, 10));
        fqh_03.addBasicElement(fqm_010);
        fqm_010.onAttributesInitialized();
        fqm_010.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fir_1 fir_17 = new fir_1();
        fir_17.onCheckOut();
        fir_17.setElementMap(fyy_02);
        fir_17.setAttribute("text");
        fir_17.setField("text");
        fuk_04.addBasicElement(fir_17);
        fir_17.onAttributesInitialized();
        fir_17.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fsk_0 fsk_010 = new fsk_0();
        fsk_010.onCheckOut();
        fsk_010.setElementMap(fyy_02);
        fsk_010.setDisplaySize(new fjf_2(32, 32));
        fsk_010.setExpandable(false);
        fsk_010.setNonBlocking(true);
        fsk_010.setPrefSize(new fjf_2(32, 32));
        fso9.addBasicElement(fsk_010);
        fsk_010.onAttributesInitialized();
        fsk_0 fsk_011 = fsk_010;
        fqp fqp5 = (fqp)((fvE)fsk_011).getAppearance();
        fqp5.setElementMap(fyy_02);
        fsk_010.addBasicElement(fqp5);
        fqp5.onAttributesInitialized();
        fqm_0 fqm_011 = fqm_0.checkOut();
        fqm_011.setElementMap(fyy_02);
        fqm_011.setInsets(new Insets(0, 3, 0, 0));
        fqp5.addBasicElement(fqm_011);
        fqm_011.onAttributesInitialized();
        fqm_011.onChildrenAdded();
        fqp5.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_02);
        fsk_010.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fir_1 fir_18 = new fir_1();
        fir_18.onCheckOut();
        fir_18.setElementMap(fyy_02);
        fir_18.setAttribute("texture");
        fir_18.setField("iconUrl");
        fqv4.addBasicElement(fir_18);
        fir_18.onAttributesInitialized();
        fir_18.onChildrenAdded();
        fqv4.onChildrenAdded();
        fsk_010.onChildrenAdded();
        this.e(fso9);
        fso9.onChildrenAdded();
        faf_23.onChildrenAdded();
        fus_04.onChildrenAdded();
        fso8.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo e(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(32, 32));
        fsk_02.setExpandable(false);
        fsk_02.setNonBlocking(true);
        fsk_02.setPrefSize(new fjf_2(32, 32));
        fso2.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("isDefenderPlayerCharacter");
        fiy_12.setName("overHead");
        fsk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 3, 0, 0));
        fqp2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqp2.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("texture");
        fir_12.setField("guildIconUrl");
        fqv2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        return fsk_02;
    }

    public fyo f(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.a);
        fid_12.setXOffset(26);
        fid_12.setYOffset(-7);
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("isFightSwordElement");
        fiy_12.setName("overHead");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("style");
        fiy_13.setField("isAttackerPlayerCharacter");
        fiy_13.setName("overHead");
        fsk_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        far_23.setElseValue("topLeftCornerNonPlayerCharacter");
        far_23.setValue("topLeftCornerPlayerCharacter");
        fiy_13.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fai_1 fai_13 = new fai_1();
        fai_13.onCheckOut();
        fai_13.setElementMap(fyy_02);
        far_23.addBasicElement(fai_13);
        fai_13.onAttributesInitialized();
        fai_13.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo g(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setXOffset(-26);
        fid_12.setYOffset(-7);
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("isFightSwordElement");
        fiy_12.setName("overHead");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        far_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("style");
        fiy_13.setField("isDefenderPlayerCharacter");
        fiy_13.setName("overHead");
        fsk_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        far_23.setElseValue("topRightCornerNonPlayerCharacter");
        far_23.setValue("topRightCornerPlayerCharacter");
        fiy_13.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fai_1 fai_13 = new fai_1();
        fai_13.onCheckOut();
        fai_13.setElementMap(fyy_02);
        far_23.addBasicElement(fai_13);
        fai_13.onAttributesInitialized();
        fai_13.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo h(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("isFightSwordElement");
        fiy_12.setName("overHead");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        far_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("visible");
        fiy_13.setField("breedIconUrl");
        fiy_13.setName("overHead");
        fso3.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        fiy_13.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_23.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setExpandable(false);
        fsk_02.setNonBlocking(true);
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setXOffset(-7);
        fid_13.setYOffset(-1);
        fsk_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("modulationColor");
        fiy_14.setField("breedIconColor");
        fiy_14.setName("overHead");
        fqp2.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fqp2.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("texture");
        fiy_15.setField("breedIconUrl");
        fiy_15.setName("overHead");
        fqv2.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }
}

