/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cPz
 */
public class cpz_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        fvk_02.setNonBlocking(true);
        fvk_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvk_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("windowNew");
        fvk_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(10, 5, 12, 5));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setExpandable(false);
        fso3.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fvM fvM3 = fvM2;
        fqj fqj3 = ((fvE)fvM3).getAppearance();
        fqj3.setElementMap(fyy_03);
        fvM2.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 10, 0, 10));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setStyle("titleBar");
        fvM2.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso fso6 = fso5;
        fqj fqj4 = ((fvE)fso6).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso5.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(3, 20, 3, 20));
        fqj4.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.e);
        fso7.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("StyledBold16White");
        fsM2.c("Mix Debugger");
        fso7.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        fvM2.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso3.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj5 = ((fvE)fso9).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso8.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 12, 0, 12));
        fqj5.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj5.onChildrenAdded();
        String string = "windowContentContainer";
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fso10);
        }
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso10.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.b);
        fin_24.setHorizontal(false);
        fso11.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        fso12.setExpandable(false);
        fso12.setStyle("white");
        fso11.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fso fso13 = fso12;
        fqj fqj6 = ((fvE)fso13).getAppearance();
        fqj6.setElementMap(fyy_03);
        fso12.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_03);
        fqo_04.setInsets(new Insets(10, 10, 10, 10));
        fqj6.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj6.onChildrenAdded();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setAlign(frs_0.b);
        fin_25.setHorizontal(false);
        fso12.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_03);
        fsM4.setExpandable(false);
        fsM4.setStyle("bold");
        fsM4.c("Criterions :");
        fso12.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM4.onChildrenAdded();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_03);
        fso14.setExpandable(false);
        fso14.setPrefSize(new fjf_2(0, 100));
        fso14.setStyle("ShortcutRowBackground");
        fso12.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        fue_0 fue_02 = new fue_0();
        fue_02.onCheckOut();
        fue_02.setElementMap(fyy_03);
        fue_02.setVerticalScrollBarPosition(1.0f);
        fso14.addBasicElement(fue_02);
        fue_02.onAttributesInitialized();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(350);
        fuk_02.setMinWidth(0);
        fuk_02.setStyle("11");
        fue_02.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fuk_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(0, 5, 0, 0));
        fqh_03.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("text");
        fiy_12.setField("criterions");
        fiy_12.setName("mixDebugger");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fue_02.onChildrenAdded();
        fso14.onChildrenAdded();
        fso12.onChildrenAdded();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_03);
        fso15.setExpandable(false);
        fso15.setStyle("white");
        fso11.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fso fso16 = fso15;
        fqj fqj7 = ((fvE)fso16).getAppearance();
        fqj7.setElementMap(fyy_03);
        fso15.addBasicElement(fqj7);
        fqj7.onAttributesInitialized();
        fqo_0 fqo_05 = new fqo_0();
        fqo_05.onCheckOut();
        fqo_05.setElementMap(fyy_03);
        fqo_05.setInsets(new Insets(10, 10, 10, 10));
        fqj7.addBasicElement(fqo_05);
        fqo_05.onAttributesInitialized();
        fqo_05.onChildrenAdded();
        fqj7.onChildrenAdded();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setAlign(frs_0.b);
        fin_26.setHorizontal(false);
        fso15.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        fsM fsM5 = new fsM();
        fsM5.onCheckOut();
        fsM5.setElementMap(fyy_03);
        fsM5.setExpandable(false);
        fsM5.setStyle("bold");
        fsM5.c("Events :");
        fso15.addBasicElement(fsM5);
        fsM5.onAttributesInitialized();
        fsM5.onChildrenAdded();
        fso fso17 = fso.checkOut();
        fso17.setElementMap(fyy_03);
        fso17.setExpandable(false);
        fso17.setPrefSize(new fjf_2(0, 100));
        fso17.setStyle("ShortcutRowBackground");
        fso15.addBasicElement(fso17);
        fso17.onAttributesInitialized();
        fue_0 fue_03 = new fue_0();
        fue_03.onCheckOut();
        fue_03.setElementMap(fyy_03);
        fue_03.setVerticalScrollBarPosition(1.0f);
        fso17.addBasicElement(fue_03);
        fue_03.onAttributesInitialized();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_03);
        fuk_04.setExpandable(false);
        fuk_04.setMaxWidth(350);
        fuk_04.setMinWidth(0);
        fuk_04.setStyle("11");
        fue_03.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fuk_0 fuk_05 = fuk_04;
        fqh_0 fqh_04 = (fqh_0)((fvE)fuk_05).getAppearance();
        fqh_04.setElementMap(fyy_03);
        fuk_04.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(0, 5, 0, 0));
        fqh_04.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqh_04.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("text");
        fiy_13.setField("events");
        fiy_13.setName("mixDebugger");
        fuk_04.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fue_03.onChildrenAdded();
        fso17.onChildrenAdded();
        fso15.onChildrenAdded();
        fso fso18 = fso.checkOut();
        fso18.setElementMap(fyy_03);
        fso18.setStyle("white");
        fso11.addBasicElement(fso18);
        fso18.onAttributesInitialized();
        fso fso19 = fso18;
        fqj fqj8 = ((fvE)fso19).getAppearance();
        fqj8.setElementMap(fyy_03);
        fso18.addBasicElement(fqj8);
        fqj8.onAttributesInitialized();
        fqo_0 fqo_06 = new fqo_0();
        fqo_06.onCheckOut();
        fqo_06.setElementMap(fyy_03);
        fqo_06.setInsets(new Insets(10, 10, 10, 10));
        fqj8.addBasicElement(fqo_06);
        fqo_06.onAttributesInitialized();
        fqo_06.onChildrenAdded();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_03);
        fqm_06.setInsets(new Insets(5, 0, 0, 0));
        fqj8.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqj8.onChildrenAdded();
        fin_2 fin_27 = fin_2.checkOut();
        fin_27.setAlign(frs_0.b);
        fin_27.setHorizontal(false);
        fso18.addBasicElement(fin_27);
        fin_27.onAttributesInitialized();
        fin_27.onChildrenAdded();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_03);
        fsM6.setExpandable(false);
        fsM6.setStyle("bold");
        fsM6.c("Cache :");
        fso18.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fsM6.onChildrenAdded();
        fso fso20 = fso.checkOut();
        fso20.setElementMap(fyy_03);
        fso20.setExpandable(false);
        fso18.addBasicElement(fso20);
        fso20.onAttributesInitialized();
        fin_2 fin_28 = fin_2.checkOut();
        fin_28.setAlign(frs_0.d);
        fso20.addBasicElement(fin_28);
        fin_28.onAttributesInitialized();
        fin_28.onChildrenAdded();
        fsM fsM7 = new fsM();
        fsM7.onCheckOut();
        fsM7.setElementMap(fyy_03);
        fsM7.setExpandable(false);
        fsM7.c("Memory : ");
        fso20.addBasicElement(fsM7);
        fsM7.onAttributesInitialized();
        fsM7.onChildrenAdded();
        fsM fsM8 = new fsM();
        fsM8.onCheckOut();
        fsM8.setElementMap(fyy_03);
        fsM8.setExpandable(false);
        fsM8.setStyle("11Dark");
        fso20.addBasicElement(fsM8);
        fsM8.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("text");
        fiy_14.setField("memoryCache");
        fiy_14.setName("mixDebugger");
        fsM8.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fsM8.onChildrenAdded();
        fsM fsM9 = new fsM();
        fsM9.onCheckOut();
        fsM9.setElementMap(fyy_03);
        fsM9.setExpandable(false);
        fsM9.c("Sources size ");
        fso20.addBasicElement(fsM9);
        fsM9.onAttributesInitialized();
        fsM fsM10 = fsM9;
        fqh_0 fqh_05 = (fqh_0)((fvE)fsM10).getAppearance();
        fqh_05.setElementMap(fyy_03);
        fsM9.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqm_0 fqm_07 = fqm_0.checkOut();
        fqm_07.setElementMap(fyy_03);
        fqm_07.setInsets(new Insets(0, 5, 0, 0));
        fqh_05.addBasicElement(fqm_07);
        fqm_07.onAttributesInitialized();
        fqm_07.onChildrenAdded();
        fqh_05.onChildrenAdded();
        fsM9.onChildrenAdded();
        fsM fsM11 = new fsM();
        fsM11.onCheckOut();
        fsM11.setElementMap(fyy_03);
        fsM11.setExpandable(false);
        fsM11.c("cache : ");
        fso20.addBasicElement(fsM11);
        fsM11.onAttributesInitialized();
        fsM11.onChildrenAdded();
        fsM fsM12 = new fsM();
        fsM12.onCheckOut();
        fsM12.setElementMap(fyy_03);
        fsM12.setExpandable(false);
        fsM12.setStyle("11Dark");
        fso20.addBasicElement(fsM12);
        fsM12.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("text");
        fiy_15.setField("cacheSourcesTotalSize");
        fiy_15.setName("mixDebugger");
        fsM12.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fsM12.onChildrenAdded();
        fsM fsM13 = new fsM();
        fsM13.onCheckOut();
        fsM13.setElementMap(fyy_03);
        fsM13.setExpandable(false);
        fsM13.c("played : ");
        fso20.addBasicElement(fsM13);
        fsM13.onAttributesInitialized();
        fsM fsM14 = fsM13;
        fqh_0 fqh_06 = (fqh_0)((fvE)fsM14).getAppearance();
        fqh_06.setElementMap(fyy_03);
        fsM13.addBasicElement(fqh_06);
        fqh_06.onAttributesInitialized();
        fqm_0 fqm_08 = fqm_0.checkOut();
        fqm_08.setElementMap(fyy_03);
        fqm_08.setInsets(new Insets(0, 5, 0, 0));
        fqh_06.addBasicElement(fqm_08);
        fqm_08.onAttributesInitialized();
        fqm_08.onChildrenAdded();
        fqh_06.onChildrenAdded();
        fsM13.onChildrenAdded();
        fsM fsM15 = new fsM();
        fsM15.onCheckOut();
        fsM15.setElementMap(fyy_03);
        fsM15.setExpandable(false);
        fsM15.setStyle("11Dark");
        fso20.addBasicElement(fsM15);
        fsM15.onAttributesInitialized();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("text");
        fiy_16.setField("sourcesTotalSize");
        fiy_16.setName("mixDebugger");
        fsM15.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fsM15.onChildrenAdded();
        fso20.onChildrenAdded();
        String string2 = "tabbedContainer";
        fut_0 fut_02 = new fut_0();
        fut_02.onCheckOut();
        fut_02.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fut_02);
        }
        fut_02.setTabsAlignment(fro_0.d);
        fut_02.setTabsLabelAlignment(frs_0.e);
        fut_02.setTabsPosition(frm_0.a);
        fut_02.setTabsSizesEquilibrate(false);
        fut_02.setTextOrientation(frh_0.c);
        fso18.addBasicElement(fut_02);
        fut_02.onAttributesInitialized();
        fut_0 fut_03 = fut_02;
        fqj fqj9 = ((fvE)fut_03).getAppearance();
        fqj9.setElementMap(fyy_03);
        fut_02.addBasicElement(fqj9);
        fqj9.onAttributesInitialized();
        fqm_0 fqm_09 = fqm_0.checkOut();
        fqm_09.setElementMap(fyy_03);
        fqm_09.setInsets(new Insets(5, 0, 0, 0));
        fqj9.addBasicElement(fqm_09);
        fqm_09.onAttributesInitialized();
        fqm_09.onChildrenAdded();
        fqj9.onChildrenAdded();
        this.a(fut_02);
        this.b(fut_02);
        this.c(fut_02);
        fut_02.onChildrenAdded();
        fso18.onChildrenAdded();
        fso11.onChildrenAdded();
        fso10.onChildrenAdded();
        fso8.onChildrenAdded();
        fso3.onChildrenAdded();
        this.a(fvk_02);
        this.b(fvk_02);
        this.c(fvk_02);
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fut_0 fut_02) {
        fyy_0 fyy_02 = this.a.peek();
        fin_1 fin_12 = new fin_1();
        fin_12.onCheckOut();
        fin_12.setElementMap(fyy_02);
        fin_12.setText("Log");
        fut_02.addBasicElement(fin_12);
        fin_12.onAttributesInitialized();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fso2.setPrefSize(new fjf_2(0, 150));
        fso2.setStyle("ShortcutRowBackground");
        fin_12.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso2.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setStyle("caracs");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        fsQ2.setCellSize(new fjf_2(125, 25));
        fsQ2.setPrefSize(new fjf_2(250, 75));
        fso3.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("cache");
        fiy_12.setName("mixDebugger");
        fsQ2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        faf_22.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso4.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        String string = "soundGroup";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fij_12);
        }
        fso4.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("value");
        fij_12.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fij_12.onChildrenAdded();
        fup_0 fup_02 = new fup_0();
        fup_02.onCheckOut();
        fup_02.setElementMap(fyy_02);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.mixDebugger:selectLogSoundGroup(soundGroup)");
        fup_02.setOnClick(fdt_12);
        fup_02.setStyle("flat");
        fso4.addBasicElement(fup_02);
        fup_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fup_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("selected");
        fir_13.setField("logFiltered");
        fup_02.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fup_02.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("bold");
        fso4.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("text");
        fir_14.setField("name");
        fsM2.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fsM2.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso4.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso3.onChildrenAdded();
        fue_0 fue_02 = new fue_0();
        fue_02.onCheckOut();
        fue_02.setElementMap(fyy_02);
        fue_02.setVerticalScrollBarPosition(0.0f);
        fso2.addBasicElement(fue_02);
        fue_02.onAttributesInitialized();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(325);
        fuk_02.setMinWidth(0);
        fuk_02.setStyle("11");
        fue_02.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 5, 0, 0));
        fqh_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("text");
        fiy_13.setField("log");
        fiy_13.setName("mixDebugger");
        fuk_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fue_02.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setExpandable(false);
        fso5.setStyle("caracs");
        fso2.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.f);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fup_0 fup_03 = new fup_0();
        fup_03.onCheckOut();
        fup_03.setElementMap(fyy_02);
        fup_03.setExpandable(false);
        fdi_2 fdi_22 = new fdi_2();
        fdi_22.a("wakfu.mixDebugger:pause");
        fup_03.setOnSelectionChange(fdi_22);
        fup_03.setStyle("flat");
        fup_03.setText("Pause");
        fso5.addBasicElement(fup_03);
        fup_03.onAttributesInitialized();
        fup_03.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_02);
        fso5.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.mixDebugger:chooseSaveDirectory");
        fru_02.setOnClick(fdt_13);
        fru_02.setText("...");
        fso5.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_02.onChildrenAdded();
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_02);
        fru_03.setExpandable(false);
        fdt_1 fdt_14 = new fdt_1();
        fdt_14.a("wakfu.mixDebugger:save");
        fru_03.setOnClick(fdt_14);
        fru_03.setText("Save");
        fso5.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        fru_03.onChildrenAdded();
        fvp_0 fvp_02 = new fvp_0();
        fvp_02.onCheckOut();
        fvp_02.setElementMap(fyy_02);
        fvp_02.setExpandable(false);
        fvp_02.setPointAlign(frs_0.i);
        fso5.addBasicElement(fvp_02);
        fvp_02.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fvp_02.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fru_0 fru_04 = new fru_0();
        fru_04.onCheckOut();
        fru_04.setElementMap(fyy_02);
        fru_04.setExpandable(false);
        fru_04.setNonBlocking(true);
        fru_04.setStyle("Yellow");
        fvp_02.addBasicElement(fru_04);
        fru_04.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(100.0f, 100.0f));
        fru_04.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fru_0 fru_05 = fru_04;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_05).getAppearance();
        fqd_02.setElementMap(fyy_02);
        fru_04.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(2, 2, 2, 3));
        fqd_02.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqd_02.onChildrenAdded();
        fru_04.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("multidirectionnalCross");
        fvp_02.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setAlign(frk_0.i);
        fsk_02.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fvp_02.onChildrenAdded();
        fso5.onChildrenAdded();
        fso2.onChildrenAdded();
        fin_12.onChildrenAdded();
        return fin_12;
    }

    public fyo b(fut_0 fut_02) {
        fyy_0 fyy_02 = this.a.peek();
        fin_1 fin_12 = new fin_1();
        fin_12.onCheckOut();
        fin_12.setElementMap(fyy_02);
        fin_12.setText("Ambiance");
        fut_02.addBasicElement(fin_12);
        fin_12.onAttributesInitialized();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fso2.setPrefSize(new fjf_2(0, 150));
        fso2.setStyle("ShortcutRowBackground");
        fin_12.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso2.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setStyle("caracs");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso3.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fue_0 fue_02 = new fue_0();
        fue_02.onCheckOut();
        fue_02.setElementMap(fyy_02);
        fue_02.setHorizontalScrollBarBehaviour(fra_0.c);
        fue_02.setVerticalScrollBarPosition(1.0f);
        fso3.addBasicElement(fue_02);
        fue_02.onAttributesInitialized();
        fus_0 fus_02 = new fus_0();
        fus_02.onCheckOut();
        fus_02.setElementMap(fyy_02);
        fus_02.setInnerExpandable(false);
        fue_02.addBasicElement(fus_02);
        fus_02.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.b);
        fin_24.setHorizontal(false);
        fus_02.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("stratas");
        fiy_12.setName("mixDebugger");
        fus_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fus_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        faf_22.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso4;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso4.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 0, 5, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setHorizontal(false);
        fso4.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("bold");
        fso4.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("text");
        fir_12.setField("name");
        fsM2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fsM2.onChildrenAdded();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(100.0f, 15));
        fsQ2.setHorizontal(false);
        fsQ2.setIdealSizeMaxColumns(1);
        fsQ2.setIdealSizeMinColumns(1);
        fso4.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fsQ fsQ3 = fsQ2;
        fqr fqr2 = (fqr)((fvE)fsQ3).getAppearance();
        fqr2.setElementMap(fyy_02);
        fsQ2.addBasicElement(fqr2);
        fqr2.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 10, 0, 0));
        fqr2.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqr2.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("content");
        fir_13.setField("containers");
        fsQ2.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        faf_2 faf_23 = new faf_2();
        faf_23.onCheckOut();
        faf_23.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_23);
        faf_23.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        faf_23.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fav_1 fav_13 = new fav_1();
        fav_13.onCheckOut();
        fav_13.setElementMap(fyy_02);
        far_23.addBasicElement(fav_13);
        fav_13.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_02);
        fav_13.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        fav_13.onChildrenAdded();
        far_23.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        faf_23.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setAlign(frs_0.d);
        fso6.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        fsM fsM3 = new fsM();
        fsM3.onCheckOut();
        fsM3.setElementMap(fyy_02);
        fsM3.setExpandable(false);
        fsM3.setNonBlocking(true);
        fsM3.setStyle("bold");
        fso6.addBasicElement(fsM3);
        fsM3.onAttributesInitialized();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("text");
        fir_14.setField("name");
        fsM3.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fsM3.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setExpandable(false);
        fsM4.setNonBlocking(true);
        fso6.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fsM4.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 3, 0, 0));
        fqh_02.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("text");
        fir_15.setField("lastAdded");
        fsM4.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso6.onChildrenAdded();
        faf_23.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso4.onChildrenAdded();
        faf_22.onChildrenAdded();
        fus_02.onChildrenAdded();
        fue_02.onChildrenAdded();
        fso3.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso7.setExpandable(false);
        fso7.setStyle("caracs");
        fso2.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_02);
        fso7.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fvp_0 fvp_02 = new fvp_0();
        fvp_02.onCheckOut();
        fvp_02.setElementMap(fyy_02);
        fvp_02.setExpandable(false);
        fvp_02.setPointAlign(frs_0.i);
        fso7.addBasicElement(fvp_02);
        fvp_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvp_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fru_02.setNonBlocking(true);
        fru_02.setStyle("Yellow");
        fvp_02.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_02);
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(2, 2, 2, 3));
        fqd_02.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqd_02.onChildrenAdded();
        fru_02.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("multidirectionnalCross");
        fvp_02.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fsk_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fvp_02.onChildrenAdded();
        fso7.onChildrenAdded();
        fso2.onChildrenAdded();
        fin_12.onChildrenAdded();
        return fin_12;
    }

    public fyo c(fut_0 fut_02) {
        fyy_0 fyy_02 = this.a.peek();
        fin_1 fin_12 = new fin_1();
        fin_12.onCheckOut();
        fin_12.setElementMap(fyy_02);
        fin_12.setText("Statut");
        fut_02.addBasicElement(fin_12);
        fin_12.onAttributesInitialized();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fso2.setPrefSize(new fjf_2(0, 150));
        fso2.setStyle("ShortcutRowBackground");
        fin_12.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso2.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setStyle("caracs");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        fsQ2.setCellSize(new fjf_2(125, 25));
        fsQ2.setPrefSize(new fjf_2(250, 75));
        fso3.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("cache");
        fiy_12.setName("mixDebugger");
        fsQ2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        faf_22.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        String string = "soundGroup";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fij_12);
        }
        fso4.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("value");
        fij_12.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fij_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso4.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fup_0 fup_02 = new fup_0();
        fup_02.onCheckOut();
        fup_02.setElementMap(fyy_02);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.mixDebugger:selectSoundGroup(soundGroup)");
        fup_02.setOnClick(fdt_12);
        fup_02.setStyle("flat");
        fso4.addBasicElement(fup_02);
        fup_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fup_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("selected");
        fir_13.setField("visible");
        fup_02.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fup_02.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("bold");
        fso4.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("text");
        fir_14.setField("name");
        fsM2.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fsM2.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso4.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso3.onChildrenAdded();
        fue_0 fue_02 = new fue_0();
        fue_02.onCheckOut();
        fue_02.setElementMap(fyy_02);
        fue_02.setVerticalScrollBarPosition(1.0f);
        fso2.addBasicElement(fue_02);
        fue_02.onAttributesInitialized();
        fus_0 fus_02 = new fus_0();
        fus_02.onCheckOut();
        fus_02.setElementMap(fyy_02);
        fus_02.setExpandable(false);
        fus_02.setHorizontal(false);
        fus_02.setInnerExpandable(false);
        fue_02.addBasicElement(fus_02);
        fus_02.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("content");
        fiy_13.setField("cache");
        fiy_13.setName("mixDebugger");
        fus_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.b);
        fin_23.setHorizontal(false);
        fus_02.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        faf_2 faf_23 = new faf_2();
        faf_23.onCheckOut();
        faf_23.setElementMap(fyy_02);
        fus_02.addBasicElement(faf_23);
        faf_23.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        faf_23.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fav_1 fav_13 = new fav_1();
        fav_13.onCheckOut();
        fav_13.setElementMap(fyy_02);
        far_23.addBasicElement(fav_13);
        fav_13.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_02);
        fav_13.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        fav_13.onChildrenAdded();
        far_23.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setExpandable(false);
        fso5.setPrefSize(new fjf_2(380, 0));
        faf_23.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.d);
        fso5.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("visible");
        fir_15.setField("visible");
        fso5.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.b);
        fin_24.setHorizontal(false);
        fso5.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fsM fsM3 = new fsM();
        fsM3.onCheckOut();
        fsM3.setElementMap(fyy_02);
        fsM3.setExpandable(false);
        fsM3.setStyle("bold");
        fso5.addBasicElement(fsM3);
        fsM3.onAttributesInitialized();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_02);
        fir_16.setAttribute("text");
        fir_16.setField("name");
        fsM3.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        fir_16.onChildrenAdded();
        fsM3.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(375);
        fuk_02.setMinWidth(0);
        fuk_02.setStyle("11");
        fso5.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 5, 0, 0));
        fqh_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fir_1 fir_17 = new fir_1();
        fir_17.onCheckOut();
        fir_17.setElementMap(fyy_02);
        fir_17.setAttribute("text");
        fir_17.setField("sourcesDescription");
        fuk_02.addBasicElement(fir_17);
        fir_17.onAttributesInitialized();
        fir_17.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso5.onChildrenAdded();
        faf_23.onChildrenAdded();
        fus_02.onChildrenAdded();
        fue_02.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso6.setExpandable(false);
        fso6.setStyle("caracs");
        fso2.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setAlign(frs_0.d);
        fso6.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setExpandable(false);
        fsM4.c("Refresh");
        fso6.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fsM4.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 0, 0, 5));
        fqh_03.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fsM4.onChildrenAdded();
        String string2 = "onOff";
        fim_1 fim_12 = new fim_1();
        fim_12.onCheckOut();
        fim_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, (fyb_0)fim_12);
        }
        fso6.addBasicElement(fim_12);
        fim_12.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("value");
        fiy_14.setField("refresh");
        fiy_14.setName("mixDebugger");
        fim_12.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fim_12.onChildrenAdded();
        ftI ftI2 = new ftI();
        ftI2.onCheckOut();
        ftI2.setElementMap(fyy_02);
        ftI2.setExpandable(false);
        ftI2.setGroupId("onOff");
        fdb_1 fdb_12 = new fdb_1();
        fdb_12.a("wakfu.mixDebugger:setRefreshOn");
        ftI2.setOnMousePress(fdb_12);
        ftI2.setText("on");
        ftI2.setValue("true");
        fso6.addBasicElement(ftI2);
        ftI2.onAttributesInitialized();
        ftI ftI3 = ftI2;
        fqb_0 fqb_02 = (fqb_0)((fvE)ftI3).getAppearance();
        fqb_02.setElementMap(fyy_02);
        ftI2.addBasicElement(fqb_02);
        fqb_02.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 0, 0, 5));
        fqb_02.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqb_02.onChildrenAdded();
        ftI2.onChildrenAdded();
        ftI ftI4 = new ftI();
        ftI4.onCheckOut();
        ftI4.setElementMap(fyy_02);
        ftI4.setExpandable(false);
        ftI4.setGroupId("onOff");
        fdb_1 fdb_13 = new fdb_1();
        fdb_13.a("wakfu.mixDebugger:setRefreshOff");
        ftI4.setOnMousePress(fdb_13);
        ftI4.setText("off");
        ftI4.setValue("false");
        fso6.addBasicElement(ftI4);
        ftI4.onAttributesInitialized();
        ftI ftI5 = ftI4;
        fqb_0 fqb_03 = (fqb_0)((fvE)ftI5).getAppearance();
        fqb_03.setElementMap(fyy_02);
        ftI4.addBasicElement(fqb_03);
        fqb_03.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_02);
        fqm_05.setInsets(new Insets(0, 0, 0, 10));
        fqb_03.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqb_03.onChildrenAdded();
        ftI4.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdb_1 fdb_14 = new fdb_1();
        fdb_14.a("wakfu.mixDebugger:forceRefresh");
        fru_02.setOnMousePress(fdb_14);
        fru_02.setText("Force refresh");
        fso6.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_02.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_02);
        fso6.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fvp_0 fvp_02 = new fvp_0();
        fvp_02.onCheckOut();
        fvp_02.setElementMap(fyy_02);
        fvp_02.setExpandable(false);
        fvp_02.setPointAlign(frs_0.i);
        fso6.addBasicElement(fvp_02);
        fvp_02.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fvp_02.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_02);
        fru_03.setExpandable(false);
        fru_03.setNonBlocking(true);
        fru_03.setStyle("Yellow");
        fvp_02.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(100.0f, 100.0f));
        fru_03.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fru_0 fru_04 = fru_03;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_04).getAppearance();
        fqd_02.setElementMap(fyy_02);
        fru_03.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(2, 2, 2, 3));
        fqd_02.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqd_02.onChildrenAdded();
        fru_03.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("multidirectionnalCross");
        fvp_02.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setAlign(frk_0.i);
        fsk_02.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fvp_02.onChildrenAdded();
        fso6.onChildrenAdded();
        fso2.onChildrenAdded();
        fin_12.onChildrenAdded();
        return fin_12;
    }

    public fyo a(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo b(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fru_02.setStyle("close");
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("unloadDialog");
        fru_02.setOnClick(fdt_12);
        fvk_02.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setSize(new fjf_2(-2, -2));
        fid_12.setXOffset(-18);
        fid_12.setYOffset(-12);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo c(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.h);
        fid_12.setInitValue(true);
        fid_12.setSize(new fjf_2(450, 600));
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }
}

