/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cQc
 */
public class cqc_1
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        String string = "window";
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fvk_02);
        }
        fvk_02.setPack(true);
        fvk_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvk_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("windowNew");
        fvk_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(10, 5, 12, 5));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setExpandable(false);
        fso3.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fvM fvM3 = fvM2;
        fqj fqj3 = ((fvE)fvM3).getAppearance();
        fqj3.setElementMap(fyy_03);
        fvM2.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 10, 0, 10));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setStyle("titleBar");
        fvM2.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso fso6 = fso5;
        fqj fqj4 = ((fvE)fso6).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso5.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(3, 20, 3, 20));
        fqj4.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.e);
        fso7.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("StyledBold16White");
        String string2 = "%playerGift.title%";
        string2 = string2.replace("%playerGift.title%", fpm_0.b().c("playerGift.title"));
        fsM2.c(string2);
        fso7.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 0, 0, 5));
        fqh_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        fvM2.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso3.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj5 = ((fvE)fso9).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso8.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(0, 12, 0, 12));
        fqj5.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqj5.onChildrenAdded();
        String string3 = "windowContentContainer";
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fso10);
        }
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso10.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso11 = fso10;
        fqj fqj6 = ((fvE)fso11).getAppearance();
        fqj6.setElementMap(fyy_03);
        fso10.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_03);
        fqo_04.setInsets(new Insets(0, 0, 0, 0));
        fqj6.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj6.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        fso12.setStyle("ScrollString");
        fso10.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.j);
        fid_14.setSize(new fjf_2(10, 100.0f));
        fid_14.setXOffset(-15);
        fso12.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fso fso13 = fso12;
        fqj fqj7 = ((fvE)fso13).getAppearance();
        fqj7.setElementMap(fyy_03);
        fso12.addBasicElement(fqj7);
        fqj7.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(30, 0, 40, 0));
        fqj7.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqj7.onChildrenAdded();
        fso12.onChildrenAdded();
        String string4 = "selectedCraft";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_03);
        if (fyy_03 != null && string4 != null) {
            fyy_03.a(string4, fij_12);
        }
        fso10.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("value");
        fiy_12.setLocal(true);
        fiy_12.setName("craft");
        fij_12.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fij_12.onChildrenAdded();
        fue_0 fue_02 = new fue_0();
        fue_02.onCheckOut();
        fue_02.setElementMap(fyy_03);
        fue_02.setExpandable(false);
        fue_02.setHorizontalScrollBarBehaviour(fra_0.c);
        fue_02.setPageJumpRatio(0.3f);
        fue_02.setStyle("Encyclopedia");
        fue_02.setVerticalScrollBarBehaviour(fra_0.b);
        fso10.addBasicElement(fue_02);
        fue_02.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.i);
        fid_15.setSize(new fjf_2(100.0f, 100.0f));
        fue_02.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fue_0 fue_03 = fue_02;
        fqj fqj8 = ((fvE)fue_03).getAppearance();
        fqj8.setElementMap(fyy_03);
        fue_02.addBasicElement(fqj8);
        fqj8.onAttributesInitialized();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_03);
        fqm_06.setInsets(new Insets(17, 3, 20, 0));
        fqj8.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqo_0 fqo_05 = new fqo_0();
        fqo_05.onCheckOut();
        fqo_05.setElementMap(fyy_03);
        fqo_05.setInsets(new Insets(0, 18, 0, 4));
        fqj8.addBasicElement(fqo_05);
        fqo_05.onAttributesInitialized();
        fqo_05.onChildrenAdded();
        fqj8.onChildrenAdded();
        fso fso14 = fso.checkOut();
        fso14.setElementMap(fyy_03);
        fso14.setExpandable(false);
        fso14.setPrefSize(new fjf_2(415, 0));
        fso14.setStyle("tiledScroll");
        fue_02.addBasicElement(fso14);
        fso14.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_03);
        fid_16.setAlign(frk_0.i);
        fso14.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fso fso15 = fso14;
        fqj fqj9 = ((fvE)fso15).getAppearance();
        fqj9.setElementMap(fyy_03);
        fso14.addBasicElement(fqj9);
        fqj9.onAttributesInitialized();
        fqo_0 fqo_06 = new fqo_0();
        fqo_06.onCheckOut();
        fqo_06.setElementMap(fyy_03);
        fqo_06.setInsets(new Insets(10, 0, 10, 0));
        fqj9.addBasicElement(fqo_06);
        fqo_06.onAttributesInitialized();
        fqo_06.onChildrenAdded();
        fqm_0 fqm_07 = fqm_0.checkOut();
        fqm_07.setElementMap(fyy_03);
        fqm_07.setInsets(new Insets(0, 0, 0, 10));
        fqj9.addBasicElement(fqm_07);
        fqm_07.onAttributesInitialized();
        fqm_07.onChildrenAdded();
        fqj9.onChildrenAdded();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.b);
        fin_24.setHorizontal(false);
        fso14.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_03);
        fso16.setExpandable(false);
        fso14.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        fso fso17 = fso16;
        fqj fqj10 = ((fvE)fso17).getAppearance();
        fqj10.setElementMap(fyy_03);
        fso16.addBasicElement(fqj10);
        fqj10.onAttributesInitialized();
        fqm_0 fqm_08 = fqm_0.checkOut();
        fqm_08.setElementMap(fyy_03);
        fqm_08.setInsets(new Insets(0, 5, 0, 0));
        fqj10.addBasicElement(fqm_08);
        fqm_08.onAttributesInitialized();
        fqm_08.onChildrenAdded();
        fqj10.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("visible");
        fiy_13.setField("selectedPackage");
        fiy_13.setName("playerGift");
        fso16.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        fiy_13.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setHorizontal(false);
        fso16.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fso fso18 = fso.checkOut();
        fso18.setElementMap(fyy_03);
        fso18.setExpandable(false);
        fso16.addBasicElement(fso18);
        fso18.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_03);
        fip_23.setAlign(frs_0.d);
        fso18.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fso fso19 = fso18;
        fqj fqj11 = ((fvE)fso19).getAppearance();
        fqj11.setElementMap(fyy_03);
        fso18.addBasicElement(fqj11);
        fqj11.onAttributesInitialized();
        fqm_0 fqm_09 = fqm_0.checkOut();
        fqm_09.setElementMap(fyy_03);
        fqm_09.setInsets(new Insets(0, 20, 0, 5));
        fqj11.addBasicElement(fqm_09);
        fqm_09.onAttributesInitialized();
        fqm_09.onChildrenAdded();
        fqj11.onChildrenAdded();
        fso fso20 = fso.checkOut();
        fso20.setElementMap(fyy_03);
        fso20.setExpandable(false);
        fso20.setPrefSize(new fjf_2(64, 64));
        fso20.setStyle("encyclopediaSplash");
        fso18.addBasicElement(fso20);
        fso20.onAttributesInitialized();
        fip_2 fip_24 = new fip_2();
        fip_24.onCheckOut();
        fip_24.setElementMap(fyy_03);
        fip_24.setAlign(frs_0.b);
        fso20.addBasicElement(fip_24);
        fip_24.onAttributesInitialized();
        fip_24.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setDisplaySize(new fjf_2(48, 48));
        fsk_02.setExpandable(false);
        fso20.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fip_2 fip_25 = new fip_2();
        fip_25.onCheckOut();
        fip_25.setElementMap(fyy_03);
        fip_25.setAlign(frs_0.e);
        fsk_02.addBasicElement(fip_25);
        fip_25.onAttributesInitialized();
        fip_25.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("visible");
        fiy_14.setField("selectedPackage");
        fiy_14.setName("playerGift");
        fsk_02.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        fiy_14.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_03);
        far_23.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_14.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("texture");
        fiy_15.setField("selectedPackage/iconUrl");
        fiy_15.setName("playerGift");
        fqv2.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso20.onChildrenAdded();
        fso fso21 = fso.checkOut();
        fso21.setElementMap(fyy_03);
        fso21.setExpandable(false);
        fso21.setStyle("backgroundPopupLight");
        fso18.addBasicElement(fso21);
        fso21.onAttributesInitialized();
        fip_2 fip_26 = new fip_2();
        fip_26.onCheckOut();
        fip_26.setElementMap(fyy_03);
        fip_26.setAlign(frs_0.b);
        fso21.addBasicElement(fip_26);
        fip_26.onAttributesInitialized();
        fip_26.onChildrenAdded();
        fso fso22 = fso21;
        fqj fqj12 = ((fvE)fso22).getAppearance();
        fqj12.setElementMap(fyy_03);
        fqj12.setModulationColor(new azf_2(1.0f, 0.0f, 0.0f, 0.7f));
        fso21.addBasicElement(fqj12);
        fqj12.onAttributesInitialized();
        fqo_0 fqo_07 = new fqo_0();
        fqo_07.onCheckOut();
        fqo_07.setElementMap(fyy_03);
        fqo_07.setInsets(new Insets(4, 4, 4, 4));
        fqj12.addBasicElement(fqo_07);
        fqo_07.onAttributesInitialized();
        fqo_07.onChildrenAdded();
        fqj12.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(315);
        fuk_02.setMinWidth(1);
        fuk_02.setStyle("whiteBold11");
        fuk_02.c("Super cadeau de bienvenue qui poutre sa m\u00e8re, la race de sa grand-m\u00e8re");
        fso21.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("text");
        fiy_16.setField("selectedPackage/title");
        fiy_16.setName("playerGift");
        fuk_02.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fqh_03.setAlign(frs_0.d);
        fuk_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_03);
        fqg_02.setColor(new azf_2(1.0f, 1.0f, 1.0f, 1.0f));
        fqg_02.setName("text");
        fqh_03.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso21.onChildrenAdded();
        fso18.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_03);
        fuk_04.setExpandable(false);
        fuk_04.setMaxWidth(385);
        fuk_04.setMinWidth(1);
        fuk_04.setStyle("darkBold");
        fuk_04.c("H\u00e9 oui ! Ha ha ha ! Ce cadeau de bienvenue vous est offert par GIFI ! Encore un bijou de technologie qui nous lib\u00e8re des tracas du quotidien !! Il nous est pr\u00e9sent\u00e9 par Micheline... Merci Micheline, vous pouvez y aller.");
        fso16.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        this.a(fuk_04);
        this.b(fuk_04);
        this.c(fuk_04);
        fuk_04.onChildrenAdded();
        this.a(fso16);
        fso16.onChildrenAdded();
        fso14.onChildrenAdded();
        fue_02.onChildrenAdded();
        this.b(fso10);
        fso10.onChildrenAdded();
        fso8.onChildrenAdded();
        this.c(fso3);
        fso3.onChildrenAdded();
        this.a(fvk_02);
        this.b(fvk_02);
        this.c(fvk_02);
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fuk_0 fuk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(5, 20, 5, 0));
        fqh_02.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        return fqh_02;
    }

    public fyo b(fuk_0 fuk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.d);
        fuk_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        return fip_22;
    }

    public fyo c(fuk_0 fuk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("selectedPackage/description");
        fiy_12.setName("playerGift");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        return fiy_12;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(100.0f, 40));
        fsQ2.setExpandable(false);
        fsQ2.setIdealSizeMaxColumns(1);
        fsQ2.setIdealSizeMinColumns(1);
        fso2.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fsQ fsQ3 = fsQ2;
        fqr fqr2 = (fqr)((fvE)fsQ3).getAppearance();
        fqr2.setElementMap(fyy_02);
        fsQ2.addBasicElement(fqr2);
        fqr2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(0, 10, 0, 10));
        fqr2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqr2.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("selectedPackage/gifts");
        fiy_12.setName("playerGift");
        fsQ2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        String string = "gift";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fij_12);
        }
        faf_22.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("value");
        fij_12.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.playerGift:openItemDetails(gift,window)");
        fso3.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(itemDescPopup)");
        fso3.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fso3.setOnPopupHide(fdf_22);
        faf_22.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("nonBlocking");
        fir_13.setField("allowControls");
        fso3.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fir_13.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        far_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fir_13.onChildrenAdded();
        String string2 = "itemDescPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fso3.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setPrefSize(new fjf_2(10, 0));
        fso4.setStyle("popup");
        fil_12.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("visible");
        fir_14.setField("allowControls");
        fso4.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setStyle("PopupInformation");
        String string3 = "%rightClickToShowDetailWindow%";
        string3 = string3.replace("%rightClickToShowDetailWindow%", fpm_0.b().c("rightClickToShowDetailWindow"));
        fuk_02.c(string3);
        fso4.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso4.onChildrenAdded();
        fil_12.onChildrenAdded();
        String string4 = "gift";
        fij_1 fij_13 = new fij_1();
        fij_13.onCheckOut();
        fij_13.setElementMap(fyy_02);
        if (fyy_02 != null && string4 != null) {
            fyy_02.a(string4, fij_13);
        }
        fso3.addBasicElement(fij_13);
        fij_13.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("value");
        fij_13.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fij_13.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setPrefSize(new fjf_2(0, 48));
        fso5.setStyle("TiledScrollCenter");
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 48));
        fso5.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso5.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(200, 3));
        fsk_02.setStyle("TiledScrollTop");
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.a);
        fid_13.setSize(new fjf_2(100.0f, -2));
        fsk_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        fsk_03.setDisplaySize(new fjf_2(200, 3));
        fsk_03.setStyle("TiledScrollBottom");
        fso3.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.m);
        fid_14.setSize(new fjf_2(100.0f, -2));
        fsk_03.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso3.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setAlign(frk_0.i);
        fid_15.setSize(new fjf_2(100.0f, -2));
        fso6.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso7.setExpandable(false);
        fso7.setStyle("encyclopediaSplash");
        fso6.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        fsk_04.setDisplaySize(new fjf_2(32, 32));
        fsk_04.setExpandable(false);
        fso7.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_04.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_02);
        fir_16.setAttribute("texture");
        fir_16.setField("iconUrl");
        fqv2.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        fir_16.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fso7.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_02);
        fuk_04.setExpandable(false);
        fuk_04.setMaxWidth(280);
        fuk_04.setMinWidth(1);
        fuk_04.setStyle("darkBold");
        fso6.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fuk_0 fuk_05 = fuk_04;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_05).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlignment(frs_0.d);
        fuk_04.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 15, 0, 0));
        fqh_03.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fir_1 fir_17 = new fir_1();
        fir_17.onCheckOut();
        fir_17.setElementMap(fyy_02);
        fir_17.setAttribute("text");
        fir_17.setField("name");
        fuk_04.addBasicElement(fir_17);
        fir_17.onAttributesInitialized();
        fir_17.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_02);
        fso6.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fru_02.setNetEnabledId("giftLock");
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.playerGift:consumeOneGift(gift)");
        fru_02.setOnClick(fdt_13);
        fde_2 fde_23 = new fde_2();
        fde_23.a("popup(consumeOneDescPopup)");
        fru_02.setOnPopupDisplay(fde_23);
        fdf_2 fdf_23 = new fdf_2();
        fdf_23.a("closePopup");
        fru_02.setOnPopupHide(fdf_23);
        fru_02.setStyle("mru34");
        fso6.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        String string5 = "consumeOneDescPopup";
        fil_1 fil_13 = new fil_1();
        fil_13.onCheckOut();
        fil_13.setElementMap(fyy_02);
        if (fyy_02 != null && string5 != null) {
            fyy_02.a(string5, fil_13);
        }
        fil_13.setAlign(frs_0.b);
        fil_13.setHotSpotPosition(frs_0.h);
        fru_02.addBasicElement(fil_13);
        fil_13.onAttributesInitialized();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso8.setPrefSize(new fjf_2(10, 0));
        fso8.setStyle("popup");
        fil_13.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fuk_0 fuk_06 = new fuk_0();
        fuk_06.onCheckOut();
        fuk_06.setElementMap(fyy_02);
        fuk_06.setEnableShrinking(false);
        fuk_06.setStyle("white");
        String string6 = "%gift.consumeOne%";
        string6 = string6.replace("%gift.consumeOne%", fpm_0.b().c("gift.consumeOne"));
        fuk_06.c(string6);
        fso8.addBasicElement(fuk_06);
        fuk_06.onAttributesInitialized();
        fuk_0 fuk_07 = fuk_06;
        fqh_0 fqh_04 = (fqh_0)((fvE)fuk_07).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fqh_04.setAlignment(frs_0.e);
        fuk_06.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fuk_06.onChildrenAdded();
        fso8.onChildrenAdded();
        fil_13.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.e);
        fru_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fir_1 fir_18 = new fir_1();
        fir_18.onCheckOut();
        fir_18.setElementMap(fyy_02);
        fir_18.setAttribute("enabled");
        fir_18.setField("allowControls");
        fru_02.addBasicElement(fir_18);
        fir_18.onAttributesInitialized();
        fir_18.onChildrenAdded();
        fru_02.onChildrenAdded();
        fso6.onChildrenAdded();
        fso3.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        return fsQ2;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setNonBlocking(true);
        fso3.setStyle("EncyclopediaPane");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(454, 565));
        fid_12.setXOffset(-10);
        fid_12.setYOffset(1);
        fso3.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 59, 0, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(10, 5, 12, 5));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        return fqj2;
    }

    public fyo a(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso2.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(40, 0, 0, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.b);
        fso3.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso3.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.playerGift:packageListOffset(packageList,-1)");
        fru_02.setOnClick(fdt_12);
        fru_02.setStyle("upWhiteArrow");
        fso3.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("numPackages");
        fiy_12.setName("playerGift");
        fru_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fam_1 fam_12 = new fam_1();
        fam_12.onCheckOut();
        fam_12.setElementMap(fyy_02);
        fam_12.setValue("5");
        far_22.addBasicElement(fam_12);
        fam_12.onAttributesInitialized();
        fam_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        String string = "giftGroup";
        fim_1 fim_12 = new fim_1();
        fim_12.onCheckOut();
        fim_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, (fyb_0)fim_12);
        }
        fso3.addBasicElement(fim_12);
        fim_12.onAttributesInitialized();
        fim_12.onChildrenAdded();
        String string2 = "packageList";
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fsQ2);
        }
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(69, 80));
        fsQ2.setHorizontal(false);
        fsQ2.setIdealSizeMaxColumns(1);
        fsQ2.setIdealSizeMaxRows(5);
        fsQ2.setIdealSizeMinColumns(1);
        fsQ2.setIdealSizeMinRows(1);
        fsQ2.setNonBlocking(false);
        fdi_1 fdi_12 = new fdi_1();
        fdi_12.a("wakfu.playerGift:selectGiftPackage");
        fsQ2.setOnItemClick(fdi_12);
        fsQ2.setScrollBar(false);
        fsQ2.setScrollMode(fqv_0.b);
        fsQ2.setScrollOnMouseWheel(true);
        fsQ2.setSelectionable(false);
        fso3.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("content");
        fiy_13.setField("giftPackages");
        fiy_13.setName("playerGift");
        fsQ2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        faf_22.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_23.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_23.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        faf_22.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso5.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        ftI ftI2 = new ftI();
        ftI2.onCheckOut();
        ftI2.setElementMap(fyy_02);
        ftI2.setGroupId("giftGroup");
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(giftPkgDescPopup)");
        ftI2.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        ftI2.setOnPopupHide(fdf_22);
        ftI2.setStyle("bigLeftWindow");
        fso5.addBasicElement(ftI2);
        ftI2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("selected");
        ftI2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_02);
        fir_12.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fat_2 fat_22 = new fat_2();
        fat_22.onCheckOut();
        fat_22.setElementMap(fyy_02);
        far_24.addBasicElement(fat_22);
        fat_22.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("value");
        fiy_14.setField("selectedPackage");
        fiy_14.setName("playerGift");
        fat_22.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fat_22.onChildrenAdded();
        far_24.onChildrenAdded();
        fir_12.onChildrenAdded();
        String string3 = "giftPkgDescPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string3 != null) {
            fyy_02.a(string3, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        ftI2.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso6.setPrefSize(new fjf_2(10, 0));
        fso6.setStyle("popup");
        fil_12.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setEnableShrinking(false);
        fuk_02.setMaxWidth(250);
        fuk_02.setMinWidth(1);
        fuk_02.setStyle("white");
        fso6.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("text");
        fir_13.setField("title");
        fuk_02.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso6.onChildrenAdded();
        fil_12.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.o);
        fid_13.setSize(new fjf_2(69, 58));
        ftI2.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("text");
        fir_14.setField("title");
        ftI2.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        ftI2.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(48, 48));
        fsk_02.setNonBlocking(true);
        fso5.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.c);
        fid_14.setSize(new fjf_2(-2, -2));
        fid_14.setXOffset(-1);
        fsk_02.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("texture");
        fir_15.setField("iconUrl");
        fqv2.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso5.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_02);
        fru_03.setExpandable(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.playerGift:packageListOffset(packageList,1)");
        fru_03.setOnClick(fdt_13);
        fru_03.setStyle("downWhiteArrow");
        fso3.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("visible");
        fiy_15.setField("numPackages");
        fiy_15.setName("playerGift");
        fru_03.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_02);
        fiy_15.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fam_1 fam_13 = new fam_1();
        fam_13.onCheckOut();
        fam_13.setElementMap(fyy_02);
        fam_13.setValue("5");
        far_25.addBasicElement(fam_13);
        fam_13.onAttributesInitialized();
        fam_13.onChildrenAdded();
        far_25.onChildrenAdded();
        fiy_15.onChildrenAdded();
        fru_03.onChildrenAdded();
        fso3.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo b(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fru_02.setStyle("close");
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.playerGift:openCloseDialog");
        fru_02.setOnClick(fdt_12);
        fvk_02.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setSize(new fjf_2(-2, -2));
        fid_12.setXOffset(-18);
        fid_12.setYOffset(-12);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo c(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setResizeOnce(true);
        fid_12.setSize(new fjf_2(-2, -2));
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }
}

