/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cQg
 */
public class cqg_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        String string = "confirmPurchaseWindow";
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fvk_02);
        }
        fvk_02.setPack(true);
        fvk_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvk_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("windowNew");
        fvk_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(10, 5, 12, 5));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setExpandable(false);
        fso3.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fvM fvM3 = fvM2;
        fqj fqj3 = ((fvE)fvM3).getAppearance();
        fqj3.setElementMap(fyy_03);
        fvM2.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 10, 0, 10));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setStyle("titleBar");
        fvM2.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso fso6 = fso5;
        fqj fqj4 = ((fvE)fso6).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso5.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(3, 20, 3, 20));
        fqj4.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.e);
        fso7.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setMinWidth(250);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("StyledBold16White");
        fso7.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("text");
        fiy_12.setField("name");
        fiy_12.setName("selectedProtectorBudget");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlign(frs_0.e);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 0, 0, 0));
        fqh_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        fvM2.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso3.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj5 = ((fvE)fso9).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso8.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(0, 12, 0, 12));
        fqj5.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqj5.onChildrenAdded();
        String string2 = "windowContentContainer";
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fso10);
        }
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setHorizontal(true);
        fso10.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso10.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        String string3 = "wallet";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fij_12);
        }
        fso11.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("value");
        fiy_13.setName("selectedProtectorBudget");
        fij_12.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fij_12.onChildrenAdded();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setHorizontal(true);
        fso11.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        fso12.setPrefSize(new fjf_2(0, 35));
        fso12.setStyle("flat");
        fso11.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_03);
        fip_23.setAlign(frs_0.e);
        fso12.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fin_2 fin_26 = fin_2.checkOut();
        fin_26.setHorizontal(false);
        fso12.addBasicElement(fin_26);
        fin_26.onAttributesInitialized();
        fin_26.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setStyle("bold");
        String string4 = "%protector.budgetToAllocate%";
        string4 = string4.replace("%protector.budgetToAllocate%", fpm_0.b().c("protector.budgetToAllocate"));
        fsM2.c(string4);
        fso12.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fqh_03.setAlign(frs_0.e);
        fsM2.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_03);
        fso13.setPrefSize(new fjf_2(150, 0));
        fso13.setStyle("ShortcutRowBackgroundFull");
        fso12.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fso fso14 = fso13;
        fqj fqj6 = ((fvE)fso14).getAppearance();
        fqj6.setElementMap(fyy_03);
        fso13.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_03);
        fqo_04.setInsets(new Insets(2, 5, 2, 5));
        fqj6.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj6.onChildrenAdded();
        String string5 = "amountTextEditor";
        fug_0 fug_02 = new fug_0();
        fug_02.onCheckOut();
        fug_02.setElementMap(fyy_03);
        if (fyy_03 != null && string5 != null) {
            fyy_03.a(string5, fug_02);
        }
        fug_02.setFocused(true);
        fdo_1 fdo_12 = new fdo_1();
        fdo_12.a("wakfu.protectorManagement:validateBudgetAllocation(confirmButton)");
        fug_02.setOnKeyType(fdo_12);
        fug_02.setRestrict("[0-9]+");
        fug_02.setSelectOnFocus(true);
        fug_02.setStyle("dark");
        fug_02.c("0");
        fso13.addBasicElement(fug_02);
        fug_02.onAttributesInitialized();
        fug_0 fug_03 = fug_02;
        fqh_0 fqh_04 = (fqh_0)((fvE)fug_03).getAppearance();
        fqh_04.setElementMap(fyy_03);
        fqh_04.setAlign(frs_0.f);
        fug_02.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(0, 0, 0, 0));
        fqh_04.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqh_04.onChildrenAdded();
        fug_02.onChildrenAdded();
        fso13.onChildrenAdded();
        fso12.onChildrenAdded();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_03);
        fso15.setPrefSize(new fjf_2(0, 35));
        fso15.setStyle("flat");
        fso11.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fip_2 fip_24 = new fip_2();
        fip_24.onCheckOut();
        fip_24.setElementMap(fyy_03);
        fip_24.setAlign(frs_0.e);
        fso15.addBasicElement(fip_24);
        fip_24.onAttributesInitialized();
        fip_24.onChildrenAdded();
        fin_2 fin_27 = fin_2.checkOut();
        fin_27.setHorizontal(false);
        fso15.addBasicElement(fin_27);
        fin_27.onAttributesInitialized();
        fin_27.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_03);
        fsM4.setStyle("bold");
        String string6 = "%protector.funds%";
        string6 = string6.replace("%protector.funds%", fpm_0.b().c("protector.funds"));
        fsM4.c(string6);
        fso15.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_05 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_05.setElementMap(fyy_03);
        fqh_05.setAlign(frs_0.e);
        fsM4.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqh_05.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso fso16 = fso.checkOut();
        fso16.setElementMap(fyy_03);
        fso16.setPrefSize(new fjf_2(100, 0));
        fso16.setStyle("ShortcutRowBackgroundFull");
        fso15.addBasicElement(fso16);
        fso16.onAttributesInitialized();
        fso fso17 = fso16;
        fqj fqj7 = ((fvE)fso17).getAppearance();
        fqj7.setElementMap(fyy_03);
        fso16.addBasicElement(fqj7);
        fqj7.onAttributesInitialized();
        fqo_0 fqo_05 = new fqo_0();
        fqo_05.onCheckOut();
        fqo_05.setElementMap(fyy_03);
        fqo_05.setInsets(new Insets(2, 5, 2, 5));
        fqj7.addBasicElement(fqo_05);
        fqo_05.onAttributesInitialized();
        fqo_05.onChildrenAdded();
        fqj7.onChildrenAdded();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_03);
        fsM6.setStyle("bold");
        fso16.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fsM fsM7 = fsM6;
        fqh_0 fqh_06 = (fqh_0)((fvE)fsM7).getAppearance();
        fqh_06.setElementMap(fyy_03);
        fqh_06.setAlign(frs_0.f);
        fsM6.addBasicElement(fqh_06);
        fqh_06.onAttributesInitialized();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_03);
        fqm_06.setInsets(new Insets(0, 0, 0, 3));
        fqh_06.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqh_06.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("text");
        fiy_14.setField("walletHandler/totalAmount");
        fiy_14.setName("protector");
        fsM6.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fsM6.onChildrenAdded();
        fso16.onChildrenAdded();
        fso15.onChildrenAdded();
        fso11.onChildrenAdded();
        fso fso18 = fso.checkOut();
        fso18.setElementMap(fyy_03);
        fso10.addBasicElement(fso18);
        fso18.onAttributesInitialized();
        fin_2 fin_28 = fin_2.checkOut();
        fin_28.setAlign(frs_0.f);
        fso18.addBasicElement(fin_28);
        fin_28.onAttributesInitialized();
        fin_28.onChildrenAdded();
        fso fso19 = fso.checkOut();
        fso19.setElementMap(fyy_03);
        fso19.setExpandable(false);
        fso18.addBasicElement(fso19);
        fso19.onAttributesInitialized();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso19.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_03);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("unloadDialog");
        fru_02.setOnClick(fdt_12);
        fru_02.setStyle("yellow");
        fso19.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(100.0f, 100.0f));
        fru_02.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_03);
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqo_0 fqo_06 = new fqo_0();
        fqo_06.onCheckOut();
        fqo_06.setElementMap(fyy_03);
        fqo_06.setInsets(new Insets(7, 7, 7, 7));
        fqd_02.addBasicElement(fqo_06);
        fqo_06.onAttributesInitialized();
        fqo_06.onChildrenAdded();
        fqd_02.onChildrenAdded();
        fru_02.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("cancel");
        fso19.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.i);
        fid_15.setSize(new fjf_2(100.0f, 100.0f));
        fsk_02.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso19.onChildrenAdded();
        fso fso20 = fso.checkOut();
        fso20.setElementMap(fyy_03);
        fso20.setExpandable(false);
        fso18.addBasicElement(fso20);
        fso20.onAttributesInitialized();
        fic_1 fic_14 = new fic_1();
        fic_14.onCheckOut();
        fic_14.setAdaptToContentSize(true);
        fso20.addBasicElement(fic_14);
        fic_14.onAttributesInitialized();
        fic_14.onChildrenAdded();
        String string7 = "confirmButton";
        fru_0 fru_04 = new fru_0();
        fru_04.onCheckOut();
        fru_04.setElementMap(fyy_03);
        if (fyy_03 != null && string7 != null) {
            fyy_03.a(string7, fru_04);
        }
        fru_04.setEnabled(true);
        fru_04.setExpandable(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.protectorManagement:allocateBudget(amountTextEditor,wallet)");
        fru_04.setOnClick(fdt_13);
        fru_04.setStyle("yellow");
        fso20.addBasicElement(fru_04);
        fru_04.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_03);
        fid_16.setAlign(frk_0.i);
        fid_16.setSize(new fjf_2(100.0f, 100.0f));
        fru_04.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fru_0 fru_05 = fru_04;
        fqd_0 fqd_03 = (fqd_0)((fvE)fru_05).getAppearance();
        fqd_03.setElementMap(fyy_03);
        fru_04.addBasicElement(fqd_03);
        fqd_03.onAttributesInitialized();
        fqo_0 fqo_07 = new fqo_0();
        fqo_07.onCheckOut();
        fqo_07.setElementMap(fyy_03);
        fqo_07.setInsets(new Insets(7, 7, 7, 7));
        fqd_03.addBasicElement(fqo_07);
        fqo_07.onAttributesInitialized();
        fqo_07.onChildrenAdded();
        fqd_03.onChildrenAdded();
        fru_04.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_03);
        fsk_03.setNonBlocking(true);
        fsk_03.setStyle("apply");
        fso20.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_03);
        fid_17.setAlign(frk_0.i);
        fid_17.setSize(new fjf_2(100.0f, 100.0f));
        fsk_03.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fso20.onChildrenAdded();
        fso18.onChildrenAdded();
        fso10.onChildrenAdded();
        fso8.onChildrenAdded();
        fso3.onChildrenAdded();
        this.a(fvk_02);
        this.b(fvk_02);
        this.c(fvk_02);
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo b(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fru_02.setStyle("close");
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("unloadDialog");
        fru_02.setOnClick(fdt_12);
        fvk_02.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setSize(new fjf_2(-2, -2));
        fid_12.setXOffset(-18);
        fid_12.setYOffset(-12);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo c(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }
}

