/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cQm
 */
public class cqm_1
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fso2.setVisible(false);
        fso2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("visible");
        fiy_12.setName("isInGame");
        fso2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fan_2 fan_22 = new fan_2();
        fan_22.onCheckOut();
        fan_22.setElementMap(fyy_03);
        far_22.addBasicElement(fan_22);
        fan_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_03);
        fan_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        fai_1 fai_13 = new fai_1();
        fai_13.onCheckOut();
        fai_13.setElementMap(fyy_03);
        fan_22.addBasicElement(fai_13);
        fai_13.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("comparedValue");
        fiy_13.setField("mustDisplay");
        fiy_13.setName("pvpInfo");
        fai_13.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fai_13.onChildrenAdded();
        fan_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setAlign(frk_0.a);
        fid_12.setSize(new fjf_2(-2, -2));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 0, 0, 2));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_03);
        fso4.setNonBlocking(false);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(pvpInformationPopup)");
        fso4.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fso4.setOnPopupHide(fdf_22);
        fso4.setPrefSize(new fjf_2(48, 48));
        fso2.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        String string = "pvpInformationPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fil_12);
        }
        fil_12.setAlign(frs_0.f);
        fil_12.setHotSpotPosition(frs_0.d);
        fso4.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setPrefSize(new fjf_2(10, 0));
        fso5.setStyle("popup");
        fil_12.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso5.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_03);
        fii_22.setData(frg_0.e);
        fso5.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setStyle("StyledBold16White");
        fso5.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("text");
        fiy_14.setField("currentPact");
        fiy_14.setName("pvpInfo");
        fsM2.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("visible");
        fiy_15.setField("currentPact");
        fiy_15.setName("pvpInfo");
        fsM2.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        fiy_15.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        far_23.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_15.onChildrenAdded();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.b);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_03);
        fsM4.setStyle("StyledBold16White");
        fso5.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("text");
        fiy_16.setField("pendingPact");
        fiy_16.setName("pvpInfo");
        fsM4.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_03);
        fiy_17.setAttribute("visible");
        fiy_17.setField("pendingPact");
        fiy_17.setName("pvpInfo");
        fsM4.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_03);
        fiy_17.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_03);
        far_24.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_24.onChildrenAdded();
        fiy_17.onChildrenAdded();
        fsM fsM5 = fsM4;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fqh_03.setAlignment(frs_0.b);
        fsM4.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_03);
        fso6.setExpandable(false);
        fso6.setPrefSize(new fjf_2(0, 1));
        fso6.setStyle("lineSeparator2");
        fso5.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_03);
        fiy_18.setAttribute("visible");
        fiy_18.setField("hasAltars");
        fiy_18.setName("pvpInfo");
        fso6.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        fiy_18.onChildrenAdded();
        fso fso7 = fso6;
        fqj fqj3 = ((fvE)fso7).getAppearance();
        fqj3.setElementMap(fyy_03);
        fso6.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(4, 0, 0, 0));
        fqj3.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso6.onChildrenAdded();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_03);
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(300, 48));
        fsQ2.setExpandable(false);
        fsQ2.setHorizontal(false);
        fsQ2.setIdealSizeMaxColumns(1);
        fsQ2.setIdealSizeMaxRows(8);
        fsQ2.setIdealSizeMinColumns(1);
        fsQ2.setIdealSizeMinRows(1);
        fso5.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_03);
        fiy_19.setAttribute("content");
        fiy_19.setField("altars");
        fiy_19.setName("pvpInfo");
        fsQ2.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        fiy_19.onChildrenAdded();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_03);
        fiy_110.setAttribute("visible");
        fiy_110.setField("hasAltars");
        fiy_110.setName("pvpInfo");
        fsQ2.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        fiy_110.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_03);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_03);
        faf_22.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_03);
        far_25.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_24 = new fab_2();
        fab_24.onCheckOut();
        fab_24.setElementMap(fyy_03);
        fav_12.addBasicElement(fab_24);
        fab_24.onAttributesInitialized();
        fab_24.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_25.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        faf_22.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso8.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_03);
        fsM6.setStyle("PopupMenu");
        fso8.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_03);
        fir_12.setAttribute("text");
        fir_12.setField("altarWorld");
        fsM6.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fsM fsM7 = fsM6;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM7).getAppearance();
        fqh_04.setElementMap(fyy_03);
        fqh_04.setAlignment(frs_0.d);
        fsM6.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(10, 0, 0, 0));
        fqh_04.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_04.onChildrenAdded();
        fsM6.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_03);
        fso8.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fso fso10 = fso9;
        fqj fqj4 = ((fvE)fso10).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso9.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(-14, 0, 0, 0));
        fqj4.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqj4.onChildrenAdded();
        fsM fsM8 = new fsM();
        fsM8.onCheckOut();
        fsM8.setElementMap(fyy_03);
        fsM8.setStyle("WhiteBold");
        fso9.addBasicElement(fsM8);
        fsM8.onAttributesInitialized();
        fsM fsM9 = fsM8;
        fqh_0 fqh_05 = (fqh_0)((fvE)fsM9).getAppearance();
        fqh_05.setElementMap(fyy_03);
        fqh_05.setAlignment(frs_0.d);
        fsM8.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqh_05.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_03);
        fir_13.setAttribute("text");
        fir_13.setField("altarTimer");
        fsM8.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fsM8.onChildrenAdded();
        fsM fsM10 = new fsM();
        fsM10.onCheckOut();
        fsM10.setElementMap(fyy_03);
        fsM10.setStyle("WhiteBold");
        fso9.addBasicElement(fsM10);
        fsM10.onAttributesInitialized();
        fsM fsM11 = fsM10;
        fqh_0 fqh_06 = (fqh_0)((fvE)fsM11).getAppearance();
        fqh_06.setElementMap(fyy_03);
        fqh_06.setAlignment(frs_0.f);
        fsM10.addBasicElement(fqh_06);
        fqh_06.onAttributesInitialized();
        fqh_06.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_03);
        fir_14.setAttribute("text");
        fir_14.setField("altarPhase");
        fsM10.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fsM10.onChildrenAdded();
        fso9.onChildrenAdded();
        fso8.onChildrenAdded();
        faf_22.onChildrenAdded();
        faf_2 faf_23 = new faf_2();
        faf_23.onCheckOut();
        faf_23.setElementMap(fyy_03);
        fsQ2.addBasicElement(faf_23);
        faf_23.onAttributesInitialized();
        far_2 far_26 = new far_2();
        far_26.onCheckOut();
        far_26.setElementMap(fyy_03);
        faf_23.addBasicElement(far_26);
        far_26.onAttributesInitialized();
        fav_1 fav_13 = new fav_1();
        fav_13.onCheckOut();
        fav_13.setElementMap(fyy_03);
        far_26.addBasicElement(fav_13);
        fav_13.onAttributesInitialized();
        fac_1 fac_12 = new fac_1();
        fac_12.onCheckOut();
        fac_12.setElementMap(fyy_03);
        fav_13.addBasicElement(fac_12);
        fac_12.onAttributesInitialized();
        fac_12.onChildrenAdded();
        fav_13.onChildrenAdded();
        far_26.onChildrenAdded();
        faf_23.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso5.onChildrenAdded();
        fil_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fso4.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setDisplaySize(new fjf_2(48, 48));
        fsk_02.setStyle("PactInfo");
        fso4.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setAlign(frk_0.a);
        fid_13.setSize(new fjf_2(48, 48));
        fsk_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_03);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fiy_1 fiy_111 = fiy_1.checkOut();
        fiy_111.setElementMap(fyy_03);
        fiy_111.setAttribute("modulationColor");
        fiy_111.setField("pendingPactTimer");
        fiy_111.setName("pvpInfo");
        fqp2.addBasicElement(fiy_111);
        fiy_111.onAttributesInitialized();
        far_2 far_27 = new far_2();
        far_27.onCheckOut();
        far_27.setElementMap(fyy_03);
        far_27.setElseValue("1,1,1");
        far_27.setValue("0.75,0.75,0.75,0.5");
        fiy_111.addBasicElement(far_27);
        far_27.onAttributesInitialized();
        fam_1 fam_12 = new fam_1();
        fam_12.onCheckOut();
        fam_12.setElementMap(fyy_03);
        fam_12.setValue("0");
        far_27.addBasicElement(fam_12);
        fam_12.onAttributesInitialized();
        fam_12.onChildrenAdded();
        far_27.onChildrenAdded();
        fiy_111.onChildrenAdded();
        fqp2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso4.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(-2, -2));
        fid_14.setXOffset(12);
        fid_14.setYOffset(-20);
        fso11.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fiy_1 fiy_112 = fiy_1.checkOut();
        fiy_112.setElementMap(fyy_03);
        fiy_112.setAttribute("visible");
        fiy_112.setField("pendingPactTimer");
        fiy_112.setName("pvpInfo");
        fso11.addBasicElement(fiy_112);
        fiy_112.onAttributesInitialized();
        far_2 far_28 = new far_2();
        far_28.onCheckOut();
        far_28.setElementMap(fyy_03);
        fiy_112.addBasicElement(far_28);
        far_28.onAttributesInitialized();
        fam_1 fam_13 = new fam_1();
        fam_13.onCheckOut();
        fam_13.setElementMap(fyy_03);
        fam_13.setValue("0");
        far_28.addBasicElement(fam_13);
        fam_13.onAttributesInitialized();
        fam_13.onChildrenAdded();
        far_28.onChildrenAdded();
        fiy_112.onChildrenAdded();
        fsM fsM12 = new fsM();
        fsM12.onCheckOut();
        fsM12.setElementMap(fyy_03);
        fsM12.setStyle("StyledBold16White");
        fso11.addBasicElement(fsM12);
        fsM12.onAttributesInitialized();
        fiy_1 fiy_113 = fiy_1.checkOut();
        fiy_113.setElementMap(fyy_03);
        fiy_113.setAttribute("text");
        fiy_113.setField("pendingPactTimer");
        fiy_113.setName("pvpInfo");
        fsM12.addBasicElement(fiy_113);
        fiy_113.onAttributesInitialized();
        fiy_113.onChildrenAdded();
        fsM fsM13 = fsM12;
        fqh_0 fqh_07 = (fqh_0)((fvE)fsM13).getAppearance();
        fqh_07.setElementMap(fyy_03);
        fqh_07.setAlignment(frs_0.e);
        fsM12.addBasicElement(fqh_07);
        fqh_07.onAttributesInitialized();
        fqh_07.onChildrenAdded();
        fsM12.onChildrenAdded();
        fso11.onChildrenAdded();
        fso4.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }
}

