/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cQP
 */
public class cqp_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        String string = "splitStackContainer";
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fso2);
        }
        fso2.setPack(true);
        fso2.setStyle("spellInventory");
        fso2.onAttributesInitialized();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(3, 2, 3, 2));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fih_2 fih_22 = new fih_2();
        fih_22.onCheckOut();
        fso2.addBasicElement(fih_22);
        fih_22.onAttributesInitialized();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_03);
        fih_22.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso4;
        fqj fqj3 = ((fvE)fso5).getAppearance();
        fqj3.setElementMap(fyy_03);
        fso4.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(8, 5, 5, 0));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_03);
        fii_22.setData(frg_0.a);
        fso4.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fih_2 fih_23 = new fih_2();
        fih_23.onCheckOut();
        fso4.addBasicElement(fih_23);
        fih_23.onAttributesInitialized();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_03);
        fih_23.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fii_2 fii_23 = fii_2.checkOut();
        fii_23.setElementMap(fyy_03);
        fii_23.setData(frg_0.e);
        fso6.addBasicElement(fii_23);
        fii_23.onAttributesInitialized();
        fii_23.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_03);
        fdb_1 fdb_12 = new fdb_1();
        fdb_12.a("wakfu.split:decreaseSplitCountToOne(quantityTextEditor)");
        fru_02.setOnMousePress(fdb_12);
        fru_02.setStyle("pagingAllLeft");
        fso6.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_0 fru_03 = fru_02;
        fqd_0 fqd_02 = (fqd_0)((fvE)fru_03).getAppearance();
        fqd_02.setElementMap(fyy_03);
        fqd_02.setModulationColor(new azf_2(1.0f, 1.0f, 1.0f, 0.5f));
        fru_02.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqd_02.onChildrenAdded();
        fru_02.onChildrenAdded();
        fru_0 fru_04 = new fru_0();
        fru_04.onCheckOut();
        fru_04.setElementMap(fyy_03);
        fdb_1 fdb_13 = new fdb_1();
        fdb_13.a("wakfu.split:decreaseSplitCount(quantityTextEditor)");
        fru_04.setOnMousePress(fdb_13);
        fru_04.setStyle("pagingOneLeft");
        fso6.addBasicElement(fru_04);
        fru_04.onAttributesInitialized();
        fru_0 fru_05 = fru_04;
        fqd_0 fqd_03 = (fqd_0)((fvE)fru_05).getAppearance();
        fqd_03.setElementMap(fyy_03);
        fqd_03.setModulationColor(new azf_2(1.0f, 1.0f, 1.0f, 0.5f));
        fru_04.addBasicElement(fqd_03);
        fqd_03.onAttributesInitialized();
        fqd_03.onChildrenAdded();
        fru_04.onChildrenAdded();
        fso6.onChildrenAdded();
        String string2 = "quantityTextEditor";
        fug_0 fug_02 = new fug_0();
        fug_02.onCheckOut();
        fug_02.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fug_02);
        }
        fug_02.setFocusable(true);
        fug_02.setFocused(true);
        fug_02.a(10);
        fdo_1 fdo_12 = new fdo_1();
        fdo_12.a("wakfu.split:keyType(quantityTextEditor)");
        fug_02.setOnKeyType(fdo_12);
        fug_02.setPrefSize(new fjf_2(40, 12));
        fug_02.setRestrict("[0-9,\\\\.\u00a0\u202f]+");
        fug_02.setSelectOnFocus(true);
        fug_02.setStyle("dark");
        fih_23.addBasicElement(fug_02);
        fug_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("text");
        fiy_12.setName("itemToSplit");
        fug_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fii_2 fii_24 = fii_2.checkOut();
        fii_24.setElementMap(fyy_03);
        fii_24.setData(frg_0.a);
        fug_02.addBasicElement(fii_24);
        fii_24.onAttributesInitialized();
        fii_24.onChildrenAdded();
        fug_0 fug_03 = fug_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fug_03).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlign(frs_0.e);
        fug_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 4, 0, 4));
        fqh_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(0, 2, 2, 2));
        fqh_02.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fug_02.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fih_23.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fii_2 fii_25 = fii_2.checkOut();
        fii_25.setElementMap(fyy_03);
        fii_25.setData(frg_0.d);
        fso7.addBasicElement(fii_25);
        fii_25.onAttributesInitialized();
        fii_25.onChildrenAdded();
        fru_0 fru_06 = new fru_0();
        fru_06.onCheckOut();
        fru_06.setElementMap(fyy_03);
        fdb_1 fdb_14 = new fdb_1();
        fdb_14.a("wakfu.split:increaseSplitCount(quantityTextEditor)");
        fru_06.setOnMousePress(fdb_14);
        fru_06.setStyle("pagingOneRight");
        fso7.addBasicElement(fru_06);
        fru_06.onAttributesInitialized();
        fru_0 fru_07 = fru_06;
        fqd_0 fqd_04 = (fqd_0)((fvE)fru_07).getAppearance();
        fqd_04.setElementMap(fyy_03);
        fqd_04.setModulationColor(new azf_2(1.0f, 1.0f, 1.0f, 0.5f));
        fru_06.addBasicElement(fqd_04);
        fqd_04.onAttributesInitialized();
        fqd_04.onChildrenAdded();
        fru_06.onChildrenAdded();
        fru_0 fru_08 = new fru_0();
        fru_08.onCheckOut();
        fru_08.setElementMap(fyy_03);
        fdb_1 fdb_15 = new fdb_1();
        fdb_15.a("wakfu.split:increaseSplitCountToMax(quantityTextEditor)");
        fru_08.setOnMousePress(fdb_15);
        fru_08.setStyle("pagingAllRight");
        fso7.addBasicElement(fru_08);
        fru_08.onAttributesInitialized();
        fru_0 fru_09 = fru_08;
        fqd_0 fqd_05 = (fqd_0)((fvE)fru_09).getAppearance();
        fqd_05.setElementMap(fyy_03);
        fqd_05.setModulationColor(new azf_2(1.0f, 1.0f, 1.0f, 0.5f));
        fru_08.addBasicElement(fqd_05);
        fqd_05.onAttributesInitialized();
        fqd_05.onChildrenAdded();
        fru_08.onChildrenAdded();
        fso7.onChildrenAdded();
        fih_23.onChildrenAdded();
        fso4.onChildrenAdded();
        fru_0 fru_010 = new fru_0();
        fru_010.onCheckOut();
        fru_010.setElementMap(fyy_03);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.split:validSplit");
        fru_010.setOnClick(fdt_12);
        fru_010.setStyle("smallValid");
        fih_22.addBasicElement(fru_010);
        fru_010.onAttributesInitialized();
        fii_2 fii_26 = fii_2.checkOut();
        fii_26.setElementMap(fyy_03);
        fii_26.setData(frg_0.d);
        fru_010.addBasicElement(fii_26);
        fii_26.onAttributesInitialized();
        fii_26.onChildrenAdded();
        fru_0 fru_011 = fru_010;
        fqd_0 fqd_06 = (fqd_0)((fvE)fru_011).getAppearance();
        fqd_06.setElementMap(fyy_03);
        fqd_06.setModulationColor(new azf_2(1.0f, 1.0f, 1.0f, 0.65f));
        fru_010.addBasicElement(fqd_06);
        fqd_06.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(3, 8, 0, 5));
        fqd_06.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqd_06.onChildrenAdded();
        fru_010.onChildrenAdded();
        fih_22.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }
}

