/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cQt
 */
public class cqt_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setAlign(frk_0.h);
        fid_12.setSize(new fjf_2(-2, -2));
        fid_12.setXOffset(-20);
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso2.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("tiledScroll");
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(20, 12, 20, 13));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(13, 0, 13, 0));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setNonBlocking(false);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.b);
        fin_23.setHorizontal(false);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_03);
        fso6.setExpandable(false);
        fso6.setStyle("AchievementUnlockedSplashScaled2");
        fso5.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fso fso7 = fso6;
        fqj fqj3 = ((fvE)fso7).getAppearance();
        fqj3.setElementMap(fyy_03);
        fso6.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 13, 0, 0));
        fqj3.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(13, 10, 13, 10));
        fqj3.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj3.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setExpandable(false);
        fsM2.setStyle("defaultBold22");
        fso6.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("text");
        fiy_12.setField("achievementIndexText");
        fiy_12.setLocal(true);
        fiy_12.setName("questListBar");
        fsM2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.b);
        fsM2.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_03);
        fqg_02.setColor(new fyr_0("scrollFleshColor"));
        fqh_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(0, 0, 0, 10));
        fqh_02.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(180);
        fuk_02.setMinWidth(1);
        fuk_02.setStyle("styledBoldWhite12");
        fso6.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_03);
        fip_23.setAlign(frs_0.b);
        fuk_02.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("text");
        fiy_13.setField("name");
        fiy_13.setLocal(true);
        fiy_13.setName("displayedAchievement");
        fuk_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fuk_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqg_0 fqg_03 = fqg_0.checkOut();
        fqg_03.setElementMap(fyy_03);
        fqg_03.setColor(new fyr_0("scrollFleshColor"));
        fqh_03.addBasicElement(fqg_03);
        fqg_03.onAttributesInitialized();
        fqg_03.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso6.onChildrenAdded();
        fus_0 fus_02 = new fus_0();
        fus_02.onCheckOut();
        fus_02.setElementMap(fyy_03);
        fus_02.setExpandable(false);
        fus_02.setHorizontal(false);
        fso5.addBasicElement(fus_02);
        fus_02.onAttributesInitialized();
        fus_0 fus_03 = fus_02;
        fqr fqr2 = (fqr)((fvE)fus_03).getAppearance();
        fqr2.setElementMap(fyy_03);
        fus_02.addBasicElement(fqr2);
        fqr2.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(0, 15, 0, 15));
        fqr2.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqr2.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("content");
        fiy_14.setField("goals");
        fiy_14.setLocal(true);
        fiy_14.setName("displayedAchievement");
        fus_02.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_03);
        fus_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_03);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        faf_22.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.d);
        fso8.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_03);
        fuk_04.setExpandable(false);
        fuk_04.setMaxWidth(180);
        fuk_04.setMinWidth(180);
        fuk_04.setStyle("styledBoldDark12");
        fso8.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fuk_0 fuk_05 = fuk_04;
        fqh_0 fqh_04 = (fqh_0)((fvE)fuk_05).getAppearance();
        fqh_04.setElementMap(fyy_03);
        fqh_04.setAlign(frs_0.d);
        fuk_04.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_03);
        fqm_06.setInsets(new Insets(0, 0, 0, 0));
        fqh_04.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_03);
        fqo_04.setInsets(new Insets(7, 0, 7, 0));
        fqh_04.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqh_04.onChildrenAdded();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_03);
        fir_12.setAttribute("text");
        fir_12.setField("description");
        fuk_04.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_03);
        fso8.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fur_02.onChildrenAdded();
        fuk_0 fuk_06 = new fuk_0();
        fuk_06.onCheckOut();
        fuk_06.setElementMap(fyy_03);
        fuk_06.setExpandable(false);
        fuk_06.setNonBlocking(true);
        fuk_06.setStyle("styledBoldDark12");
        fso8.addBasicElement(fuk_06);
        fuk_06.onAttributesInitialized();
        fuk_0 fuk_07 = fuk_06;
        fqh_0 fqh_05 = (fqh_0)((fvE)fuk_07).getAppearance();
        fqh_05.setElementMap(fyy_03);
        fqh_05.setAlign(frs_0.e);
        fuk_06.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqh_05.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_03);
        fir_13.setAttribute("text");
        fir_13.setField("progressionText");
        fuk_06.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_03);
        fir_14.setAttribute("visible");
        fir_14.setField("isCompleted");
        fuk_06.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        fir_14.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fan_2 fan_22 = new fan_2();
        fan_22.onCheckOut();
        fan_22.setElementMap(fyy_03);
        far_23.addBasicElement(fan_22);
        fan_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_03);
        fan_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        fau_1 fau_13 = new fau_1();
        fau_13.onCheckOut();
        fau_13.setElementMap(fyy_03);
        fan_22.addBasicElement(fau_13);
        fau_13.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_03);
        fir_15.setAttribute("comparedValue");
        fir_15.setField("progressionText");
        fau_13.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_03);
        fir_15.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fat_2 fat_22 = new fat_2();
        fat_22.onCheckOut();
        fat_22.setElementMap(fyy_03);
        fat_22.setValue("-1");
        far_24.addBasicElement(fat_22);
        fat_22.onAttributesInitialized();
        fat_22.onChildrenAdded();
        far_24.onChildrenAdded();
        fir_15.onChildrenAdded();
        fau_13.onChildrenAdded();
        fan_22.onChildrenAdded();
        far_23.onChildrenAdded();
        fir_14.onChildrenAdded();
        fuk_06.onChildrenAdded();
        fso8.onChildrenAdded();
        faf_22.onChildrenAdded();
        fus_02.onChildrenAdded();
        fuk_0 fuk_08 = new fuk_0();
        fuk_08.onCheckOut();
        fuk_08.setElementMap(fyy_03);
        fuk_08.setExpandable(false);
        fuk_08.setMaxWidth(200);
        fuk_08.setMinWidth(1);
        fuk_08.setStyle("darkBold");
        fuk_08.c("bg");
        fso5.addBasicElement(fuk_08);
        fuk_08.onAttributesInitialized();
        fuk_0 fuk_09 = fuk_08;
        fqh_0 fqh_06 = (fqh_0)((fvE)fuk_09).getAppearance();
        fqh_06.setElementMap(fyy_03);
        fuk_08.addBasicElement(fqh_06);
        fqh_06.onAttributesInitialized();
        fqm_0 fqm_07 = fqm_0.checkOut();
        fqm_07.setElementMap(fyy_03);
        fqm_07.setInsets(new Insets(5, 20, 5, 20));
        fqh_06.addBasicElement(fqm_07);
        fqm_07.onAttributesInitialized();
        fqm_07.onChildrenAdded();
        fqh_06.onChildrenAdded();
        fip_2 fip_24 = new fip_2();
        fip_24.onCheckOut();
        fip_24.setElementMap(fyy_03);
        fip_24.setAlign(frs_0.d);
        fuk_08.addBasicElement(fip_24);
        fip_24.onAttributesInitialized();
        fip_24.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("text");
        fiy_15.setField("backgroundText");
        fiy_15.setLocal(true);
        fiy_15.setName("displayedAchievement");
        fuk_08.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("visible");
        fiy_16.setField("backgroundText");
        fiy_16.setLocal(true);
        fiy_16.setName("displayedAchievement");
        fuk_08.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_03);
        fiy_16.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fan_2 fan_23 = new fan_2();
        fan_23.onCheckOut();
        fan_23.setElementMap(fyy_03);
        far_25.addBasicElement(fan_23);
        fan_23.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_03);
        fan_23.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        faa_2 faa_22 = new faa_2();
        faa_22.onCheckOut();
        faa_22.setElementMap(fyy_03);
        faa_22.setValue("");
        fan_23.addBasicElement(faa_22);
        faa_22.onAttributesInitialized();
        faa_22.onChildrenAdded();
        fan_23.onChildrenAdded();
        far_25.onChildrenAdded();
        fiy_16.onChildrenAdded();
        fuk_08.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_03);
        fso9.setExpandable(false);
        fso5.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fso fso10 = fso9;
        fqj fqj4 = ((fvE)fso10).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso9.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqm_0 fqm_08 = fqm_0.checkOut();
        fqm_08.setElementMap(fyy_03);
        fqm_08.setInsets(new Insets(5, 13, 5, 13));
        fqj4.addBasicElement(fqm_08);
        fqm_08.onAttributesInitialized();
        fqm_08.onChildrenAdded();
        fqj4.onChildrenAdded();
        fip_2 fip_25 = new fip_2();
        fip_25.onCheckOut();
        fip_25.setElementMap(fyy_03);
        fip_25.setAlign(frs_0.e);
        fso9.addBasicElement(fip_25);
        fip_25.onAttributesInitialized();
        fip_25.onChildrenAdded();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso9.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setDisplaySize(new fjf_2(210, 29));
        fsk_02.setStyle("scrollTitleBar");
        fso9.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.h);
        fid_14.setSize(new fjf_2(-2, -2));
        fsk_02.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fuk_0 fuk_010 = new fuk_0();
        fuk_010.onCheckOut();
        fuk_010.setElementMap(fyy_03);
        fuk_010.setNonBlocking(true);
        fuk_010.setStyle("styledBoldWhite12");
        String string = "%achievement.reward%";
        string = string.replace("%achievement.reward%", fpm_0.b().c("achievement.reward"));
        fuk_010.c(string);
        fso9.addBasicElement(fuk_010);
        fuk_010.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.h);
        fid_15.setSize(new fjf_2(100.0f, 2));
        fuk_010.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fuk_0 fuk_011 = fuk_010;
        fqh_0 fqh_07 = (fqh_0)((fvE)fuk_011).getAppearance();
        fqh_07.setElementMap(fyy_03);
        fqh_07.setAlign(frs_0.e);
        fuk_010.addBasicElement(fqh_07);
        fqh_07.onAttributesInitialized();
        this.a(fqh_07);
        fqh_07.onChildrenAdded();
        fuk_010.onChildrenAdded();
        fso9.onChildrenAdded();
        this.a(fso5);
        fso5.onChildrenAdded();
        this.b(fso3);
        fso3.onChildrenAdded();
        this.c(fso2);
        this.d(fso2);
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo a(fqh_0 fqh_02) {
        fyy_0 fyy_02 = this.a.peek();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_02);
        fqg_02.setColor(new fyr_0("scrollFleshColor"));
        fqh_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        return fqg_02;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(170, 52));
        fsQ2.setExpandable(false);
        fsQ2.setIdealSizeMaxColumns(1);
        fsQ2.setIdealSizeMinColumns(1);
        fsQ2.setPrefSize(new fjf_2(0, 0));
        fso2.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("rewards");
        fiy_12.setLocal(true);
        fiy_12.setName("displayedAchievement");
        fsQ2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.e);
        fsQ2.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fsQ fsQ3 = fsQ2;
        fqr fqr2 = (fqr)((fvE)fsQ3).getAppearance();
        fqr2.setElementMap(fyy_02);
        fsQ2.addBasicElement(fqr2);
        fqr2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 0, 0, 0));
        fqr2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqr2.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fdi_1 fdi_12 = new fdi_1();
        fdi_12.a("wakfu:openItemDetailWindow()");
        faf_22.setOnItemClick(fdi_12);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        faf_22.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setExpandable(false);
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso4;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso4.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 0, 0, 5));
        fqj2.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj2.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso4.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setStyle("IconEmptyEmote");
        fso4.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(-2, -2));
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        fsk_03.setDisplaySize(new fjf_2(48, 48));
        fso4.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(-2, -2));
        fsk_03.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_03.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("texture");
        fir_12.setField("iconUrl");
        fqv2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("bold");
        fso4.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(5, 5, 5, 5));
        fqh_02.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_02);
        fqg_02.setColor(new fyr_0("defaultDarkColor"));
        fqg_02.setName("text");
        fqh_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.q);
        fid_14.setSize(new fjf_2(-2, -2));
        fsM2.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("text");
        fir_13.setField("quantity");
        fsM2.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("visible");
        fir_14.setField("quantity");
        fsM2.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        fir_14.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fam_1 fam_12 = new fam_1();
        fam_12.onCheckOut();
        fam_12.setElementMap(fyy_02);
        fam_12.setValue("1");
        far_23.addBasicElement(fam_12);
        fam_12.onAttributesInitialized();
        fam_12.onChildrenAdded();
        far_23.onChildrenAdded();
        fir_14.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso4.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(115);
        fuk_02.setMinWidth(1);
        fuk_02.setStyle("styledBoldDark10");
        fso3.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("text");
        fir_15.setField("description");
        fuk_02.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlign(frs_0.b);
        fuk_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_02);
        fqm_05.setInsets(new Insets(10, 0, 0, 0));
        fqh_03.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso3.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        return fsQ2;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setVisible(false);
        fso3.setExpandable(false);
        fso3.setNonBlocking(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setLocal(true);
        fiy_12.setName("questListBar");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.e);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(19, 20));
        fsQ2.setIdealSizeMaxColumns(10);
        fsQ2.setIdealSizeMaxRows(1);
        fsQ2.setIdealSizeMinColumns(1);
        fsQ2.setIdealSizeMinRows(1);
        fso3.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.e);
        fsQ2.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("content");
        fiy_13.setField("quests");
        fiy_13.setLocal(true);
        fiy_13.setName("questListBar");
        fsQ2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        faf_22.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_23.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_23.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        faf_22.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso4.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setStyle("AchievementListComplete");
        fso4.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(-2, -2));
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("visible");
        fir_12.setField("isCompleted");
        fsk_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        fsk_03.setStyle("AchievementListInactive");
        fso4.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(-2, -2));
        fsk_03.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("visible");
        fir_13.setField("isActivated");
        fsk_03.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_02);
        fir_13.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        far_24.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_24.onChildrenAdded();
        fir_13.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        fsk_04.setStyle("AchievementListActive");
        fso4.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(-2, -2));
        fsk_04.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("visible");
        fir_14.setField("isActivated");
        fsk_04.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_02);
        fir_14.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fan_2 fan_22 = new fan_2();
        fan_22.onCheckOut();
        fan_22.setElementMap(fyy_02);
        far_25.addBasicElement(fan_22);
        fan_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        fan_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        fau_1 fau_13 = new fau_1();
        fau_13.onCheckOut();
        fau_13.setElementMap(fyy_02);
        fan_22.addBasicElement(fau_13);
        fau_13.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("comparedValue");
        fir_15.setField("isCompleted");
        fau_13.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fau_13.onChildrenAdded();
        fan_22.onChildrenAdded();
        far_25.onChildrenAdded();
        fir_14.onChildrenAdded();
        fsk_04.onChildrenAdded();
        String string = "quest";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fij_12);
        }
        fso4.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_02);
        fir_16.setAttribute("value");
        fij_12.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        fir_16.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso4.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso fso5 = fso3;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 0, 15, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_02);
        fip_23.setAlign(frs_0.e);
        fso3.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(260, 45));
        fsk_02.setStyle("ScrollBorderTop2");
        fso2.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.c);
        fid_12.setSize(new fjf_2(-2, -2));
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fsk_02.onChildrenAdded();
        return fsk_02;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(260, 45));
        fsk_02.setStyle("ScrollBorderBottom2");
        fso2.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.o);
        fid_12.setSize(new fjf_2(-2, -2));
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fsk_02.onChildrenAdded();
        return fsk_02;
    }
}

