/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cQu
 */
public class cqu_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        String string = "craftWindow";
        fvk_0 fvk_02 = new fvk_0();
        fvk_02.onCheckOut();
        fvk_02.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fvk_02);
        }
        fvk_02.setPack(true);
        fvk_02.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fvk_02.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setStyle("windowNew");
        fvk_02.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(10, 5, 12, 5));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setSize(new fjf_2(100.0f, 100.0f));
        fso3.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fvM fvM2 = new fvM();
        fvM2.onCheckOut();
        fvM2.setElementMap(fyy_03);
        fvM2.setExpandable(false);
        fso3.addBasicElement(fvM2);
        fvM2.onAttributesInitialized();
        fvM fvM3 = fvM2;
        fqj fqj3 = ((fvE)fvM3).getAppearance();
        fqj3.setElementMap(fyy_03);
        fvM2.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 10, 0, 10));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_03);
        fso5.setStyle("titleBar");
        fvM2.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fso fso6 = fso5;
        fqj fqj4 = ((fvE)fso6).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso5.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(3, 20, 3, 20));
        fqj4.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso7.setExpandable(false);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.e);
        fso7.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("StyledBold16White");
        fso7.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("text");
        fiy_12.setField("name");
        fiy_12.setName("recipeView");
        fsM2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso7.onChildrenAdded();
        fso5.onChildrenAdded();
        fvM2.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_03);
        fso3.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fso fso9 = fso8;
        fqj fqj5 = ((fvE)fso9).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso8.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 12, 0, 12));
        fqj5.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj5.onChildrenAdded();
        String string2 = "windowContentContainer";
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fso10);
        }
        fso8.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fus_0 fus_02 = new fus_0();
        fus_02.onCheckOut();
        fus_02.setElementMap(fyy_03);
        fso10.addBasicElement(fus_02);
        fus_02.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("content");
        fiy_13.setName("recipeView");
        fus_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_03);
        fus_02.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        String string3 = "recipe";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fij_12);
        }
        faf_22.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("value");
        fiy_14.setName("recipeView");
        fij_12.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        faf_22.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.d);
        fso11.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setExpandable(false);
        fuk_02.setNonBlocking(true);
        fuk_02.setPrefSize(new fjf_2(46, 0));
        fuk_02.setStyle("whiteBold");
        fso11.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_03);
        fir_12.setAttribute("text");
        fir_12.setField("levelShort");
        fuk_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fqh_03.setAlign(frs_0.d);
        fuk_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("visible");
        fiy_15.setField("isConceptual");
        fiy_15.setLocal(true);
        fiy_15.setName("craft");
        fuk_02.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        fiy_15.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_03);
        far_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_15.onChildrenAdded();
        fuk_0 fuk_04 = fuk_02;
        fqh_0 fqh_04 = (fqh_0)((fvE)fuk_04).getAppearance();
        fqh_04.setElementMap(fyy_03);
        fuk_02.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(0, 6, 0, 3));
        fqh_04.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_04.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_03);
        fso12.setExpandable(false);
        fso12.setNonBlocking(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.crafts:openProducedItemDescription(recipe,craftWindow);wakfu.crafts:clickOnRecipeResult(recipe)");
        fso12.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(recipeDesc)");
        fso12.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fso12.setOnPopupHide(fdf_22);
        fso12.setPrefSize(new fjf_2(54, 54));
        fso11.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        String string4 = "recipeDesc";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_03);
        if (fyy_03 != null && string4 != null) {
            fyy_03.a(string4, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fso12.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_03);
        fso13.setPrefSize(new fjf_2(10, 0));
        fso13.setStyle("popup");
        fil_12.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setHorizontal(false);
        fso13.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fuk_0 fuk_05 = new fuk_0();
        fuk_05.onCheckOut();
        fuk_05.setElementMap(fyy_03);
        fuk_05.setExpandable(false);
        fuk_05.setStyle("PopupInformation");
        String string5 = "%rightClickToShowDetailWindow%";
        string5 = string5.replace("%rightClickToShowDetailWindow%", fpm_0.b().c("rightClickToShowDetailWindow"));
        fuk_05.c(string5);
        fso13.addBasicElement(fuk_05);
        fuk_05.onAttributesInitialized();
        fuk_0 fuk_06 = fuk_05;
        fqh_0 fqh_05 = (fqh_0)((fvE)fuk_06).getAppearance();
        fqh_05.setElementMap(fyy_03);
        fqh_05.setAlignment(frs_0.d);
        fuk_05.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_03);
        fqg_02.setColor(new azf_2(0.8f, 0.8f, 0.8f, 0.8f));
        fqh_05.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqh_05.onChildrenAdded();
        fuk_05.onChildrenAdded();
        fuk_0 fuk_07 = new fuk_0();
        fuk_07.onCheckOut();
        fuk_07.setElementMap(fyy_03);
        fuk_07.setMaxWidth(250);
        fuk_07.setMinWidth(1);
        fuk_07.setStyle("white");
        fso13.addBasicElement(fuk_07);
        fuk_07.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_03);
        fir_13.setAttribute("visible");
        fir_13.setField("criterionDescription");
        fuk_07.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        fir_13.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        far_23.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_23.onChildrenAdded();
        fir_13.onChildrenAdded();
        fuk_0 fuk_08 = fuk_07;
        fqh_0 fqh_06 = (fqh_0)((fvE)fuk_08).getAppearance();
        fqh_06.setElementMap(fyy_03);
        fqh_06.setAlign(frs_0.d);
        fuk_07.addBasicElement(fqh_06);
        fqh_06.onAttributesInitialized();
        fqh_06.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_03);
        fir_14.setAttribute("text");
        fir_14.setField("criterionDescription");
        fuk_07.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fuk_07.onChildrenAdded();
        fso13.onChildrenAdded();
        fil_12.onChildrenAdded();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso12.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso14 = fso12;
        fqj fqj6 = ((fvE)fso14).getAppearance();
        fqj6.setElementMap(fyy_03);
        fso12.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(0, 3, 0, 3));
        fqj6.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqj6.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setDisplaySize(new fjf_2(48, 48));
        fsk_02.setExpandable(false);
        fsk_02.setNonBlocking(true);
        fso12.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(-2, -2));
        fsk_02.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_03);
        fir_15.setAttribute("texture");
        fir_15.setField("themeItemBorderUrl");
        fqv2.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        String string6 = "recipeIcon";
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_03);
        if (fyy_03 != null && string6 != null) {
            fyy_03.a(string6, fsk_03);
        }
        fsk_03.setDisplaySize(new fjf_2(48, 48));
        fsk_03.setNonBlocking(true);
        fso12.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.i);
        fid_15.setSize(new fjf_2(-2, -2));
        fsk_03.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_03);
        fsk_03.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_03);
        fir_16.setAttribute("texture");
        fir_16.setField("iconUrl");
        fqv3.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        fir_16.onChildrenAdded();
        fqv3.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_03);
        fsk_04.setDisplaySize(new fjf_2(16, 16));
        fsk_04.setStyle("craftUpgrade");
        fso12.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fir_1 fir_17 = new fir_1();
        fir_17.onCheckOut();
        fir_17.setElementMap(fyy_03);
        fir_17.setAttribute("visible");
        fir_17.setField("isUpgrade");
        fsk_04.addBasicElement(fir_17);
        fir_17.onAttributesInitialized();
        fir_17.onChildrenAdded();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_03);
        fid_16.setAlign(frk_0.q);
        fid_16.setXOffset(-3);
        fid_16.setYOffset(6);
        fsk_04.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_03);
        fsM4.setNonBlocking(true);
        fsM4.setStyle("White10Bordered");
        fso12.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_03);
        fid_17.setAlign(frk_0.q);
        fsM4.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fsM fsM5 = fsM4;
        fqh_0 fqh_07 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_07.setElementMap(fyy_03);
        fsM4.addBasicElement(fqh_07);
        fqh_07.onAttributesInitialized();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_03);
        fqm_06.setInsets(new Insets(0, 6, 6, 0));
        fqh_07.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqh_07.onChildrenAdded();
        this.a(fsM4);
        fsM4.onChildrenAdded();
        fso12.onChildrenAdded();
        this.a(fso11);
        this.b(fso11);
        this.c(fso11);
        this.d(fso11);
        fso11.onChildrenAdded();
        faf_22.onChildrenAdded();
        fus_02.onChildrenAdded();
        fso10.onChildrenAdded();
        fso8.onChildrenAdded();
        fso3.onChildrenAdded();
        this.a(fvk_02);
        this.b(fvk_02);
        this.c(fvk_02);
        this.d(fvk_02);
        fvk_02.onChildrenAdded();
        return fvk_02;
    }

    public fyo a(fsM fsM2) {
        fyy_0 fyy_02 = this.a.peek();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("text");
        fir_12.setField("quantityText");
        fsM2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        return fir_12;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(3, 8, 0, 3));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.d);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setExpandable(false);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.b);
        fin_23.setHorizontal(false);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setNonBlocking(true);
        fuk_02.setPrefSize(new fjf_2(150, 0));
        fuk_02.setStyle("Bold");
        fso5.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("text");
        fir_12.setField("nameWithRarity");
        fuk_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fuk_02.onChildrenAdded();
        String string = "ingredientList";
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fsQ2);
        }
        fsQ2.setCellSize(new fjf_2(27, 26));
        fsQ2.setExpandable(false);
        fsQ2.setPrefSize(new fjf_2(216, 26));
        fso5.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fsQ fsQ3 = fsQ2;
        fqr fqr2 = (fqr)((fvE)fsQ3).getAppearance();
        fqr2.setElementMap(fyy_02);
        fsQ2.addBasicElement(fqr2);
        fqr2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(3, 0, 0, 0));
        fqr2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqr2.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("content");
        fir_13.setField("ingredients");
        fsQ2.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fdi_1 fdi_12 = new fdi_1();
        fdi_12.a("wakfu.crafts:clickOnRecipeIngredient");
        faf_22.setOnItemClick(fdi_12);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        String string2 = "ingredient";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fij_12);
        }
        faf_22.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("value");
        fij_12.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fij_12.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso6.setNonBlocking(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.crafts:openIngredientDescription(ingredient,craftWindow)");
        fso6.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(descIngredient)");
        fso6.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fso6.setOnPopupHide(fdf_22);
        faf_22.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        String string3 = "descIngredient";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string3 != null) {
            fyy_02.a(string3, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fso6.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso7.setPrefSize(new fjf_2(10, 0));
        fso7.setStyle("popup");
        fil_12.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.a);
        fso7.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.b);
        fin_24.setHorizontal(false);
        fso7.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fuk_0 fuk_03 = new fuk_0();
        fuk_03.onCheckOut();
        fuk_03.setElementMap(fyy_02);
        fuk_03.setExpandable(false);
        fuk_03.setStyle("white");
        fso7.addBasicElement(fuk_03);
        fuk_03.onAttributesInitialized();
        fuk_0 fuk_04 = fuk_03;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_04).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.d);
        fuk_03.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("text");
        fir_15.setField("name");
        fuk_03.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fuk_03.onChildrenAdded();
        fuk_0 fuk_05 = new fuk_0();
        fuk_05.onCheckOut();
        fuk_05.setElementMap(fyy_02);
        fuk_05.setExpandable(false);
        fuk_05.setStyle("white");
        String string4 = "(%desc.missingIngredient%)";
        string4 = string4.replace("%desc.missingIngredient%", fpm_0.b().c("desc.missingIngredient"));
        fuk_05.c(string4);
        fso7.addBasicElement(fuk_05);
        fuk_05.onAttributesInitialized();
        fuk_0 fuk_06 = fuk_05;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_06).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlign(frs_0.d);
        fuk_05.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_02);
        fir_16.setAttribute("visible");
        fir_16.setField("isPossessed");
        fuk_05.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        fir_16.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        far_23.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_23.onChildrenAdded();
        fir_16.onChildrenAdded();
        fuk_05.onChildrenAdded();
        fso7.onChildrenAdded();
        fil_12.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso8.setExpandable(false);
        fso6.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso8.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso9 = fso8;
        fqj fqj3 = ((fvE)fso9).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso8.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 0, 0, 1));
        fqj3.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj3.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(26, 26));
        fsk_02.setNonBlocking(true);
        fso8.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(-2, -2));
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_17 = new fir_1();
        fir_17.onCheckOut();
        fir_17.setElementMap(fyy_02);
        fir_17.setAttribute("texture");
        fir_17.setField("themeItemBorderUrl");
        fqv2.addBasicElement(fir_17);
        fir_17.onAttributesInitialized();
        fir_17.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        String string5 = "icon";
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        if (fyy_02 != null && string5 != null) {
            fyy_02.a(string5, fsk_03);
        }
        fsk_03.setDisplaySize(new fjf_2(26, 26));
        fsk_03.setNonBlocking(true);
        fso8.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(-2, -2));
        fsk_03.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fsk_03.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fir_1 fir_18 = new fir_1();
        fir_18.onCheckOut();
        fir_18.setElementMap(fyy_02);
        fir_18.setAttribute("texture");
        fir_18.setField("iconUrl");
        fqv3.addBasicElement(fir_18);
        fir_18.onAttributesInitialized();
        fir_18.onChildrenAdded();
        fqv3.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("White10Bordered");
        fso8.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.q);
        fsM2.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fsM fsM3 = fsM2;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fsM2.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 0, 4, 4));
        fqh_04.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_04.onChildrenAdded();
        fir_1 fir_19 = new fir_1();
        fir_19.onCheckOut();
        fir_19.setElementMap(fyy_02);
        fir_19.setAttribute("text");
        fir_19.setField("quantity");
        fsM2.addBasicElement(fir_19);
        fir_19.onAttributesInitialized();
        fir_19.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso8.onChildrenAdded();
        fso6.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        fso5.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setPrefSize(new fjf_2(90, 0));
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 3, 0, 3));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(0, 6, 0, 6));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.e);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setExpandable(false);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("whiteBold");
        fso5.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("text");
        fir_12.setField("productionPercentageShort");
        fuk_02.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setField("isConceptual");
        fiy_12.setLocal(true);
        fiy_12.setName("craft");
        fso5.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        far_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fso5.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso6.setExpandable(false);
        fso3.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.d);
        fso6.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        String string = "craftXpText";
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fuk_04);
        }
        fuk_04.setExpandable(false);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(xpGainPopup,craftXpText)");
        fuk_04.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fuk_04.setOnPopupHide(fdf_22);
        fuk_04.setStyle("whiteBold");
        fso6.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("text");
        fir_13.setField("craftXp");
        fuk_04.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fuk_0 fuk_05 = fuk_04;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_05).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlign(frs_0.f);
        fuk_04.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("text");
        fiy_13.setField("craftXp");
        fiy_13.setName("recipeView");
        fuk_04.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(16, 14));
        fsk_02.setExpandable(false);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("xpIcon");
        fso6.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 3, 0, 0));
        fqp2.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqp2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        String string2 = "xpGainPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fso6.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso7.setPrefSize(new fjf_2(10, 0));
        fso7.setStyle("popup");
        fil_12.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fuk_0 fuk_06 = new fuk_0();
        fuk_06.onCheckOut();
        fuk_06.setElementMap(fyy_02);
        fuk_06.setExpandable(false);
        fuk_06.setStyle("white");
        String string3 = "%craft.base.xp%";
        string3 = string3.replace("%craft.base.xp%", fpm_0.b().c("craft.base.xp"));
        fuk_06.c(string3);
        fso7.addBasicElement(fuk_06);
        fuk_06.onAttributesInitialized();
        fuk_0 fuk_07 = fuk_06;
        fqh_0 fqh_04 = (fqh_0)((fvE)fuk_07).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fqh_04.setAlign(frs_0.d);
        fuk_06.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fuk_06.onChildrenAdded();
        fuk_0 fuk_08 = new fuk_0();
        fuk_08.onCheckOut();
        fuk_08.setElementMap(fyy_02);
        fuk_08.setStyle("white");
        fuk_08.c("craftXp");
        fso7.addBasicElement(fuk_08);
        fuk_08.onAttributesInitialized();
        fuk_0 fuk_09 = fuk_08;
        fqh_0 fqh_05 = (fqh_0)((fvE)fuk_09).getAppearance();
        fqh_05.setElementMap(fyy_02);
        fqh_05.setAlign(frs_0.d);
        fuk_08.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqh_05.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("text");
        fiy_14.setField("baseCraftXp");
        fiy_14.setName("recipeView");
        fuk_08.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fuk_08.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        fsk_04.setDisplaySize(new fjf_2(16, 14));
        fsk_04.setExpandable(false);
        fsk_04.setNonBlocking(true);
        fsk_04.setStyle("xpIcon");
        fso7.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fsk_0 fsk_05 = fsk_04;
        fqp fqp3 = (fqp)((fvE)fsk_05).getAppearance();
        fqp3.setElementMap(fyy_02);
        fsk_04.addBasicElement(fqp3);
        fqp3.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(0, 3, 0, 0));
        fqp3.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqp3.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fso7.onChildrenAdded();
        fil_12.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("visible");
        fiy_15.setField("isConceptual");
        fiy_15.setLocal(true);
        fiy_15.setName("craft");
        fso6.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        fiy_15.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fan_2 fan_22 = new fan_2();
        fan_22.onCheckOut();
        fan_22.setElementMap(fyy_02);
        far_23.addBasicElement(fan_22);
        fan_22.onAttributesInitialized();
        fau_1 fau_13 = new fau_1();
        fau_13.onCheckOut();
        fau_13.setElementMap(fyy_02);
        fan_22.addBasicElement(fau_13);
        fau_13.onAttributesInitialized();
        fau_13.onChildrenAdded();
        fan_2 fan_23 = new fan_2();
        fan_23.onCheckOut();
        fan_23.setElementMap(fyy_02);
        fan_22.addBasicElement(fan_23);
        fan_23.onAttributesInitialized();
        fam_1 fam_12 = new fam_1();
        fam_12.onCheckOut();
        fam_12.setElementMap(fyy_02);
        fam_12.setValue("0");
        fan_23.addBasicElement(fam_12);
        fam_12.onAttributesInitialized();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("comparedValue");
        fir_14.setField("craftXp");
        fam_12.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fam_12.onChildrenAdded();
        fam_1 fam_13 = new fam_1();
        fam_13.onCheckOut();
        fam_13.setElementMap(fyy_02);
        fam_13.setValue("0");
        fan_23.addBasicElement(fam_13);
        fam_13.onAttributesInitialized();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("comparedValue");
        fir_15.setField("productionPercentageValue");
        fam_13.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fam_13.onChildrenAdded();
        fan_23.onChildrenAdded();
        fan_22.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_15.onChildrenAdded();
        fso6.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setExpandable(false);
        fso3.setPrefSize(new fjf_2(22, 0));
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fso fso4 = fso3;
        fqj fqj2 = ((fvE)fso4).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso3.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 3, 0, 3));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setVisible(false);
        fso3.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso5.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("visible");
        fir_12.setField("canUseAsIngredient");
        fso5.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        String string = "displayLinkedRecipesButton";
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fru_02);
        }
        fru_02.setStyle("yellowSmall");
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.crafts:displayRecipesWithIngredient(recipe)");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(displayLinkedRecipesPopup,displayLinkedRecipesButton)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fso5.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(16, 16));
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("passportRecipesDone");
        fso5.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(3, 3, 3, 3));
        fqp2.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqp2.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(-2, -2));
        fsk_02.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso5.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.e);
        fso3.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fbf_1 fbf_12 = new fbf_1();
        fbf_12.onCheckOut();
        fbf_12.setElementMap(fyy_02);
        fbf_12.setColor(new fyr_0("oddCellColor"));
        fqj2.addBasicElement(fbf_12);
        fbf_12.onAttributesInitialized();
        fbf_12.onChildrenAdded();
        fqj2.onChildrenAdded();
        return fqj2;
    }

    public fyo a(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fvk_02.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo b(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fru_02.setStyle("close");
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("unloadDialog");
        fru_02.setOnClick(fdt_12);
        fvk_02.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.e);
        fid_12.setSize(new fjf_2(-2, -2));
        fid_12.setXOffset(-18);
        fid_12.setYOffset(-12);
        fru_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo c(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setInitValue(true);
        fid_12.setSize(new fjf_2(200, 200));
        fid_12.setXOffset(-120);
        fvk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        return fid_12;
    }

    public fyo d(fvk_0 fvk_02) {
        fyy_0 fyy_02 = this.a.peek();
        String string = "displayLinkedRecipesPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fvk_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        fso2.setPrefSize(new fjf_2(10, 0));
        fso2.setStyle("popup");
        fil_12.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setStyle("white");
        String string2 = "%craft.displayLinkedRecipes%";
        string2 = string2.replace("%craft.displayLinkedRecipes%", fpm_0.b().c("craft.displayLinkedRecipes"));
        fuk_02.c(string2);
        fso2.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.d);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso2.onChildrenAdded();
        fil_12.onChildrenAdded();
        return fil_12;
    }
}

