/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cRb
 */
public class crb_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fso2.setPack(true);
        fso2.onAttributesInitialized();
        String string = "statePopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fso2.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setPrefSize(new fjf_2(10, 0));
        fso3.setStyle("popup");
        fil_12.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_03);
        fso4.setPrefSize(new fjf_2(150, 0));
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso4;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso4.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(3, 3, 3, 3));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso4.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_03);
        fso4.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setDisplaySize(new fjf_2(48, 48));
        fsk_02.setExpandable(false);
        fsk_02.setNonBlocking(true);
        fsk_02.setScaled(true);
        fso6.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.b);
        fsk_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("texture");
        fiy_12.setField("iconUrl");
        fiy_12.setLocal(true);
        fiy_12.setName("describedRunningEffect");
        fqv2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        fso6.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fso fso8 = fso7;
        fqj fqj3 = ((fvE)fso8).getAppearance();
        fqj3.setElementMap(fyy_03);
        fso7.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 3, 0, 0));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj3.onChildrenAdded();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.b);
        fin_24.setHorizontal(false);
        fso7.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_03);
        fso9.setExpandable(false);
        fso9.setPrefSize(new fjf_2(0, 20));
        fso9.setStyle("smallDarkBackground");
        fso7.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fso fso10 = fso9;
        fqj fqj4 = ((fvE)fso10).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso9.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(2, 0, 2, 0));
        fqj4.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqj4.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("whiteBold11");
        fso9.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlign(frs_0.d);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(0, 5, 0, 5));
        fqh_02.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("text");
        fiy_13.setField("nameAndLevel");
        fiy_13.setLocal(true);
        fiy_13.setName("describedRunningEffect");
        fuk_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso9.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso11.setExpandable(false);
        fso11.setPrefSize(new fjf_2(0, 20));
        fso11.setStyle("smallDarkBackground");
        fso7.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fso fso12 = fso11;
        fqj fqj5 = ((fvE)fso12).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso11.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(2, 0, 2, 0));
        fqj5.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(0, 5, 0, 5));
        fqj5.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj5.onChildrenAdded();
        fin_2 fin_25 = fin_2.checkOut();
        fin_25.setAlign(frs_0.d);
        fso11.addBasicElement(fin_25);
        fin_25.onAttributesInitialized();
        fin_25.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("visible");
        fiy_14.setField("remainingDurationText");
        fiy_14.setLocal(true);
        fiy_14.setName("describedRunningEffect");
        fso11.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        fiy_14.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_14.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_03);
        fsM2.setExpandable(false);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("whiteBold");
        String string2 = "%duration% ";
        string2 = string2.replace("%duration%", fpm_0.b().c("duration"));
        fsM2.c(string2);
        fso11.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM2.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_03);
        fuk_04.setNonBlocking(true);
        fuk_04.setStyle("white");
        fso11.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fuk_0 fuk_05 = fuk_04;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_05).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fqh_03.setAlign(frs_0.d);
        fuk_04.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("text");
        fiy_15.setField("remainingDurationText");
        fiy_15.setLocal(true);
        fiy_15.setName("describedRunningEffect");
        fuk_04.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("visible");
        fiy_16.setField("remainingDurationText");
        fiy_16.setLocal(true);
        fiy_16.setName("describedRunningEffect");
        fuk_04.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        fiy_16.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_03);
        far_23.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_16.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fso11.onChildrenAdded();
        fso7.onChildrenAdded();
        fso6.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_03);
        fso13.setExpandable(false);
        fso13.setPrefSize(new fjf_2(0, 20));
        fso13.setStyle("smallDarkBackground");
        fso4.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_03);
        fiy_17.setAttribute("visible");
        fiy_17.setName("isInFight");
        fso13.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_03);
        fiy_17.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fan_2 fan_22 = new fan_2();
        fan_22.onCheckOut();
        fan_22.setElementMap(fyy_03);
        far_24.addBasicElement(fan_22);
        fan_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_03);
        fan_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_03);
        fan_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_03);
        fiy_18.setAttribute("comparedValue");
        fiy_18.setField("description");
        fiy_18.setLocal(true);
        fiy_18.setName("describedRunningEffect");
        fai_12.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_03);
        fiy_18.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fab_2 fab_24 = new fab_2();
        fab_24.onCheckOut();
        fab_24.setElementMap(fyy_03);
        far_25.addBasicElement(fab_24);
        fab_24.onAttributesInitialized();
        fab_24.onChildrenAdded();
        far_25.onChildrenAdded();
        fiy_18.onChildrenAdded();
        fai_12.onChildrenAdded();
        fan_22.onChildrenAdded();
        far_24.onChildrenAdded();
        fiy_17.onChildrenAdded();
        fso fso14 = fso13;
        fqj fqj6 = ((fvE)fso14).getAppearance();
        fqj6.setElementMap(fyy_03);
        fso13.addBasicElement(fqj6);
        fqj6.onAttributesInitialized();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_03);
        fqm_06.setInsets(new Insets(2, 0, 2, 0));
        fqj6.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_03);
        fqo_04.setInsets(new Insets(5, 5, 5, 5));
        fqj6.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj6.onChildrenAdded();
        fuk_0 fuk_06 = new fuk_0();
        fuk_06.onCheckOut();
        fuk_06.setElementMap(fyy_03);
        fuk_06.setMaxWidth(230);
        fuk_06.setMinWidth(1);
        fuk_06.setNonBlocking(true);
        fuk_06.setStyle("narrow12");
        fso13.addBasicElement(fuk_06);
        fuk_06.onAttributesInitialized();
        fuk_0 fuk_07 = fuk_06;
        fqh_0 fqh_04 = (fqh_0)((fvE)fuk_07).getAppearance();
        fqh_04.setElementMap(fyy_03);
        fqh_04.setAlign(frs_0.d);
        fuk_06.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_03);
        fqg_02.setColor(new fyr_0("descriptionPopupColor"));
        fqh_04.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqh_04.onChildrenAdded();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_03);
        fiy_19.setAttribute("text");
        fiy_19.setField("description");
        fiy_19.setLocal(true);
        fiy_19.setName("describedRunningEffect");
        fuk_06.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        fiy_19.onChildrenAdded();
        fuk_06.onChildrenAdded();
        fso13.onChildrenAdded();
        fso fso15 = fso.checkOut();
        fso15.setElementMap(fyy_03);
        fso15.setExpandable(false);
        fso15.setStyle("smallDarkBackground");
        fso4.addBasicElement(fso15);
        fso15.onAttributesInitialized();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_03);
        fiy_110.setAttribute("visible");
        fiy_110.setField("effects");
        fiy_110.setLocal(true);
        fiy_110.setName("describedRunningEffect");
        fso15.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        far_2 far_26 = new far_2();
        far_26.onCheckOut();
        far_26.setElementMap(fyy_03);
        fiy_110.addBasicElement(far_26);
        far_26.onAttributesInitialized();
        fab_2 fab_25 = new fab_2();
        fab_25.onCheckOut();
        fab_25.setElementMap(fyy_03);
        far_26.addBasicElement(fab_25);
        fab_25.onAttributesInitialized();
        fab_25.onChildrenAdded();
        far_26.onChildrenAdded();
        fiy_110.onChildrenAdded();
        fso fso16 = fso15;
        fqj fqj7 = ((fvE)fso16).getAppearance();
        fqj7.setElementMap(fyy_03);
        fso15.addBasicElement(fqj7);
        fqj7.onAttributesInitialized();
        fqm_0 fqm_07 = fqm_0.checkOut();
        fqm_07.setElementMap(fyy_03);
        fqm_07.setInsets(new Insets(2, 0, 2, 0));
        fqj7.addBasicElement(fqm_07);
        fqm_07.onAttributesInitialized();
        fqm_07.onChildrenAdded();
        fqo_0 fqo_05 = new fqo_0();
        fqo_05.onCheckOut();
        fqo_05.setElementMap(fyy_03);
        fqo_05.setInsets(new Insets(5, 5, 5, 5));
        fqj7.addBasicElement(fqo_05);
        fqo_05.onAttributesInitialized();
        fqo_05.onChildrenAdded();
        fqj7.onChildrenAdded();
        fuk_0 fuk_08 = new fuk_0();
        fuk_08.onCheckOut();
        fuk_08.setElementMap(fyy_03);
        fuk_08.setEnableOnlySelectablePartInteraction(true);
        fuk_08.setMaxWidth(230);
        fuk_08.setMinWidth(1);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.spellDetails:processText(container,stateDetailPopup)");
        fuk_08.setOnClick(fdt_12);
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.a("wakfu.spellDetails:processText(container,stateDetailPopup)");
        fuk_08.setOnMouseEnter(fdy_12);
        fdz_1 fdz_12 = new fdz_1();
        fdz_12.a("xulor:closePopup");
        fuk_08.setOnMouseExit(fdz_12);
        fuk_08.setStyle("white11");
        fso15.addBasicElement(fuk_08);
        fuk_08.onAttributesInitialized();
        fiy_1 fiy_111 = fiy_1.checkOut();
        fiy_111.setElementMap(fyy_03);
        fiy_111.setAttribute("text");
        fiy_111.setField("effects");
        fiy_111.setLocal(true);
        fiy_111.setName("describedRunningEffect");
        fuk_08.addBasicElement(fiy_111);
        fiy_111.onAttributesInitialized();
        fiy_111.onChildrenAdded();
        fuk_0 fuk_09 = fuk_08;
        fqh_0 fqh_05 = (fqh_0)((fvE)fuk_09).getAppearance();
        fqh_05.setElementMap(fyy_03);
        fuk_08.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqm_0 fqm_08 = fqm_0.checkOut();
        fqm_08.setElementMap(fyy_03);
        fqm_08.setInsets(new Insets(0, 0, 0, 0));
        fqh_05.addBasicElement(fqm_08);
        fqm_08.onAttributesInitialized();
        fqm_08.onChildrenAdded();
        fqh_05.onChildrenAdded();
        fuk_08.onChildrenAdded();
        fso15.onChildrenAdded();
        fso4.onChildrenAdded();
        fso3.onChildrenAdded();
        fil_12.onChildrenAdded();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setAlign(frk_0.e);
        fid_12.setSize(new fjf_2(-2, -2));
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fiy_1 fiy_112 = fiy_1.checkOut();
        fiy_112.setElementMap(fyy_03);
        fiy_112.setAttribute("xOffset");
        fiy_112.setName("isInGame");
        fid_12.addBasicElement(fiy_112);
        fiy_112.onAttributesInitialized();
        far_2 far_27 = new far_2();
        far_27.onCheckOut();
        far_27.setElementMap(fyy_03);
        far_27.setElseValue("0");
        far_27.setValue("-258");
        fiy_112.addBasicElement(far_27);
        far_27.onAttributesInitialized();
        fai_1 fai_13 = new fai_1();
        fai_13.onCheckOut();
        fai_13.setElementMap(fyy_03);
        far_27.addBasicElement(fai_13);
        fai_13.onAttributesInitialized();
        fai_13.onChildrenAdded();
        far_27.onChildrenAdded();
        fiy_112.onChildrenAdded();
        fid_12.onChildrenAdded();
        this.a(fso2);
        this.b(fso2);
        this.c(fso2);
        this.g(fso2);
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 0, 0, 2));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        return fqj2;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fin_2 fin_22 = fin_2.checkOut();
        fso2.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        return null;
    }

    public fyo c(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setVisible(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setName("isAdmin");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fan_2 fan_22 = new fan_2();
        fan_22.onCheckOut();
        fan_22.setElementMap(fyy_02);
        far_22.addBasicElement(fan_22);
        fan_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        fan_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fan_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("comparedValue");
        fiy_13.setName("isInGame");
        fab_22.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fab_22.onChildrenAdded();
        fai_1 fai_13 = new fai_1();
        fai_13.onCheckOut();
        fai_13.setElementMap(fyy_02);
        fan_22.addBasicElement(fai_13);
        fai_13.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("comparedValue");
        fiy_14.setName("isInGame");
        fai_13.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fai_13.onChildrenAdded();
        fan_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.b);
        fso3.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        String string = "adminQuickMenuDrawer";
        fsy_0 fsy_02 = new fsy_0();
        fsy_02.onCheckOut();
        fsy_02.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fsy_02);
        }
        fsy_02.setAlign(frs_0.h);
        fsy_02.setExpandable(false);
        fsy_02.setHotSpotPosition(frs_0.b);
        fsy_02.setPack(true);
        fso3.addBasicElement(fsy_02);
        fsy_02.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("visible");
        fiy_15.setName("isInAdministratorGroup");
        fsy_02.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setThemeElementName("staticContainer");
        fsy_02.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("switchDrawer(adminQuickMenuDrawer)");
        fru_02.setOnClick(fdt_12);
        fru_02.setText("Quick menu");
        fso4.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_02.onChildrenAdded();
        fso4.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setStyle("Caracs");
        fso5.setThemeElementName("popupContainer");
        fsy_02.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso5.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("bold");
        fsM2.c("TP");
        fso5.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso5.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_02);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.adminQuickMenu:teleportToMarket");
        fru_03.setOnClick(fdt_13);
        fru_03.setText("Market");
        fso6.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        fru_03.onChildrenAdded();
        fru_0 fru_04 = new fru_0();
        fru_04.onCheckOut();
        fru_04.setElementMap(fyy_02);
        fdt_1 fdt_14 = new fdt_1();
        fdt_14.a("wakfu.adminQuickMenu:teleportToEnchantingTable");
        fru_04.setOnClick(fdt_14);
        fru_04.setText("Enchant");
        fso6.addBasicElement(fru_04);
        fru_04.onAttributesInitialized();
        fru_04.onChildrenAdded();
        fso6.onChildrenAdded();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso5.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fru_0 fru_05 = new fru_0();
        fru_05.onCheckOut();
        fru_05.setElementMap(fyy_02);
        fdt_1 fdt_15 = new fdt_1();
        fdt_15.a("wakfu.adminQuickMenu:teleportToWorkshop");
        fru_05.setOnClick(fdt_15);
        fru_05.setText("Workshop");
        fso7.addBasicElement(fru_05);
        fru_05.onAttributesInitialized();
        fru_05.onChildrenAdded();
        fru_0 fru_06 = new fru_0();
        fru_06.onCheckOut();
        fru_06.setElementMap(fyy_02);
        fdt_1 fdt_16 = new fdt_1();
        fdt_16.a("wakfu.adminQuickMenu:teleportToRift");
        fru_06.setOnClick(fdt_16);
        fru_06.setText("Rift");
        fso7.addBasicElement(fru_06);
        fru_06.onAttributesInitialized();
        fru_06.onChildrenAdded();
        fso7.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso5.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fru_0 fru_07 = new fru_0();
        fru_07.onCheckOut();
        fru_07.setElementMap(fyy_02);
        fdt_1 fdt_17 = new fdt_1();
        fdt_17.a("wakfu.adminQuickMenu:teleportToDungeon");
        fru_07.setOnClick(fdt_17);
        fru_07.setText("Dungeon");
        fso8.addBasicElement(fru_07);
        fru_07.onAttributesInitialized();
        fru_07.onChildrenAdded();
        fru_0 fru_08 = new fru_0();
        fru_08.onCheckOut();
        fru_08.setElementMap(fyy_02);
        fdt_1 fdt_18 = new fdt_1();
        fdt_18.a("wakfu.adminQuickMenu:teleportToThreePlayerDungeon");
        fru_08.setOnClick(fdt_18);
        fru_08.setText("3P dungeon");
        fso8.addBasicElement(fru_08);
        fru_08.onAttributesInitialized();
        fru_08.onChildrenAdded();
        fso8.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setStyle("bold");
        fsM4.c("Give");
        fso5.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlign(frs_0.e);
        fsM4.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_02);
        fso5.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(32, 32));
        fdt_1 fdt_19 = new fdt_1();
        fdt_19.a("wakfu.adminQuickMenu:giveShards");
        fsk_02.setOnClick(fdt_19);
        fso9.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(-2, -2));
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_02);
        fiy_16.setAttribute("texture");
        fiy_16.setField("shardsItemIcon");
        fiy_16.setName("adminQuickMenu");
        fqv2.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        fsk_03.setDisplaySize(new fjf_2(32, 32));
        fdt_1 fdt_110 = new fdt_1();
        fdt_110.a("wakfu.adminQuickMenu:givePowder");
        fsk_03.setOnClick(fdt_110);
        fso9.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(-2, -2));
        fsk_03.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fsk_03.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_02);
        fiy_17.setAttribute("texture");
        fiy_17.setField("powderItemIcon");
        fiy_17.setName("adminQuickMenu");
        fqv3.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        fqv3.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        fsk_04.setDisplaySize(new fjf_2(32, 32));
        fdt_1 fdt_111 = new fdt_1();
        fdt_111.a("wakfu.adminQuickMenu:giveKeys");
        fsk_04.setOnClick(fdt_111);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(keysPopup)");
        fsk_04.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fsk_04.setOnPopupHide(fdf_22);
        fso9.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(-2, -2));
        fsk_04.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_02);
        fsk_04.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_02);
        fiy_18.setAttribute("texture");
        fiy_18.setField("keysItemIcon");
        fiy_18.setName("adminQuickMenu");
        fqv4.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        fiy_18.onChildrenAdded();
        fqv4.onChildrenAdded();
        String string2 = "keysPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fsk_04.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_02);
        fso10.setStyle("popup");
        fil_12.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setStyle("PopupInformation");
        fuk_02.c("Get keys to all dungeons, ultimate rifts and bosses");
        fso10.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_02.onChildrenAdded();
        fso10.onChildrenAdded();
        fil_12.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fso9.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_02);
        fso5.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fsk_0 fsk_05 = new fsk_0();
        fsk_05.onCheckOut();
        fsk_05.setElementMap(fyy_02);
        fsk_05.setDisplaySize(new fjf_2(32, 32));
        fdt_1 fdt_112 = new fdt_1();
        fdt_112.a("wakfu.adminQuickMenu:giveEquipment");
        fsk_05.setOnClick(fdt_112);
        fsk_05.setStyle("ShardWHITEFull");
        fso11.addBasicElement(fsk_05);
        fsk_05.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setAlign(frk_0.i);
        fid_15.setSize(new fjf_2(-2, -2));
        fsk_05.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fsk_05.onChildrenAdded();
        fsk_0 fsk_06 = new fsk_0();
        fsk_06.onCheckOut();
        fsk_06.setElementMap(fyy_02);
        fsk_06.setDisplaySize(new fjf_2(32, 32));
        fdt_1 fdt_113 = new fdt_1();
        fdt_113.a("wakfu.adminQuickMenu:giveAdminItem");
        fsk_06.setOnClick(fdt_113);
        fso11.addBasicElement(fsk_06);
        fsk_06.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_02);
        fid_16.setAlign(frk_0.i);
        fid_16.setSize(new fjf_2(-2, -2));
        fsk_06.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_02);
        fsk_06.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_02);
        fiy_19.setAttribute("texture");
        fiy_19.setField("adminItemIcon");
        fiy_19.setName("adminQuickMenu");
        fqv5.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        fiy_19.onChildrenAdded();
        fqv5.onChildrenAdded();
        fsk_06.onChildrenAdded();
        fsk_0 fsk_07 = new fsk_0();
        fsk_07.onCheckOut();
        fsk_07.setElementMap(fyy_02);
        fsk_07.setDisplaySize(new fjf_2(32, 32));
        fdt_1 fdt_114 = new fdt_1();
        fdt_114.a("wakfu.adminQuickMenu:giveKamas");
        fsk_07.setOnClick(fdt_114);
        fsk_07.setStyle("Kama");
        fso11.addBasicElement(fsk_07);
        fsk_07.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_02);
        fid_17.setAlign(frk_0.i);
        fid_17.setSize(new fjf_2(-2, -2));
        fsk_07.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fsk_07.onChildrenAdded();
        fso11.onChildrenAdded();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_02);
        fsM6.setStyle("bold");
        fsM6.c("Fight");
        fso5.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fsM fsM7 = fsM6;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM7).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fqh_04.setAlign(frs_0.e);
        fsM6.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fsM6.onChildrenAdded();
        fso fso12 = fso.checkOut();
        fso12.setElementMap(fyy_02);
        fso5.addBasicElement(fso12);
        fso12.onAttributesInitialized();
        fru_0 fru_09 = new fru_0();
        fru_09.onCheckOut();
        fru_09.setElementMap(fyy_02);
        fdt_1 fdt_115 = new fdt_1();
        fdt_115.a("wakfu.adminQuickMenu:winFight");
        fru_09.setOnClick(fdt_115);
        fru_09.setText("Win");
        fso12.addBasicElement(fru_09);
        fru_09.onAttributesInitialized();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_02);
        fiy_110.setAttribute("enabled");
        fiy_110.setName("isInFight");
        fru_09.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        fiy_110.onChildrenAdded();
        fru_09.onChildrenAdded();
        fru_0 fru_010 = new fru_0();
        fru_010.onCheckOut();
        fru_010.setElementMap(fyy_02);
        fdt_1 fdt_116 = new fdt_1();
        fdt_116.a("wakfu.adminQuickMenu:fleeFight");
        fru_010.setOnClick(fdt_116);
        fru_010.setText("Flee");
        fso12.addBasicElement(fru_010);
        fru_010.onAttributesInitialized();
        fiy_1 fiy_111 = fiy_1.checkOut();
        fiy_111.setElementMap(fyy_02);
        fiy_111.setAttribute("enabled");
        fiy_111.setName("isInFight");
        fru_010.addBasicElement(fiy_111);
        fiy_111.onAttributesInitialized();
        fiy_111.onChildrenAdded();
        fru_010.onChildrenAdded();
        fso12.onChildrenAdded();
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_02);
        fso5.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fru_0 fru_011 = new fru_0();
        fru_011.onCheckOut();
        fru_011.setElementMap(fyy_02);
        fdt_1 fdt_117 = new fdt_1();
        fdt_117.a("wakfu.adminQuickMenu:pauseFight");
        fru_011.setOnClick(fdt_117);
        fru_011.setText("Poz");
        fso13.addBasicElement(fru_011);
        fru_011.onAttributesInitialized();
        fiy_1 fiy_112 = fiy_1.checkOut();
        fiy_112.setElementMap(fyy_02);
        fiy_112.setAttribute("enabled");
        fiy_112.setName("isInFight");
        fru_011.addBasicElement(fiy_112);
        fiy_112.onAttributesInitialized();
        fiy_112.onChildrenAdded();
        fru_011.onChildrenAdded();
        fru_0 fru_012 = new fru_0();
        fru_012.onCheckOut();
        fru_012.setElementMap(fyy_02);
        fdt_1 fdt_118 = new fdt_1();
        fdt_118.a("wakfu.adminQuickMenu:startCollectFight");
        fru_012.setOnClick(fdt_118);
        fru_012.setText("Collect");
        fso13.addBasicElement(fru_012);
        fru_012.onAttributesInitialized();
        this.a(fru_012);
        fru_012.onChildrenAdded();
        fso13.onChildrenAdded();
        this.d(fso5);
        this.e(fso5);
        this.f(fso5);
        fso5.onChildrenAdded();
        fsy_02.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo a(fru_0 fru_02) {
        fyy_0 fyy_02 = this.a.peek();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("enabled");
        fiy_12.setName("isInFight");
        fru_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        far_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        return fiy_12;
    }

    public fyo d(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(22, 22));
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.adminQuickMenu:spawnTestMonster");
        fsk_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(testMobPopup)");
        fsk_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fsk_02.setOnPopupHide(fdf_22);
        fsk_02.setStyle("SmallMonster");
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(-2, -2));
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        String string = "testMobPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fil_12);
        }
        fil_12.setAlign(frs_0.b);
        fil_12.setHotSpotPosition(frs_0.h);
        fsk_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setStyle("popup");
        fil_12.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setStyle("PopupInformation");
        fso4.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("text");
        fiy_12.setField("testMonsterName");
        fiy_12.setName("adminQuickMenu");
        fuk_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso4.onChildrenAdded();
        fil_12.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        fsk_03.setDisplaySize(new fjf_2(22, 22));
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.adminQuickMenu:spawnRegularMonster");
        fsk_03.setOnClick(fdt_13);
        fde_2 fde_23 = new fde_2();
        fde_23.a("popup(mobPopup)");
        fsk_03.setOnPopupDisplay(fde_23);
        fdf_2 fdf_23 = new fdf_2();
        fdf_23.a("closePopup");
        fsk_03.setOnPopupHide(fdf_23);
        fsk_03.setStyle("ProtectorEcosystemMonster");
        fso3.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(-2, -2));
        fsk_03.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        String string2 = "mobPopup";
        fil_1 fil_13 = new fil_1();
        fil_13.onCheckOut();
        fil_13.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fil_13);
        }
        fil_13.setAlign(frs_0.b);
        fil_13.setHotSpotPosition(frs_0.h);
        fsk_03.addBasicElement(fil_13);
        fil_13.onAttributesInitialized();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setStyle("popup");
        fil_13.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fuk_0 fuk_03 = new fuk_0();
        fuk_03.onCheckOut();
        fuk_03.setElementMap(fyy_02);
        fuk_03.setStyle("PopupInformation");
        fso5.addBasicElement(fuk_03);
        fuk_03.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("text");
        fiy_13.setField("regularMonsterName");
        fiy_13.setName("adminQuickMenu");
        fuk_03.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fuk_03.onChildrenAdded();
        fso5.onChildrenAdded();
        fil_13.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo e(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("bold");
        fsM2.c("Misc");
        fso2.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        return fsM2;
    }

    public fyo f(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.adminQuickMenu:subscribe");
        fru_02.setOnClick(fdt_12);
        fru_02.setText("Sub");
        fso3.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fru_02.onChildrenAdded();
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_02);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.adminQuickMenu:xpCharacterAndCrafts");
        fru_03.setOnClick(fdt_13);
        fru_03.setText("XP");
        fso3.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        fru_03.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo g(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.b);
        fso3.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.c);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setVisible(false);
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setName("isAdmin");
        fso4.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fan_2 fan_22 = new fan_2();
        fan_22.onCheckOut();
        fan_22.setElementMap(fyy_02);
        far_22.addBasicElement(fan_22);
        fan_22.onAttributesInitialized();
        fai_1 fai_12 = new fai_1();
        fai_12.onCheckOut();
        fai_12.setElementMap(fyy_02);
        fan_22.addBasicElement(fai_12);
        fai_12.onAttributesInitialized();
        fai_12.onChildrenAdded();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fan_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("comparedValue");
        fiy_13.setName("isInGame");
        fab_22.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fab_22.onChildrenAdded();
        fai_1 fai_13 = new fai_1();
        fai_13.onCheckOut();
        fai_13.setElementMap(fyy_02);
        fan_22.addBasicElement(fai_13);
        fai_13.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("comparedValue");
        fiy_14.setName("isInGame");
        fai_13.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fai_13.onChildrenAdded();
        fan_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_02);
        fso4.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fso4.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu:moderatorRequestUserRequest");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(moderationPopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setText("Request");
        fso4.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fip_2 fip_24 = new fip_2();
        fip_24.onCheckOut();
        fip_24.setElementMap(fyy_02);
        fip_24.setAlign(frs_0.b);
        fru_02.addBasicElement(fip_24);
        fip_24.onAttributesInitialized();
        fip_24.onChildrenAdded();
        String string = "moderationPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fil_12);
        }
        fil_12.setAlign(frs_0.a);
        fil_12.setHotSpotPosition(frs_0.c);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setPrefSize(new fjf_2(10, 0));
        fso5.setStyle("popup");
        fil_12.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.a);
        fso5.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        fsM2.c("Process next user request");
        fso5.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso5.onChildrenAdded();
        fil_12.onChildrenAdded();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_02);
        fiy_15.setAttribute("text");
        fiy_15.setName("numModeratorHelpRequestText");
        fru_02.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        fiy_15.onChildrenAdded();
        fru_02.onChildrenAdded();
        fru_0 fru_03 = new fru_0();
        fru_03.onCheckOut();
        fru_03.setElementMap(fyy_02);
        fru_03.setExpandable(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu:moderation");
        fru_03.setOnClick(fdt_13);
        fde_2 fde_23 = new fde_2();
        fde_23.a("popup(moderationPopup)");
        fru_03.setOnPopupDisplay(fde_23);
        fdf_2 fdf_23 = new fdf_2();
        fdf_23.a("closePopup");
        fru_03.setOnPopupHide(fdf_23);
        fru_03.setText("[M]");
        fso4.addBasicElement(fru_03);
        fru_03.onAttributesInitialized();
        fip_2 fip_25 = new fip_2();
        fip_25.onCheckOut();
        fip_25.setElementMap(fyy_02);
        fip_25.setAlign(frs_0.b);
        fru_03.addBasicElement(fip_25);
        fip_25.onAttributesInitialized();
        fip_25.onChildrenAdded();
        String string2 = "moderationPopup";
        fil_1 fil_13 = new fil_1();
        fil_13.onCheckOut();
        fil_13.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fil_13);
        }
        fil_13.setAlign(frs_0.a);
        fil_13.setHotSpotPosition(frs_0.c);
        fru_03.addBasicElement(fil_13);
        fil_13.onAttributesInitialized();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso6.setPrefSize(new fjf_2(10, 0));
        fso6.setStyle("popup");
        fil_13.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fii_2 fii_23 = fii_2.checkOut();
        fii_23.setElementMap(fyy_02);
        fii_23.setData(frg_0.a);
        fso6.addBasicElement(fii_23);
        fii_23.onAttributesInitialized();
        fii_23.onChildrenAdded();
        fsM fsM4 = new fsM();
        fsM4.onCheckOut();
        fsM4.setElementMap(fyy_02);
        fsM4.setStyle("PopupInformation");
        fsM4.c("Moderation");
        fso6.addBasicElement(fsM4);
        fsM4.onAttributesInitialized();
        fsM fsM5 = fsM4;
        fqh_0 fqh_03 = (fqh_0)((fvE)fsM5).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlignment(frs_0.d);
        fsM4.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fsM4.onChildrenAdded();
        fso6.onChildrenAdded();
        fil_13.onChildrenAdded();
        fru_03.onChildrenAdded();
        fru_0 fru_04 = new fru_0();
        fru_04.onCheckOut();
        fru_04.setElementMap(fyy_02);
        fru_04.setExpandable(false);
        fdt_1 fdt_14 = new fdt_1();
        fdt_14.a("wakfu:openAdminMonitorPanel");
        fru_04.setOnClick(fdt_14);
        fde_2 fde_24 = new fde_2();
        fde_24.a("popup(descAdminPanel)");
        fru_04.setOnPopupDisplay(fde_24);
        fdf_2 fdf_24 = new fdf_2();
        fdf_24.a("closePopup");
        fru_04.setOnPopupHide(fdf_24);
        fru_04.setText("[A]");
        fso4.addBasicElement(fru_04);
        fru_04.onAttributesInitialized();
        fip_2 fip_26 = new fip_2();
        fip_26.onCheckOut();
        fip_26.setElementMap(fyy_02);
        fip_26.setAlign(frs_0.b);
        fru_04.addBasicElement(fip_26);
        fip_26.onAttributesInitialized();
        fip_26.onChildrenAdded();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_02);
        fiy_16.setAttribute("visible");
        fiy_16.setName("hasDebugRights");
        fru_04.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        fiy_16.onChildrenAdded();
        String string3 = "descAdminPanel";
        fil_1 fil_14 = new fil_1();
        fil_14.onCheckOut();
        fil_14.setElementMap(fyy_02);
        if (fyy_02 != null && string3 != null) {
            fyy_02.a(string3, fil_14);
        }
        fil_14.setAlign(frs_0.a);
        fil_14.setHotSpotPosition(frs_0.c);
        fru_04.addBasicElement(fil_14);
        fil_14.onAttributesInitialized();
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_02);
        fso7.setPrefSize(new fjf_2(10, 0));
        fso7.setStyle("popup");
        fil_14.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fii_2 fii_24 = fii_2.checkOut();
        fii_24.setElementMap(fyy_02);
        fii_24.setData(frg_0.a);
        fso7.addBasicElement(fii_24);
        fii_24.onAttributesInitialized();
        fii_24.onChildrenAdded();
        fsM fsM6 = new fsM();
        fsM6.onCheckOut();
        fsM6.setElementMap(fyy_02);
        fsM6.setStyle("PopupInformation");
        fsM6.c("Admin Panel");
        fso7.addBasicElement(fsM6);
        fsM6.onAttributesInitialized();
        fsM fsM7 = fsM6;
        fqh_0 fqh_04 = (fqh_0)((fvE)fsM7).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fqh_04.setAlignment(frs_0.d);
        fsM6.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqh_04.onChildrenAdded();
        fsM6.onChildrenAdded();
        fso7.onChildrenAdded();
        fil_14.onChildrenAdded();
        fru_04.onChildrenAdded();
        fru_0 fru_05 = new fru_0();
        fru_05.onCheckOut();
        fru_05.setElementMap(fyy_02);
        fru_05.setExpandable(false);
        fdt_1 fdt_15 = new fdt_1();
        fdt_15.a("wakfu:openHeroBuildTempUI");
        fru_05.setOnClick(fdt_15);
        fru_05.setText("[HB]");
        fso4.addBasicElement(fru_05);
        fru_05.onAttributesInitialized();
        fip_2 fip_27 = new fip_2();
        fip_27.onCheckOut();
        fip_27.setElementMap(fyy_02);
        fip_27.setAlign(frs_0.b);
        fru_05.addBasicElement(fip_27);
        fip_27.onAttributesInitialized();
        fip_27.onChildrenAdded();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_02);
        fiy_17.setAttribute("visible");
        fiy_17.setName("hasDebugRights");
        fru_05.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        fru_05.onChildrenAdded();
        fru_0 fru_06 = new fru_0();
        fru_06.onCheckOut();
        fru_06.setElementMap(fyy_02);
        fru_06.setExpandable(false);
        fdt_1 fdt_16 = new fdt_1();
        fdt_16.a("wakfu:openAdminCharacterEditor");
        fru_06.setOnClick(fdt_16);
        fde_2 fde_25 = new fde_2();
        fde_25.a("popup(descCharactereditor)");
        fru_06.setOnPopupDisplay(fde_25);
        fdf_2 fdf_25 = new fdf_2();
        fdf_25.a("closePopup");
        fru_06.setOnPopupHide(fdf_25);
        fru_06.setText("[o_o]");
        fso4.addBasicElement(fru_06);
        fru_06.onAttributesInitialized();
        fip_2 fip_28 = new fip_2();
        fip_28.onCheckOut();
        fip_28.setElementMap(fyy_02);
        fip_28.setAlign(frs_0.b);
        fru_06.addBasicElement(fip_28);
        fip_28.onAttributesInitialized();
        fip_28.onChildrenAdded();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_02);
        fiy_18.setAttribute("visible");
        fiy_18.setName("hasDebugRights");
        fru_06.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        fiy_18.onChildrenAdded();
        String string4 = "descCharactereditor";
        fil_1 fil_15 = new fil_1();
        fil_15.onCheckOut();
        fil_15.setElementMap(fyy_02);
        if (fyy_02 != null && string4 != null) {
            fyy_02.a(string4, fil_15);
        }
        fil_15.setAlign(frs_0.a);
        fil_15.setHotSpotPosition(frs_0.c);
        fru_06.addBasicElement(fil_15);
        fil_15.onAttributesInitialized();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso8.setPrefSize(new fjf_2(10, 0));
        fso8.setStyle("popup");
        fil_15.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fii_2 fii_25 = fii_2.checkOut();
        fii_25.setElementMap(fyy_02);
        fii_25.setData(frg_0.a);
        fso8.addBasicElement(fii_25);
        fii_25.onAttributesInitialized();
        fii_25.onChildrenAdded();
        fsM fsM8 = new fsM();
        fsM8.onCheckOut();
        fsM8.setElementMap(fyy_02);
        fsM8.setStyle("PopupInformation");
        fsM8.c("Character Editor");
        fso8.addBasicElement(fsM8);
        fsM8.onAttributesInitialized();
        fsM fsM9 = fsM8;
        fqh_0 fqh_05 = (fqh_0)((fvE)fsM9).getAppearance();
        fqh_05.setElementMap(fyy_02);
        fqh_05.setAlignment(frs_0.d);
        fsM8.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqh_05.onChildrenAdded();
        fsM8.onChildrenAdded();
        fso8.onChildrenAdded();
        fil_15.onChildrenAdded();
        fru_06.onChildrenAdded();
        fru_0 fru_07 = new fru_0();
        fru_07.onCheckOut();
        fru_07.setElementMap(fyy_02);
        fru_07.setExpandable(false);
        fdt_1 fdt_17 = new fdt_1();
        fdt_17.a("wakfu:openStuffDebugPreviewEditor");
        fru_07.setOnClick(fdt_17);
        fde_2 fde_26 = new fde_2();
        fde_26.a("popup(previewPopup)");
        fru_07.setOnPopupDisplay(fde_26);
        fdf_2 fdf_26 = new fdf_2();
        fdf_26.a("closePopup");
        fru_07.setOnPopupHide(fdf_26);
        fru_07.setText("(>'_')>");
        fso4.addBasicElement(fru_07);
        fru_07.onAttributesInitialized();
        fip_2 fip_29 = new fip_2();
        fip_29.onCheckOut();
        fip_29.setElementMap(fyy_02);
        fip_29.setAlign(frs_0.b);
        fru_07.addBasicElement(fip_29);
        fip_29.onAttributesInitialized();
        fip_29.onChildrenAdded();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_02);
        fiy_19.setAttribute("visible");
        fiy_19.setName("hasDebugRights");
        fru_07.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        fiy_19.onChildrenAdded();
        String string5 = "previewPopup";
        fil_1 fil_16 = new fil_1();
        fil_16.onCheckOut();
        fil_16.setElementMap(fyy_02);
        if (fyy_02 != null && string5 != null) {
            fyy_02.a(string5, fil_16);
        }
        fil_16.setAlign(frs_0.a);
        fil_16.setHotSpotPosition(frs_0.c);
        fru_07.addBasicElement(fil_16);
        fil_16.onAttributesInitialized();
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_02);
        fso9.setPrefSize(new fjf_2(10, 0));
        fso9.setStyle("popup");
        fil_16.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fii_2 fii_26 = fii_2.checkOut();
        fii_26.setElementMap(fyy_02);
        fii_26.setData(frg_0.a);
        fso9.addBasicElement(fii_26);
        fii_26.onAttributesInitialized();
        fii_26.onChildrenAdded();
        fsM fsM10 = new fsM();
        fsM10.onCheckOut();
        fsM10.setElementMap(fyy_02);
        fsM10.setStyle("PopupInformation");
        fsM10.c("Equipment preview");
        fso9.addBasicElement(fsM10);
        fsM10.onAttributesInitialized();
        fsM fsM11 = fsM10;
        fqh_0 fqh_06 = (fqh_0)((fvE)fsM11).getAppearance();
        fqh_06.setElementMap(fyy_02);
        fqh_06.setAlignment(frs_0.d);
        fsM10.addBasicElement(fqh_06);
        fqh_06.onAttributesInitialized();
        fqh_06.onChildrenAdded();
        fsM10.onChildrenAdded();
        fso9.onChildrenAdded();
        fil_16.onChildrenAdded();
        fru_07.onChildrenAdded();
        fru_0 fru_08 = new fru_0();
        fru_08.onCheckOut();
        fru_08.setElementMap(fyy_02);
        fru_08.setExpandable(false);
        fdt_1 fdt_18 = new fdt_1();
        fdt_18.a("wakfu:openThemeInfoDialog");
        fru_08.setOnClick(fdt_18);
        fde_2 fde_27 = new fde_2();
        fde_27.a("popup(themeInfoPopup)");
        fru_08.setOnPopupDisplay(fde_27);
        fdf_2 fdf_27 = new fdf_2();
        fdf_27.a("closePopup");
        fru_08.setOnPopupHide(fdf_27);
        fru_08.setText("[UI]");
        fso4.addBasicElement(fru_08);
        fru_08.onAttributesInitialized();
        fip_2 fip_210 = new fip_2();
        fip_210.onCheckOut();
        fip_210.setElementMap(fyy_02);
        fip_210.setAlign(frs_0.b);
        fru_08.addBasicElement(fip_210);
        fip_210.onAttributesInitialized();
        fip_210.onChildrenAdded();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_02);
        fiy_110.setAttribute("visible");
        fiy_110.setName("hasDebugRights");
        fru_08.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        fiy_110.onChildrenAdded();
        String string6 = "themeInfoPopup";
        fil_1 fil_17 = new fil_1();
        fil_17.onCheckOut();
        fil_17.setElementMap(fyy_02);
        if (fyy_02 != null && string6 != null) {
            fyy_02.a(string6, fil_17);
        }
        fil_17.setAlign(frs_0.a);
        fil_17.setHotSpotPosition(frs_0.c);
        fru_08.addBasicElement(fil_17);
        fil_17.onAttributesInitialized();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_02);
        fso10.setPrefSize(new fjf_2(10, 0));
        fso10.setStyle("popup");
        fil_17.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fii_2 fii_27 = fii_2.checkOut();
        fii_27.setElementMap(fyy_02);
        fii_27.setData(frg_0.a);
        fso10.addBasicElement(fii_27);
        fii_27.onAttributesInitialized();
        fii_27.onChildrenAdded();
        this.h(fso10);
        fso10.onChildrenAdded();
        fil_17.onChildrenAdded();
        fru_08.onChildrenAdded();
        this.i(fso4);
        this.j(fso4);
        fso4.onChildrenAdded();
        this.k(fso3);
        fso3.onChildrenAdded();
        return fso3;
    }

    public fyo h(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        fsM2.c("Theme Info");
        fso2.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        return fsM2;
    }

    public fyo i(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu:openNinePatch");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(ninePatchPopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setText("[9]");
        fso2.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.b);
        fru_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setName("hasDebugRights");
        fru_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        String string = "ninePatchPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fil_12);
        }
        fil_12.setAlign(frs_0.a);
        fil_12.setHotSpotPosition(frs_0.c);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setPrefSize(new fjf_2(10, 0));
        fso3.setStyle("popup");
        fil_12.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.a);
        fso3.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        fsM2.c("9 Patch editor");
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso3.onChildrenAdded();
        fil_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo j(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fru_0 fru_02 = new fru_0();
        fru_02.onCheckOut();
        fru_02.setElementMap(fyy_02);
        fru_02.setExpandable(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu:openCinematicsSelectorDialog");
        fru_02.setOnClick(fdt_12);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(cinematicsPopup)");
        fru_02.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fru_02.setOnPopupHide(fdf_22);
        fru_02.setText("[MOV]");
        fso2.addBasicElement(fru_02);
        fru_02.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("visible");
        fiy_12.setName("videoDisabled");
        fru_02.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fan_2 fan_22 = new fan_2();
        fan_22.onCheckOut();
        fan_22.setElementMap(fyy_02);
        far_22.addBasicElement(fan_22);
        fan_22.onAttributesInitialized();
        fau_1 fau_12 = new fau_1();
        fau_12.onCheckOut();
        fau_12.setElementMap(fyy_02);
        fan_22.addBasicElement(fau_12);
        fau_12.onAttributesInitialized();
        fau_12.onChildrenAdded();
        fan_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.b);
        fru_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("visible");
        fiy_13.setName("hasDebugRights");
        fru_02.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        String string = "cinematicsPopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fil_12);
        }
        fil_12.setAlign(frs_0.a);
        fil_12.setHotSpotPosition(frs_0.c);
        fru_02.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setPrefSize(new fjf_2(10, 0));
        fso3.setStyle("popup");
        fil_12.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fii_2 fii_22 = fii_2.checkOut();
        fii_22.setElementMap(fyy_02);
        fii_22.setData(frg_0.a);
        fso3.addBasicElement(fii_22);
        fii_22.onAttributesInitialized();
        fii_22.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setStyle("PopupInformation");
        fsM2.c("Cinematics Selector");
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.d);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso3.onChildrenAdded();
        fil_12.onChildrenAdded();
        fru_02.onChildrenAdded();
        return fru_02;
    }

    public fyo k(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        String string = "stateBarWindow";
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fsQ2);
        }
        fsQ2.setAutoIdealSize(true);
        fsQ2.setCellSize(new fjf_2(34, 47));
        fsQ2.setExpandable(false);
        fsQ2.setHorizontal(false);
        fsQ2.setIdealSizeMaxColumns(6);
        fsQ2.setIdealSizeMinColumns(1);
        fsQ2.setNonBlocking(true);
        fdi_1 fdi_12 = new fdi_1();
        fdi_12.a("wakfu.controlCenter:openRunningEffectDescription");
        fsQ2.setOnItemClick(fdi_12);
        fdk_2 fdk_22 = new fdk_2();
        fdk_22.a("wakfu.popupInfos:closePopup");
        fsQ2.setOnItemOut(fdk_22);
        fdl_2 fdl_22 = new fdl_2();
        fdl_22.a("wakfu.popupInfos:showPopup(statePopup,stateBarWindow)");
        fsQ2.setOnItemOver(fdl_22);
        fso2.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("allStates");
        fiy_12.setName("observedCharacter");
        fsQ2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.c);
        fsQ2.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fsQ fsQ3 = fsQ2;
        fqr fqr2 = (fqr)((fvE)fsQ3).getAppearance();
        fqr2.setElementMap(fyy_02);
        fsQ2.addBasicElement(fqr2);
        fqr2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 5, 0, 5));
        fqr2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqr2.onChildrenAdded();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_02);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        faf_22.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_02);
        far_22.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        fav_12.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_22.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        faf_22.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setAlign(frs_0.b);
        fin_22.setHorizontal(false);
        fso3.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        String string2 = "borderContainer";
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fso4);
        }
        fso4.setExpandable(false);
        fso4.setNonBlocking(false);
        fso4.setStyle("white2");
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_02);
        fip_23.setAlign(frs_0.e);
        fso4.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fso fso5 = fso4;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso4.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_02);
        fqo_02.setInsets(new Insets(4, 4, 4, 4));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso4.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setDisplaySize(new fjf_2(24, 24));
        fsk_02.setExpandable(false);
        fsk_02.setNonBlocking(true);
        fsk_02.setScaled(true);
        fso4.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("texture");
        fir_12.setField("iconUrl");
        fqv2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso6.setStyle("backgroundPopupLight");
        fso4.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("visible");
        fir_13.setField("stackSize");
        fso6.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        fir_13.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fam_1 fam_12 = new fam_1();
        fam_12.onCheckOut();
        fam_12.setElementMap(fyy_02);
        fam_12.setValue("1");
        far_23.addBasicElement(fam_12);
        fam_12.onAttributesInitialized();
        fam_12.onChildrenAdded();
        far_23.onChildrenAdded();
        fir_13.onChildrenAdded();
        fso fso7 = fso6;
        fqj fqj3 = ((fvE)fso7).getAppearance();
        fqj3.setElementMap(fyy_02);
        fso6.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_02);
        fqo_03.setInsets(new Insets(2, 2, 2, 2));
        fqj3.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj3.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.q);
        fid_13.setSize(new fjf_2(-2, -2));
        fid_13.setXOffset(3);
        fid_13.setYOffset(-3);
        fso6.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setEnableAutoZoomShrink(true);
        fsM2.setExpandable(false);
        fsM2.setMaxWidth(22);
        fsM2.setNonBlocking(true);
        fsM2.setStyle("White10Bordered");
        fso6.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("text");
        fir_14.setField("stackSize");
        fsM2.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fsM2.onChildrenAdded();
        fso6.onChildrenAdded();
        fso4.onChildrenAdded();
        fso fso8 = fso.checkOut();
        fso8.setElementMap(fyy_02);
        fso8.setExpandable(false);
        fso8.setStyle("backgroundPopupLight");
        fso3.addBasicElement(fso8);
        fso8.onAttributesInitialized();
        fip_2 fip_24 = new fip_2();
        fip_24.onCheckOut();
        fip_24.setElementMap(fyy_02);
        fip_24.setAlign(frs_0.e);
        fso8.addBasicElement(fip_24);
        fip_24.onAttributesInitialized();
        fip_24.onChildrenAdded();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("visible");
        fir_15.setField("remainingDuration");
        fso8.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_02);
        fir_15.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_02);
        far_24.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_24.onChildrenAdded();
        fir_15.onChildrenAdded();
        fso fso9 = fso8;
        fqj fqj4 = ((fvE)fso9).getAppearance();
        fqj4.setElementMap(fyy_02);
        fso8.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqo_0 fqo_04 = new fqo_0();
        fqo_04.onCheckOut();
        fqo_04.setElementMap(fyy_02);
        fqo_04.setInsets(new Insets(0, 3, 0, 3));
        fqj4.addBasicElement(fqo_04);
        fqo_04.onAttributesInitialized();
        fqo_04.onChildrenAdded();
        fqj4.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setEnableAutoZoomShrink(true);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(22);
        fuk_02.setMultiline(false);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("White10Bordered");
        fso8.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlign(frs_0.e);
        fuk_02.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqh_03.onChildrenAdded();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_02);
        fir_16.setAttribute("text");
        fir_16.setField("remainingDuration");
        fuk_02.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        fir_16.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso8.onChildrenAdded();
        fso3.onChildrenAdded();
        faf_22.onChildrenAdded();
        fsQ2.onChildrenAdded();
        return fsQ2;
    }
}

