/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cSa
 */
public class csa_2
implements fyq {
    private Stack<fyy_0> a = new Stack();
    private fya_0 b;

    @Override
    public fyo a(fya_0 fya_02, fyy_0 fyy_02) {
        this.b = fya_02;
        this.a.push(fyy_02);
        fyy_0 fyy_03 = this.a.peek();
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_03);
        fso2.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_03);
        fid_12.setAlign(frk_0.a);
        fid_12.setXOffset(5);
        fid_12.setYOffset(0);
        fso2.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(true);
        fso2.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_03);
        fso3.setNonBlocking(false);
        fdt_1 fdt_12 = new fdt_1();
        fdt_12.a("wakfu.petDialog:unloadTutorialDialog");
        fso3.setOnClick(fdt_12);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_03);
        fiy_12.setAttribute("visible");
        fiy_12.setName("tutorialMessageView");
        fso3.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_03);
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_03);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_03);
        fso4.setStyle("backgroundPopup");
        fso3.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fso fso5 = fso4;
        fqj fqj2 = ((fvE)fso5).getAppearance();
        fqj2.setElementMap(fyy_03);
        fso4.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqo_0 fqo_02 = new fqo_0();
        fqo_02.onCheckOut();
        fqo_02.setElementMap(fyy_03);
        fqo_02.setInsets(new Insets(10, 10, 15, 10));
        fqj2.addBasicElement(fqo_02);
        fqo_02.onAttributesInitialized();
        fqo_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_03);
        fiy_13.setAttribute("visible");
        fiy_13.setField("style");
        fiy_13.setName("tutorialMessageView");
        fso4.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_03);
        fiy_13.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fab_2 fab_23 = new fab_2();
        fab_23.onCheckOut();
        fab_23.setElementMap(fyy_03);
        far_23.addBasicElement(fab_23);
        fab_23.onAttributesInitialized();
        fab_23.onChildrenAdded();
        far_23.onChildrenAdded();
        fiy_13.onChildrenAdded();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_03);
        fid_13.setAlign(frk_0.a);
        fid_13.setSize(new fjf_2(-2, -2));
        fid_13.setXOffset(15);
        fso4.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_03);
        fsk_02.setExpandable(false);
        fso4.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_03);
        fiy_14.setAttribute("style");
        fiy_14.setField("style");
        fiy_14.setName("tutorialMessageView");
        fsk_02.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        fiy_14.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fso4.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_03);
        fso3.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_03);
        fid_14.setSize(new fjf_2(100.0f, 100.0f));
        fso6.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setHorizontal(false);
        fso6.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fur_0 fur_02 = new fur_0();
        fur_02.onCheckOut();
        fur_02.setElementMap(fyy_03);
        fur_02.setExpandable(false);
        fur_02.setPrefSize(new fjf_2(0, 35));
        fso6.addBasicElement(fur_02);
        fur_02.onAttributesInitialized();
        fiy_1 fiy_15 = fiy_1.checkOut();
        fiy_15.setElementMap(fyy_03);
        fiy_15.setAttribute("visible");
        fiy_15.setField("style");
        fiy_15.setName("tutorialMessageView");
        fur_02.addBasicElement(fiy_15);
        fiy_15.onAttributesInitialized();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_03);
        fiy_15.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fab_2 fab_24 = new fab_2();
        fab_24.onCheckOut();
        fab_24.setElementMap(fyy_03);
        far_24.addBasicElement(fab_24);
        fab_24.onAttributesInitialized();
        fab_24.onChildrenAdded();
        far_24.onChildrenAdded();
        fiy_15.onChildrenAdded();
        fur_02.onChildrenAdded();
        String string = "tutorialMessageContainer";
        fso fso7 = fso.checkOut();
        fso7.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fso7);
        }
        fso7.setPack(true);
        fso7.setStyle("backgroundPopup");
        fso6.addBasicElement(fso7);
        fso7.onAttributesInitialized();
        fso fso8 = fso7;
        fqj fqj3 = ((fvE)fso8).getAppearance();
        fqj3.setElementMap(fyy_03);
        fso7.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(5, 0, 0, 0));
        fqj3.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqo_0 fqo_03 = new fqo_0();
        fqo_03.onCheckOut();
        fqo_03.setElementMap(fyy_03);
        fqo_03.setInsets(new Insets(15, 15, 15, 15));
        fqj3.addBasicElement(fqo_03);
        fqo_03.onAttributesInitialized();
        fqo_03.onChildrenAdded();
        fqj3.onChildrenAdded();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setAlign(frs_0.b);
        fin_24.setHorizontal(false);
        fso7.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_03);
        fsk_03.setExpandable(false);
        fso7.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fiy_1 fiy_16 = fiy_1.checkOut();
        fiy_16.setElementMap(fyy_03);
        fiy_16.setAttribute("visible");
        fiy_16.setField("imageUrl");
        fiy_16.setName("tutorialMessageView");
        fsk_03.addBasicElement(fiy_16);
        fiy_16.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_03);
        fiy_16.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        fab_2 fab_25 = new fab_2();
        fab_25.onCheckOut();
        fab_25.setElementMap(fyy_03);
        far_25.addBasicElement(fab_25);
        fab_25.onAttributesInitialized();
        fab_25.onChildrenAdded();
        far_25.onChildrenAdded();
        fiy_16.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fsk_03.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fiy_1 fiy_17 = fiy_1.checkOut();
        fiy_17.setElementMap(fyy_03);
        fiy_17.setAttribute("texture");
        fiy_17.setField("imageUrl");
        fiy_17.setName("tutorialMessageView");
        fqv2.addBasicElement(fiy_17);
        fiy_17.onAttributesInitialized();
        fiy_17.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_03.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_03);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(200);
        fuk_02.setMinWidth(1);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("SmallBoldBordered12");
        fso7.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_03);
        fip_22.setAlign(frs_0.d);
        fuk_02.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_03);
        fqh_02.setAlignment(frs_0.d);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_03);
        fqg_02.setColor(new fyr_0("questObjectiveColor"));
        fqh_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fiy_1 fiy_18 = fiy_1.checkOut();
        fiy_18.setElementMap(fyy_03);
        fiy_18.setAttribute("text");
        fiy_18.setField("title");
        fiy_18.setName("tutorialMessageView");
        fuk_02.addBasicElement(fiy_18);
        fiy_18.onAttributesInitialized();
        fiy_18.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_03);
        fuk_04.setExpandable(false);
        fuk_04.setMaxWidth(200);
        fuk_04.setMinWidth(1);
        fuk_04.setNonBlocking(true);
        fuk_04.setStyle("SmallBoldBordered");
        fso7.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fip_2 fip_23 = new fip_2();
        fip_23.onCheckOut();
        fip_23.setElementMap(fyy_03);
        fip_23.setAlign(frs_0.d);
        fuk_04.addBasicElement(fip_23);
        fip_23.onAttributesInitialized();
        fip_23.onChildrenAdded();
        fuk_0 fuk_05 = fuk_04;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_05).getAppearance();
        fqh_03.setElementMap(fyy_03);
        fqh_03.setAlignment(frs_0.d);
        fuk_04.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_03);
        fqm_03.setInsets(new Insets(0, 10, 0, 0));
        fqh_03.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqg_0 fqg_03 = fqg_0.checkOut();
        fqg_03.setElementMap(fyy_03);
        fqg_03.setColor(new fyr_0("defaultLightColor"));
        fqh_03.addBasicElement(fqg_03);
        fqg_03.onAttributesInitialized();
        fqg_03.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fiy_1 fiy_19 = fiy_1.checkOut();
        fiy_19.setElementMap(fyy_03);
        fiy_19.setAttribute("text");
        fiy_19.setField("description");
        fiy_19.setName("tutorialMessageView");
        fuk_04.addBasicElement(fiy_19);
        fiy_19.onAttributesInitialized();
        fiy_19.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fso7.onChildrenAdded();
        fso6.onChildrenAdded();
        String string2 = "particleContainer";
        fso fso9 = fso.checkOut();
        fso9.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fso9);
        }
        fso9.setNonBlocking(true);
        fso3.addBasicElement(fso9);
        fso9.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_03);
        fid_15.setAlign(frk_0.i);
        fid_15.setSize(new fjf_2(95.0f, 95.0f));
        fso9.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fso9.onChildrenAdded();
        fso3.onChildrenAdded();
        fso fso10 = fso.checkOut();
        fso10.setElementMap(fyy_03);
        fso10.setExpandable(false);
        fso10.setNonBlocking(false);
        fdt_1 fdt_13 = new fdt_1();
        fdt_13.a("wakfu.petDialog:validOrSetNextMessage");
        fso10.setOnClick(fdt_13);
        fso2.addBasicElement(fso10);
        fso10.onAttributesInitialized();
        fip_2 fip_24 = new fip_2();
        fip_24.onCheckOut();
        fip_24.setElementMap(fyy_03);
        fip_24.setAlign(frs_0.b);
        fso10.addBasicElement(fip_24);
        fip_24.onAttributesInitialized();
        fip_24.onChildrenAdded();
        fiy_1 fiy_110 = fiy_1.checkOut();
        fiy_110.setElementMap(fyy_03);
        fiy_110.setAttribute("visible");
        fiy_110.setName("petBubbleMessage");
        fso10.addBasicElement(fiy_110);
        fiy_110.onAttributesInitialized();
        far_2 far_26 = new far_2();
        far_26.onCheckOut();
        far_26.setElementMap(fyy_03);
        fiy_110.addBasicElement(far_26);
        far_26.onAttributesInitialized();
        fab_2 fab_26 = new fab_2();
        fab_26.onCheckOut();
        fab_26.setElementMap(fyy_03);
        far_26.addBasicElement(fab_26);
        fab_26.onAttributesInitialized();
        fab_26.onChildrenAdded();
        far_26.onChildrenAdded();
        fiy_110.onChildrenAdded();
        fic_1 fic_13 = new fic_1();
        fic_13.onCheckOut();
        fic_13.setAdaptToContentSize(true);
        fso10.addBasicElement(fic_13);
        fic_13.onAttributesInitialized();
        fic_13.onChildrenAdded();
        fso fso11 = fso.checkOut();
        fso11.setElementMap(fyy_03);
        fso11.setExpandable(false);
        fso11.setStyle("petBubble");
        fso10.addBasicElement(fso11);
        fso11.onAttributesInitialized();
        fid_1 fid_16 = new fid_1();
        fid_16.onCheckOut();
        fid_16.setElementMap(fyy_03);
        fid_16.setAlign(frk_0.c);
        fso11.addBasicElement(fid_16);
        fid_16.onAttributesInitialized();
        fid_16.onChildrenAdded();
        fso fso12 = fso11;
        fqj fqj4 = ((fvE)fso12).getAppearance();
        fqj4.setElementMap(fyy_03);
        fso11.addBasicElement(fqj4);
        fqj4.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_03);
        fqm_04.setInsets(new Insets(23, 0, 20, 0));
        fqj4.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqj4.onChildrenAdded();
        String string3 = "text";
        fuk_0 fuk_06 = new fuk_0();
        fuk_06.onCheckOut();
        fuk_06.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fuk_06);
        }
        fuk_06.setMaxWidth(250);
        fuk_06.setMinWidth(10);
        fuk_06.setStyle("DefaultBold14");
        fso11.addBasicElement(fuk_06);
        fuk_06.onAttributesInitialized();
        fiy_1 fiy_111 = fiy_1.checkOut();
        fiy_111.setElementMap(fyy_03);
        fiy_111.setAttribute("text");
        fiy_111.setName("petBubbleMessage");
        fuk_06.addBasicElement(fiy_111);
        fiy_111.onAttributesInitialized();
        fiy_111.onChildrenAdded();
        fuk_06.onChildrenAdded();
        fso11.onChildrenAdded();
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_03);
        fsk_04.setExpandable(false);
        fsk_04.setStyle("petBubble");
        fso10.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fid_1 fid_17 = new fid_1();
        fid_17.onCheckOut();
        fid_17.setElementMap(fyy_03);
        fid_17.setAlign(frk_0.a);
        fid_17.setSize(new fjf_2(-2, -2));
        fid_17.setXOffset(20);
        fsk_04.addBasicElement(fid_17);
        fid_17.onAttributesInitialized();
        fid_17.onChildrenAdded();
        fsk_04.onChildrenAdded();
        fso10.onChildrenAdded();
        String string4 = "fightChallenges";
        fso fso13 = fso.checkOut();
        fso13.setElementMap(fyy_03);
        if (fyy_03 != null && string4 != null) {
            fyy_03.a(string4, fso13);
        }
        fso2.addBasicElement(fso13);
        fso13.onAttributesInitialized();
        fso fso14 = fso13;
        fqj fqj5 = ((fvE)fso14).getAppearance();
        fqj5.setElementMap(fyy_03);
        fso13.addBasicElement(fqj5);
        fqj5.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_03);
        fqm_05.setInsets(new Insets(5, 0, 0, 0));
        fqj5.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqj5.onChildrenAdded();
        String string5 = "fightChallengesList";
        fsQ fsQ2 = new fsQ();
        fsQ2.onCheckOut();
        fsQ2.setElementMap(fyy_03);
        if (fyy_03 != null && string5 != null) {
            fyy_03.a(string5, fsQ2);
        }
        fsQ2.setAutoIdealSize(true);
        fsQ2.setHorizontal(true);
        fsQ2.setIdealSizeMaxRows(1);
        fsQ2.setIdealSizeMinRows(1);
        fsQ2.setCellSize(new fjf_2(53, 48));
        fso13.addBasicElement(fsQ2);
        fsQ2.onAttributesInitialized();
        faf_2 faf_22 = new faf_2();
        faf_22.onCheckOut();
        faf_22.setElementMap(fyy_03);
        fsQ2.addBasicElement(faf_22);
        faf_22.onAttributesInitialized();
        far_2 far_27 = new far_2();
        far_27.onCheckOut();
        far_27.setElementMap(fyy_03);
        faf_22.addBasicElement(far_27);
        far_27.onAttributesInitialized();
        fav_1 fav_12 = new fav_1();
        fav_12.onCheckOut();
        fav_12.setElementMap(fyy_03);
        far_27.addBasicElement(fav_12);
        fav_12.onAttributesInitialized();
        fab_2 fab_27 = new fab_2();
        fab_27.onCheckOut();
        fab_27.setElementMap(fyy_03);
        fav_12.addBasicElement(fab_27);
        fab_27.onAttributesInitialized();
        fab_27.onChildrenAdded();
        fav_12.onChildrenAdded();
        far_27.onChildrenAdded();
        String string6 = "challenge";
        fij_1 fij_12 = new fij_1();
        fij_12.onCheckOut();
        fij_12.setElementMap(fyy_03);
        if (fyy_03 != null && string6 != null) {
            fyy_03.a(string6, fij_12);
        }
        faf_22.addBasicElement(fij_12);
        fij_12.onAttributesInitialized();
        this.a(fij_12);
        fij_12.onChildrenAdded();
        this.a(faf_22);
        faf_22.onChildrenAdded();
        this.a(fsQ2);
        fsQ2.onChildrenAdded();
        this.a(fso13);
        fso13.onChildrenAdded();
        this.b(fso2);
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo a(fij_1 fij_12) {
        fyy_0 fyy_02 = this.a.peek();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("value");
        fij_12.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        return fir_12;
    }

    public fyo a(faf_2 faf_22) {
        fyy_0 fyy_02 = this.a.peek();
        String string = "container";
        fso fso2 = fso.checkOut();
        fso2.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fso2);
        }
        fso2.setNonBlocking(false);
        fde_2 fde_22 = new fde_2();
        fde_22.a("popup(challengePopup)");
        fso2.setOnPopupDisplay(fde_22);
        fdf_2 fdf_22 = new fdf_2();
        fdf_22.a("closePopup");
        fso2.setOnPopupHide(fdf_22);
        faf_22.addBasicElement(fso2);
        fso2.onAttributesInitialized();
        fso fso3 = fso2;
        fqj fqj2 = ((fvE)fso3).getAppearance();
        fqj2.setElementMap(fyy_02);
        fso2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_02);
        fqm_02.setInsets(new Insets(0, 5, 0, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        fqj2.onChildrenAdded();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso2.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        String string2 = "image";
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fsk_02);
        }
        fsk_02.setNonBlocking(true);
        fsk_02.setDisplaySize(new fjf_2(48, 48));
        fso2.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setAlign(frk_0.i);
        fid_12.setSize(new fjf_2(-2, -2));
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fir_1 fir_12 = new fir_1();
        fir_12.onCheckOut();
        fir_12.setElementMap(fyy_02);
        fir_12.setAttribute("texture");
        fir_12.setField("iconUrl");
        fqv2.addBasicElement(fir_12);
        fir_12.onAttributesInitialized();
        fir_12.onChildrenAdded();
        fqv2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        String string3 = "image1Point5";
        fsk_0 fsk_03 = new fsk_0();
        fsk_03.onCheckOut();
        fsk_03.setElementMap(fyy_02);
        if (fyy_02 != null && string3 != null) {
            fyy_02.a(string3, fsk_03);
        }
        fsk_03.setNonBlocking(true);
        fsk_03.setVisible(false);
        fso2.addBasicElement(fsk_03);
        fsk_03.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fid_13.setSize(new fjf_2(-2, -2));
        fsk_03.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsk_03.onChildrenAdded();
        String string4 = "image2";
        fsk_0 fsk_04 = new fsk_0();
        fsk_04.onCheckOut();
        fsk_04.setElementMap(fyy_02);
        if (fyy_02 != null && string4 != null) {
            fyy_02.a(string4, fsk_04);
        }
        fsk_04.setNonBlocking(true);
        fsk_04.setStyle("apply");
        fsk_04.setDisplaySize(new fjf_2(36, 36));
        fso2.addBasicElement(fsk_04);
        fsk_04.onAttributesInitialized();
        fid_1 fid_14 = new fid_1();
        fid_14.onCheckOut();
        fid_14.setElementMap(fyy_02);
        fid_14.setAlign(frk_0.i);
        fid_14.setSize(new fjf_2(-2, -2));
        fid_14.setXOffset(-1);
        fsk_04.addBasicElement(fid_14);
        fid_14.onAttributesInitialized();
        fid_14.onChildrenAdded();
        fir_1 fir_13 = new fir_1();
        fir_13.onCheckOut();
        fir_13.setElementMap(fyy_02);
        fir_13.setAttribute("visible");
        fir_13.setField("isCompleted");
        fsk_04.addBasicElement(fir_13);
        fir_13.onAttributesInitialized();
        fir_13.onChildrenAdded();
        fsk_04.onChildrenAdded();
        String string5 = "image3";
        fsk_0 fsk_05 = new fsk_0();
        fsk_05.onCheckOut();
        fsk_05.setElementMap(fyy_02);
        if (fyy_02 != null && string5 != null) {
            fyy_02.a(string5, fsk_05);
        }
        fsk_05.setNonBlocking(true);
        fsk_05.setStyle("cancel");
        fsk_05.setDisplaySize(new fjf_2(36, 36));
        fso2.addBasicElement(fsk_05);
        fsk_05.onAttributesInitialized();
        fid_1 fid_15 = new fid_1();
        fid_15.onCheckOut();
        fid_15.setElementMap(fyy_02);
        fid_15.setAlign(frk_0.i);
        fid_15.setSize(new fjf_2(-2, -2));
        fid_15.setXOffset(-1);
        fsk_05.addBasicElement(fid_15);
        fid_15.onAttributesInitialized();
        fid_15.onChildrenAdded();
        fir_1 fir_14 = new fir_1();
        fir_14.onCheckOut();
        fir_14.setElementMap(fyy_02);
        fir_14.setAttribute("visible");
        fir_14.setField("isFailed");
        fsk_05.addBasicElement(fir_14);
        fir_14.onAttributesInitialized();
        fir_14.onChildrenAdded();
        fsk_05.onChildrenAdded();
        String string6 = "challengePopup";
        fil_1 fil_12 = new fil_1();
        fil_12.onCheckOut();
        fil_12.setElementMap(fyy_02);
        if (fyy_02 != null && string6 != null) {
            fyy_02.a(string6, fil_12);
        }
        fil_12.setAlign(frs_0.a);
        fil_12.setHotSpotPosition(frs_0.g);
        fil_12.setXOffset(-8);
        fso2.addBasicElement(fil_12);
        fil_12.onAttributesInitialized();
        fso fso4 = fso.checkOut();
        fso4.setElementMap(fyy_02);
        fso4.setStyle("popup");
        fil_12.addBasicElement(fso4);
        fso4.onAttributesInitialized();
        fin_2 fin_22 = fin_2.checkOut();
        fin_22.setHorizontal(false);
        fso4.addBasicElement(fin_22);
        fin_22.onAttributesInitialized();
        fin_22.onChildrenAdded();
        fso fso5 = fso.checkOut();
        fso5.setElementMap(fyy_02);
        fso5.setExpandable(false);
        fso5.setPrefSize(new fjf_2(0, 0));
        fso4.addBasicElement(fso5);
        fso5.onAttributesInitialized();
        fin_2 fin_23 = fin_2.checkOut();
        fin_23.setAlign(frs_0.d);
        fso5.addBasicElement(fin_23);
        fin_23.onAttributesInitialized();
        fin_23.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.d);
        fso5.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fuk_0 fuk_02 = new fuk_0();
        fuk_02.onCheckOut();
        fuk_02.setElementMap(fyy_02);
        fuk_02.setExpandable(false);
        fuk_02.setMaxWidth(318);
        fuk_02.setMinWidth(1);
        fuk_02.setNonBlocking(true);
        fuk_02.setStyle("SmallBoldBordered12");
        fso5.addBasicElement(fuk_02);
        fuk_02.onAttributesInitialized();
        fuk_0 fuk_03 = fuk_02;
        fqh_0 fqh_02 = (fqh_0)((fvE)fuk_03).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlign(frs_0.d);
        fuk_02.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqm_0 fqm_03 = fqm_0.checkOut();
        fqm_03.setElementMap(fyy_02);
        fqm_03.setInsets(new Insets(0, 0, 0, 0));
        fqh_02.addBasicElement(fqm_03);
        fqm_03.onAttributesInitialized();
        fqm_03.onChildrenAdded();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_02);
        fqg_02.setColor(new azf_2(1.0f, 1.0f, 1.0f, 1.0f));
        fqh_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqh_02.onChildrenAdded();
        fir_1 fir_15 = new fir_1();
        fir_15.onCheckOut();
        fir_15.setElementMap(fyy_02);
        fir_15.setAttribute("text");
        fir_15.setField("name");
        fuk_02.addBasicElement(fir_15);
        fir_15.onAttributesInitialized();
        fir_15.onChildrenAdded();
        fuk_02.onChildrenAdded();
        fso5.onChildrenAdded();
        fuk_0 fuk_04 = new fuk_0();
        fuk_04.onCheckOut();
        fuk_04.setElementMap(fyy_02);
        fuk_04.setExpandable(false);
        fuk_04.setMaxWidth(318);
        fuk_04.setMinWidth(1);
        fuk_04.setNonBlocking(true);
        fuk_04.setStyle("SmallBoldBordered");
        fso4.addBasicElement(fuk_04);
        fuk_04.onAttributesInitialized();
        fir_1 fir_16 = new fir_1();
        fir_16.onCheckOut();
        fir_16.setElementMap(fyy_02);
        fir_16.setAttribute("text");
        fir_16.setField("goals");
        fuk_04.addBasicElement(fir_16);
        fir_16.onAttributesInitialized();
        fir_16.onChildrenAdded();
        fuk_0 fuk_05 = fuk_04;
        fqh_0 fqh_03 = (fqh_0)((fvE)fuk_05).getAppearance();
        fqh_03.setElementMap(fyy_02);
        fqh_03.setAlign(frs_0.d);
        fuk_04.addBasicElement(fqh_03);
        fqh_03.onAttributesInitialized();
        fqg_0 fqg_03 = fqg_0.checkOut();
        fqg_03.setElementMap(fyy_02);
        fqg_03.setColor(new fyr_0("questObjectiveColor"));
        fqh_03.addBasicElement(fqg_03);
        fqg_03.onAttributesInitialized();
        fqg_03.onChildrenAdded();
        fqh_03.onChildrenAdded();
        fuk_04.onChildrenAdded();
        fso fso6 = fso.checkOut();
        fso6.setElementMap(fyy_02);
        fso4.addBasicElement(fso6);
        fso6.onAttributesInitialized();
        fin_2 fin_24 = fin_2.checkOut();
        fin_24.setHorizontal(false);
        fso6.addBasicElement(fin_24);
        fin_24.onAttributesInitialized();
        fin_24.onChildrenAdded();
        fir_1 fir_17 = new fir_1();
        fir_17.onCheckOut();
        fir_17.setElementMap(fyy_02);
        fir_17.setAttribute("visible");
        fir_17.setField("additionalInfos");
        fso6.addBasicElement(fir_17);
        fir_17.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        fir_17.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        fab_2 fab_22 = new fab_2();
        fab_22.onCheckOut();
        fab_22.setElementMap(fyy_02);
        far_22.addBasicElement(fab_22);
        fab_22.onAttributesInitialized();
        fab_22.onChildrenAdded();
        far_22.onChildrenAdded();
        fir_17.onChildrenAdded();
        fuk_0 fuk_06 = new fuk_0();
        fuk_06.onCheckOut();
        fuk_06.setElementMap(fyy_02);
        fuk_06.setExpandable(false);
        fuk_06.setMaxWidth(318);
        fuk_06.setMinWidth(1);
        fuk_06.setNonBlocking(true);
        fuk_06.setStyle("SmallBoldBordered");
        String string7 = "%fightChallenge.additionalInfos%";
        string7 = string7.replace("%fightChallenge.additionalInfos%", fpm_0.b().c("fightChallenge.additionalInfos"));
        fuk_06.c(string7);
        fso6.addBasicElement(fuk_06);
        fuk_06.onAttributesInitialized();
        fuk_0 fuk_07 = fuk_06;
        fqh_0 fqh_04 = (fqh_0)((fvE)fuk_07).getAppearance();
        fqh_04.setElementMap(fyy_02);
        fqh_04.setAlign(frs_0.d);
        fuk_06.addBasicElement(fqh_04);
        fqh_04.onAttributesInitialized();
        fqm_0 fqm_04 = fqm_0.checkOut();
        fqm_04.setElementMap(fyy_02);
        fqm_04.setInsets(new Insets(5, 0, 0, 0));
        fqh_04.addBasicElement(fqm_04);
        fqm_04.onAttributesInitialized();
        fqm_04.onChildrenAdded();
        fqg_0 fqg_04 = fqg_0.checkOut();
        fqg_04.setElementMap(fyy_02);
        fqg_04.setColor(new azf_2(1.0f, 1.0f, 1.0f, 1.0f));
        fqh_04.addBasicElement(fqg_04);
        fqg_04.onAttributesInitialized();
        fqg_04.onChildrenAdded();
        fqh_04.onChildrenAdded();
        fuk_06.onChildrenAdded();
        fuk_0 fuk_08 = new fuk_0();
        fuk_08.onCheckOut();
        fuk_08.setElementMap(fyy_02);
        fuk_08.setExpandable(false);
        fuk_08.setMaxWidth(318);
        fuk_08.setMinWidth(1);
        fuk_08.setNonBlocking(true);
        fuk_08.setStyle("SmallBoldBordered");
        fso6.addBasicElement(fuk_08);
        fuk_08.onAttributesInitialized();
        fuk_0 fuk_09 = fuk_08;
        fqh_0 fqh_05 = (fqh_0)((fvE)fuk_09).getAppearance();
        fqh_05.setElementMap(fyy_02);
        fqh_05.setAlign(frs_0.d);
        fuk_08.addBasicElement(fqh_05);
        fqh_05.onAttributesInitialized();
        fqm_0 fqm_05 = fqm_0.checkOut();
        fqm_05.setElementMap(fyy_02);
        fqm_05.setInsets(new Insets(2, 3, 0, 0));
        fqh_05.addBasicElement(fqm_05);
        fqm_05.onAttributesInitialized();
        fqm_05.onChildrenAdded();
        fqg_0 fqg_05 = fqg_0.checkOut();
        fqg_05.setElementMap(fyy_02);
        fqg_05.setColor(new fyr_0("questObjectiveColor"));
        fqh_05.addBasicElement(fqg_05);
        fqg_05.onAttributesInitialized();
        fqg_05.onChildrenAdded();
        fqh_05.onChildrenAdded();
        fir_1 fir_18 = new fir_1();
        fir_18.onCheckOut();
        fir_18.setElementMap(fyy_02);
        fir_18.setAttribute("text");
        fir_18.setField("additionalInfos");
        fuk_08.addBasicElement(fir_18);
        fir_18.onAttributesInitialized();
        fir_18.onChildrenAdded();
        fuk_08.onChildrenAdded();
        fso6.onChildrenAdded();
        fuk_0 fuk_010 = new fuk_0();
        fuk_010.onCheckOut();
        fuk_010.setElementMap(fyy_02);
        fuk_010.setExpandable(false);
        fuk_010.setMaxWidth(318);
        fuk_010.setMinWidth(1);
        fuk_010.setNonBlocking(true);
        fuk_010.setStyle("SmallBoldBordered");
        String string8 = "%fightChallenge.rewards%";
        string8 = string8.replace("%fightChallenge.rewards%", fpm_0.b().c("fightChallenge.rewards"));
        fuk_010.c(string8);
        fso4.addBasicElement(fuk_010);
        fuk_010.onAttributesInitialized();
        fuk_0 fuk_011 = fuk_010;
        fqh_0 fqh_06 = (fqh_0)((fvE)fuk_011).getAppearance();
        fqh_06.setElementMap(fyy_02);
        fqh_06.setAlign(frs_0.d);
        fuk_010.addBasicElement(fqh_06);
        fqh_06.onAttributesInitialized();
        fqm_0 fqm_06 = fqm_0.checkOut();
        fqm_06.setElementMap(fyy_02);
        fqm_06.setInsets(new Insets(5, 0, 0, 0));
        fqh_06.addBasicElement(fqm_06);
        fqm_06.onAttributesInitialized();
        fqm_06.onChildrenAdded();
        fqg_0 fqg_06 = fqg_0.checkOut();
        fqg_06.setElementMap(fyy_02);
        fqg_06.setColor(new azf_2(1.0f, 1.0f, 1.0f, 1.0f));
        fqh_06.addBasicElement(fqg_06);
        fqg_06.onAttributesInitialized();
        fqg_06.onChildrenAdded();
        fqh_06.onChildrenAdded();
        fuk_010.onChildrenAdded();
        fuk_0 fuk_012 = new fuk_0();
        fuk_012.onCheckOut();
        fuk_012.setElementMap(fyy_02);
        fuk_012.setExpandable(false);
        fuk_012.setMaxWidth(318);
        fuk_012.setMinWidth(1);
        fuk_012.setNonBlocking(true);
        fuk_012.setStyle("SmallBoldBordered");
        fso4.addBasicElement(fuk_012);
        fuk_012.onAttributesInitialized();
        fuk_0 fuk_013 = fuk_012;
        fqh_0 fqh_07 = (fqh_0)((fvE)fuk_013).getAppearance();
        fqh_07.setElementMap(fyy_02);
        fqh_07.setAlign(frs_0.d);
        fuk_012.addBasicElement(fqh_07);
        fqh_07.onAttributesInitialized();
        fqm_0 fqm_07 = fqm_0.checkOut();
        fqm_07.setElementMap(fyy_02);
        fqm_07.setInsets(new Insets(2, 3, 0, 0));
        fqh_07.addBasicElement(fqm_07);
        fqm_07.onAttributesInitialized();
        fqm_07.onChildrenAdded();
        fqg_0 fqg_07 = fqg_0.checkOut();
        fqg_07.setElementMap(fyy_02);
        fqg_07.setColor(new fyr_0("questObjectiveColor"));
        fqh_07.addBasicElement(fqg_07);
        fqg_07.onAttributesInitialized();
        fqg_07.onChildrenAdded();
        fqh_07.onChildrenAdded();
        fir_1 fir_19 = new fir_1();
        fir_19.onCheckOut();
        fir_19.setElementMap(fyy_02);
        fir_19.setAttribute("text");
        fir_19.setField("rewards");
        fuk_012.addBasicElement(fir_19);
        fir_19.onAttributesInitialized();
        fir_19.onChildrenAdded();
        fuk_012.onChildrenAdded();
        fso4.onChildrenAdded();
        fil_12.onChildrenAdded();
        fso2.onChildrenAdded();
        return fso2;
    }

    public fyo a(fsQ fsQ2) {
        fyy_0 fyy_02 = this.a.peek();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("content");
        fiy_12.setField("fightChallenge");
        fiy_12.setName("followedAchievements");
        fsQ2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        fiy_12.onChildrenAdded();
        return fiy_12;
    }

    public fyo a(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.b);
        fso2.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        return fip_22;
    }

    public fyo b(fso fso2) {
        fyy_0 fyy_02 = this.a.peek();
        fso fso3 = fso.checkOut();
        fso3.setElementMap(fyy_02);
        fso3.setVisible(false);
        fso2.addBasicElement(fso3);
        fso3.onAttributesInitialized();
        fic_1 fic_12 = new fic_1();
        fic_12.onCheckOut();
        fic_12.setAdaptToContentSize(true);
        fso3.addBasicElement(fic_12);
        fic_12.onAttributesInitialized();
        fic_12.onChildrenAdded();
        fsk_0 fsk_02 = new fsk_0();
        fsk_02.onCheckOut();
        fsk_02.setElementMap(fyy_02);
        fsk_02.setNonBlocking(true);
        fsk_02.setStyle("controlCenterTimer");
        fso3.addBasicElement(fsk_02);
        fsk_02.onAttributesInitialized();
        fid_1 fid_12 = new fid_1();
        fid_12.onCheckOut();
        fid_12.setElementMap(fyy_02);
        fid_12.setSize(new fjf_2(100.0f, 100.0f));
        fsk_02.addBasicElement(fid_12);
        fid_12.onAttributesInitialized();
        fid_12.onChildrenAdded();
        fsk_0 fsk_03 = fsk_02;
        fqp fqp2 = (fqp)((fvE)fsk_03).getAppearance();
        fqp2.setElementMap(fyy_02);
        fsk_02.addBasicElement(fqp2);
        fqp2.onAttributesInitialized();
        fiy_1 fiy_12 = fiy_1.checkOut();
        fiy_12.setElementMap(fyy_02);
        fiy_12.setAttribute("modulationColor");
        fiy_12.setLocal(true);
        fiy_12.setName("countdownState");
        fqp2.addBasicElement(fiy_12);
        fiy_12.onAttributesInitialized();
        far_2 far_22 = new far_2();
        far_22.onCheckOut();
        far_22.setElementMap(fyy_02);
        far_22.setElseValue("1,1,1");
        fiy_12.addBasicElement(far_22);
        far_22.onAttributesInitialized();
        far_2 far_23 = new far_2();
        far_23.onCheckOut();
        far_23.setElementMap(fyy_02);
        far_23.setValue("1,0.9,0.6");
        far_22.addBasicElement(far_23);
        far_23.onAttributesInitialized();
        fat_2 fat_22 = new fat_2();
        fat_22.onCheckOut();
        fat_22.setElementMap(fyy_02);
        fat_22.setValue("1");
        far_23.addBasicElement(fat_22);
        fat_22.onAttributesInitialized();
        fat_22.onChildrenAdded();
        far_23.onChildrenAdded();
        far_2 far_24 = new far_2();
        far_24.onCheckOut();
        far_24.setElementMap(fyy_02);
        far_24.setValue("1,0.6,0.6");
        far_22.addBasicElement(far_24);
        far_24.onAttributesInitialized();
        fat_2 fat_23 = new fat_2();
        fat_23.onCheckOut();
        fat_23.setElementMap(fyy_02);
        fat_23.setValue("2");
        far_24.addBasicElement(fat_23);
        fat_23.onAttributesInitialized();
        fat_23.onChildrenAdded();
        far_24.onChildrenAdded();
        far_22.onChildrenAdded();
        fiy_12.onChildrenAdded();
        fqp2.onChildrenAdded();
        fsk_02.onChildrenAdded();
        fsM fsM2 = new fsM();
        fsM2.onCheckOut();
        fsM2.setElementMap(fyy_02);
        fsM2.setNonBlocking(true);
        fsM2.setPrefSize(new fjf_2(80, 0));
        fsM2.setStyle("BigTitle");
        fso3.addBasicElement(fsM2);
        fsM2.onAttributesInitialized();
        fid_1 fid_13 = new fid_1();
        fid_13.onCheckOut();
        fid_13.setElementMap(fyy_02);
        fid_13.setAlign(frk_0.i);
        fsM2.addBasicElement(fid_13);
        fid_13.onAttributesInitialized();
        fid_13.onChildrenAdded();
        fsM fsM3 = fsM2;
        fqh_0 fqh_02 = (fqh_0)((fvE)fsM3).getAppearance();
        fqh_02.setElementMap(fyy_02);
        fqh_02.setAlignment(frs_0.e);
        fsM2.addBasicElement(fqh_02);
        fqh_02.onAttributesInitialized();
        fqh_02.onChildrenAdded();
        fiy_1 fiy_13 = fiy_1.checkOut();
        fiy_13.setElementMap(fyy_02);
        fiy_13.setAttribute("text");
        fiy_13.setLocal(true);
        fiy_13.setName("countdownText");
        fsM2.addBasicElement(fiy_13);
        fiy_13.onAttributesInitialized();
        fiy_13.onChildrenAdded();
        fsM2.onChildrenAdded();
        fip_2 fip_22 = new fip_2();
        fip_22.onCheckOut();
        fip_22.setElementMap(fyy_02);
        fip_22.setAlign(frs_0.b);
        fso3.addBasicElement(fip_22);
        fip_22.onAttributesInitialized();
        fip_22.onChildrenAdded();
        fiy_1 fiy_14 = fiy_1.checkOut();
        fiy_14.setElementMap(fyy_02);
        fiy_14.setAttribute("visible");
        fiy_14.setLocal(true);
        fiy_14.setName("countdownValue");
        fso3.addBasicElement(fiy_14);
        fiy_14.onAttributesInitialized();
        far_2 far_25 = new far_2();
        far_25.onCheckOut();
        far_25.setElementMap(fyy_02);
        fiy_14.addBasicElement(far_25);
        far_25.onAttributesInitialized();
        faa_2 faa_22 = new faa_2();
        faa_22.onCheckOut();
        faa_22.setElementMap(fyy_02);
        faa_22.setValue("0");
        far_25.addBasicElement(faa_22);
        faa_22.onAttributesInitialized();
        faa_22.onChildrenAdded();
        far_25.onChildrenAdded();
        fiy_14.onChildrenAdded();
        fso3.onChildrenAdded();
        return fso3;
    }
}

