/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from dsM
 */
public class dsm_1
implements fyn_0 {
    private fyw_0 a;
    private Stack<fyy_0> b = new Stack();

    @Override
    public void a(fyy_0 fyy_02, fyw_0 fyw_02, fvE fvE2) {
        this.a = fyw_02;
        this.b.push(fyy_02);
        fyy_0 fyy_03 = this.b.peek();
        fvE fvE3 = fvE2;
        fqj_0 fqj_02 = (fqj_0)fvE3.getAppearance();
        fqj_02.setElementMap(fyy_03);
        fqj_02.setState("default");
        fvE2.addBasicElement(fqj_02);
        fqj_02.onAttributesInitialized();
        String string = "blueCheckBoxDefaultBackground";
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fby_22);
        }
        fby_22.setScaled(true);
        fqj_02.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fqv2.setHeight(1);
        fqv2.setPosition(frk_0.i);
        fqv2.setTexture(this.a.c("themeDefault"));
        fqv2.setWidth(1);
        fqv2.setX(574);
        fqv2.setY(853);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fby_22.onChildrenAdded();
        String string2 = "blueCheckBoxDefaultBorder";
        fbc_1 fbc_12 = new fbc_1();
        fbc_12.onCheckOut();
        fbc_12.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fbc_12);
        }
        fqj_02.addBasicElement(fbc_12);
        fbc_12.onAttributesInitialized();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_03);
        fqv3.setHeight(11);
        fqv3.setPosition(frk_0.a);
        fqv3.setTexture(this.a.c("themeDefault"));
        fqv3.setWidth(5);
        fqv3.setX(566);
        fqv3.setY(841);
        fbc_12.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_03);
        fqv4.setHeight(11);
        fqv4.setPosition(frk_0.c);
        fqv4.setTexture(this.a.c("themeDefault"));
        fqv4.setWidth(1);
        fqv4.setX(574);
        fqv4.setY(841);
        fbc_12.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_03);
        fqv5.setHeight(11);
        fqv5.setPosition(frk_0.e);
        fqv5.setTexture(this.a.c("themeDefault"));
        fqv5.setWidth(5);
        fqv5.setX(578);
        fqv5.setY(841);
        fbc_12.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_03);
        fqv6.setHeight(1);
        fqv6.setPosition(frk_0.j);
        fqv6.setTexture(this.a.c("themeDefault"));
        fqv6.setWidth(5);
        fqv6.setX(578);
        fqv6.setY(853);
        fbc_12.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_03);
        fqv7.setHeight(14);
        fqv7.setPosition(frk_0.q);
        fqv7.setTexture(this.a.c("themeDefault"));
        fqv7.setWidth(5);
        fqv7.setX(578);
        fqv7.setY(855);
        fbc_12.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_03);
        fqv8.setHeight(14);
        fqv8.setPosition(frk_0.o);
        fqv8.setTexture(this.a.c("themeDefault"));
        fqv8.setWidth(1);
        fqv8.setX(574);
        fqv8.setY(855);
        fbc_12.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_03);
        fqv9.setHeight(14);
        fqv9.setPosition(frk_0.m);
        fqv9.setTexture(this.a.c("themeDefault"));
        fqv9.setWidth(5);
        fqv9.setX(566);
        fqv9.setY(855);
        fbc_12.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_03);
        fqv10.setHeight(1);
        fqv10.setPosition(frk_0.h);
        fqv10.setTexture(this.a.c("themeDefault"));
        fqv10.setWidth(5);
        fqv10.setX(566);
        fqv10.setY(853);
        fbc_12.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fbc_12.onChildrenAdded();
        fqj_02.onChildrenAdded();
        fvE fvE4 = fvE2;
        fqj_0 fqj_03 = (fqj_0)fvE4.getAppearance();
        fqj_03.setElementMap(fyy_03);
        fqj_03.setState("mouseHover");
        fvE2.addBasicElement(fqj_03);
        fqj_03.onAttributesInitialized();
        String string3 = "blueCheckBoxOverBackground";
        fby_2 fby_23 = fby_2.checkOut();
        fby_23.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fby_23);
        }
        fby_23.setScaled(true);
        fqj_03.addBasicElement(fby_23);
        fby_23.onAttributesInitialized();
        fqv fqv11 = fqv.checkOut();
        fqv11.setElementMap(fyy_03);
        fqv11.setHeight(1);
        fqv11.setPosition(frk_0.i);
        fqv11.setTexture(this.a.c("themeOver"));
        fqv11.setWidth(1);
        fqv11.setX(574);
        fqv11.setY(853);
        fby_23.addBasicElement(fqv11);
        fqv11.onAttributesInitialized();
        fqv11.onChildrenAdded();
        fby_23.onChildrenAdded();
        String string4 = "blueCheckBoxOverBorder";
        fbc_1 fbc_13 = new fbc_1();
        fbc_13.onCheckOut();
        fbc_13.setElementMap(fyy_03);
        if (fyy_03 != null && string4 != null) {
            fyy_03.a(string4, fbc_13);
        }
        fqj_03.addBasicElement(fbc_13);
        fbc_13.onAttributesInitialized();
        fqv fqv12 = fqv.checkOut();
        fqv12.setElementMap(fyy_03);
        fqv12.setHeight(11);
        fqv12.setPosition(frk_0.a);
        fqv12.setTexture(this.a.c("themeOver"));
        fqv12.setWidth(5);
        fqv12.setX(566);
        fqv12.setY(841);
        fbc_13.addBasicElement(fqv12);
        fqv12.onAttributesInitialized();
        fqv12.onChildrenAdded();
        fqv fqv13 = fqv.checkOut();
        fqv13.setElementMap(fyy_03);
        fqv13.setHeight(11);
        fqv13.setPosition(frk_0.c);
        fqv13.setTexture(this.a.c("themeOver"));
        fqv13.setWidth(1);
        fqv13.setX(574);
        fqv13.setY(841);
        fbc_13.addBasicElement(fqv13);
        fqv13.onAttributesInitialized();
        fqv13.onChildrenAdded();
        fqv fqv14 = fqv.checkOut();
        fqv14.setElementMap(fyy_03);
        fqv14.setHeight(11);
        fqv14.setPosition(frk_0.e);
        fqv14.setTexture(this.a.c("themeOver"));
        fqv14.setWidth(5);
        fqv14.setX(578);
        fqv14.setY(841);
        fbc_13.addBasicElement(fqv14);
        fqv14.onAttributesInitialized();
        fqv14.onChildrenAdded();
        fqv fqv15 = fqv.checkOut();
        fqv15.setElementMap(fyy_03);
        fqv15.setHeight(1);
        fqv15.setPosition(frk_0.j);
        fqv15.setTexture(this.a.c("themeOver"));
        fqv15.setWidth(5);
        fqv15.setX(578);
        fqv15.setY(853);
        fbc_13.addBasicElement(fqv15);
        fqv15.onAttributesInitialized();
        fqv15.onChildrenAdded();
        fqv fqv16 = fqv.checkOut();
        fqv16.setElementMap(fyy_03);
        fqv16.setHeight(14);
        fqv16.setPosition(frk_0.q);
        fqv16.setTexture(this.a.c("themeOver"));
        fqv16.setWidth(5);
        fqv16.setX(578);
        fqv16.setY(855);
        fbc_13.addBasicElement(fqv16);
        fqv16.onAttributesInitialized();
        fqv16.onChildrenAdded();
        fqv fqv17 = fqv.checkOut();
        fqv17.setElementMap(fyy_03);
        fqv17.setHeight(14);
        fqv17.setPosition(frk_0.o);
        fqv17.setTexture(this.a.c("themeOver"));
        fqv17.setWidth(1);
        fqv17.setX(574);
        fqv17.setY(855);
        fbc_13.addBasicElement(fqv17);
        fqv17.onAttributesInitialized();
        fqv17.onChildrenAdded();
        fqv fqv18 = fqv.checkOut();
        fqv18.setElementMap(fyy_03);
        fqv18.setHeight(14);
        fqv18.setPosition(frk_0.m);
        fqv18.setTexture(this.a.c("themeOver"));
        fqv18.setWidth(5);
        fqv18.setX(566);
        fqv18.setY(855);
        fbc_13.addBasicElement(fqv18);
        fqv18.onAttributesInitialized();
        fqv18.onChildrenAdded();
        fqv fqv19 = fqv.checkOut();
        fqv19.setElementMap(fyy_03);
        fqv19.setHeight(1);
        fqv19.setPosition(frk_0.h);
        fqv19.setTexture(this.a.c("themeOver"));
        fqv19.setWidth(5);
        fqv19.setX(566);
        fqv19.setY(853);
        fbc_13.addBasicElement(fqv19);
        fqv19.onAttributesInitialized();
        fqv19.onChildrenAdded();
        fbc_13.onChildrenAdded();
        fqj_03.onChildrenAdded();
        fvE fvE5 = fvE2;
        fqj_0 fqj_04 = (fqj_0)fvE5.getAppearance();
        fqj_04.setElementMap(fyy_03);
        fqj_04.setState("pressed");
        fvE2.addBasicElement(fqj_04);
        fqj_04.onAttributesInitialized();
        String string5 = "blueCheckBoxPressedBackground";
        fby_2 fby_24 = fby_2.checkOut();
        fby_24.setElementMap(fyy_03);
        if (fyy_03 != null && string5 != null) {
            fyy_03.a(string5, fby_24);
        }
        fby_24.setScaled(true);
        fqj_04.addBasicElement(fby_24);
        fby_24.onAttributesInitialized();
        fqv fqv20 = fqv.checkOut();
        fqv20.setElementMap(fyy_03);
        fqv20.setHeight(1);
        fqv20.setPosition(frk_0.i);
        fqv20.setTexture(this.a.c("themePressed"));
        fqv20.setWidth(1);
        fqv20.setX(574);
        fqv20.setY(853);
        fby_24.addBasicElement(fqv20);
        fqv20.onAttributesInitialized();
        fqv20.onChildrenAdded();
        fby_24.onChildrenAdded();
        String string6 = "blueCheckBoxPressedBorder";
        fbc_1 fbc_14 = new fbc_1();
        fbc_14.onCheckOut();
        fbc_14.setElementMap(fyy_03);
        if (fyy_03 != null && string6 != null) {
            fyy_03.a(string6, fbc_14);
        }
        fqj_04.addBasicElement(fbc_14);
        fbc_14.onAttributesInitialized();
        fqv fqv21 = fqv.checkOut();
        fqv21.setElementMap(fyy_03);
        fqv21.setHeight(11);
        fqv21.setPosition(frk_0.a);
        fqv21.setTexture(this.a.c("themePressed"));
        fqv21.setWidth(5);
        fqv21.setX(566);
        fqv21.setY(841);
        fbc_14.addBasicElement(fqv21);
        fqv21.onAttributesInitialized();
        fqv21.onChildrenAdded();
        fqv fqv22 = fqv.checkOut();
        fqv22.setElementMap(fyy_03);
        fqv22.setHeight(11);
        fqv22.setPosition(frk_0.c);
        fqv22.setTexture(this.a.c("themePressed"));
        fqv22.setWidth(1);
        fqv22.setX(574);
        fqv22.setY(841);
        fbc_14.addBasicElement(fqv22);
        fqv22.onAttributesInitialized();
        fqv22.onChildrenAdded();
        fqv fqv23 = fqv.checkOut();
        fqv23.setElementMap(fyy_03);
        fqv23.setHeight(11);
        fqv23.setPosition(frk_0.e);
        fqv23.setTexture(this.a.c("themePressed"));
        fqv23.setWidth(5);
        fqv23.setX(578);
        fqv23.setY(841);
        fbc_14.addBasicElement(fqv23);
        fqv23.onAttributesInitialized();
        fqv23.onChildrenAdded();
        fqv fqv24 = fqv.checkOut();
        fqv24.setElementMap(fyy_03);
        fqv24.setHeight(1);
        fqv24.setPosition(frk_0.j);
        fqv24.setTexture(this.a.c("themePressed"));
        fqv24.setWidth(5);
        fqv24.setX(578);
        fqv24.setY(853);
        fbc_14.addBasicElement(fqv24);
        fqv24.onAttributesInitialized();
        fqv24.onChildrenAdded();
        fqv fqv25 = fqv.checkOut();
        fqv25.setElementMap(fyy_03);
        fqv25.setHeight(14);
        fqv25.setPosition(frk_0.q);
        fqv25.setTexture(this.a.c("themePressed"));
        fqv25.setWidth(5);
        fqv25.setX(578);
        fqv25.setY(855);
        fbc_14.addBasicElement(fqv25);
        fqv25.onAttributesInitialized();
        fqv25.onChildrenAdded();
        fqv fqv26 = fqv.checkOut();
        fqv26.setElementMap(fyy_03);
        fqv26.setHeight(14);
        fqv26.setPosition(frk_0.o);
        fqv26.setTexture(this.a.c("themePressed"));
        fqv26.setWidth(1);
        fqv26.setX(574);
        fqv26.setY(855);
        fbc_14.addBasicElement(fqv26);
        fqv26.onAttributesInitialized();
        fqv26.onChildrenAdded();
        fqv fqv27 = fqv.checkOut();
        fqv27.setElementMap(fyy_03);
        fqv27.setHeight(14);
        fqv27.setPosition(frk_0.m);
        fqv27.setTexture(this.a.c("themePressed"));
        fqv27.setWidth(5);
        fqv27.setX(566);
        fqv27.setY(855);
        fbc_14.addBasicElement(fqv27);
        fqv27.onAttributesInitialized();
        fqv27.onChildrenAdded();
        fqv fqv28 = fqv.checkOut();
        fqv28.setElementMap(fyy_03);
        fqv28.setHeight(1);
        fqv28.setPosition(frk_0.h);
        fqv28.setTexture(this.a.c("themePressed"));
        fqv28.setWidth(5);
        fqv28.setX(566);
        fqv28.setY(853);
        fbc_14.addBasicElement(fqv28);
        fqv28.onAttributesInitialized();
        fqv28.onChildrenAdded();
        fbc_14.onChildrenAdded();
        fqj_04.onChildrenAdded();
        fvE fvE6 = fvE2;
        fqj_0 fqj_05 = (fqj_0)fvE6.getAppearance();
        fqj_05.setElementMap(fyy_03);
        fqj_05.setState("disabled");
        fvE2.addBasicElement(fqj_05);
        fqj_05.onAttributesInitialized();
        String string7 = "blueCheckBoxDisabledBackground";
        fby_2 fby_25 = fby_2.checkOut();
        fby_25.setElementMap(fyy_03);
        if (fyy_03 != null && string7 != null) {
            fyy_03.a(string7, fby_25);
        }
        fby_25.setScaled(true);
        fqj_05.addBasicElement(fby_25);
        fby_25.onAttributesInitialized();
        fqv fqv29 = fqv.checkOut();
        fqv29.setElementMap(fyy_03);
        fqv29.setHeight(1);
        fqv29.setPosition(frk_0.i);
        fqv29.setTexture(this.a.c("themeDisabled"));
        fqv29.setWidth(1);
        fqv29.setX(574);
        fqv29.setY(853);
        fby_25.addBasicElement(fqv29);
        fqv29.onAttributesInitialized();
        fqv29.onChildrenAdded();
        fby_25.onChildrenAdded();
        String string8 = "blueCheckBoxDisabledBorder";
        fbc_1 fbc_15 = new fbc_1();
        fbc_15.onCheckOut();
        fbc_15.setElementMap(fyy_03);
        if (fyy_03 != null && string8 != null) {
            fyy_03.a(string8, fbc_15);
        }
        fqj_05.addBasicElement(fbc_15);
        fbc_15.onAttributesInitialized();
        fqv fqv30 = fqv.checkOut();
        fqv30.setElementMap(fyy_03);
        fqv30.setHeight(11);
        fqv30.setPosition(frk_0.a);
        fqv30.setTexture(this.a.c("themeDisabled"));
        fqv30.setWidth(5);
        fqv30.setX(566);
        fqv30.setY(841);
        fbc_15.addBasicElement(fqv30);
        fqv30.onAttributesInitialized();
        fqv30.onChildrenAdded();
        fqv fqv31 = fqv.checkOut();
        fqv31.setElementMap(fyy_03);
        fqv31.setHeight(11);
        fqv31.setPosition(frk_0.c);
        fqv31.setTexture(this.a.c("themeDisabled"));
        fqv31.setWidth(1);
        fqv31.setX(574);
        fqv31.setY(841);
        fbc_15.addBasicElement(fqv31);
        fqv31.onAttributesInitialized();
        fqv31.onChildrenAdded();
        fqv fqv32 = fqv.checkOut();
        fqv32.setElementMap(fyy_03);
        fqv32.setHeight(11);
        fqv32.setPosition(frk_0.e);
        fqv32.setTexture(this.a.c("themeDisabled"));
        fqv32.setWidth(5);
        fqv32.setX(578);
        fqv32.setY(841);
        fbc_15.addBasicElement(fqv32);
        fqv32.onAttributesInitialized();
        fqv32.onChildrenAdded();
        fqv fqv33 = fqv.checkOut();
        fqv33.setElementMap(fyy_03);
        fqv33.setHeight(1);
        fqv33.setPosition(frk_0.j);
        fqv33.setTexture(this.a.c("themeDisabled"));
        fqv33.setWidth(5);
        fqv33.setX(578);
        fqv33.setY(853);
        fbc_15.addBasicElement(fqv33);
        fqv33.onAttributesInitialized();
        fqv33.onChildrenAdded();
        fqv fqv34 = fqv.checkOut();
        fqv34.setElementMap(fyy_03);
        fqv34.setHeight(14);
        fqv34.setPosition(frk_0.q);
        fqv34.setTexture(this.a.c("themeDisabled"));
        fqv34.setWidth(5);
        fqv34.setX(578);
        fqv34.setY(855);
        fbc_15.addBasicElement(fqv34);
        fqv34.onAttributesInitialized();
        fqv34.onChildrenAdded();
        fqv fqv35 = fqv.checkOut();
        fqv35.setElementMap(fyy_03);
        fqv35.setHeight(14);
        fqv35.setPosition(frk_0.o);
        fqv35.setTexture(this.a.c("themeDisabled"));
        fqv35.setWidth(1);
        fqv35.setX(574);
        fqv35.setY(855);
        fbc_15.addBasicElement(fqv35);
        fqv35.onAttributesInitialized();
        fqv35.onChildrenAdded();
        fqv fqv36 = fqv.checkOut();
        fqv36.setElementMap(fyy_03);
        fqv36.setHeight(14);
        fqv36.setPosition(frk_0.m);
        fqv36.setTexture(this.a.c("themeDisabled"));
        fqv36.setWidth(5);
        fqv36.setX(566);
        fqv36.setY(855);
        fbc_15.addBasicElement(fqv36);
        fqv36.onAttributesInitialized();
        fqv36.onChildrenAdded();
        fqv fqv37 = fqv.checkOut();
        fqv37.setElementMap(fyy_03);
        fqv37.setHeight(1);
        fqv37.setPosition(frk_0.h);
        fqv37.setTexture(this.a.c("themeDisabled"));
        fqv37.setWidth(5);
        fqv37.setX(566);
        fqv37.setY(853);
        fbc_15.addBasicElement(fqv37);
        fqv37.onAttributesInitialized();
        fqv37.onChildrenAdded();
        fbc_15.onChildrenAdded();
        fqj_05.onChildrenAdded();
        fvE fvE7 = fvE2;
        fqj_0 fqj_06 = (fqj_0)fvE7.getAppearance();
        fqj_06.setElementMap(fyy_03);
        fqj_06.setState("selected");
        fvE2.addBasicElement(fqj_06);
        fqj_06.onAttributesInitialized();
        this.a(fqj_06);
        this.b(fqj_06);
        fqj_06.onChildrenAdded();
        this.c(fvE2);
        this.d(fvE2);
        this.e(fvE2);
    }

    public fyo a(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        String string = "blueCheckBoxDefaultSelectedBackground";
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fby_22);
        }
        fby_22.setScaled(true);
        fyo2.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(1);
        fqv2.setPosition(frk_0.i);
        fqv2.setTexture(this.a.c("themeDefaultSelected"));
        fqv2.setWidth(1);
        fqv2.setX(574);
        fqv2.setY(853);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fby_22.onChildrenAdded();
        return fby_22;
    }

    public fyo b(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        String string = "blueCheckBoxDefaultSelectedBorder";
        fbc_1 fbc_12 = new fbc_1();
        fbc_12.onCheckOut();
        fbc_12.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fbc_12);
        }
        fyo2.addBasicElement(fbc_12);
        fbc_12.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(11);
        fqv2.setPosition(frk_0.a);
        fqv2.setTexture(this.a.c("themeDefaultSelected"));
        fqv2.setWidth(5);
        fqv2.setX(566);
        fqv2.setY(841);
        fbc_12.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fqv3.setHeight(11);
        fqv3.setPosition(frk_0.c);
        fqv3.setTexture(this.a.c("themeDefaultSelected"));
        fqv3.setWidth(1);
        fqv3.setX(574);
        fqv3.setY(841);
        fbc_12.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_02);
        fqv4.setHeight(11);
        fqv4.setPosition(frk_0.e);
        fqv4.setTexture(this.a.c("themeDefaultSelected"));
        fqv4.setWidth(5);
        fqv4.setX(578);
        fqv4.setY(841);
        fbc_12.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_02);
        fqv5.setHeight(1);
        fqv5.setPosition(frk_0.j);
        fqv5.setTexture(this.a.c("themeDefaultSelected"));
        fqv5.setWidth(5);
        fqv5.setX(578);
        fqv5.setY(853);
        fbc_12.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_02);
        fqv6.setHeight(14);
        fqv6.setPosition(frk_0.q);
        fqv6.setTexture(this.a.c("themeDefaultSelected"));
        fqv6.setWidth(5);
        fqv6.setX(578);
        fqv6.setY(855);
        fbc_12.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_02);
        fqv7.setHeight(14);
        fqv7.setPosition(frk_0.o);
        fqv7.setTexture(this.a.c("themeDefaultSelected"));
        fqv7.setWidth(1);
        fqv7.setX(574);
        fqv7.setY(855);
        fbc_12.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_02);
        fqv8.setHeight(14);
        fqv8.setPosition(frk_0.m);
        fqv8.setTexture(this.a.c("themeDefaultSelected"));
        fqv8.setWidth(5);
        fqv8.setX(566);
        fqv8.setY(855);
        fbc_12.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_02);
        fqv9.setHeight(1);
        fqv9.setPosition(frk_0.h);
        fqv9.setTexture(this.a.c("themeDefaultSelected"));
        fqv9.setWidth(5);
        fqv9.setX(566);
        fqv9.setY(853);
        fbc_12.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fbc_12.onChildrenAdded();
        return fbc_12;
    }

    public fyo c(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fvE fvE2 = (fvE)fyo2;
        fqj_0 fqj_02 = (fqj_0)fvE2.getAppearance();
        fqj_02.setElementMap(fyy_02);
        fqj_02.setState("mouseHoverSelected");
        fyo2.addBasicElement(fqj_02);
        fqj_02.onAttributesInitialized();
        String string = "blueCheckBoxOverSelectedBackground";
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fby_22);
        }
        fby_22.setScaled(true);
        fqj_02.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(1);
        fqv2.setPosition(frk_0.i);
        fqv2.setTexture(this.a.c("themeOverSelected"));
        fqv2.setWidth(1);
        fqv2.setX(574);
        fqv2.setY(853);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fby_22.onChildrenAdded();
        String string2 = "blueCheckBoxOverSelectedBorder";
        fbc_1 fbc_12 = new fbc_1();
        fbc_12.onCheckOut();
        fbc_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fbc_12);
        }
        fqj_02.addBasicElement(fbc_12);
        fbc_12.onAttributesInitialized();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fqv3.setHeight(11);
        fqv3.setPosition(frk_0.a);
        fqv3.setTexture(this.a.c("themeOverSelected"));
        fqv3.setWidth(5);
        fqv3.setX(566);
        fqv3.setY(841);
        fbc_12.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_02);
        fqv4.setHeight(11);
        fqv4.setPosition(frk_0.c);
        fqv4.setTexture(this.a.c("themeOverSelected"));
        fqv4.setWidth(1);
        fqv4.setX(574);
        fqv4.setY(841);
        fbc_12.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_02);
        fqv5.setHeight(11);
        fqv5.setPosition(frk_0.e);
        fqv5.setTexture(this.a.c("themeOverSelected"));
        fqv5.setWidth(5);
        fqv5.setX(578);
        fqv5.setY(841);
        fbc_12.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_02);
        fqv6.setHeight(1);
        fqv6.setPosition(frk_0.j);
        fqv6.setTexture(this.a.c("themeOverSelected"));
        fqv6.setWidth(5);
        fqv6.setX(578);
        fqv6.setY(853);
        fbc_12.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_02);
        fqv7.setHeight(14);
        fqv7.setPosition(frk_0.q);
        fqv7.setTexture(this.a.c("themeOverSelected"));
        fqv7.setWidth(5);
        fqv7.setX(578);
        fqv7.setY(855);
        fbc_12.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_02);
        fqv8.setHeight(14);
        fqv8.setPosition(frk_0.o);
        fqv8.setTexture(this.a.c("themeOverSelected"));
        fqv8.setWidth(1);
        fqv8.setX(574);
        fqv8.setY(855);
        fbc_12.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_02);
        fqv9.setHeight(14);
        fqv9.setPosition(frk_0.m);
        fqv9.setTexture(this.a.c("themeOverSelected"));
        fqv9.setWidth(5);
        fqv9.setX(566);
        fqv9.setY(855);
        fbc_12.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_02);
        fqv10.setHeight(1);
        fqv10.setPosition(frk_0.h);
        fqv10.setTexture(this.a.c("themeOverSelected"));
        fqv10.setWidth(5);
        fqv10.setX(566);
        fqv10.setY(853);
        fbc_12.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fbc_12.onChildrenAdded();
        fqj_02.onChildrenAdded();
        return fqj_02;
    }

    public fyo d(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fvE fvE2 = (fvE)fyo2;
        fqj_0 fqj_02 = (fqj_0)fvE2.getAppearance();
        fqj_02.setElementMap(fyy_02);
        fqj_02.setState("pressedSelected");
        fyo2.addBasicElement(fqj_02);
        fqj_02.onAttributesInitialized();
        String string = "blueCheckBoxPressedSelectedBackground";
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fby_22);
        }
        fby_22.setScaled(true);
        fqj_02.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(1);
        fqv2.setPosition(frk_0.i);
        fqv2.setTexture(this.a.c("themePressedSelected"));
        fqv2.setWidth(1);
        fqv2.setX(574);
        fqv2.setY(853);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fby_22.onChildrenAdded();
        String string2 = "blueCheckBoxPressedSelectedBorder";
        fbc_1 fbc_12 = new fbc_1();
        fbc_12.onCheckOut();
        fbc_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fbc_12);
        }
        fqj_02.addBasicElement(fbc_12);
        fbc_12.onAttributesInitialized();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fqv3.setHeight(11);
        fqv3.setPosition(frk_0.a);
        fqv3.setTexture(this.a.c("themePressedSelected"));
        fqv3.setWidth(5);
        fqv3.setX(566);
        fqv3.setY(841);
        fbc_12.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_02);
        fqv4.setHeight(11);
        fqv4.setPosition(frk_0.c);
        fqv4.setTexture(this.a.c("themePressedSelected"));
        fqv4.setWidth(1);
        fqv4.setX(574);
        fqv4.setY(841);
        fbc_12.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_02);
        fqv5.setHeight(11);
        fqv5.setPosition(frk_0.e);
        fqv5.setTexture(this.a.c("themePressedSelected"));
        fqv5.setWidth(5);
        fqv5.setX(578);
        fqv5.setY(841);
        fbc_12.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_02);
        fqv6.setHeight(1);
        fqv6.setPosition(frk_0.j);
        fqv6.setTexture(this.a.c("themePressedSelected"));
        fqv6.setWidth(5);
        fqv6.setX(578);
        fqv6.setY(853);
        fbc_12.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_02);
        fqv7.setHeight(14);
        fqv7.setPosition(frk_0.q);
        fqv7.setTexture(this.a.c("themePressedSelected"));
        fqv7.setWidth(5);
        fqv7.setX(578);
        fqv7.setY(855);
        fbc_12.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_02);
        fqv8.setHeight(14);
        fqv8.setPosition(frk_0.o);
        fqv8.setTexture(this.a.c("themePressedSelected"));
        fqv8.setWidth(1);
        fqv8.setX(574);
        fqv8.setY(855);
        fbc_12.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_02);
        fqv9.setHeight(14);
        fqv9.setPosition(frk_0.m);
        fqv9.setTexture(this.a.c("themePressedSelected"));
        fqv9.setWidth(5);
        fqv9.setX(566);
        fqv9.setY(855);
        fbc_12.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_02);
        fqv10.setHeight(1);
        fqv10.setPosition(frk_0.h);
        fqv10.setTexture(this.a.c("themePressedSelected"));
        fqv10.setWidth(5);
        fqv10.setX(566);
        fqv10.setY(853);
        fbc_12.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fbc_12.onChildrenAdded();
        fqj_02.onChildrenAdded();
        return fqj_02;
    }

    public fyo e(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fvE fvE2 = (fvE)fyo2;
        fqj_0 fqj_02 = (fqj_0)fvE2.getAppearance();
        fqj_02.setElementMap(fyy_02);
        fqj_02.setState("disabledSelected");
        fyo2.addBasicElement(fqj_02);
        fqj_02.onAttributesInitialized();
        String string = "blueCheckBoxDisabledSelectedBackground";
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fby_22);
        }
        fby_22.setScaled(true);
        fqj_02.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(1);
        fqv2.setPosition(frk_0.i);
        fqv2.setTexture(this.a.c("themeDisabledSelected"));
        fqv2.setWidth(1);
        fqv2.setX(574);
        fqv2.setY(853);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fby_22.onChildrenAdded();
        String string2 = "blueCheckBoxDisabledSelectedBorder";
        fbc_1 fbc_12 = new fbc_1();
        fbc_12.onCheckOut();
        fbc_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fbc_12);
        }
        fqj_02.addBasicElement(fbc_12);
        fbc_12.onAttributesInitialized();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fqv3.setHeight(11);
        fqv3.setPosition(frk_0.a);
        fqv3.setTexture(this.a.c("themeDisabledSelected"));
        fqv3.setWidth(5);
        fqv3.setX(566);
        fqv3.setY(841);
        fbc_12.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_02);
        fqv4.setHeight(11);
        fqv4.setPosition(frk_0.c);
        fqv4.setTexture(this.a.c("themeDisabledSelected"));
        fqv4.setWidth(1);
        fqv4.setX(574);
        fqv4.setY(841);
        fbc_12.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_02);
        fqv5.setHeight(11);
        fqv5.setPosition(frk_0.e);
        fqv5.setTexture(this.a.c("themeDisabledSelected"));
        fqv5.setWidth(5);
        fqv5.setX(578);
        fqv5.setY(841);
        fbc_12.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_02);
        fqv6.setHeight(1);
        fqv6.setPosition(frk_0.j);
        fqv6.setTexture(this.a.c("themeDisabledSelected"));
        fqv6.setWidth(5);
        fqv6.setX(578);
        fqv6.setY(853);
        fbc_12.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_02);
        fqv7.setHeight(14);
        fqv7.setPosition(frk_0.q);
        fqv7.setTexture(this.a.c("themeDisabledSelected"));
        fqv7.setWidth(5);
        fqv7.setX(578);
        fqv7.setY(855);
        fbc_12.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_02);
        fqv8.setHeight(14);
        fqv8.setPosition(frk_0.o);
        fqv8.setTexture(this.a.c("themeDisabledSelected"));
        fqv8.setWidth(1);
        fqv8.setX(574);
        fqv8.setY(855);
        fbc_12.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_02);
        fqv9.setHeight(14);
        fqv9.setPosition(frk_0.m);
        fqv9.setTexture(this.a.c("themeDisabledSelected"));
        fqv9.setWidth(5);
        fqv9.setX(566);
        fqv9.setY(855);
        fbc_12.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_02);
        fqv10.setHeight(1);
        fqv10.setPosition(frk_0.h);
        fqv10.setTexture(this.a.c("themeDisabledSelected"));
        fqv10.setWidth(5);
        fqv10.setX(566);
        fqv10.setY(853);
        fbc_12.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fbc_12.onChildrenAdded();
        fqj_02.onChildrenAdded();
        return fqj_02;
    }
}

