/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from dtj
 */
public class dtj_1
implements fyn_0 {
    private fyw_0 a;
    private Stack<fyy_0> b = new Stack();

    @Override
    public void a(fyy_0 fyy_02, fyw_0 fyw_02, fvE fvE2) {
        this.a = fyw_02;
        this.b.push(fyy_02);
        fyy_0 fyy_03 = this.b.peek();
        fvE fvE3 = fvE2;
        fqj_0 fqj_02 = (fqj_0)fvE3.getAppearance();
        fqj_02.setElementMap(fyy_03);
        fqj_02.setState("default");
        fvE2.addBasicElement(fqj_02);
        fqj_02.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fqv2.setHeight(35);
        fqv2.setPosition(frk_0.i);
        fqv2.setTexture(this.a.c("themeSimple2"));
        fqv2.setWidth(22);
        fqv2.setX(1671);
        fqv2.setY(307);
        fqj_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_03);
        fqg_02.setColor(new azf_2(1.0f, 1.0f, 1.0f, 0.5f));
        fqg_02.setDecoratorSwitch(true);
        fqg_02.setName("modulation");
        fqj_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        fqj_02.onChildrenAdded();
        fvE fvE4 = fvE2;
        fqj_0 fqj_03 = (fqj_0)fvE4.getAppearance();
        fqj_03.setElementMap(fyy_03);
        fqj_03.setState("mouseHover");
        fvE2.addBasicElement(fqj_03);
        fqj_03.onAttributesInitialized();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_03);
        fqv3.setHeight(35);
        fqv3.setPosition(frk_0.i);
        fqv3.setTexture(this.a.c("themeSimple2"));
        fqv3.setWidth(22);
        fqv3.setX(1671);
        fqv3.setY(305);
        fqj_03.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqg_0 fqg_03 = fqg_0.checkOut();
        fqg_03.setElementMap(fyy_03);
        fqg_03.setColor(new azf_2(1.0f, 1.0f, 1.0f, 0.5f));
        fqg_03.setDecoratorSwitch(true);
        fqg_03.setName("modulation");
        fqj_03.addBasicElement(fqg_03);
        fqg_03.onAttributesInitialized();
        fqg_03.onChildrenAdded();
        fqj_03.onChildrenAdded();
        fvE fvE5 = fvE2;
        fqj_0 fqj_04 = (fqj_0)fvE5.getAppearance();
        fqj_04.setElementMap(fyy_03);
        fqj_04.setState("disabled");
        fvE2.addBasicElement(fqj_04);
        fqj_04.onAttributesInitialized();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_03);
        fqv4.setHeight(35);
        fqv4.setPosition(frk_0.i);
        fqv4.setTexture(this.a.c("themeSimple2"));
        fqv4.setWidth(22);
        fqv4.setX(1671);
        fqv4.setY(307);
        fqj_04.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqg_0 fqg_04 = fqg_0.checkOut();
        fqg_04.setElementMap(fyy_03);
        fqg_04.setColor(new azf_2(0.7f, 0.7f, 0.7f, 0.5f));
        fqg_04.setDecoratorSwitch(true);
        fqg_04.setName("modulation");
        fqj_04.addBasicElement(fqg_04);
        fqg_04.onAttributesInitialized();
        fqg_04.onChildrenAdded();
        fqj_04.onChildrenAdded();
        fvE fvE6 = fvE2;
        fqj_0 fqj_05 = (fqj_0)fvE6.getAppearance();
        fqj_05.setElementMap(fyy_03);
        fqj_05.setState("pressed");
        fvE2.addBasicElement(fqj_05);
        fqj_05.onAttributesInitialized();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_03);
        fqv5.setHeight(35);
        fqv5.setPosition(frk_0.i);
        fqv5.setTexture(this.a.c("themeSimple2"));
        fqv5.setWidth(22);
        fqv5.setX(1671);
        fqv5.setY(303);
        fqj_05.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqg_0 fqg_05 = fqg_0.checkOut();
        fqg_05.setElementMap(fyy_03);
        fqg_05.setColor(new azf_2(1.0f, 1.0f, 1.0f, 0.5f));
        fqg_05.setDecoratorSwitch(true);
        fqg_05.setName("modulation");
        fqj_05.addBasicElement(fqg_05);
        fqg_05.onAttributesInitialized();
        fqg_05.onChildrenAdded();
        fqj_05.onChildrenAdded();
        fvE fvE7 = fvE2;
        fqj_0 fqj_06 = (fqj_0)fvE7.getAppearance();
        fqj_06.setElementMap(fyy_03);
        fqj_06.setState("selected");
        fvE2.addBasicElement(fqj_06);
        fqj_06.onAttributesInitialized();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_03);
        fqv6.setHeight(35);
        fqv6.setPosition(frk_0.i);
        fqv6.setTexture(this.a.c("themeSimple2"));
        fqv6.setWidth(22);
        fqv6.setX(1671);
        fqv6.setY(307);
        fqj_06.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqg_0 fqg_06 = fqg_0.checkOut();
        fqg_06.setElementMap(fyy_03);
        fqg_06.setColor(new azf_2(1.0f, 1.0f, 1.0f, 1.0f));
        fqg_06.setDecoratorSwitch(true);
        fqg_06.setName("modulation");
        fqj_06.addBasicElement(fqg_06);
        fqg_06.onAttributesInitialized();
        fqg_06.onChildrenAdded();
        fqj_06.onChildrenAdded();
        fvE fvE8 = fvE2;
        fqj_0 fqj_07 = (fqj_0)fvE8.getAppearance();
        fqj_07.setElementMap(fyy_03);
        fqj_07.setState("mouseHoverSelected");
        fvE2.addBasicElement(fqj_07);
        fqj_07.onAttributesInitialized();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_03);
        fqv7.setHeight(35);
        fqv7.setPosition(frk_0.i);
        fqv7.setTexture(this.a.c("themeSimple2"));
        fqv7.setWidth(22);
        fqv7.setX(1671);
        fqv7.setY(305);
        fqj_07.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqg_0 fqg_07 = fqg_0.checkOut();
        fqg_07.setElementMap(fyy_03);
        fqg_07.setColor(new azf_2(1.0f, 1.0f, 1.0f, 1.0f));
        fqg_07.setDecoratorSwitch(true);
        fqg_07.setName("modulation");
        fqj_07.addBasicElement(fqg_07);
        fqg_07.onAttributesInitialized();
        fqg_07.onChildrenAdded();
        fqj_07.onChildrenAdded();
        fvE fvE9 = fvE2;
        fqj_0 fqj_08 = (fqj_0)fvE9.getAppearance();
        fqj_08.setElementMap(fyy_03);
        fqj_08.setState("disabledSelected");
        fvE2.addBasicElement(fqj_08);
        fqj_08.onAttributesInitialized();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_03);
        fqv8.setHeight(35);
        fqv8.setPosition(frk_0.i);
        fqv8.setTexture(this.a.c("themeSimple2"));
        fqv8.setWidth(22);
        fqv8.setX(1671);
        fqv8.setY(307);
        fqj_08.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqg_0 fqg_08 = fqg_0.checkOut();
        fqg_08.setElementMap(fyy_03);
        fqg_08.setColor(new azf_2(0.7f, 0.7f, 0.7f, 1.0f));
        fqg_08.setDecoratorSwitch(true);
        fqg_08.setName("modulation");
        fqj_08.addBasicElement(fqg_08);
        fqg_08.onAttributesInitialized();
        fqg_08.onChildrenAdded();
        fqj_08.onChildrenAdded();
        fvE fvE10 = fvE2;
        fqj_0 fqj_09 = (fqj_0)fvE10.getAppearance();
        fqj_09.setElementMap(fyy_03);
        fqj_09.setState("pressedSelected");
        fvE2.addBasicElement(fqj_09);
        fqj_09.onAttributesInitialized();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_03);
        fqv9.setHeight(35);
        fqv9.setPosition(frk_0.i);
        fqv9.setTexture(this.a.c("themeSimple2"));
        fqv9.setWidth(22);
        fqv9.setX(1671);
        fqv9.setY(303);
        fqj_09.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqg_0 fqg_09 = fqg_0.checkOut();
        fqg_09.setElementMap(fyy_03);
        fqg_09.setColor(new azf_2(1.0f, 1.0f, 1.0f, 1.0f));
        fqg_09.setDecoratorSwitch(true);
        fqg_09.setName("modulation");
        fqj_09.addBasicElement(fqg_09);
        fqg_09.onAttributesInitialized();
        fqg_09.onChildrenAdded();
        fqj_09.onChildrenAdded();
    }
}

