/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from dUV
 */
public class duv_1
implements fyn_0 {
    private fyw_0 a;
    private Stack<fyy_0> b = new Stack();

    @Override
    public void a(fyy_0 fyy_02, fyw_0 fyw_02, fvE fvE2) {
        this.a = fyw_02;
        this.b.push(fyy_02);
        fyy_0 fyy_03 = this.b.peek();
        fvE fvE3 = fvE2;
        fqr fqr2 = (fqr)fvE3.getAppearance();
        fqr2.setElementMap(fyy_03);
        fvE2.addBasicElement(fqr2);
        fqr2.onAttributesInitialized();
        fvE fvE4 = fqr2.getParentOfType(fvE.class);
        fvE fvE5 = fvE4.getWidgetByThemeElementName("verticalScrollbar", false);
        if (fvE5 != null) {
            fqv fqv2;
            fyg_0 fyg_02;
            fyb_0 fyb_02;
            fyg_0 fyg_03;
            fyb_0 fyb_03;
            fyb_0 fyb_04;
            fyb_0 fyb_05;
            fyb_0 fyb_06;
            fyb_0 fyb_07;
            fyg_0 fyg_04;
            fyb_0 fyb_08;
            fyb_0 fyb_09;
            fyb_0 fyb_010;
            fvE fvE6;
            fyb_0 fyb_011;
            fvE fvE7 = fvE5;
            fqj fqj2 = fvE7.getAppearance();
            fqj2.setElementMap(fyy_03);
            fvE5.addBasicElement(fqj2);
            fqj2.onAttributesInitialized();
            fvE fvE8 = fqj2.getParentOfType(fvE.class);
            fvE fvE9 = fvE8.getWidgetByThemeElementName("verticalIncreaseButton", false);
            if (fvE9 != null) {
                fyb_011 = new fqo_0();
                ((fql_0)fyb_011).onCheckOut();
                fyb_011.setElementMap(fyy_03);
                ((fql_0)fyb_011).setInsets(new Insets(1, 1, 1, 1));
                fvE9.addBasicElement(fyb_011);
                fyb_011.onAttributesInitialized();
                fyb_011.onChildrenAdded();
                fvE6 = fvE9;
                fyb_010 = (fqd_0)fvE6.getAppearance();
                fyb_010.setElementMap(fyy_03);
                ((fqj)fyb_010).setState("default");
                fvE9.addBasicElement(fyb_010);
                fyb_010.onAttributesInitialized();
                fyb_09 = fqv.checkOut();
                fyb_09.setElementMap(fyy_03);
                ((fqv)fyb_09).setHeight(6);
                ((fqv)fyb_09).setPosition(frk_0.i);
                ((fqv)fyb_09).setTexture(this.a.c("txScrollbarButton"));
                ((fqv)fyb_09).setWidth(8);
                ((fqv)fyb_09).setX(0);
                ((fqv)fyb_09).setY(0);
                fyb_010.addBasicElement(fyb_09);
                fyb_09.onAttributesInitialized();
                fyb_09.onChildrenAdded();
                fyb_010.onChildrenAdded();
                fyb_08 = fvE9;
                fyg_04 = (fqd_0)((fvE)fyb_08).getAppearance();
                fyg_04.setElementMap(fyy_03);
                ((fqj)fyg_04).setState("mouseHover");
                fvE9.addBasicElement(fyg_04);
                fyg_04.onAttributesInitialized();
                fyb_07 = fqv.checkOut();
                fyb_07.setElementMap(fyy_03);
                ((fqv)fyb_07).setHeight(6);
                ((fqv)fyb_07).setPosition(frk_0.i);
                ((fqv)fyb_07).setTexture(this.a.c("txScrollbarButton"));
                ((fqv)fyb_07).setWidth(8);
                ((fqv)fyb_07).setX(0);
                ((fqv)fyb_07).setY(8);
                fyg_04.addBasicElement(fyb_07);
                fyb_07.onAttributesInitialized();
                fyb_07.onChildrenAdded();
                fyg_04.onChildrenAdded();
                fyb_06 = fvE9;
                fyb_05 = (fqd_0)((fvE)fyb_06).getAppearance();
                fyb_05.setElementMap(fyy_03);
                ((fqj)fyb_05).setState("pressed");
                fvE9.addBasicElement(fyb_05);
                fyb_05.onAttributesInitialized();
                fyb_04 = fqv.checkOut();
                fyb_04.setElementMap(fyy_03);
                ((fqv)fyb_04).setHeight(6);
                ((fqv)fyb_04).setPosition(frk_0.i);
                ((fqv)fyb_04).setTexture(this.a.c("txScrollbarButton"));
                ((fqv)fyb_04).setWidth(8);
                ((fqv)fyb_04).setX(0);
                ((fqv)fyb_04).setY(16);
                fyb_05.addBasicElement(fyb_04);
                fyb_04.onAttributesInitialized();
                fyb_04.onChildrenAdded();
                fyb_05.onChildrenAdded();
                fyb_03 = fvE9;
                fyg_03 = (fqd_0)((fvE)fyb_03).getAppearance();
                fyg_03.setElementMap(fyy_03);
                ((fqj)fyg_03).setState("disabled");
                fvE9.addBasicElement(fyg_03);
                fyg_03.onAttributesInitialized();
                fyb_02 = fqv.checkOut();
                fyb_02.setElementMap(fyy_03);
                ((fqv)fyb_02).setHeight(6);
                ((fqv)fyb_02).setPosition(frk_0.i);
                ((fqv)fyb_02).setTexture(this.a.c("txScrollbarButton"));
                ((fqv)fyb_02).setWidth(8);
                ((fqv)fyb_02).setX(0);
                ((fqv)fyb_02).setY(24);
                fyg_03.addBasicElement(fyb_02);
                fyb_02.onAttributesInitialized();
                fyb_02.onChildrenAdded();
                fyg_03.onChildrenAdded();
            }
            if ((fvE6 = ((fvE)(fyb_011 = fqj2.getParentOfType(fvE.class))).getWidgetByThemeElementName("verticalDecreaseButton", false)) != null) {
                fyb_010 = new fqo_0();
                ((fql_0)fyb_010).onCheckOut();
                fyb_010.setElementMap(fyy_03);
                ((fql_0)fyb_010).setInsets(new Insets(1, 1, 1, 1));
                fvE6.addBasicElement(fyb_010);
                fyb_010.onAttributesInitialized();
                fyb_010.onChildrenAdded();
                fyb_09 = fvE6;
                fyb_08 = (fqd_0)((fvE)fyb_09).getAppearance();
                fyb_08.setElementMap(fyy_03);
                ((fqj)fyb_08).setState("default");
                fvE6.addBasicElement(fyb_08);
                fyb_08.onAttributesInitialized();
                fyg_04 = fqv.checkOut();
                fyg_04.setElementMap(fyy_03);
                ((fqv)fyg_04).setFlipVerticaly(true);
                ((fqv)fyg_04).setHeight(6);
                ((fqv)fyg_04).setPosition(frk_0.i);
                ((fqv)fyg_04).setTexture(this.a.c("txScrollbarButton"));
                ((fqv)fyg_04).setWidth(8);
                ((fqv)fyg_04).setX(0);
                ((fqv)fyg_04).setY(0);
                fyb_08.addBasicElement(fyg_04);
                fyg_04.onAttributesInitialized();
                fyg_04.onChildrenAdded();
                fyb_08.onChildrenAdded();
                fyb_07 = fvE6;
                fyb_06 = (fqd_0)((fvE)fyb_07).getAppearance();
                fyb_06.setElementMap(fyy_03);
                ((fqj)fyb_06).setState("mouseHover");
                fvE6.addBasicElement(fyb_06);
                fyb_06.onAttributesInitialized();
                fyb_05 = fqv.checkOut();
                fyb_05.setElementMap(fyy_03);
                ((fqv)fyb_05).setFlipVerticaly(true);
                ((fqv)fyb_05).setHeight(6);
                ((fqv)fyb_05).setPosition(frk_0.i);
                ((fqv)fyb_05).setTexture(this.a.c("txScrollbarButton"));
                ((fqv)fyb_05).setWidth(8);
                ((fqv)fyb_05).setX(0);
                ((fqv)fyb_05).setY(8);
                fyb_06.addBasicElement(fyb_05);
                fyb_05.onAttributesInitialized();
                fyb_05.onChildrenAdded();
                fyb_06.onChildrenAdded();
                fyb_04 = fvE6;
                fyb_03 = (fqd_0)((fvE)fyb_04).getAppearance();
                fyb_03.setElementMap(fyy_03);
                ((fqj)fyb_03).setState("pressed");
                fvE6.addBasicElement(fyb_03);
                fyb_03.onAttributesInitialized();
                fyg_03 = fqv.checkOut();
                fyg_03.setElementMap(fyy_03);
                ((fqv)fyg_03).setFlipVerticaly(true);
                ((fqv)fyg_03).setHeight(6);
                ((fqv)fyg_03).setPosition(frk_0.i);
                ((fqv)fyg_03).setTexture(this.a.c("txScrollbarButton"));
                ((fqv)fyg_03).setWidth(8);
                ((fqv)fyg_03).setX(0);
                ((fqv)fyg_03).setY(16);
                fyb_03.addBasicElement(fyg_03);
                fyg_03.onAttributesInitialized();
                fyg_03.onChildrenAdded();
                fyb_03.onChildrenAdded();
                fyb_02 = fvE6;
                fyg_02 = (fqd_0)((fvE)fyb_02).getAppearance();
                fyg_02.setElementMap(fyy_03);
                ((fqj)fyg_02).setState("disabled");
                fvE6.addBasicElement(fyg_02);
                fyg_02.onAttributesInitialized();
                fqv2 = fqv.checkOut();
                fqv2.setElementMap(fyy_03);
                fqv2.setFlipVerticaly(true);
                fqv2.setHeight(6);
                fqv2.setPosition(frk_0.i);
                fqv2.setTexture(this.a.c("txScrollbarButton"));
                fqv2.setWidth(8);
                fqv2.setX(0);
                fqv2.setY(24);
                fyg_02.addBasicElement(fqv2);
                fqv2.onAttributesInitialized();
                fqv2.onChildrenAdded();
                fyg_02.onChildrenAdded();
            }
            if ((fyb_09 = ((fvE)(fyb_010 = fqj2.getParentOfType(fvE.class))).getWidgetByThemeElementName("verticalSlider", false)) != null) {
                fyb_08 = fyb_09;
                fyg_04 = ((fvE)fyb_08).getAppearance();
                fyg_04.setElementMap(fyy_03);
                fyb_09.addBasicElement(fyg_04);
                fyg_04.onAttributesInitialized();
                fyb_07 = fyg_04.getParentOfType(fvE.class);
                fyb_06 = ((fvE)fyb_07).getWidgetByThemeElementName("verticalButton", false);
                if (fyb_06 != null) {
                    fyb_05 = fyb_06;
                    fyb_04 = (fqd_0)((fvE)fyb_05).getAppearance();
                    fyb_04.setElementMap(fyy_03);
                    ((fqj)fyb_04).setState("default");
                    fyb_06.addBasicElement(fyb_04);
                    fyb_04.onAttributesInitialized();
                    fyb_03 = fby_2.checkOut();
                    fyb_03.setElementMap(fyy_03);
                    ((fbk_1)fyb_03).setEnabled(true);
                    ((fby_2)fyb_03).setScaled(true);
                    fyb_04.addBasicElement(fyb_03);
                    fyb_03.onAttributesInitialized();
                    fyg_03 = fqv.checkOut();
                    fyg_03.setElementMap(fyy_03);
                    ((fqv)fyg_03).setHeight(4);
                    ((fqv)fyg_03).setPosition(frk_0.a);
                    ((fqv)fyg_03).setTexture(this.a.c("txScrollbarSlider"));
                    ((fqv)fyg_03).setWidth(4);
                    ((fqv)fyg_03).setX(0);
                    ((fqv)fyg_03).setY(0);
                    fyb_03.addBasicElement(fyg_03);
                    fyg_03.onAttributesInitialized();
                    fyg_03.onChildrenAdded();
                    fyb_02 = fqv.checkOut();
                    fyb_02.setElementMap(fyy_03);
                    ((fqv)fyb_02).setHeight(1);
                    ((fqv)fyb_02).setPosition(frk_0.h);
                    ((fqv)fyb_02).setTexture(this.a.c("txScrollbarSlider"));
                    ((fqv)fyb_02).setWidth(4);
                    ((fqv)fyb_02).setX(0);
                    ((fqv)fyb_02).setY(4);
                    fyb_03.addBasicElement(fyb_02);
                    fyb_02.onAttributesInitialized();
                    fyb_02.onChildrenAdded();
                    fyg_02 = fqv.checkOut();
                    fyg_02.setElementMap(fyy_03);
                    ((fqv)fyg_02).setHeight(4);
                    ((fqv)fyg_02).setPosition(frk_0.m);
                    ((fqv)fyg_02).setTexture(this.a.c("txScrollbarSlider"));
                    ((fqv)fyg_02).setWidth(4);
                    ((fqv)fyg_02).setX(0);
                    ((fqv)fyg_02).setY(12);
                    fyb_03.addBasicElement(fyg_02);
                    fyg_02.onAttributesInitialized();
                    fyg_02.onChildrenAdded();
                    fqv2 = fqv.checkOut();
                    fqv2.setElementMap(fyy_03);
                    fqv2.setHeight(4);
                    fqv2.setPosition(frk_0.c);
                    fqv2.setTexture(this.a.c("txScrollbarSlider"));
                    fqv2.setWidth(1);
                    fqv2.setX(3);
                    fqv2.setY(0);
                    fyb_03.addBasicElement(fqv2);
                    fqv2.onAttributesInitialized();
                    fqv2.onChildrenAdded();
                    fqv fqv3 = fqv.checkOut();
                    fqv3.setElementMap(fyy_03);
                    fqv3.setHeight(1);
                    fqv3.setPosition(frk_0.i);
                    fqv3.setTexture(this.a.c("txScrollbarSlider"));
                    fqv3.setWidth(1);
                    fqv3.setX(3);
                    fqv3.setY(4);
                    fyb_03.addBasicElement(fqv3);
                    fqv3.onAttributesInitialized();
                    fqv3.onChildrenAdded();
                    fqv fqv4 = fqv.checkOut();
                    fqv4.setElementMap(fyy_03);
                    fqv4.setHeight(4);
                    fqv4.setPosition(frk_0.o);
                    fqv4.setTexture(this.a.c("txScrollbarSlider"));
                    fqv4.setWidth(1);
                    fqv4.setX(3);
                    fqv4.setY(12);
                    fyb_03.addBasicElement(fqv4);
                    fqv4.onAttributesInitialized();
                    fqv4.onChildrenAdded();
                    fqv fqv5 = fqv.checkOut();
                    fqv5.setElementMap(fyy_03);
                    fqv5.setHeight(4);
                    fqv5.setPosition(frk_0.e);
                    fqv5.setTexture(this.a.c("txScrollbarSlider"));
                    fqv5.setWidth(4);
                    fqv5.setX(4);
                    fqv5.setY(0);
                    fyb_03.addBasicElement(fqv5);
                    fqv5.onAttributesInitialized();
                    fqv5.onChildrenAdded();
                    fqv fqv6 = fqv.checkOut();
                    fqv6.setElementMap(fyy_03);
                    fqv6.setHeight(1);
                    fqv6.setPosition(frk_0.j);
                    fqv6.setTexture(this.a.c("txScrollbarSlider"));
                    fqv6.setWidth(4);
                    fqv6.setX(4);
                    fqv6.setY(4);
                    fyb_03.addBasicElement(fqv6);
                    fqv6.onAttributesInitialized();
                    fqv6.onChildrenAdded();
                    fqv fqv7 = fqv.checkOut();
                    fqv7.setElementMap(fyy_03);
                    fqv7.setHeight(4);
                    fqv7.setPosition(frk_0.q);
                    fqv7.setTexture(this.a.c("txScrollbarSlider"));
                    fqv7.setWidth(4);
                    fqv7.setX(4);
                    fqv7.setY(12);
                    fyb_03.addBasicElement(fqv7);
                    fqv7.onAttributesInitialized();
                    fqv7.onChildrenAdded();
                    fyb_03.onChildrenAdded();
                    fqv fqv8 = fqv.checkOut();
                    fqv8.setElementMap(fyy_03);
                    fqv8.setHeight(0);
                    fqv8.setPosition(frk_0.i);
                    fqv8.setTexture(this.a.c("txScrollbarSlider"));
                    fqv8.setWidth(0);
                    fqv8.setX(0);
                    fqv8.setY(16);
                    fyb_04.addBasicElement(fqv8);
                    fqv8.onAttributesInitialized();
                    fqv8.onChildrenAdded();
                    fyb_04.onChildrenAdded();
                    fvE fvE10 = (fvE)fyb_06;
                    fqd_0 fqd_02 = (fqd_0)fvE10.getAppearance();
                    fqd_02.setElementMap(fyy_03);
                    fqd_02.setState("mouseHover");
                    fyb_06.addBasicElement(fqd_02);
                    fqd_02.onAttributesInitialized();
                    fby_2 fby_22 = fby_2.checkOut();
                    fby_22.setElementMap(fyy_03);
                    fby_22.setScaled(true);
                    fqd_02.addBasicElement(fby_22);
                    fby_22.onAttributesInitialized();
                    fqv fqv9 = fqv.checkOut();
                    fqv9.setElementMap(fyy_03);
                    fqv9.setHeight(4);
                    fqv9.setPosition(frk_0.a);
                    fqv9.setTexture(this.a.c("txScrollbarSlider"));
                    fqv9.setWidth(4);
                    fqv9.setX(0);
                    fqv9.setY(18);
                    fby_22.addBasicElement(fqv9);
                    fqv9.onAttributesInitialized();
                    fqv9.onChildrenAdded();
                    fqv fqv10 = fqv.checkOut();
                    fqv10.setElementMap(fyy_03);
                    fqv10.setHeight(1);
                    fqv10.setPosition(frk_0.h);
                    fqv10.setTexture(this.a.c("txScrollbarSlider"));
                    fqv10.setWidth(4);
                    fqv10.setX(0);
                    fqv10.setY(22);
                    fby_22.addBasicElement(fqv10);
                    fqv10.onAttributesInitialized();
                    fqv10.onChildrenAdded();
                    fqv fqv11 = fqv.checkOut();
                    fqv11.setElementMap(fyy_03);
                    fqv11.setHeight(4);
                    fqv11.setPosition(frk_0.m);
                    fqv11.setTexture(this.a.c("txScrollbarSlider"));
                    fqv11.setWidth(4);
                    fqv11.setX(0);
                    fqv11.setY(30);
                    fby_22.addBasicElement(fqv11);
                    fqv11.onAttributesInitialized();
                    fqv11.onChildrenAdded();
                    fqv fqv12 = fqv.checkOut();
                    fqv12.setElementMap(fyy_03);
                    fqv12.setHeight(4);
                    fqv12.setPosition(frk_0.c);
                    fqv12.setTexture(this.a.c("txScrollbarSlider"));
                    fqv12.setWidth(1);
                    fqv12.setX(3);
                    fqv12.setY(18);
                    fby_22.addBasicElement(fqv12);
                    fqv12.onAttributesInitialized();
                    fqv12.onChildrenAdded();
                    fqv fqv13 = fqv.checkOut();
                    fqv13.setElementMap(fyy_03);
                    fqv13.setHeight(1);
                    fqv13.setPosition(frk_0.i);
                    fqv13.setTexture(this.a.c("txScrollbarSlider"));
                    fqv13.setWidth(1);
                    fqv13.setX(3);
                    fqv13.setY(22);
                    fby_22.addBasicElement(fqv13);
                    fqv13.onAttributesInitialized();
                    fqv13.onChildrenAdded();
                    fqv fqv14 = fqv.checkOut();
                    fqv14.setElementMap(fyy_03);
                    fqv14.setHeight(4);
                    fqv14.setPosition(frk_0.o);
                    fqv14.setTexture(this.a.c("txScrollbarSlider"));
                    fqv14.setWidth(1);
                    fqv14.setX(3);
                    fqv14.setY(30);
                    fby_22.addBasicElement(fqv14);
                    fqv14.onAttributesInitialized();
                    fqv14.onChildrenAdded();
                    fqv fqv15 = fqv.checkOut();
                    fqv15.setElementMap(fyy_03);
                    fqv15.setHeight(4);
                    fqv15.setPosition(frk_0.e);
                    fqv15.setTexture(this.a.c("txScrollbarSlider"));
                    fqv15.setWidth(4);
                    fqv15.setX(4);
                    fqv15.setY(18);
                    fby_22.addBasicElement(fqv15);
                    fqv15.onAttributesInitialized();
                    fqv15.onChildrenAdded();
                    fqv fqv16 = fqv.checkOut();
                    fqv16.setElementMap(fyy_03);
                    fqv16.setHeight(1);
                    fqv16.setPosition(frk_0.j);
                    fqv16.setTexture(this.a.c("txScrollbarSlider"));
                    fqv16.setWidth(4);
                    fqv16.setX(4);
                    fqv16.setY(22);
                    fby_22.addBasicElement(fqv16);
                    fqv16.onAttributesInitialized();
                    fqv16.onChildrenAdded();
                    fqv fqv17 = fqv.checkOut();
                    fqv17.setElementMap(fyy_03);
                    fqv17.setHeight(4);
                    fqv17.setPosition(frk_0.q);
                    fqv17.setTexture(this.a.c("txScrollbarSlider"));
                    fqv17.setWidth(4);
                    fqv17.setX(4);
                    fqv17.setY(30);
                    fby_22.addBasicElement(fqv17);
                    fqv17.onAttributesInitialized();
                    fqv17.onChildrenAdded();
                    fby_22.onChildrenAdded();
                    fqd_02.onChildrenAdded();
                    fvE fvE11 = (fvE)fyb_06;
                    fqd_0 fqd_03 = (fqd_0)fvE11.getAppearance();
                    fqd_03.setElementMap(fyy_03);
                    fqd_03.setState("pressed");
                    fyb_06.addBasicElement(fqd_03);
                    fqd_03.onAttributesInitialized();
                    fby_2 fby_23 = fby_2.checkOut();
                    fby_23.setElementMap(fyy_03);
                    fby_23.setScaled(true);
                    fqd_03.addBasicElement(fby_23);
                    fby_23.onAttributesInitialized();
                    fqv fqv18 = fqv.checkOut();
                    fqv18.setElementMap(fyy_03);
                    fqv18.setHeight(4);
                    fqv18.setPosition(frk_0.a);
                    fqv18.setTexture(this.a.c("txScrollbarSlider"));
                    fqv18.setWidth(4);
                    fqv18.setX(0);
                    fqv18.setY(36);
                    fby_23.addBasicElement(fqv18);
                    fqv18.onAttributesInitialized();
                    fqv18.onChildrenAdded();
                    fqv fqv19 = fqv.checkOut();
                    fqv19.setElementMap(fyy_03);
                    fqv19.setHeight(1);
                    fqv19.setPosition(frk_0.h);
                    fqv19.setTexture(this.a.c("txScrollbarSlider"));
                    fqv19.setWidth(4);
                    fqv19.setX(0);
                    fqv19.setY(40);
                    fby_23.addBasicElement(fqv19);
                    fqv19.onAttributesInitialized();
                    fqv19.onChildrenAdded();
                    fqv fqv20 = fqv.checkOut();
                    fqv20.setElementMap(fyy_03);
                    fqv20.setHeight(4);
                    fqv20.setPosition(frk_0.m);
                    fqv20.setTexture(this.a.c("txScrollbarSlider"));
                    fqv20.setWidth(4);
                    fqv20.setX(0);
                    fqv20.setY(48);
                    fby_23.addBasicElement(fqv20);
                    fqv20.onAttributesInitialized();
                    fqv20.onChildrenAdded();
                    fqv fqv21 = fqv.checkOut();
                    fqv21.setElementMap(fyy_03);
                    fqv21.setHeight(4);
                    fqv21.setPosition(frk_0.c);
                    fqv21.setTexture(this.a.c("txScrollbarSlider"));
                    fqv21.setWidth(1);
                    fqv21.setX(3);
                    fqv21.setY(36);
                    fby_23.addBasicElement(fqv21);
                    fqv21.onAttributesInitialized();
                    fqv21.onChildrenAdded();
                    fqv fqv22 = fqv.checkOut();
                    fqv22.setElementMap(fyy_03);
                    fqv22.setHeight(1);
                    fqv22.setPosition(frk_0.i);
                    fqv22.setTexture(this.a.c("txScrollbarSlider"));
                    fqv22.setWidth(1);
                    fqv22.setX(3);
                    fqv22.setY(40);
                    fby_23.addBasicElement(fqv22);
                    fqv22.onAttributesInitialized();
                    fqv22.onChildrenAdded();
                    fqv fqv23 = fqv.checkOut();
                    fqv23.setElementMap(fyy_03);
                    fqv23.setHeight(4);
                    fqv23.setPosition(frk_0.o);
                    fqv23.setTexture(this.a.c("txScrollbarSlider"));
                    fqv23.setWidth(1);
                    fqv23.setX(3);
                    fqv23.setY(48);
                    fby_23.addBasicElement(fqv23);
                    fqv23.onAttributesInitialized();
                    fqv23.onChildrenAdded();
                    this.a(fby_23);
                    this.b(fby_23);
                    this.c(fby_23);
                    fby_23.onChildrenAdded();
                    fqd_03.onChildrenAdded();
                    this.d(fyb_06);
                }
                this.e(fyg_04);
                fyg_04.onChildrenAdded();
            }
            fqj2.onChildrenAdded();
        }
        this.f(fqr2);
        fqr2.onChildrenAdded();
    }

    public fyo a(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(4);
        fqv2.setPosition(frk_0.e);
        fqv2.setTexture(this.a.c("txScrollbarSlider"));
        fqv2.setWidth(4);
        fqv2.setX(4);
        fqv2.setY(36);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo b(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(1);
        fqv2.setPosition(frk_0.j);
        fqv2.setTexture(this.a.c("txScrollbarSlider"));
        fqv2.setWidth(4);
        fqv2.setX(4);
        fqv2.setY(40);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo c(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(4);
        fqv2.setPosition(frk_0.q);
        fqv2.setTexture(this.a.c("txScrollbarSlider"));
        fqv2.setWidth(4);
        fqv2.setX(4);
        fqv2.setY(48);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo d(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fvE fvE2 = (fvE)fyo2;
        fqd_0 fqd_02 = (fqd_0)fvE2.getAppearance();
        fqd_02.setElementMap(fyy_02);
        fqd_02.setState("disabled");
        fyo2.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_02);
        fby_22.setScaled(true);
        fqd_02.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(4);
        fqv2.setPosition(frk_0.a);
        fqv2.setTexture(this.a.c("txScrollbarSlider"));
        fqv2.setWidth(4);
        fqv2.setX(0);
        fqv2.setY(54);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fqv3.setHeight(1);
        fqv3.setPosition(frk_0.h);
        fqv3.setTexture(this.a.c("txScrollbarSlider"));
        fqv3.setWidth(4);
        fqv3.setX(0);
        fqv3.setY(58);
        fby_22.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_02);
        fqv4.setHeight(4);
        fqv4.setPosition(frk_0.m);
        fqv4.setTexture(this.a.c("txScrollbarSlider"));
        fqv4.setWidth(4);
        fqv4.setX(0);
        fqv4.setY(66);
        fby_22.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_02);
        fqv5.setHeight(4);
        fqv5.setPosition(frk_0.c);
        fqv5.setTexture(this.a.c("txScrollbarSlider"));
        fqv5.setWidth(1);
        fqv5.setX(3);
        fqv5.setY(54);
        fby_22.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_02);
        fqv6.setHeight(1);
        fqv6.setPosition(frk_0.i);
        fqv6.setTexture(this.a.c("txScrollbarSlider"));
        fqv6.setWidth(1);
        fqv6.setX(3);
        fqv6.setY(58);
        fby_22.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_02);
        fqv7.setHeight(4);
        fqv7.setPosition(frk_0.o);
        fqv7.setTexture(this.a.c("txScrollbarSlider"));
        fqv7.setWidth(1);
        fqv7.setX(3);
        fqv7.setY(66);
        fby_22.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_02);
        fqv8.setHeight(4);
        fqv8.setPosition(frk_0.e);
        fqv8.setTexture(this.a.c("txScrollbarSlider"));
        fqv8.setWidth(4);
        fqv8.setX(4);
        fqv8.setY(54);
        fby_22.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_02);
        fqv9.setHeight(1);
        fqv9.setPosition(frk_0.j);
        fqv9.setTexture(this.a.c("txScrollbarSlider"));
        fqv9.setWidth(4);
        fqv9.setX(4);
        fqv9.setY(58);
        fby_22.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_02);
        fqv10.setHeight(4);
        fqv10.setPosition(frk_0.q);
        fqv10.setTexture(this.a.c("txScrollbarSlider"));
        fqv10.setWidth(4);
        fqv10.setX(4);
        fqv10.setY(66);
        fby_22.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fby_22.onChildrenAdded();
        fqd_02.onChildrenAdded();
        return fqd_02;
    }

    public fyo e(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_02);
        fby_22.setEnabled(true);
        fby_22.setScaled(true);
        fyo2.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(3);
        fqv2.setPosition(frk_0.a);
        fqv2.setTexture(this.a.c("txScrollbarBackground"));
        fqv2.setWidth(3);
        fqv2.setX(0);
        fqv2.setY(0);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fqv3.setHeight(0);
        fqv3.setPosition(frk_0.h);
        fqv3.setTexture(this.a.c("txScrollbarBackground"));
        fqv3.setWidth(3);
        fqv3.setX(0);
        fqv3.setY(4);
        fby_22.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_02);
        fqv4.setHeight(3);
        fqv4.setPosition(frk_0.m);
        fqv4.setTexture(this.a.c("txScrollbarBackground"));
        fqv4.setWidth(3);
        fqv4.setX(0);
        fqv4.setY(13);
        fby_22.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_02);
        fqv5.setHeight(3);
        fqv5.setPosition(frk_0.c);
        fqv5.setTexture(this.a.c("txScrollbarBackground"));
        fqv5.setWidth(1);
        fqv5.setX(2);
        fqv5.setY(0);
        fby_22.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_02);
        fqv6.setHeight(0);
        fqv6.setPosition(frk_0.i);
        fqv6.setTexture(this.a.c("txScrollbarBackground"));
        fqv6.setWidth(1);
        fqv6.setX(2);
        fqv6.setY(4);
        fby_22.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_02);
        fqv7.setHeight(3);
        fqv7.setPosition(frk_0.o);
        fqv7.setTexture(this.a.c("txScrollbarBackground"));
        fqv7.setWidth(1);
        fqv7.setX(2);
        fqv7.setY(13);
        fby_22.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_02);
        fqv8.setHeight(3);
        fqv8.setPosition(frk_0.e);
        fqv8.setTexture(this.a.c("txScrollbarBackground"));
        fqv8.setWidth(3);
        fqv8.setX(3);
        fqv8.setY(0);
        fby_22.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_02);
        fqv9.setHeight(0);
        fqv9.setPosition(frk_0.j);
        fqv9.setTexture(this.a.c("txScrollbarBackground"));
        fqv9.setWidth(3);
        fqv9.setX(3);
        fqv9.setY(4);
        fby_22.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_02);
        fqv10.setHeight(3);
        fqv10.setPosition(frk_0.q);
        fqv10.setTexture(this.a.c("txScrollbarBackground"));
        fqv10.setWidth(3);
        fqv10.setX(3);
        fqv10.setY(13);
        fby_22.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fby_22.onChildrenAdded();
        return fby_22;
    }

    public fyo f(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fvE fvE2 = fyo2.getParentOfType(fvE.class);
        fvE fvE3 = fvE2.getWidgetByThemeElementName("renderableTemplate", false);
        if (fvE3 != null) {
            fvE fvE4 = fvE3;
            fqj fqj2 = fvE4.getAppearance();
            fqj2.setElementMap(fyy_02);
            fqj2.setState("default");
            fvE3.addBasicElement(fqj2);
            fqj2.onAttributesInitialized();
            String string = "pmbListElementDefault";
            fby_2 fby_22 = fby_2.checkOut();
            fby_22.setElementMap(fyy_02);
            if (fyy_02 != null && string != null) {
                fyy_02.a(string, fby_22);
            }
            fby_22.setScaled(true);
            fqj2.addBasicElement(fby_22);
            fby_22.onAttributesInitialized();
            fqv fqv2 = fqv.checkOut();
            fqv2.setElementMap(fyy_02);
            fqv2.setHeight(8);
            fqv2.setPosition(frk_0.a);
            fqv2.setTexture(this.a.c("txListElement"));
            fqv2.setWidth(8);
            fqv2.setX(0);
            fqv2.setY(0);
            fby_22.addBasicElement(fqv2);
            fqv2.onAttributesInitialized();
            fqv2.onChildrenAdded();
            fqv fqv3 = fqv.checkOut();
            fqv3.setElementMap(fyy_02);
            fqv3.setHeight(1);
            fqv3.setPosition(frk_0.h);
            fqv3.setTexture(this.a.c("txListElement"));
            fqv3.setWidth(8);
            fqv3.setX(0);
            fqv3.setY(18);
            fby_22.addBasicElement(fqv3);
            fqv3.onAttributesInitialized();
            fqv3.onChildrenAdded();
            fqv fqv4 = fqv.checkOut();
            fqv4.setElementMap(fyy_02);
            fqv4.setHeight(10);
            fqv4.setPosition(frk_0.m);
            fqv4.setTexture(this.a.c("txListElement"));
            fqv4.setWidth(8);
            fqv4.setX(0);
            fqv4.setY(28);
            fby_22.addBasicElement(fqv4);
            fqv4.onAttributesInitialized();
            fqv4.onChildrenAdded();
            fqv fqv5 = fqv.checkOut();
            fqv5.setElementMap(fyy_02);
            fqv5.setHeight(8);
            fqv5.setPosition(frk_0.c);
            fqv5.setTexture(this.a.c("txListElement"));
            fqv5.setWidth(1);
            fqv5.setX(18);
            fqv5.setY(0);
            fby_22.addBasicElement(fqv5);
            fqv5.onAttributesInitialized();
            fqv5.onChildrenAdded();
            fqv fqv6 = fqv.checkOut();
            fqv6.setElementMap(fyy_02);
            fqv6.setHeight(1);
            fqv6.setPosition(frk_0.i);
            fqv6.setTexture(this.a.c("txListElement"));
            fqv6.setWidth(1);
            fqv6.setX(18);
            fqv6.setY(18);
            fby_22.addBasicElement(fqv6);
            fqv6.onAttributesInitialized();
            fqv6.onChildrenAdded();
            fqv fqv7 = fqv.checkOut();
            fqv7.setElementMap(fyy_02);
            fqv7.setHeight(10);
            fqv7.setPosition(frk_0.o);
            fqv7.setTexture(this.a.c("txListElement"));
            fqv7.setWidth(1);
            fqv7.setX(18);
            fqv7.setY(28);
            fby_22.addBasicElement(fqv7);
            fqv7.onAttributesInitialized();
            fqv7.onChildrenAdded();
            fqv fqv8 = fqv.checkOut();
            fqv8.setElementMap(fyy_02);
            fqv8.setHeight(8);
            fqv8.setPosition(frk_0.e);
            fqv8.setTexture(this.a.c("txListElement"));
            fqv8.setWidth(8);
            fqv8.setX(28);
            fqv8.setY(0);
            fby_22.addBasicElement(fqv8);
            fqv8.onAttributesInitialized();
            fqv8.onChildrenAdded();
            fqv fqv9 = fqv.checkOut();
            fqv9.setElementMap(fyy_02);
            fqv9.setHeight(1);
            fqv9.setPosition(frk_0.j);
            fqv9.setTexture(this.a.c("txListElement"));
            fqv9.setWidth(8);
            fqv9.setX(28);
            fqv9.setY(18);
            fby_22.addBasicElement(fqv9);
            fqv9.onAttributesInitialized();
            fqv9.onChildrenAdded();
            fqv fqv10 = fqv.checkOut();
            fqv10.setElementMap(fyy_02);
            fqv10.setHeight(10);
            fqv10.setPosition(frk_0.q);
            fqv10.setTexture(this.a.c("txListElement"));
            fqv10.setWidth(8);
            fqv10.setX(28);
            fqv10.setY(28);
            fby_22.addBasicElement(fqv10);
            fqv10.onAttributesInitialized();
            fqv10.onChildrenAdded();
            fby_22.onChildrenAdded();
            fqj2.onChildrenAdded();
            fvE fvE5 = fvE3;
            fqj fqj3 = fvE5.getAppearance();
            fqj3.setElementMap(fyy_02);
            fqj3.setState("mouseHover");
            fvE3.addBasicElement(fqj3);
            fqj3.onAttributesInitialized();
            String string2 = "pmbListElementOver";
            fby_2 fby_23 = fby_2.checkOut();
            fby_23.setElementMap(fyy_02);
            if (fyy_02 != null && string2 != null) {
                fyy_02.a(string2, fby_23);
            }
            fby_23.setScaled(true);
            fqj3.addBasicElement(fby_23);
            fby_23.onAttributesInitialized();
            fqv fqv11 = fqv.checkOut();
            fqv11.setElementMap(fyy_02);
            fqv11.setHeight(8);
            fqv11.setPosition(frk_0.a);
            fqv11.setTexture(this.a.c("txListElement"));
            fqv11.setWidth(8);
            fqv11.setX(0);
            fqv11.setY(40);
            fby_23.addBasicElement(fqv11);
            fqv11.onAttributesInitialized();
            fqv11.onChildrenAdded();
            fqv fqv12 = fqv.checkOut();
            fqv12.setElementMap(fyy_02);
            fqv12.setHeight(1);
            fqv12.setPosition(frk_0.h);
            fqv12.setTexture(this.a.c("txListElement"));
            fqv12.setWidth(8);
            fqv12.setX(0);
            fqv12.setY(58);
            fby_23.addBasicElement(fqv12);
            fqv12.onAttributesInitialized();
            fqv12.onChildrenAdded();
            fqv fqv13 = fqv.checkOut();
            fqv13.setElementMap(fyy_02);
            fqv13.setHeight(10);
            fqv13.setPosition(frk_0.m);
            fqv13.setTexture(this.a.c("txListElement"));
            fqv13.setWidth(8);
            fqv13.setX(0);
            fqv13.setY(68);
            fby_23.addBasicElement(fqv13);
            fqv13.onAttributesInitialized();
            fqv13.onChildrenAdded();
            fqv fqv14 = fqv.checkOut();
            fqv14.setElementMap(fyy_02);
            fqv14.setHeight(8);
            fqv14.setPosition(frk_0.c);
            fqv14.setTexture(this.a.c("txListElement"));
            fqv14.setWidth(1);
            fqv14.setX(18);
            fqv14.setY(40);
            fby_23.addBasicElement(fqv14);
            fqv14.onAttributesInitialized();
            fqv14.onChildrenAdded();
            fqv fqv15 = fqv.checkOut();
            fqv15.setElementMap(fyy_02);
            fqv15.setHeight(1);
            fqv15.setPosition(frk_0.i);
            fqv15.setTexture(this.a.c("txListElement"));
            fqv15.setWidth(1);
            fqv15.setX(18);
            fqv15.setY(58);
            fby_23.addBasicElement(fqv15);
            fqv15.onAttributesInitialized();
            fqv15.onChildrenAdded();
            fqv fqv16 = fqv.checkOut();
            fqv16.setElementMap(fyy_02);
            fqv16.setHeight(10);
            fqv16.setPosition(frk_0.o);
            fqv16.setTexture(this.a.c("txListElement"));
            fqv16.setWidth(1);
            fqv16.setX(18);
            fqv16.setY(68);
            fby_23.addBasicElement(fqv16);
            fqv16.onAttributesInitialized();
            fqv16.onChildrenAdded();
            fqv fqv17 = fqv.checkOut();
            fqv17.setElementMap(fyy_02);
            fqv17.setHeight(8);
            fqv17.setPosition(frk_0.e);
            fqv17.setTexture(this.a.c("txListElement"));
            fqv17.setWidth(8);
            fqv17.setX(28);
            fqv17.setY(40);
            fby_23.addBasicElement(fqv17);
            fqv17.onAttributesInitialized();
            fqv17.onChildrenAdded();
            fqv fqv18 = fqv.checkOut();
            fqv18.setElementMap(fyy_02);
            fqv18.setHeight(1);
            fqv18.setPosition(frk_0.j);
            fqv18.setTexture(this.a.c("txListElement"));
            fqv18.setWidth(8);
            fqv18.setX(28);
            fqv18.setY(58);
            fby_23.addBasicElement(fqv18);
            fqv18.onAttributesInitialized();
            fqv18.onChildrenAdded();
            fqv fqv19 = fqv.checkOut();
            fqv19.setElementMap(fyy_02);
            fqv19.setHeight(10);
            fqv19.setPosition(frk_0.q);
            fqv19.setTexture(this.a.c("txListElement"));
            fqv19.setWidth(8);
            fqv19.setX(28);
            fqv19.setY(68);
            fby_23.addBasicElement(fqv19);
            fqv19.onAttributesInitialized();
            fqv19.onChildrenAdded();
            fby_23.onChildrenAdded();
            fqj3.onChildrenAdded();
            fvE fvE6 = fvE3;
            fqj fqj4 = fvE6.getAppearance();
            fqj4.setElementMap(fyy_02);
            fqj4.setState("pressed");
            fvE3.addBasicElement(fqj4);
            fqj4.onAttributesInitialized();
            String string3 = "pmbListElementPressed";
            fby_2 fby_24 = fby_2.checkOut();
            fby_24.setElementMap(fyy_02);
            if (fyy_02 != null && string3 != null) {
                fyy_02.a(string3, fby_24);
            }
            fby_24.setScaled(true);
            fqj4.addBasicElement(fby_24);
            fby_24.onAttributesInitialized();
            fqv fqv20 = fqv.checkOut();
            fqv20.setElementMap(fyy_02);
            fqv20.setHeight(8);
            fqv20.setPosition(frk_0.a);
            fqv20.setTexture(this.a.c("txListElement"));
            fqv20.setWidth(8);
            fqv20.setX(0);
            fqv20.setY(80);
            fby_24.addBasicElement(fqv20);
            fqv20.onAttributesInitialized();
            fqv20.onChildrenAdded();
            fqv fqv21 = fqv.checkOut();
            fqv21.setElementMap(fyy_02);
            fqv21.setHeight(1);
            fqv21.setPosition(frk_0.h);
            fqv21.setTexture(this.a.c("txListElement"));
            fqv21.setWidth(8);
            fqv21.setX(0);
            fqv21.setY(98);
            fby_24.addBasicElement(fqv21);
            fqv21.onAttributesInitialized();
            fqv21.onChildrenAdded();
            fqv fqv22 = fqv.checkOut();
            fqv22.setElementMap(fyy_02);
            fqv22.setHeight(10);
            fqv22.setPosition(frk_0.m);
            fqv22.setTexture(this.a.c("txListElement"));
            fqv22.setWidth(8);
            fqv22.setX(0);
            fqv22.setY(108);
            fby_24.addBasicElement(fqv22);
            fqv22.onAttributesInitialized();
            fqv22.onChildrenAdded();
            fqv fqv23 = fqv.checkOut();
            fqv23.setElementMap(fyy_02);
            fqv23.setHeight(8);
            fqv23.setPosition(frk_0.c);
            fqv23.setTexture(this.a.c("txListElement"));
            fqv23.setWidth(1);
            fqv23.setX(18);
            fqv23.setY(80);
            fby_24.addBasicElement(fqv23);
            fqv23.onAttributesInitialized();
            fqv23.onChildrenAdded();
            fqv fqv24 = fqv.checkOut();
            fqv24.setElementMap(fyy_02);
            fqv24.setHeight(1);
            fqv24.setPosition(frk_0.i);
            fqv24.setTexture(this.a.c("txListElement"));
            fqv24.setWidth(1);
            fqv24.setX(18);
            fqv24.setY(98);
            fby_24.addBasicElement(fqv24);
            fqv24.onAttributesInitialized();
            fqv24.onChildrenAdded();
            fqv fqv25 = fqv.checkOut();
            fqv25.setElementMap(fyy_02);
            fqv25.setHeight(10);
            fqv25.setPosition(frk_0.o);
            fqv25.setTexture(this.a.c("txListElement"));
            fqv25.setWidth(1);
            fqv25.setX(18);
            fqv25.setY(108);
            fby_24.addBasicElement(fqv25);
            fqv25.onAttributesInitialized();
            fqv25.onChildrenAdded();
            fqv fqv26 = fqv.checkOut();
            fqv26.setElementMap(fyy_02);
            fqv26.setHeight(8);
            fqv26.setPosition(frk_0.e);
            fqv26.setTexture(this.a.c("txListElement"));
            fqv26.setWidth(8);
            fqv26.setX(28);
            fqv26.setY(80);
            fby_24.addBasicElement(fqv26);
            fqv26.onAttributesInitialized();
            fqv26.onChildrenAdded();
            fqv fqv27 = fqv.checkOut();
            fqv27.setElementMap(fyy_02);
            fqv27.setHeight(1);
            fqv27.setPosition(frk_0.j);
            fqv27.setTexture(this.a.c("txListElement"));
            fqv27.setWidth(8);
            fqv27.setX(28);
            fqv27.setY(98);
            fby_24.addBasicElement(fqv27);
            fqv27.onAttributesInitialized();
            fqv27.onChildrenAdded();
            fqv fqv28 = fqv.checkOut();
            fqv28.setElementMap(fyy_02);
            fqv28.setHeight(10);
            fqv28.setPosition(frk_0.q);
            fqv28.setTexture(this.a.c("txListElement"));
            fqv28.setWidth(8);
            fqv28.setX(28);
            fqv28.setY(108);
            fby_24.addBasicElement(fqv28);
            fqv28.onAttributesInitialized();
            fqv28.onChildrenAdded();
            fby_24.onChildrenAdded();
            fqj4.onChildrenAdded();
            fvE fvE7 = fvE3;
            fqj fqj5 = fvE7.getAppearance();
            fqj5.setElementMap(fyy_02);
            fqj5.setState("disabled");
            fvE3.addBasicElement(fqj5);
            fqj5.onAttributesInitialized();
            String string4 = "pmbListElementDisabled";
            fby_2 fby_25 = fby_2.checkOut();
            fby_25.setElementMap(fyy_02);
            if (fyy_02 != null && string4 != null) {
                fyy_02.a(string4, fby_25);
            }
            fby_25.setScaled(true);
            fqj5.addBasicElement(fby_25);
            fby_25.onAttributesInitialized();
            fqv fqv29 = fqv.checkOut();
            fqv29.setElementMap(fyy_02);
            fqv29.setHeight(8);
            fqv29.setPosition(frk_0.a);
            fqv29.setTexture(this.a.c("txListElement"));
            fqv29.setWidth(8);
            fqv29.setX(0);
            fqv29.setY(120);
            fby_25.addBasicElement(fqv29);
            fqv29.onAttributesInitialized();
            fqv29.onChildrenAdded();
            fqv fqv30 = fqv.checkOut();
            fqv30.setElementMap(fyy_02);
            fqv30.setHeight(8);
            fqv30.setPosition(frk_0.c);
            fqv30.setTexture(this.a.c("txListElement"));
            fqv30.setWidth(1);
            fqv30.setX(18);
            fqv30.setY(120);
            fby_25.addBasicElement(fqv30);
            fqv30.onAttributesInitialized();
            fqv30.onChildrenAdded();
            fqv fqv31 = fqv.checkOut();
            fqv31.setElementMap(fyy_02);
            fqv31.setHeight(8);
            fqv31.setPosition(frk_0.e);
            fqv31.setTexture(this.a.c("txListElement"));
            fqv31.setWidth(8);
            fqv31.setX(28);
            fqv31.setY(120);
            fby_25.addBasicElement(fqv31);
            fqv31.onAttributesInitialized();
            fqv31.onChildrenAdded();
            fqv fqv32 = fqv.checkOut();
            fqv32.setElementMap(fyy_02);
            fqv32.setHeight(1);
            fqv32.setPosition(frk_0.h);
            fqv32.setTexture(this.a.c("txListElement"));
            fqv32.setWidth(8);
            fqv32.setX(0);
            fqv32.setY(139);
            fby_25.addBasicElement(fqv32);
            fqv32.onAttributesInitialized();
            fqv32.onChildrenAdded();
            fqv fqv33 = fqv.checkOut();
            fqv33.setElementMap(fyy_02);
            fqv33.setHeight(1);
            fqv33.setPosition(frk_0.i);
            fqv33.setTexture(this.a.c("txListElement"));
            fqv33.setWidth(1);
            fqv33.setX(18);
            fqv33.setY(139);
            fby_25.addBasicElement(fqv33);
            fqv33.onAttributesInitialized();
            fqv33.onChildrenAdded();
            fqv fqv34 = fqv.checkOut();
            fqv34.setElementMap(fyy_02);
            fqv34.setHeight(1);
            fqv34.setPosition(frk_0.j);
            fqv34.setTexture(this.a.c("txListElement"));
            fqv34.setWidth(8);
            fqv34.setX(28);
            fqv34.setY(139);
            fby_25.addBasicElement(fqv34);
            fqv34.onAttributesInitialized();
            fqv34.onChildrenAdded();
            fqv fqv35 = fqv.checkOut();
            fqv35.setElementMap(fyy_02);
            fqv35.setHeight(10);
            fqv35.setPosition(frk_0.m);
            fqv35.setTexture(this.a.c("txListElement"));
            fqv35.setWidth(8);
            fqv35.setX(0);
            fqv35.setY(148);
            fby_25.addBasicElement(fqv35);
            fqv35.onAttributesInitialized();
            fqv35.onChildrenAdded();
            fqv fqv36 = fqv.checkOut();
            fqv36.setElementMap(fyy_02);
            fqv36.setHeight(10);
            fqv36.setPosition(frk_0.o);
            fqv36.setTexture(this.a.c("txListElement"));
            fqv36.setWidth(1);
            fqv36.setX(18);
            fqv36.setY(148);
            fby_25.addBasicElement(fqv36);
            fqv36.onAttributesInitialized();
            fqv36.onChildrenAdded();
            fqv fqv37 = fqv.checkOut();
            fqv37.setElementMap(fyy_02);
            fqv37.setHeight(10);
            fqv37.setPosition(frk_0.q);
            fqv37.setTexture(this.a.c("txListElement"));
            fqv37.setWidth(8);
            fqv37.setX(28);
            fqv37.setY(148);
            fby_25.addBasicElement(fqv37);
            fqv37.onAttributesInitialized();
            fqv37.onChildrenAdded();
            fby_25.onChildrenAdded();
            fqj5.onChildrenAdded();
            fvE fvE8 = fvE3;
            fqj fqj6 = fvE8.getAppearance();
            fqj6.setElementMap(fyy_02);
            fqj6.setState("selected");
            fvE3.addBasicElement(fqj6);
            fqj6.onAttributesInitialized();
            String string5 = "pmbListElementSelected";
            fby_2 fby_26 = fby_2.checkOut();
            fby_26.setElementMap(fyy_02);
            if (fyy_02 != null && string5 != null) {
                fyy_02.a(string5, fby_26);
            }
            fby_26.setScaled(true);
            fqj6.addBasicElement(fby_26);
            fby_26.onAttributesInitialized();
            fqv fqv38 = fqv.checkOut();
            fqv38.setElementMap(fyy_02);
            fqv38.setHeight(8);
            fqv38.setPosition(frk_0.a);
            fqv38.setTexture(this.a.c("txListElement"));
            fqv38.setWidth(8);
            fqv38.setX(0);
            fqv38.setY(160);
            fby_26.addBasicElement(fqv38);
            fqv38.onAttributesInitialized();
            fqv38.onChildrenAdded();
            fqv fqv39 = fqv.checkOut();
            fqv39.setElementMap(fyy_02);
            fqv39.setHeight(1);
            fqv39.setPosition(frk_0.h);
            fqv39.setTexture(this.a.c("txListElement"));
            fqv39.setWidth(8);
            fqv39.setX(0);
            fqv39.setY(178);
            fby_26.addBasicElement(fqv39);
            fqv39.onAttributesInitialized();
            fqv39.onChildrenAdded();
            this.g(fby_26);
            this.h(fby_26);
            this.i(fby_26);
            this.j(fby_26);
            this.k(fby_26);
            this.l(fby_26);
            this.m(fby_26);
            fby_26.onChildrenAdded();
            fqj6.onChildrenAdded();
            this.n(fvE3);
            this.o(fvE3);
            this.p(fvE3);
        }
        return fvE3;
    }

    public fyo g(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(10);
        fqv2.setPosition(frk_0.m);
        fqv2.setTexture(this.a.c("txListElement"));
        fqv2.setWidth(8);
        fqv2.setX(0);
        fqv2.setY(188);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo h(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(8);
        fqv2.setPosition(frk_0.c);
        fqv2.setTexture(this.a.c("txListElement"));
        fqv2.setWidth(1);
        fqv2.setX(18);
        fqv2.setY(160);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo i(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(1);
        fqv2.setPosition(frk_0.i);
        fqv2.setTexture(this.a.c("txListElement"));
        fqv2.setWidth(1);
        fqv2.setX(18);
        fqv2.setY(178);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo j(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(10);
        fqv2.setPosition(frk_0.o);
        fqv2.setTexture(this.a.c("txListElement"));
        fqv2.setWidth(1);
        fqv2.setX(18);
        fqv2.setY(188);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo k(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(8);
        fqv2.setPosition(frk_0.e);
        fqv2.setTexture(this.a.c("txListElement"));
        fqv2.setWidth(8);
        fqv2.setX(28);
        fqv2.setY(160);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo l(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(1);
        fqv2.setPosition(frk_0.j);
        fqv2.setTexture(this.a.c("txListElement"));
        fqv2.setWidth(8);
        fqv2.setX(28);
        fqv2.setY(178);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo m(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(10);
        fqv2.setPosition(frk_0.q);
        fqv2.setTexture(this.a.c("txListElement"));
        fqv2.setWidth(8);
        fqv2.setX(28);
        fqv2.setY(188);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo n(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fvE fvE2 = (fvE)fyo2;
        fqj fqj2 = fvE2.getAppearance();
        fqj2.setElementMap(fyy_02);
        fqj2.setState("mouseHoverSelected");
        fyo2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        String string = "pmbListElementOverSelected";
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fby_22);
        }
        fby_22.setScaled(true);
        fqj2.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(8);
        fqv2.setPosition(frk_0.a);
        fqv2.setTexture(this.a.c("txListElement"));
        fqv2.setWidth(8);
        fqv2.setX(0);
        fqv2.setY(200);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fqv3.setHeight(8);
        fqv3.setPosition(frk_0.c);
        fqv3.setTexture(this.a.c("txListElement"));
        fqv3.setWidth(1);
        fqv3.setX(18);
        fqv3.setY(200);
        fby_22.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_02);
        fqv4.setHeight(8);
        fqv4.setPosition(frk_0.e);
        fqv4.setTexture(this.a.c("txListElement"));
        fqv4.setWidth(8);
        fqv4.setX(28);
        fqv4.setY(200);
        fby_22.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_02);
        fqv5.setHeight(1);
        fqv5.setPosition(frk_0.h);
        fqv5.setTexture(this.a.c("txListElement"));
        fqv5.setWidth(8);
        fqv5.setX(0);
        fqv5.setY(219);
        fby_22.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_02);
        fqv6.setHeight(1);
        fqv6.setPosition(frk_0.i);
        fqv6.setTexture(this.a.c("txListElement"));
        fqv6.setWidth(1);
        fqv6.setX(18);
        fqv6.setY(219);
        fby_22.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_02);
        fqv7.setHeight(1);
        fqv7.setPosition(frk_0.j);
        fqv7.setTexture(this.a.c("txListElement"));
        fqv7.setWidth(8);
        fqv7.setX(28);
        fqv7.setY(219);
        fby_22.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_02);
        fqv8.setHeight(10);
        fqv8.setPosition(frk_0.m);
        fqv8.setTexture(this.a.c("txListElement"));
        fqv8.setWidth(8);
        fqv8.setX(0);
        fqv8.setY(228);
        fby_22.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_02);
        fqv9.setHeight(10);
        fqv9.setPosition(frk_0.o);
        fqv9.setTexture(this.a.c("txListElement"));
        fqv9.setWidth(1);
        fqv9.setX(18);
        fqv9.setY(228);
        fby_22.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_02);
        fqv10.setHeight(10);
        fqv10.setPosition(frk_0.q);
        fqv10.setTexture(this.a.c("txListElement"));
        fqv10.setWidth(8);
        fqv10.setX(28);
        fqv10.setY(228);
        fby_22.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fby_22.onChildrenAdded();
        fqj2.onChildrenAdded();
        return fqj2;
    }

    public fyo o(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fvE fvE2 = (fvE)fyo2;
        fqj fqj2 = fvE2.getAppearance();
        fqj2.setElementMap(fyy_02);
        fqj2.setState("pressedSelected");
        fyo2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        String string = "pmbListElementPressedSelected";
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fby_22);
        }
        fby_22.setScaled(true);
        fqj2.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(8);
        fqv2.setPosition(frk_0.a);
        fqv2.setTexture(this.a.c("txListElement"));
        fqv2.setWidth(8);
        fqv2.setX(0);
        fqv2.setY(240);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fqv3.setHeight(8);
        fqv3.setPosition(frk_0.c);
        fqv3.setTexture(this.a.c("txListElement"));
        fqv3.setWidth(1);
        fqv3.setX(18);
        fqv3.setY(240);
        fby_22.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_02);
        fqv4.setHeight(8);
        fqv4.setPosition(frk_0.e);
        fqv4.setTexture(this.a.c("txListElement"));
        fqv4.setWidth(8);
        fqv4.setX(28);
        fqv4.setY(240);
        fby_22.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_02);
        fqv5.setHeight(1);
        fqv5.setPosition(frk_0.h);
        fqv5.setTexture(this.a.c("txListElement"));
        fqv5.setWidth(8);
        fqv5.setX(0);
        fqv5.setY(259);
        fby_22.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_02);
        fqv6.setHeight(1);
        fqv6.setPosition(frk_0.i);
        fqv6.setTexture(this.a.c("txListElement"));
        fqv6.setWidth(1);
        fqv6.setX(18);
        fqv6.setY(259);
        fby_22.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_02);
        fqv7.setHeight(1);
        fqv7.setPosition(frk_0.j);
        fqv7.setTexture(this.a.c("txListElement"));
        fqv7.setWidth(8);
        fqv7.setX(28);
        fqv7.setY(259);
        fby_22.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_02);
        fqv8.setHeight(10);
        fqv8.setPosition(frk_0.m);
        fqv8.setTexture(this.a.c("txListElement"));
        fqv8.setWidth(8);
        fqv8.setX(0);
        fqv8.setY(268);
        fby_22.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_02);
        fqv9.setHeight(10);
        fqv9.setPosition(frk_0.o);
        fqv9.setTexture(this.a.c("txListElement"));
        fqv9.setWidth(1);
        fqv9.setX(18);
        fqv9.setY(268);
        fby_22.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_02);
        fqv10.setHeight(10);
        fqv10.setPosition(frk_0.q);
        fqv10.setTexture(this.a.c("txListElement"));
        fqv10.setWidth(8);
        fqv10.setX(28);
        fqv10.setY(268);
        fby_22.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fby_22.onChildrenAdded();
        fqj2.onChildrenAdded();
        return fqj2;
    }

    public fyo p(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fvE fvE2 = (fvE)fyo2;
        fqj fqj2 = fvE2.getAppearance();
        fqj2.setElementMap(fyy_02);
        fqj2.setState("disabledSelected");
        fyo2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        String string = "pmbListElementDisabledSelected";
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fby_22);
        }
        fby_22.setScaled(true);
        fqj2.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(8);
        fqv2.setPosition(frk_0.a);
        fqv2.setTexture(this.a.c("txListElement"));
        fqv2.setWidth(8);
        fqv2.setX(0);
        fqv2.setY(280);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fqv3.setHeight(8);
        fqv3.setPosition(frk_0.c);
        fqv3.setTexture(this.a.c("txListElement"));
        fqv3.setWidth(1);
        fqv3.setX(18);
        fqv3.setY(280);
        fby_22.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_02);
        fqv4.setHeight(8);
        fqv4.setPosition(frk_0.e);
        fqv4.setTexture(this.a.c("txListElement"));
        fqv4.setWidth(8);
        fqv4.setX(28);
        fqv4.setY(280);
        fby_22.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_02);
        fqv5.setHeight(1);
        fqv5.setPosition(frk_0.h);
        fqv5.setTexture(this.a.c("txListElement"));
        fqv5.setWidth(8);
        fqv5.setX(0);
        fqv5.setY(299);
        fby_22.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_02);
        fqv6.setHeight(1);
        fqv6.setPosition(frk_0.i);
        fqv6.setTexture(this.a.c("txListElement"));
        fqv6.setWidth(1);
        fqv6.setX(18);
        fqv6.setY(299);
        fby_22.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_02);
        fqv7.setHeight(1);
        fqv7.setPosition(frk_0.j);
        fqv7.setTexture(this.a.c("txListElement"));
        fqv7.setWidth(8);
        fqv7.setX(28);
        fqv7.setY(299);
        fby_22.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_02);
        fqv8.setHeight(10);
        fqv8.setPosition(frk_0.m);
        fqv8.setTexture(this.a.c("txListElement"));
        fqv8.setWidth(8);
        fqv8.setX(0);
        fqv8.setY(308);
        fby_22.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_02);
        fqv9.setHeight(10);
        fqv9.setPosition(frk_0.o);
        fqv9.setTexture(this.a.c("txListElement"));
        fqv9.setWidth(1);
        fqv9.setX(18);
        fqv9.setY(308);
        fby_22.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_02);
        fqv10.setHeight(10);
        fqv10.setPosition(frk_0.q);
        fqv10.setTexture(this.a.c("txListElement"));
        fqv10.setWidth(8);
        fqv10.setX(28);
        fqv10.setY(308);
        fby_22.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fby_22.onChildrenAdded();
        fqj2.onChildrenAdded();
        return fqj2;
    }
}

