/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from dWk
 */
public class dwk_1
implements fyn_0 {
    private fyw_0 a;
    private Stack<fyy_0> b = new Stack();

    @Override
    public void a(fyy_0 fyy_02, fyw_0 fyw_02, fvE fvE2) {
        this.a = fyw_02;
        this.b.push(fyy_02);
        fyy_0 fyy_03 = this.b.peek();
        fvE fvE3 = fvE2;
        fqb_0 fqb_02 = (fqb_0)fvE3.getAppearance();
        fqb_02.setElementMap(fyy_03);
        fqb_02.setAlignment(frs_0.e);
        fqb_02.setState("default");
        fvE2.addBasicElement(fqb_02);
        fqb_02.onAttributesInitialized();
        fqn fqn2 = fqn.checkOut();
        fqn2.setRenderer(fpm_0.b().g().d("fontTitle12"));
        fqn2.setElementMap(fyy_03);
        fqb_02.addBasicElement(fqn2);
        fqn2.onAttributesInitialized();
        fqn2.onChildrenAdded();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_03);
        fqg_02.setColor(new fyr_0("defaultDarkColor"));
        fqb_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        String string = "radioButtonTabBackgroundDefault";
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fby_22);
        }
        fby_22.setScaled(true);
        fqb_02.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fqv2.setHeight(1);
        fqv2.setPosition(frk_0.i);
        fqv2.setTexture(this.a.c("themeDefault"));
        fqv2.setWidth(1);
        fqv2.setX(31);
        fqv2.setY(626);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fby_22.onChildrenAdded();
        String string2 = "radioButtonTabBorderDefault";
        fbc_1 fbc_12 = new fbc_1();
        fbc_12.onCheckOut();
        fbc_12.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fbc_12);
        }
        fqb_02.addBasicElement(fbc_12);
        fbc_12.onAttributesInitialized();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_03);
        fqv3.setHeight(2);
        fqv3.setPosition(frk_0.a);
        fqv3.setTexture(this.a.c("themeDefault"));
        fqv3.setWidth(2);
        fqv3.setX(27);
        fqv3.setY(622);
        fbc_12.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_03);
        fqv4.setHeight(2);
        fqv4.setPosition(frk_0.c);
        fqv4.setTexture(this.a.c("themeDefault"));
        fqv4.setWidth(1);
        fqv4.setX(31);
        fqv4.setY(622);
        fbc_12.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_03);
        fqv5.setFlipHorizontaly(true);
        fqv5.setHeight(2);
        fqv5.setPosition(frk_0.e);
        fqv5.setTexture(this.a.c("themeDefault"));
        fqv5.setWidth(2);
        fqv5.setX(27);
        fqv5.setY(622);
        fbc_12.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_03);
        fqv6.setHeight(2);
        fqv6.setPosition(frk_0.j);
        fqv6.setRotation(avg_1.b);
        fqv6.setTexture(this.a.c("themeDefault"));
        fqv6.setWidth(1);
        fqv6.setX(31);
        fqv6.setY(622);
        fbc_12.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_03);
        fqv7.setHeight(0);
        fqv7.setPosition(frk_0.q);
        fqv7.setTexture(this.a.c("themeDefault"));
        fqv7.setWidth(2);
        fqv7.setX(27);
        fqv7.setY(622);
        fbc_12.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_03);
        fqv8.setHeight(0);
        fqv8.setPosition(frk_0.o);
        fqv8.setTexture(this.a.c("themeDefault"));
        fqv8.setWidth(1);
        fqv8.setX(31);
        fqv8.setY(622);
        fbc_12.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_03);
        fqv9.setHeight(0);
        fqv9.setPosition(frk_0.m);
        fqv9.setTexture(this.a.c("themeDefault"));
        fqv9.setWidth(2);
        fqv9.setX(27);
        fqv9.setY(622);
        fbc_12.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_03);
        fqv10.setHeight(2);
        fqv10.setPosition(frk_0.h);
        fqv10.setRotation(avg_1.d);
        fqv10.setTexture(this.a.c("themeDefault"));
        fqv10.setWidth(1);
        fqv10.setX(31);
        fqv10.setY(622);
        fbc_12.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fbc_12.onChildrenAdded();
        fqb_02.onChildrenAdded();
        fvE fvE4 = fvE2;
        fqb_0 fqb_03 = (fqb_0)fvE4.getAppearance();
        fqb_03.setElementMap(fyy_03);
        fqb_03.setAlignment(frs_0.e);
        fqb_03.setState("mouseHover");
        fvE2.addBasicElement(fqb_03);
        fqb_03.onAttributesInitialized();
        fqn fqn3 = fqn.checkOut();
        fqn3.setRenderer(fpm_0.b().g().d("fontTitle12"));
        fqn3.setElementMap(fyy_03);
        fqb_03.addBasicElement(fqn3);
        fqn3.onAttributesInitialized();
        fqn3.onChildrenAdded();
        fqg_0 fqg_03 = fqg_0.checkOut();
        fqg_03.setElementMap(fyy_03);
        fqg_03.setColor(new fyr_0("defaultDarkColor"));
        fqb_03.addBasicElement(fqg_03);
        fqg_03.onAttributesInitialized();
        fqg_03.onChildrenAdded();
        String string3 = "radioButtonTabBackgroundOver";
        fby_2 fby_23 = fby_2.checkOut();
        fby_23.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fby_23);
        }
        fby_23.setScaled(true);
        fqb_03.addBasicElement(fby_23);
        fby_23.onAttributesInitialized();
        fqv fqv11 = fqv.checkOut();
        fqv11.setElementMap(fyy_03);
        fqv11.setHeight(1);
        fqv11.setPosition(frk_0.i);
        fqv11.setTexture(this.a.c("themeOver"));
        fqv11.setWidth(1);
        fqv11.setX(31);
        fqv11.setY(626);
        fby_23.addBasicElement(fqv11);
        fqv11.onAttributesInitialized();
        fqv11.onChildrenAdded();
        fby_23.onChildrenAdded();
        String string4 = "radioButtonTabBorderOver";
        fbc_1 fbc_13 = new fbc_1();
        fbc_13.onCheckOut();
        fbc_13.setElementMap(fyy_03);
        if (fyy_03 != null && string4 != null) {
            fyy_03.a(string4, fbc_13);
        }
        fqb_03.addBasicElement(fbc_13);
        fbc_13.onAttributesInitialized();
        fqv fqv12 = fqv.checkOut();
        fqv12.setElementMap(fyy_03);
        fqv12.setHeight(2);
        fqv12.setPosition(frk_0.a);
        fqv12.setTexture(this.a.c("themeOver"));
        fqv12.setWidth(2);
        fqv12.setX(27);
        fqv12.setY(622);
        fbc_13.addBasicElement(fqv12);
        fqv12.onAttributesInitialized();
        fqv12.onChildrenAdded();
        fqv fqv13 = fqv.checkOut();
        fqv13.setElementMap(fyy_03);
        fqv13.setHeight(2);
        fqv13.setPosition(frk_0.c);
        fqv13.setTexture(this.a.c("themeOver"));
        fqv13.setWidth(1);
        fqv13.setX(31);
        fqv13.setY(622);
        fbc_13.addBasicElement(fqv13);
        fqv13.onAttributesInitialized();
        fqv13.onChildrenAdded();
        fqv fqv14 = fqv.checkOut();
        fqv14.setElementMap(fyy_03);
        fqv14.setFlipHorizontaly(true);
        fqv14.setHeight(2);
        fqv14.setPosition(frk_0.e);
        fqv14.setTexture(this.a.c("themeOver"));
        fqv14.setWidth(2);
        fqv14.setX(27);
        fqv14.setY(622);
        fbc_13.addBasicElement(fqv14);
        fqv14.onAttributesInitialized();
        fqv14.onChildrenAdded();
        fqv fqv15 = fqv.checkOut();
        fqv15.setElementMap(fyy_03);
        fqv15.setHeight(2);
        fqv15.setPosition(frk_0.j);
        fqv15.setRotation(avg_1.b);
        fqv15.setTexture(this.a.c("themeOver"));
        fqv15.setWidth(1);
        fqv15.setX(31);
        fqv15.setY(622);
        fbc_13.addBasicElement(fqv15);
        fqv15.onAttributesInitialized();
        fqv15.onChildrenAdded();
        fqv fqv16 = fqv.checkOut();
        fqv16.setElementMap(fyy_03);
        fqv16.setHeight(0);
        fqv16.setPosition(frk_0.q);
        fqv16.setTexture(this.a.c("themeOver"));
        fqv16.setWidth(2);
        fqv16.setX(27);
        fqv16.setY(622);
        fbc_13.addBasicElement(fqv16);
        fqv16.onAttributesInitialized();
        fqv16.onChildrenAdded();
        fqv fqv17 = fqv.checkOut();
        fqv17.setElementMap(fyy_03);
        fqv17.setHeight(0);
        fqv17.setPosition(frk_0.o);
        fqv17.setTexture(this.a.c("themeOver"));
        fqv17.setWidth(1);
        fqv17.setX(31);
        fqv17.setY(622);
        fbc_13.addBasicElement(fqv17);
        fqv17.onAttributesInitialized();
        fqv17.onChildrenAdded();
        fqv fqv18 = fqv.checkOut();
        fqv18.setElementMap(fyy_03);
        fqv18.setHeight(0);
        fqv18.setPosition(frk_0.m);
        fqv18.setTexture(this.a.c("themeOver"));
        fqv18.setWidth(2);
        fqv18.setX(27);
        fqv18.setY(622);
        fbc_13.addBasicElement(fqv18);
        fqv18.onAttributesInitialized();
        fqv18.onChildrenAdded();
        fqv fqv19 = fqv.checkOut();
        fqv19.setElementMap(fyy_03);
        fqv19.setHeight(2);
        fqv19.setPosition(frk_0.h);
        fqv19.setRotation(avg_1.d);
        fqv19.setTexture(this.a.c("themeOver"));
        fqv19.setWidth(1);
        fqv19.setX(31);
        fqv19.setY(622);
        fbc_13.addBasicElement(fqv19);
        fqv19.onAttributesInitialized();
        fqv19.onChildrenAdded();
        fbc_13.onChildrenAdded();
        fqb_03.onChildrenAdded();
        fvE fvE5 = fvE2;
        fqb_0 fqb_04 = (fqb_0)fvE5.getAppearance();
        fqb_04.setElementMap(fyy_03);
        fqb_04.setAlignment(frs_0.e);
        fqb_04.setState("pressed");
        fvE2.addBasicElement(fqb_04);
        fqb_04.onAttributesInitialized();
        fqn fqn4 = fqn.checkOut();
        fqn4.setRenderer(fpm_0.b().g().d("fontTitle12"));
        fqn4.setElementMap(fyy_03);
        fqb_04.addBasicElement(fqn4);
        fqn4.onAttributesInitialized();
        fqn4.onChildrenAdded();
        fqg_0 fqg_04 = fqg_0.checkOut();
        fqg_04.setElementMap(fyy_03);
        fqg_04.setColor(new fyr_0("defaultDarkColor"));
        fqb_04.addBasicElement(fqg_04);
        fqg_04.onAttributesInitialized();
        fqg_04.onChildrenAdded();
        String string5 = "radioButtonTabBackgroundPressed";
        fby_2 fby_24 = fby_2.checkOut();
        fby_24.setElementMap(fyy_03);
        if (fyy_03 != null && string5 != null) {
            fyy_03.a(string5, fby_24);
        }
        fby_24.setScaled(true);
        fqb_04.addBasicElement(fby_24);
        fby_24.onAttributesInitialized();
        fqv fqv20 = fqv.checkOut();
        fqv20.setElementMap(fyy_03);
        fqv20.setHeight(1);
        fqv20.setPosition(frk_0.i);
        fqv20.setTexture(this.a.c("themeDefault"));
        fqv20.setWidth(1);
        fqv20.setX(31);
        fqv20.setY(626);
        fby_24.addBasicElement(fqv20);
        fqv20.onAttributesInitialized();
        fqv20.onChildrenAdded();
        fby_24.onChildrenAdded();
        String string6 = "radioButtonTabBorderPressed";
        fbc_1 fbc_14 = new fbc_1();
        fbc_14.onCheckOut();
        fbc_14.setElementMap(fyy_03);
        if (fyy_03 != null && string6 != null) {
            fyy_03.a(string6, fbc_14);
        }
        fqb_04.addBasicElement(fbc_14);
        fbc_14.onAttributesInitialized();
        fqv fqv21 = fqv.checkOut();
        fqv21.setElementMap(fyy_03);
        fqv21.setHeight(2);
        fqv21.setPosition(frk_0.a);
        fqv21.setTexture(this.a.c("themeDefault"));
        fqv21.setWidth(2);
        fqv21.setX(27);
        fqv21.setY(622);
        fbc_14.addBasicElement(fqv21);
        fqv21.onAttributesInitialized();
        fqv21.onChildrenAdded();
        fqv fqv22 = fqv.checkOut();
        fqv22.setElementMap(fyy_03);
        fqv22.setHeight(2);
        fqv22.setPosition(frk_0.c);
        fqv22.setTexture(this.a.c("themeDefault"));
        fqv22.setWidth(1);
        fqv22.setX(31);
        fqv22.setY(622);
        fbc_14.addBasicElement(fqv22);
        fqv22.onAttributesInitialized();
        fqv22.onChildrenAdded();
        fqv fqv23 = fqv.checkOut();
        fqv23.setElementMap(fyy_03);
        fqv23.setFlipHorizontaly(true);
        fqv23.setHeight(2);
        fqv23.setPosition(frk_0.e);
        fqv23.setTexture(this.a.c("themeDefault"));
        fqv23.setWidth(2);
        fqv23.setX(27);
        fqv23.setY(622);
        fbc_14.addBasicElement(fqv23);
        fqv23.onAttributesInitialized();
        fqv23.onChildrenAdded();
        fqv fqv24 = fqv.checkOut();
        fqv24.setElementMap(fyy_03);
        fqv24.setHeight(2);
        fqv24.setPosition(frk_0.j);
        fqv24.setRotation(avg_1.b);
        fqv24.setTexture(this.a.c("themeDefault"));
        fqv24.setWidth(1);
        fqv24.setX(31);
        fqv24.setY(622);
        fbc_14.addBasicElement(fqv24);
        fqv24.onAttributesInitialized();
        fqv24.onChildrenAdded();
        fqv fqv25 = fqv.checkOut();
        fqv25.setElementMap(fyy_03);
        fqv25.setHeight(0);
        fqv25.setPosition(frk_0.q);
        fqv25.setTexture(this.a.c("themeDefault"));
        fqv25.setWidth(2);
        fqv25.setX(27);
        fqv25.setY(622);
        fbc_14.addBasicElement(fqv25);
        fqv25.onAttributesInitialized();
        fqv25.onChildrenAdded();
        fqv fqv26 = fqv.checkOut();
        fqv26.setElementMap(fyy_03);
        fqv26.setHeight(0);
        fqv26.setPosition(frk_0.o);
        fqv26.setTexture(this.a.c("themeDefault"));
        fqv26.setWidth(1);
        fqv26.setX(31);
        fqv26.setY(622);
        fbc_14.addBasicElement(fqv26);
        fqv26.onAttributesInitialized();
        fqv26.onChildrenAdded();
        fqv fqv27 = fqv.checkOut();
        fqv27.setElementMap(fyy_03);
        fqv27.setHeight(0);
        fqv27.setPosition(frk_0.m);
        fqv27.setTexture(this.a.c("themeDefault"));
        fqv27.setWidth(2);
        fqv27.setX(27);
        fqv27.setY(622);
        fbc_14.addBasicElement(fqv27);
        fqv27.onAttributesInitialized();
        fqv27.onChildrenAdded();
        fqv fqv28 = fqv.checkOut();
        fqv28.setElementMap(fyy_03);
        fqv28.setHeight(2);
        fqv28.setPosition(frk_0.h);
        fqv28.setRotation(avg_1.d);
        fqv28.setTexture(this.a.c("themeDefault"));
        fqv28.setWidth(1);
        fqv28.setX(31);
        fqv28.setY(622);
        fbc_14.addBasicElement(fqv28);
        fqv28.onAttributesInitialized();
        fqv28.onChildrenAdded();
        fbc_14.onChildrenAdded();
        fqb_04.onChildrenAdded();
        fvE fvE6 = fvE2;
        fqb_0 fqb_05 = (fqb_0)fvE6.getAppearance();
        fqb_05.setElementMap(fyy_03);
        fqb_05.setAlignment(frs_0.e);
        fqb_05.setState("selected");
        fvE2.addBasicElement(fqb_05);
        fqb_05.onAttributesInitialized();
        fqn fqn5 = fqn.checkOut();
        fqn5.setRenderer(fpm_0.b().g().d("fontTitle12"));
        fqn5.setElementMap(fyy_03);
        fqb_05.addBasicElement(fqn5);
        fqn5.onAttributesInitialized();
        fqn5.onChildrenAdded();
        fqg_0 fqg_05 = fqg_0.checkOut();
        fqg_05.setElementMap(fyy_03);
        fqg_05.setColor(new fyr_0("defaultDarkColor"));
        fqb_05.addBasicElement(fqg_05);
        fqg_05.onAttributesInitialized();
        fqg_05.onChildrenAdded();
        String string7 = "radioButtonTabBackgroundDefaultSelected";
        fby_2 fby_25 = fby_2.checkOut();
        fby_25.setElementMap(fyy_03);
        if (fyy_03 != null && string7 != null) {
            fyy_03.a(string7, fby_25);
        }
        fby_25.setScaled(true);
        fqb_05.addBasicElement(fby_25);
        fby_25.onAttributesInitialized();
        fqv fqv29 = fqv.checkOut();
        fqv29.setElementMap(fyy_03);
        fqv29.setHeight(1);
        fqv29.setPosition(frk_0.i);
        fqv29.setTexture(this.a.c("themePressed"));
        fqv29.setWidth(1);
        fqv29.setX(31);
        fqv29.setY(626);
        fby_25.addBasicElement(fqv29);
        fqv29.onAttributesInitialized();
        fqv29.onChildrenAdded();
        fby_25.onChildrenAdded();
        String string8 = "radioButtonTabBorderDefaultSelected";
        fbc_1 fbc_15 = new fbc_1();
        fbc_15.onCheckOut();
        fbc_15.setElementMap(fyy_03);
        if (fyy_03 != null && string8 != null) {
            fyy_03.a(string8, fbc_15);
        }
        fqb_05.addBasicElement(fbc_15);
        fbc_15.onAttributesInitialized();
        fqv fqv30 = fqv.checkOut();
        fqv30.setElementMap(fyy_03);
        fqv30.setHeight(2);
        fqv30.setPosition(frk_0.a);
        fqv30.setTexture(this.a.c("themePressed"));
        fqv30.setWidth(2);
        fqv30.setX(27);
        fqv30.setY(622);
        fbc_15.addBasicElement(fqv30);
        fqv30.onAttributesInitialized();
        fqv30.onChildrenAdded();
        fqv fqv31 = fqv.checkOut();
        fqv31.setElementMap(fyy_03);
        fqv31.setHeight(2);
        fqv31.setPosition(frk_0.c);
        fqv31.setTexture(this.a.c("themePressed"));
        fqv31.setWidth(1);
        fqv31.setX(31);
        fqv31.setY(622);
        fbc_15.addBasicElement(fqv31);
        fqv31.onAttributesInitialized();
        fqv31.onChildrenAdded();
        fqv fqv32 = fqv.checkOut();
        fqv32.setElementMap(fyy_03);
        fqv32.setFlipHorizontaly(true);
        fqv32.setHeight(2);
        fqv32.setPosition(frk_0.e);
        fqv32.setTexture(this.a.c("themePressed"));
        fqv32.setWidth(2);
        fqv32.setX(27);
        fqv32.setY(622);
        fbc_15.addBasicElement(fqv32);
        fqv32.onAttributesInitialized();
        fqv32.onChildrenAdded();
        this.a(fbc_15);
        this.b(fbc_15);
        this.c(fbc_15);
        this.d(fbc_15);
        this.e(fbc_15);
        fbc_15.onChildrenAdded();
        fqb_05.onChildrenAdded();
        this.f(fvE2);
        this.g(fvE2);
    }

    public fyo a(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(2);
        fqv2.setPosition(frk_0.j);
        fqv2.setRotation(avg_1.b);
        fqv2.setTexture(this.a.c("themePressed"));
        fqv2.setWidth(1);
        fqv2.setX(31);
        fqv2.setY(622);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo b(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(0);
        fqv2.setPosition(frk_0.q);
        fqv2.setTexture(this.a.c("themePressed"));
        fqv2.setWidth(2);
        fqv2.setX(27);
        fqv2.setY(622);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo c(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(0);
        fqv2.setPosition(frk_0.o);
        fqv2.setTexture(this.a.c("themePressed"));
        fqv2.setWidth(1);
        fqv2.setX(31);
        fqv2.setY(622);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo d(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(0);
        fqv2.setPosition(frk_0.m);
        fqv2.setTexture(this.a.c("themePressed"));
        fqv2.setWidth(2);
        fqv2.setX(27);
        fqv2.setY(622);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo e(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(2);
        fqv2.setPosition(frk_0.h);
        fqv2.setRotation(avg_1.d);
        fqv2.setTexture(this.a.c("themePressed"));
        fqv2.setWidth(1);
        fqv2.setX(31);
        fqv2.setY(622);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo f(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fvE fvE2 = (fvE)fyo2;
        fqb_0 fqb_02 = (fqb_0)fvE2.getAppearance();
        fqb_02.setElementMap(fyy_02);
        fqb_02.setAlignment(frs_0.e);
        fqb_02.setState("mouseHoverSelected");
        fyo2.addBasicElement(fqb_02);
        fqb_02.onAttributesInitialized();
        fqn fqn2 = fqn.checkOut();
        fqn2.setRenderer(fpm_0.b().g().d("fontTitle12"));
        fqn2.setElementMap(fyy_02);
        fqb_02.addBasicElement(fqn2);
        fqn2.onAttributesInitialized();
        fqn2.onChildrenAdded();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_02);
        fqg_02.setColor(new fyr_0("defaultDarkColor"));
        fqb_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        String string = "radioButtonTabBackgroundOverSelected";
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fby_22);
        }
        fby_22.setScaled(true);
        fqb_02.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(1);
        fqv2.setPosition(frk_0.i);
        fqv2.setTexture(this.a.c("themePressed"));
        fqv2.setWidth(1);
        fqv2.setX(31);
        fqv2.setY(626);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fby_22.onChildrenAdded();
        String string2 = "radioButtonTabBorderOverSelected";
        fbc_1 fbc_12 = new fbc_1();
        fbc_12.onCheckOut();
        fbc_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fbc_12);
        }
        fqb_02.addBasicElement(fbc_12);
        fbc_12.onAttributesInitialized();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fqv3.setHeight(2);
        fqv3.setPosition(frk_0.a);
        fqv3.setTexture(this.a.c("themePressed"));
        fqv3.setWidth(2);
        fqv3.setX(27);
        fqv3.setY(622);
        fbc_12.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_02);
        fqv4.setHeight(2);
        fqv4.setPosition(frk_0.c);
        fqv4.setTexture(this.a.c("themePressed"));
        fqv4.setWidth(1);
        fqv4.setX(31);
        fqv4.setY(622);
        fbc_12.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_02);
        fqv5.setFlipHorizontaly(true);
        fqv5.setHeight(2);
        fqv5.setPosition(frk_0.e);
        fqv5.setTexture(this.a.c("themePressed"));
        fqv5.setWidth(2);
        fqv5.setX(27);
        fqv5.setY(622);
        fbc_12.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_02);
        fqv6.setHeight(2);
        fqv6.setPosition(frk_0.j);
        fqv6.setRotation(avg_1.b);
        fqv6.setTexture(this.a.c("themePressed"));
        fqv6.setWidth(1);
        fqv6.setX(31);
        fqv6.setY(622);
        fbc_12.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_02);
        fqv7.setHeight(0);
        fqv7.setPosition(frk_0.q);
        fqv7.setTexture(this.a.c("themePressed"));
        fqv7.setWidth(2);
        fqv7.setX(27);
        fqv7.setY(622);
        fbc_12.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_02);
        fqv8.setHeight(0);
        fqv8.setPosition(frk_0.o);
        fqv8.setTexture(this.a.c("themePressed"));
        fqv8.setWidth(1);
        fqv8.setX(31);
        fqv8.setY(622);
        fbc_12.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_02);
        fqv9.setHeight(0);
        fqv9.setPosition(frk_0.m);
        fqv9.setTexture(this.a.c("themePressed"));
        fqv9.setWidth(2);
        fqv9.setX(27);
        fqv9.setY(622);
        fbc_12.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_02);
        fqv10.setHeight(2);
        fqv10.setPosition(frk_0.h);
        fqv10.setRotation(avg_1.d);
        fqv10.setTexture(this.a.c("themePressed"));
        fqv10.setWidth(1);
        fqv10.setX(31);
        fqv10.setY(622);
        fbc_12.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fbc_12.onChildrenAdded();
        fqb_02.onChildrenAdded();
        return fqb_02;
    }

    public fyo g(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fvE fvE2 = (fvE)fyo2;
        fqb_0 fqb_02 = (fqb_0)fvE2.getAppearance();
        fqb_02.setElementMap(fyy_02);
        fqb_02.setAlignment(frs_0.e);
        fqb_02.setState("pressedSelected");
        fyo2.addBasicElement(fqb_02);
        fqb_02.onAttributesInitialized();
        fqn fqn2 = fqn.checkOut();
        fqn2.setRenderer(fpm_0.b().g().d("fontTitle12"));
        fqn2.setElementMap(fyy_02);
        fqb_02.addBasicElement(fqn2);
        fqn2.onAttributesInitialized();
        fqn2.onChildrenAdded();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_02);
        fqg_02.setColor(new fyr_0("defaultDarkColor"));
        fqb_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        String string = "radioButtonTabBackgroundPressedSelected";
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_02);
        if (fyy_02 != null && string != null) {
            fyy_02.a(string, fby_22);
        }
        fby_22.setScaled(true);
        fqb_02.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(1);
        fqv2.setPosition(frk_0.i);
        fqv2.setTexture(this.a.c("themePressed"));
        fqv2.setWidth(1);
        fqv2.setX(31);
        fqv2.setY(626);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fby_22.onChildrenAdded();
        String string2 = "radioButtonTabBorderPressedSelected";
        fbc_1 fbc_12 = new fbc_1();
        fbc_12.onCheckOut();
        fbc_12.setElementMap(fyy_02);
        if (fyy_02 != null && string2 != null) {
            fyy_02.a(string2, fbc_12);
        }
        fqb_02.addBasicElement(fbc_12);
        fbc_12.onAttributesInitialized();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_02);
        fqv3.setHeight(2);
        fqv3.setPosition(frk_0.a);
        fqv3.setTexture(this.a.c("themePressed"));
        fqv3.setWidth(2);
        fqv3.setX(27);
        fqv3.setY(622);
        fbc_12.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_02);
        fqv4.setHeight(2);
        fqv4.setPosition(frk_0.c);
        fqv4.setTexture(this.a.c("themePressed"));
        fqv4.setWidth(1);
        fqv4.setX(31);
        fqv4.setY(622);
        fbc_12.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_02);
        fqv5.setFlipHorizontaly(true);
        fqv5.setHeight(2);
        fqv5.setPosition(frk_0.e);
        fqv5.setTexture(this.a.c("themePressed"));
        fqv5.setWidth(2);
        fqv5.setX(27);
        fqv5.setY(622);
        fbc_12.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_02);
        fqv6.setHeight(2);
        fqv6.setPosition(frk_0.j);
        fqv6.setRotation(avg_1.b);
        fqv6.setTexture(this.a.c("themePressed"));
        fqv6.setWidth(1);
        fqv6.setX(31);
        fqv6.setY(622);
        fbc_12.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_02);
        fqv7.setHeight(0);
        fqv7.setPosition(frk_0.q);
        fqv7.setTexture(this.a.c("themePressed"));
        fqv7.setWidth(2);
        fqv7.setX(27);
        fqv7.setY(622);
        fbc_12.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_02);
        fqv8.setHeight(0);
        fqv8.setPosition(frk_0.o);
        fqv8.setTexture(this.a.c("themePressed"));
        fqv8.setWidth(1);
        fqv8.setX(31);
        fqv8.setY(622);
        fbc_12.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_02);
        fqv9.setHeight(0);
        fqv9.setPosition(frk_0.m);
        fqv9.setTexture(this.a.c("themePressed"));
        fqv9.setWidth(2);
        fqv9.setX(27);
        fqv9.setY(622);
        fbc_12.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_02);
        fqv10.setHeight(2);
        fqv10.setPosition(frk_0.h);
        fqv10.setRotation(avg_1.d);
        fqv10.setTexture(this.a.c("themePressed"));
        fqv10.setWidth(1);
        fqv10.setX(31);
        fqv10.setY(622);
        fbc_12.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fbc_12.onChildrenAdded();
        fqb_02.onChildrenAdded();
        return fqb_02;
    }
}

