/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from dYk
 */
public class dyk_0
implements fyn_0 {
    private fyw_0 a;
    private Stack<fyy_0> b = new Stack();

    @Override
    public void a(fyy_0 fyy_02, fyw_0 fyw_02, fvE fvE2) {
        fyb_0 fyb_02;
        this.a = fyw_02;
        this.b.push(fyy_02);
        fyy_0 fyy_03 = this.b.peek();
        fvE fvE3 = fvE2;
        fqj fqj2 = fvE3.getAppearance();
        fqj2.setElementMap(fyy_03);
        fvE2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fbc_1 fbc_12 = new fbc_1();
        fbc_12.onCheckOut();
        fbc_12.setElementMap(fyy_03);
        fbc_12.setEnabled(true);
        fqj2.addBasicElement(fbc_12);
        fbc_12.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fqv2.setHeight(2);
        fqv2.setPosition(frk_0.a);
        fqv2.setTexture(this.a.c("themeSimple"));
        fqv2.setWidth(3);
        fqv2.setX(24);
        fqv2.setY(176);
        fbc_12.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_03);
        fqv3.setHeight(2);
        fqv3.setPosition(frk_0.c);
        fqv3.setTexture(this.a.c("themeSimple"));
        fqv3.setWidth(1);
        fqv3.setX(30);
        fqv3.setY(176);
        fbc_12.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_03);
        fqv4.setFlipHorizontaly(true);
        fqv4.setHeight(2);
        fqv4.setPosition(frk_0.e);
        fqv4.setTexture(this.a.c("themeSimple"));
        fqv4.setWidth(3);
        fqv4.setX(24);
        fqv4.setY(176);
        fbc_12.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_03);
        fqv5.setHeight(1);
        fqv5.setPosition(frk_0.h);
        fqv5.setTexture(this.a.c("themeSimple"));
        fqv5.setWidth(3);
        fqv5.setX(24);
        fqv5.setY(179);
        fbc_12.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_03);
        fqv6.setHeight(1);
        fqv6.setPosition(frk_0.i);
        fqv6.setTexture(this.a.c("themeSimple"));
        fqv6.setWidth(1);
        fqv6.setX(30);
        fqv6.setY(181);
        fbc_12.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_03);
        fqv7.setFlipHorizontaly(true);
        fqv7.setHeight(1);
        fqv7.setPosition(frk_0.j);
        fqv7.setTexture(this.a.c("themeSimple"));
        fqv7.setWidth(3);
        fqv7.setX(24);
        fqv7.setY(179);
        fbc_12.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_03);
        fqv8.setFlipVerticaly(true);
        fqv8.setHeight(2);
        fqv8.setPosition(frk_0.m);
        fqv8.setTexture(this.a.c("themeSimple"));
        fqv8.setWidth(3);
        fqv8.setX(24);
        fqv8.setY(176);
        fbc_12.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_03);
        fqv9.setFlipVerticaly(true);
        fqv9.setHeight(2);
        fqv9.setPosition(frk_0.o);
        fqv9.setTexture(this.a.c("themeSimple"));
        fqv9.setWidth(1);
        fqv9.setX(30);
        fqv9.setY(176);
        fbc_12.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_03);
        fqv10.setFlipHorizontaly(true);
        fqv10.setFlipVerticaly(true);
        fqv10.setHeight(2);
        fqv10.setPosition(frk_0.q);
        fqv10.setTexture(this.a.c("themeSimple"));
        fqv10.setWidth(3);
        fqv10.setX(24);
        fqv10.setY(176);
        fbc_12.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fbc_12.onChildrenAdded();
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_03);
        fby_22.setEnabled(true);
        fby_22.setScaled(true);
        fqj2.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv11 = fqv.checkOut();
        fqv11.setElementMap(fyy_03);
        fqv11.setHeight(1);
        fqv11.setPosition(frk_0.i);
        fqv11.setTexture(this.a.c("themeSimple"));
        fqv11.setWidth(1);
        fqv11.setX(30);
        fqv11.setY(181);
        fby_22.addBasicElement(fqv11);
        fqv11.onAttributesInitialized();
        fqv11.onChildrenAdded();
        fby_22.onChildrenAdded();
        fvE fvE4 = fqj2.getParentOfType(fvE.class);
        fvE fvE5 = fvE4.getWidgetByThemeElementName("horizontalButton", false);
        if (fvE5 != null) {
            fyb_02 = fvE5;
            fqd_0 fqd_02 = (fqd_0)((fvE)fyb_02).getAppearance();
            fqd_02.setElementMap(fyy_03);
            fqd_02.setState("default");
            fvE5.addBasicElement(fqd_02);
            fqd_02.onAttributesInitialized();
            fqv fqv12 = fqv.checkOut();
            fqv12.setElementMap(fyy_03);
            fqv12.setHeight(20);
            fqv12.setPosition(frk_0.i);
            fqv12.setTexture(this.a.c("themeDefault"));
            fqv12.setWidth(20);
            fqv12.setX(486);
            fqv12.setY(559);
            fqd_02.addBasicElement(fqv12);
            fqv12.onAttributesInitialized();
            fqv12.onChildrenAdded();
            fqd_02.onChildrenAdded();
            fvE fvE6 = fvE5;
            fqd_0 fqd_03 = (fqd_0)fvE6.getAppearance();
            fqd_03.setElementMap(fyy_03);
            fqd_03.setState("mouseHover");
            fvE5.addBasicElement(fqd_03);
            fqd_03.onAttributesInitialized();
            fqv fqv13 = fqv.checkOut();
            fqv13.setElementMap(fyy_03);
            fqv13.setHeight(20);
            fqv13.setPosition(frk_0.i);
            fqv13.setTexture(this.a.c("themeOver"));
            fqv13.setWidth(20);
            fqv13.setX(486);
            fqv13.setY(559);
            fqd_03.addBasicElement(fqv13);
            fqv13.onAttributesInitialized();
            fqv13.onChildrenAdded();
            fqd_03.onChildrenAdded();
            fvE fvE7 = fvE5;
            fqd_0 fqd_04 = (fqd_0)fvE7.getAppearance();
            fqd_04.setElementMap(fyy_03);
            fqd_04.setState("pressed");
            fvE5.addBasicElement(fqd_04);
            fqd_04.onAttributesInitialized();
            fqv fqv14 = fqv.checkOut();
            fqv14.setElementMap(fyy_03);
            fqv14.setHeight(20);
            fqv14.setPosition(frk_0.i);
            fqv14.setTexture(this.a.c("themePressed"));
            fqv14.setWidth(20);
            fqv14.setX(486);
            fqv14.setY(559);
            fqd_04.addBasicElement(fqv14);
            fqv14.onAttributesInitialized();
            fqv14.onChildrenAdded();
            fqd_04.onChildrenAdded();
        }
        fyb_02 = fqv.checkOut();
        fyb_02.setElementMap(fyy_03);
        ((fqv)fyb_02).setHeight(12);
        ((fqv)fyb_02).setPosition(frk_0.i);
        ((fqv)fyb_02).setTexture(this.a.c("themeSimple2"));
        ((fqv)fyb_02).setWidth(1);
        ((fqv)fyb_02).setX(299);
        ((fqv)fyb_02).setY(254);
        fqj2.addBasicElement(fyb_02);
        fyb_02.onAttributesInitialized();
        fyb_02.onChildrenAdded();
        fqj2.onChildrenAdded();
    }
}

