/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from eaD
 */
public class ead_1
implements fyn_0 {
    private fyw_0 a;
    private Stack<fyy_0> b = new Stack();

    @Override
    public void a(fyy_0 fyy_02, fyw_0 fyw_02, fvE fvE2) {
        fbm_2 fbm_22;
        fqd_0 fqd_02;
        fyb_0 fyb_02;
        fyb_0 fyb_03;
        fyb_0 fyb_04;
        fyb_0 fyb_05;
        fyg_0 fyg_02;
        fyb_0 fyb_06;
        fyb_0 fyb_07;
        fyb_0 fyb_08;
        fvE fvE3;
        fyb_0 fyb_09;
        this.a = fyw_02;
        this.b.push(fyy_02);
        fyy_0 fyy_03 = this.b.peek();
        fvE fvE4 = fvE2;
        fvE fvE5 = fvE2;
        fqj fqj2 = fvE5.getAppearance();
        fqj2.setElementMap(fyy_03);
        fvE2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fvE fvE6 = fqj2.getParentOfType(fvE.class);
        fvE fvE7 = fvE6.getWidgetByThemeElementName("verticalIncreaseButton", false);
        if (fvE7 != null) {
            fyb_09 = new fqo_0();
            ((fql_0)fyb_09).onCheckOut();
            fyb_09.setElementMap(fyy_03);
            ((fql_0)fyb_09).setInsets(new Insets(3, 0, 3, 0));
            fvE7.addBasicElement(fyb_09);
            fyb_09.onAttributesInitialized();
            fyb_09.onChildrenAdded();
            fvE3 = fvE7;
            fyb_08 = (fqd_0)fvE3.getAppearance();
            fyb_08.setElementMap(fyy_03);
            ((fqh_0)fyb_08).setAlignment(frs_0.e);
            ((fqj)fyb_08).setState("default");
            fvE7.addBasicElement(fyb_08);
            fyb_08.onAttributesInitialized();
            fyb_07 = fqv.checkOut();
            fyb_07.setElementMap(fyy_03);
            ((fqv)fyb_07).setHeight(18);
            ((fqv)fyb_07).setPosition(frk_0.i);
            ((fqv)fyb_07).setRotation(avg_1.b);
            ((fqv)fyb_07).setTexture(this.a.c("themeDefault"));
            ((fqv)fyb_07).setWidth(16);
            ((fqv)fyb_07).setX(281);
            ((fqv)fyb_07).setY(60);
            fyb_08.addBasicElement(fyb_07);
            fyb_07.onAttributesInitialized();
            fyb_07.onChildrenAdded();
            fyb_08.onChildrenAdded();
            fyb_06 = fvE7;
            fyg_02 = (fqd_0)((fvE)fyb_06).getAppearance();
            fyg_02.setElementMap(fyy_03);
            ((fqh_0)fyg_02).setAlignment(frs_0.e);
            ((fqj)fyg_02).setState("mouseHover");
            fvE7.addBasicElement(fyg_02);
            fyg_02.onAttributesInitialized();
            fyb_05 = fqv.checkOut();
            fyb_05.setElementMap(fyy_03);
            ((fqv)fyb_05).setHeight(18);
            ((fqv)fyb_05).setPosition(frk_0.i);
            ((fqv)fyb_05).setRotation(avg_1.b);
            ((fqv)fyb_05).setTexture(this.a.c("themeOver"));
            ((fqv)fyb_05).setWidth(16);
            ((fqv)fyb_05).setX(281);
            ((fqv)fyb_05).setY(60);
            fyg_02.addBasicElement(fyb_05);
            fyb_05.onAttributesInitialized();
            fyb_05.onChildrenAdded();
            fyg_02.onChildrenAdded();
            fyb_04 = fvE7;
            fyb_03 = (fqd_0)((fvE)fyb_04).getAppearance();
            fyb_03.setElementMap(fyy_03);
            ((fqh_0)fyb_03).setAlignment(frs_0.e);
            ((fqj)fyb_03).setState("pressed");
            fvE7.addBasicElement(fyb_03);
            fyb_03.onAttributesInitialized();
            fyb_02 = fqv.checkOut();
            fyb_02.setElementMap(fyy_03);
            ((fqv)fyb_02).setHeight(18);
            ((fqv)fyb_02).setPosition(frk_0.i);
            ((fqv)fyb_02).setRotation(avg_1.b);
            ((fqv)fyb_02).setTexture(this.a.c("themePressed"));
            ((fqv)fyb_02).setWidth(16);
            ((fqv)fyb_02).setX(281);
            ((fqv)fyb_02).setY(60);
            fyb_03.addBasicElement(fyb_02);
            fyb_02.onAttributesInitialized();
            fyb_02.onChildrenAdded();
            fyb_03.onChildrenAdded();
        }
        if ((fvE3 = ((fvE)(fyb_09 = fqj2.getParentOfType(fvE.class))).getWidgetByThemeElementName("verticalDecreaseButton", false)) != null) {
            fyb_08 = new fqo_0();
            ((fql_0)fyb_08).onCheckOut();
            fyb_08.setElementMap(fyy_03);
            ((fql_0)fyb_08).setInsets(new Insets(3, 0, 3, 0));
            fvE3.addBasicElement(fyb_08);
            fyb_08.onAttributesInitialized();
            fyb_08.onChildrenAdded();
            fyb_07 = fvE3;
            fyb_06 = (fqd_0)((fvE)fyb_07).getAppearance();
            fyb_06.setElementMap(fyy_03);
            ((fqh_0)fyb_06).setAlignment(frs_0.e);
            ((fqj)fyb_06).setState("default");
            fvE3.addBasicElement(fyb_06);
            fyb_06.onAttributesInitialized();
            fyg_02 = fqv.checkOut();
            fyg_02.setElementMap(fyy_03);
            ((fqv)fyg_02).setHeight(18);
            ((fqv)fyg_02).setPosition(frk_0.i);
            ((fqv)fyg_02).setRotation(avg_1.d);
            ((fqv)fyg_02).setTexture(this.a.c("themeDefault"));
            ((fqv)fyg_02).setWidth(16);
            ((fqv)fyg_02).setX(281);
            ((fqv)fyg_02).setY(60);
            fyb_06.addBasicElement(fyg_02);
            fyg_02.onAttributesInitialized();
            fyg_02.onChildrenAdded();
            fyb_06.onChildrenAdded();
            fyb_05 = fvE3;
            fyb_04 = (fqd_0)((fvE)fyb_05).getAppearance();
            fyb_04.setElementMap(fyy_03);
            ((fqh_0)fyb_04).setAlignment(frs_0.e);
            ((fqj)fyb_04).setState("mouseHover");
            fvE3.addBasicElement(fyb_04);
            fyb_04.onAttributesInitialized();
            fyb_03 = fqv.checkOut();
            fyb_03.setElementMap(fyy_03);
            ((fqv)fyb_03).setHeight(18);
            ((fqv)fyb_03).setPosition(frk_0.i);
            ((fqv)fyb_03).setRotation(avg_1.d);
            ((fqv)fyb_03).setTexture(this.a.c("themeOver"));
            ((fqv)fyb_03).setWidth(16);
            ((fqv)fyb_03).setX(281);
            ((fqv)fyb_03).setY(60);
            fyb_04.addBasicElement(fyb_03);
            fyb_03.onAttributesInitialized();
            fyb_03.onChildrenAdded();
            fyb_04.onChildrenAdded();
            fyb_02 = fvE3;
            fqd_02 = (fqd_0)((fvE)fyb_02).getAppearance();
            fqd_02.setElementMap(fyy_03);
            fqd_02.setAlignment(frs_0.e);
            fqd_02.setState("pressed");
            fvE3.addBasicElement(fqd_02);
            fqd_02.onAttributesInitialized();
            fbm_22 = fqv.checkOut();
            fbm_22.setElementMap(fyy_03);
            ((fqv)fbm_22).setHeight(18);
            ((fqv)fbm_22).setPosition(frk_0.i);
            ((fqv)fbm_22).setRotation(avg_1.d);
            ((fqv)fbm_22).setTexture(this.a.c("themePressed"));
            ((fqv)fbm_22).setWidth(16);
            ((fqv)fbm_22).setX(281);
            ((fqv)fbm_22).setY(60);
            fqd_02.addBasicElement(fbm_22);
            fbm_22.onAttributesInitialized();
            fbm_22.onChildrenAdded();
            fqd_02.onChildrenAdded();
        }
        if ((fyb_07 = ((fvE)(fyb_08 = fqj2.getParentOfType(fvE.class))).getWidgetByThemeElementName("verticalSlider", false)) != null) {
            fyb_06 = fyb_07;
            fyg_02 = ((fvE)fyb_06).getAppearance();
            fyg_02.setElementMap(fyy_03);
            fyb_07.addBasicElement(fyg_02);
            fyg_02.onAttributesInitialized();
            fyb_05 = new fqo_0();
            ((fql_0)fyb_05).onCheckOut();
            fyb_05.setElementMap(fyy_03);
            ((fql_0)fyb_05).setInsets(new Insets(0, 4, 0, 4));
            fyg_02.addBasicElement(fyb_05);
            fyb_05.onAttributesInitialized();
            fyb_05.onChildrenAdded();
            fyb_04 = fyg_02.getParentOfType(fvE.class);
            fyb_03 = ((fvE)fyb_04).getWidgetByThemeElementName("verticalButton", false);
            if (fyb_03 != null) {
                fyb_02 = fyb_03;
                fqd_02 = (fqd_0)((fvE)fyb_02).getAppearance();
                fqd_02.setElementMap(fyy_03);
                fqd_02.setState("default");
                fyb_03.addBasicElement(fqd_02);
                fqd_02.onAttributesInitialized();
                fbm_22 = new fbc_1();
                ((fbc_1)fbm_22).onCheckOut();
                fbm_22.setElementMap(fyy_03);
                fqd_02.addBasicElement(fbm_22);
                fbm_22.onAttributesInitialized();
                fqv fqv2 = fqv.checkOut();
                fqv2.setElementMap(fyy_03);
                fqv2.setHeight(4);
                fqv2.setPosition(frk_0.a);
                fqv2.setTexture(this.a.c("themeDefault"));
                fqv2.setWidth(1);
                fqv2.setX(105);
                fqv2.setY(1);
                fbm_22.addBasicElement(fqv2);
                fqv2.onAttributesInitialized();
                fqv2.onChildrenAdded();
                fqv fqv3 = fqv.checkOut();
                fqv3.setElementMap(fyy_03);
                fqv3.setHeight(4);
                fqv3.setPosition(frk_0.c);
                fqv3.setTexture(this.a.c("themeDefault"));
                fqv3.setWidth(11);
                fqv3.setX(106);
                fqv3.setY(1);
                fbm_22.addBasicElement(fqv3);
                fqv3.onAttributesInitialized();
                fqv3.onChildrenAdded();
                fqv fqv4 = fqv.checkOut();
                fqv4.setElementMap(fyy_03);
                fqv4.setHeight(4);
                fqv4.setPosition(frk_0.e);
                fqv4.setTexture(this.a.c("themeDefault"));
                fqv4.setWidth(1);
                fqv4.setX(117);
                fqv4.setY(1);
                fbm_22.addBasicElement(fqv4);
                fqv4.onAttributesInitialized();
                fqv4.onChildrenAdded();
                fqv fqv5 = fqv.checkOut();
                fqv5.setElementMap(fyy_03);
                fqv5.setHeight(13);
                fqv5.setPosition(frk_0.j);
                fqv5.setTexture(this.a.c("themeDefault"));
                fqv5.setWidth(1);
                fqv5.setX(105);
                fqv5.setY(5);
                fbm_22.addBasicElement(fqv5);
                fqv5.onAttributesInitialized();
                fqv5.onChildrenAdded();
                fqv fqv6 = fqv.checkOut();
                fqv6.setElementMap(fyy_03);
                fqv6.setHeight(4);
                fqv6.setPosition(frk_0.q);
                fqv6.setTexture(this.a.c("themeDefault"));
                fqv6.setWidth(1);
                fqv6.setX(105);
                fqv6.setY(17);
                fbm_22.addBasicElement(fqv6);
                fqv6.onAttributesInitialized();
                fqv6.onChildrenAdded();
                fqv fqv7 = fqv.checkOut();
                fqv7.setElementMap(fyy_03);
                fqv7.setHeight(4);
                fqv7.setPosition(frk_0.o);
                fqv7.setTexture(this.a.c("themeDefault"));
                fqv7.setWidth(11);
                fqv7.setX(106);
                fqv7.setY(18);
                fbm_22.addBasicElement(fqv7);
                fqv7.onAttributesInitialized();
                fqv7.onChildrenAdded();
                fqv fqv8 = fqv.checkOut();
                fqv8.setElementMap(fyy_03);
                fqv8.setHeight(4);
                fqv8.setPosition(frk_0.m);
                fqv8.setTexture(this.a.c("themeDefault"));
                fqv8.setWidth(1);
                fqv8.setX(117);
                fqv8.setY(18);
                fbm_22.addBasicElement(fqv8);
                fqv8.onAttributesInitialized();
                fqv8.onChildrenAdded();
                fqv fqv9 = fqv.checkOut();
                fqv9.setElementMap(fyy_03);
                fqv9.setHeight(13);
                fqv9.setPosition(frk_0.h);
                fqv9.setTexture(this.a.c("themeDefault"));
                fqv9.setWidth(1);
                fqv9.setX(105);
                fqv9.setY(5);
                fbm_22.addBasicElement(fqv9);
                fqv9.onAttributesInitialized();
                fqv9.onChildrenAdded();
                fbm_22.onChildrenAdded();
                fby_2 fby_22 = fby_2.checkOut();
                fby_22.setElementMap(fyy_03);
                fby_22.setEnabled(true);
                fby_22.setScaled(true);
                fqd_02.addBasicElement(fby_22);
                fby_22.onAttributesInitialized();
                fqv fqv10 = fqv.checkOut();
                fqv10.setElementMap(fyy_03);
                fqv10.setHeight(2);
                fqv10.setPosition(frk_0.i);
                fqv10.setTexture(this.a.c("themeDefault"));
                fqv10.setWidth(11);
                fqv10.setX(106);
                fqv10.setY(16);
                fby_22.addBasicElement(fqv10);
                fqv10.onAttributesInitialized();
                fqv10.onChildrenAdded();
                fby_22.onChildrenAdded();
                fqv fqv11 = fqv.checkOut();
                fqv11.setElementMap(fyy_03);
                fqv11.setHeight(5);
                fqv11.setPosition(frk_0.i);
                fqv11.setTexture(this.a.c("themeDefault"));
                fqv11.setWidth(11);
                fqv11.setX(106);
                fqv11.setY(9);
                fqd_02.addBasicElement(fqv11);
                fqv11.onAttributesInitialized();
                fqv11.onChildrenAdded();
                fqd_02.onChildrenAdded();
                fvE fvE8 = (fvE)fyb_03;
                fqd_0 fqd_03 = (fqd_0)fvE8.getAppearance();
                fqd_03.setElementMap(fyy_03);
                fqd_03.setState("mouseHover");
                fyb_03.addBasicElement(fqd_03);
                fqd_03.onAttributesInitialized();
                fbc_1 fbc_12 = new fbc_1();
                fbc_12.onCheckOut();
                fbc_12.setElementMap(fyy_03);
                fbc_12.setEnabled(false);
                fqd_03.addBasicElement(fbc_12);
                fbc_12.onAttributesInitialized();
                fqv fqv12 = fqv.checkOut();
                fqv12.setElementMap(fyy_03);
                fqv12.setHeight(4);
                fqv12.setPosition(frk_0.a);
                fqv12.setTexture(this.a.c("themeOver"));
                fqv12.setWidth(1);
                fqv12.setX(105);
                fqv12.setY(1);
                fbc_12.addBasicElement(fqv12);
                fqv12.onAttributesInitialized();
                fqv12.onChildrenAdded();
                fqv fqv13 = fqv.checkOut();
                fqv13.setElementMap(fyy_03);
                fqv13.setHeight(4);
                fqv13.setPosition(frk_0.c);
                fqv13.setTexture(this.a.c("themeOver"));
                fqv13.setWidth(11);
                fqv13.setX(106);
                fqv13.setY(1);
                fbc_12.addBasicElement(fqv13);
                fqv13.onAttributesInitialized();
                fqv13.onChildrenAdded();
                fqv fqv14 = fqv.checkOut();
                fqv14.setElementMap(fyy_03);
                fqv14.setHeight(4);
                fqv14.setPosition(frk_0.e);
                fqv14.setTexture(this.a.c("themeOver"));
                fqv14.setWidth(1);
                fqv14.setX(117);
                fqv14.setY(1);
                fbc_12.addBasicElement(fqv14);
                fqv14.onAttributesInitialized();
                fqv14.onChildrenAdded();
                fqv fqv15 = fqv.checkOut();
                fqv15.setElementMap(fyy_03);
                fqv15.setHeight(13);
                fqv15.setPosition(frk_0.j);
                fqv15.setTexture(this.a.c("themeOver"));
                fqv15.setWidth(1);
                fqv15.setX(105);
                fqv15.setY(5);
                fbc_12.addBasicElement(fqv15);
                fqv15.onAttributesInitialized();
                fqv15.onChildrenAdded();
                fqv fqv16 = fqv.checkOut();
                fqv16.setElementMap(fyy_03);
                fqv16.setHeight(4);
                fqv16.setPosition(frk_0.q);
                fqv16.setTexture(this.a.c("themeOver"));
                fqv16.setWidth(1);
                fqv16.setX(105);
                fqv16.setY(17);
                fbc_12.addBasicElement(fqv16);
                fqv16.onAttributesInitialized();
                fqv16.onChildrenAdded();
                fqv fqv17 = fqv.checkOut();
                fqv17.setElementMap(fyy_03);
                fqv17.setHeight(4);
                fqv17.setPosition(frk_0.o);
                fqv17.setTexture(this.a.c("themeOver"));
                fqv17.setWidth(11);
                fqv17.setX(106);
                fqv17.setY(18);
                fbc_12.addBasicElement(fqv17);
                fqv17.onAttributesInitialized();
                fqv17.onChildrenAdded();
                fqv fqv18 = fqv.checkOut();
                fqv18.setElementMap(fyy_03);
                fqv18.setHeight(4);
                fqv18.setPosition(frk_0.m);
                fqv18.setTexture(this.a.c("themeOver"));
                fqv18.setWidth(1);
                fqv18.setX(117);
                fqv18.setY(18);
                fbc_12.addBasicElement(fqv18);
                fqv18.onAttributesInitialized();
                fqv18.onChildrenAdded();
                fqv fqv19 = fqv.checkOut();
                fqv19.setElementMap(fyy_03);
                fqv19.setHeight(13);
                fqv19.setPosition(frk_0.h);
                fqv19.setTexture(this.a.c("themeOver"));
                fqv19.setWidth(1);
                fqv19.setX(105);
                fqv19.setY(5);
                fbc_12.addBasicElement(fqv19);
                fqv19.onAttributesInitialized();
                fqv19.onChildrenAdded();
                fbc_12.onChildrenAdded();
                fby_2 fby_23 = fby_2.checkOut();
                fby_23.setElementMap(fyy_03);
                fby_23.setEnabled(false);
                fby_23.setScaled(true);
                fqd_03.addBasicElement(fby_23);
                fby_23.onAttributesInitialized();
                fqv fqv20 = fqv.checkOut();
                fqv20.setElementMap(fyy_03);
                fqv20.setHeight(2);
                fqv20.setPosition(frk_0.i);
                fqv20.setTexture(this.a.c("themeOver"));
                fqv20.setWidth(11);
                fqv20.setX(106);
                fqv20.setY(16);
                fby_23.addBasicElement(fqv20);
                fqv20.onAttributesInitialized();
                fqv20.onChildrenAdded();
                fby_23.onChildrenAdded();
                fqv fqv21 = fqv.checkOut();
                fqv21.setElementMap(fyy_03);
                fqv21.setHeight(5);
                fqv21.setPosition(frk_0.i);
                fqv21.setTexture(this.a.c("themeOver"));
                fqv21.setWidth(11);
                fqv21.setX(106);
                fqv21.setY(9);
                fqd_03.addBasicElement(fqv21);
                fqv21.onAttributesInitialized();
                fqv21.onChildrenAdded();
                fqd_03.onChildrenAdded();
                fvE fvE9 = (fvE)fyb_03;
                fqd_0 fqd_04 = (fqd_0)fvE9.getAppearance();
                fqd_04.setElementMap(fyy_03);
                fqd_04.setState("pressed");
                fyb_03.addBasicElement(fqd_04);
                fqd_04.onAttributesInitialized();
                fbc_1 fbc_13 = new fbc_1();
                fbc_13.onCheckOut();
                fbc_13.setElementMap(fyy_03);
                fbc_13.setEnabled(false);
                fqd_04.addBasicElement(fbc_13);
                fbc_13.onAttributesInitialized();
                fqv fqv22 = fqv.checkOut();
                fqv22.setElementMap(fyy_03);
                fqv22.setHeight(4);
                fqv22.setPosition(frk_0.a);
                fqv22.setTexture(this.a.c("themePressed"));
                fqv22.setWidth(1);
                fqv22.setX(105);
                fqv22.setY(1);
                fbc_13.addBasicElement(fqv22);
                fqv22.onAttributesInitialized();
                fqv22.onChildrenAdded();
                fqv fqv23 = fqv.checkOut();
                fqv23.setElementMap(fyy_03);
                fqv23.setHeight(4);
                fqv23.setPosition(frk_0.c);
                fqv23.setTexture(this.a.c("themePressed"));
                fqv23.setWidth(11);
                fqv23.setX(106);
                fqv23.setY(1);
                fbc_13.addBasicElement(fqv23);
                fqv23.onAttributesInitialized();
                fqv23.onChildrenAdded();
                fqv fqv24 = fqv.checkOut();
                fqv24.setElementMap(fyy_03);
                fqv24.setHeight(4);
                fqv24.setPosition(frk_0.e);
                fqv24.setTexture(this.a.c("themePressed"));
                fqv24.setWidth(1);
                fqv24.setX(117);
                fqv24.setY(1);
                fbc_13.addBasicElement(fqv24);
                fqv24.onAttributesInitialized();
                fqv24.onChildrenAdded();
                fqv fqv25 = fqv.checkOut();
                fqv25.setElementMap(fyy_03);
                fqv25.setHeight(13);
                fqv25.setPosition(frk_0.j);
                fqv25.setTexture(this.a.c("themePressed"));
                fqv25.setWidth(1);
                fqv25.setX(105);
                fqv25.setY(5);
                fbc_13.addBasicElement(fqv25);
                fqv25.onAttributesInitialized();
                fqv25.onChildrenAdded();
                fqv fqv26 = fqv.checkOut();
                fqv26.setElementMap(fyy_03);
                fqv26.setHeight(4);
                fqv26.setPosition(frk_0.q);
                fqv26.setTexture(this.a.c("themePressed"));
                fqv26.setWidth(1);
                fqv26.setX(105);
                fqv26.setY(17);
                fbc_13.addBasicElement(fqv26);
                fqv26.onAttributesInitialized();
                fqv26.onChildrenAdded();
                fqv fqv27 = fqv.checkOut();
                fqv27.setElementMap(fyy_03);
                fqv27.setHeight(4);
                fqv27.setPosition(frk_0.o);
                fqv27.setTexture(this.a.c("themePressed"));
                fqv27.setWidth(11);
                fqv27.setX(106);
                fqv27.setY(18);
                fbc_13.addBasicElement(fqv27);
                fqv27.onAttributesInitialized();
                fqv27.onChildrenAdded();
                this.a(fbc_13);
                this.b(fbc_13);
                fbc_13.onChildrenAdded();
                this.c(fqd_04);
                this.d(fqd_04);
                fqd_04.onChildrenAdded();
            }
            fyg_02.onChildrenAdded();
        }
        fqj2.onChildrenAdded();
    }

    public fyo a(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(4);
        fqv2.setPosition(frk_0.m);
        fqv2.setTexture(this.a.c("themePressed"));
        fqv2.setWidth(1);
        fqv2.setX(117);
        fqv2.setY(18);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo b(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(13);
        fqv2.setPosition(frk_0.h);
        fqv2.setTexture(this.a.c("themePressed"));
        fqv2.setWidth(1);
        fqv2.setX(105);
        fqv2.setY(5);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo c(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_02);
        fby_22.setEnabled(false);
        fby_22.setScaled(true);
        fyo2.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(2);
        fqv2.setPosition(frk_0.i);
        fqv2.setTexture(this.a.c("themePressed"));
        fqv2.setWidth(11);
        fqv2.setX(106);
        fqv2.setY(16);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fby_22.onChildrenAdded();
        return fby_22;
    }

    public fyo d(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(5);
        fqv2.setPosition(frk_0.i);
        fqv2.setTexture(this.a.c("themePressed"));
        fqv2.setWidth(11);
        fqv2.setX(106);
        fqv2.setY(9);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }
}

