/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from eaf
 */
public class eaf_1
implements fyn_0 {
    private fyw_0 a;
    private Stack<fyy_0> b = new Stack();

    @Override
    public void a(fyy_0 fyy_02, fyw_0 fyw_02, fvE fvE2) {
        this.a = fyw_02;
        this.b.push(fyy_02);
        fyy_0 fyy_03 = this.b.peek();
        fvE fvE3 = fvE2;
        fvE fvE4 = fvE2;
        fqd_0 fqd_02 = (fqd_0)fvE4.getAppearance();
        fqd_02.setElementMap(fyy_03);
        fqd_02.setState("default");
        fvE2.addBasicElement(fqd_02);
        fqd_02.onAttributesInitialized();
        fqn fqn2 = fqn.checkOut();
        fqn2.setRenderer(fpm_0.b().g().d("fontDefault10Bold"));
        fqn2.setElementMap(fyy_03);
        fqd_02.addBasicElement(fqn2);
        fqn2.onAttributesInitialized();
        fqn2.onChildrenAdded();
        fqg_0 fqg_02 = fqg_0.checkOut();
        fqg_02.setElementMap(fyy_03);
        fqg_02.setColor(new fyr_0("defaultLightColor"));
        fqd_02.addBasicElement(fqg_02);
        fqg_02.onAttributesInitialized();
        fqg_02.onChildrenAdded();
        String string = "upArrowIcon";
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fqv2);
        }
        fqv2.setHeight(10);
        fqv2.setPosition(frk_0.i);
        fqv2.setTexture(this.a.c("themeSimple"));
        fqv2.setWidth(12);
        fqv2.setX(333);
        fqv2.setY(431);
        fqd_02.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        String string2 = "buttonFlatBackgroundDefault";
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fby_22);
        }
        fby_22.setScaled(true);
        fqd_02.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_03);
        fqv3.setHeight(7);
        fqv3.setPosition(frk_0.i);
        fqv3.setTexture(this.a.c("themeDefault"));
        fqv3.setWidth(1);
        fqv3.setX(298);
        fqv3.setY(3);
        fby_22.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fby_22.onChildrenAdded();
        String string3 = "buttonFlatBorderDefault";
        fbc_1 fbc_12 = new fbc_1();
        fbc_12.onCheckOut();
        fbc_12.setElementMap(fyy_03);
        if (fyy_03 != null && string3 != null) {
            fyy_03.a(string3, fbc_12);
        }
        fqd_02.addBasicElement(fbc_12);
        fbc_12.onAttributesInitialized();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_03);
        fqv4.setHeight(3);
        fqv4.setPosition(frk_0.a);
        fqv4.setTexture(this.a.c("themeDefault"));
        fqv4.setWidth(3);
        fqv4.setX(291);
        fqv4.setY(0);
        fbc_12.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_03);
        fqv5.setHeight(3);
        fqv5.setPosition(frk_0.c);
        fqv5.setTexture(this.a.c("themeDefault"));
        fqv5.setWidth(1);
        fqv5.setX(298);
        fqv5.setY(0);
        fbc_12.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_03);
        fqv6.setHeight(3);
        fqv6.setPosition(frk_0.e);
        fqv6.setTexture(this.a.c("themeDefault"));
        fqv6.setWidth(3);
        fqv6.setX(303);
        fqv6.setY(0);
        fbc_12.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_03);
        fqv7.setHeight(7);
        fqv7.setPosition(frk_0.h);
        fqv7.setTexture(this.a.c("themeDefault"));
        fqv7.setWidth(3);
        fqv7.setX(291);
        fqv7.setY(3);
        fbc_12.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_03);
        fqv8.setHeight(7);
        fqv8.setPosition(frk_0.j);
        fqv8.setTexture(this.a.c("themeDefault"));
        fqv8.setWidth(3);
        fqv8.setX(303);
        fqv8.setY(3);
        fbc_12.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_03);
        fqv9.setHeight(3);
        fqv9.setPosition(frk_0.m);
        fqv9.setTexture(this.a.c("themeDefault"));
        fqv9.setWidth(3);
        fqv9.setX(291);
        fqv9.setY(11);
        fbc_12.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_03);
        fqv10.setHeight(3);
        fqv10.setPosition(frk_0.o);
        fqv10.setTexture(this.a.c("themeDefault"));
        fqv10.setWidth(1);
        fqv10.setX(298);
        fqv10.setY(11);
        fbc_12.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fqv fqv11 = fqv.checkOut();
        fqv11.setElementMap(fyy_03);
        fqv11.setHeight(3);
        fqv11.setPosition(frk_0.q);
        fqv11.setTexture(this.a.c("themeDefault"));
        fqv11.setWidth(3);
        fqv11.setX(303);
        fqv11.setY(11);
        fbc_12.addBasicElement(fqv11);
        fqv11.onAttributesInitialized();
        fqv11.onChildrenAdded();
        fbc_12.onChildrenAdded();
        fqd_02.onChildrenAdded();
        fvE fvE5 = fvE2;
        fqd_0 fqd_03 = (fqd_0)fvE5.getAppearance();
        fqd_03.setElementMap(fyy_03);
        fqd_03.setState("mouseHover");
        fvE2.addBasicElement(fqd_03);
        fqd_03.onAttributesInitialized();
        String string4 = "buttonFlatBackgroundOver";
        fby_2 fby_23 = fby_2.checkOut();
        fby_23.setElementMap(fyy_03);
        if (fyy_03 != null && string4 != null) {
            fyy_03.a(string4, fby_23);
        }
        fby_23.setScaled(true);
        fqd_03.addBasicElement(fby_23);
        fby_23.onAttributesInitialized();
        fqv fqv12 = fqv.checkOut();
        fqv12.setElementMap(fyy_03);
        fqv12.setHeight(7);
        fqv12.setPosition(frk_0.i);
        fqv12.setTexture(this.a.c("themeOver"));
        fqv12.setWidth(1);
        fqv12.setX(298);
        fqv12.setY(3);
        fby_23.addBasicElement(fqv12);
        fqv12.onAttributesInitialized();
        fqv12.onChildrenAdded();
        fby_23.onChildrenAdded();
        String string5 = "buttonFlatBorderOver";
        fbc_1 fbc_13 = new fbc_1();
        fbc_13.onCheckOut();
        fbc_13.setElementMap(fyy_03);
        if (fyy_03 != null && string5 != null) {
            fyy_03.a(string5, fbc_13);
        }
        fqd_03.addBasicElement(fbc_13);
        fbc_13.onAttributesInitialized();
        fqv fqv13 = fqv.checkOut();
        fqv13.setElementMap(fyy_03);
        fqv13.setHeight(3);
        fqv13.setPosition(frk_0.a);
        fqv13.setTexture(this.a.c("themeOver"));
        fqv13.setWidth(3);
        fqv13.setX(291);
        fqv13.setY(0);
        fbc_13.addBasicElement(fqv13);
        fqv13.onAttributesInitialized();
        fqv13.onChildrenAdded();
        fqv fqv14 = fqv.checkOut();
        fqv14.setElementMap(fyy_03);
        fqv14.setHeight(3);
        fqv14.setPosition(frk_0.c);
        fqv14.setTexture(this.a.c("themeOver"));
        fqv14.setWidth(1);
        fqv14.setX(298);
        fqv14.setY(0);
        fbc_13.addBasicElement(fqv14);
        fqv14.onAttributesInitialized();
        fqv14.onChildrenAdded();
        fqv fqv15 = fqv.checkOut();
        fqv15.setElementMap(fyy_03);
        fqv15.setHeight(3);
        fqv15.setPosition(frk_0.e);
        fqv15.setTexture(this.a.c("themeOver"));
        fqv15.setWidth(3);
        fqv15.setX(303);
        fqv15.setY(0);
        fbc_13.addBasicElement(fqv15);
        fqv15.onAttributesInitialized();
        fqv15.onChildrenAdded();
        fqv fqv16 = fqv.checkOut();
        fqv16.setElementMap(fyy_03);
        fqv16.setHeight(7);
        fqv16.setPosition(frk_0.h);
        fqv16.setTexture(this.a.c("themeOver"));
        fqv16.setWidth(3);
        fqv16.setX(291);
        fqv16.setY(3);
        fbc_13.addBasicElement(fqv16);
        fqv16.onAttributesInitialized();
        fqv16.onChildrenAdded();
        fqv fqv17 = fqv.checkOut();
        fqv17.setElementMap(fyy_03);
        fqv17.setHeight(7);
        fqv17.setPosition(frk_0.j);
        fqv17.setTexture(this.a.c("themeOver"));
        fqv17.setWidth(3);
        fqv17.setX(303);
        fqv17.setY(3);
        fbc_13.addBasicElement(fqv17);
        fqv17.onAttributesInitialized();
        fqv17.onChildrenAdded();
        fqv fqv18 = fqv.checkOut();
        fqv18.setElementMap(fyy_03);
        fqv18.setHeight(3);
        fqv18.setPosition(frk_0.m);
        fqv18.setTexture(this.a.c("themeOver"));
        fqv18.setWidth(3);
        fqv18.setX(291);
        fqv18.setY(11);
        fbc_13.addBasicElement(fqv18);
        fqv18.onAttributesInitialized();
        fqv18.onChildrenAdded();
        fqv fqv19 = fqv.checkOut();
        fqv19.setElementMap(fyy_03);
        fqv19.setHeight(3);
        fqv19.setPosition(frk_0.o);
        fqv19.setTexture(this.a.c("themeOver"));
        fqv19.setWidth(1);
        fqv19.setX(298);
        fqv19.setY(11);
        fbc_13.addBasicElement(fqv19);
        fqv19.onAttributesInitialized();
        fqv19.onChildrenAdded();
        fqv fqv20 = fqv.checkOut();
        fqv20.setElementMap(fyy_03);
        fqv20.setHeight(3);
        fqv20.setPosition(frk_0.q);
        fqv20.setTexture(this.a.c("themeOver"));
        fqv20.setWidth(3);
        fqv20.setX(303);
        fqv20.setY(11);
        fbc_13.addBasicElement(fqv20);
        fqv20.onAttributesInitialized();
        fqv20.onChildrenAdded();
        fbc_13.onChildrenAdded();
        fqd_03.onChildrenAdded();
        fvE fvE6 = fvE2;
        fqd_0 fqd_04 = (fqd_0)fvE6.getAppearance();
        fqd_04.setElementMap(fyy_03);
        fqd_04.setState("pressed");
        fvE2.addBasicElement(fqd_04);
        fqd_04.onAttributesInitialized();
        String string6 = "buttonFlatBackgroundPressed";
        fby_2 fby_24 = fby_2.checkOut();
        fby_24.setElementMap(fyy_03);
        if (fyy_03 != null && string6 != null) {
            fyy_03.a(string6, fby_24);
        }
        fby_24.setScaled(true);
        fqd_04.addBasicElement(fby_24);
        fby_24.onAttributesInitialized();
        fqv fqv21 = fqv.checkOut();
        fqv21.setElementMap(fyy_03);
        fqv21.setHeight(7);
        fqv21.setPosition(frk_0.i);
        fqv21.setTexture(this.a.c("themePressed"));
        fqv21.setWidth(1);
        fqv21.setX(298);
        fqv21.setY(3);
        fby_24.addBasicElement(fqv21);
        fqv21.onAttributesInitialized();
        fqv21.onChildrenAdded();
        fby_24.onChildrenAdded();
        String string7 = "buttonFlatBorderPressed";
        fbc_1 fbc_14 = new fbc_1();
        fbc_14.onCheckOut();
        fbc_14.setElementMap(fyy_03);
        if (fyy_03 != null && string7 != null) {
            fyy_03.a(string7, fbc_14);
        }
        fqd_04.addBasicElement(fbc_14);
        fbc_14.onAttributesInitialized();
        fqv fqv22 = fqv.checkOut();
        fqv22.setElementMap(fyy_03);
        fqv22.setHeight(3);
        fqv22.setPosition(frk_0.a);
        fqv22.setTexture(this.a.c("themePressed"));
        fqv22.setWidth(3);
        fqv22.setX(291);
        fqv22.setY(0);
        fbc_14.addBasicElement(fqv22);
        fqv22.onAttributesInitialized();
        fqv22.onChildrenAdded();
        fqv fqv23 = fqv.checkOut();
        fqv23.setElementMap(fyy_03);
        fqv23.setHeight(3);
        fqv23.setPosition(frk_0.c);
        fqv23.setTexture(this.a.c("themePressed"));
        fqv23.setWidth(1);
        fqv23.setX(298);
        fqv23.setY(0);
        fbc_14.addBasicElement(fqv23);
        fqv23.onAttributesInitialized();
        fqv23.onChildrenAdded();
        fqv fqv24 = fqv.checkOut();
        fqv24.setElementMap(fyy_03);
        fqv24.setHeight(3);
        fqv24.setPosition(frk_0.e);
        fqv24.setTexture(this.a.c("themePressed"));
        fqv24.setWidth(3);
        fqv24.setX(303);
        fqv24.setY(0);
        fbc_14.addBasicElement(fqv24);
        fqv24.onAttributesInitialized();
        fqv24.onChildrenAdded();
        fqv fqv25 = fqv.checkOut();
        fqv25.setElementMap(fyy_03);
        fqv25.setHeight(7);
        fqv25.setPosition(frk_0.h);
        fqv25.setTexture(this.a.c("themePressed"));
        fqv25.setWidth(3);
        fqv25.setX(291);
        fqv25.setY(3);
        fbc_14.addBasicElement(fqv25);
        fqv25.onAttributesInitialized();
        fqv25.onChildrenAdded();
        fqv fqv26 = fqv.checkOut();
        fqv26.setElementMap(fyy_03);
        fqv26.setHeight(7);
        fqv26.setPosition(frk_0.j);
        fqv26.setTexture(this.a.c("themePressed"));
        fqv26.setWidth(3);
        fqv26.setX(303);
        fqv26.setY(3);
        fbc_14.addBasicElement(fqv26);
        fqv26.onAttributesInitialized();
        fqv26.onChildrenAdded();
        fqv fqv27 = fqv.checkOut();
        fqv27.setElementMap(fyy_03);
        fqv27.setHeight(3);
        fqv27.setPosition(frk_0.m);
        fqv27.setTexture(this.a.c("themePressed"));
        fqv27.setWidth(3);
        fqv27.setX(291);
        fqv27.setY(11);
        fbc_14.addBasicElement(fqv27);
        fqv27.onAttributesInitialized();
        fqv27.onChildrenAdded();
        fqv fqv28 = fqv.checkOut();
        fqv28.setElementMap(fyy_03);
        fqv28.setHeight(3);
        fqv28.setPosition(frk_0.o);
        fqv28.setTexture(this.a.c("themePressed"));
        fqv28.setWidth(1);
        fqv28.setX(298);
        fqv28.setY(11);
        fbc_14.addBasicElement(fqv28);
        fqv28.onAttributesInitialized();
        fqv28.onChildrenAdded();
        fqv fqv29 = fqv.checkOut();
        fqv29.setElementMap(fyy_03);
        fqv29.setHeight(3);
        fqv29.setPosition(frk_0.q);
        fqv29.setTexture(this.a.c("themePressed"));
        fqv29.setWidth(3);
        fqv29.setX(303);
        fqv29.setY(11);
        fbc_14.addBasicElement(fqv29);
        fqv29.onAttributesInitialized();
        fqv29.onChildrenAdded();
        fbc_14.onChildrenAdded();
        fqd_04.onChildrenAdded();
        fvE fvE7 = fvE2;
        fqd_0 fqd_05 = (fqd_0)fvE7.getAppearance();
        fqd_05.setElementMap(fyy_03);
        fqd_05.setState("disabled");
        fvE2.addBasicElement(fqd_05);
        fqd_05.onAttributesInitialized();
        String string8 = "buttonFlatBackgroundDisabled";
        fby_2 fby_25 = fby_2.checkOut();
        fby_25.setElementMap(fyy_03);
        if (fyy_03 != null && string8 != null) {
            fyy_03.a(string8, fby_25);
        }
        fby_25.setScaled(true);
        fqd_05.addBasicElement(fby_25);
        fby_25.onAttributesInitialized();
        fqv fqv30 = fqv.checkOut();
        fqv30.setElementMap(fyy_03);
        fqv30.setHeight(7);
        fqv30.setPosition(frk_0.i);
        fqv30.setTexture(this.a.c("themeDisabled"));
        fqv30.setWidth(1);
        fqv30.setX(298);
        fqv30.setY(3);
        fby_25.addBasicElement(fqv30);
        fqv30.onAttributesInitialized();
        fqv30.onChildrenAdded();
        fby_25.onChildrenAdded();
        String string9 = "buttonFlatBorderDisabled";
        fbc_1 fbc_15 = new fbc_1();
        fbc_15.onCheckOut();
        fbc_15.setElementMap(fyy_03);
        if (fyy_03 != null && string9 != null) {
            fyy_03.a(string9, fbc_15);
        }
        fqd_05.addBasicElement(fbc_15);
        fbc_15.onAttributesInitialized();
        fqv fqv31 = fqv.checkOut();
        fqv31.setElementMap(fyy_03);
        fqv31.setHeight(3);
        fqv31.setPosition(frk_0.a);
        fqv31.setTexture(this.a.c("themeDisabled"));
        fqv31.setWidth(3);
        fqv31.setX(291);
        fqv31.setY(0);
        fbc_15.addBasicElement(fqv31);
        fqv31.onAttributesInitialized();
        fqv31.onChildrenAdded();
        fqv fqv32 = fqv.checkOut();
        fqv32.setElementMap(fyy_03);
        fqv32.setHeight(3);
        fqv32.setPosition(frk_0.c);
        fqv32.setTexture(this.a.c("themeDisabled"));
        fqv32.setWidth(1);
        fqv32.setX(298);
        fqv32.setY(0);
        fbc_15.addBasicElement(fqv32);
        fqv32.onAttributesInitialized();
        fqv32.onChildrenAdded();
        fqv fqv33 = fqv.checkOut();
        fqv33.setElementMap(fyy_03);
        fqv33.setHeight(3);
        fqv33.setPosition(frk_0.e);
        fqv33.setTexture(this.a.c("themeDisabled"));
        fqv33.setWidth(3);
        fqv33.setX(303);
        fqv33.setY(0);
        fbc_15.addBasicElement(fqv33);
        fqv33.onAttributesInitialized();
        fqv33.onChildrenAdded();
        fqv fqv34 = fqv.checkOut();
        fqv34.setElementMap(fyy_03);
        fqv34.setHeight(7);
        fqv34.setPosition(frk_0.h);
        fqv34.setTexture(this.a.c("themeDisabled"));
        fqv34.setWidth(3);
        fqv34.setX(291);
        fqv34.setY(3);
        fbc_15.addBasicElement(fqv34);
        fqv34.onAttributesInitialized();
        fqv34.onChildrenAdded();
        fqv fqv35 = fqv.checkOut();
        fqv35.setElementMap(fyy_03);
        fqv35.setHeight(7);
        fqv35.setPosition(frk_0.j);
        fqv35.setTexture(this.a.c("themeDisabled"));
        fqv35.setWidth(3);
        fqv35.setX(303);
        fqv35.setY(3);
        fbc_15.addBasicElement(fqv35);
        fqv35.onAttributesInitialized();
        fqv35.onChildrenAdded();
        fqv fqv36 = fqv.checkOut();
        fqv36.setElementMap(fyy_03);
        fqv36.setHeight(3);
        fqv36.setPosition(frk_0.m);
        fqv36.setTexture(this.a.c("themeDisabled"));
        fqv36.setWidth(3);
        fqv36.setX(291);
        fqv36.setY(11);
        fbc_15.addBasicElement(fqv36);
        fqv36.onAttributesInitialized();
        fqv36.onChildrenAdded();
        this.a(fbc_15);
        this.b(fbc_15);
        fbc_15.onChildrenAdded();
        fqd_05.onChildrenAdded();
    }

    public fyo a(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(3);
        fqv2.setPosition(frk_0.o);
        fqv2.setTexture(this.a.c("themeDisabled"));
        fqv2.setWidth(1);
        fqv2.setX(298);
        fqv2.setY(11);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }

    public fyo b(fyo fyo2) {
        fyy_0 fyy_02 = this.b.peek();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_02);
        fqv2.setHeight(3);
        fqv2.setPosition(frk_0.q);
        fqv2.setTexture(this.a.c("themeDisabled"));
        fqv2.setWidth(3);
        fqv2.setX(303);
        fqv2.setY(11);
        fyo2.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        return fqv2;
    }
}

