/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from ecM
 */
public class ecm_2
implements fyn_0 {
    private fyw_0 a;
    private Stack<fyy_0> b = new Stack();

    @Override
    public void a(fyy_0 fyy_02, fyw_0 fyw_02, fvE fvE2) {
        this.a = fyw_02;
        this.b.push(fyy_02);
        fyy_0 fyy_03 = this.b.peek();
        fvE fvE3 = fvE2;
        fvE fvE4 = fvE2;
        fqj fqj2 = fvE4.getAppearance();
        fqj2.setElementMap(fyy_03);
        fqj2.setState("default");
        fvE2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fqm_0 fqm_02 = fqm_0.checkOut();
        fqm_02.setElementMap(fyy_03);
        fqm_02.setInsets(new Insets(0, 0, 8, 0));
        fqj2.addBasicElement(fqm_02);
        fqm_02.onAttributesInitialized();
        fqm_02.onChildrenAdded();
        String string = "pmbWhite10";
        fby_2 fby_22 = fby_2.checkOut();
        fby_22.setElementMap(fyy_03);
        if (fyy_03 != null && string != null) {
            fyy_03.a(string, fby_22);
        }
        fby_22.setScaled(true);
        fqj2.addBasicElement(fby_22);
        fby_22.onAttributesInitialized();
        fqv fqv2 = fqv.checkOut();
        fqv2.setElementMap(fyy_03);
        fqv2.setHeight(3);
        fqv2.setPosition(frk_0.a);
        fqv2.setTexture(this.a.c("txWhite10Background"));
        fqv2.setWidth(3);
        fqv2.setX(0);
        fqv2.setY(0);
        fby_22.addBasicElement(fqv2);
        fqv2.onAttributesInitialized();
        fqv2.onChildrenAdded();
        fqv fqv3 = fqv.checkOut();
        fqv3.setElementMap(fyy_03);
        fqv3.setHeight(1);
        fqv3.setPosition(frk_0.h);
        fqv3.setTexture(this.a.c("txWhite10Background"));
        fqv3.setWidth(3);
        fqv3.setX(0);
        fqv3.setY(16);
        fby_22.addBasicElement(fqv3);
        fqv3.onAttributesInitialized();
        fqv3.onChildrenAdded();
        fqv fqv4 = fqv.checkOut();
        fqv4.setElementMap(fyy_03);
        fqv4.setHeight(3);
        fqv4.setPosition(frk_0.m);
        fqv4.setTexture(this.a.c("txWhite10Background"));
        fqv4.setWidth(3);
        fqv4.setX(0);
        fqv4.setY(29);
        fby_22.addBasicElement(fqv4);
        fqv4.onAttributesInitialized();
        fqv4.onChildrenAdded();
        fqv fqv5 = fqv.checkOut();
        fqv5.setElementMap(fyy_03);
        fqv5.setHeight(3);
        fqv5.setPosition(frk_0.c);
        fqv5.setTexture(this.a.c("txWhite10Background"));
        fqv5.setWidth(1);
        fqv5.setX(16);
        fqv5.setY(0);
        fby_22.addBasicElement(fqv5);
        fqv5.onAttributesInitialized();
        fqv5.onChildrenAdded();
        fqv fqv6 = fqv.checkOut();
        fqv6.setElementMap(fyy_03);
        fqv6.setHeight(1);
        fqv6.setPosition(frk_0.i);
        fqv6.setTexture(this.a.c("txWhite10Background"));
        fqv6.setWidth(1);
        fqv6.setX(16);
        fqv6.setY(16);
        fby_22.addBasicElement(fqv6);
        fqv6.onAttributesInitialized();
        fqv6.onChildrenAdded();
        fqv fqv7 = fqv.checkOut();
        fqv7.setElementMap(fyy_03);
        fqv7.setHeight(3);
        fqv7.setPosition(frk_0.o);
        fqv7.setTexture(this.a.c("txWhite10Background"));
        fqv7.setWidth(1);
        fqv7.setX(16);
        fqv7.setY(29);
        fby_22.addBasicElement(fqv7);
        fqv7.onAttributesInitialized();
        fqv7.onChildrenAdded();
        fqv fqv8 = fqv.checkOut();
        fqv8.setElementMap(fyy_03);
        fqv8.setHeight(3);
        fqv8.setPosition(frk_0.e);
        fqv8.setTexture(this.a.c("txWhite10Background"));
        fqv8.setWidth(3);
        fqv8.setX(29);
        fqv8.setY(0);
        fby_22.addBasicElement(fqv8);
        fqv8.onAttributesInitialized();
        fqv8.onChildrenAdded();
        fqv fqv9 = fqv.checkOut();
        fqv9.setElementMap(fyy_03);
        fqv9.setHeight(1);
        fqv9.setPosition(frk_0.j);
        fqv9.setTexture(this.a.c("txWhite10Background"));
        fqv9.setWidth(3);
        fqv9.setX(29);
        fqv9.setY(16);
        fby_22.addBasicElement(fqv9);
        fqv9.onAttributesInitialized();
        fqv9.onChildrenAdded();
        fqv fqv10 = fqv.checkOut();
        fqv10.setElementMap(fyy_03);
        fqv10.setHeight(3);
        fqv10.setPosition(frk_0.q);
        fqv10.setTexture(this.a.c("txWhite10Background"));
        fqv10.setWidth(3);
        fqv10.setX(29);
        fqv10.setY(29);
        fby_22.addBasicElement(fqv10);
        fqv10.onAttributesInitialized();
        fqv10.onChildrenAdded();
        fby_22.onChildrenAdded();
        fqj2.onChildrenAdded();
        fvE fvE5 = fvE2;
        fqj fqj3 = fvE5.getAppearance();
        fqj3.setElementMap(fyy_03);
        fqj3.setState("mouseHover");
        fvE2.addBasicElement(fqj3);
        fqj3.onAttributesInitialized();
        String string2 = "pmbWhite25";
        fby_2 fby_23 = fby_2.checkOut();
        fby_23.setElementMap(fyy_03);
        if (fyy_03 != null && string2 != null) {
            fyy_03.a(string2, fby_23);
        }
        fby_23.setScaled(true);
        fqj3.addBasicElement(fby_23);
        fby_23.onAttributesInitialized();
        fqv fqv11 = fqv.checkOut();
        fqv11.setElementMap(fyy_03);
        fqv11.setHeight(3);
        fqv11.setPosition(frk_0.a);
        fqv11.setTexture(this.a.c("txWhite25Background"));
        fqv11.setWidth(3);
        fqv11.setX(0);
        fqv11.setY(0);
        fby_23.addBasicElement(fqv11);
        fqv11.onAttributesInitialized();
        fqv11.onChildrenAdded();
        fqv fqv12 = fqv.checkOut();
        fqv12.setElementMap(fyy_03);
        fqv12.setHeight(1);
        fqv12.setPosition(frk_0.h);
        fqv12.setTexture(this.a.c("txWhite25Background"));
        fqv12.setWidth(3);
        fqv12.setX(0);
        fqv12.setY(16);
        fby_23.addBasicElement(fqv12);
        fqv12.onAttributesInitialized();
        fqv12.onChildrenAdded();
        fqv fqv13 = fqv.checkOut();
        fqv13.setElementMap(fyy_03);
        fqv13.setHeight(3);
        fqv13.setPosition(frk_0.m);
        fqv13.setTexture(this.a.c("txWhite25Background"));
        fqv13.setWidth(3);
        fqv13.setX(0);
        fqv13.setY(29);
        fby_23.addBasicElement(fqv13);
        fqv13.onAttributesInitialized();
        fqv13.onChildrenAdded();
        fqv fqv14 = fqv.checkOut();
        fqv14.setElementMap(fyy_03);
        fqv14.setHeight(3);
        fqv14.setPosition(frk_0.c);
        fqv14.setTexture(this.a.c("txWhite25Background"));
        fqv14.setWidth(1);
        fqv14.setX(16);
        fqv14.setY(0);
        fby_23.addBasicElement(fqv14);
        fqv14.onAttributesInitialized();
        fqv14.onChildrenAdded();
        fqv fqv15 = fqv.checkOut();
        fqv15.setElementMap(fyy_03);
        fqv15.setHeight(1);
        fqv15.setPosition(frk_0.i);
        fqv15.setTexture(this.a.c("txWhite25Background"));
        fqv15.setWidth(1);
        fqv15.setX(16);
        fqv15.setY(16);
        fby_23.addBasicElement(fqv15);
        fqv15.onAttributesInitialized();
        fqv15.onChildrenAdded();
        fqv fqv16 = fqv.checkOut();
        fqv16.setElementMap(fyy_03);
        fqv16.setHeight(3);
        fqv16.setPosition(frk_0.o);
        fqv16.setTexture(this.a.c("txWhite25Background"));
        fqv16.setWidth(1);
        fqv16.setX(16);
        fqv16.setY(29);
        fby_23.addBasicElement(fqv16);
        fqv16.onAttributesInitialized();
        fqv16.onChildrenAdded();
        fqv fqv17 = fqv.checkOut();
        fqv17.setElementMap(fyy_03);
        fqv17.setHeight(3);
        fqv17.setPosition(frk_0.e);
        fqv17.setTexture(this.a.c("txWhite25Background"));
        fqv17.setWidth(3);
        fqv17.setX(29);
        fqv17.setY(0);
        fby_23.addBasicElement(fqv17);
        fqv17.onAttributesInitialized();
        fqv17.onChildrenAdded();
        fqv fqv18 = fqv.checkOut();
        fqv18.setElementMap(fyy_03);
        fqv18.setHeight(1);
        fqv18.setPosition(frk_0.j);
        fqv18.setTexture(this.a.c("txWhite25Background"));
        fqv18.setWidth(3);
        fqv18.setX(29);
        fqv18.setY(16);
        fby_23.addBasicElement(fqv18);
        fqv18.onAttributesInitialized();
        fqv18.onChildrenAdded();
        fqv fqv19 = fqv.checkOut();
        fqv19.setElementMap(fyy_03);
        fqv19.setHeight(3);
        fqv19.setPosition(frk_0.q);
        fqv19.setTexture(this.a.c("txWhite25Background"));
        fqv19.setWidth(3);
        fqv19.setX(29);
        fqv19.setY(29);
        fby_23.addBasicElement(fqv19);
        fqv19.onAttributesInitialized();
        fqv19.onChildrenAdded();
        fby_23.onChildrenAdded();
        fqj3.onChildrenAdded();
    }
}

