/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from elQ
 */
public class elq_1
implements fyn_0 {
    private fyw_0 a;
    private Stack<fyy_0> b = new Stack();

    @Override
    public void a(fyy_0 fyy_02, fyw_0 fyw_02, fvE fvE2) {
        fbm_2 fbm_22;
        Object object;
        fyb_0 fyb_02;
        fyg_0 fyg_02;
        fyb_0 fyb_03;
        fyb_0 fyb_04;
        fyg_0 fyg_03;
        fyb_0 fyb_05;
        fyb_0 fyb_06;
        fyg_0 fyg_04;
        fyb_0 fyb_07;
        Object object2;
        fyb_0 fyb_08;
        fyb_0 fyb_09;
        fyb_0 fyb_010;
        fvE fvE3;
        this.a = fyw_02;
        this.b.push(fyy_02);
        fyy_0 fyy_03 = this.b.peek();
        fvE fvE4 = fvE2;
        fqj fqj2 = fvE4.getAppearance();
        fqj2.setElementMap(fyy_03);
        fvE2.addBasicElement(fqj2);
        fqj2.onAttributesInitialized();
        fvE fvE5 = fqj2.getParentOfType(fvE.class);
        fvE fvE6 = fvE5.getWidgetByThemeElementName("textEditor", false);
        if (fvE6 != null) {
            fvE3 = fvE6;
            fyb_010 = (fqh_0)fvE3.getAppearance();
            fyb_010.setElementMap(fyy_03);
            ((fqh_0)fyb_010).setAlign(frs_0.f);
            fvE6.addBasicElement(fyb_010);
            fyb_010.onAttributesInitialized();
            fyb_09 = fqn.checkOut();
            ((fqn)fyb_09).setRenderer(fpm_0.b().g().d("fontDefault9Bold"));
            fyb_09.setElementMap(fyy_03);
            fyb_010.addBasicElement(fyb_09);
            fyb_09.onAttributesInitialized();
            fyb_09.onChildrenAdded();
            fyb_08 = fqg_0.checkOut();
            fyb_08.setElementMap(fyy_03);
            ((fqg_0)fyb_08).setColor(new fyr_0("defaultDarkColor"));
            fyb_010.addBasicElement(fyb_08);
            fyb_08.onAttributesInitialized();
            fyb_08.onChildrenAdded();
            object2 = "textEditorLightBorder";
            fyb_07 = new fbc_1();
            ((fbc_1)fyb_07).onCheckOut();
            fyb_07.setElementMap(fyy_03);
            if (fyy_03 != null && object2 != null) {
                fyy_03.a((String)object2, fyb_07);
            }
            fyb_010.addBasicElement(fyb_07);
            fyb_07.onAttributesInitialized();
            fyg_04 = fqv.checkOut();
            fyg_04.setElementMap(fyy_03);
            ((fqv)fyg_04).setHeight(4);
            ((fqv)fyg_04).setPosition(frk_0.a);
            ((fqv)fyg_04).setTexture(this.a.c("themeSimple"));
            ((fqv)fyg_04).setWidth(4);
            ((fqv)fyg_04).setX(396);
            ((fqv)fyg_04).setY(153);
            fyb_07.addBasicElement(fyg_04);
            fyg_04.onAttributesInitialized();
            fyg_04.onChildrenAdded();
            fyb_06 = fqv.checkOut();
            fyb_06.setElementMap(fyy_03);
            ((fqv)fyb_06).setHeight(4);
            ((fqv)fyb_06).setPosition(frk_0.c);
            ((fqv)fyb_06).setTexture(this.a.c("themeSimple"));
            ((fqv)fyb_06).setWidth(20);
            ((fqv)fyb_06).setX(400);
            ((fqv)fyb_06).setY(153);
            fyb_07.addBasicElement(fyb_06);
            fyb_06.onAttributesInitialized();
            fyb_06.onChildrenAdded();
            fyb_05 = fqv.checkOut();
            fyb_05.setElementMap(fyy_03);
            ((fqv)fyb_05).setHeight(4);
            ((fqv)fyb_05).setPosition(frk_0.e);
            ((fqv)fyb_05).setTexture(this.a.c("themeSimple"));
            ((fqv)fyb_05).setWidth(4);
            ((fqv)fyb_05).setX(420);
            ((fqv)fyb_05).setY(153);
            fyb_07.addBasicElement(fyb_05);
            fyb_05.onAttributesInitialized();
            fyb_05.onChildrenAdded();
            fyg_03 = fqv.checkOut();
            fyg_03.setElementMap(fyy_03);
            ((fqv)fyg_03).setHeight(7);
            ((fqv)fyg_03).setPosition(frk_0.j);
            ((fqv)fyg_03).setTexture(this.a.c("themeSimple"));
            ((fqv)fyg_03).setWidth(4);
            ((fqv)fyg_03).setX(420);
            ((fqv)fyg_03).setY(157);
            fyb_07.addBasicElement(fyg_03);
            fyg_03.onAttributesInitialized();
            fyg_03.onChildrenAdded();
            fyb_04 = fqv.checkOut();
            fyb_04.setElementMap(fyy_03);
            ((fqv)fyb_04).setHeight(3);
            ((fqv)fyb_04).setPosition(frk_0.q);
            ((fqv)fyb_04).setTexture(this.a.c("themeSimple"));
            ((fqv)fyb_04).setWidth(4);
            ((fqv)fyb_04).setX(420);
            ((fqv)fyb_04).setY(164);
            fyb_07.addBasicElement(fyb_04);
            fyb_04.onAttributesInitialized();
            fyb_04.onChildrenAdded();
            fyb_03 = fqv.checkOut();
            fyb_03.setElementMap(fyy_03);
            ((fqv)fyb_03).setHeight(3);
            ((fqv)fyb_03).setPosition(frk_0.o);
            ((fqv)fyb_03).setTexture(this.a.c("themeSimple"));
            ((fqv)fyb_03).setWidth(20);
            ((fqv)fyb_03).setX(400);
            ((fqv)fyb_03).setY(164);
            fyb_07.addBasicElement(fyb_03);
            fyb_03.onAttributesInitialized();
            fyb_03.onChildrenAdded();
            fyg_02 = fqv.checkOut();
            fyg_02.setElementMap(fyy_03);
            ((fqv)fyg_02).setHeight(3);
            ((fqv)fyg_02).setPosition(frk_0.m);
            ((fqv)fyg_02).setTexture(this.a.c("themeSimple"));
            ((fqv)fyg_02).setWidth(4);
            ((fqv)fyg_02).setX(396);
            ((fqv)fyg_02).setY(164);
            fyb_07.addBasicElement(fyg_02);
            fyg_02.onAttributesInitialized();
            fyg_02.onChildrenAdded();
            fyb_02 = fqv.checkOut();
            fyb_02.setElementMap(fyy_03);
            ((fqv)fyb_02).setHeight(7);
            ((fqv)fyb_02).setPosition(frk_0.h);
            ((fqv)fyb_02).setTexture(this.a.c("themeSimple"));
            ((fqv)fyb_02).setWidth(4);
            ((fqv)fyb_02).setX(396);
            ((fqv)fyb_02).setY(157);
            fyb_07.addBasicElement(fyb_02);
            fyb_02.onAttributesInitialized();
            fyb_02.onChildrenAdded();
            fyb_07.onChildrenAdded();
            object = "textEditorLightBackground";
            fbm_22 = fby_2.checkOut();
            fbm_22.setElementMap(fyy_03);
            if (fyy_03 != null && object != null) {
                fyy_03.a((String)object, fbm_22);
            }
            ((fby_2)fbm_22).setScaled(true);
            fyb_010.addBasicElement(fbm_22);
            fbm_22.onAttributesInitialized();
            fqv fqv2 = fqv.checkOut();
            fqv2.setElementMap(fyy_03);
            fqv2.setHeight(7);
            fqv2.setPosition(frk_0.i);
            fqv2.setTexture(this.a.c("themeSimple"));
            fqv2.setWidth(20);
            fqv2.setX(400);
            fqv2.setY(157);
            fbm_22.addBasicElement(fqv2);
            fqv2.onAttributesInitialized();
            fqv2.onChildrenAdded();
            fbm_22.onChildrenAdded();
            fyb_010.onChildrenAdded();
        }
        if ((fyb_010 = (fvE3 = fqj2.getParentOfType(fvE.class)).getWidgetByThemeElementName("increaseButton", false)) != null) {
            fyb_09 = (fvE)fyb_010;
            fyb_08 = (fqd_0)((fvE)fyb_09).getAppearance();
            fyb_08.setElementMap(fyy_03);
            ((fqj)fyb_08).setState("default");
            fyb_010.addBasicElement(fyb_08);
            fyb_08.onAttributesInitialized();
            object2 = fqv.checkOut();
            ((fyb_0)object2).setElementMap(fyy_03);
            ((fqv)object2).setHeight(9);
            ((fqv)object2).setPosition(frk_0.i);
            ((fqv)object2).setTexture(this.a.c("themeDefault"));
            ((fqv)object2).setWidth(17);
            ((fqv)object2).setX(322);
            ((fqv)object2).setY(32);
            fyb_08.addBasicElement((fyo)object2);
            ((fyo)object2).onAttributesInitialized();
            ((fyb_0)object2).onChildrenAdded();
            fyb_08.onChildrenAdded();
            fyb_07 = (fvE)fyb_010;
            fyg_04 = (fqd_0)((fvE)fyb_07).getAppearance();
            fyg_04.setElementMap(fyy_03);
            ((fqj)fyg_04).setState("mouseHover");
            fyb_010.addBasicElement(fyg_04);
            fyg_04.onAttributesInitialized();
            fyb_06 = fqv.checkOut();
            fyb_06.setElementMap(fyy_03);
            ((fqv)fyb_06).setHeight(9);
            ((fqv)fyb_06).setPosition(frk_0.i);
            ((fqv)fyb_06).setTexture(this.a.c("themeOver"));
            ((fqv)fyb_06).setWidth(17);
            ((fqv)fyb_06).setX(322);
            ((fqv)fyb_06).setY(32);
            fyg_04.addBasicElement(fyb_06);
            fyb_06.onAttributesInitialized();
            fyb_06.onChildrenAdded();
            fyg_04.onChildrenAdded();
            fyb_05 = (fvE)fyb_010;
            fyg_03 = (fqd_0)((fvE)fyb_05).getAppearance();
            fyg_03.setElementMap(fyy_03);
            ((fqj)fyg_03).setState("disabled");
            fyb_010.addBasicElement(fyg_03);
            fyg_03.onAttributesInitialized();
            fyb_04 = fqv.checkOut();
            fyb_04.setElementMap(fyy_03);
            ((fqv)fyb_04).setHeight(9);
            ((fqv)fyb_04).setPosition(frk_0.i);
            ((fqv)fyb_04).setTexture(this.a.c("themeDisabled"));
            ((fqv)fyb_04).setWidth(17);
            ((fqv)fyb_04).setX(322);
            ((fqv)fyb_04).setY(32);
            fyg_03.addBasicElement(fyb_04);
            fyb_04.onAttributesInitialized();
            fyb_04.onChildrenAdded();
            fyg_03.onChildrenAdded();
            fyb_03 = (fvE)fyb_010;
            fyg_02 = (fqd_0)((fvE)fyb_03).getAppearance();
            fyg_02.setElementMap(fyy_03);
            ((fqj)fyg_02).setState("pressed");
            fyb_010.addBasicElement(fyg_02);
            fyg_02.onAttributesInitialized();
            fyb_02 = fqv.checkOut();
            fyb_02.setElementMap(fyy_03);
            ((fqv)fyb_02).setHeight(9);
            ((fqv)fyb_02).setPosition(frk_0.i);
            ((fqv)fyb_02).setTexture(this.a.c("themePressed"));
            ((fqv)fyb_02).setWidth(17);
            ((fqv)fyb_02).setX(322);
            ((fqv)fyb_02).setY(32);
            fyg_02.addBasicElement(fyb_02);
            fyb_02.onAttributesInitialized();
            fyb_02.onChildrenAdded();
            fyg_02.onChildrenAdded();
        }
        if ((fyb_08 = ((fvE)(fyb_09 = fqj2.getParentOfType(fvE.class))).getWidgetByThemeElementName("decreaseButton", false)) != null) {
            object2 = (fvE)fyb_08;
            fyb_07 = (fqd_0)((fvE)object2).getAppearance();
            fyb_07.setElementMap(fyy_03);
            ((fqj)fyb_07).setState("default");
            fyb_08.addBasicElement(fyb_07);
            fyb_07.onAttributesInitialized();
            fyg_04 = fqv.checkOut();
            fyg_04.setElementMap(fyy_03);
            ((fqv)fyg_04).setHeight(9);
            ((fqv)fyg_04).setPosition(frk_0.i);
            ((fqv)fyg_04).setTexture(this.a.c("themeDefault"));
            ((fqv)fyg_04).setWidth(17);
            ((fqv)fyg_04).setX(322);
            ((fqv)fyg_04).setY(43);
            fyb_07.addBasicElement(fyg_04);
            fyg_04.onAttributesInitialized();
            fyg_04.onChildrenAdded();
            fyb_07.onChildrenAdded();
            fyb_06 = (fvE)fyb_08;
            fyb_05 = (fqd_0)((fvE)fyb_06).getAppearance();
            fyb_05.setElementMap(fyy_03);
            ((fqj)fyb_05).setState("mouseHover");
            fyb_08.addBasicElement(fyb_05);
            fyb_05.onAttributesInitialized();
            fyg_03 = fqv.checkOut();
            fyg_03.setElementMap(fyy_03);
            ((fqv)fyg_03).setHeight(9);
            ((fqv)fyg_03).setPosition(frk_0.i);
            ((fqv)fyg_03).setTexture(this.a.c("themeOver"));
            ((fqv)fyg_03).setWidth(17);
            ((fqv)fyg_03).setX(322);
            ((fqv)fyg_03).setY(43);
            fyb_05.addBasicElement(fyg_03);
            fyg_03.onAttributesInitialized();
            fyg_03.onChildrenAdded();
            fyb_05.onChildrenAdded();
            fyb_04 = (fvE)fyb_08;
            fyb_03 = (fqd_0)((fvE)fyb_04).getAppearance();
            fyb_03.setElementMap(fyy_03);
            ((fqj)fyb_03).setState("disabled");
            fyb_08.addBasicElement(fyb_03);
            fyb_03.onAttributesInitialized();
            fyg_02 = fqv.checkOut();
            fyg_02.setElementMap(fyy_03);
            ((fqv)fyg_02).setHeight(9);
            ((fqv)fyg_02).setPosition(frk_0.i);
            ((fqv)fyg_02).setTexture(this.a.c("themeDisabled"));
            ((fqv)fyg_02).setWidth(17);
            ((fqv)fyg_02).setX(322);
            ((fqv)fyg_02).setY(43);
            fyb_03.addBasicElement(fyg_02);
            fyg_02.onAttributesInitialized();
            fyg_02.onChildrenAdded();
            fyb_03.onChildrenAdded();
            fyb_02 = (fvE)fyb_08;
            object = (fqd_0)((fvE)fyb_02).getAppearance();
            ((fyb_0)object).setElementMap(fyy_03);
            ((fqj)object).setState("pressed");
            fyb_08.addBasicElement((fyo)object);
            ((fyo)object).onAttributesInitialized();
            fbm_22 = fqv.checkOut();
            fbm_22.setElementMap(fyy_03);
            ((fqv)fbm_22).setHeight(9);
            ((fqv)fbm_22).setPosition(frk_0.i);
            ((fqv)fbm_22).setTexture(this.a.c("themePressed"));
            ((fqv)fbm_22).setWidth(17);
            ((fqv)fbm_22).setX(322);
            ((fqv)fbm_22).setY(43);
            ((fyo)object).addBasicElement(fbm_22);
            fbm_22.onAttributesInitialized();
            fbm_22.onChildrenAdded();
            ((fyb_0)object).onChildrenAdded();
        }
        fqj2.onChildrenAdded();
    }
}

