/*
 * Decompiled with CFR 0.152.
 */
public final class YN {
    public static final String a = "themes";
    public static final String b = "selectedTheme";
    public static final String c = "themes/config.properties";
    public static final String d = "theme.xml";
    public static final String e = "theme";
    public static final String f = "theme/colors/colors.xml";
    public static final String g = "theme_autoGenerated";
    public static final String h = "theme/appSkin/";
    public static final String i = "^theme_[\\w-]{1,20}$";
    public static final String j = "-";
    public static final String k = "theme";
    public static final String l = "name";
    public static final String m = "author";
    public static final String n = "version";
    public static final String o = "wakfuVersion";
    public static final String p = "date";
    public static final String q = "description";
    public static final int r = 30;
    public static final int s = 300;

    private YN() {
    }
}

